### ISSUE TITLE
Progress Circle in Menu

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#1031]
- [ ] Need: Required data for progress circle. 
- [ ] Show Progress

# Notes
- A check is complete when something is selected and the user clicks "Save and Continue" 
- In the home screen, we will also need a cumulative progress for a whole tool. The information from this issue may help with that.

**Comment by cckozie** [comment]
The progress is updated when the user selects the translated text, not when the user clicks Save and Continue.

**Comment by cckozie** [comment]
Waiting to see if the timing of the save is addressed in issue #1181 being worked on.

**Comment by cckozie** [comment]
In 0.6.15, the progress circle is updated when the selection is made, but it is not persisted until the user clicks Save and Continue (or Previous).
Is that the behavior we want @benjore ?

**Comment by cckozie** [comment]
My app must have been in a weird state when I tested this before, because now I am seeing that the selection and progress is persisted before clicking Save and Continue
