### ISSUE TITLE
Font sizes in Helps

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#1035]
Get mockups from Thomas with correct font sizes. 

- [ ] Make font sizes match mock-ups.

**Comment by Thajny** [comment]
![fonts](https://cloud.githubusercontent.com/assets/21183377/24724701/c1fb566e-1a11-11e7-82d3-b942617aa2bc.png)

**Comment by Thajny** [comment]
Note: Top Menu is also included in the 14pt font size, both regular and bold

**Comment by Thajny** [comment]
![fonts](https://cloud.githubusercontent.com/assets/21183377/24764748/fc07cad2-1aba-11e7-961d-0a309ad4b640.png)
