### ISSUE TITLE
Change the pop-over type for displaying Greek information

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#1037]
- [ ] Make the pop-over click with root close
- [ ] Remove the pipe after the Greek word in the pop-over

https://react-bootstrap.github.io/components.html#popovers
Use: "Click w/ rootClose"

**Comment by mannycolon** [comment]
This issue was a lot more complicated than expected. 

The react bootstrap  component handles its own state and in our implementation in tC we handle the state, which eliminated the benefit we wanted to add by using Click w/ rootClose.

**Comment by mannycolon** [comment]
https://github.com/translationCoreApps/ScripturePane/pull/32
