### ISSUE TITLE
Implement new top menu

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#1038]
- [ ] Implement Design. Connecting it up to its final destination can happen later

**Comment by Thajny** [comment]
![menus](https://cloud.githubusercontent.com/assets/21183377/24726689/db3cbac6-1a18-11e7-85d9-25a6ad1d8e7f.png)

**Comment by Thajny** [comment]
![menus](https://cloud.githubusercontent.com/assets/21183377/24726709/ea93f020-1a18-11e7-85f2-7670910b5eac.png)
