### ISSUE TITLE
Scripture Pane Language selection not always showing properly

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#1066]
Via @klappy: The root issue is that this is statically set and does not update when you change languages.
Target Language should and must always be tied to the currently loaded project manifest, not static.

**Comment by cdwhitfield73** [comment]
I did several tests on this with the most current code base and this bug no longer exists.  This issue should be completed and closed.

**Comment by klappy** [comment]
I see this issue on a few of my projects...
Here's one of them:
https://git.door43.org/klappy/tvs_tit_text_reg

**Comment by klappy** [comment]
@cdwhitfield73 @mannycolon:
To get this to display correctly, I had to manually delete my moduleSettings.json file inside of ~/Library/App.../translationCore/. Then it hit me what was going on. It is being set once and then not being updated when we checkout a new project, which can likely have a different target language. 

So the root issue is that this is statically set and does not update when you change languages.
Target Language should and must always be tied to the currently loaded project manifest, not static.
