### ISSUE TITLE
Side Menu Modifications

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#1068]
- [x] Make the expand/collapse chevron buttons the same size
- [x] Make the expand/collapse chevron a different color as the menu
- [x] Make the sub-menu a different color than the main menu
- [x] Make the Bible references left aligned under the check title (add a left gutter for the icons)

**Comment by Thajny** [comment]
![sidebar thing](https://cloud.githubusercontent.com/assets/21183377/24926900/bf8a4966-1ec2-11e7-9768-e92b14315aa4.png)
