### ISSUE TITLE
Unable To Change Tools

### ISSUE THREAD

**Issue by RoyalSix** [unfoldingWord/translationCore#1072]

**Comment by benjore** [comment]
Works going from tW -> tN, but not tN -> tW

**Comment by klappy** [comment]
@RoyalSix: Here's what is currently happening for me... tN populates the groupIndex. when switching to tW, it keeps the existing groupIndex in state and overwrites the ImportantWords/index.json file with the tN data.

**Comment by RoyalSix** [comment]
Blocked by #1132

**Comment by cckozie** [comment]
Dup
