### ISSUE TITLE
VerseCheck: Target Language modal not displaying Right-to-Left correctly

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#1097]
<img width="1280" alt="screen shot 2017-04-17 at 10 21 13 pm" src="https://cloud.githubusercontent.com/assets/118073/25111960/3380600a-23bc-11e7-8a99-e11226e92db2.png">

**Comment by EllDoubleYew** [comment]
OOPS, misread this story... Just did this for the scripture pane modal by accident. Will do this story next.

see https://github.com/unfoldingWord-dev/translationCore/issues/1101 for what I accidentally did 😅

**Comment by cckozie** [comment]
Chapter/Verse order needs to be switched (RTL) too when displaying RTL languages.
3:14 for us would be 14:3 in RTL languages.
Issue #1308 addresses this generically for other panels.
