### ISSUE TITLE
Creating Builds

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#11]
Builds are crucial for non-developers, including demos, QA and field testing.

**Comment by ihoegen** [comment]
I've got a build system setup, but I need to bring back gulp...

**Comment by ihoegen** [comment]
At the current moment, I am trying to figure out how to avoid using babel-register. It isn't working with the build. It needs to be compiled and bundled into a single file. @EvanWiederspan or @therealsamf would you guys have any suggestions? I used the gulp file from previously, but I ran into an issue with the request module.

**Comment by therealsamf** [comment]
Don't bundle the modules, use Babel-register only for those. Probably should ask Chris where he would want the modules to go, like in their own repos maybe

**Comment by therealsamf** [comment]
Once you remove the modules I'm pretty sure most of the node module requires within the modules will break. Each module might need a 'node_module' folder and package.json

**Comment by klappy** [comment]
As a Product Owner, this is music to my ears. It is important to hear what issues this affects and asking for input for direction because you know what it affects future development.

Modules do need to go into their own repo, but that leads to a new epic and user stories.

The topic of removing modules/apps from the tC codebase and each module/app being in its own repo has come up quite a few times when exploring this with other development teams.

Here are my thoughts so far:
- tC has **no** apps/modules in the code base. 
- Each tC app has its own repo and lifecycle.
- We finalize tC API spec 1.0 and don't make any breaking changes to the API.
- Each app needs to define which API spec version that is being used for compatibility checks.
- We allow adding of tC apps just like adding a project, by git URL or release URL from github.
- We can ship tC with links to approved tC apps that can be downloaded with a click.
- Eventually add a way to browse and search for tC apps.

**Comment by klappy** [comment]
I'm assuming we can make a folder inside the "Translation Core" folder that is created for tC Apps, and another for projects. 

What do you guys think of that?

**Comment by RoyalSix** [comment]
This sounds really good, so modular! We would also need to add a new field to every module that has its version so that we can check if there is a newer one available when retrieving it from git. I'm assuming you do not want to download the modules from git on every app launch.
It looks like we wouldn't need to change much in the workflow in terms of the way we retrieve modules, just more loading screens.

**Comment by ihoegen** [comment]
This works fine if the project stays as a JavaScript project and is not compiled down and packaged with an electron builder. But I keep running into issues with the compilation, and I wonder if there's another solution besides building with electron
