### ISSUE TITLE
Show Target Language in Proper Direction in Expanded Scripture Pane

### ISSUE THREAD

**Issue by EllDoubleYew** [unfoldingWord/translationCore#1101]
> As a checker I want the expanded scripture pane to have my text displayed in the correct direction when I am looking at it in fullscreen.

**Comment by cckozie** [comment]
Chapter/Verse order needs to be switched (RTL) too when displaying RTL languages.
3:14 for us would be 14:3 in RTL languages.
Issue #1308 addresses this generically for other panels.
