### ISSUE TITLE
When in edit mode, after editing verse, the changes are saved when checkbox is selected rather than when "Save Changes" is selected

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#1105]
Via @klappy: This issue was masking the fact that VerseEdits is not updating the application state's copy of the verse. Now that this is removed, and not using VerseCheck's state to display the update, the edit looks like it did not take, but it did in the filesystem.

**Comment by cckozie** [comment]
Where in the file system are these saved?
