### ISSUE TITLE
In edit mode, require a checkbox to be selected before "Save Changes" can be clicked

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#1108]
- [x] If a user tries to click "Save Changes" without selecting a checkbox, show a modal that says "Please indicate what type of edit this is by selecting a checkbox." Include a simple "Close" button.

**Comment by benjore** [comment]
If it takes longer than a 1, ask Manny :)

**Comment by cckozie** [comment]
It works now. The problem was handled in issue #1177
