### ISSUE TITLE
Browse Door43 projects broken

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord/translationCore#1118]
when clicked Browse door43 projects got the follwoing bug 
<img width="1280" alt="screen shot 2017-04-18 at 9 43 17 pm" src="https://cloud.githubusercontent.com/assets/17072300/25159805/327d621a-2480-11e7-90a4-1667ffcec168.png">

```
Uncaught (in promise) TypeError: Cannot read property 'split' of undefined
    at /Users/mannycolon/dev/translationCore/src/js/components/core/login/GogsApi.js:122:31
    at Array.map (native)
    at /Users/mannycolon/dev/translationCore/src/js/components/core/login/GogsApi.js:121:29
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by EllDoubleYew** [comment]
@mannycolon this only happens when I click "refresh" when I am not logged in. Does this work for you when you are logged in? 

We should probably just remove the refresh and back buttons when you are not logged in.
