### ISSUE TITLE
Importing Door43 Project Doesn't work

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#1133]
When importing a project from Door43, clicking the load button just sits there even though it downloaded the project to the filesystem.

**Comment by cckozie** [comment]
There is no indication that anything is happening after the Load Project button is clicked. On my Windows machine it takes about 10 seconds to download Ephesians, and during that time it just sits there. Eventually the snackbar message of ready to use or only Ephesians and Titus is briefly displayed.
At a minimum there needs to be a spinning wheel displayed during the download. Better would be a modal dialog with description of what is happening as well as a progress bar. (future release)
Also, the snackbar message dialog should eventually be replaced with a success dialog that is more intrusive. (future release)

**Comment by cckozie** [comment]
On hold waiting for a build in which I can import from door43.

**Comment by cckozie** [comment]
Importing from door43 works for the most part. There are still a few issues, but they are written up in other issues.
