### ISSUE TITLE
tW Not Loading Projects Other Than Tit/Eph

### ISSUE THREAD

**Issue by RoyalSix** [unfoldingWord/translationCore#1136]
In Dev mode all project books should work

**Comment by ihoegen** [comment]
@RoyalSix I'm having trouble recreating this, is there a specific project that this does not work on?

**Comment by ihoegen** [comment]
translationWords loads the project Luke, but right now it hangs for an extended period of time.

**Comment by ihoegen** [comment]
@RoyalSix No luck recreating, have tried three different books now

**Comment by mannycolon** [comment]
<img width="1280" alt="screen shot 2017-04-20 at 10 00 34 pm" src="https://cloud.githubusercontent.com/assets/17072300/25259557/d7297dfe-2614-11e7-9fa4-67bb5cf51475.png">

**Comment by mannycolon** [comment]
@ihoegen @RoyalSix this is an example but using tN

**Comment by mannycolon** [comment]
- it happens when switching from tW to tN
- also when opening the project the first time

**Comment by mannycolon** [comment]
here is the project i used https://git.door43.org/klappy/zh_1th_text_ulb_l1

**Comment by ihoegen** [comment]
@mannycolon Is the issue that console log? If so, that's just because a filter does not exist. It's a debugging thing, and I can remove it and make a PR

**Comment by RoyalSix** [comment]
I fixed this issue in my last PR for tN

**Comment by RoyalSix** [comment]
@mannycolon You are using tN this issue is for tW. And I can't recreate it either.
