### ISSUE TITLE
tC fails silently when loading projects without finished chunks

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord/translationCore#1138]
we either need to add better error checking and display a message or generate the finished chunks and save it to the manifest as we used to do in the past.

**Comment by mannycolon** [comment]
@klappy @benjore

**Comment by ihoegen** [comment]
@mannycolon Did the thing that updates the finished chunks get removed from the app? If so, I can add it back.

**Comment by mannycolon** [comment]
@ihoegen yes we should added back.

**Comment by cckozie** [comment]
How are supposed to deal with "undone" chunks? TBD, we need a new story to deal with that.
