### ISSUE TITLE
Fix build issues that block testing

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#1155]
- [x] Known issue is capitalization mismatch in VerseCheck.
- [x] Include tC_apps other than just translationWords and translationNotes. Not issue.
- [x] Find out why commits were behind on build.
- [x] ./css/style vs ./css/Style
- [x] Fix update version script.
- [x] Fix closing dialog for skipping checks.
- [x] Fix Tests.
- [ ] Check for more and add as necessary.

**Comment by klappy** [comment]
@ihoegen: How do we add the other tC_apps submodules for travis to build them?

**Comment by ihoegen** [comment]
@klappy Just add them to the repo, travis pulls them in using `git pull --recursive` so all submodules are included
