### ISSUE TITLE
Screen real estate problem on open project work screen on my Lenovo laptop (11e, 11.5 inch screen)

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1168]
![image](https://cloud.githubusercontent.com/assets/8171759/25356812/41ee79ac-2901-11e7-97bd-4a9cd1759e65.png)

**Comment by cckozie** [comment]
This is much better in 0.6.18, but there is no space between the Save and Continue button and the task bar. Waiting to see if this gets fixed after the buttons have been restyled.

**Comment by cckozie** [comment]
Now the main buttons are completely hidden by the task bar. (My display resolution is 1366x738)
![image](https://cloud.githubusercontent.com/assets/8171759/25674103/52c8cb74-2fff-11e7-9eb3-c6d17d556f8b.png)

**Comment by benjore** [comment]
#1473 is related

**Comment by benjore** [comment]
Use flex on the tools that go into the tools container

**Comment by cdwhitfield73** [comment]
Full overhaul of tools container done, implementing flex.  All elements, including the save buttons, will now fit nicely on the smallest screen size and will grow to fill larger screens.

**Comment by cckozie** [comment]
The buttons are now accessible on the screen.
Several other issues were introduced with this fix. See #1645
