### ISSUE TITLE
It is not intuitive how to unselect something in the Select box

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1170]
The pointing finger is not a traditional way of indicating that clicking there will undo my selection. Plus, on a slow machine there is a noticeable delay after clicking before the selection is removed. I don't know if we need a "Clear selection" button, or a right click menu, or something else, but I am not comfortable with it the way it is.

**Comment by klappy** [comment]
A delay is a sign of something going wrong behind the scenes that is taking too long. We can look into what is slowing it down in addition to changing the cursor type. Any preferences on the cursor type?

**Comment by benjore** [comment]
Will be taken care of by #1721
