### ISSUE TITLE
The tC installation on Windows needs work

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1174]
It does not feel anything like a normal Windows application install. None of the normal dialogs, e.g. copyright, where to install, option to create a desktop icon, progress bar, are displayed. Instead I just see the animated tC icon with no information about what is happening. Eventually the animated icon goes away and nothing happens for several seconds leaving the user wondering. There is also no way to cancel out of the installation process.

**Comment by benjore** [comment]
- [ ] Talk to Joel and see what he's doing with tS Desktop

# Notes
- Inno is used for tS
