### ISSUE TITLE
Problems created by force closing the app

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1175]
After having to force close the app because of the problem in issue , I accidentally relaunched the installer because it's icon was on my desktop and the real tC icon was hidden under other windows. I then killed the installer from the taskbar. When I opened tC, the project I was working on was gone and it displayed this screen:
![image](https://cloud.githubusercontent.com/assets/8171759/25358648/cc3012d2-2907-11e7-9fef-cfbe14addb9d.png)

**Comment by cckozie** [comment]
Actually, it looks like this is from an old version of the app even though I previously did an uninstall before loading the current build.

**Comment by cdwhitfield73** [comment]
It seems like this might be an outdated issue.  Moving to QA for analysis.

**Comment by cckozie** [comment]
This is so old and I've not experienced anything like it lately, so I'm going to just move it on.
