### ISSUE TITLE
There should be some verbiage and a progress bar during the load of a project/tool combo

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1176]
Currently there is just the animated icon which animates for about half of the time it takes to load the project.

**Comment by benjore** [comment]
- [x] Add a "spinning wheel"
- [x] Where to add
  - [x] Downloading a project #1232 #1360
  - [x] Uploading a project
  - [x] Loading a project
  - [x] [anything that takes longer than ~1 second]

**Comment by cckozie** [comment]
When opening a project on my slow Windows machine I see this:
![image](https://cloud.githubusercontent.com/assets/8171759/25641355/4c80c1a0-2f59-11e7-974b-8a655c4af1a3.png)
The percentage displayed quickly gets to some number, usually in about 2-3 seconds on an Eph. project, then stays there while it takes another 15 seconds or so to finish loading the project. 
Also note that the "logo" displayed is not the tC logo.

**Comment by benjore** [comment]
#1401 is a dup of this

**Comment by klappy** [comment]
Most of this should be addressed now. There are a few issues around the percentage and progress circle that I wonder if it is worth hiding it until we can get them resolved. Behind the scenes we are using 100% of our CPU to do the work, and the updating of the progress is queued up after the work is done. We would have to do a lot of work to make this and it could take days potentially a week to address it. 

We have spent a few days already on this issue in previous versions of the progress. 

Should we hide it and fix it later or invest a few days to address it now?

**Comment by mannycolon** [comment]
@benjore @cckozie I agree with @klappy

**Comment by cckozie** [comment]
@benjore @klappy @mannycolon 
1. It is "better" now since the progress bar has been taken away so that I'm not seeing an inaccurate indicate of how close this process is to finishing. (I see in 0.6.22 that the progress wheel is back sometimes, but the % number that it displays is not consistent with the % displayed in the progress wheel.
2. When I am in my Eph/tN project and change the tool to tW, there is no indication that anything is happening for the 23 seconds it takes to load. No modal or any type of work/progress is indicated. Once the tW project is opened, the system performance has been significantly degraded. When I click on a check in the menu, it takes anywhere from 3 to 10 seconds before the app responds to that click. After a while the performance does improve.
3. Do we really want to release something to the field that shows an icon with the text "logo" running around the circumference of a circle while the project is loading?
4. Loading Matthew with tW takes 28 seconds on my field grade computer which gives me 28 seconds to wonder if it's just slow or broken. (Ephesians takes 16 seconds)
5. In the case of the Matthew/tW project, even after the project appears to have loaded and I can see the checking screen behind the Loading... modal, the modal stays on the screen and I can't dismiss it or doing anything else with tC. All I can do is force close the app.
If I wait for another 6 minutes, eventually the entire tC window goes to white and all I see is the Windows tC menu bar at the top.

I am personally not comfortable releasing something to the field with these kinds of issues even if we are technically only supporting Ephesians and Titus.

**Comment by mannycolon** [comment]
@cckozie @benjore I did some work this morning to help render the spinning logo instead of just the `logo verbiage `. However this won't be fixed until i fully implement #1499

**Comment by cckozie** [comment]
@mannycolon - Something else to watch for when working on this and the fetching issues:
Many/most times when changing tools the loading screen does not come up at all, or if it does, it doesn't come up until after the project has been loaded. On my Windows field machine, that is about 24 seconds during which there is no indication that anything is happening.

**Comment by cckozie** [comment]
It is much now without the progress indicator so the user isn't confused about how much is left, but the tC icon still does not show. It is still the circling "logo" image.
![image](https://cloud.githubusercontent.com/assets/8171759/26258479/5f832084-3c8a-11e7-8fc2-55ee9fd0adf2.png)

![image](https://cloud.githubusercontent.com/assets/8171759/26257095/e8b0fdfa-3c84-11e7-97c4-39a38c6cc4d0.png)

**Comment by mannycolon** [comment]
@ihoegen when we make a  build do we do anything with the path that may affect including images in a component???

**Comment by mannycolon** [comment]
@ihoegen I've tried two different implementations to import the image in the loader and it's not finding it in the builds unlike in develop which works fine.

**Comment by cckozie** [comment]
No change in 0.6.26.5 - Still seeing the "logo" image rather than the tC icon.

**Comment by mannycolon** [comment]
@cckozie what error did you get on the console for this?? was it different than before ??

**Comment by cckozie** [comment]
@mannycolon ![image](https://cloud.githubusercontent.com/assets/8171759/26322618/d505b288-3ef9-11e7-93af-0176e0815b1f.png)
file:///Applications/translationCore.app/Contents/Resources/app.asar/images/TC_icon.png

**Comment by cckozie** [comment]
The progress indicator has been removed.
The rotating tC logo and "Loading..." text now are good.
