### ISSUE TITLE
The Skip or Close modal doesn't work.

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1177]
When attempting to move backward of forward without making a text selection, the modal that is displayed does not close when the CLOSE button is clicked. Also, nothing happens when the SKIP button is clicked.

**Comment by klappy** [comment]
This should be addressed in v0.6.13 and above.
https://github.com/unfoldingWord-dev/translationCore/releases/tag/v0.6.13

**Comment by cckozie** [comment]
I am passing this issue because the functionality does work, but the buttons do not comply with the design standards. Creating a new issue for that.
