### ISSUE TITLE
We should provide some indication to the user that the app is loading (Windows)

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1178]
On my slower Windows machine it takes about 19 seconds for the app to launch. During that time the small spinning wheel is displayed a couple of time for a second or two, but most of the time there is no indication that anything is happening. When the user launches the app we should provide some immediate and continuous feedback that the app is in fact launching.

**Comment by benjore** [comment]
- [ ] Add a splash screen with a progress bar
