### ISSUE TITLE
The coloring on the project list screen is confusing

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1179]
I have 3 projects on my machine. When the project list page is displayed, the first and third project names are displayed against the white background of the dialog, and the second project name is displayed against a gray background. My first inclination is that the second project is currently selected. If we use alternating color as background in this list, neither of the colors should be the same as the rest of the dialog's background color. Alternately, or in addition, I think it would be good to extend the separator lines currently by the Open and Sync buttons all the way across the dialog.

**Comment by Thajny** [comment]
![my projects blank 2](https://cloud.githubusercontent.com/assets/21183377/25492132/b3a173a0-2b37-11e7-8aa4-f749a79ef287.png)

**Comment by cdwhitfield73** [comment]
@benjore Do you want me to use this color scheme to style the other two tabs too?  Do you want/need Thomas to do a mock up of those tabs first? Is there a separate issue for the other tabs?

**Comment by cdwhitfield73** [comment]
I think this issue should include the entire modal, because even the top bar with the tabs is completely different than what we have.

**Comment by benjore** [comment]
This is a color scheme for all three tabs. If you need specifics, ask. If not, do your best to replicate this style on teh other two tabs as well.

**Comment by cdwhitfield73** [comment]
It's not EXACTLY like the mock up above, but there are good reasons for most of the differences, and I think for now it might fall into the category of "good enough" since we are going to change it soon anyway.

**Comment by mannycolon** [comment]
i cant access the close button
<img width="1280" alt="screen shot 2017-04-28 at 9 51 58 pm" src="https://cloud.githubusercontent.com/assets/17072300/25552017/ffedd17e-2c5c-11e7-983c-0c2ba4d82955.png">

**Comment by mannycolon** [comment]
#1362 
<img width="1280" alt="screen shot 2017-04-28 at 9 49 29 pm" src="https://cloud.githubusercontent.com/assets/17072300/25552020/0b62f58e-2c5d-11e7-81e7-f42c8a71e77d.png">

**Comment by cckozie** [comment]
I am passing this issue because the defined issue has been addressed, but I created a new issue (issue #1404) to fix problems when the user has a smaller screen.
