### ISSUE TITLE
Inconsistencies in when changes are commited

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1181]
If I highlight text, immediately it shows the checkmark icon next to the check. The same is true for bookmarking the check. If I enter a Comment, I need to actually click the Save Changes button in order for that to be saved. That is also true if I edit the text. As far as I can tell, clicking the Save and Continue or the Save and Previous buttons don't actually save anything. I believe this is very confusing.

**Comment by benjore** [comment]
- [ ] Only add the green checkmark when save & continue (or save & previous) is clicked (and the highlight has been made)

## Note
- Bookmarks appears as soon as clicked (not waiting until "Save & Continue" is clicked)

**Comment by mannycolon** [comment]
@benjore @klappy As I remeber, when we spoke about this issue in the past. we debated whether we should remove the word save from the navigation buttons (`save & previous` and `save & continue`). and have a separate save button in the action area of verseCheck component.

I just believe we should talk this further before we implement it.

**Comment by cckozie** [comment]
Should be handled in new UI issues
