### ISSUE TITLE
It doesn't make sense to have buttons indicating something will be saved when the user hasn't done anything that needs to be saved

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1182]

**Comment by benjore** [comment]
- [ ] "Save & Continue"
  - [ ] When no highlights have been made, this button should display "Skip" (preferably with the same style as the current "Save & Previous"
  - [ ] When a highlight has been made, the button turns into "Save & Continue", appearing exactly as it currently does. 
- [ ] "Save & Previous"
  - [ ] When no highlights have been made, this button should display "Previous"
  - [ ] When a highlight has been made, the button turns into "Save & Previous", appearing exactly as it currently does.

**Comment by Thajny** [comment]
![tranlsationwords full scrip 24](https://cloud.githubusercontent.com/assets/21183377/25441357/9956cdd6-2a67-11e7-97c5-b4f872e65024.png)
![tranlsationwords full scrip 28](https://cloud.githubusercontent.com/assets/21183377/25441358/9957349c-2a67-11e7-9f2a-f582c17c0779.png)

**Comment by benjore** [comment]
Covered in #1688
