### ISSUE TITLE
The style guide standards for buttons are not followed on the project check screen

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1184]
The Save and Continue button may follow the standard, but the others, including in the Comment and Edit dialogs do not.

**Comment by Thajny** [comment]
![ui consistency](https://cloud.githubusercontent.com/assets/21183377/25545843/21844e30-2c26-11e7-877c-94ab301d0f60.png)

**Comment by cdwhitfield73** [comment]
This is basically done, although may need more changes later.  Currently, I have it matching the screen shot above except for the buttons aren't gray when disabled and the green is a different shade.  Both these issues have been discussed with Thomas and he is okay with what I have for now.  Also, I (and a few others) aren't sure about the buttons being yellow, but I left them for now.

**Comment by cckozie** [comment]
I am going to pass this for now, and will add new issues to deal with these:
1. The green and yellow gotta go. Not enough text contrast and contrast between disabled and enabled. Plus they do not fit well with our color scheme and more colors are distracting. (my opinion)
2. The buttons should be reduced in width so that they do not overflow left of the vertical line between the select and edit/comment areas when the window is at our minimum width.
