### ISSUE TITLE
There is no user warning when an edit reason has been checked but no editing has occured

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1191]
There is a user warning when an edit is performed but no reason is checked. The opposite should be true as well.

**Comment by benjore** [comment]
- [x] Make checkboxes disabled until an edit is made
- [x] When a checkbox has been selected, enable the "Save" button
- [ ] pop-up
  - [ ] If a user tries to click a checkbox without a making an edit, a modal should pop up saying "Attention: Please make a change before selecting a checkbox."
  - [ ] Keep the pop-up for "save changes" as is

**Comment by cckozie** [comment]
@benjore The first two items in your list have been implemented. I believe the desired result has been achieved, but it was implemented differently than what you specified in the third item. Is this OK with you? (I think it's fine)
Screenshot when edit is first opened:
![image](https://cloud.githubusercontent.com/assets/8171759/25532768/13527c74-2bf4-11e7-9b54-dbc5653bfc16.png)

Screenshot after edit is made:
![image](https://cloud.githubusercontent.com/assets/8171759/25532810/380269ee-2bf4-11e7-9d59-6117873dead5.png)

Screenshot after clicking a checkbox:
![image](https://cloud.githubusercontent.com/assets/8171759/25532854/5af08c7e-2bf4-11e7-8952-24ea0cceb56b.png)

**Comment by cdwhitfield73** [comment]
There really isn't an easy way to make something happen when a user tries to click something that is disabled.  By default, disabling something removes the ability to click it.  I tried to design the flow well enough that the popup is not necessary.

**Comment by cckozie** [comment]
We determined that this was a good implementation.
