### ISSUE TITLE
The reason is not being saved with the edit

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1193]
Or at least they are not being populated into the dialog when it is reopened.

**Comment by benjore** [comment]
When a user makes an edit, selects a checkbox(s), then saves it, then returns to the edit tab:
- [ ] Retain the last selected checkboxes (the checkboxes will be disabled at this point)
- [ ] When the text is edited and the checkboxes become activate, reset all the checkboxes

**Comment by benjore** [comment]
This will be covered in Edit History
