### ISSUE TITLE
tHelps not rendering properly

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#1207]
Some tHelps articles are not rendering properly. (I used this project: https://git.door43.org/Danjuma_Alfred_H/sw_tit_text_ulb , build 0.6.13) 

![screenshot 2017-04-25 09 55 51](https://cloud.githubusercontent.com/assets/13352518/25392140/7c3af3fa-299d-11e7-9414-bfe86e146726.png)

- [ ] The title is showing up twice. Make it only show up in the title.

**Comment by benjore** [comment]
Might be related to #1264

**Comment by benjore** [comment]
Also not #1282

**Comment by EllDoubleYew** [comment]
![newthelps](https://cloud.githubusercontent.com/assets/7133050/25492723/e94ff36e-2b41-11e7-9aa6-e385197c99f6.png)
This is what it looks like now. Is this okay @benjore

**Comment by cckozie** [comment]
The forward slashes are gone and that text is now italicized, but the title is still showing up as a heading and then again in normal text.

**Comment by EllDoubleYew** [comment]
@cckozie This duplication issue is related to old sources again. Until we decide to refresh all the sources for tN/tW there will be occasional issues with the text in the tHelps pane.

**Comment by cckozie** [comment]
I'm putting a QA Hold label on this one until a decision is made on whether or not the sources will be refreshed before rolling out the release.

**Comment by EllDoubleYew** [comment]
This is confirmed an issue with sources:

So to clarify, we are actually injecting the title of the article at the top of each translationHelps article inside of translationNotes. This can be removed however sometimes the title is not inside of the sources.

So it is really a question of would we rather always have a title and it be duplicated sometimes or would we rather have a title sometimes and sometimes not have it at all. At least with the current sources. 

It would be possible to dynamically check to see if there is a title before we inject a title but this is a reasonably large amount of work. It would also not be perfect, as it would need to be written to include multiple edge cases and depending on the specific formatting of the source it could be thrown off into incorrectly assuming there is/is not already a title on the page. Especially considering it is something that (should*) be remedied with a refresh on sources.

**Comment by benjore** [comment]
@EllDoubleYew I can live with a double title (a big and a little one), I can't live with no title.

**Comment by cckozie** [comment]
Some titles are repeated but I'm not seeing any missing titles in 0.6.24
