### ISSUE TITLE
Highlighting bug

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#1209]
I highlighted `wavivu`. Then when I tried to highlight the following word `na`, the highlight showed up above as per the screenshot. I was unable to highlight the word `na`. (Project: https://git.door43.org/Danjuma_Alfred_H/sw_tit_text_ulb , Build 0.6.13)

![screenshot 2017-04-25 10 00 27](https://cloud.githubusercontent.com/assets/13352518/25392476/5484bf48-299e-11e7-92fd-805b1ff1850a.png)

## Notes: 
- If I highlight `na` first, it works as expected.
- If I highlight the last word `walafi` then `na`, it works as expected.
- Drag to select also works as expected.

**Comment by benjore** [comment]
Happened again a couple checks later trying to highlight the word `wa`. 

![screenshot 2017-04-25 10 05 09](https://cloud.githubusercontent.com/assets/13352518/25392604/a9cf259c-299e-11e7-9dc4-e3dffd8db973.png)

**Comment by cckozie** [comment]
It appears that the noted problem has been fixed. I did uncover another problem while testing. See issue #1577
