### ISSUE TITLE
Fix the wording on the Add Resources dialog

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1210]
The current text is "Select the settings for the scripture source you want to load in to the scripture pane"
"settings" doesn't make sense in context
"in to" should be "into"
Does it need to be this wordy? Does that descriptive sentence need to be there at all?

The label for the dropdown box is "Select source language name"
Wouldn't just "Select Resource" be better?

What is our design standard for capitalization on labels?

**Comment by benjore** [comment]
Title: Add Resources
Instructions: Select source language
Dropdown

**Comment by cckozie** [comment]
I think it would be good to display the actual name of the resource in the dropdown rather than just the abreviation.

**Comment by cdwhitfield73** [comment]
Wording has been changed, select box has been centered, and a close button has been added.

Changing the "EN" to "English" in the dropdown will be a little harder.  This data is being pulled from the manifest and the manifest only contains the slug, not the name.  We will have to do some kind of data lookup to get the name and I am not sure where this info might be.  This should be spun off into its own issue if it is important.

**Comment by cckozie** [comment]
Added issue #1327 to display the actual name of the resource rather than our secret code.
