### ISSUE TITLE
Decide on and implement a standard for Close button and/or "X" on dialogs/modals

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1213]
We need to be consistent on the options given to a user to close dialogs and modals. Some of them currently have just a Close button, some have both a Close button and an "X", and some just have the "X".

**Comment by cdwhitfield73** [comment]
All should now have a close button at the button (in standard blue color scheme) and a close X at the top right, in white (on blue headers) except for the tHelps, which is darker.
