### ISSUE TITLE
Change verbiage on tools' definitions.

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1216]
Current verbiage is "The translationWords check works by providing translators with clear, concise definitions and translation suggestions for every important word in the Bible."

I don't think we should use the words "works by" in the definition. Suggest something like: "The translationWords check provides translators with clear, concise definitions and translation suggestions for every important word in the Bible.

Even better would be to make the definitions more consistent between tN and tW.

**Comment by benjore** [comment]
tW - "A tool to comprehensively check the meaning of all key terms in the Bible using a set of clear, concise definitions and including suggestions for translation."
tN - "A tool to check a wide range of potential translation problems in the Bible, including grammatical constructions and figures of speech that can be difficult to translate, with explanations and suggestions for translation."
