### ISSUE TITLE
Change the text in the instructional part of the checking dialog

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1219]
The verbiage of "Please select the correct translation for: _word/phrase_" remains after the user makes a selection. I suggest that after a select is made the verbiage gets changed to "_selected word/phrase_ has been selected as the correct translation for: _word/phrase_"

**Comment by benjore** [comment]
https://github.com/unfoldingWord-dev/design/issues/141

**Comment by Thajny** [comment]
![select card](https://cloud.githubusercontent.com/assets/21183377/25487979/686d86f0-2b2b-11e7-9c3d-8f9dbd70f1fc.png)

**Comment by benjore** [comment]
- [ ] The instructions stay the way they currently are until a selection is made
- [ ] Once a selection is made, the instruction card changes
  - [ ] On the top (in blue) - what is being checked. This should appear the same as in the highlighted ULB and the check info card
  - [ ] Middle line (in black) - "is translated as:"
  - [ ] Bottom line (in blue) - whatever is highlighted. This portion should be dynamic, so as they highlight/change their highlight, what shows up here should dynamically change to match it.

**Comment by benjore** [comment]
Rendered obsolete by #1748
