### ISSUE TITLE
Make the dialog boxes consistent & conform to the Style Guide

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1222]
Here are some examples in the build 0.6.13

![no link specified](https://cloud.githubusercontent.com/assets/8171759/25399886/79fbc060-29b6-11e7-9fcb-63009fce1cb0.jpg)

![not supported](https://cloud.githubusercontent.com/assets/8171759/25399887/79fc1c18-29b6-11e7-923b-e3e58e9d6f46.jpg)

![attention](https://cloud.githubusercontent.com/assets/8171759/25399884/79fa3b6e-29b6-11e7-9172-b1a45e5b73f3.png)

![selecting](https://cloud.githubusercontent.com/assets/8171759/25399885/79fb121e-29b6-11e7-8fed-ab34052e11d5.png)

**Comment by benjore** [comment]
Also affects #1211 #1212 #1213 
Related to #1184

**Comment by mannycolon** [comment]
@benjore we should have Thomas review this and then we will be able to implement it.

**Comment by cckozie** [comment]
There are still several different formats that we are using for displaying user messages.
@benjore Do we want to do more work on this now?

![login error message](https://cloud.githubusercontent.com/assets/8171759/25765839/aedd2b88-31b4-11e7-9ca9-aaca30eefaf2.PNG)
![only titus error](https://cloud.githubusercontent.com/assets/8171759/25765841/aede684a-31b4-11e7-9bba-0931abf4e377.PNG)
![project ready msg](https://cloud.githubusercontent.com/assets/8171759/25765840/aeddd998-31b4-11e7-9741-95026e7b1aee.PNG)
![skip msg](https://cloud.githubusercontent.com/assets/8171759/25765842/aedef742-31b4-11e7-856b-1243fb32b8fb.PNG)
![unable to connect msg](https://cloud.githubusercontent.com/assets/8171759/25765843/aee0a2d6-31b4-11e7-865c-5940cb961813.PNG)

**Comment by benjore** [comment]
@cckozie Sure. If we're going to do the work, let's make them conform to the style guide.

**Comment by cdwhitfield73** [comment]
Issue #1484 was created to address updating the "Login Failed" dialog example from above.

**Comment by cckozie** [comment]
I am passing this for now. 1484 was created for the login error. I'm accepting the snackbar message for the time being. I will be creating new issues for the circumstances where we can't display the list of the user's door43 projects (no Internet and no Door43 login).
