### ISSUE TITLE
Project sync does not work

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1223]
Nothing happens when I click the button

**Comment by cckozie** [comment]
Dup

**Comment by cckozie** [comment]
Now I'm not sure that it is a dup.
I am signed in as user qa99
I imported project https://git.door43.org/faustin-azaza/en-x-demo1_eph_text_reg, loaded tW, and made a couple of edits
I returned to the projects page and clicked Sync. Nothing appeared to happen. I opened the developers console and see these errors:
![image](https://cloud.githubusercontent.com/assets/8171759/25594060/ca47deb4-2e84-11e7-9f2a-dbc66af167ec.png)

**Comment by mannycolon** [comment]
this now works, however, there's no confirmation of successfully upload. therefore, will work on adding it.

**Comment by mannycolon** [comment]
- [x] add confirmation of successful upload.
- [x] fix upload bug.

**Comment by cckozie** [comment]
If I'm logged in with the door43 user profile used to import the project, when I try to upload the project I get this error message:
![no repo](https://cloud.githubusercontent.com/assets/8171759/25822662/e7f533b0-33fe-11e7-88b2-2a1273ab8c87.PNG)

If I respond with OK to that message, I am presented with this:
![image](https://cloud.githubusercontent.com/assets/8171759/25822807/85b545c2-33ff-11e7-8c7f-ff00c926c1c1.png)

**Comment by mannycolon** [comment]
@cckozie this should be addressed in one of the latest releases.

**Comment by mannycolon** [comment]
@cckozie 
1. that is not an error message. That is a question for the user to respond.
2. @ihoegen do you know why that window message pops up?

**Comment by ihoegen** [comment]
@mannycolon It's a git thing, I'll dig deeper into it, and make it more user friendly

**Comment by ihoegen** [comment]
@mannycolon It should be pushing to git using the user's authentication token, but for some reason, it is not

**Comment by cckozie** [comment]
@mannycolon 1. It should go to the repo of the user who is logged in.

**Comment by ihoegen** [comment]
The issue with that, and the reason the alert comes up, is because they
don't have that repository as their own. We could create a repository as a
default, without any notification.

**Comment by mannycolon** [comment]
@ihoegen i think we should not ask them. we should just create it. what do you think?

**Comment by ihoegen** [comment]
@mannycolon I agree, let's do that then

**Comment by cckozie** [comment]
@mannycolon @ihoegen Why would we create a repo for someone that already has one?

**Comment by mannycolon** [comment]
@ihoegen I need help with this issue

**Comment by mannycolon** [comment]
@ihoegen how can i remove the Windows alert asking for git credentials??

**Comment by cckozie** [comment]
@mannycolon While you're working on this, please also fix the error message that is displayed when logged in to Door43 and the Internet connection is lost and the user then attempts to upload.
![image](https://cloud.githubusercontent.com/assets/8171759/25969154/8398feda-3659-11e7-844d-309321139b15.png)

It probably makes sense to display the same generic message that is shown when the user attempts to download without an Internet connection.
![image](https://cloud.githubusercontent.com/assets/8171759/25969266/f93ee1ae-3659-11e7-99c1-ed2ee0496f94.png)

**Comment by mannycolon** [comment]
@cckozie 
I'm going to move this specific bug to its own issue/story. 


When I'm logged in as a different door43 user I get this error message when I try to upload:
![bad id](https://cloud.githubusercontent.com/assets/8171759/25822703/07e18156-33ff-11e7-812f-ffff1eb6de24.PNG)

**Comment by mannycolon** [comment]
@cckozie and I'm looking into that other bug you just posted.

**Comment by cckozie** [comment]
1. There is no indication during the upload that anything is happening. After clicking the upload button the screen just sits there until the success or failure message is displayed.
2. If the Internet connection is lost during the upload, the message text is "Error Uploading: Unknown error". We should be able to detect that it is an Internet problem and issue that standard message.
3. If an upload is attempted when logged in as a local user the message text is "Error Uploading: Can not find the repository of this user". The message text should be "Error Uploading: You must be logged in with a Door43 account to upload projects".

**Comment by cckozie** [comment]
I'm moving the 3 issues about to a new issue #1582
