### ISSUE TITLE
In Tools, change the "iW" icon to "tW"

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#1226]

**Comment by Thajny** [comment]
<img width="551" alt="translationwords" src="https://cloud.githubusercontent.com/assets/21183377/25406208/93207742-29cb-11e7-95c0-992443c3bae7.png">

**Comment by Thajny** [comment]
<img width="551" alt="translationwords" src="https://cloud.githubusercontent.com/assets/21183377/25406222/9abce6d4-29cb-11e7-8255-57c2c27518c6.png">

**Comment by Thajny** [comment]
![translationwords](https://cloud.githubusercontent.com/assets/21183377/25438108/0d9e3cf6-2a5e-11e7-95dd-0a27881f3e96.png)

**Comment by Thajny** [comment]
![tw circle](https://cloud.githubusercontent.com/assets/21183377/25494058/0947856e-2b3e-11e7-9cfb-98408fc7493f.png)
