### ISSUE TITLE
Fix download from Door43

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#1232]

**Comment by klappy** [comment]
@mannycolon & @benjore: Should there be a new issue about creating commits on every save so that there is something to upload to Door43?

**Comment by cckozie** [comment]
Need a new build to test door43 stuff.

**Comment by cckozie** [comment]
@benjore @klappy @mannycolon 
I don't know what I should be testing on this issue.

**Comment by mannycolon** [comment]
@cckozie importing projects from door43 didn't work before now it does.
