### ISSUE TITLE
There are multiple dialogs for selecting a project

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1235]
One is displayed when I click on the Project link in the "menu bar", a different one is displayed when I click on View/Reload

**Comment by benjore** [comment]
@cckozie I'm not seeing the "View/Reload" Where do you get that?

**Comment by cckozie** [comment]
@benjore 
![screen shot 2017-04-25 at 8 04 50 pm](https://cloud.githubusercontent.com/assets/8171759/25413850/021a6fc8-29f3-11e7-8d0c-03c77e4a6b2c.jpg)
