### ISSUE TITLE
Create user account does not work

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1247]
Nothing happens when I click the Create Account button if no locally detectable errors exist.
If we are not going to support creating an account from within tC, we need to change the Create Account button to a link to the create account feature on door43.

**Comment by benjore** [comment]
Change to a hyperlink that opens in an external web browser. 

https://git.door43.org/user/sign_up

**Comment by cckozie** [comment]
Added issue #1328 to indicate that we're using door43 user accounts.
