### ISSUE TITLE
Improper error message when listing door43 projects if no Internet connection is available

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1257]
Currently returns "No Projects Found"

**Comment by EllDoubleYew** [comment]
@cckozie Would it be sufficient to change this message to say "No Projects Found. Check to make sure you are connected to the internet"?  Or should it explicitly check if the user is in online/offline mode?

**Comment by cckozie** [comment]
@EllDoubleYew If tC is unable to connect to the server (because there is no Internet connection, the server is down, or whatever) it should return an error message stating "Unable to connect to the server. Please check your Internet connection.".
