### ISSUE TITLE
Some links in tHelps open external links

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#1264]
All links to other tHelps articles should only be internal links. 

Example: In Titus, tW tool, Apollos check - there is a link for "How to Translate Names". This should be an internal link, but it opens a web browser instead. 

- [ ] Turn off opening browser 
- [ ] if it is not found, open a window that says, "I'm sorry, this article is not currently available."

**Comment by cckozie** [comment]
Should be fixed in #1207

**Comment by mannycolon** [comment]
@cckozie was this addressed in v0.7.0?

**Comment by cckozie** [comment]
@mannycolon It was partially addressed in 0.7.0. There are some remaining problems.
