### ISSUE TITLE
Disable "Import Local Project"

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#1266]
This can be done by simply removing the tab.

**Comment by klappy** [comment]
Can we keep the Import Local? I still feel that by removing this we are limiting the usability that was expected in the requirements.

**Comment by cdwhitfield73** [comment]
@benjore Am I correct in assuming that the decision is that you want it removed for now?

**Comment by benjore** [comment]
Yes. Remove it for now. We'll bring it back for the next version of tC.
