### ISSUE TITLE
Verbiage changes on Account Information panel

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1269]
![image](https://cloud.githubusercontent.com/assets/8171759/25436026/982973ce-2a57-11e7-85d4-d057be674160.png)
"No email address found" is displayed even though there is an email address for the user on door43.
I do not believe that email addresses appear in the revision history. That phrase should probably be part of the description for the username.

**Comment by benjore** [comment]
- [x] Remove the whole "email" section
