### ISSUE TITLE
The Help sidebar is too long for laptop screens

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1277]
It is hidden behind the taskbar/dock on both Mac and Windows
![image](https://cloud.githubusercontent.com/assets/8171759/25437497/317820e4-2a5c-11e7-8d11-fdaccbcd8334.png)

It is not even viewable when in fullscreen mode
![screen shot 2017-04-26 at 8 57 44 am](https://cloud.githubusercontent.com/assets/8171759/25438437/12be4978-2a5f-11e7-9fba-f9ef17809f2a.jpg)

**Comment by benjore** [comment]
I think the same problem exists with the tHelps pane.

**Comment by EllDoubleYew** [comment]
@benjore @cckozie So I am a big confused with this story. Is this for the menu on the left side of the screen or the tHelps pane on the right side of the screen. I am uncertain of the issues just from looking at the screenshots.

**Comment by cckozie** [comment]
@EllDoubleYew Sorry, I guess I don't know all of your terminology. The problem is with the collapsable pane on the right side of the screen, tHelps I guess.
