### ISSUE TITLE
Different icons used to expand References and Helps pane

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1278]
![image](https://cloud.githubusercontent.com/assets/8171759/25437644/a83c7b62-2a5c-11e7-9011-b70af0821e60.png)
![image](https://cloud.githubusercontent.com/assets/8171759/25438124/1ac51a80-2a5e-11e7-9c47-333c4d04efa0.png)

**Comment by cdwhitfield73** [comment]
@benjore So, which one do you want?

**Comment by benjore** [comment]
I like the 4 arrows better than the one, but the one in the mockups would be even better.
