### ISSUE TITLE
Hide the File, Edit, View, Window, and Help menus on the menu bar

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1283]

**Comment by cckozie** [comment]
Works on Windows but menu bar is still displayed on Mac. (Sorry CW, on second look I was wrong about tS on Mac. It has Edit and View options.)
We'll probably have to remove all of the menus individually.

**Comment by cdwhitfield73** [comment]
@cckozie I talked with Klappy about this yesterday.  Apparently, there is no way to completely remove that bar on a Mac (the OS overrides it).  But I disabled the "custom" menu that we had, so all you are seeing now is the generic options.  Klappy said that was fine.  The only other thing we could do is create a new "custom" menu that removes "most" options, but there will always be "something" that shows up there on a Mac.  But again, Klappy said that was not necessary for now.  We can discuss again and decide whether to pass this or make further changes.

**Comment by cdwhitfield73** [comment]
We think this change did not get fully implemented on the last build.  Please retest.

**Comment by cckozie** [comment]
No change in 0.6.18 OSX
![screen shot 2017-05-02 at 2 55 41 pm](https://cloud.githubusercontent.com/assets/8171759/25636614/8d8a2b9e-2f47-11e7-9686-85a4ffbb07c2.jpg)

**Comment by cdwhitfield73** [comment]
Created a new very stripped out custom menu bar.  You should now only see the "translationCore" option with quit, an "Edit" option with cut, copy and paste, and a "Window" option, with minimize, reload and toggle developer tools.  This is as small as we can make it without losing functionality.

**Comment by cckozie** [comment]
Still seeing more than I should (0.6.20)
![image](https://cloud.githubusercontent.com/assets/8171759/25760396/37604ca6-319c-11e7-89a8-e632ac662cc0.png)

![image](https://cloud.githubusercontent.com/assets/8171759/25760427/5b796df2-319c-11e7-92a7-8c8693509cc7.png)
