### ISSUE TITLE
The displayed list of projects on door43 is not complete for user

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1288]
I uploaded two different 1th projects to door43. I can see them on the Internet and in translationStudio, but they do not appear on the Import Online Project screen. I did click the Refresh button several times and stopped and restarted tC.

**Comment by cckozie** [comment]
It looks like we may be arbitrarily limiting the list to 20 items. On repos with fewer than 20 projects, they all appear in the list. If there are more than 20, the list appears to be truncated.
The API will return a maximum of 50, so that is what we should use.

**Comment by cdwhitfield73** [comment]
internal limit increased from 20 to 50
