### ISSUE TITLE
It is not at all obvious how to get to the screen that allows the user to browse door43 projects and enter a project URL

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1290]
Once there are projects on the computer, it appears that the only way to get back to the browse screen is to click the Back button on the screen that lists the door43 projects.
It may suffice for now to change the text on that button to "Enter URL".
It needs a better fix for future releases.

**Comment by benjore** [comment]
- [x] When "Import Online Project" is clicked, 
  - [x] go directly to their list of projects
  - [x] add the option at the bottom for "Enter URL" + Import Button
- [x] Remove the current "Import Online Project" home page

**Comment by benjore** [comment]
Please note #1310
