### ISSUE TITLE
Move the vertical line in the check info card to line up with Scripture Pane

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#1296]
Please move it over both pixels needed to align it

**Comment by cckozie** [comment]
They are not aligned on my Mac or Windows.
![image](https://cloud.githubusercontent.com/assets/8171759/25533312/df00e594-2bf5-11e7-9904-4a1583c646e2.png)

**Comment by klappy** [comment]
I know we tested this before merging. I wonder if it got undone in a following merge?

**Comment by cdwhitfield73** [comment]
Retest on next build.
