### ISSUE TITLE
Change the verbiage on the warning that a reason code needs to be entered

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1298]
Current text is "Please indicate what type of edit this is by selecting a checkbox."
Change to "Please indicate what type of edit this is by selecting one or more checkboxes." or something similar.

**Comment by cdwhitfield73** [comment]
This whole flow was changed in another issue, so there is no popup dialog anymore with this wording.  It now says something like "Check the reason(s)..." after you make a change and the reasons become enabled.
