### ISSUE TITLE
Feedback does not get sent

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1306]
Entered text into the box and clicked submit. 
Feedback submitted! was displayed, but no issue showed up in github.

**Comment by ihoegen** [comment]
@cckozie Feedback does not open issues in github as of now, only bug reports. Instead, feedback gets sent to a reporting system. @klappy Should we let feedback open issues in Github?

**Comment by cckozie** [comment]
@ihoegen None of the three feedback options are currently (0.6.17) creating issues in github.

**Comment by ihoegen** [comment]
@cckozie my bad, I meant the automated bug reports. No user submitted
feedback comes in to github, only stuff that's under the hood, such as
console errors: all console errors are submitted to github

**Comment by ihoegen** [comment]
@cckozie I've updated the error reporting, now feedback should create issues. This change does not need a new build.

**Comment by cckozie** [comment]
Something is getting to the issues repo now so I am passing this issue. I've added issue #1391 to make it better.
