### ISSUE TITLE
The projects modal needs usability work

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1310]
These problems exist on both the My Projects and Import Online Project tabs

The scroll bar is almost invisible. It should be larger and have more contrast with the background.

Since there is no visual delineation of the extents of the list panel, the average user will think that there is room more more projects on the page and will not think of trying to scroll to see if there are more. There should be a visual delineation of how low the list actually can go. I would suggest using the same lighter gray as on the My Projects, Import Local Projects, etc. bar on the top.

**Comment by Thajny** [comment]
![image 2017-05-02 at 3 30 52 pm](https://cloud.githubusercontent.com/assets/21183377/25637967/688f2a7e-2f4c-11e7-918b-26165c7809e8.png)

**Comment by cckozie** [comment]
0.6.18
There is no scrollbar on either the Projects or Tools tab. The only place the scrollbar is currently shown is on the Import Online Project screen.

**Comment by cdwhitfield73** [comment]
FYI - the version of the scrollbar that we finally decided on looks different than the mock up above

**Comment by cckozie** [comment]
The modal has some sizing issues that I wrote up in issue #1473
