### ISSUE TITLE
Multiple panel sizing issues when app window is reduced in width or height

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1311]
The helps panel gets wider
The reason checkboxes overwrite each other
The icon to add another resource gets shrunk beyond recognition
The Save and Continue button flows out of its panel
![image](https://cloud.githubusercontent.com/assets/8171759/25507991/e2122346-2b74-11e7-8177-fee1cc059277.png)

The resources panel gets too long
Much of the edit panel disappears
![image](https://cloud.githubusercontent.com/assets/8171759/25508195/096b3bb6-2b76-11e7-9d0a-2089c295bd4c.png)

**Comment by cdwhitfield73** [comment]
These issues should be resolved with the flex refactor done in another issue.
