### ISSUE TITLE
Display full resource name in the Add Resource dropdown list

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1327]
Currently we're just displaying what we call the resources; e.g. En (UDB), Greek (UGNT).
That is assuming lots of knowledge on the part of the user, and will probably be confusing to many.

**Comment by benjore** [comment]
Related to #1210

**Comment by benjore** [comment]
Hard code it for now. E.g. "English (Unlocked Literal Bible)" "Greek (Unlocked Greek New Testament)" 

These should appear only in the "Add Resource dropdown list". In the Scripture Pane, it should appear "English (ULB)" "Greek (UGNT)"
