### ISSUE TITLE
Disable Selection in Edit Mode & Comment Mode

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#1336]

**Comment by cckozie** [comment]
Technically "Selection" is disabled when in Edit or Comment mode, but I am able to double click or drag to highlight text in the Select pane. (See image below) The highlighting does disappear when I click in the Edit or Comment box or anywhere else on the screen.
![image](https://cloud.githubusercontent.com/assets/8171759/25920023/1a621bc2-3596-11e7-909f-dbf8204e27c6.png)
