### ISSUE TITLE
Cannot load non-Ephesians/Titus project in developer mode

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1337]
I entered the konami code to get into developer mode, then selected a jhn project. It informs me that my project is ready to load and I need to select a tool, but it also informs me that I need to load a project before I can select a tool. Very confusing!
![screen shot 2017-04-28 at 1 08 04 pm](https://cloud.githubusercontent.com/assets/8171759/25542343/bf2a9842-2c17-11e7-8751-3b55f8129129.jpg)

**Comment by mannycolon** [comment]
@cckozie i believe this bug addressed by my PR #1360
