### ISSUE TITLE
Clean up user experience upon opening app

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1345]
There are a couple of pretty confusing issues that I think we can easily clean up.
1. Since both the Home and User options on the menu bar do the same thing, I suggest we should eliminate the Home option.
2. When the project list is displayed on the main screen it is not obvious that it is possible to import projects or how to do it. I suggest we remove the project list from the main page and replace it with text in the middle of the blank space that states "Click on User:" if no one is signed in, or else "Click on User or Project:". (I think it would be better to also show the menu bar icon associated with the User and Project options in the "click on" messages)
3. If it wouldn't be more work, a better alternative for 2. would be to automatically perform the "clicks" so that the user would never see just that "background" screen.

This would also eliminate the need to fix issue #1342 .

**Comment by benjore** [comment]
- [x] Remove the Projects from the main screen (Projects should only be accessible from within the main modal)
- [x] On the main screen include tC logo + "Welcome to translationCore" + button: "Get Started"
- [x] Keep the Home button in the menu
