### ISSUE TITLE
Once a project is selected, it's full name should be shown in the menu bar

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1346]
In case the user forgot which one he selected, or thinks that his selection didn't work.

**Comment by cdwhitfield73** [comment]
This is working now, don't know when it got fixed.

**Comment by cckozie** [comment]
@cdwhitfield73 My description wasn't very good. The problem is that only the book name is displayed, not the actual project name. I'm throwing this back into prioritized issues.

**Comment by RoyalSix** [comment]
# Overview
If the user is in the project `ilo_luk_text_ulb` they should see that name in the menu bar under heading Project as such `Project: ilo_luk_text_ulb`

# Tasks
  - [ ] Get the project folder name and pipe string down to prop for display
## Tests
- [ ] Write tests to ensure that correct name is being displayed (Worth the test??)
