### ISSUE TITLE
my recent projects not scrolling down to allow access for more projects

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord/translationCore#1362]
I currently have 15 projects and as seen in the picture below I can only access 12 projects because it doesn't scroll down.

<img width="1280" alt="screen shot 2017-04-28 at 9 49 29 pm" src="https://cloud.githubusercontent.com/assets/17072300/25552002/a38c26ba-2c5c-11e7-9b12-fb5e15ec32ea.png">

**Comment by EllDoubleYew** [comment]
This is weird because its given `overflowy:scroll` why would it not scroll @mannycolon ?

**Comment by mannycolon** [comment]
@EllDoubleYew not sure why not. but im sure its not scrolling. maybe there is a nested element that needs the  `overflowy: scroll` property.
