### ISSUE TITLE
Disappearing Checks 

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#1363]
In tW, the first time I load the tool for Ephesians, there are a lot of checks for the word "God" and when I switch checks a few times, or close the app and reload tW, sometimes the category of "God" sometimes does not expand, and other times it just disappears.

**Comment by klappy** [comment]
@ihoegen: I think your fix helps address one of the issues but I think there is one that still remains. My gut tells me it is due to the whole word file contents being included in the checks in groupData. 

My file after switching projects/tools back and forth to Titus/tW, it corrupts the groupData file for God. 

The error I get is: "failed loading group data for god"
and here is the resulting file that it was trying to load:
[click to download: god.json.txt](https://github.com/unfoldingWord-dev/translationCore/files/977648/god.json.txt)

**Comment by ihoegen** [comment]
@klappy Putting the json in a json linter gives me this as an error: 
![image](https://cloud.githubusercontent.com/assets/11003242/25726885/0bd47e8e-30db-11e7-92ba-39e2f488f86f.png)
I don't know much about the data writing/reading process. @mannycolon @RoyalSix could I get some input? I don't think this is caused by the filters

**Comment by klappy** [comment]
There are a few issues here. First something is breaking the json. Second, there is data in the json that shouldn't be there. If we fix both, that's great. We should use the opportunity to fix what's breaking the json and then remove the extra data that should not be in each check. If we remove the extra data first we may not find what is actually breaking the json, but fix the current issue/behavior that we are seeing.

**Comment by ihoegen** [comment]
@klappy I figured it out, there was another instance where case sensitivity was throwing things off

**Comment by cckozie** [comment]
@klappy Do you have a sense for how many times I should switch tools and/or projects without seeing any problems before I could be fairly confident that this problem has been fixed. I have seen the results from random playing around in the past (when I wasn't watching for it), but now after trying to break it after about a dozen times changing project or tool or both, I have not seen any issues.

**Comment by klappy** [comment]
In the past it only took a full rotation of every combination of tW/tN between just two projects and it would cause issues. So I don't think I had to try more than 4 times.

**Comment by cckozie** [comment]
I'm passing this since I haven't seen or been able to reproduce it in the last several builds.
