### ISSUE TITLE
Git is not installed with tC, and the instructions on the warning are unclear

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1364]
Git should be installed with tC, but if it's not, we need to give the user proper instructions to help them get it installed on both Windows and Mac. This is the current error Windows message:
![image](https://cloud.githubusercontent.com/assets/8171759/25580404/4f1548aa-2e46-11e7-969f-788f336c9246.png)

**Comment by cckozie** [comment]
I see now that when I attempt to launch tC again on Windows that it does run the git setup, however, it would be much less confusing for the user if it bypassed all of the screens that give the user options that he probably does not know how to respond to. I believe it would be much better to just automatically launch the git install when necessary, and make it a silent install (no screens offering user options).

**Comment by mannycolon** [comment]
@ihoegen what do you think about this one?

**Comment by ihoegen** [comment]
@mannycolon I don't think I can make it a silent install, it's the official git installer

**Comment by ihoegen** [comment]
@mannycolon Nevermind, figured it out, making a PR

**Comment by mannycolon** [comment]
@ihoegen haha awesome.

**Comment by mannycolon** [comment]
@ihoegen I knew you were the right man for this.

**Comment by mannycolon** [comment]
Lol

**Comment by cckozie** [comment]
Two issues installing on 64 bit Windows 10:
1. On thius dialog, captialize "git" in the first sentence and modify the second sentence to read "Click OK to install Git now."
![install 3](https://cloud.githubusercontent.com/assets/8171759/25640520/6d68fae4-2f55-11e7-831c-18a77e909a70.PNG)

2. After the user clicks OK this error is displayed:
![install 4](https://cloud.githubusercontent.com/assets/8171759/25640539/7e84f45e-2f55-11e7-9b0c-23138a27ba28.PNG)

**Comment by cckozie** [comment]
Works fine in 0.6.19. I also tested with the installation of git not successfully completing, and it automatically ran the git install next time I tried to open tC.
