### ISSUE TITLE
Error message after clicking on a door43 project to import

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1368]
0.6.15
![image](https://cloud.githubusercontent.com/assets/8171759/25581535/05684dda-2e4e-11e7-90e2-5668fa54f006.png)
project https://git.door43.org/qa99/en_tit_text_reg
This project only has text in a single chunk.
Once this error is encounter, this error message is returned for every import I attempt. Had to quit tC and restart it to do further testing.

**Comment by cckozie** [comment]
Different behavior on 0.6.17
Now I can import and open the project, but the main window still appears blank and the checks all indicate "undefined".
![image](https://cloud.githubusercontent.com/assets/8171759/25587953/0014d5c4-2e6c-11e7-9792-a7e650ad8170.png)

**Comment by cckozie** [comment]
I am putting this on QA Hold until issue #1469 is addressed because I think they are probably related.

**Comment by cckozie** [comment]
I am removing the hold because #1469 is still in the Prioritized Issues lane. 
In 0.6.21 I am no longer getting the error message as in my first comment, but after importing and opening this project, when I navigate to the Import Online Projects screen it shows the message "Unable to connect to the server. Please check your Internet connection."
If I then go to the My Projects page and select a valid project to load, it logs me out and takes me to the Sign In page.

**Comment by cdwhitfield73** [comment]
Failed imports now delete the "project" folder that was created, so further attempts to import won't lock up the app.  I think this resolves all the problems with this issue.

**Comment by cckozie** [comment]
I do not believe that this issue had anything to do with failed imports.
Importing the project no longer causes the error message and strange behaviors, but it does still open as an "empty" project in tN. Issue #1536 was created to deal with that problem.
