### ISSUE TITLE
Unable to use tC without good internet

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#1370]
Right now I do not have consistent internet. When I launch tC it logs me out of D43 since it can't connect to the server. I get stuck on the login screen and cannot open a project/tool. This is preventing me from programming on it.

**Comment by EllDoubleYew** [comment]
@klappy Short term solution: disable the requirement to login before loading a project in developer mode. Is this something I should do for right now?

**Comment by benjore** [comment]
- [ ] The user validation should only happen when: 
  - [ ] logging in for the first time
  - [ ] changing user
  - [ ] uploading data
- [ ] The credentials should be stored locally and shouldn't try to reautheticate unless one of the previous actions is attempted

**Comment by cckozie** [comment]
In 0.6.19 I cannot import a project from the Door43 project list even when I am logged in. I am able, though, to import using a URL.

**Comment by cckozie** [comment]
This is fixed in 0.6.20

**Comment by cckozie** [comment]
I am putting this on hold. It needs to be retested/reevaluated after we have implemented the local user option.

**Comment by cckozie** [comment]
Need to test on 0.6.23

**Comment by cckozie** [comment]
I think we're good now with 0.6.23
