### ISSUE TITLE
Update all colors/buttons to conform to global style settings

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#1374]
- [x] Update all colors to global style settings
- [x] Update all buttons to conform to global style settings
- [x] Standardize on HTML/React Bootstrap buttons

**Comment by cdwhitfield73** [comment]
The button portion of this is done.  All buttons are now standard HTML buttons.  We are no longer using React buttons.  All buttons use the global class names for styling.

**Comment by cdwhitfield73** [comment]
I'm pretty sure I've got all the colors updated.  A global search does not find anymore.  This isn't something that will be easy for QA to test.  Nothing to see in the UI, just changing hard coded colors into variable names in the code.

**Comment by cckozie** [comment]
I think this is all good now in 0.6.26.6
