### ISSUE TITLE
Re-importing a project from door43 causes problems

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1382]
Issue 1.
If I re-import a project that I have open, all of the checks go to "undefined" and the text is empty. If I reload the project the checks come back as expected.
Issue 2. 
When I re-import the project, it does not contain changes to the project on the server that were made after the original import from door43.

**Comment by cdwhitfield73** [comment]
This has been resolved for now, in that you can no longer re-import a project at all that you have locally.
