### ISSUE TITLE
Refactor Feedback and Comments

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1391]
Current Github issue created:
![image](https://cloud.githubusercontent.com/assets/8171759/25620156/12acb63c-2f13-11e7-82b5-33ad939ca656.png)

1. Include dropdown list selection rather than labeling all submissions as "Bug Report"
2. Consider moving details from Rollbar to Github
3. Consider user option for contact info
4. Consider sending the feedback to separate repos depending on category selected
5. Don't enable the Submit button until the user has entered some text
6. Replace the "Feedback Submitted!" text in the textbox with a modal that indicates whether or not the feedback was successfully sent.
7. (moved from issue 1393) If a user submits feedback when there is no Internet connection, the app still returns the "Feedback Submitted" message even though it was not submitted. The user should be informed through a user friendly message that the feedback could not be submitted because there was no access to the Internet, and that he should retry after establishing a connection.

**Comment by benjore** [comment]
Add tC version #, OS version, project, tool, etc. whatever we know that might be helpful.

**Comment by benjore** [comment]
Superseded by #2963 .
