### ISSUE TITLE
Logo Not Shown When Loading Tool

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/translationCore#1401]
In v0.6.18 when loading a tool the splash screen doesn't show the logo, instead it shows "logo" spinning.  The initial app load launch screen does work correctly.

See screenshot:
![screen shot 2017-05-02 at 11 43 46 am](https://cloud.githubusercontent.com/assets/107731/25631134/b5283f08-2f2c-11e7-962d-9a0da9b23a96.png)

**Comment by benjore** [comment]
Dup of #1176
