### ISSUE TITLE
Highlight when navigating

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#1405]
As a user, I want my eye to be drawn to where I'm supposed to be looking so that I have an enjoyable, easy time knowing what I'm supposed to be doing. 

- [x] When a user clicks "Edit", the text edit box is highlighted and the cursor appears inside the box. (Instead of highlighting "Cancel" as it currently does). 
  - [x] When in Edit Mode, when a user clicks "Cancel" or "Save Changes", there either should be no action highlighted or "Save & Continue" should be highlighted
- [x] When a user clicks "Comment", the text edit box is highlighted and the cursor appears inside the box. 
  - [x] When in Comment Mode, when a user clicks "Cancel" or "Save Changes", there either should be no action highlighted or "Save & Continue" should be highlighted

**Comment by klappy** [comment]
@EllDoubleYew: Is this issue addressed all the way with the closed PR? Or is there more work to be done?

**Comment by cdwhitfield73** [comment]
It appears to me that the two main issues above are working.  As for the two sub issues, we had discussed as a group that no highlighting was acceptable.  Therefore, it looks like this issue is complete with the closed PR.

**Comment by klappy** [comment]
👍
