### ISSUE TITLE
Refactor the User and Project tabs

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1406]
There are two issues here that are both UX problems:
1. There is no indication that the gray text (for the non-selected option) is actually a user option and something that can be clicked on.
2. Even if the user realizes that the gray text for the non-selected options is something that can be selected, because of its color it appears to be something that is disabled.

I am not familiar with any standards for multiple panel options on tabs, but reproducing the higher level "tab" metaphor may be an acceptable option. (It was quite a bit better in previous builds with the dark background.)

**Comment by Thajny** [comment]
![my projects blank 2](https://cloud.githubusercontent.com/assets/21183377/25871776/3faba02e-34ce-11e7-86f3-c8b7ee145244.png)

**Comment by Thajny** [comment]
![my projects blank 2](https://cloud.githubusercontent.com/assets/21183377/25872224/84ecb6a4-34cf-11e7-9770-f17f8483cc66.png)

**Comment by Thajny** [comment]
![my projects blank 2](https://cloud.githubusercontent.com/assets/21183377/25872638/232c6a3e-34d1-11e7-99e1-25985d8068e5.png)

**Comment by cdwhitfield73** [comment]
I fixed this issue based on the discussion that I thought we agreed using the existing lighter blue was acceptable for now rather than creating a new custom color as seen in the mock up above.
