### ISSUE TITLE
Make modals conform to Style Guide

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#1408]
- [x] Add Resources
- [x] Expand verse check
- [x] Expand Scripture Pane

**Comment by cckozie** [comment]
@benjore Should the Close button on the expanded verse check and expanded tHelps modals be the default/primary with the blue background rather than just outlined in blue?

**Comment by benjore** [comment]
@cckozie Sure. Make them primary if they are the only button available.
