### ISSUE TITLE
Windows install hangs while loading

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#1413]
From Todd on Slack #translationcore channel 5/3: 

"v0.6.18 on Win 10 64-bit seems to be installing really slowly. Are there some prerequisite steps I need to take (installing node.js or git) first? I had to reinstall Windows on this machine so lost all of that from before.

"It just hangs here [Spinning tC icon with "Loading..."]

**Comment by EllDoubleYew** [comment]
So I know we talked about not having spikes on these "bug fixes" but this is not really a bug fix. This is a "something is slow, what is slow and how do we make it not slow anymore" 😅. I feel like there definitely needs to be some time taken here to find the weakest link in the install. No clue what it could be. @ihoegen Do you have any suspicions on this one?

**Comment by ihoegen** [comment]
@EllDoubleYew @benjore @klappy This has nothing to do with the install. The spinning logo comes up on startup. He would need to try with the newest version, and see if the problem still persists

**Comment by benjore** [comment]
Follow up with Todd.

**Comment by klappy** [comment]
Response from Todd: "Thanks for asking. v 0.6.21 installed without a problem but I haven't had a chance to try it out... I'll give it a test run today or tomorrow."

**Comment by cckozie** [comment]
I'm passing this for now as I've not seen any installation problems.
