### ISSUE TITLE
Replace the green and yellow colors used in the edit and comment sections

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1424]
The contrast between the white text and the color is insufficient for good legibility.
On the buttons, the contrast between the disabled and enabled states is too subtle.
I believe these colors are distracting and don't really fit our color scheme. My preference would be to continue to use the same blue as on the rest of the screen.

**Comment by Thajny** [comment]
![ui consistency 1](https://cloud.githubusercontent.com/assets/21183377/25870686/9d589c30-34ca-11e7-95ff-41015505e9aa.png)

**Comment by benjore** [comment]
- [x] Also switch the "Read" Header bar, "Select" Header bar, and the "Check Info Card" to the dark blue

**Comment by cdwhitfield73** [comment]
Done.  Just a reminder that the "disabled" state of the buttons is not gray, as shown in the above mockups.
