### ISSUE TITLE
Receive Login Failed message even though I have a good Internet connection and am using a valid username and password

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1429]
![image](https://cloud.githubusercontent.com/assets/8171759/25678679/32532a54-3010-11e7-891a-2d98ee35c96c.png)

**Comment by cckozie** [comment]
This may be the result of another problem I'm seeing. I am not logged in, but was able to import a project from door43 using the URL. I then did a couple other things, then performed another import from door43 using the URL. This time  it looks like the app went into a loop because the spinning circle just spins and spins. I then close the import modal and tried to login using a good profile. Here is the console log:
[import log.txt](https://github.com/unfoldingWord-dev/translationCore/files/974532/import.log.txt)

After restarting tC I was able to login using that profile.

**Comment by cdwhitfield73** [comment]
The bug that was causing the "loop" has been fixed, so I don't think this will be an issue anymore either.
