### ISSUE TITLE
Project downloaded from door43 but the loading process did not continue

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1432]
I imported the project from the URL https://git.door43.org/qa98/ar_mat_text_ulb
When the spinning wheel stopped, the modal remained on top. I could see part of the snackbar message that comes up after a successful import, but I was not taken to the screen to select a tool. When I closed the modal I just saw this: (note that a tool name is showing but not a project name)
![image](https://cloud.githubusercontent.com/assets/8171759/25681354/9b2b6f92-3019-11e7-8dac-e281af716bb0.png)

**Comment by cckozie** [comment]
I suspect this may be due to the fact that I was not in developer mode and the project was Matthew.

**Comment by cdwhitfield73** [comment]
Can you see if this is still an issue in the current build?  I suspect this has been cleaned up.
