### ISSUE TITLE
Clicking on multiple links in tHelps opens multiple windows

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1456]
We should reuse an already open window if one exists rather than opening a new one. It looks like there is currently no limit to the number of windows that will get opened.

**Comment by cckozie** [comment]
This may be fixed as part of #1207

**Comment by EllDoubleYew** [comment]
I am going to need to find a way to manage the number of windows Electron has open at once. The missing piece here is an inability to actually ask Electron if a window is open. I am currently working with @mannycolon to find if there is a way to do this or not.

**Comment by cckozie** [comment]
Putting a hold on this since many of the links do not work. Need to retest once issue #1553 is completed.

**Comment by cdwhitfield73** [comment]
Currently, URL's are just references and don't do anything when clicked.  Anything referencing another word or notes topic should open in the Modal, therefore, the external window is not currently needed.
