### ISSUE TITLE
Multiple tC icons created in Windows start menu most used list

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1457]
Could this be related to issue #1456 ?
![image](https://cloud.githubusercontent.com/assets/8171759/25748251/18b10f60-3170-11e7-9dc8-3cdcbd46300a.png)

**Comment by cckozie** [comment]
I think this will be fixed when #1207 is

**Comment by mannycolon** [comment]
@cckozie was this ever fixed??

**Comment by cckozie** [comment]
@mannycolon I don't know as I can't fully test it until we resolved all of the problems with links in tHelps.

**Comment by mannycolon** [comment]
@cckozie this should not be related to the tHelps problems

**Comment by cckozie** [comment]
@mannycolon I'm pretty sure that the multiple icons are related to all of the windows opened by clicking on links in tHelps. I think that problem has been resolved, but won't know for sure until all of the non-functioning links get fixed so I can thoroughly test it.
