### ISSUE TITLE
Problems created if tS is installed on a Windows machine that has tC installed

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1458]
Uninstalled tS and Git on my Windows machine
Installed and used tC
Installed tS (completed without errors, the Git uninstall/reinstall also ran without errors)
Now when tS is opened, the "Git is not installed..."message is displayed (tried multiple times)
Now when tC is opened it also indicates that Git is not installed
In the Uninstall or change a program screen of the control console it indicates that Git version 2.9.2 is installed.
When the error message is displayed in tC and I allow it to run the Git install, when the install completes I can use both tC and tS.
At a minimum we should have a warning and explicit instructions in the release notes for users who want to run both apps on a Windows machine. (Don't know yet if this is a problem on OSX or Linux)

**Comment by mannycolon** [comment]
@EllDoubleYew you may want to assign yourself to this issue since you moved it to in progress lol

**Comment by klappy** [comment]
@ihoegen: If tC uses git v 2.9.2, that matches tS and should resolve our issues.
