### ISSUE TITLE
App hangs when attempting to download a project using a URL and there is no Internet connection

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1460]
I've seen multiple scenarios here.
The first time I observed it the app actually hung and I couldn't do anything except close the app.
In other cases, I am able to click the Close button which returns me to the Welcome screen. In this case, when I go back to the Import screen the progress wheel is still spinning although the URL is no longer populated.
If the Internet connection is restore while in this state, nothing happens if I again click on the Import and Select button for the URL although clicking the Refresh button does now reload the list, and clicking on one of the door43 projects button does cause it to be downloaded (but no message indicating that is happening.

**Comment by cckozie** [comment]
This should be handled by fixes done in #1373

**Comment by cdwhitfield73** [comment]
This also has been resolved with all the changes made to the importing process.
