### ISSUE TITLE
Wrong error message displayed when attempting to import project from door43 and there is no Internet connection

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1461]
The message should be the same as when the user clicks the Refresh button on that screen; "Unable to connect to the server. Please check your Internet connection." rather than the generic problem message..

![image](https://cloud.githubusercontent.com/assets/8171759/25751561/1578884a-317b-11e7-8a38-56201354c019.png)

**Comment by cckozie** [comment]
Hopefully this was fixed in #1373

**Comment by cdwhitfield73** [comment]
Yes, this was fixed.
