### ISSUE TITLE
There is no indication that anything is happening after the Import & Select button is clicked on a project on the Import Online Project screen

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1463]
When I click on the Import & Select button nothing happens until after the project has been downloaded and the tool selection screen appears.
When a URL is used, then a spinning wheel is displayed.

**Comment by cckozie** [comment]
This should be fix by changes made on #1373

**Comment by cdwhitfield73** [comment]
Yes, this has been fixed by #1373.  You should see the spinning wheel when importing now.
