### ISSUE TITLE
Avatar

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#1466]
- [x] Fix avatar so that if a user avatar is available, that is used
- [x] For Door43 users that don't have a personalized avatar, used the Door43 logo as their avatar
- [ ] For local users, use the tC logo - use the correct logo

**Comment by EllDoubleYew** [comment]
@benjore So maybe I am confused on this one here, but where would an offline user ever see an avatar that would need to be replaced with the tC logo? Right now I have it showing the door43 correctly but I can't think of a case that a local user would see a d43 avatar.

**Comment by benjore** [comment]
@EllDoubleYew The screen below is the only place I can think of (presently) that will have the avatar appear.

![screenshot 2017-05-08 08 28 40](https://cloud.githubusercontent.com/assets/13352518/25806314/5f10d6c0-33c8-11e7-82a9-bc52d11934af.png)

**Comment by EllDoubleYew** [comment]
@benjore right but is there ever a case of this screen appearing when its a local user (i.e. someone not logged in?)

**Comment by cckozie** [comment]
Door43 user with and without a custom avatar works correctly.
Avatar displayed for a local user is a generic headshot icon. The issues specifies the tC logo.

**Comment by benjore** [comment]
@mannycolon @cckozie I talked with Manny and he explained why the tC logo wasn't appearing properly in an earlier version. I determined the cost-benefit of making the tC icon appear correctly was not worth it and agreed that we could just move forward with the "user" avatar for the local user.

**Comment by cckozie** [comment]
Passing as is based on Ben's comment
