### ISSUE TITLE
App gets into weird state after opening an imported project

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1469]
Sign in with username=qa99, password=qa99
Go to the import projects screen and select ab_tit_text_reg
When the import finished select tW
After the project opens, click User in the menu bar
Click the Sign Out button
Nothing appears to happen except that qa99 is removed by User in the menu bar
Click the Close button
Click User in the menu bar
Sign in with a valid username/password
Login failed, incorrect username message is displayed
Click on Project
Click on Import Online Project 
Click the Refresh button
It appears that you are still logged in to Door43

**Comment by cckozie** [comment]
This should be caught by testing in #1407

**Comment by cdwhitfield73** [comment]
This is probably fixed now, but if not, it will definitely be fixed on the next build with Ian's changes restricted a non logged in user to only the login page.
