### ISSUE TITLE
Implement report data filtering/parsing for reportview

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord/translationCore#147]

**Comment by ihoegen** [comment]
List of things to filter by:
- [x] Group
- [x] Status (correct in context, flagged, none), 
- [x] Retained/replaced
- [x] With and without notes
- [x] With and without proposed changes

Search is looking for specific words/phrases,in explicit places: 
- [x] Source/target text
- [x] Notes
- [x] Proposed changes
