### ISSUE TITLE
User looses ability to import door43 projects after restarting tC

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1497]
Log in to door43 account
Close and reopen tC
Navigate to the Import Online Project screen
Click on the Import & Select button for one of the projects
You're then forced to the User screen with a snackbar message stating "Please login before starting a project.

**Comment by cdwhitfield73** [comment]
This has been fixed.  The importing process used to check a "loggedIn" variable that was buggy.  It no longer checks for it, so importing will always work.
