### ISSUE TITLE
 Centralize the authentication tokens

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord/translationCore#15]

**Comment by ihoegen** [comment]
I think a single JSON in the root would be the best solution, with the possibility of an api function to access the Github token

**Comment by RoyalSix** [comment]
Seems like it would work, are you working on this? I might give it a shot, sounds fun.

**Comment by ihoegen** [comment]
I'm working on a build, you can go ahead with this. Just assign it to
yourself.

**Comment by RoyalSix** [comment]
Ok cool, also I have another question but its better suited for slack.
