### ISSUE TITLE
typing error on Terms and Conditions Page

### ISSUE THREAD

**Issue by ChrisJarka** [unfoldingWord/translationCore#1500]
Stament of Faith s/b Statement of Faith

![typing error](https://cloud.githubusercontent.com/assets/9850185/25860840/d084bd38-34b0-11e7-8fe4-1d258e7def6a.png)

**Comment by ChrisJarka** [comment]
Even though I'm 'online' the links are not working.

![links not active](https://cloud.githubusercontent.com/assets/9850185/25860988/52ed64c8-34b1-11e7-9bde-bf4c84db933f.png)

**Comment by cdwhitfield73** [comment]
these issues have been resolved.
