### ISSUE TITLE
"Login in" -> "Log in"

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#1501]
- [x] Change verbiage to "Log in with Door43"

## Notes 
- "Login" is a noun (I have a login). "Log in" is a verb (Please log in to Door43). 
- The button is correct 

![screenshot 2017-05-09 11 36 43](https://cloud.githubusercontent.com/assets/13352518/25862084/684f5ac4-34ac-11e7-963a-778ed936ec9d.png)

**Comment by ihoegen** [comment]
"Login in"

**Comment by mannycolon** [comment]
@benjore yeah I know `log in` is a verb lol. it was an honest mistake. I was so focused on getting it done that I forgot to pay attention to that haha.
