### ISSUE TITLE
Main Modal Navigation

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#1502]
- [x] Add "Next" button to the Profile Screen. 
- [x] Move "Close" to an "x" in the top right

**Comment by Thajny** [comment]
![modal nav](https://cloud.githubusercontent.com/assets/21183377/25868231/9a366f68-34c1-11e7-90d1-c2528fd1e015.png)

**Comment by mannycolon** [comment]
@benjore I never got a mockup for this??

**Comment by cckozie** [comment]
The Next button and X have been added as requested and do function properly. However, after logging in, both the Create and Submit buttons appear with the primary button attributes. I believe the Next button should be the primary one. 
@benjore Do you want this changed, or is it good enough for now?

**Comment by cckozie** [comment]
I created issue #1548 to address the button styling.
