### ISSUE TITLE
Prohibit user from re-upload a project that would overwrite the existing one

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#1503]
- [ ] A warning dialog needs to appear when attempting to export a project to Door43
  - [ ] If there will be non-shared git history, the upload needs to be prevented.

**Comment by cckozie** [comment]
If there is not a shared history between the local project and the one in the user's repo, then issue this message in the alert modal: "[project name] cannot be uploaded because there have been changes to the translation of that project on your Door43 account."

**Comment by cckozie** [comment]
@EllDoubleYew I just tweaked the message text a little.
