### ISSUE TITLE
Not able to open project after no user logged in error, and then logging in

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1504]
Logged out
Navigated to Import Online Projects screen
Imported a project using the URL
Attempted to open the project and received the Need to login error message
Logged in as a local user
Selected a previously worked on project and tool
The loading dialog stays up forever
Closed and reopened the app
Now the project loads correctly and is usable

**Comment by cdwhitfield73** [comment]
This appears to be working now on multiple tests.  However, after Ian's changes get merged to where non logged in users can't even get to the project screen, we can remove the check for a logged in user and the dialog box when selecting a project, which will ensure that this issue doesn't happen.
