### ISSUE TITLE
Checking work is lost after switching tools

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1508]
0.6.22
Renamed the translationStudio folder to start with a clean slate.
Logged in with a door43 account and imported https://git.door43.org/qa98/es-419_eph_text_ulb
Opened the project using tW
Opened the checking group for God
Switched the tool to tN
Switched the tool back to tW
Selected text for 7 of the 8 checks for God, and bookmarked the other one
Switched the tool to tN
Switched back to tW
All of the progress, checkmarks, and bookmark were gone in the checks menu
All of the selected text and the bookmark did appear in work area

Might this be related to #1333 as it has the same symptoms?

After switching back to tN, performing some checks, switching to a Titus/tW project, then coming back to the Ephesians/tW project, the progress, checkmarks, and bookmark do appear again in the checks menu. But when I switch to tN, those progress and checkmarkss have now disappeared.

**Comment by cckozie** [comment]
@mannycolon Attached is the tC folder. Sorry this took so long! I got trapped in a couple other meetings.
[translationCore.zip](https://github.com/unfoldingWord-dev/translationCore/files/990665/translationCore.zip)

**Comment by mannycolon** [comment]
@cckozie Thanks

**Comment by mannycolon** [comment]
Working on #1499 first.  The fetch data process revamp may help fix #1508.

**Comment by klappy** [comment]
Just to confirm that no data is lost but the menu appears to lose sync with the actual data that is on the filesystem? For example the menu shows nothing for an item but when you click on the item, it could have a selection, edit, comment, or bookmark?

I'm wondering if "re-rendering" the required menu data on project/tool load would prevent the data in the groupData (menu) from being stale and not reflecting what's in the checkData folder for the checks themselves?

**Comment by benjore** [comment]
@mannycolon Can you give this an estimate?

**Comment by mannycolon** [comment]
@benjore this is a duplicate
