### ISSUE TITLE
Improper error message when attempting to upload while logged in as a local user

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1516]
![image](https://cloud.githubusercontent.com/assets/8171759/25923642/1697c27c-35a4-11e7-9cfb-a42f7ae7c4b1.png)

**Comment by cckozie** [comment]
0.6.22
Retest with new build

**Comment by mannycolon** [comment]
@cckozie this should be good to go. i implemented this last sprint.

**Comment by cckozie** [comment]
Thanks @mannycolon
