### ISSUE TITLE
Revise the text on the Add Resources dialog

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1520]
Currently the dialog title is "Add Resources"
Currently the label text is "Select source language"
Are we expecting to have resources available at some point other than language resources? 
The dropdown list contains the actual project source language(s), reference language(s) (which could be considered "source"), and the project's target language. So the label is technically inaccurate.

**Comment by cdwhitfield73** [comment]
For now, I changed it to "Select language".  Is that okay?
