### ISSUE TITLE
Clicking on the (i) on the login page does not do anything

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1521]
When the user clicks the (i) it should bring up the text per this link in a popup
https://xd.adobe.com/view/f848f4cb-bdc4-46cd-809f-4bdd025b0af0/screen/5116d49e-d45f-4a47-9739-2be5e04ce181/Profile-Popup

**Comment by klappy** [comment]
@cckozie: What are your thoughts on this heading? "Door43 Information"

![screen shot 2017-05-15 at 4 28 42 pm](https://cloud.githubusercontent.com/assets/118073/26077884/a50be93a-398b-11e7-9a1c-48e6b11205e1.png)

**Comment by cckozie** [comment]
@klappy That works for me.

**Comment by cckozie** [comment]
The info dialog opens when the (i) is clicked on. The cursor should change to the hand cursor when hovering over the (i) like it does on the other clickable areas. Wrote this up in issue #1574.
