### ISSUE TITLE
Blank checking area on screen

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1532]
0.6.23  (Possibly the same problem in #1496 running 0.6.22)
Loaded a previously used project and see this:
![image](https://cloud.githubusercontent.com/assets/8171759/25959572/a6072c46-3639-11e7-805a-f6a82a0de619.png)

Here's what's in the console:
![image](https://cloud.githubusercontent.com/assets/8171759/25959493/615edf4e-3639-11e7-8066-49037451a3cd.png)

Restarted tC and it now appears correctly.

**Comment by cckozie** [comment]
To replicate the problem, use these two projects taken from the translationStudio folder:
This is a mostly good project that I have used for quite a bit of testing
[es-419_eph_text_ulb.zip](https://github.com/unfoldingWord-dev/translationCore/files/993767/es-419_eph_text_ulb.zip)

This is a project that only has a small amount of text in the first chunk and has no verse markers set
[en_tit_text_reg.zip](https://github.com/unfoldingWord-dev/translationCore/files/993768/en_tit_text_reg.zip)

1. Load the Ephesians project with tW
2. Click on Tool in the menu bar and select tN
3. Click on Project in the menu bar and select the Titus project using tN
4. You will most likely see that the app hangs on the loading dialog 
5. Close and reopen tC
6. Load the Ephesians project with tN
You will likely see this screen after the loading is complete:
![eph_tn](https://cloud.githubusercontent.com/assets/8171759/25961309/757c7e2c-363f-11e7-8f15-ca9f5579844e.png)
Here is a screenshot of the console when the app is in that state:
![eph_tn_log](https://cloud.githubusercontent.com/assets/8171759/25961328/8ca94ff8-363f-11e7-94ff-b837623a539b.png)
 7. If you now switch to the tW tool you will see what is referenced in the first comment above.

**Comment by cckozie** [comment]
After playing with this longer I have realized that I can create the same behavior just with the Ephesians project. 
If I load Ephesians using tN first, I get the blank checking area. If I then switch to tW, I again get the blank checking area. 
If I then close tC, reopen it, the open Ephesians first using tW, it works fine. If I then switch to tN, that works fine too.
I suspect that the problem may be caused by the fact that there are some chunks that are not marked as complete, and a few that do not show any text for the verse, although I believe there is actually text in those verses in the project. Upon inspecting the project in the file system, I see that there were no verse markers in chapter 3. I reimported the project and now see the verse markers are there. (I can't guarantee that there were there when the project was originally imported)

**Comment by cckozie** [comment]
I have labeled this as a critical bug. I am unsure if that is the correct priority or not. Here's my reasoning:
The observed problem was no doubt caused by loading an "invalid" project as it has very little data, no verse markers set, and no completed chunks. That is an "unsupported" scenario for this release, so it does not bother me too much that that project causes the app to hang while loading, although it would be much preferable to catch what's causing the error and alert the user.

The critical issue in my mind is that after the error is encountered, it is stays in a state that prevents me from working on my projects until I close and reopen the app. (I have rewritten this section several times as I have been able to narrow down the issue. At this point I am less inclined to believe this is a critical bug, but would like to discuss it with you before making a decision)

**Comment by benjore** [comment]
How difficult is it to detect that tC has thrown a white screen? And then if it has thrown a white screen show an error message (and fail gracefully)?

**Comment by benjore** [comment]
@mannycolon thinks this is covered with #1499

**Comment by cckozie** [comment]
0.6.26.6
![image](https://cloud.githubusercontent.com/assets/8171759/26433097/89ad5b3e-40ce-11e7-9d75-86f1abd9b985.png)
[ar_eph_text_ulb.zip](https://github.com/unfoldingWord-dev/translationCore/files/1027771/ar_eph_text_ulb.zip)
If this is a corrupted project issue, it was corrupted in this build. It was downloaded an hour ago from a Door43 repo that has not had an upload from tC. https://git.door43.org/pjoakes/ar_eph_text_ulb
I did have the project open earlier with tW after the import and did not see this problem.
I'm thinking maybe there are missing verses, but I did not get that error message.

**Comment by mannycolon** [comment]
That project is corrupted. @cckozie please delete the .apps folder and try loading it again.

**Comment by klappy** [comment]
Looks like this is due to the bibles getting overwritten with Titus somehow.

@mannycolon: Sounds like @cckozie was able to create this issue off of a fresh project in the build he was using. 

@cckozie: Technically, Manny is right, in this case the data tC needs got overwritten. Recovering from this issue requires deleting all bibles and regenerating them. In theory we didn't lose anything, since all selections, comments, bookmarks and edits are saved elsewhere, in addition to source USFM edited and in sync with the version we had.

To make sure this can pass QA: 
Did we fix the root issue that is causing this? Are we sure that the bibles aren't being over-written when changing projects? I can try in the latest development.

If so, we need to detect mismatch of project's book and bible in the data. I feel strongly that we need to address this as a separate issue. Mainly in that there is a wholistic approach of changing the way we store bibles in tC data that will avoid related issues in the future.
1. Store bibles in a nested approach like:
`./.apps/translationCore/resources/bibles/[version]/book/chapter.json`
2. Regenerate bible/book data if the target book in the new data structure is missing.

**Comment by klappy** [comment]
@cckozie @benjore: We have two symptoms that have the root issue of the above related issue that I'd like to have us address:
- Going from a Titus Project to Ephesians, seems to overwrite the Ephesians bibles with Titus bibles, and causes the blank screen. (it is missing too much data, it fails to render)
- Going from an Ephesians Project to Titus, seems to overwrite the Titus bibles with Ephesians bibles, and causes the wrong target text to render. (it has too much data and none missing, so it still renders)

I've created this on the latest build and using the latest code merged into develop branch currently.

![screen shot 2017-05-26 at 4 52 23 pm](https://cloud.githubusercontent.com/assets/118073/26512252/c1a8eca4-4233-11e7-892f-b9ec7fea2491.png)

**Comment by klappy** [comment]
I worked with @cckozie on a workflow/checklist for us before we merge each PR or create each build for a quick easy way to look for issues. It won't be comprehensive, but it will catch most things in about a minute or so of visual inspection.
