### ISSUE TITLE
can't upload to door43 while logged in

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord/translationCore#1537]
When I'm logged in as a different door43 user I get this error message when I try to upload:
![bad id](https://cloud.githubusercontent.com/assets/8171759/25822703/07e18156-33ff-11e7-812f-ffff1eb6de24.PNG)

**Comment by mannycolon** [comment]
@cckozie I moved it here

**Comment by mannycolon** [comment]
This bug usually happens after switching between local user and door43 acct.

**Comment by EllDoubleYew** [comment]
@mannycolon I no longer get this error with the new gitSync method. This is addressed with #1567. Moving into pending build.

**Comment by mannycolon** [comment]
you have to switch users between local and door43 users @EllDoubleYew

**Comment by EllDoubleYew** [comment]
@mannycolon Yeah I tested it! You can test it as well if you would like. Ill make sure I tag a mention of this on the PR as well.

**Comment by cckozie** [comment]
In 0.6.26 it no longer appears to discriminate whether or not the repo being uploaded into is the same one as the project import.
