### ISSUE TITLE
Picture links in tHelps do not work

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1552]
0.6.24
I assume these are supposed to be links. Clicking on them does not do anything.
![image](https://cloud.githubusercontent.com/assets/8171759/26061307/2d21e926-394d-11e7-9d40-7498c383e9ff.png)

**Comment by cdwhitfield73** [comment]
These are not links.  They are just references to images that it is expecting to find locally and can't.  We need to just include these images in the app in a folder that these links can point to in order for them to show up (this is how we do it in tS for translationAcademy articles)

**Comment by EllDoubleYew** [comment]
@cdwhitfield73 I was breaking them with my regex. Fixed now, Will be a part of another PR that addresses a handfull of tHelps issues.
