### ISSUE TITLE
Improper links in tHelps

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1553]
0.6.24
This is from Inclusive "We" in tN
![image](https://cloud.githubusercontent.com/assets/8171759/26061766/77e34fc6-394e-11e7-90c0-b309b0450912.png)

**Comment by cckozie** [comment]
0.6.26.6
The above circled element still does not appear as a link.

**Comment by cdwhitfield73** [comment]
Currently, URL references like this are just "references" not links.  The way they are included in the text of the data makes them difficult to parse to turn into links.  Will have to be worked on later.
