### ISSUE TITLE
Overlapping Selection/Highlight Bug

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#1554]
When selecting an overlapping text, the blue selection seems to cover the first part of the text preceding the selection(s). 

To recreate this, select a word/phrase, then select the word directly before it including part of the existing highlight. 

If two selections are made first and a new overlapping selection, the entire verse ends up being selected, not just a ghost selection of the preceding text. This may be a limitation of what we are able to do. Either we need a huge breakthrough, or find a way to limit the user from doing this and communicate to remove the selections first. The other option is to alert the user when it happens.

Let me know if you need help recreating.

![screen shot 2017-05-15 at 12 13 06 pm](https://cloud.githubusercontent.com/assets/118073/26067731/27bea1ce-3969-11e7-8f07-c3e1d6be45de.png)

**Comment by cckozie** [comment]
Could not replicate the problem in beta.65. I did find a new problem tho, and wrote it up in #2700.
