### ISSUE TITLE
Implement new translationCore app layout design

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord/translationCore#156]

**Comment by mannycolon** [comment]
![screen shot 2016-09-16 at 1 47 43 pm](https://cloud.githubusercontent.com/assets/17072300/18768574/5117fc42-80f4-11e6-8bb0-c223b4c49a71.png)

**Comment by klappy** [comment]
Issues in the epic are closed, completing this is superseded by the new UX/UI.
