### ISSUE TITLE
Verse text appears blank in projects that have merge conflicts

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1573]
I have a project that has a single merge conflict in one verse. The text for most verses does not appear in either the Select area or the scripture pane even though it is in the file system.

**Comment by cckozie** [comment]
May want to combine with #1572

**Comment by ihoegen** [comment]
#1564 Has a bug report for this

**Comment by cckozie** [comment]
We're now not allowing merged projects and have plans to deal with it otherwise in the future.
