### ISSUE TITLE
Password handling

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#1576]
## Story

As a user who has one password for my bank, Google, and tC, I want tC to securely handle my password at all times so that I do not have to sue when my identity is stolen shortly after my tC password is compromised.

**Comment by klappy** [comment]
@jag3773: Do you know if Gogs Git Server implementation (gitea) supports user API Tokens for Git uploading/pushing? We're trying to avoid saving passwords, asking users for the password everytime, and/or implementing ssh keys.

**Comment by klappy** [comment]
@ihoegen: All my research lead me to this post: https://github.com/gogits/gogs/issues/842

**Comment by ihoegen** [comment]
@klappy So I tried to implement it like we did in the past, and it works again
