### ISSUE TITLE
Multiple problems when uploading

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1582]
These issues were copied from #1223
1. There is no indication during the upload that anything is happening. After clicking the upload button the screen just sits there until the success or failure message is displayed.
2. If the Internet connection is lost during the upload, the message text is "Error Uploading: Unknown error". We should be able to detect that it is an Internet problem and issue that standard message.
3. If an upload is attempted when logged in as a local user the message text is "Error Uploading: Can not find the repository of this user". The message text should be "Error Uploading: You must be logged in with a Door43 account to upload projects".

**Comment by cckozie** [comment]
4. Internet connection was lost during upload. Proper error message was displayed.
With Internet connection still unavailable, I clicked on the Upload button for the same project and received the message: Unknown error while trying to create the repository.

**Comment by cdwhitfield73** [comment]
@cckozie Can you give me a screen shot of the console after you get the unknown error message?  I can't duplicate this, I am getting the correct error message when I perform these steps.  I need to know what error you are receiving before I can look for it and catch it.

**Comment by cckozie** [comment]
@cdwhitfield73 Here ya go
![image](https://cloud.githubusercontent.com/assets/8171759/26208545/fd4546f2-3baf-11e7-9439-508479e84ee4.png)

**Comment by cdwhitfield73** [comment]
It should now catch all possible iterations (that I know of) of errors relating to loss of internet (there's at least 6 different messages it can send!)

**Comment by cckozie** [comment]
Looks good in 0.6.26.6 on all 4 problems noted.
