### ISSUE TITLE
Received the "Some selections are no longer valid and are removed." message

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1583]
SEE THE LAST COMMENT. The Resources/Bibles folder is getting replaced by one from a different project.

![image](https://cloud.githubusercontent.com/assets/8171759/26131963/b1570e9a-3a62-11e7-8425-64d7b3106691.png)

I am not sure what I did to cause this, but may be due to the following process:
Uninstalled tC, tS, and Git
Installed and used tC
With tC still open, installed and ran tS
When I came back to tC I got that error message.

Possibly due to the fact that installing tS always uninstalls and then re-installs Git?

**Comment by cckozie** [comment]
0.6.26.4
This happened today on Mac (previous comment was on Windows). Reopened a project that was complete on tN and received the message.
Yikes! Now that I look closer I see that the target has somehow gotten changed from French to English inside tC. Looking in the file system, I see that the verse text is still in French, but in the Bibles folder, the target language is now English.

[fr_eph_text_ulb 2.zip](https://github.com/unfoldingWord-dev/translationCore/files/1015536/fr_eph_text_ulb.2.zip)

![image](https://cloud.githubusercontent.com/assets/8171759/26266239/2cbd46f0-3caa-11e7-92df-e2251b1f2269.png)

![image](https://cloud.githubusercontent.com/assets/8171759/26266275/51394a60-3caa-11e7-95bd-bc9f9de89273.png)

**Comment by cckozie** [comment]
Saw this again today. I had a Matthew project whose target language was Arabic (loaded with tW). I looked around inside that project for a while, then loaded my French Ephesians project. Now the French project shows the translations in Arabic, although it is not displayed RTL. So of course now all my checks are invalid.
All of the files in the Resources/Bibles folder for my French Ephesians project have been replaced by those from the Arabic Matthew project.
![image](https://cloud.githubusercontent.com/assets/8171759/26333836/db8ed078-3f2e-11e7-8464-1da878cdb876.png)

**Comment by mannycolon** [comment]
@klappy @benjore @cckozie actually this was a lot easier than we expected. it took me more time to find the problem than fixing it. lol
 I'm about to put in a PR.

**Comment by mannycolon** [comment]
@klappy when are we supposed to get the ***"Some selections are no longer valid and are removed."** alert message.

this error seems to be different from the issue I fixed related to bible resources.

**Comment by klappy** [comment]
When ever we render the highlights, it checks to make sure that the "selections" are found in the current verse. If it is not found, it alerts the user when it deletes it.

**Comment by cckozie** [comment]
![image](https://cloud.githubusercontent.com/assets/8171759/26600009/1790aa3a-4540-11e7-8afe-4be6d2ca2e83.png)
Switching projects and tools still causes this issue. Here's the steps I used to get here:
1. Import https://git.door43.org/pjoakes/fr_eph_text_ulb
2. Import https://git.door43.org/pjoakes/es-419_eph_text_ulb
3. Load the French project with Words and make some checks
4. Load the Spanish project with Words and make some checks
5. Switch to Notes in the Spanish project and make some checks
6. Load the French project with Notes and make some checks
7. Load the Spanish project with Notes. Received the error message and see that the language title in the scripture pane is French, but in the Select pane it is Latin American Spanish. The language text in both panes is French.
