### ISSUE TITLE
Prohibit loading projects with merge conflicts

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#1586]
- [x] When a user tries to select an imported project that has one of the following problems: 
  - [x] Merge Conflicts
    - [x] Prohibit the loading of this project
    - [x] Error message: "Oops! The project you are trying to load has a merge conflict and cannot be opened in this version of translationCore! Please contact Help Desk (help@door43.org) for assistance."

**Comment by cckozie** [comment]
0.6.26.4
Imported project with a single merge conflict and received the error message. Used a text editor to resolve the problem in the tC folder, and the project will now open.
