### ISSUE TITLE
Warn user when trying to load project with missing verses

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#1588]
- [x] When a user tries to select an imported project that has one of the following problems: 
  - [x] Blank Verses
    - [x] Allow the loading of this project after the following warning is displayed
    - [x] Warning message: "Oops! Your project has blank verses! Please contact Help Desk (help@door43.org) for assistance with fixing this problem. If you proceed without fixing, some features may not work properly." Buttons: "Cancel" "Continue Without Fixing"

**Comment by mannycolon** [comment]
This issue/story is blocked pending the completion of #1499

**Comment by mannycolon** [comment]
nvm lol

**Comment by cckozie** [comment]
The error message is missing the final period, but I'm passing it for now.
