### ISSUE TITLE
Unexpected behavior during unselect

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1590]
Use project https://git.door43.org/qa91/es-419_tit_text_ulb
Go to the Metaphor check for Titus 1:7
Highlight individually by double clicking the words como administrador de Dios
Click on "de" to unselect it
Both "de" and "Dios" are unselected

I've looked at this a little further, and it looks like the issue is related to "Dios" being on a new line. When I change the screen width such that the word wrapping occurs between different words, the word that improperly gets unselected is the one a the end of the line just above the word that was unselected.

**Comment by cckozie** [comment]
Still a problem in 0.7.0. It does have to do with the line breaks. It works differently depending on where the line breaks occur.

**Comment by cckozie** [comment]
beta.65
It is still unselecting the last word on the line above where I unselect the first word.

After making the 4 individual selections:
![image](https://user-images.githubusercontent.com/8171759/30383144-9c37bcaa-9866-11e7-86f7-4fec28315799.png)

After unselecting only "de":
![image](https://user-images.githubusercontent.com/8171759/30383185-b84f6bae-9866-11e7-986a-1967308c3d55.png)

**Comment by cckozie** [comment]
I just found another problem with unselect.
Open a project and go to a check where a select has been made. Click the Select button, then click on one of the highlighted words. It does not unselect. You must click the unselect button to get it to work. Same thing happens if you go to a check that does not have a select, make a selection and click "Save". Then click "Select" and try to unselect by clicking.

**Comment by cckozie** [comment]
I'm not sure if I didn't properly test this, but the initial problem does still exist in beta.76. The  problem in the latest comment above has been resolved, but the one above it with the images still exists.

**Comment by klappy** [comment]
Likely the selected text does not preserve the actual space that formed the line break but sent the new line character. If we can find a way to make it look for any whitespace including linebreaks instead of just spaces, that should address the issue.

**Comment by PhotoNomad0** [comment]
Don't have time to look at this now.

**Comment by cckozie** [comment]
In 2.1 the selections are merged so the problem no longer exists.
