### ISSUE TITLE
Save and Continue moves to next check, but text in Select area remains on same verse

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1594]
I was performing tN checks in https://git.door43.org/qa91/es-419_tit_text_ulb
I made several selects and unselects and went into and then canceled out of the edit box in the Metaphor check on Titus 1:7. 
I then continued on with additional check highlighting and clicking Save and Continue. 
I then noticed that when moving to the next check there was already selected text, and then noticed that the text in the select area is not advancing with the check.

![image](https://cloud.githubusercontent.com/assets/8171759/26171330/2af03694-3b0a-11e7-8906-dffff400ec0e.png)

![image](https://cloud.githubusercontent.com/assets/8171759/26171256/eaadbbd8-3b09-11e7-9e6b-b0810eb06a04.png)

**Comment by cckozie** [comment]
I think clicked on the 3:8 check and the Select pane went there, but then after clicking back to a previous check, the Select pane stayed the same.
I then clicked on Save and Continue when brought up the the Attention: Please select... dialog, and found that clicking on the Skip button moved to the next check, but the Attention dialog did not get dismissed. 
After doing that a few time I ended up with this screen
![image](https://cloud.githubusercontent.com/assets/8171759/26171798/dde31dce-3b0b-11e7-83fd-4acffba212b7.png)

And this in the log
![image](https://cloud.githubusercontent.com/assets/8171759/26171834/fa8c7a7e-3b0b-11e7-9756-be2ec4141a67.png)

**Comment by cckozie** [comment]
After the above, I force quit tC. After restarting it and attempting to reload the project with tN, the app hangs on the loading dialog.
![image](https://cloud.githubusercontent.com/assets/8171759/26176832/25bd40e6-3b1d-11e7-9e49-a16fb618a2c0.png)

[es-419_tit_text_ulb.zip](https://github.com/unfoldingWord-dev/translationCore/files/1009158/es-419_tit_text_ulb.zip)

**Comment by cckozie** [comment]
Looks like it went nuts on selections in chapter 1, verse 7:)

**Comment by cckozie** [comment]
This is easy to reproduce.
Load the project referenced at the top of this issue with the tN tool.
Make selections and click Save and Continue for the checks as they become active
After completing the Metaphor check of Titus 2:14 you'll notice that the Select pane is stuck on 2:14 and there are errors in the console.

I thought it may have something to do with the fact that 2:14 is the first verse with 2 tN checks, but that appears to not be true. Using https://git.door43.org/pjoakes/fr_tit_text_ulb I do not see the same issue on that check.

**Comment by cckozie** [comment]
I see in build 0.6.26+3 the problem also occurs when doing tW checks. The Select pane "freezes" on Titus 2:13 when hitting the "born again..." check.
Interesting that the problem occurs in the same chunk as in tN.

**Comment by RoyalSix** [comment]
@cckozie I tried several times trying to recreate this, are you still experiencing this behavior?

**Comment by cckozie** [comment]
@RoyalSix Looks like it has been fixed in 0.6.26.4, at least on the referenced project. I see that verses 3:5-7 appear blank (actually, they just don't have any verse markers). I suspect that is what was causing the issue in previous builds. 
I'm moving this to QA to do a little more testing on it.
