### ISSUE TITLE
Headers have disappeared on enlarged scripture pane between 0.6.22 and 0.6.23

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1597]
0.6.26
![image](https://cloud.githubusercontent.com/assets/8171759/26179529/e55a8e2a-3b29-11e7-8282-6413090a1fe0.png)

0.6.22
![image](https://cloud.githubusercontent.com/assets/8171759/26179574/15b027c4-3b2a-11e7-97f0-acaaaf421bfd.png)

**Comment by cdwhitfield73** [comment]
I noticed this when I was working on issue 1168 and have fixed it.  It will be included in the PR that gets submitted for that issue.
