### ISSUE TITLE
Highlighting should be disabled during edit and comment

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1598]
# Overview
Even though we don't allow selecting text when the Edit or Comment pane is open, the user is able to highlight text in the Select pane. That will likely be confusing to the user as the text does stay highlighted in blue and then disappears when the Edit or Comment pane is closed.

**Comment by mannycolon** [comment]
# Tasks
- [ ] [1] Add appropriate css settings to the selection area during edit & comment
