### ISSUE TITLE
App hangs when reloading a project

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1604]
[es-419_eph_text_ulb.zip](https://github.com/unfoldingWord-dev/translationCore/files/1010906/es-419_eph_text_ulb.zip)
[es-419_tit_text_ulb.zip](https://github.com/unfoldingWord-dev/translationCore/files/1010907/es-419_tit_text_ulb.zip)
Load the Ephesians project with tW
Load the Titus project with tW
Load the Ephesians project with tW - The app hangs on the loading screen.

**Comment by mannycolon** [comment]
i think this will be resolved by #1499

**Comment by cckozie** [comment]
Probably due to a corrupted project.
