### ISSUE TITLE
App malfunctions while performing/skipping checks

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1611]
Opened a project with tW
Performed some checks and skips
After a couple of skips I am no longer able to dismiss the skip dialog, although the active check is moved to the next one in the menu. May be related to #1604
![image](https://cloud.githubusercontent.com/assets/8171759/26205046/38f00fac-3ba6-11e7-8259-b0070119e44c.png)

**Comment by cckozie** [comment]
Probably due to a corrupted project

**Comment by mannycolon** [comment]
@cckozie is this issue address in v0.7.0?

**Comment by cckozie** [comment]
@mannycolon I haven't seen this problem for a long time now, so I'm closing the issue.
