### ISSUE TITLE
rename apps folder to .apps

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#1614]
Before releasing beta we need to use the standard using .apps folder in the project instead of apps. This will make it future compatible.

**Comment by cckozie** [comment]
In existing projects it now adds the .apps folder rather than renaming the existing one so all existing checks, edits, and comments appear to be gone.
This is true even for projects I had previously uploaded to Door43. When I import them, all of the previous work is gone.

**Comment by ihoegen** [comment]
@cckozie We're thinking about having the few users that we have rename the apps folder to .apps

**Comment by cdwhitfield73** [comment]
Even though we only have a "few" users (Koz being one of them that didn't get the memo to rename his folders), I think it is pretty simple code to do this automatically for them and should be done.  My suggestion for a quick fix (and not a full migration) would be at the point of selecting the project, just search for an "apps" folder and rename it to ".apps" before continuing to load the project.
