### ISSUE TITLE
Highlights are missing in ULB for checks that contain ellipses (...)

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1616]
See for example Ephesians 2:19 Metaphor check in tN
![image](https://cloud.githubusercontent.com/assets/8171759/26223485/d6e3c662-3be3-11e7-8144-40e9c8a75b7f.png)

**Comment by mannycolon** [comment]
@cckozie i thought that was expected behavior

**Comment by cckozie** [comment]
Klappy thinks we punted on it. Ben doesn't remember discussing it.

**Comment by benjore** [comment]
QUESTION: Is it inclusive of everything in between or exclusive?
