### ISSUE TITLE
Keep the height of the check pane consistent

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1626]
Currently the height of the scripture pane and select pane appear to be fixed, but the check pane varies in height depending on the text displayed in it. This is both distracting to the user, and it causes the action buttons to move up and down and the user moves through the checks. I believe it would be a better user experience if the elements on the screen remain in a fixed location unless the user intentionally changes them.

**Comment by cdwhitfield73** [comment]
This has already been addressed with the change to using flex layout...issue #1168
