### ISSUE TITLE
Selection has been made in check, but edit glyph is displayed

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1629]
[fr_eph_text_ulb.zip](https://github.com/unfoldingWord-dev/translationCore/files/1014545/fr_eph_text_ulb.zip)

I had finished doing the tN checks in this project. I then uploaded it, then exported it. When the export finished, I reopened the project and noticed that the check mark was not shown on Metaphor for 2:16. I'm not sure if that problem existed before the upload and export was done, although a screen shot from earlier during the checking process does show it with the check.
After closing tC, then reopening the project, the edit glyph was still displayed.
After undoing and redoing the selection, the check is again displayed.
Before:
![image](https://cloud.githubusercontent.com/assets/8171759/26251836/31d0afc8-3c74-11e7-8f97-6d8e423d445b.png)

After:
![image](https://cloud.githubusercontent.com/assets/8171759/26252197/2edc35de-3c75-11e7-819d-70be0a212214.png)

**Comment by cckozie** [comment]
This is still an issue in 0.6.26.5
[fr_eph_text_ulb.zip](https://github.com/unfoldingWord-dev/translationCore/files/1016515/fr_eph_text_ulb.zip)
![image](https://cloud.githubusercontent.com/assets/8171759/26279396/2c7ba870-3d78-11e7-8fe7-925a3b78f891.png)

**Comment by mannycolon** [comment]
I did an extensive/detailed research and found the root cause of this bug. Basically, two Group IDs are writing files to the same chapter and verse.  In this case 2:16. 
**figs_metonymy **
```
{
    "priority": 1,
    "comments": false,
    "reminders": false,
    "selections": true,
    "verseEdits": false,
    "contextId": {
      "information": "The cross here represents Christ's death on the cross. AT: \"by means of Christ's death on the cross\" (See: [[:en:ta:vol2:translate:figs_metonymy]])\n  ",
      "reference": {
        "bookId": "eph",
        "chapter": 2,
        "verse": 16
      },
      "tool": "translationNotes",
      "groupId": "figs_metonymy",
      "quote": "through the cross",
      "occurrence": 1
    }
  }
```
**figs_metaphor**
```
{
    "priority": 1,
    "comments": false,
    "reminders": false,
    "selections": false,
    "verseEdits": true,
    "contextId": {
      "information": "Stopping their hostility is spoken of as if he killed their hostility. By dying on the cross Jesus eliminated the reason for Jews and Gentiles to be hostile toward each other. Neither are now required to live according to the law of Moses. AT: \"stopping them from hating one another\" (See: [[:en:ta:vol1:translate:figs_metaphor]])\n",
      "reference": {
        "bookId": "eph",
        "chapter": 2,
        "verse": 16
      },
      "tool": "translationNotes",
      "groupId": "figs_metaphor",
      "quote": "putting to death the hostility",
      "occurrence": 1
    }
  }
```

The script that verifies that the menu reflects the check data in the filesystem basically on read the file with the latest timestamp and doesn't get to the other file that in this case is for **group id figs_metaphor**
