### ISSUE TITLE
tC does not recognize previously installed Git 2.9.2

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1631]
I was running 0.6.26+3. Ran the install of 0.6.26.4 and received this message even though Git is already installed.
![image](https://cloud.githubusercontent.com/assets/8171759/26253575/7ad063bc-3c79-11e7-8897-c12c9d7e1a20.png)

**Comment by cckozie** [comment]
After the tC install I now have two copies of Git 2.9.2 on my machine.
![image](https://cloud.githubusercontent.com/assets/8171759/26253803/2e2d067c-3c7a-11e7-8b5d-12e452b7b817.png)

**Comment by ihoegen** [comment]
So it looks like we're installing the 32 bit version of git, and tS does the bit version based on machines. We could do something similar, but the main issue is that Git is not on the Window's path variable. So we would still need to install git, but we could make it so only 1 version is installed.

**Comment by cckozie** [comment]
Looks good in 0.6.26.7
