### ISSUE TITLE
SPIKE: Research Resources, Requirements, Implementation of OT Support

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#164]
See https://git.door43.org/Door43/UHB for a bit of an overview.

The files you want to be using are all at https://github.com/openscriptures/morphhb/tree/master/wlc .  Use https://github.com/openscriptures/morphhb/blob/master/wlc/Ruth.xml as your test as it has the morphology complete and is a small book ;)

The key for the morph codes is at http://openscriptures.github.io/morphhb/parsing/HebrewMorphologyCodes.html .  The `/` character is used to distinguish between multiple words that are apart of the same token.  For instance, the [first token](https://github.com/openscriptures/morphhb/blob/master/wlc/Ruth.xml#L73) in Ruth is actually two words "and" and "to be" verb.

There is an existing JS bible app that uses that content at javascripture.org , the code for it is at https://github.com/scruffian/javascripture

cc @jag3773 if you have any other questions.

**Comment by mannycolon** [comment]
@klappy did you mean OT?
