### ISSUE TITLE
UI improvements on checking screen

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1645]
These are on OSX
1. Appears to be no padding in the instructions pane. (Both left and right side)
![image](https://cloud.githubusercontent.com/assets/8171759/26277055/069c0858-3d4a-11e7-86ce-03f13e189747.png)

2. The checking area width expands and contracts as the tHelps pane is hidden and unhidden. It seems like if we're going to let it expand (that's my preference), it would make more sense to let it expand to the full width of the window.

3. The checking area width also expands and contracts as I move through the checks. It appears to be related to the data in the tHelps pane, as I see it change when changing from group to group. e.g. rom "Idiom" to "Inclusive We" to "Metaphor" in Eph.

4. The text should be centered vertically in the blue pane that has the explanation of the check.
![image](https://cloud.githubusercontent.com/assets/8171759/26277280/2ac14170-3d4b-11e7-81bf-a3bf3512e235.png)

5. The "See..." instructions float out of the blue bar and sometimes disappear completely.
![image](https://cloud.githubusercontent.com/assets/8171759/26277393/e06159c0-3d4b-11e7-9c20-4830d6fb8c0c.png)
![image](https://cloud.githubusercontent.com/assets/8171759/26277397/117dded4-3d4c-11e7-91e1-46b33cfe6b76.png)

**Comment by cckozie** [comment]
This is on Windows
Notice that the "See Metaphor" half appears even though the tHelps pane is showing.
#1646 added for the problem in the scripture pane.
![image](https://cloud.githubusercontent.com/assets/8171759/26279296/54a96920-3d75-11e7-990b-d981057da3f2.png)

**Comment by cdwhitfield73** [comment]
Most of these issues have been addressed.  The check area width should only be changing when the screen size changes, not when tHelps collapses or you change checks.  I cannot duplicate this issue so not sure why you are seeing it.  Per a conversation with Ben, the check Info area (blue section in the middle) now is set to add a scroll bar if the text gets too long.  This eliminates the problem of the "link" or other text getting pushed off the edge.

**Comment by cckozie** [comment]
On OSX:
Items 1, 4, and 5 now are fixed. Items 2 and 3 are still a problem.

On Windows:

**Comment by cdwhitfield73** [comment]
Still can't duplicate this on Windows, but did notice that I cut a few corners in that flex was not "fully" implemented on the tHelps pane.  This may be the cause of the problem, so I am going to fix it and then you can retest on Mac.

**Comment by cdwhitfield73** [comment]
Was finally able to duplicate this on Windows.  Not really to do with the fact that flex wasn't fully implemented on tHelps, but either way, it is now!  The issue only appears in Notes and only with a smaller screen size.  The issue is that some of the Note categories (Metaphor is the worst one) have a minimum width built into the data that I can't change, so it was overriding the size of the pane.  Then when you switch to a category, like Doublet, that plays nicely, it then changed back to the correct size.  I have addressed this issue by giving the pane a permanent minimum size that will fit all the categories.

**Comment by cckozie** [comment]
Can no longer test item 2 as both my Mac and Windows machines' screens are small so the checking area expands to also take up the tHelps pane.
Everything else looks good.
