### ISSUE TITLE
Strong's numbers showing in definition pane

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1654]
I don't know if this is a source issue or tC issue or what.
![image](https://cloud.githubusercontent.com/assets/8171759/26333474/fb089a40-3f2b-11e7-8962-00bcd4614748.png)

**Comment by benjore** [comment]
- [ ] Start showing from the "Definition" section
- [ ] Show the entire first paragraph

**Comment by benjore** [comment]
QUESTION: This appears to be abnormal content. Check with @jag3773

**Comment by jag3773** [comment]
That is how they will all look soon. Someone determined that this data should be in the text. Check with Perry on what he prefers.

**Comment by cckozie** [comment]
Waiting for import of new resources

**Comment by jag3773** [comment]
Just confirmed with Perry that we will move these entries to the bottom of the tW articles so that they show last.
