### ISSUE TITLE
Multiple problems with links in tHelps

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1665]
0.6.26.6
Screenshot from tW, Apostle
![image](https://cloud.githubusercontent.com/assets/8171759/26430785/e62f76be-40bd-11e7-9969-c48000acdb62.png)

All of the blue text in this screenshot appear to be links.
1. In each case, when I hover over one of the blue text fields, the text becomes underlined indicating a link, but the cursor changes from a pointing (arrow) cursor to an edit cursor. It should be the hand cursor.
2. When clicked on, the following links do nothing: How to translate unknowns, authority, disciple, the twelve, and all of the verses listed under Bible Reference, and all of those listed un Examples from Bible stories
3. Clicking on either James (son of Zebedee) or Paul opens the tHelps expansion pane. Clicking on the links inside the expansion pane sometimes brings up a door43 window (e.g. clicking on Paul in tHelps and then How to translate names in the expansion pane), sometimes they do nothing (e.g. clicking on Christian in the expansion window), and sometimes they replace the content in the expansion window but don't provide a way back to where you came from (e.g. clicking on Jewish leaders in the expansion pane)

**Comment by cdwhitfield73** [comment]
Much, if not all, of this has been addressed.
