### ISSUE TITLE
Target translation is not displayed in scripture pane or in Select area

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1668]
0.6.26.6
![image](https://cloud.githubusercontent.com/assets/8171759/26433349/27b1c01c-40d0-11e7-8dd3-8d18a4210f87.png)

I see that there is text in the project for Eph 1:5, but it is not showing in tC.
[ar_eph_text_ulb.zip](https://github.com/unfoldingWord-dev/translationCore/files/1027801/ar_eph_text_ulb.zip)

Imported from https://git.door43.org/pjoakes/ar_eph_text_ulb

**Comment by mannycolon** [comment]
@cckozie hey could you please give me more information. do you remember what you did? and can you pinpoint what ay have caused this??

**Comment by mannycolon** [comment]
Does this object look familiar to anyone ??? @cckozie @ihoegen @klappy @cdwhitfield73 @RoyalSix @EllDoubleYew 
```
{
  "1": {
    "-1": "Test of a new project."
  }
}
```

**Comment by mannycolon** [comment]
@cckozie Never mind I figured it out.

**Comment by cckozie** [comment]
@mannycolon I just started tC, opened the project with tW, and that's what I see. Happens every time for me on my Mac.
