### ISSUE TITLE
Scripture Pane Language Name doesn't match the actual translation

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#1672]
See the far right pane - both in the dropdown and now as the heading it reads "Russian" but it is actually "Swahili" 

![screenshot 2017-05-25 16 45 10](https://cloud.githubusercontent.com/assets/13352518/26469935/c8136a8a-4169-11e7-9fdf-6fa1a1a42d38.png)

**Comment by benjore** [comment]
This happened when I was supposed to be in an Ephesians project, but Titus was actually loaded.

**Comment by cckozie** [comment]
I think this is part of the larger problem of data corruption when switching projects or tools and is related to issues #1532, #1583, and #1668

**Comment by cckozie** [comment]
0.7.0
I've seen this again. I did a test of 20 iterations of changing project, language, tool in 0.6.26.8. Keeping those same 4 projects, my first test with 0.7.0 caused this issue. Looking in the Resources folder, it looks like everything is good. It appears to be just a problem with the language title in the scripture pane. Exiting tC and then reopening the project does not fix the problem.
[fr_eph_text_ulb.zip](https://github.com/unfoldingWord-dev/translationCore/files/1043223/fr_eph_text_ulb.zip)

![image](https://cloud.githubusercontent.com/assets/8171759/26658818/34098d10-4632-11e7-807a-3952e0c3a695.png)

**Comment by cckozie** [comment]
This was handled in other issues.
