### ISSUE TITLE
Clicking Skip invalidates next check

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1677]
Bug found on the field:
1. Go to a verse that already has a check-mark beside it, where the verse immediately following it also has a check mark.
2. Decide that the first of the two has been incorrectly checked, hover over the highlight to undo it, then click "Save & Continue" to come back to it later.
3. A pop-up loads that presents 2 options: Skip or Close.  If Skip is selected, a message loads that says "Some selections are no longer valid and are removed."  (That comment only appears if the next verse has already been checked.)
4. The only option presented after "Some selections are no longer valid and are removed." is OK.  But clicking on OK then causes a problem.  It removes the highlighted text from the next verse and undoes the check mark for the next verse.

(And the same is also currently happening in reverse -- if you clear the 2nd checked verse in a row then click "Save & Previous".) (edited)

**Comment by mannycolon** [comment]
@klappy what is the purpose of "Some selections are no longer valid and are removed." in other words what causes that alert to show up and why?

**Comment by mannycolon** [comment]
I ask you because I think you implemented it and I'm not quite sure why we have it there.

**Comment by klappy** [comment]
If the selection is not found in the verse, it alerts the user.
For example, if a word is previously highlighted, and it got edited somehow, and the check is no longer valid.

We may need to consider removing the automatic cleanup, and just notify the user without deleting the highlight.

The current method is aggressive and maybe we just alert and show them the previous selection in the alert and let them do something about it instead of assuming they want us to delete it.

**Comment by klappy** [comment]
@benjore @cckozie: What do you think of the above change from what we currently have implemented?

**Comment by cckozie** [comment]
@benjore @klappy My initial thought is that it would be really confusing how to properly represent that situation in the UI if we show highlighted text that is invalid because, for instance, the ULB got updated. Would they make the connection that there is highlighted text but no check mark? Should we switch the highlighting to a different color if it's invalid? I do see what we're currently doing as a problem too, because when the error dialog is up, the user cannot see the screen and really does not know what the real problem is. We should discuss to see if there's a better solution.

All of that said, the underlying issue that was reported does need to be figured out and fixed. The system is inappropriately removing the highlighting of check B when the user unselects the text in check A.

**Comment by cckozie** [comment]
@klappy I found a slightly different use case, but probably the same issue. I'm on a check for which my project has no text, so I skip the check, then make a selection for the next check and continue on. When I come back the review the checks, I again hit the one that I need to skip because that verse has no text in my project. When I click the Skip button it invalidates and removes the selection for the following check.

**Comment by cckozie** [comment]
0.7.0
This is better now, but I have found a repeatable failure case.
