### ISSUE TITLE
Need visual indicators in the checking area when edits and comments have been performed on the check

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1679]
As a checker I would like to be able to see on any given check (regardless of whether or not a selection has been made) a visual indication of when there have been edits and/or comments made to the check so that I don't have to open the edit or comment box to see that indication.

**Comment by cckozie** [comment]
I believe this will be dealt with by other future features.

**Comment by benjore** [comment]
Covered in #1722
