### ISSUE TITLE
Take Apps Out Of Codebase

### ISSUE THREAD

**Issue by RoyalSix** [unfoldingWord/translationCore#168]

**Comment by ihoegen** [comment]
One thing that needs to be done with this is renaming manifest.json to package.json, then npm install --save babel-preset-react. This needs to be done for each package, then a .babelrc file needs to be created, and in it is an Json object with the field preset equal to ["react"]

**Comment by RoyalSix** [comment]
If you have a better understanding, you might want to take this issue, unless you have any reason not to? :)

**Comment by ihoegen** [comment]
My only reason not to is that I want to share. If you have nothing else to do, I'd be glad to let you do it, and I could just do the package.json part.

**Comment by RoyalSix** [comment]
Yea true! Ill work on it, Ill let you know if I have any problems!
