### ISSUE TITLE
Error message when uploading

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1681]
I was logged in with username: qa98, password: qa98
![image](https://cloud.githubusercontent.com/assets/8171759/26505778/11d6a476-4218-11e7-9ce4-6080b03176b4.png)
![image](https://cloud.githubusercontent.com/assets/8171759/26505844/4cffb75e-4218-11e7-8109-ccdd678a658a.png)
[es-419_eph_text_ulb.zip](https://github.com/unfoldingWord-dev/translationCore/files/1032600/es-419_eph_text_ulb.zip)

**Comment by cdwhitfield73** [comment]
The user token was not being persisted properly and had become invalid.  I fixed the persistence issue so the token is being stored with the current user info when the app is closed.  I also added proper error handling message to the user if the token becomes invalid.

**Comment by cckozie** [comment]
0.6.26.8
It now prompts user to re-login if the token has been lost.
