### ISSUE TITLE
Project imports from user's repo, but not using the URL

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1682]
No problems importing the project when I'm logged in as qa95 and select it from the list of my projects. But if I enter the URL, I get the error.
https://door43.org/u/qa95/fr_eph_text_ulb
![image](https://cloud.githubusercontent.com/assets/8171759/26509512/10775e4a-4227-11e7-803e-2bf49928027e.png)

username: qa95, password: qa95

**Comment by cckozie** [comment]
It does work if I add ".git" to the URL.

**Comment by cdwhitfield73** [comment]
Had me stumped for a minute on this one.  It's not the .git causing the problem.  That was already accounted for.  It's because you are using the redirect version of the url "door43.org/u/" instead of "git.door43.org/".  I have updated the regex to handle both versions now.
