### ISSUE TITLE
Remove the block that prevents any New Testament from being loaded in the tW tool

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#1685]
- [x] Keep OT blocked
- [x] Add tests
  
Implemented in conjunction with #3175

**Comment by RoyalSix** [comment]
@benjore So if I'm not mistaken, the projects that are supported are the following:
In developer mode: any projects
Not in developer mode:
- tW NT
- wA NT

**Comment by benjore** [comment]
@RoyalSix Yes, that is correct.

**Comment by cckozie** [comment]
Works in 1.0.0 (71a9a28)
