### ISSUE TITLE
Dynamic Next/Previous Buttons

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#1687]

**Comment by Thajny** [comment]
![navigation](https://cloud.githubusercontent.com/assets/21183377/26603308/f824c602-454b-11e7-9de6-04fbbf9bb71e.png)

**Comment by benjore** [comment]
![tranlsationwords full scrip 24](https://cloud.githubusercontent.com/assets/21183377/25441357/9956cdd6-2a67-11e7-97c5-b4f872e65024.png)
![tranlsationwords full scrip 28](https://cloud.githubusercontent.com/assets/21183377/25441358/9957349c-2a67-11e7-9f2a-f582c17c0779.png)

**Comment by benjore** [comment]
Rendered obsolete by #1748
