### ISSUE TITLE
Dynamic Instructions for "Select" Card

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#1688]

**Comment by Thajny** [comment]
![select card instructions](https://cloud.githubusercontent.com/assets/21183377/26601286/f4e20d8a-4544-11e7-9651-e11cefab44a8.png)
![select card](https://cloud.githubusercontent.com/assets/21183377/26601285/f4dda06a-4544-11e7-9ee7-024dfafe15cc.png)

**Comment by benjore** [comment]
![tranlsationwords full scrip 24](https://cloud.githubusercontent.com/assets/21183377/25441357/9956cdd6-2a67-11e7-97c5-b4f872e65024.png)
![tranlsationwords full scrip 28](https://cloud.githubusercontent.com/assets/21183377/25441358/9957349c-2a67-11e7-9f2a-f582c17c0779.png)

**Comment by benjore** [comment]
Dup of #1219
