### ISSUE TITLE
Don't reset tHelps to the top when user clicks on a link

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1701]
# Overview 
When a user clicks on a link in the tHelps pane it opens a window to view the content, but at the same time it resets the tHelps pane to the top of the topic. This is annoying to the user who is reading down the tHelps pane and viewing additional info as he goes.

**Comment by mannycolon** [comment]
# Tasks
- [ ] [2] move logic that resets the tH scroll bar to the appropriate react life cycle funct.
