### ISSUE TITLE
Provide a way for errors users encounter to be sent to us.

### ISSUE THREAD

**Issue by EllDoubleYew** [unfoldingWord/translationCore#171]
> As a translation checker I want a way to easily report my errors to the translation Core development team so that they are aware of my issues.

This has potential to be an epic but a smaller one. Give a second button if a user encounters an error that lets them report it. That would just send one of us an email containing the error and system information so we can see what we need to fix before it becomes too big of an issue.

**Comment by ihoegen** [comment]
As per Spike #517 I think the best way to implement this would be using HockeyApp. It would integrate with our Feedback system as well, so that users can describe bugs that we don't catch
