### ISSUE TITLE
Project Import Check: License Check

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#1710]
- [x] If the (c) status is in the manifest and one of the accepted ones, the pre-flight check continues to the next check without stopping at the license check
- [x] If "none of the above" is selected, then the project import is aborted.

**Comment by mannycolon** [comment]
@benjore @cckozie @klappy can I get a list of the project accepted Licenses?

**Comment by mannycolon** [comment]
# Tasks
- [3] make an action to check manifest for license type.
- [2] write code to display license step in pre-flight check

**Comment by cckozie** [comment]
Handled by another issue.
