### ISSUE TITLE
Project Import Check: Manifest Check

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#1711]
- [x] free-form the language code for now
- [x] Books of the Bible from a dropdownlist (format "John (jhn)" using the USFM standard codes)

**Comment by klappy** [comment]
## Tasks
- [3] Manifest Check: Check for required manifest data attributes for tC
- [2] Manifest Check: Write Tests for good and bad manifests
- [2] Manifest Check: Ensure Manifest Check runs as Project is loaded 
- [8] Manifest Check: Create simple UI form for editing manifest attributes
    - Book ID
    - Language ID
    - Direction
    - Others?
<img width="1136" alt="screen shot 2017-07-31 at 1 39 16 pm" src="https://user-images.githubusercontent.com/118073/28790066-b030aea8-75f5-11e7-9ff5-b98b0727dbe6.png">

**Comment by cckozie** [comment]
Covered by other issues.
