### ISSUE TITLE
Project Import Check: Merge Conflicts Check

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#1712]
Give list of merge conflicts.

**Comment by cckozie** [comment]
Conflicts in tS project chapter 1, chunk 1 and chunk 7
https://git.door43.org/tc01/en-x-demo1_php_text_ulb

**Comment by RoyalSix** [comment]
## Tasks:
- [ ] [4] Get merge conflicts separated by `<<<<<` markers
- [ ] [3] Display list of merge conflicts (Basic styling)

**Comment by cckozie** [comment]
Holding until merge conflicts is complete.

**Comment by cckozie** [comment]
Covered by other issues.
