### ISSUE TITLE
Integrate reportFilter.js functions with the report view UI

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord/translationCore#172]
convert searched word into a query so that it could be handled by the reportFilter component. in other words, when an user types in a word in the search box it will be parse to a query that will be used by the reportFilter component.

**Comment by EvanWiederspan** [comment]
Wanna make the title shorter and add a description? What does this even mean?

**Comment by mannycolon** [comment]
@EvanWiederspan I hope this is more clear now, before it was just a note/reminder for myself.
