### ISSUE TITLE
Show edit/comment/bookmark status indicators

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#1722]
- [ ] Indicators in blue bar
- [ ] Bookmark toggle

**Comment by benjore** [comment]
![status icons](https://user-images.githubusercontent.com/21183377/27098036-cee194dc-503b-11e7-82b0-74cb379282ec.png)

**Comment by mannycolon** [comment]
@benjore hey is the bookmark icon still going to be a button?

**Comment by mannycolon** [comment]
# Tasks

- [1] Design icon indicators in the verseCheck card.
- [1] Add functionality for enabled / disabled icon indicators.
- [2] Add new bookmark toggle button.
