### ISSUE TITLE
Make reports an internal component and remove new window option

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord/translationCore#173]

**Comment by EvanWiederspan** [comment]
@mannycolon Why do you feel that this change is necessary? At best I don't think that putting the reports in app with everything else will make them easier to read or view, i actually think it'll make them harder to read because you'll have so much less viewing space

**Comment by mannycolon** [comment]
@EvanWiederspan Now its actually rendering as another div in the main index.html. so when opened  it will render in front of all the components. thus, it will have all the screen space. In addition, when closed it will only return an empty div.

**Comment by mannycolon** [comment]
@EvanWiederspan if you want you can take a look in my branch mc-new-reportsview
