### ISSUE TITLE
Check has been completed, but bookmark icon is displayed instead of check

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1747]
Problem found in the field.
Opened a project in tW and switched to tN. One of the checks that had been completed (selection was displayed) but the bookmark icon was displayed in the check menu.
https://git.door43.org/russp41/hi_tit_text_reg

**Comment by russp41** [comment]
I experienced what might be the same problem. I installed 0.7.1 alpha, then opened Bahasa Indonesia Ephesians, tW. I realized that Bahasa Indonesia Titus, tW was the project & tool I really wanted, so opened it. I noticed that the checks for Blameless (Tit 1:7, 2:8) were each flagged in the left menu pane as having bookmarks enabled, but the bookmark flags in the Select Card for each verse were disabled. After some trial and error, I found that switching to tN and back to tW toggled this state (flags on the Select Card out of sync with left pane, then flags in sync with left pane).
![titus 1-7 2-8 out of sync again](https://user-images.githubusercontent.com/10854620/27202866-3d5f4ed4-51f1-11e7-99db-0f3cdb5f297a.jpg)
![titus 1-7 2-8 flag back in sync again](https://user-images.githubusercontent.com/10854620/27202865-3d5ddd6a-51f1-11e7-8e9a-5bf98e755281.jpg)

**Comment by russp41** [comment]
Here are other screen captures of the bookmarks incorrectly enabled or disabled.
![titus 1-7 bookmark not set but flag is set](https://user-images.githubusercontent.com/10854620/27202995-ca4d9968-51f1-11e7-943e-c8b724f9bee8.jpg)
![titus 1-7 bookmark set but flag is not set](https://user-images.githubusercontent.com/10854620/27202993-ca4c10ac-51f1-11e7-8211-dd539b2a29d4.jpg)
![titus 2-8 bookmark not set but flag set](https://user-images.githubusercontent.com/10854620/27202994-ca4cf27e-51f1-11e7-991a-5b4db15499c5.jpg)
![titus 2-8 bookmark set but flag not set](https://user-images.githubusercontent.com/10854620/27202992-ca49e980-51f1-11e7-81ed-c418149b0bee.jpg)

**Comment by mannycolon** [comment]
## Task

- [ ] [3] Spike: debug code to find the root cause of the bug.
- [ ] [2] Fix bug with out of sync menu and the bookmark button.

**Comment by mannycolon** [comment]
@cckozie I'm having trouble trying to recreate this bug.

**Comment by cckozie** [comment]
@mannycolon I just now got the new build installed. I'll do some testing to see if I can recreate it.

**Comment by cckozie** [comment]
@mannycolon I cannot replicate the problem in 0.7.1-beta.3. If it's OK with you I'll go ahead and close the issue.
