### ISSUE TITLE
Project Import Stepper

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#1750]
- [x] Stepper
- [x] Navigation

**Comment by mannycolon** [comment]
@benjore @klappy @cckozie can I get a more in depth description of what needs to be done here?

is this related to the UI? and is so can I get the mock up design for this?

**Comment by cckozie** [comment]
@mannycolon See #691, it is the high level description of the epics attached to it, and has a link to the UI designs.

**Comment by mannycolon** [comment]
# Tasks
- [3] Design Import Stepper front end.
- [2] Design Import Stepper back end.
- [3] Implement Import Stepper Navigation functionalities.

**Comment by cckozie** [comment]
Handled by another issue.
