### ISSUE TITLE
Project Import Check: "Display Report"

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#1752]
- [ ] Generate List on UI
  - [x] List missing verses
  - [ ] List verses with USFM issues

**Comment by mannycolon** [comment]
https://github.com/unfoldingWord-dev/translationCore/issues/2190

**Comment by cckozie** [comment]
Holding until all USFM import stories have been complete.

**Comment by cckozie** [comment]
There is currently no report on anything except missing verses. Do we want to list missing or misplaced chapter markers?

**Comment by cckozie** [comment]
Closing as it is superseded by #3309
