### ISSUE TITLE
Rewrite Project/Tool loading

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1767]

**Comment by mannycolon** [comment]
# Overview 
The project loading process needs to be cleaned up so that it is more maintainable.

# Tasks
- [4] Rewrite project loading actions
- [1] Extract code out of project loading actions into helpers

**Comment by klappy** [comment]
Most of the code has been refactored already.
## Tasks
[4] Organize the code from GetDatActions, openProjectActions into new files:
  - ToolSelectionActions.js
  - ProjectLoadingActions.js
  - ToolLoadingActions.js
  - (ResourceActions.js)
  - Todos for new actions


[3] Debug project/tool loading to fix potential issues.
  - Update actions references from their new files.

[1] Propose actions to refactor for project/tool loading.
[8] Refactor actions for project/tool loading as needed.

   - rename actions/constants
   - remove unused actions/constants
   - Group/Organize Constants

**Comment by mannycolon** [comment]
ProjectSelectionActions.js
ToolSelectionActions.js
ProjectLoadingActions.js
