### ISSUE TITLE
Rewrite tool loading

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1768]

**Comment by mannycolon** [comment]
# Overview 
The tool loading process needs to be cleaned up so that it is more maintainable.

# Tasks
- [ ] [3] SPIKE: Research actions related to the tools that should be refactored.
- [ ] [5] Rewrite all actions related to tool loading/rendering
       - setToolName, setToolTitle, setDataFetched, saveModules, saveModuleFetchData, setModuleView
