### ISSUE TITLE
Organize Reducers

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1771]

**Comment by mannycolon** [comment]
- Renaming reducers.
- Merging reducers that should be together or separating them if needed.

**Comment by RoyalSix** [comment]
# Overview
There are too many reducers. The reducers can be condensed by combining by similarities/categories. 
The reducers can be combined on a file level or folder level

# Tasks
  - [ ] Determine which reducers need combining
  - [ ] Combine reducers
## Tests
- [ ] Write tests to ensure that all functionality in old reducer structure is maintained

**Comment by klappy** [comment]
@mannycolon @RoyalSix: Should we consider nesting all reducers under props.reducers.[reducerName] in this Story? If so we could add a task for that.

**Comment by klappy** [comment]
## Tasks
- [4] currentTool, toolsReducer, coreStoreReducer can be combined.
- [1] statusBarReducer should move to settingsReducer.

- [4] refactor moduleSettingsReducer
  - moves to settingsReducer, nested as toolsSettings: {}
  - update references from moduleSettingsReducer to settingsReducer.toolsSettings
  - rename references of module in names to tool (actions and constants).
  -  delete modulesReducer file.
- [1] settingsReducer
- [1] BodyUIReducer renamed to homeScreenReducer

Steps to organize a reducer:
  - remove as many as possible that aren't being use, or shouldn't be used.
  - move remaining ones to other reducer files if possible.
  - rename existing reducer if any need to remain.
  - update references to the reducer.
