### ISSUE TITLE
Move all authentication tokens into a single file. 

### ISSUE THREAD

**Issue by ihoegen** [unfoldingWord/translationCore#18]
As a developer, I want a centralized place to store my authentication tokens, so that I may have easy setup.

**Comment by ihoegen** [comment]
Refereneced in #15

**Comment by klappy** [comment]
What do you guys think of keeping things in the Review column until I sign off on them. Reserve the Done column for QA or Product Owner?

**Comment by klappy** [comment]
NM, That's what closed is for, I don't want to add any unnecessary layers/steps.

**Comment by klappy** [comment]
Is this a duplicate of #15?

**Comment by RoyalSix** [comment]
Yea I think that's why it got closed.
