### ISSUE TITLE
[0] BCV: Update how Bibles are stored on FS

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#1814]
## Filesystem
- [x] [3] update how bibles are stored
  - [x] chapter level files
  - [x] target bible stored in the project's root folder
  - [x] reference bibles stored in ~/translationCore/resources/bibles/[bible-id]/[v]/...
  - [x] archive source files that were imported ./.apps/translationCore/importedSource/...

**Comment by mannycolon** [comment]
@klappy ` archiving source files that were imported ./.apps/translationCore/importedSource/...` means it won't open with tS. are we ok with that?
