### ISSUE TITLE
[0] Gather all resources being used in a project

### ISSUE THREAD

**Issue by RoyalSix** [unfoldingWord/translationCore#1830]
Get sources from public API.

## Bibles

- Catalog: https://api.unfoldingword.org/uw/txt/2/catalog.json
Must check catalog version before updating ULB/UDB, since only latest is represented.
Get the .usfm for each book and parse.
  - UDB v9: https://api.unfoldingword.org/udb/txt/1/udb-en/
  - ULB v9: https://api.unfoldingword.org/ulb/txt/1/ulb-en/
  - UGNT v0.2: [CNTR0.xlsx](https://github.com/unfoldingWord-dev/translationCore/files/1069845/CNTR0.xlsx)
  - UHB v4.20: https://github.com/openscriptures/morphhb/tree/master/wlc

## translationHelps
Must update Notes at the same time as ULB to be in sync.
- translationWords v5: https://git.door43.org/Door43/en_tw/src/v5/bible
- translationNotes v2: https://git.door43.org/Door43/en_tn/src/v2
- translationAcademy v6: https://git.door43.org/Door43/en_ta/src/master/translate

## Lexicons
- UGL v0?: https://github.com/translatable-exegetical-tools/Abbott-Smith/blob/1.1/abbott-smith.tei.xml
- UHL: ? https://unfoldingword.org/uhal/

**Comment by klappy** [comment]
@benjore @jag3773: 

Is the UHB from this link correct? 
https://github.com/openscriptures/morphhb/tree/master/wlc

Also, what version should we use for this? Only number I see is wlc 4.20.
Do we want to fork it and use our own version number?

**Comment by klappy** [comment]
lc: "en"
mod: "1490790472"
-vers: [
-{
mod: "1490790472"
name: "Unlocked Literal Bible"
slug: "ulb-en"
-status: {
checking_entity: "Wycliffe Associates"
checking_level: "3"
comments: ""
contributors: "Wycliffe Associates"
publish_date: "20170329"
source_text: "en"
source_text_version: "9"
version: "9"
}
-toc: [ … ]
}
-{
mod: "1487635200"
name: "Unlocked Dynamic Bible"
slug: "udb-en"
-status: {
checking_entity: "Wycliffe Associates"
checking_level: "3"
comments: ""
contributors: "Wycliffe Associates"
publish_date: "20170221"
source_text: "en"
source_text_version: "9"
version: "9"
}
-toc: [ … ]
}
]

**Comment by klappy** [comment]
@benjore: Which is the right version of the notes?
I'm getting two sets of notes depending on where I look? That seems strange.

https://git.door43.org/Door43/tn-en/raw/master/eph/01/01.md
https://git.door43.org/Door43/en_tn/src/master/eph/01/01.md
https://api.unfoldingword.org/ts/txt/2/eph/en/notes.json

**Comment by klappy** [comment]
@benjore @jag3773: Where should we get the UHAL from? Our ufw page gives us no further links. https://unfoldingword.org/uhal/

**Comment by benjore** [comment]
@jag3773 said that the tN will soon be in the API in the latest format (API V3). I'd suggest we wait for that.

**Comment by klappy** [comment]
Moved to Wiki for future updates.

**Comment by jag3773** [comment]
The WLC location is correct.  No need to fork right now.

If we can wait until end of June we'll have all our English source content tagged and consistent in DCS.  Will that work @klappy and @benjore ?  It will all be in https://git.door43.org/Door43-Catalog .

**Comment by jag3773** [comment]
Note that if you want previews of what the content will look like I can give you that too.  It's not significantly different than current but there are some minor changes in some of the source content (like strong's numbers now appearing in the tW).
