### ISSUE TITLE
[0] Architect internal file structure

### ISSUE THREAD

**Issue by RoyalSix** [unfoldingWord/translationCore#1833]
## Folder Structure
In the code folder structure `./static/`:
- resources/
  - bibles/
    - udb-en/v9/
    - ulb-en/v6/
    - ugnt/v0/
    - uhb/v0/
  - translationHelps/
    - translationAcademy/v5/
    - translationNotes/v0/
    - translationWords/v0/
  - lexicons/
    - en-UGL/v0/
    - en-UHL/v0/

## Bibles
In the folder structure of the Bible's name `./static/resources/bibles/`:
- [bible-id]/[v0]/
  - [book-id]/
    - [chapter].json

## translationNotes `./static/resources/translationHelps/`:
- translationNotes/v0/
  - index.json
  - groups/
    - eph/
      - figs-metaphors.json
      - ...json

## translationAcademy `./static/resources/translationHelps/`:
- translationAcademy/v0/
  - index.json
  - content/
    - figs-metaphors.md
    - ...md

## translationWords `./static/resources/translationHelps/`:
- translationWords/v0/
  - index.json
  - groups/
    - eph/
      - adoption.json
      - ...json
  - content/
    - adoption.md
    - ...md

## Lexicons `./static/resources/lexicons/`:
- en-UGL/v0/
  - index.json (key is strongs number, name is greek word)
  - content/
    - [strongs number].json

**Comment by klappy** [comment]
created wiki page
