### ISSUE TITLE
[2] SPIKE: Research actions related to the tools that should be refactored.

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord/translationCore#1834]

**Comment by klappy** [comment]
## Recommendations
Think of actions being abstracted from fs/db/http/api, that way adapters can be built to do the read/write to each storage type and actions stay light.
- [ ] FS actions should be abstracted if possible, moved to helpers. 
  - [ ] GroupsDataActions: verifyGroupDataMatchesWithFs/getUniqueObjectsFromFolder/contains
  - [ ] checkDataLoadActions: loadCheckData
  - [ ] contextIdActions: loadCurrentContextId
  - [ ] GetDataActions: lots... may need abstraction and not just move
  - [ ] RecentProjectActions: getProjectsFromFolder, CSV functions
  - [ ] ResourcesActions: loadBiblesFromFS
  - [ ] ToolsActions: getDefaultModules, fillDefaultModules
