### ISSUE TITLE
Unable to import projects in 0.7.1-beta.3

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1856]
The screen dims, no error message, nothing in the console log.
I assume this is due to refactoring.

**Comment by cckozie** [comment]
I think this has to do with projects that have missing verses. In beta.3 after the import "fails", if I close and reopen tC I am able to load the project. It then gives me the missing verses error message.

**Comment by klappy** [comment]
- [3] Update missing verses check to check our new chapter.json files.
- [5] Debug why it's stuck in a loop.

**Comment by cckozie** [comment]
Project that causes failure is https://git.door43.org/tc01/fr_eph_text_reg
Nothing in console log

**Comment by russp41** [comment]
I experienced this behavior importing a project that has verse bridges, which tC seems to treat as missing verses. 

The project is North Western Kolami (kfb):
https://git.door43.org/russp41/kfb_eph_text_reg

There are two verse bridges. One is Eph 1:19-20 and the other is Eph 2:11-12. After closing the dimmed tC screen, the project can be opened but shows blank verses at Eph 1:20 and 2:12. Look at 'God' in Words to see the blank verse at Eph 1:20 and 2:12. In fact, the content of 1:20 and 2:12 is included with 1:19 and 2:11, respectively. See 1:19 at 'believe, believe in, belief' and 2:12 at 'flesh'.

The tC project was created by using a SFM file from ParaTExt, importing the file into tS with its USFM import, then uploading the project to Door43, then importing from Door43 into tC. 

The original ParaTExt file 50EPHKOL.SFM was renamed to 50EPHKOL.TXT to attach below.

![blank verses](https://user-images.githubusercontent.com/10854620/27498138-ab5262ec-582b-11e7-9976-ad0e71c917e6.jpg)

[50EPHKOL.TXT](https://github.com/unfoldingWord-dev/translationCore/files/1098898/50EPHKOL.TXT)

**Comment by cckozie** [comment]
This does not appear to be a problem anymore in beta.11, although I still cannot load any projects with tW.

**Comment by cckozie** [comment]
It is broken again in beta.54. Same behavior as in the first comment.

**Comment by klappy** [comment]
This appears to be an issue with importing an existing tC project that has already "migrated" tS .txt files to tC .json files.

**Comment by klappy** [comment]
This QA Fail issue appears ambiguous to address and fix. 
Is there a clear list of directions to recreate?
