### ISSUE TITLE
Confusing first screen

### ISSUE THREAD

**Issue by ChrisJarka** [unfoldingWord/translationCore#186]
With both navigation arrows being white, I do not which one to click on. 
Perhaps if the navigation arrow that does work is grayed out - it would be more helpful to the user?
![what does this active arrow do](https://cloud.githubusercontent.com/assets/9850185/19274349/d77b37ec-8f9d-11e6-83a2-8deea7ee3393.png)

**Comment by EllDoubleYew** [comment]
PR is in at #215
