### ISSUE TITLE
Wording on 'Load your first project' screen

### ISSUE THREAD

**Issue by ChrisJarka** [unfoldingWord/translationCore#187]
Is this the screen that they will see only for their **first** project? Does anyone else think that the translator might think that it means the first translation work that they did?

Then also, see the side text as suggested changes to the text.

![wording on loading first project](https://cloud.githubusercontent.com/assets/9850185/19274501/4c69ef44-8f9e-11e6-9871-1e36f123ad16.png)

**Comment by klappy** [comment]
Thanks Christine, What text do you recommend?

**Comment by mannycolon** [comment]
#218
