### ISSUE TITLE
Error on loading project

### ISSUE THREAD

**Issue by ChrisJarka** [unfoldingWord/translationCore#190]
I have a couple of questions on this error message.

What does ENOENT mean? Can the word 'error' or even 'notice' can replace it? (IMHO error messages are best worded if they do not point error to the end-user)
Translation is not spelled correctly.
What is a manifest? Maybe continuing to use the word 'project' would be better?

![mis spelling](https://cloud.githubusercontent.com/assets/9850185/19274788/515ebc04-8f9f-11e6-872c-8439f8188341.png)

**Comment by EllDoubleYew** [comment]
@klappy I know that the original idea for handling this is to have a "Show more information" button. Is that still the method that you want me to implement? Just have a generic "An error occured" message and provide a way for the user to get more technical information if it is needed?

**Comment by klappy** [comment]
Let's keep it generic for now, and have the button/link for more info.
