### ISSUE TITLE
Presentation of the translation notes information

### ISSUE THREAD

**Issue by ChrisJarka** [unfoldingWord/translationCore#191]
See on this screenshot how the YAML is not rendered correctly?

![yaml not rendered correctly](https://cloud.githubusercontent.com/assets/9850185/19274884/c0cfba20-8f9f-11e6-8894-2ea9fb38e30d.png)

**Comment by mannycolon** [comment]
@ChrisJarka what would you like us to render it instead??? Would it make sense if we just get rid of the YAML??

**Comment by ChrisJarka** [comment]
Manny,
IMHO, most of the YAML should stay. There is important information in the YAML that should be present on the tC screen.  Such as: Title of the topic and the dependencies. Perhaps the question and recommended would also be good to add. 
Have you seen how the YAML looks in the tA manuals?

![yaml from ta web](https://cloud.githubusercontent.com/assets/9850185/19327443/11d73fc6-909d-11e6-9f53-e093c33858d6.png)

**Comment by mannycolon** [comment]
@ChrisJarka Just a question, why do you guys use YAML for this instead of Markdown ?? for instance below.
<img width="629" alt="screen shot 2016-10-12 at 8 13 14 pm" src="https://cloud.githubusercontent.com/assets/17072300/19332271/628ad3cc-90b8-11e6-9cb6-069af18006cd.png">

**Comment by mannycolon** [comment]
@ChrisJarka Does this look better?? 
<img width="489" alt="screen shot 2016-10-12 at 8 18 31 pm" src="https://cloud.githubusercontent.com/assets/17072300/19332343/26621a58-90b9-11e6-82f0-a63173eacee6.png">

**Comment by mannycolon** [comment]
@ChrisJarka 
<img width="501" alt="screen shot 2016-10-12 at 8 22 01 pm" src="https://cloud.githubusercontent.com/assets/17072300/19332395/915b4ec4-90b9-11e6-8a84-756760299dcd.png">
