### ISSUE TITLE
Enhancement on Scriptural Context scrolling

### ISSUE THREAD

**Issue by ChrisJarka** [unfoldingWord/translationCore#192]
See the screen shot ....

![scroll together](https://cloud.githubusercontent.com/assets/9850185/19274928/e73060ca-8f9f-11e6-869c-4ef944cc26e9.png)

**Comment by klappy** [comment]
We are looking to only show 1 verse by default. Then a way to click to see the context (verses around it). Will that be okay with you?

**Comment by klappy** [comment]
Should be addressed in new UX/UI
