### ISSUE TITLE
Users should be able to delete resources in the expanded scripture pane

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1936]
I can delete and add resources in the normal scripture pane, but in the expanded I can only add them. If I have 3 resources open and then expand the scripture pane, there is no way for me to swap resources without going back to the normal pane.
An even better solution would be to allow users to change the resources in a pane rather than having to delete and add. See issue #3205

**Comment by benjore** [comment]
Covered in #3642
