### ISSUE TITLE
Error saving project: fatal: Not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by russp41** [unfoldingWord/translationCore#1948]
Version 0.7.1-beta.3
When attempting to Upload the project hi_eph_text_reg, encountered the following error:
Error saving project: fatal: Not a git repository (or any of the parent directories): .git

This error was encountered by two different people, one on Windows 10 and one on Mac.

The original project is from https://git.door43.org/Ludhiana/hi_eph_text_reg
The project was then checked (both Words and Notes) by the Hindi team at the Ludhiana workshop. The checked project that encounters the error is attached in the zip file. 

To recreate the error, unzip the file and with tC not running, copy the resulting folder hi_eph_text_reg to the appropriate folder (the following is for Windows): 
C:\Users\<user>\translationCore folder. 
Then open tC, and try to upload the project hi_eph_text_reg.

[hi_eph_text_reg.zip](https://github.com/unfoldingWord-dev/translationCore/files/1098448/hi_eph_text_reg.zip)

![error saving project](https://user-images.githubusercontent.com/10854620/27491454-6c87d094-5810-11e7-8a47-db8982d6857e.jpg)

**Comment by klappy** [comment]
## Tasks
- [3] Detect if project isn't initialized as a git repo
- [2] Confirmation dialogue for initializing as a git repo

**Comment by cckozie** [comment]
In beta.39 I can now successfully upload the project referenced by Russ.
