### ISSUE TITLE
Scrollbar on wrong side of resource in scripture pane

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1951]
0.7.1-beta.3
![image](https://user-images.githubusercontent.com/8171759/27512467-348dfdc0-5906-11e7-94b1-52ac34f2e8e9.png)

**Comment by benjore** [comment]
French is showing up RTL instead of LTR.

**Comment by benjore** [comment]
@cckozie What is the project that was used?

**Comment by cckozie** [comment]
This was a problem in beta.3 but is no longer an issue in beta.11
