### ISSUE TITLE
Target language not available in scripture pane dropdown list

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1952]
The target language is French in this project, but tC seems to think it's Latin American Spanish
[fr_eph_text_reg.zip](https://github.com/unfoldingWord-dev/translationCore/files/1100041/fr_eph_text_reg.zip)

![image](https://user-images.githubusercontent.com/8171759/27512539-665bf278-5909-11e7-95fb-ca7e2e437ed3.png)

**Comment by mannycolon** [comment]
# Tasks

- [2] Debug wrong target language name in scripture pane drop-down list.
- [1] Fix target language name in scripture pane drop-down list.
