### ISSUE TITLE
[0] Spike: Profile tC on Windows

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord/translationCore#1964]
[1] List all data read from FS when menu item is clicked (contextId changes).
[2] Determine if the above data is read from FS more than once when clicking on a menu item.
[2] Evaluate which components render() has too much logic in it and could affect performance.

**Comment by RoyalSix** [comment]
## Most tasking functions
- loadBiblesChapter
- loadCheckData
(By removing these functions there is virtually 0 zero lag, only other lag time is directly from react state handling the change)

## React Performance Resources:
- https://www.toptal.com/react/optimizing-react-performance
- https://www.toptal.com/react/react-redux-and-immutablejs
- https://medium.com/@alexandereardon/performance-optimisations-for-react-applications-b453c597b191
- https://medium.com/@alexandereardon/performance-optimisations-for-react-applications-round-2-2042e5c9af97
- https://medium.com/@esamatti/react-js-pure-render-performance-anti-pattern-fb88c101332f

**Comment by RoyalSix** [comment]
## React-Redux Performance conclusions:
- Do not pass functions if you can avoid it. Rather, let the child dispatch actions when it wants to. This has the added advantage of moving business logic out of components.
- It is very common to see functions bound to the context of the component inside the render function. This will cause the render() function to create a new function on every render. A much better way of doing the same is handling it in the constructor.
- implementing shouldComponentUpdate
- take all of logic out of render functions, some logic creates new instances of variables therefore cause shallow equality check to fail and make the component re-render. If you pass the component all of its state from the parent then it will not re-render unnecessarily.

**Comment by klappy** [comment]
Good info. We'll have to circle back to this later.
