### ISSUE TITLE
Cannot open any project in 0.7.1-beta.7

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1982]
After selecting the project and tool, when the Loading... dialog goes away I'm back at the Welcome screen. There are no errors in the console log.

**Comment by klappy** [comment]
The existing build is a half implementation of the home screen which requires going back to the Overview/Home after selecting a tool. You should see a Launch button to load the project/tool after they are selected.

**Comment by cckozie** [comment]
I originally was using the old modal, and that's what I wrote up the issue on. If I use the new workflow, it does laugh the project, but the checking screen is blank other than the menu. Then I have no way to get back to another project. After closing and reopening tC, all I can do is log in. The project screen does not show any projects.
![image](https://user-images.githubusercontent.com/8171759/27566127-a737508a-5aa8-11e7-9903-36ca8805ae9d.png)

**Comment by cckozie** [comment]
This is what I get in the log after deleting the translationCore folder, restarting tC, and copying a project into the folder and launching it with the old modal with tW.
![image](https://user-images.githubusercontent.com/8171759/27592601-7f7edfc8-5b1a-11e7-91d8-3de51bfc9502.png)

**Comment by cckozie** [comment]
https://git.door43.org/tc01/fr_tit_text_ulb
I did manage to get this project opened with tN, but when I attempt to launch it with tW I get this in the console:
![image](https://user-images.githubusercontent.com/8171759/27643426-aa9bcece-5be6-11e7-9ef2-373916be4d7b.png)

**Comment by cckozie** [comment]
Projects related to this issue: 
[es-419_tit_text_ulb.zip](https://github.com/unfoldingWord-dev/translationCore/files/1110085/es-419_tit_text_ulb.zip)
[es-419_eph_text_ulb.zip](https://github.com/unfoldingWord-dev/translationCore/files/1110084/es-419_eph_text_ulb.zip)



I received this when attempting to switch from Eph to Titus. I had opened Eph with tN, then attempted to switch to tW where I encountered the expected error as in the above comment. I then changed projects to Titus and received this message.
![image](https://user-images.githubusercontent.com/8171759/27657593-d386a044-5c12-11e7-9028-de08096ea156.png)

I then ended and restarted tC, loaded the Eph/tN project, then switched to Titus/tN. Now I did not get the same error, but the Loading dialog continued to spin:
![image](https://user-images.githubusercontent.com/8171759/27657824-84b34d2c-5c13-11e7-9dd6-b489375283ee.png)

I tried it again without first opening Eph/tN. Titus/tN still does not open, same as above.

**Comment by cckozie** [comment]
This is with beta.21 - It will open correctly in tN
[fr_tit_text_ulb.zip](https://github.com/unfoldingWord-dev/translationCore/files/1115384/fr_tit_text_ulb.zip)

![image](https://user-images.githubusercontent.com/8171759/27738804-1959a1ec-5d72-11e7-8c04-b82e6b8e22b4.png)

**Comment by cckozie** [comment]
Now I can't open it in tN either. Going to delete tC folder and start over.

**Comment by cckozie** [comment]
After deleting the tC folder I am now able to open it in both tN and tW. Able to now import and open multiple projects. Closing this issue.
