### ISSUE TITLE
Improper message on log in screen

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1985]
This was implemented as designed, but the highlighted message only makes sense if the user is logged in locally, but not if the user in not logged in at all.
It also does not make sense to display any of the info on the instruction card once the user has logged in. (see second screenshot)

![image](https://user-images.githubusercontent.com/8171759/27567766-936b271a-5ab3-11e7-9432-de0e647b2595.png)

![image](https://user-images.githubusercontent.com/8171759/27568042-579fa2a4-5ab5-11e7-8f94-8f863a680658.png)

**Comment by benjore** [comment]
Change Instructions to say:

You are currently logged in.

To continue to Projects, click "Continue to Project".

To log out, click "Log out".

**Comment by mannycolon** [comment]
# Tasks

- [1] Update instructions card text for login card.

**Comment by cckozie** [comment]
Not yet in build (beta.54)

**Comment by klappy** [comment]
@mannycolon was this done and included in another PR for another task?

**Comment by cckozie** [comment]
beta-33
When first starting out, the message on the instruction card is correct, but after logging in, the "Please log in... instructions are still displayed.

**Comment by cckozie** [comment]
I think the instruction text when not logged in still needs some work, but we'll fix that when we change from local account to guest user.
