### ISSUE TITLE
Import from online to use listing of repos

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#199]
As a user, I want to see a list of the D43 repos to import so that I don't have to find, copy, paste a URL.

**Comment by ihoegen** [comment]
@klappy For now, is this just a users own projects?

**Comment by klappy** [comment]
That is a good start, eventually it would be good to add other projects, search, sort, filter, but we can create a new user story for that.

**Comment by ihoegen** [comment]
I've created a new user story
