### ISSUE TITLE
SPIKE: Planning for the selecting of the UGNT, UHB, & UDB

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#1997]
We need to make available a basic tool for a few people to use so that the ULB and UGNT text can be aligned. 

Probably Jesse & Klappy need to get together to figure out a quick hack for making MAP available.

**Comment by klappy** [comment]
@benjore: How much detail are we looking to align? All words between the UGNT/UHB and ULB? 
Or are we just looking to align the quotes that are in checks from the ULB?

**Comment by benjore** [comment]
@klappy For my purposes, I only need the quotes that are being checked from the ULB. Practically, it might be easier to do all the words.

**Comment by klappy** [comment]
From my understanding, if we are just wanting to get the alignment of checks that are currently quoted in the ULB to UGNT and UDB, we can do that with the existing UI.

- Perform the checks on UDB and UGNT for the desired books. Select UDB as the target book to check, and repeat with the UGNT as the target book to check.

**Comment by benjore** [comment]
@klappy I'm going to go back on my previous statement about just having the Words aligned. I would like to spec out aligning the whole Bible - starting with Titus & Ephesians > NT > OT. The focus for now will be the ULB in English, but I'd like a solution that will allow for the future alignment of any other Bible translation (UDB, ULB-Hindi, etc.). 

This SPIKE is likely to have a bunch of overlap with #2122 and #2123

**Comment by klappy** [comment]
This document was started for the UGNT => Hindi alignment and can be leveraged as a starting point in planning UGNT => ULB/UDB. 
https://docs.google.com/document/d/1btdDbmcELpQyFLFDlUJ84bt-B6UsrLmWx3mrm-NzG-M/edit#heading=h.e4gfnlypg0ux
