### ISSUE TITLE
Localized User Interface

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#2003]

**Comment by da1nerd** [comment]
@jag3773 @benjore which languages do you want the application localized in?

**Comment by da1nerd** [comment]
You can see which ones I've selected for starters here https://crowdin.com/project/translationcore

**Comment by cckozie** [comment]
@neutrinog I'm running build 0.8.1-alpha.15-ab5cb00 from develop and don't see a way to change languages. Is it hidden somewhere?

**Comment by da1nerd** [comment]
Once the app is opened an the user is logged you can change it from the home screen by clicking on the new menu on the user card.

![image](https://user-images.githubusercontent.com/166412/35750207-13e8a6d0-0809-11e8-99ea-b83882063553.png)

**Comment by cckozie** [comment]
Items not localized on home screen:
First two lines on instructions card
Language name on user card
Text on Go to User button
Log out link
Text on stepper bar
Text on license page behind the (i) icon
![image](https://user-images.githubusercontent.com/8171759/35815991-5fd2a606-0a5f-11e8-86ac-b221f00b6c1a.png)

**Comment by da1nerd** [comment]
@cckozie some of those things are localized in my latested PR. Also, only a few of the items show real-ish translations because @jag3773 wants to review all of our strings before we formally translate everything. Therefore most of the words will actually show up in English by default. So for now it may not be super easy for  you to actually test what's been localized.

**Comment by cckozie** [comment]
0.8.1-alpha.15-53e1b0c
Language set to en_US
![image](https://user-images.githubusercontent.com/8171759/35870790-2b6009da-0b28-11e8-90d3-0474754a12e6.png)

**Comment by da1nerd** [comment]
aha! now that's a bug I can fix :)

**Comment by da1nerd** [comment]
fyi this is related to https://github.com/unfoldingWord-dev/translationCore/issues/3750 (ui for changing the locale)

**Comment by da1nerd** [comment]
The initial localization has been completed in https://github.com/unfoldingWord-dev/translationCore/issues/2265. I'm closing that issue and we can continue discussion here.

**Comment by da1nerd** [comment]
@cckozie I condensed all of the locale issues into this one (closed them). Everything is still linked so we can see them.

**Comment by cckozie** [comment]
I'm holding all of the localization issues until all the related issues get to QA

**Comment by cckozie** [comment]
Passing all held localization issues with remaining problems in newer issues.
