### ISSUE TITLE
Translation Correct, Nothing to Select

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#2011]
## User Story

As a checker, I want to mark a check as correct without selecting it so that I can indicate that a check has been completed even if a selection cannot be made. 

![image](https://user-images.githubusercontent.com/13352518/34441937-71ad3a74-ec84-11e7-8c68-9099a729fbb6.png)

![image](https://user-images.githubusercontent.com/13352518/34441942-7737449e-ec84-11e7-885a-e54410b400ad.png)

![image](https://user-images.githubusercontent.com/13352518/34441944-7bad424e-ec84-11e7-9155-91f2aedbbe7c.png)

![image](https://user-images.githubusercontent.com/13352518/34441950-8228f1a4-ec84-11e7-923f-2ab86a35c8fa.png)

**Comment by klappy** [comment]
- (M+) UI Changes
- (L) Data storage for selection to handle attribute of "no selection needed"
- (M) Menu handling new use case for completion (check completed)
- (M) ToolCards percentages to calculate based on new use case
- (M) Export to CSV to handle use case

**Comment by RoyalSix** [comment]
Is this going to be in the menu?

**Comment by benjore** [comment]
This will toggle the green checkmark in the side menu. 

- [ ] Add an item in the filter for "No Selection Needed"

**Comment by mannycolon** [comment]
Verified on b1cd66e

**Comment by cckozie** [comment]
@benjore - 
1. The issue doesn't specify whether this feature is applicable to both tW and tN. It has been implemented in both. Is that what you wanted?
2. We didn't see anything in the issue about what you wanted in the selections.csv file when the user clicks on the No selection needed.

**Comment by benjore** [comment]
1. Implemented in tN & tW is desired. 
2. It seems to me that adding the check with `[No selection needed]` in the "selections" category 
would make sense.

**Comment by elsylambert** [comment]
Works in 1.2.0 (7caed9f)
needs regression.
