### ISSUE TITLE
Verbiage in Guest Terms & Conditions

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#2017]
By continuing, you affirm that you have read and understand the terms and conditions and agree to:

Only add content that does not infringe on someone else's copyright.

Only add content that does not conflict with the Statement of Faith.

Release your contributions to the content under a Creative Commons Attribution-ShareAlike 4.0 International License.

## Note: 
- This only applies to the Guest (Local User) T&C, not creating a Door43 account.

**Comment by RoyalSix** [comment]
## Tasks
- [ ] [1] Change Verbiage For Creating Local User
