### ISSUE TITLE
Refactor home Screen navigation buttons

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord/translationCore#2027]
The main navigation buttons on the bottom should say where the button will take the user. So in the screenshot above it should be "Go Home" and "Go to Projects" (when in Projects is should say "Go to User" and "Go to Tools"). The forward action should be disabled until all prerequisite actions have been completed (e.g. login complete).

- The Next button should be disabled until user logs in

**Comment by klappy** [comment]
@mannycolon: I'm assuming this is blocked until the tool management step is implemented. I added the dependency accordingly.

**Comment by RoyalSix** [comment]
# Tasks
- [ ] [2] Associate user cards with meaningful string names
- [ ] [2] Block actions to move on unless prerequisites have been completed

**Comment by cckozie** [comment]
I think the blank disabled buttons should be hidden. Since there is no reference to that situation in the instructions, I will write up a new issue for it. (#2253)
