### ISSUE TITLE
Can't Copy & Paste

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#203]
I cant right click to paste, I have to press ctrl+C. I know to us devs thats not an issue but a lot of people exclusivley copy and paste by right clicking on things still.

From #197

**Comment by mannycolon** [comment]
recovering the copy and paste messes up with translationNotes' targetversedisplay section and affects the drag and select, working on moving the css property internally to the component only.

**Comment by mannycolon** [comment]
#232
