### ISSUE TITLE
Fix missing verses bug

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2033]
beta.21
Same problem with both tN and tW.
[es-419_tit_text_ulb.zip](https://github.com/unfoldingWord-dev/translationCore/files/1116576/es-419_tit_text_ulb.zip)
![image](https://user-images.githubusercontent.com/8171759/27755830-ef1e8bea-5db7-11e7-8178-1b5b7109271c.png)

**Comment by mannycolon** [comment]
# Tasks

- [3] SPIKE: Debug Project loading bug.
- [2]  Fix project loading bug.

**Comment by cckozie** [comment]
This one is pretty old. I think the attached project is corrupt or it is in a form that we no longer support. I think the original problem has been fixed.
Closing in .beta63.
