### ISSUE TITLE
Problem loading projects

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#209]
As soon as I loaded my first project from this repo I got the following error C:\Users\Luke\AppData\Local\translation_core\app-0.1.2\resources\app.asar\src\js\components\core\On…:29 Uncaught TypeError: this.submitLink is not a functionReactErrorUtils.invokeGuardedCallback @ C:\Users\Luke\AppData\Local\translation_core\app-0.1.2\resources\app.asar\node_modules\react\lib\Re…:70 C:\Users\Luke\AppData\Local\translation_core\app-0.1.2\resources\app.asar\modules\translationWords_…:307 Uncaught TypeError: Cannot read property '5' of undefined So that is a very huge problem. From a quick spot check of the repo it looks like nothing is wrong so this is something we certainly want to investigate further into.

From #197

**Comment by RoyalSix** [comment]
Refactoring project loading because this error is too hard to pinpoint
