### ISSUE TITLE
Error Modals not working in builds

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#210]
The error modal didnt load so at this point I had no clue what to do as a new user so I close the app then open it back up. The app immedeatly starts to load that same project that caused an error so I have no way to escape. As a developer I know I can clear my local storage but the new user would just be up a creek without a paddle. We need a way for a user to force a hard reset if some big time error like this keeps happening. Even if they deleted all the apps files and redownloaded the app it would still get hung up on the same loading screen because the local storage was never cleared out.

From #197

**Comment by mannycolon** [comment]
@EllDoubleYew hey bro, was this address in your latest PR??

**Comment by RoyalSix** [comment]
I have an idea for this one, we could create a flag in localStorage that tracks if the user has had a fatal on "startup", last time
And if they did, do a clear storage
