### ISSUE TITLE
SPIKE: Break down how to Add support for the GL

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#2110]
List of resources that will need to exist for our "Gateway Language Resource Package".
What does it take to remove English from our app and add it back in as a GLRP?
What will it take to remove English and replace it with Hindi or another GL?
This should be repeatable for Hindi and other Gateway languages.
What are all the pieces that need to be translated?

How will the user/developer add new GLRP to the app?
How will the end user select the languages that are available?

In theory, this GLRP could be translated with Google Translate for visual testing.

**Comment by mannycolon** [comment]
## Tasks

- [10] Research how to Break down how to Add support for the GL.
- [11] Document findings on how to Break down how to Add support for the GL.

**Comment by RoyalSix** [comment]
## Required Language Specific(GL) Resources ##
- UI Strings
- Gateway Language Bible
- Lexicons
  - UGL 
  - UHL
- translationHelps
  - tA
  - tN
  - tW

## Removing English from our app and add it back in as a GLRP ##
 - Getting a list of all UI strings, Extracting, Replacing (Localization #2111)
 -  Resources have already been translated into English, but that would most likely be the longest step.
    - This includes the content, and the index's
    - Lexicons are not a requirement?
 - Allowing user to select language on startup and then select GLRP before checking may be a good idea as well.
 - The process should be pretty straight forward, do not foresee any leaping changes to data structure at all.

**Comment by RoyalSix** [comment]
## How will the user/developer add new GLRP to the app? ##
 - Once tC has successfully extracted all UI strings, that is the last step in order for us to separate the language specific content from the app.
 - The tC team will need to create an entry point for developers to import custom GLRP in to the app. This could live in the settings.
 - In order to make it easy to import such a resource package I suggest keeping things very similar to how we currently handle tC import.
 - Ideally we would keep the same format as we have in our static folder which makes it optimal for tC parsing.
 - The user could then select a folder to import
    - Folder structure as such: 
```
My Resource Package Name
│
└─── strings
│   │   strings.csv
└─── bibles
│   └─── udb-en
│   │   └─── v9
│   │       └─── groups
│   │               └─── 1ch
│   │                │   1.json
│   │                │   2.json
│   │                │   ...
│   │                └─── 1co
│   │                │   1.json
│   │                │   2.json
│   │                │   ...
│   │
│   └─── ugnt
│   │   └─── v0
│   │       └─── groups
│   │              └─── 1ch
│   │                │   1.json
│   │                │   2.json
│   │                │   ...
│   │                └─── 1co
│   │                │   1.json
│   │                │   2.json
│   │                │   ...
│   └─── uhb
│   │   └─── v9
│   │       └─── groups
│   │              └─── 1ch
│   │                │   1.json
│   │                │   2.json
│   │                │   ...
│   │                └─── 1co
│   │                │   1.json
│   │                │   2.json
│   │                │   ...
│   └─── ulb-en
│        └─── v6
│   │       └─── groups
│   │              └─── 1ch
│   │                │   1.json
│   │                │   2.json
│   │                │   ...
│   │                └─── 1co
│   │                │   1.json
│   │                │   2.json
│   │                │   ...
└─── lexicons
│   └─── en-UGL
│   │   └─── v0
│   │       └─── content
│   │               │   1.json
│   │               │   2.json
│   │               │   ...
│   └─── en-UHL
│         └─── v0
│              └─── content
│                      │   1.json
│                      │   2.json
│                      │   ...
└─── translationHelps
       └─── translationNotes
       │   └─── v0
       │         └─── groups
       │                └─── 1ch
       │                │   figs_123person.json
       │                │   figs_activepassive.json
       │                │   ...
       │                └─── 1co
       │                │   figs_123person.json
       │                │   figs_activepassive.json
       │                │   ...
       │                 ...
       └─── translationAcademy
       │   └─── v0
       │          └─── content
       │          │    │   figs_metaphors.md
       │          │    │   figs_123person.md
       │          │    │   ...
       │          └─── index.json
       └─── translationWords
             └─── v0
                    └─── groups
                    │   └─── 1ch
                    │   │   abiathar.md
                    │   │   ahaz.md
                    │   └─── 1co
                    │   │   adam.md
                    │   │   amen.md
                    │   │   ...
                    └─── content
                    │   │   abiathar.md
                    │   │   abomination.md
                    │   │   ...
                    └─── index.json
```
 - I would propose having the strings being in either a csv file or in a folder structure easily parsed. I think data wise tC should parse the csv into a folder structure format easily consumable in the app depending on the library used.

**Comment by RoyalSix** [comment]
## Testing Visually Through Google Translate ##
 - Google Translate is not free even for small projects
 - Translate [Yandex](https://translate.yandex.com/?lang=en-ru) is free
 - Contact ian about previously used Google translate API
