### ISSUE TITLE
SPIKE: Break down localization of the app

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#2111]
User Interface localization.

1. What libraries and services exist for our stack?
2. Define what data structure for UI strings. Bias is CSV.
3. How are we going to translate/extract/replace/etc... text strings.

**Comment by RoyalSix** [comment]
## Things To Consider ##
1. Detecting the users locality
    - OS location/language services
    - Manual input (persisted after input)
2. Translating UI elements
    - Use a library
3. Using local specific content such as dates/time/currency (Don't think we have to worry about that right now)

**Comment by RoyalSix** [comment]
## Libraries For Translation: ##
###  [React Intl](https://github.com/yahoo/react-intl) ###
  - Pros
    - Widely supported
    - Well documented
    - Most popular
  - Cons
    - Higher learning curve than others. Using react mixins
    - Maybe a bit much documentation, may take longer to get setup
###  [React Localization](https://github.com/stefalda/react-localization) (Decided)
  - Pros
    - Simple setup
    - Seems very react friendly
  - Cons
    - Less support
###  [React i18next](https://github.com/i18next/react-i18next) ### 
  - Pros
    - Website interface for translation management
    - Detects the user language
    - Moderate learning curve
    - Many features for performance/react-redux friendly
  - Cons 
    - Relatively new
  - Check out demo: https://www.youtube.com/watch?v=9NOzJhgmyQE

**Comment by RoyalSix** [comment]
## How To Translate/Extract/Replace Strings ##
### Extracting ###
 - Manually go through each component visually and find string in code and copy over to a master list
### Translating ###
 - Go through csv file and see context/description and translate.
 - Go through tC tool and enter in new translation with context easily visible on screen

**Comment by RoyalSix** [comment]
## Regroup Conclusions
- <s>Implement React Localization library</s> Doing own implementation
- Extract UI strings into JSON
- First parsing UI strings in JSON with `id`, `text`, and `description` then to CSV for user entry this makes the data easily parsable for tC into reducers
```
//homeScreen.json
"homeScreen":{
  "loginButton": {
    "text": "Login",
    "description": "Text to display on Login button"
    }
}
//Multiple nesting is also an option
```
- Move all the static content in a separate repo
- Then migrate UI strings to CSV
```
//strings.csv
"id", "text", "description"
"homeScreen-LoginButton", "Login", "Text to display on Login button"
```
- Eventually build a tool to guide translation (GLRP)
- Localization Reducer to handle all UI strings

**Comment by da1nerd** [comment]
I found this library that I think will do exactly what is suggested above. https://www.npmjs.com/package/react-localize-redux.

**Comment by RoyalSix** [comment]
@klappy @mannycolon Check it out ^^

**Comment by da1nerd** [comment]
I can configure the locale to automatically sync with crowdin when merges are made on Github. For now I'm only going to upload the latest english locale to Crowdin, but we could also download the latest localization from crowdin a well.

Any thoughts on that?
