### ISSUE TITLE
SPIKE: Define the desired data structure for Greek

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#2122]
UGNT will be coming from a CSV. tC will be using some internal proprietary json. What do we recommend that the uW website represents this data as.

@jag3773 has recommended OSIS format, confirm that this will work for us or make another recommendation.

**Comment by klappy** [comment]
See Wiki Page: https://github.com/unfoldingWord-dev/translationCore/wiki/Greek-Hebrew-Ideal-Format:-USFM-3
