### ISSUE TITLE
App is still looking for the uhb for NT projects

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2127]
Seeing in beta.54

**Comment by benjore** [comment]
- [ ] completely remove UHB for now

**Comment by klappy** [comment]
Use the bibleHelper.isOldTestament to detect if it is Old Testament. If it is, use for UHB, if it isn't, use UGNT.

**Comment by mannycolon** [comment]
# Tasks
- [2] Use the bibleHelper.isOldTestament to detect if it is Old Testament. If it is, use for UHB, if it isn't, use UGNT.
