### ISSUE TITLE
Overlapping of reason codes on verse edit

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2128]
beta.54
Width shrunk as far a possible
![image](https://user-images.githubusercontent.com/8171759/28034548-1f1c8ca4-6577-11e7-843a-6f71cf1a3bad.png)

**Comment by benjore** [comment]
Make 3 rows of check boxes, 2 columns

**Comment by mannycolon** [comment]
# Tasks

-[3] Fix layout the overlapping of reason codes on verse edit by using rows and cols.

**Comment by cckozie** [comment]
It looks a little weird with "Other" not aligned vertically. If it's not a big deal (2 hours or less), please align it vertically with "Word".
![checkbox](https://user-images.githubusercontent.com/8171759/29588490-5e1b7e40-8757-11e7-8e2b-b355db1a7a61.png)

**Comment by mannycolon** [comment]
- [2] Fix unaligned checkbox with the label of "other" in verse check
