### ISSUE TITLE
Automatically set focus to username field on login dialogs

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2130]
Focus should automatically be set to the username field on both the log in with Door43 and continue as guest dialogs.

**Comment by richmahn** [comment]
- [ ] [2] Automatically set focus to username field on login and signup forms
- [ ] [2] Write unit tests to test focus goes to username on login and signup forms

**Comment by cckozie** [comment]
When logging in to Door43, the cursor is repositioned to the username field after the first character of the password is entered. Users now have to manually reposition the cursor to the password field every time a new character is entered there.
