### ISSUE TITLE
Change the text wrapping format on the project card details line

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2132]
Currently the wrapped text left margin aligns with the icon rather than the top line of text. This makes it look somewhat confusing to the normal user, it looks like a second row of text rather than wrapped text.
![image](https://user-images.githubusercontent.com/8171759/28072968-09918c24-661a-11e7-9cc1-f272b37276b0.png)

**Comment by benjore** [comment]
- [ ] Make the second line of text align under the text, not under the icon.

**Comment by cckozie** [comment]
I think this will be superseded by #2297

**Comment by richmahn** [comment]
- [3] Change Project cards to use tables with set widths
- [2] Unit test for project cards to verify HTML

**Comment by richmahn** [comment]
Note that this issue's fix is also in PR #3060

**Comment by cckozie** [comment]
Held pending response to questions in #2297

**Comment by cckozie** [comment]
Passing as the issues related to the hold will be addressed in #2297
