### ISSUE TITLE
[0] Bug: Quote not found prevents check from loading

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#2136]
## Steps to recreate:
- Open any language project of Ephesians.
- Open translationWords tool.
- Click "suffer, suffering" heading in the menu.
- Look at logs, `Uncaught TypeError: Cannot read property '0' of undefined
    at Verse.highlightQuoteInVerse (/Users/klappy/GitHub/translationCore/tC_apps/ScripturePane/components/Verse.js:43:31)`

**Comment by cckozie** [comment]
The check now opens, but after completing the check and saving it, the app does not move to the next check. If I click on another check and then come back to "suffer", the verse displayed is incorrect.
