### ISSUE TITLE
Get tW Part I working in Hindi

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#2150]
## Prereqs
- [ ] tW Part I (Titus) is working for English
- [ ] Hindi content is complete, in the correct form, and in the API

## To Do 
- [ ] Import aligned Hindi ULB
- [ ] Import Hindi tW content
- [ ] UI/UX to choose the source language
- [ ] Show all available GL resources in the Scripture Pane 
- [ ] Update tW & Helps to accommodate the source language that has been chosen

**Comment by jag3773** [comment]
Duplicate of #2529 .
