### ISSUE TITLE
Determine/implement best way to avoid special characters appearing in exported csv files

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2152]
The text is correct in tC, but not in the exported csv.
![export characters](https://user-images.githubusercontent.com/8171759/28214241-163ce9d0-686f-11e7-8b67-0519987011aa.png)

**Comment by benjore** [comment]
Klappy - Use a CSV library

**Comment by klappy** [comment]
@cckozie What language/project did you use to create those issues so that I can work with the same one?

**Comment by cckozie** [comment]
@klappy 
I think it was the project that's attached to #1637. I know it was French and Ephesians. I can't currently get any Eph projects to work in the current build, so I can't test it there.

**Comment by cckozie** [comment]
I'm going to pass this issue since it was an "investigate" one. The original bug is in issue #1637.
