### ISSUE TITLE
Discrepancies between what is on instruction card and action card on the "you are logged in as" screen

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2173]
Seems that it should be two words on the button. To be consistent with "Continue to Project", the "o" in "out" should be capitalized.
![image](https://user-images.githubusercontent.com/8171759/28217957-aa510d74-687c-11e7-9e8c-736295e4f54e.png)

**Comment by benjore** [comment]
- [ ] The button should be "Log out" (For reference, a person can "Log out" or "Log in" - both verbs - but in order to do that, there might be a "Login" screen or a "Logout" screen - both nouns/adjectives.)
