### ISSUE TITLE
Typo on Internet use warning dialog

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2179]
There is a typo on the Internet warning card. Unfortunately it was specified incorrectly on the instructions for this issue. 
The specified (and implemented) text was: "You are about to transmit data over the internet, you sure you want to do that?"
It should be: 

You are about to transmit data over the Internet. 
Are you sure you want to do that?

(insert the word "are" between "internet," and "you")
Also, the first letter of "internet" should be capitalized.
![image](https://user-images.githubusercontent.com/8171759/28242067-3f69dc2a-6967-11e7-954c-1a2f99630fdd.png)

**Comment by klappy** [comment]
# Task
[1] Update text on Internet use warning dialog
