### ISSUE TITLE
Wrong error message displayed when logged in as a local user and attempting to upload a project

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2180]
beta.42
1. Since we don't allow uploading when logged in as a local user, the "You are about to use the Internet" message should not be displayed.
2. Below is the message that is displayed. It should be the one the specifies that you need to be logged in with a Door43 account.
![image](https://user-images.githubusercontent.com/8171759/28242083-1e096496-6968-11e7-9cd8-3cf2ffa8e8e1.png)

**Comment by cckozie** [comment]
As of beta.41, no message is displayed. Nothing happens other than a console error.
![image](https://user-images.githubusercontent.com/8171759/28695492-0b470cfa-72f5-11e7-926b-a59a602be89d.png)

**Comment by RoyalSix** [comment]
@cckozie I'm getting the wrong error message dialog but not the console error. I can fix the dialog for now and let me know if you are still getting a console error. If so what steps are you taking?

**Comment by cckozie** [comment]
@RoyalSix I am not seeing the console error in beta.47
