### ISSUE TITLE
Polish off Home Screen

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#2187]
We created pieces of Home Screen but the whole thing appears to have holes in the implementation. There are also a few different styles and approaches to the screens that could be evaluated and made consistent.

- Inconsistencies in containers.
- Overview page missing project card menu functions.
- Overview page Heading Links need to go to correct step, they all take you to the login step.
- Remove Next button since the Steps walk you through the stepper.
- Select a project takes you to the wrong step.
- Tools don't have instructions.

**Comment by mannycolon** [comment]
## Tasks

- [3] Spike: research what needs to be done/changed.
- [6] Fix Inconsistencies in containers.
- [3] Update Overview page Heading Links to go to the correct step.
- [6] Fix instructions implementation.
- [3] Clean the props being sent down through containers in the home screen implementation.
