### ISSUE TITLE
Project opens to blank checking screen

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2188]
[fr_eph_text_reg.zip](https://github.com/unfoldingWord-dev/translationCore/files/1153543/fr_eph_text_reg.zip)

![image](https://user-images.githubusercontent.com/8171759/28282512-452ca450-6af0-11e7-8479-cb5e1fae87a6.png)

**Comment by RoyalSix** [comment]
I believe this is related to the react lifecycle or dispatch order of actions
## Tasks:
- [ ] [2] Find issue of menu not rendering on first load
- [ ] [2] Fix issue of menu not rendering on first load
