### ISSUE TITLE
Text overwrite in scripture pane

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2189]
tC window at minimum width
![image](https://user-images.githubusercontent.com/8171759/28282618-aca2ed2e-6af0-11e7-89e0-d80d4a640e6b.png)

**Comment by benjore** [comment]
- [ ] Truncate the language name so that it all stays on one line in the scripture pane
- [ ] Add  a hover-over for complete name

**Comment by mannycolon** [comment]
# Tasks
- [1 ] Truncate the language name so that it all stays on one line in the scripture pane.
- [2] Add a hover-over for complete language name in the scripture pane.
