### ISSUE TITLE
Handling projects with missing chapter numbers (projects that use chunks)

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord/translationCore#22]

**Comment by klappy** [comment]
Does this mean using projects that haven't completed all chunks in a tS project?
That is very common for us to find these when testing, the happy path or intended workflow is for them to use tC after they merge projects into a single project of a completed book. However, there is discussion of a new module/app to be created to facilitate merging unfinished projects into a single project.

**Comment by mannycolon** [comment]
yes, i meant unfinished projects. so i guess we could close this issue?

**Comment by klappy** [comment]
Should we parse path/files for chapter/chunks without referencing manifest? And use the manifest just to know the status if a chunk is finished?

**Comment by ihoegen** [comment]
The problem with that is sometimes a chunk exists, but it won't be in USFM format. finished_chunks consists of chunks that are finished and in USFM.

**Comment by ihoegen** [comment]
I think for now I can just at the very least make it so the app doesn't crash on us when they are missing a chunk. Everything else should be up to further discussion.
