### ISSUE TITLE
Make FAB words clickable

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2216]
I find myself frequently trying to click on the description of the FAB option instead of the image. I suggest that we either change the background for the text so that it doesn't look like a button, or else allow the text "button" to also be clickable.

Also, I'm not sure if there are actually any standards for this, but I was not able to find any examples where there was descriptive text for the close "button". Most of the examples I was able to find had the close "button" a different color, and some of them had it as a larger circle.

**Comment by RoyalSix** [comment]
- text clickable, ask about text verbiage updates

**Comment by mannycolon** [comment]
@richmahn this is a story you cant add hours estimates to stories only to tasks

**Comment by richmahn** [comment]
- [x] [4] Make the FAB labels have an onClick action
- [x] [4] Write a test for ProjectFAB to verify labels are clickable and have a pointer cursor
