### ISSUE TITLE
Menu option to close the program

### ISSUE THREAD

**Issue by ChrisJarka** [unfoldingWord/translationCore#222]
I did not expect to find the 'close' or a way to exit the program as a choice in the main 'window' menu. Is that the new trend to put the exit/close on that menu rather than the file menu?

**Comment by ChrisJarka** [comment]
![close app not where expected](https://cloud.githubusercontent.com/assets/9850185/19401410/3c876092-9229-11e6-8dd2-f1cd911d493e.jpg)

**Comment by klappy** [comment]
This goes in "File" for web browsers, we should move it there.
