### ISSUE TITLE
Hide Developer Tools Menu item?

### ISSUE THREAD

**Issue by ChrisJarka** [unfoldingWord/translationCore#223]
I wonder if you might want to have a toggle in settings that will allow an end-user to choose to see the developer tools.  But, until then, for the program to default to not showing the developers tools.
![might want to remove this from the main menu](https://cloud.githubusercontent.com/assets/9850185/19401456/7a0c201a-9229-11e6-9cd9-a1f41e8f9b15.jpg)

**Comment by klappy** [comment]
We want to leave this in throughout all Alpha and Beta releases, and make that option hidden after that.
