### ISSUE TITLE
Update the text on the import from Door43 modal

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2248]
1. Do we want the verbiage to specify that only Titus projects can be opened?
2. "From" in the window title bar should not be capitalized
3. Do we want all/just the NT books to show in the book dropdown?

![image](https://user-images.githubusercontent.com/8171759/28536058-1df2ac46-706c-11e7-9469-84d94b4ebdd2.png)
![image](https://user-images.githubusercontent.com/8171759/28536630-d96f20f2-706d-11e7-87b0-8254307a3d39.png)

**Comment by benjore** [comment]
1. ..."only Titus projects can be loaded"
2. correct
3. only NT in dropdown

**Comment by mannycolon** [comment]
# Tasks
- [1] Update the verbiage in the import from Door43 modal.

**Comment by cckozie** [comment]
1. OK - Verbiage has been changed.
2. Fail - "From" is still capitalized
3. OK - Only NT books appear in the dropdown.
We may want to filter the results so that only NT books are displayed too. Since that wasn't part of this issue, I'll create a new one for it.

**Comment by mannycolon** [comment]
- [0:30] Update "From" to "from" in the door43 import modal
