### ISSUE TITLE
Change the text on the Titus only alert dialog

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2252]
I think something along the lines of "This version of translationCord only supports Titus projects." is better than a "you can't do that for now" kind of message. I don't like the "You", and the "for now" has no context. Can I do it after lunch, after rebooting, after performing some other function in tC?

**Comment by cckozie** [comment]
Looks like this one didn't make it into build beta.52
![image](https://user-images.githubusercontent.com/8171759/29586541-9cd88efe-8750-11e7-9562-04c24b6aeaeb.png)

**Comment by mannycolon** [comment]
- [1] update Titus only projects alert
