### ISSUE TITLE
UGNT: Import proposed Greek in USFM 3

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#2259]
Via Wiki: https://github.com/unfoldingWord-dev/translationCore/wiki/Greek-Hebrew-Ideal-Format:-USFM-3

## Tasks
- [Blocking] UGNT USFM 3 exposed via DCS v3 API.
- [13] Write download/import script for Greek USFM 3 in DCS v3 API.
- [8] Package download/import script to be run as an NPM script.

**Comment by benjore** [comment]
Initial SPIKE for the data structure #2122

**Comment by benjore** [comment]
Here is the file to be used for Titus:

https://team43.slack.com/files/jag3773/F6P9SC58A/57-tit.usfm

**Comment by klappy** [comment]
From this point on, the Greek will only include Titus. (Until we have more data)

**Comment by jag3773** [comment]
duplicate of #3104 and #2143 .
