### ISSUE TITLE
Extract UI Strings

### ISSUE THREAD

**Issue by RoyalSix** [unfoldingWord/translationCore#2265]
- Manually going through and finding all content from visual inspection of the app.
 - Create json files to represent UI elements in a data structure as such:
```
//homeScreen.json
"homeScreen":{
  "loginButton": {
    "text": "Login",
    "description": "Text to display on Login button"
    }
}
//Multiple nesting is also an option
//Container/Component/String key
```

**Comment by da1nerd** [comment]
Started working on this. The library we're using supports this nested syntax which will be very hand for organization.
