### ISSUE TITLE
Translate UI Strings (For Testing)

### ISSUE THREAD

**Issue by RoyalSix** [unfoldingWord/translationCore#2266]
- Translate API [Yandex](https://translate.yandex.com/?lang=en-ru) is free
- Once changes have been made on a version basis they are ready to be imported into tC
- All strings need to be translated in two languages that reach edge cases for length

**Comment by da1nerd** [comment]
We are using crowdin to perform the translation. https://crowdin.com/project/translationcore. I'm not sure if we need this issue anymore.

**Comment by da1nerd** [comment]
see https://github.com/unfoldingWord-dev/translationCore/issues/2003 for further discussion.
