### ISSUE TITLE
Redux Implementation of UI Strings From CSV

### ISSUE THREAD

**Issue by RoyalSix** [unfoldingWord/translationCore#2267]
- We will have to write an import script to receive the translation from the repo and inject them into the app.
 - Redux implementation of handling getting the UI Strings into the app from the repo

**Comment by da1nerd** [comment]
This is done. However, we're not using csv since crowdin accepts json input.

**Comment by da1nerd** [comment]
See https://github.com/unfoldingWord-dev/translationCore/issues/2003 for further discussion.
