### ISSUE TITLE
JSON To CSV Conversion For UI Strings

### ISSUE THREAD

**Issue by RoyalSix** [unfoldingWord/translationCore#2270]
- Run script on json files and export csv in a format as such:
```
//strings.csv
"id", "text", "description"
"homeScreen-LoginButton", "Login", "Text to display on Login button"
```
 - Create git repository for managing changes to UI strings(also GLRP)

**Comment by da1nerd** [comment]
I believe this is no longer applicable. Since we will use crowdin for translation and it accepts json input.

**Comment by da1nerd** [comment]
see https://github.com/unfoldingWord-dev/translationCore/issues/2003 for further discussion
