### ISSUE TITLE
Alignment Tool: Create D&D Interface for aligning words/phrases between source/target.

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#2277]

**Comment by mannycolon** [comment]
# Tasks
- [6] Create drag and drop source word box component
- [6] Create drag and drop target word box component
- [2] Refine D&D components behavior

**Comment by cckozie** [comment]
If there are duplicates of a word in the GL word list, when I drag the first one of them to a box in the alignment area, the second one disappears from the GL word list. The screenshots are from Titus 1:1. The same thing happens with the word "le" in Titus 1:3.
[fr_tit_text_ulb.tstudio.zip](https://github.com/unfoldingWord-dev/translationCore/files/1360077/fr_tit_text_ulb.tstudio.zip)

At beginning:
![image](https://user-images.githubusercontent.com/8171759/31235743-de6e5e1e-a9b7-11e7-88c1-618456af3f37.png)
After aligning first Dieu:
![image](https://user-images.githubusercontent.com/8171759/31235796-058754c4-a9b8-11e7-91a5-c7b22456d8c4.png)

**Comment by cckozie** [comment]
I'm still seeing the same bad behavior in beta.91
