### ISSUE TITLE
Alignment Tool: Style UI components

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#2279]

**Comment by mannycolon** [comment]
# Tasks
- [6] Style source words box
- [6] Style target box component
- [3] Make desired changes to scripture pane
- [6] Refine styling for alignment tool components

**Comment by mannycolon** [comment]
# Tasks
- [5] style target Boxes to include a checkbox to allow Greek words to switch places with other Greek words

**Comment by cckozie** [comment]
The scripture panel should be tweaked to more closely match the UI design, but we'll pass this for now and change it later.
