### ISSUE TITLE
Write download/import script for Greek USFM 3 in DCS v3 API

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#2280]
Package download/import script to be run as an NPM script.

**Comment by benjore** [comment]
include tests

**Comment by jag3773** [comment]
Is this still relevant @mannycolon or @PhotoNomad0 ?  If not, please close it.

**Comment by PhotoNomad0** [comment]
@jag3773 @mannycolon - I vote no.  Manny If you feel differently you can reopen.
