### ISSUE TITLE
Rethink what to show on the select screen when the verse is blank

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2289]
I think it will be confusing to the user about what they should do in the case of a blank verse. There is an instruction that doesn't really make any sense and a bunch of buttons leaving the user to wonder what he should do. I'd suggest replacing the "Please select..." instruction with a message indicating that the verse is blank and instructions to edit, leave a comment, or bookmark it, or click the Next button (assuming that we are changing to Next and Previous). Also, I think we should not automatically go into Select mode if the verse is blank.
![image](https://user-images.githubusercontent.com/8171759/28624988-848eb114-71e0-11e7-8cbc-2a881e55ccd9.png)

**Comment by benjore** [comment]
Covered by #2290
