### ISSUE TITLE
Text overflows left panel of select area

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2291]
![image](https://user-images.githubusercontent.com/8171759/28626396-7c7e1614-71e4-11e7-8146-f1f54d046f3a.png)

**Comment by benjore** [comment]
- [ ] Add scroll bar

**Comment by mannycolon** [comment]
# Tasks
- [1] Debug the left panel of select area.
- [2] Add scroll overflow to the left panel of select area.
