### ISSUE TITLE
Unrealistically long selections caused part of "... has been translated.." message to be hidden

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2292]
Even though the scroll bar is all the way to the top, the beginning of the message cannot be seen.
![image](https://user-images.githubusercontent.com/8171759/28626602-17dd9378-71e5-11e7-9712-29949b909378.png)

**Comment by benjore** [comment]
- [ ] On the left side
  - [ ] Add a scroll bar
  - [ ] Prevent the text from scrolling out of the designated area
- [ ] On the right side
  - [ ] fix the scrolling so that when scrolled all the way to the top, the top of the text is visible

**Comment by elsylambert** [comment]
Retested in 2.0.0 (4b3ebee). Not seeing this issue. Scroll bars appears when there are long texts.
