### ISSUE TITLE
Refactor text on project cards

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2297]
Make individual fields (or cells) for last updated, book, and language. Make them all fixed widths (like columns) so that they line up in the same place on each of the project cards. Wrap the text when necessary to fit in the column, but if the text overflows two lines, then truncate it so that it fits in the two lines.

**Comment by cckozie** [comment]
This will probably supersede #2132

**Comment by cckozie** [comment]
I reopened this issue since it is not really the same or expressly included in #2132.

**Comment by cckozie** [comment]
@benjore There are a couple things here I was not envisioning when submitting this issue. My initial reaction was to fail it, but would like your opinion.
1. No padding between the "columns". (First project card)
2. What appears to be vertical centering alignment when the text gets wrapped. It seems like the icon and first line of text should always be aligned. (2nd and 5th card)
![image](https://user-images.githubusercontent.com/8171759/32460216-afa1720c-c2f7-11e7-99bf-3dc76b9d13b7.png)

**Comment by benjore** [comment]
Yes to both.

**Comment by cckozie** [comment]
1. Please add some reasonable padding between the columns. Something in the neighborhood of twice the distance between the icon and its following text should be good.
2. When the text is wrapped, the top line should still align horizontally with the icon.

**Comment by richmahn** [comment]
- [x] [1] Fix issues that failed in QA for Project Card refactoring
