### ISSUE TITLE
Selection Refinement

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#2300]

**Comment by klappy** [comment]
## Tasks
- [4] Selection: Move all selection code to `selectionHelpers`
- [4] Selection: Write unit tests to validate the behavior of all `selectionHelpers`
- [8] Selection: Make all tests pass
- [8] Selection: Refactor `selectionHelpers`
- [4] Selection: Move browser text selection code to `selectionsActions`
- [4] Selection: Write unit tests for `selectionActions`
- [8] Selection: Make all `selectionActions` tests pass
- [4] Selection: Refactor VerseCheck with core `selectionActions` and `selectionHelpers`
- [8] Selection: Attempt separate layers, highlighting and selecting
- [8] Selection: Debug remaining issues

**Comment by cckozie** [comment]
All work is being performed on other stories.
