### ISSUE TITLE
Show the full file path and name on the "There is something wrong with the project..." alert

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2305]
This alert is displayed when attempting to import a local project. It would be helpful to the user to display the full file path and name, or at least the full name including the extension.
There may be multiple alerts that this applies to.

**Comment by RoyalSix** [comment]
This alert message verbiage (For this specific error) has changed since the original issue was created....
Going to add the fullpath to all similar instances of the issue @cckozie

**Comment by cckozie** [comment]
.beta96
I'm not sure what project was causing the original problem. It looks like it has been fixed, although as mentioned above, the original wording has also been changed.
