### ISSUE TITLE
Update Project Details Reducer (manifest)

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#2349]
Project Details Reducer needs to maintain some information.
- Project Save Location
- Progress of tools
- Manifest

**Comment by mannycolon** [comment]
## Tasks
- [4] Persist Manifest as the manifest.json in the project folder for fs load/save.
- [4] Update prop references from Project Details Reducer to Project Manifest Reducer.
    - Remove params and replace with data in the manifest.
