### ISSUE TITLE
Git Errors

### ISSUE THREAD

**Issue by RoyalSix** [unfoldingWord/translationCore#235]
We still have git errors that prevents users from being able to switch checks. This will come up if you switch checks before the git processes are complete

**Comment by RoyalSix** [comment]
<img width="1278" alt="screen shot 2016-10-18 at 4 51 33 pm" src="https://cloud.githubusercontent.com/assets/16184018/19500605/a3e15144-9553-11e6-8da8-9e98763b5593.png">
<img width="1267" alt="screen shot 2016-10-18 at 4 53 16 pm" src="https://cloud.githubusercontent.com/assets/16184018/19500609/a94529e4-9553-11e6-8026-d9ef640c8a55.png">

**Comment by RoyalSix** [comment]
before I dive into this one, @ihoegen would you know why this is happening?

**Comment by ihoegen** [comment]
@royalsix That one is one I've never seen before
