### ISSUE TITLE
ProjectValidation Stepper UI

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#2352]
Having two steppers seems confusing, seems like it should be a modal.

## Front End
- Create ProjectValidationStepper container and components
- Implement ProjectValidationStepper Styling
- Implement ProjectValidationStepper Reducer and Actions

## Back End
- Create ProjectValidationStepper Reducer and Actions
- Integrate ProjectValidation Stepper in Project Open
  - ProjectValidation Stepper Determine which checks to prompt
  - ProjectValidation Stepper Opens when project is selected

**Comment by cckozie** [comment]
Placing on hold until the check functionality is available.
Is "Previous" the correct verbiage on the back button on the Copyright check screen?
Is the verbiage above the check card correct (it is now one long "word")

**Comment by cckozie** [comment]
Remove the back arrow from the Cancel button (since it doesn't really go back)
Change the verbiage on the other button to "Continue" at all steps

**Comment by mannycolon** [comment]
# Tasks
- [2] Remove the back arrow from the Cancel button and Change the verbiage on the other button to "Continue" at all steps
