### ISSUE TITLE
ProjectValidation: Merge Conflicts

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#2355]
## Front End
- ProjectValidation MergeConflict Instructions
- Create ProjectValidation MergeConflicts component
  - ProjectValidation/MergeConflicts Folder with index.js for the main component
- Create ProjectValidation MergeConflictCard component
  - Create ProjectValidation MergeConflictOption component

## Back End
- MergeConflictsReducer 
  - Array of all merge conflicts
- MergeConflictsActions
  - Find merge conflicts
    - Look for node library for merge conflict parsing
  - Populate reducer with merge conflicts
- MergeConflicts Tests

**Comment by cckozie** [comment]
[en-x-demo1_php_text_reg_old.zip](https://github.com/unfoldingWord-dev/translationCore/files/1225457/en-x-demo1_php_text_reg_old.zip)
I did not get any indication of merge conflicts when opening this project, but it does appear to have some.
![image](https://user-images.githubusercontent.com/8171759/29321866-661468c0-81a1-11e7-921b-a26e1f7785a1.png)

Cannot test other projects because the import fails for my other projects that have merge conflicts.

**Comment by RoyalSix** [comment]
- [ ] [3] Determine best method for detecting merge conflict in projects already imported
  - Maybe checking git history
- [ ] [4] Implement additional use case for detecting already imported projects with merge conflicts

**Comment by RoyalSix** [comment]
@cckozie This merge conflict is not actually resolvable. Theres not enough data to know where the conflicts separate. In this case should we present the user with a alert stating so, and not load the project?

**Comment by cckozie** [comment]
@benjore How do we to handle situations where the merge conflicts are so bad that we can't resolve them? (We don't deal with this very well in tS either)

**Comment by benjore** [comment]
@RoyalSix @cckozie We're gonna have to deal with this problem. So I think what we need to do is 
A. Display a warning telling the user what went wrong and what the consequences are
B. Abort the import process

Now for a message... "Warning! This project has fatal errors and cannot be loaded." Only one button available, "Cancel Import"

**Comment by RoyalSix** [comment]
Should we mention something specific to merge conflicts in the error dialog? @benjore

**Comment by klappy** [comment]
@RoyalSix I see this story sitting in the review column but all tasks appear to be in the completed column but don't see a PR for any of them. What should we do with this Story? Make new tasks? Attach a PR or move it to In QA?

**Comment by RoyalSix** [comment]
Forgot to make new tasks for QA fails, updated.

**Comment by cckozie** [comment]
https://git.door43.org/tc02/es-419_tit_text_ulb
This project those a console error and keeps me on the Project Info page
![image](https://user-images.githubusercontent.com/8171759/29832102-b3c08232-8cac-11e7-897f-2fda083a068b.png)

**Comment by RoyalSix** [comment]
This seems to be working in traslationCore 0.7.1-beta.59 @cckozie

**Comment by cckozie** [comment]
Referenced projext en-x-demo1_php_text_reg_old.zip now indicates fatal errors.
Referenced project https://git.door43.org/tc02/es-419_tit_text_ulb now imports and opens w/o a console error.
