### ISSUE TITLE
ProjectValidation: Missing Verses

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#2356]
## Front End
- ProjectValidation MissingVerses Instructions (no report)
- Create ProjectValidation MissingVerses component
  - ProjectValidation/MissingVerses Folder with index.js for the  main component
- Create ProjectValidation MissingVerseCard component
  - Create ProjectValidation MergeConflictOption component

## Back End
- MissingVersesReducer 
  - Array of all missing verses
- MissingVersesActions
  - Find missing verses
  - Populate reducer with missing verses
- MissingVerses Tests

**Comment by cckozie** [comment]
This is now really broken! 
1. The imported file has multiple missing verses, but the missing verse panel was not displayed as part of the project validation. 
2. Verses that are in the USFM file sometimes show up as a different verse in the project. (e.g. Verse 2 is missing in the USFM file, but verse 3 shows up as verse 2 in the project.) Verses that are in the USFM file sometimes show as missing in the project. (e.g. Verse 5 is missing in the USFM but it has text in the project)
[es-419_tit_text_ulb_missing.txt.zip](https://github.com/unfoldingWord-dev/translationCore/files/1260948/es-419_tit_text_ulb_missing.txt.zip)

[es-419_tit_text_ulb_missing__usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/1260947/es-419_tit_text_ulb_missing__usfm.zip)

**Comment by RoyalSix** [comment]
@cckozie I think these issues were fixed in #2190

**Comment by cckozie** [comment]
All of the info in my last comment is still true in beta.57.

**Comment by RoyalSix** [comment]
@cckozie I found the issue with this project. 
The issue was with the parser...after the projects are parsed they are formatted for tC.
Which makes future loads faster, so it does not go through and re-evaluate the old imported usfm file.
The usfm file with the correct content is still stored in the project, so it could be fixed.
So my question is:
Should I write off this project because technically it has 'bad' data.
Or make a migration that will have to check each project for validity according to the imported source (Note: the imported source project is not necessarily a correct format to check by because the user could have removed / added verses in their project while checking that were not there to begin with)

**Comment by RoyalSix** [comment]
@benjore @klappy @mannycolon

**Comment by RoyalSix** [comment]
<img width="1279" alt="screen shot 2017-08-31 at 2 19 10 pm" src="https://user-images.githubusercontent.com/16184018/29945830-ab566358-8e57-11e7-80be-0aaabde9eeb4.png">
Was being parsed as follows
<img width="1241" alt="screen shot 2017-08-31 at 2 19 17 pm" src="https://user-images.githubusercontent.com/16184018/29945828-ab46bb1a-8e57-11e7-9269-9979da39288d.png">

**Comment by klappy** [comment]
@benjore @cckozie: This feature and bug was introduced after Private Beta 0.7.0, and I am unaware of any users testing 0.7.1-beta.x because it hasn't been stable enough to do so.

As far as fixing old projects, I'm not sure the juice is worth the squeeze, to steal @cckozie saying.

If this feature had made it to the users, I would encourage a migration, although I do not know how we would recover them automatically without reseting the project to overwriting the original usfm file, then "replaying" the verseEdits to attempt to bring back their changes, which may be mis-aligned since they may be editing the wrong verses.

**Comment by cckozie** [comment]
@klappy @RoyalSix : I'm not sure what you mean by your comments about this being an old project and having to do a migration. The USFM file is a valid file, but it is missing verses. Our import and validation process needs to be able to import it, list the missing verses, and display the valid data for using in checking.

**Comment by RoyalSix** [comment]
@cckozie The zip named ```es-419_tit_text_ulb_missing__usfm.zip``` has bad data.
the zip named ```es-419_tit_text_ulb_missing.txt.zip``` (The usfm) has been fixed in #2586 and will work as expected.

**Comment by RoyalSix** [comment]
<img width="643" alt="screen shot 2017-08-31 at 7 14 24 pm" src="https://user-images.githubusercontent.com/16184018/29952812-a3b98e4e-8e80-11e7-8696-f4014af8aaef.png">
<img width="1185" alt="screen shot 2017-08-31 at 7 14 15 pm" src="https://user-images.githubusercontent.com/16184018/29952811-a3b516a2-8e80-11e7-8921-4dbe642dc282.png">
