### ISSUE TITLE
Wrong check being displayed from menu

### ISSUE THREAD

**Issue by RoyalSix** [unfoldingWord/translationCore#2394]

**Comment by cckozie** [comment]
@RoyalSix How do I test this?

**Comment by RoyalSix** [comment]
@cckozie Try selecting checks on the menu and seeing if they actually go to the one selected. This was a bug introduced where the correct check wasn't being displayed

**Comment by cckozie** [comment]
I was not able to find any problems in beta.44

**Comment by RoyalSix** [comment]
Ok @cckozie it was specifically for tW
