### ISSUE TITLE
I am able to load non-Titus projects when not in developer mode

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2399]
beta.42
Import a non-Titus USFM file, click Next on each of the project checks, choose the tW tool, the project opens.

**Comment by klappy** [comment]
## Task
[2] Explore where the best place to prevent non-Titus projects from importing in non-dev mode
[3] Implement logic to block non-Titus projects from importing in non-dev mode

**Comment by cckozie** [comment]
.beta55
There is still a bug here, but since it is probably somewhat of an edge case, I'm going to leave this as a pass and create a new issue for it.(#2555)

If I import a project in developer mode, then switch out of developer mode, I am able to load the project.
