### ISSUE TITLE
Inconsistencies in displaying selections

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2406]
Open a project in tW and make a selection.
Click Save Changes
Click Edit, copy all of the text to the clipboard, delete all of the verse text, and then check the Other box
Click Save Changes, then Save Blank Verse, and then OK.
Click Edit, paste the text back in, then click the Other box
Click Save Changes
Notice that the previously selected text no longer shows as being selected.
Click Select
Notice that the previously selected text again shows as being selected in the Edit box
Click Cancel
Notice that the previously selected text no longer shows as being selected.

**Comment by klappy** [comment]
After rereading and recreating this issue, while related to the other selection issues, it isn't resolved yet. I'd like to explore the intended behavior a bit more before we fix it.

There is a state mismatch that we should be able to resolve with relatively moderate complexity.

Notes for resolution:
While we remove the selections, the component state doesn't get updated and persisted from the previous editing of selection. Should be able to address with resetting state to default when mode changes.

**Comment by klappy** [comment]
Tasks:
[2] Select Mode: Determine the best way to manage state in component lifecycle
[2] Select Mode: Update component lifecycle to use defaults on mode change
[2] Select Mode: Light Refactor as needed
