### ISSUE TITLE
SPIKE: Find the best way to store check resources locally

### ISSUE THREAD

**Issue by EllDoubleYew** [unfoldingWord/translationCore#241]
> As a checker I want all of my resources that I need for my check to be downloaded optimally with my check so that I dont need to fetch them dynamically

We need to find the best way to download and store this information so that is per parsed. This is research for 2 people and they should find tasks for the rest of the epic from this spike

**Comment by RoyalSix** [comment]
First let’s look at what we already have that is static that could be distributed with each tool to make tC smaller, but the tool larger. 
- Gateway Bible 1.7 Mb
- Hebrew Bible 10.9 Mb
- Greek Bible 1.7 Mb

Now let’s see what exactly is being processed on a load
- Common 800Kb
  - Target Language 
  - Gateway Language 
  - tC manifest 
- Each check data generated JSON obj of groups and check (Varies in size)
  - I.e. tNotes Check 2.7Mb
    - Groups and checks pertaining to a specific book
- This data has user specific information and timestamps 
- Translation Academy Section List 700 Kb
  - Figures of speech information (not book specific ?)

**Comment by ihoegen** [comment]
Looking at @RoyalSix 's list, this is what I think we can do with the following.
- Hebrew Bible - Keep with TC
- Greek Bible - Keep with TC
- Gateway Bible - Keep with TC
- Check data folder 
  - Each check data generated JSON obj of groups and check - Send these to their respective tools
    - I.e. tWords Check 
      - Groups and checks pertaining to a specific book
    - This data has user specific information and timestamps 
  - Translation Academy Section List - Keep with TA tools
    - Figures of speech information (not book specific ?)

**Comment by RoyalSix** [comment]
Updated the list, those top ones are already extracted in the TPane right now

**Comment by ihoegen** [comment]
Okay so the tA stuff, I think we should package it with tA, since that's for sure not book specific. 
However, translationWords and translationNotes is book specific. And that looks like a lot of data.

**Comment by RoyalSix** [comment]
I agree with tA, but what if we process the data for every book for translationNotes/Words, then load that from a repo (whichever book is specified)
We could leave user specific fields, time stamps and other project specific data blank until used
Would the download of a 2.5Mb+ file be as fast as downloading a 700Kb+ file (tA) and then processing it into 2.5Mb+?

**Comment by ihoegen** [comment]
In most of our intended use cases, processing it ourselves into 2.5Mb would be faster. At the very least, we  should have the source files for tN and tW packaged with the respective tools. Although I do like the idea of preprocessing it into JSON and leaving the fields blank.

**Comment by RoyalSix** [comment]
By "source files for tN and tW" you are referring to the .tc files that have the "check data"?

[TranslationWordsChecker.txt](https://github.com/unfoldingWord-dev/translationCore/files/552016/TranslationWordsChecker.txt)

**Comment by RoyalSix** [comment]
I propose taking out any data that is not relevant to tC itself, looking at the roadmap for the app.

**Comment by RoyalSix** [comment]
I propose taking out any data that is not relevant to tC itself that is project specific that can be loaded(not processed again in the app, but processed outside of the app and will be static information for the most part), looking at the roadmap for the app. 
This includes:
- Gateway Bible 1.7 Mb
- Hebrew Bible 10.9 Mb
- Greek Bible 1.7 Mb
- Any type of data that the developer can specify, and the location of it on the repo. (tW/tN check data)
     - Sort of like if each module can have a static folder

**Comment by klappy** [comment]
High level need is attaching all required files that get downloaded when running a check for the first time for a book, move that to be downloaded all at once for all books while installing the checking tool. There shouldn't be anything downloaded when loading a checking tool for a project, because it should already have been downloaded during the install of the checking tool.

**Comment by ihoegen** [comment]
I've got a PR open for tA: https://github.com/translationCoreApps/translation_academy/pull/1
@RoyalSix By source files, I mean these: https://github.com/Door43/d43-en/tree/master/bible/notesfor translationNotes, https://github.com/Door43/d43-en/tree/master/obe/kt for translationWords. The tW source appears to be a whole lot smaller.

**Comment by ihoegen** [comment]
I think by at least cutting down on http request that are to be made with each target language, we can improve functionality tremendously.

**Comment by RoyalSix** [comment]
note on translation Notes:
- There is two type of data im seeing processed:
  - The complete list of wordList that contains all the information for translationWords from github
  - The wordList specific to the project(chunks completed, book of the bible)
    My thought is if we get the complete word list downloaded as a JSON (finished this) then we can use that to process it either two ways:
    - Retain the current way its being processed
      - this results in the same load time for tWords but requires no internet connection
    - Preprocess every book (all chapters) and then just load in specific chunks from a huge (2.5 Mb+ \* 66) JSON based on book/finished chunks index

**Comment by klappy** [comment]
This is a great starting point. Let's download them all and process on load, this addresses the biggest current issue. We can later optimise the processing but for now let's focus on the downloads.

**Comment by RoyalSix** [comment]
Sounds good.
