### ISSUE TITLE
[0] Implement logic to block non-Titus projects from importing in non-dev mode

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#2432]

**Comment by klappy** [comment]
@cckozie: Should we remove evidence of this from the project folder once we prevent it from opening? I assume so, as it wouldn't be expected behavior for it to reside in the project list after we block it.

**Comment by cckozie** [comment]
@klappy I'd say let's not block it for now. We have allowed visibility into non-Titus/Eph projects from Door43, but stopped loading them unless in developer mode. I think that blocking visibility into them would be a new issue from the PO.
