### ISSUE TITLE
Do we want to hide non-Titus project when the user is not in developer mode?

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2443]
Currently we display all projects, we just don't allow loading them.

**Comment by benjore** [comment]
When the user is not in developer mode, modify all non-Titus project cards as follows:
- [ ] Disable the Select button. 
- [ ] Gray out the text in project box. Use #BFBFBF as the text color for the text elements on the card.
- [ ] When hovering over the Select button, have a pop-up that says, "Only Titus projects are supported."
