### ISSUE TITLE
Cannot import local tstudio projects

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2444]
[en-x-demo1_php_text_ulb.tstudio.zip](https://github.com/unfoldingWord-dev/translationCore/files/1225359/en-x-demo1_php_text_ulb.tstudio.zip)
![image](https://user-images.githubusercontent.com/8171759/29320604-544630e6-819d-11e7-91b5-5f0923cfaaed.png)

**Comment by cckozie** [comment]
Can import but not open this one.
[ilo_1jn_text_reg.tstudio.zip](https://github.com/unfoldingWord-dev/translationCore/files/1225401/ilo_1jn_text_reg.tstudio.zip)
![image](https://user-images.githubusercontent.com/8171759/29320925-6f073316-819e-11e7-9185-b35b26d08938.png)

**Comment by mannycolon** [comment]
# Tasks
- [2] Debug wrong references of helper functions.
- [3] Fix wrong references of helper functions.

**Comment by mannycolon** [comment]
It looks like the items above about the project list being displayed  has been fixed, but the app now hangs when importing https://git.door43.org/tc03/bhd_tit_text_reg
(Actually, it looks like it fails to import any project)
![image](https://user-images.githubusercontent.com/8171759/29319152-956d6350-8198-11e7-9c15-8c21deef12d5.png)

**Comment by cckozie** [comment]
I think something may have been broken in beta.54. This is a good project exported from tS that won't import into tC. Some tS project work, some don't. It could have to do with a number being in the project name.
[es-419_tit_text_ulb-3.tstudio.zip](https://github.com/unfoldingWord-dev/translationCore/files/1250003/es-419_tit_text_ulb-3.tstudio.zip)

![image](https://user-images.githubusercontent.com/8171759/29684733-a299f5e2-88d8-11e7-80f3-d93484232995.png)

**Comment by mannycolon** [comment]
# 2nd QA tasks
- [2] Debug issues with importing `.tstudio` projects
- [4] Fix issues with importing `.tstudio` projects.

**Comment by mannycolon** [comment]
@cckozie Found out that this issue is related to changing the project name of a `.tstudio` project. 
This should probably be a different/new issue/user story.

**Comment by mannycolon** [comment]
@klappy @benjore

**Comment by cckozie** [comment]
@mannycolon OK, that makes sense. I'll pass this one and write up a new issue. (issue #2551)
The other projects listed above do import now and load now with the exception of the ilo_1jn_text_reg one. That one loads to an open checking screen which I'm assuming is a problem with the missing verse check.
