### ISSUE TITLE
[0] Spike: Determine project name structure for consistency

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#2455]
The project/folder names for tS projects is something we should closely mimic. 
`[language_id]_[book_id]_[project_type]`
However, there seems to be some confusion with the usage of `reg` and `text` for the project type.
I propose that we ask @benjore, @cckozie, @jag3773 what would be acceptable here, and add that option in the Project Details Screen.

For example, Spanish, Titus, ULB project would be:
`es-419_tit_ulb`

**Comment by jag3773** [comment]
This should answer most of the questions: https://git.door43.org/Door43/registry#registry .  Let me know if any persist after reading through that spec and examples.

**Comment by klappy** [comment]
## Explicit Project and Type
### Form
`[language]_[resource]_[project]_[type]`
### Examples
- en_ulb_gen_book
- en_obs_obs_book
- en_obs_obs_video
- en_tn_gen_help
