### ISSUE TITLE
General Notes to be checked (tN)

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#246]
As a user, I want to check notes that are not tagged to a translationAcademy article so that I don't miss anything.
- [ ] Parse what we can and add them to a General category.
- [ ] Ask notes team if they can tag Alternate Translations.
- [ ] How to handle General Information/Connecting Statement.
- [ ] Generate some output of notes that don't get included in tC.

**Comment by benjore** [comment]
Proposal: Make General Notes its own tool, divided by chapter, organized verse-by-verse. Move all Figures of Speech tN into their own tool.
