### ISSUE TITLE
Limit which files are selectable for importing locally

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2468]
Do no allow the user to select any file for importing that does not have a USFM, SFM, TXT, or TSTUDIO extension.

**Comment by benjore** [comment]
Don't show other files.

**Comment by jag3773** [comment]
Related to #2954

**Comment by PhotoNomad0** [comment]
### Tasks:
- [ ] [4] Change file selection filter
- [ ] [6] Add Unit tests
