### ISSUE TITLE
Gray out (disable) sources that have already be loaded in Scripture Pane

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#2470]
## User Story

As a user, I want to clearly see which resources are already showing in the Scripture Pane so I don't get frustrated by loading up two instances of the same resource.

**Comment by benjore** [comment]
This is the list in the drop down.

**Comment by richmahn** [comment]
- [ ] [3] Gray out (disable) sources that have already be loaded in Scripture Pane
- [ ] [3] Write unit tests for checking loaded sources are grayed out in scripture pane
