### ISSUE TITLE
Cannot export to USFM

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2478]
.beta46
![image](https://user-images.githubusercontent.com/8171759/29421209-fb7e4658-8339-11e7-8a31-2985f92e4a88.png)

![image](https://user-images.githubusercontent.com/8171759/29421253-1bac18ce-833a-11e7-83b4-1715a8304e11.png)
Nothing in the console
[es-419_tit_text_reg.zip](https://github.com/unfoldingWord-dev/translationCore/files/1231843/es-419_tit_text_reg.zip)

**Comment by cckozie** [comment]
beta.53
The export now indicates that it is successful, but the output file has issues.
\id TIT EN_ULB es-419_Español Latin America_ltr Wed Aug 23 2017 13:43:25 GMT-0500 (CDT) tc
\h Titus
\v 1 [object Object]
\v 2 [object Object]
\v 3 [object Object]

[es-419_tit_text_ulb_sav.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/1246746/es-419_tit_text_ulb_sav.usfm.zip)

**Comment by RoyalSix** [comment]
## Tasks
- [ ] [2] Test project to find location of bug
- [ ] [3] Fix exporting feature to parse object instead of just writing out object

**Comment by klappy** [comment]
In build 63 not build 62

**Comment by cckozie** [comment]
.beta63
Exported multiple projects OK.
