### ISSUE TITLE
Offline Error Handling

### ISSUE THREAD

**Issue by RoyalSix** [unfoldingWord/translationCore#25]
If a user is connected to the internet, opens the app then disconnects, and loads an app they will be stuck in the loading screen and have to restart.
...if there are more errors you guys find we can make an epic.

**Comment by therealsamf** [comment]
Yeah we should probably make an epic for general error checking/robustness (if that's a word). If anything happens during FetchData the app crashes and you can't navigate off the loading screen, when the workflow should be an error popup and then they can choose to load another module

**Comment by RoyalSix** [comment]
@eldoubleyew did this (:

**Comment by klappy** [comment]
Is this still an issue?
