### ISSUE TITLE
Missing verses check is bypassed and project hangs when opening

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2505]
beta.52
[es-419_luk_text_ulb.tstudio.zip](https://github.com/unfoldingWord-dev/translationCore/files/1242671/es-419_luk_text_ulb.tstudio.zip)
This is a good project exported from tS. There are many missing verses, but none were detected by the missing verses check (assuming that it actually ran).
When opened with tW, the app hangs with the Loading... dialog displayed.
![image](https://user-images.githubusercontent.com/8171759/29576250-c6ce5ae6-872c-11e7-94ff-34204db06c1a.png)

**Comment by RoyalSix** [comment]
- We need to create the target language bible after all the checks are ran and there are no merge conflicts

**Comment by cckozie** [comment]
This no longer appears to be a problem in .beta63.
