### ISSUE TITLE
tHelps panel is cut off when window width is minimized

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2512]
beta.52
![image](https://user-images.githubusercontent.com/8171759/29585453-c8ae30a0-874c-11e7-9792-411adc97f60d.png)

**Comment by RoyalSix** [comment]
## Tasks
- [ ] [3] Find culprit of css that is causing issue for width
- [ ] [1] Implement fix for width on tHelps
 
Note: High level fix is the tHelps width should be dynamic but have a min width corresponding to how big the parent is
