### ISSUE TITLE
Make the app more consistent when attempting to import projects when not in developer mode

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2513]
beta.52
Currently we don't allow users to import non-Titus projects locally, either tstudio or usfm, but we do allow them to import online non-Titus projects and then prevent them from loading them. We should probably make it consistent on either blocking the import or blocking the loading in all cases.

**Comment by benjore** [comment]
Will soon be outdated with OT projects being allowed to be imported for Word Alignment
