### ISSUE TITLE
Change the text on the "must be logged in with door43 account" message

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2517]
![image](https://user-images.githubusercontent.com/8171759/29626207-a0e0efd4-87f3-11e7-950e-99517062d9e2.png)
Change text to "You must be logged in with a Door43 account to upload projects. Please log out and then back in with a Door43 user account".

**Comment by cckozie** [comment]
Tested in tC_Test_Verbiage_Misc.sikuli

**Comment by cckozie** [comment]
Sorry to fail this, but there needs to be a period at the end of the second sentence. (Yes, I understand that I had the closing quote before the period in my comment, but I feel that someone should have caught this and questioned it.)

**Comment by bspidel** [comment]
## Tasks
- [ ] [1] Add period to second sentence

## Test
1. login as guest
1. select project
1. attempt to upload to door43 (click ellipsis on project)

**Comment by cckozie** [comment]
This was fixed in alpha.11 in #3072
