### ISSUE TITLE
We need to deal gracefully with projects that are not individual books of the Bible

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2524]
Door43 has many projects that contain multiple books (mostly labeled as "Bible") and also tN, tW, tA, and OBS projects. Currently we allow importing of the Bible projects, but only a console error is reported when attempting to select one of them. The user has no clue as to why he couldn't select it. 
In the case of OBS, I'm seeing it trying to run the stepper, but then fails without a user message.
In the case of the helps projects, the message is:
![image](https://user-images.githubusercontent.com/8171759/29670942-d36733c2-88ad-11e7-85de-d836400e77f8.png)
In each of these cases, a project is created and left in the tC Projects folder. Invalid projects should get deleted.
Also, we need to be able to deal with attempts to import all of these "invalid" projects locally.

**Comment by klappy** [comment]
Is it Titus?
Is it NT book Project?
Is it a book of the bible?
Is it more than one book?
Does it have a manifest?
Is it tW or tH or tQ?

**Comment by RoyalSix** [comment]
## Tasks
- [ ] [4] Verify project structure on import
- [ ] [3] Tests for project structure verification

**Comment by RoyalSix** [comment]
@cckozie Would you happen to have a door43/tS project with multiple books

**Comment by cckozie** [comment]
@RoyalSix Here's one: https://git.door43.org/phillip-hopper/bible_hi

**Comment by RoyalSix** [comment]
https://git.door43.org/Jarern/th_obs_text_obs.git
https://git.door43.org/richmahn/hr_obs.git
https://git.door43.org/tx-manager-test-data/nt_ru.git
https://git.door43.org/richmahn/en_tn_mat.git
https://git.door43.org/benVar/en_ta.git
https://git.door43.org/uday/en_tw.git

**Comment by RoyalSix** [comment]
@cckozie What strings do we want for this? 
Right now I have 
```
//Beginning of every error
Project selection failed

//Second part depends on which project was trying to be loaded
You cannot load Open Bible Scriptures into tC
You cannot load translationNotes resource content into tC
You cannot load translationQuestions resource content into tC
You cannot load translationAcademy resource content into tC
You cannot load translationWords resource content into tC
```

**Comment by benjore** [comment]
@RoyalSix 
Can you change the basic message for all of these to read: 

`translationCore does not support checking for translationNotes. It will not be loaded.`

Also, it should be `Open Bible Stories` (not `Open Bible Scriptures`)

You should probably add a "catch-all" one too: `translationCore does not support this file type. It will not be loaded`

**Comment by RoyalSix** [comment]
So its just one message correct? For all the errors? @benjore

**Comment by RoyalSix** [comment]
@benjore do you mean substitute {translationNotes} for the type thats not able to be loaded?

**Comment by cckozie** [comment]
beta.79
https://git.door43.org/chuck/es-419_bible_tw
![image](https://user-images.githubusercontent.com/8171759/30752008-a3ed13ca-9f80-11e7-98c5-e5e8b99467ae.png)

**Comment by cckozie** [comment]
Another issue in beta.79 with tQ and tN projects:
https://git.door43.org/danieldane003/ceb_2sa_tq_L3
https://git.door43.org/danieldane003/ceb_2sa_tn_L3
tC indicates that the project imported successfully.
The book name is missing on the project info card, but it lets me continue anyway. (I'll write this up as a separate issue)
When attempting to load with tW, the app hangs with this console message:
![image](https://user-images.githubusercontent.com/8171759/30754029-cb38ae16-9f86-11e7-92f0-9de3c74ee873.png)
