### ISSUE TITLE
Allow renaming of project on import

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2546]
As a user I would like to be able to customize the name of a project after selecting it for import so that I can use names meaningful to me, and so that I can reimport a project already on my machine by changing its name.

**Comment by benjore** [comment]
Change the folder name. 
There may be a spot in the manifest to add name. 
Change Door43 location too. 
Write tests.

**Comment by benjore** [comment]
Do we allow users to name their project whatever they want? Upload it to Door43 as a new project with that name? Keep the usual prefix & give it a custom suffix?

**Comment by benjore** [comment]
The `title` should be customizable but the `folder` should not.

**Comment by benjore** [comment]
Related to #3421

**Comment by benjore** [comment]
Subsumed by #3421
