### ISSUE TITLE
FAB options should be disabled when file finder/explorer is displayed

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2550]
The options on the FAB should not be active when the finder/explorer is open. They currently are active. (beta.54). It would probably be best to close the FAB when selecting files for local imports like we do when doing online imports.
![image](https://user-images.githubusercontent.com/8171759/29734970-07497d9a-89bb-11e7-8e37-6804d04edc59.png)

**Comment by RoyalSix** [comment]
- [ ] [2] Close FAB after file explorer is opened

**Comment by cckozie** [comment]
This has been implemented but the issue is actually larger than the FAB. See issue #2715.
