### ISSUE TITLE
Allow importing projects when the project's name does not match the name in the manifest the proj

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2551]
When exporting projects from tS, the user is allowed to change the name of the tstudio file. Also, tS users in the field often change the name of the project's repo. tC needs to be able to import and process such projects.

**Comment by benjore** [comment]
Use the internal folder name for the project name instead of the zip file's name.

**Comment by mannycolon** [comment]
Fixed on #2980

**Comment by cckozie** [comment]
@benjore 
I am now able to successfully import projects whose name does not match the manifest. In your instructions above, you specify that the project should get the name from the "internal folder name". Are you referring to the name in the manifest? Currently tC is naming the project according to the tstudio file name. Is that OK?

**Comment by cckozie** [comment]
alpha.12
Works now. Project name is same as tstudio/Door43 name.
