### ISSUE TITLE
Do not add the loggged in user as a checker when creating the manifest for imported USFM projects

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2587]
The logged in user is currently being added to the manifest as a checker whenever a USFM project is imported. That is not a desired behavior.

**Comment by RoyalSix** [comment]
@cckozie Do we want to have the logged in user as the default checker for regular project imports?

**Comment by cckozie** [comment]
@RoyalSix Per Ben, we do not want to add any user information to the manifest. The information about users who performed checking activities will be available in the CSV export now, and later after we have implemented reporting.

**Comment by cckozie** [comment]
I think something was broken with this fix. Now when I import a new project, even after going through the validation stepper and loading the project, when I select it again I am again presented the project information screen even though all of the fields were already entered.

**Comment by RoyalSix** [comment]
- [ ] [2] Debug how import process stopped persisting
- [ ] [1] Fix import persisting
