### ISSUE TITLE
Don't wrap the edit reason codes unless necessary

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2606]
Work Choice should not be wrapped. There is plenty of space with this screen size.
![image](https://user-images.githubusercontent.com/8171759/29838015-860c4bd8-8cbf-11e7-930b-2b1cd129c010.png)

**Comment by RoyalSix** [comment]
2 x 3 unless width does not allow

**Comment by RoyalSix** [comment]
## Tasks
- [ ] [2] EditMode:Make Text Wrap Only When Needed
