### ISSUE TITLE
Project Import Problems (merge conflicts)

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#2607]
I tried to import the project: https://git.door43.org/EllDoubleYew/ar_eph_text_ulb 

Problem #1: There was a merge conflict. I tried to resolve it, but could not click anything that would accept my selection and move on. (It allows the user to select one of the merge options and enables the Continue button, but then clicking Continue has no effect.)

Problem #2: I then canceled out of the project import, but the project showed up in the list of projects. 

Problem #3: When I tried to open the project, the app froze (spinner spun forever) and I had to close the program. 
![image](https://user-images.githubusercontent.com/8171759/29883028-883a5ed0-8d74-11e7-97ef-c5506526fbb0.png)

Note: When I reopened tC, I was able to open the project (without completing the stepper) and begin checking.

**Comment by cckozie** [comment]
This is an interesting project. I can import and open it in tS Android, but not tS desktop. I do know that verse 5 in chapter 1 is in English and the rest of the project is Arabic. Could that be the problem?
The app needs to be able to handle such situations gracefully. It needs to detect any problem in an imported file and either allow the user to resolve the problem, or if it is not resolvable within tC, then warn the user of such. (I think we already have an alert that states that the project has fatal errors) 
The app should never hang.
The project should never open unless it has successfully made it through the stepper. Cancelling at any step of the stepper indicates that it has not successfully made it through.

**Comment by cckozie** [comment]
.beta63
After importing the project I am presented the Merge Conflicts screen. After selecting the version I want, clicking on the continue button does not do anything. After clicking the Continue button a second time, I still stay on the same screen but see this in the console:
![image](https://user-images.githubusercontent.com/8171759/30139161-d8630b92-9331-11e7-8219-ac7cac22112c.png)

**Comment by klappy** [comment]
Tasks:
[2] Merge Conflicts: Evaluate and determine differences of this project
[1] Merge Conflicts: Add test use case to handle this issue
[1] Merge Conflicts: Evaluate workflow and implementation
[2] Merge Conflicts: Make test pass
[2] Merge Conflicts: Refactor code edits

**Comment by cckozie** [comment]
Now tC displays a merge conflict without any data.
![image](https://user-images.githubusercontent.com/8171759/31131507-fcda4a14-a81f-11e7-8010-6e4c1f1090ad.png)

**Comment by cckozie** [comment]
This problem appears to have been solved, but I need to retest after the tW tool is back.
