### ISSUE TITLE
RTL not working in expanded Scripture Pane

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#2608]
RTL worked in the Scripture Pane, but not in the expanded Scripture Pane. 

Note: this is only an issue in the 3-version Scripture Pane. The expanded "Select" scripture pane with just Arabic works as expected. 

I was using this project https://git.door43.org/EllDoubleYew/ar_eph_text_ulb (see #2607 for problems with importing that file)

**Comment by RoyalSix** [comment]
## Tasks
- [ ] [4] Fix RTL On Expanded Scripture Pane

**Comment by cckozie** [comment]
beta.78
https://git.door43.org/tc01/ar_mat_text_ulb
Expanded scripture pane does not open. Console shows this error:
![image](https://user-images.githubusercontent.com/8171759/30751302-917fb2f8-9f7e-11e7-85c4-2987820ef344.png)
