### ISSUE TITLE
Checks are skipped

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2613]
beta.57
[es-419_tit_text_ulb_sav 3.zip](https://github.com/unfoldingWord-dev/translationCore/files/1265442/es-419_tit_text_ulb_sav.3.zip)

Open with tW
Go to the "blameless" group
The check for 1:7 works fine
The check for 2:6 is skipped, both when moving forward from 1:7, and when clicking on the 2:6 check directly.
The same is true for 1:6 in the "evil" group.
(There is text for the verses related to the checks that are skipped)

There are multiple checks that are skipped in most projects I have loaded.

**Comment by klappy** [comment]
Instead of skipping checks, fix the scripture pane from crashing.

**Comment by klappy** [comment]
Tasks:
[3] Check Skip: Modify code to no longer validate/skip checks when quote is invalid
[2] Check Skip: Debug Scripture Pane and determine fix for crashes
[2] Check Skip: Extract functions as helpers

**Comment by cckozie** [comment]
beta.69
Did a full check of Eph, Php, and Titus. No problems found!
