### ISSUE TITLE
Cannot add Bible to scripture pane

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2621]
beta.57
Happens on multiple projects. Had trouble deleting them too. Now I can only see what is in the first column.
![image](https://user-images.githubusercontent.com/8171759/30006351-4618e92c-90bc-11e7-835b-a79346b0b7ad.png)

**Comment by mannycolon** [comment]
# Tasks
- [2] Fix scripture pane adding functionality
