### ISSUE TITLE
Corrupted manifest file

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2633]
I was using this project earlier today and it was fine. I then loaded some other projects to do QA testing. When I came back to it, it hung when loading. Based on the console log message, I looked in the manifest and see that now both the book and the language are wrong there.
![image](https://user-images.githubusercontent.com/8171759/30126312-34d6613e-9301-11e7-8e4c-f0e347c36d8a.png)
[fr_eph_text_ulb_old.zip](https://github.com/unfoldingWord-dev/translationCore/files/1282105/fr_eph_text_ulb_old.zip)

**Comment by cckozie** [comment]
.beta63
Something similar has happened again. I imported the project @ https://git.door43.org/tc01/fr_eph_text_ulb/
On the project page it shows that the project has the wrong book and no language code.
![image](https://user-images.githubusercontent.com/8171759/30138192-857bb686-932c-11e7-850b-c5ad5aa38249.png)
Here is the manifest file from Door43:
[ fr_eph_text_ulb_manifest.txt](https://github.com/unfoldingWord-dev/translationCore/files/1282922/fr_eph_text_ulb_manifest.txt)
Here is the manifest file from tC:
[manifest.json.txt](https://github.com/unfoldingWord-dev/translationCore/files/1282924/manifest.json.txt)

**Comment by cckozie** [comment]
Here's how to replicate the problem directly above:
1. Delete the translationCore/Projects folder
2. Start tC
3. Import https://git.door43.org/tc01/fr_eph_text_ulb/ but do not open it. (When the Tools page comes up, click on the Go to Projects button)
4. Import this USFM file:
[php_usfm_NoV1.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/1282968/php_usfm_NoV1.usfm.zip) 
5. Enter es-419 as the language code and language name
6. Click Cancel on the Missing Verses page
Note that the book is wrong and language is now missing on the fr_eph_text_ulb project

**Comment by benjore** [comment]
test after imports to make sure manifests are valid
