### ISSUE TITLE
Problems with missing verse detection when importing tstudio projects

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2642]
beta.63
The same problem exists both when importing locally and from Door43
https://door43.org/u/TC_SAVE/abu_tit_text_reg
[abu_tit_text_reg.tstudio.zip](https://github.com/unfoldingWord-dev/translationCore/files/1289085/abu_tit_text_reg.tstudio.zip)
This project is missing these verses: 1:1, 1:9-10, 2:1-15
(All verses in chapter 2 are missing. Titus 3:3 and 3:8 are single verse chunks, so it looks like not handling those two scenarios are at least part of the problem.)
(The same project in USFM format does import correctly

tC reports:
![image](https://user-images.githubusercontent.com/8171759/30230549-66376514-94ac-11e7-953e-d0bd1fcb672d.png)

**Comment by mannycolon** [comment]
# Tasks
- [4] Unified the process used to detect missing verses for all projects (USFM, tStudio)
- [1] Debug for issues related to missing verses
- [3] Fix bugs found in missing verses check

**Comment by cckozie** [comment]
There is also a problem that tC no longer catches it when I'm trying to load a local tstudio file when that project already exists in tC. I'm hoping/assuming that is fixed when the same problem is addressed for USFM files in #2190, but if not, it should be fixed here.

**Comment by RoyalSix** [comment]
I am not able to get the project into tC from online import using the url ```https://door43.org/u/TC_SAVE/abu_tit_text_reg```

**Comment by RoyalSix** [comment]
@cckozie So we should handle chunks that have no verse marker but are implicit because its on the file name

**Comment by cckozie** [comment]
I assume you're talking about the chunk file name, and I suppose that would be one way to handle. Not sure if there are other ways. In any case, we can't report verses missing when they are actually there. Maybe a look at the tS code would be helpful. The "missing" verse markers do actually appear in tS.

**Comment by cckozie** [comment]
The missing verses check now catches the correct verses, but when the referenced project is imported from Door43 and loaded with tW, the app is broken. When the tool opens to the first check and I click on the expanded scripture icon, it takes 12 seconds for the panel to open. When I click on the next checking group, I get this message in the console:
![image](https://user-images.githubusercontent.com/8171759/30834310-2a30cee2-a218-11e7-8bef-06bdd1aff8a5.png)

**Comment by cckozie** [comment]
The issue mentioned directly above has not been fixed. It still takes a long to time to open the expanded scripture panel and the console is full of errors.

**Comment by RoyalSix** [comment]
Those errors are actually warnings (That say error). I can remove them. They are not helpful at all to the user or the developer.

**Comment by cckozie** [comment]
Cannot fully test until I have access to tW tool again.

**Comment by cckozie** [comment]
.beta96
tC is still incorrectly reporting that verses 3:3 and 3:8 are missing.

The problem with it taking so long to open the expanded scripture pain has been fixed.
The errors in the above comment no longer appear when the project is opened in tW.

**Comment by RoyalSix** [comment]
- [ ] [2] Detect/ Handle single chunks from tStudio projects
