### ISSUE TITLE
Implement Greek Titus USFM

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#2650]
- Add Greek Titus USFM to resources sub module
- Replace current Greek Bible with this limited one
- Update parsing to our internal json

**Comment by klappy** [comment]
[57-TIT.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/1293585/57-TIT.usfm.zip)

**Comment by mannycolon** [comment]
# Tasks
- [6] Add Greek Titus USFM to resources sub module
- [6] Update parsing to our internal json
- [5] Replace current Greek Bible in tC with this limited one

**Comment by mannycolon** [comment]
`Blocked` until completion of `tC_resources` submodule
