### ISSUE TITLE
[0] Add Greek Titus USFM to resources sub module 

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord/translationCore#2652]

**Comment by klappy** [comment]
@RoyalSix If you don't mind getting to this one soon. I only have one story left that isn't blocked by this task. 

You might need to further break this one down... 
[1] Add raw USFM 3 file to repo temporarily until in API
[?] Parse USFM 3 to tC compatible json
[2] Add parsed data to resources repo as ugnt/v0.2

I'm okay if I get through with my other story to pick this one up if you can't get to it yet.

**Comment by RoyalSix** [comment]
@klappy Sounds good.
