### ISSUE TITLE
Extracting tC apps/modules to their own Repo

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#27]
As a developer I want to manage apps/modules in separate repos so that we can optimize development life cycles.

The topic of removing modules/apps from the tC codebase and each module/app being in its own repo has come up quite a few times when exploring this with other development teams.

Here are my thoughts so far:
- tC has **no** apps/modules in the code base. 
- Each tC app has its own repo and lifecycle.
- We finalize tC API spec 1.0 and don't make any breaking changes to the API.
- Each app needs to define which API spec version that is being used for compatibility checks.
- We allow adding of tC apps just like adding a project, by git URL or release URL from github.
- We can ship tC with links to approved tC apps that can be downloaded with a click.
- Eventually add a way to browse and search for tC apps.

Decisions need to be made:
- Do we bundle any with the builds? Yes.
- Ensure that offline users have a way to get apps.

**Comment by therealsamf** [comment]
So what are your thoughts on the 'tools' -- like TPane -- that aren't apps themselves but are decoupled as to be used in multiple tc apps without duplicating code. If they're included within tc app's repos themselves then the decoupling goes away; an other option I can think of is putting those in their own repos as well, but that creates a lot of repos, potentially for miniscule tools such as example_tool or proposed_changes.

**Comment by klappy** [comment]
Maybe we should list Pros/Cons of separate repo.

# Separate

## Pros
- modular
- independent development lifecycle
- app/modules can control versions to include?
- potential increased contributions 
- smaller code bases

## Cons
- potential sync issues
- more repos to manage
- likely more...

**Comment by klappy** [comment]
We mentioned it in slack but will officially write it here.

Pros seem to outweigh the cons, so we're going to move forward with the separate repos for all modules. For time sake, we can start with just the apps. Then extract other components/tools one out at a time.
