### ISSUE TITLE
Another selection anomoly

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2700]
[sw_tit_text_ulb.zip](https://github.com/unfoldingWord-dev/translationCore/files/1300045/sw_tit_text_ulb.zip)
Open the project in tN and go to Titus 1:7 in Metaphors
Double click the word "Lazima"
Drag to select the letters "asi" in the following word. You should see the selection like this:
![image](https://user-images.githubusercontent.com/8171759/30387872-91845c2a-9873-11e7-8f8f-350e2057ef4c.png)
Now place the cursor between the "m" and the "w" in the word "mwepesi" and click and drag to the left until you get the cursor between the "a" and the "s" in "asiwe". Release the cursor and you'll see errors in highlighting, presumably because of the repetition of the words.
![image](https://user-images.githubusercontent.com/8171759/30388035-0fbfb21a-9874-11e7-8601-c2599c35abc9.png)

**Comment by bspidel** [comment]
This report does not say what the correct behavior should be.

**Comment by cckozie** [comment]
This issue can be tested in tW by going to the word "blameless" in the menu. Verse 1:7 will be the first verse there which is the same as in the first comment above.
The correct behavior would be for all of the selections (and only them) to be highlighted as is shown here:
![image](https://user-images.githubusercontent.com/8171759/34575701-54d4dda0-f141-11e7-81f9-ea2101dbfdd9.png)

**Comment by klappy** [comment]
@cckozie: The latest PR should address the issue and not introduce any new bugs. :tada:

**Comment by cckozie** [comment]
Looks good, but I did uncover another selection issue that was existing before. #3753
