### ISSUE TITLE
unexpected behavior when making a selection that includes special characters (? ! $ &) 

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord/translationCore#2704]
verse edit bug

**Comment by mannycolon** [comment]
<img width="1280" alt="screen shot 2017-09-14 at 3 56 23 pm" src="https://user-images.githubusercontent.com/17072300/30453380-b931357e-9966-11e7-8b88-0cc6839d6d02.png">

**Comment by cckozie** [comment]
I'm pretty sure this is fixed in beta.79
