### ISSUE TITLE
The main tC screen should be dimmed & disabled when Finder or Explorer is open

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2715]
This is the case both when doing a local import and a USFM or CSV export. It should work the same as it does when selecting a Door43 project for import.

**Comment by mannycolon** [comment]
## Tasks
- [ ] [5] Find a way to dim the screen so that the FAB isn't clickable.

**Comment by cckozie** [comment]
Tested in tC_Test_Verbiage_Misc.sikuli

**Comment by cckozie** [comment]
beta.96
This works on Mac,
On Windows it works when choosing to export to CSV, but when choosing to import a local project, the main screen is dimmed, but when I click on the FAB, the main screen window is brought to the foreground and the Explorer window is hidden behind it.

**Comment by mannycolon** [comment]
# Task
- [ ] [3] Fix QA issues for the dimmed screen component.
