### ISSUE TITLE
Add detecting and reporting USFM file problems, other than missing verses and bad/missing id, to project validation stepper

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2724]
We current catch problems with missing verses and missing or bad book id, but we don't properly catch things like missing or misplaced chapter markers. Those currently show up as missing verses which is not correct. Such problems should be caught and properly reported in the UI.

**Comment by benjore** [comment]
Need: a list of all problems we will be trying to catch.

**Comment by cckozie** [comment]
I think missing and misplaced chapter markers are the important ones that we are not accounting for now (other than misinterpreting them as missing verses). This could probably be added to the missing verses panel.

**Comment by benjore** [comment]
dup of #3309
