### ISSUE TITLE
Add "X" to close UGNT popup

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2730]
It is not obvious how the user can close the popup.

**Comment by RoyalSix** [comment]
- [ ] [2] Find way to use icon in material-ui popover element, and style presentationaly
https://material.io/icons/#ic_close

**Comment by RoyalSix** [comment]
- Wherever the greek popover is available

**Comment by RoyalSix** [comment]
@cckozie @benjore  Is it ok to add close functionality to all popovers such as the ones in the home stepper on the user screen when you click the (i) icon

**Comment by cckozie** [comment]
I don't see any problem with doing that. I think it would be good.
