### ISSUE TITLE
Wrong message issued when repo is not found

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2740]
Attempting to import project https://git.door43.org/Danjuma_Alfred_H/sw_tit_text_ulb generates an error that states "Cannot clone repository". Actually, the referenced repo no longer exists. That user now has projects labeled sw_tit_text_ulb_L2 and sw_tit_text_ulb_L3. The message should state "Project not found."

**Comment by PhotoNomad0** [comment]
## Tasks

- [x] [0] Add unique prompt if repo is not found.
- [x] [0] Do unit tests (includes Learning how to do unit testing in tC)

**Comment by cckozie** [comment]
Tested in tC_Test_Verbiage_Misc.sikuli
