### ISSUE TITLE
Update BHP (Greek NT) for Titus

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#2741]
## Tasks
[1] UGNT: Run USFM parsing on latest file
[1] UGNT: Update parser to maintain punctuation
[1] UGNT: Update Titus UGNT in tC_Resources

## Notes
- Keep named the BHP

**Comment by klappy** [comment]
@jag3773 Can you attach the latest version here? 
It should have the updated capitalization and punctuation in place.

**Comment by jag3773** [comment]
Latest is at https://git.door43.org/Door43/BHP

**Comment by cckozie** [comment]
There are some case differences between the BHP and what we are showing in tC:
(based on https://git.door43.org/Door43/BHP/commit/118ab0b72c22cfd32e67974a14721aa85949c49d)
![image](https://user-images.githubusercontent.com/8171759/31250122-719afe50-a9df-11e7-8cc8-054ca816a446.png)
![image](https://user-images.githubusercontent.com/8171759/31250138-7c7c9202-a9df-11e7-8121-df37252b9605.png)
It's not as obvious in the text on the screen, but the same is true for G23160, and possibly others.
![image](https://user-images.githubusercontent.com/8171759/31253036-d6634a32-a9e8-11e7-8b37-d0a554f9cfce.png)
![image](https://user-images.githubusercontent.com/8171759/31253044-dcbb032a-a9e8-11e7-9b29-c47199924342.png)

**Comment by jag3773** [comment]
@cckozie Can you be more specific?  I can't find the difference that you allude to.

**Comment by cckozie** [comment]
@jag3773 I don't know Greek but am assuming these are case differences
![image](https://user-images.githubusercontent.com/8171759/31284730-0f3d0bcc-aa7f-11e7-9301-b72399367f04.png)

**Comment by jag3773** [comment]
Good catch @cckozie.
