### ISSUE TITLE
Alignment: Create helper to sort word objects in proper order

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#2752]
## Tasks
[1] Alignment Sort: Review use cases for word object sorting
[2] Alignment Sort: Write tests for sorting word objects
[2] Alignment Sort: Create helper to sort words in proper order
[2] Alignment Sort: Make tests pass for sorting word objects

## Use Cases
- Sort word bank items when added to Greek words
- Sort word bank items when moved back
- Sort Alignment data for populating targetLanguage verse array

**Comment by cckozie** [comment]
I can put the GL words in pretty much any order I want them either when initially dropping them into a box, or rearranging them afterwords. (Once moved into a box I can drag words to the right within the box, but not to the left)
@benjore - Is this something we need to be fixed before 0.8 release?
![image](https://user-images.githubusercontent.com/8171759/31129160-5e0ca3f6-a819-11e7-952c-9e322c943e44.png)

![image](https://user-images.githubusercontent.com/8171759/31129183-6dac1378-a819-11e7-8735-e0d7c16edce1.png)

![image](https://user-images.githubusercontent.com/8171759/31129190-7441aedc-a819-11e7-87e3-a0fc0947f7fa.png)
