### ISSUE TITLE
Alignment: Strip out punctuation

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#2757]
Strip out punctuation when creating words for the word bank.
Think about how to preserve them in the data for export to USFM 3.

## Tasks
[2] Alignment Punctuation: Edit word bank generation to not include punctuation

**Comment by cckozie** [comment]
Apostrophes are not being stripped.
![image](https://user-images.githubusercontent.com/8171759/31129391-0af2b4b6-a81a-11e7-8ce4-9fd70a749232.png)

**Comment by cckozie** [comment]
This may be a feature and not a bug for other languages.
