### ISSUE TITLE
Alignment: Show Greek popup in the dropboxes

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#2758]
Copy the code in Scripture Pane to make the greek words in the Alignment Tool clickable to view the same popup as the greek words in the scripture pane.

## Tasks
[] Expose morph in topWords in alignment data (empty for now)

**Comment by RoyalSix** [comment]
- [ ] [3] Use old popover to make greek words clickable in the alignment tool
- [ ] [2] Expose morph in topWords in alignment data (empty for now)
