### ISSUE TITLE
Refactor verbiage on log in instructions card

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2799]
Change the last sentence to "If you would rather work offline, you many select continue as guest."
![image](https://user-images.githubusercontent.com/8171759/30886296-286da3d6-a2dc-11e7-9906-949d12ddf4b6.png)

**Comment by benjore** [comment]
Please log in with your Door43 account. 

If you do not have a Door43 account, you may create one. 

If you do not want to create an account at this time, you may continue as a guest.

**Comment by cckozie** [comment]
Tested in tC_Test_Verbiage_Misc.sikuli
