### ISSUE TITLE
SPIKE: Some Lexicon entries are not showing up in the pop-up

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#2801]
SPIKE: time-box 2 hours - figure out what it would take to get current lexicon working.

**Comment by cckozie** [comment]
Apparently the data is not missing, but tC is sometimes failing to find it. Opened a Titus project and checked the first few verses for Lexicon data, some was found, some was missing. Open a different Titus project and saw that the missing data results were different than on the first project. Reopened the first project and again the data was missing in different place than it was when I previously opened that project.
Strangely, it appears that most of the Lexicon data is displayed on odd numbered verses, and most of it is not displayed on even numbered verses.
