### ISSUE TITLE
Provide a better description on the Word Alignment tool card

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2806]
![alignment_tool_card](https://user-images.githubusercontent.com/8171759/30970745-8bfafe9e-a42b-11e7-9717-f612c44aec1f.png)

**Comment by pjoakes** [comment]
Here's a first stab at the description:

![image](https://user-images.githubusercontent.com/15133599/31506612-81384044-af3d-11e7-922d-08f8a665f982.png)

**Comment by benjore** [comment]
A tool to align the translation with the original biblical languages in order to show how the translation communicates the meaning represented in the original. This data can be useful in creating other resources such as concordances and interlinear Bibles in the target language.

**Comment by pjoakes** [comment]
Looks good to me.

**Comment by mannycolon** [comment]
@richmahn next time attach the PR to a story, not a task. ;)

**Comment by mannycolon** [comment]
I meant the hours should be added to a tats not a story

**Comment by mannycolon** [comment]
@richmahn

**Comment by richmahn** [comment]
@mannycolon Isn't this the task? This is the only thing I was assigned to.

**Comment by cckozie** [comment]
Tested in tC_Test_Verbiage_Misc.sikuli
