### ISSUE TITLE
Refactor Mac build process to create a Mac installer rather than a zip file

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2807]
Users will not be familiar with this non-standard install process.

**Comment by da1nerd** [comment]
we need to spend some time adding compression to the DMGs.

**Comment by jag3773** [comment]
If we can't compress it properly then possibly have Mac run the Mac builds for `release-*` and git tags.

**Comment by da1nerd** [comment]
Still not making any progress with compressing DMGs on linux.

**Comment by da1nerd** [comment]
@jag3773 @cckozie After some further reflection and seeing once again how slow the travis osx build environments are. I would like to propose we abandon compressed dmg's in automated builds and instead rely on manual osx builds to create the compressed dmg files.

Doing so will still lay the groundwork for potentially automating these compressed dmg's in the future should the tooling improve.

This seems reasonable given we only need the compressed dmg's when actually releasing a new version of the application.

**Comment by da1nerd** [comment]
I've added a PR for the local builds. BTW, I ran a test with travis attempting to run on a macOS image. It waited 1 hour before starting then ran for 23 minutes before being killed. For comparisons sake the linux image runs in about 7 minutes which includes tests and builds for all OS'.
