### ISSUE TITLE
Refactor WIndows build process to create a Windows installer output

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2808]
Currently running the setup exe is nothing like a normal Windows install (no dialogs for user input or information)

**Comment by da1nerd** [comment]
@benjore @cckozie I'm investigating this. I'm not certain Squirrel supports a more standard installation dialog. I think you either use a gif or you can pass control to the application for some things.

I'm still investigating but it seems like we'd have to create an installer window in electron that tells the user what's going on. That's not ideal in my opinion. I'm still researching alternatives.

**Comment by cckozie** [comment]
@neutrinog Is there a reason that we're not using the same process as we did with tS?

**Comment by da1nerd** [comment]
I left things as I found them in tC and just finished setting up the configuration. That was the quickest solution to getting builds running again.
tC is set up to use electron forge, however in tS we used electron-packager.
As far as I know there's nothing preventing us from following the same path as tS except that we'll need to entirely change the build process.

That wouldn't be terrible, but it would be quicker if I can figure out a way to display a decent install window.

**Comment by da1nerd** [comment]
@cckozie I've added a PR https://github.com/unfoldingWord-dev/translationCore/pull/2886 that changes the install gif to the tC logo with the text "Installing translationStudio please wait...".

If that will suffice great! Otherwise I'm 99% certain we'll need to go the route we took with tS.

**Comment by cckozie** [comment]
My thought is that we need to use a true Windows installer.

**Comment by da1nerd** [comment]
@cckozie here's a sample installer. Let me know what you think https://www.dropbox.com/s/ec5jhszpkzsm68b/translationCore-win-x64-0.7.1-beta.97.setup.exe?dl=1

**Comment by cckozie** [comment]
@neutrinog I'm on vacation with only a Mac. I won't be able to test it until the 17th.

**Comment by da1nerd** [comment]
I have the mac dmg's working now as well. Though for now the dmgs are not compressed. This means the files will be 300mb unless zipped. Currently the only way I know to compress dmgs is on a mac, which I'm trying to avoid because travis has super slow build times in the mac queue
