### ISSUE TITLE
Import aligned Hindi ULB - Titus (as a resource)

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#2809]
Hindi will be aligned in tC & exported as USFM3, uploaded to DCS. The need is to pull it in from DCS. 

Hindi alignment data in https://git.door43.org/aniljohn/hi_tit .

Related issue #3188 (English aligned import)

**Comment by PhotoNomad0** [comment]
PR: https://github.com/translationCoreApps/tC_Resources/pull/22

**Comment by cckozie** [comment]
@PhotoNomad0 Is there anything I can test to see if this was actually done?

**Comment by PhotoNomad0** [comment]
Only visible in resource folder. Should see hindi folder.  My understanding is that next sprint has issues to use this.

**Comment by cckozie** [comment]
0.8.1-alpha.17-2e5f7d5
There is no Hindi folder in the resources folder on the file system. I'm not sure whether or not it should be there at this point.

**Comment by PhotoNomad0** [comment]
May need to delete the resources folder and restart the app since we haven’t bumped the version number.  I expect to see an hi folder in resources.  Probably won’t get to check until Monday.

**Comment by PhotoNomad0** [comment]
Nevermind, found that 'hi' is not being being copied

**Comment by cckozie** [comment]
0.8.1-alpha.18-ba1063d
I am now seeing the hi folder in resources. Not apparent anywhere else, including the resources selector in the scripture pane.
