### ISSUE TITLE
Launching app for the first time causes problems because packages-compiled does not exist yet

### ISSUE THREAD

**Issue by EllDoubleYew** [unfoldingWord/translationCore#281]
> As a checker I want to begin loading projects and checking my draft rather than run into errors so that I can finish my check more quickly

We essentially just need to make an empty packages-compiled folder in the application files of tC on the first launch. This should not be too hard to fix but is important because it causes a perpetual error if someone downloads tC for the first time.

**Comment by RoyalSix** [comment]
This should have a high priority @klappy

**Comment by len-wallstrom** [comment]
Re-discovered during testing of tC-v0.1.5.
