### ISSUE TITLE
Remove one off usfm parsing and use usfm.js library

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#2821]
@RoyalSix Can you update this to use the new USFM.js parsing instead of using the internal function to parse the chunks? It may need some extra code to adapt it for your use case but shouldn't require any usfm parsing knowledge in tC.

https://github.com/unfoldingWord-dev/translationCore/blob/ea7ae19a44e8523149b761ea3666ccd5166df13d/src/js/actions/TargetLanguageActions.js#L88

**Comment by mannycolon** [comment]
# Tasks

- [2] Remove USFM parsing function from TargetLanguageActions.
- [3] Made necessary changes to use the usfm.js library in the TargetLanguageActions.

**Comment by cckozie** [comment]
Waiting to see if the QA Fail written up in #2190 should be on this one instead.
