### ISSUE TITLE
App breaks when reopening a project with alignment tool

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2827]
I was working in the project, then closed it by clicking on Project in the menu bar. On the Projects screen I clicked Go to Tools, then clicked Launch on the Word Alignment tool. I had to restart tC to use it again. It does not seem to be project related. This also happens when changing tools.
![image](https://user-images.githubusercontent.com/8171759/31130076-ff0e6daa-a81b-11e7-884d-c044d64079de.png)

**Comment by cckozie** [comment]
Still a problem in beta.88
Same thing happens when changing tools if project is not changed too.

**Comment by mannycolon** [comment]
# Tasks
- [3] Debug why tC breaks when reopening a project with alignment tool
- [5] Fix the bug that causes tC to break when reopening a project with alignment tool
