### ISSUE TITLE
Make it more obvious when the Greek text is not available

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2843]
Neither the UGNT or BHP (do we want both available?) actually display the Greek. It seems like the warning should be in a different font or color or otherwise more distinguishable for scripture text.
![image](https://user-images.githubusercontent.com/8171759/31198049-9718cf6c-a918-11e7-8ea7-605976385a2f.png)

**Comment by benjore** [comment]
Put the quote in `[ ]` and preface it with `Warning:` Make the font italic.

**Comment by richmahn** [comment]
- [x] [2] Refactor warning message when Greek text not available
- [x] [2] Write unit tests to verify text when Greek text not available
