### ISSUE TITLE
Multiple Greek choices are available in the alignment scripture panel

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2845]
This is the way it loads:
![image](https://user-images.githubusercontent.com/8171759/31198683-b95c50b0-a91a-11e7-91fe-48a8944e5309.png)

These are the options:
![screen shot 2017-10-04 at 3 41 55 pm](https://user-images.githubusercontent.com/8171759/31198713-d4b9b65e-a91a-11e7-8d1d-5d63f17667c3.jpg)

With both Greek texts loaded:
![image](https://user-images.githubusercontent.com/8171759/31198745-eb9cf9ee-a91a-11e7-81d6-047d3ce92f8d.png)

**Comment by benjore** [comment]
- [ ] Remove the UGNT, replace with the BHP
