### ISSUE TITLE
Add "(Current project)" next to the project's language in the scripture pane dropdown

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2865]
It's pretty ambiguous what "English" refers to in the list
![screen shot 2017-10-06 at 3 51 51 pm](https://user-images.githubusercontent.com/8171759/31298229-d0405372-aaae-11e7-892b-20af0d84c54b.jpg)

**Comment by benjore** [comment]
The example above should read `English (Current Project)`

**Comment by richmahn** [comment]
- [x] [1] Add "(Current project)" next to the project's language in the scripture pane dropdown
- [x] [1] Write unit tests to verify "(Current project)" is showing
