### ISSUE TITLE
Check mark should not be shown for aligned verses if there are any empty Greek targets

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2868]
Currently the check mark on the verse is only indicative of the word list being empty. It does not take into account whether all of the Greek words have at least one corresponding project word.

**Comment by cckozie** [comment]
Per issue #2257:
- [ ] The checkmark in the side menu appears only when the following 2 criteria are true:
  - [ ] All the English words have been used
  - [ ] All Alignment boxes have at least one Greek & one English word

**Comment by benjore** [comment]
Dup of #3059
