### ISSUE TITLE
% Complete not showing in chapter circle in verse menu

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2873]

**Comment by RoyalSix** [comment]
# Tasks
- [ ] [2] WordAlignment: Send % to menu side bar

**Comment by cckozie** [comment]
@benjore We may not have been explicit enough in our description for this issue. 
1. Should the % complete for a chapter be updated as each GL word is aligned, or after all of the words in the verse have been aligned? Currently it is updating with each word. (First two images)
2. Should the % complete of the chapter be measured as % of words in the chapter aligned or the % of verses aligned? (last image)
![image](https://user-images.githubusercontent.com/8171759/32462748-1eba933c-c300-11e7-826e-1398cfb54370.png)
Essentially no change after aligning the last word in a verse.
![image](https://user-images.githubusercontent.com/8171759/32462729-0d1097e4-c300-11e7-9095-990934efa179.png)

Also, it looks like it may be measuring the % of words aligned vs the total number of words in the chapter since in this sample clearly not 3/4 of the verses have been aligned.
![image](https://user-images.githubusercontent.com/8171759/32462763-2be89b76-c300-11e7-8c48-c4b1e5544ea4.png)

**Comment by cckozie** [comment]
Ben and I were both expecting the % complete to be based on the % of verses complete (check marks as in the other tools) rather than the % of words aligned. Sorry that we didn't make that explicit in the description!

**Comment by RoyalSix** [comment]
## Tasks
- [ ] [2]  WordAlignment: % complete based on the % of verses completed
- [ ] [1] WordAlignment: Update tests
