### ISSUE TITLE
AIignment data is not getting reset when importing and opening a new project

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2881]
.beta 91
I deleted the tranlationCore folder before installing the build.
I imported an Enging Titus project and aligned all of the verses.
I then imported a Hindi Titus project, and when I opened it all of the verses showed the English aligned to the Greek.

**Comment by mannycolon** [comment]
# Tasks
- [3] Debug and pinpoint error with alignment data not getting reset 
- [2] Fix error with alignment data not getting reset
