### ISSUE TITLE
Unable to un-merge Greek words

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2923]
beta.92
Titus 1:11
[unMerge.mov.zip](https://github.com/unfoldingWord-dev/translationCore/files/1381043/unMerge.mov.zip)
Cannot find a way to undo this merge. 
Maybe it will no longer be a problem after we prevent un-merging a middle word.
In rc2:
I see that in rc2 I am able to do the unmerge, but the small box into which I can drop the unmerged word does not become active unless I drag the word to the bottom box.

**Comment by jag3773** [comment]
Will likely be fixed by #2925

**Comment by cckozie** [comment]
0.8.1-alpha.16-2079663
This is no longer an issue since a user can no longer merge the Greek words out of order.
