### ISSUE TITLE
Resize alignment boxes

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2925]
With fixed size boxes and multiple long words as part of an alignment, it can obscure the aligned data.
![image](https://user-images.githubusercontent.com/8171759/32178362-809bbf5a-bd5a-11e7-9609-924b989016d6.png)

**Comment by benjore** [comment]
- [x] Set the minimum/standard width of boxes to half the current size
- [x] Expand the gray box to include the width of longer words or merged words (for Greek or bottom words)
