### ISSUE TITLE
Again able to put GL words in wrong order

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2926]
beta.92 - same in rc2
[fr_tit_text_ulb.tstudio.zip](https://github.com/unfoldingWord-dev/translationCore/files/1381075/fr_tit_text_ulb.tstudio.zip)
1.
![image](https://user-images.githubusercontent.com/8171759/31524739-393e161c-af81-11e7-9d06-e10ac51d6b40.png)
Move the French words into the target in this order: sévèrement, témoignage, reprimende, Ce

2.
![image](https://user-images.githubusercontent.com/8171759/31524885-1b1bcdb8-af82-11e7-83b5-6644e0fdf12a.png)
Move the French words into the target in this order: saine, foi, une

**Comment by benjore** [comment]
Another instance of the same thing. Using this project: https://git.door43.org/aniljohn/hi_tit . Able to determine the order of the bottom words based on the order I align them. 


[Hindi Titus 2_11 bug.zip](https://github.com/unfoldingWord-dev/translationCore/files/1675115/Hindi.Titus.2_11.bug.zip)

**Comment by benjore** [comment]
Is this a data thing or a display thing?

**Comment by cckozie** [comment]
Blocked by #4439
