### ISSUE TITLE
Tokenization Issue With USFM Import

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/translationCore#2928]
Using https://github.com/unfoldingWord-dev/translationCore/releases/tag/untagged-a3be49f15799fd37fc49 .

I used the USFM import feature to import https://git.door43.org/Door43-Catalog/en_ulb/src/master/57-TIT.usfm.

When I opened the project in the aligner the word "God's" is split up as two words, "God", "s". See screenshot:
![screen shot 2017-10-13 at 8 43 29 am](https://user-images.githubusercontent.com/107731/31546786-d9fb9950-aff2-11e7-8412-cbadf94739cb.png)

Problem occurs at least in Titus 1:1 and 1:7.

**Comment by benjore** [comment]
This is a feature, not a bug ;) At least for now and until further feedback from users, this is the tokenization we're gonna work with.
