### ISSUE TITLE
Issues discovered in tC v0.1.5

### ISSUE THREAD

**Issue by len-wallstrom** [unfoldingWord/translationCore#293]
* [ ] no desktop icon created
 * [ ] [tutorial] all of the tutorial bubbles are mis-registered (show up pointing to an item below what is being described)
 * [ ] User signin is refused (despite having a valid door43 userid)
 * [ ] Signin refusal popup is unhelpful ("Login failed")

**Comment by klappy** [comment]
May be a git.door43.org account issue. This is a known issue many users experience where their username/email is a duplicate.
