### ISSUE TITLE
Export to CSV creates a alignment file, but there is no alignment data in it

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2935]
rc2
The file does contain a row for each verse in the project, whereas the other csv files have a single row that shows "No data"

**Comment by benjore** [comment]
- [ ] When exporting as a CSV file, do not give any alignment data (alignment data will only be available in USFM3)

**Comment by cckozie** [comment]
As of v0.9 there is data in the file but it is not meaningful.
![image](https://user-images.githubusercontent.com/8171759/39836190-2c402fde-5398-11e8-83bf-bac462b77796.png)

**Comment by cckozie** [comment]
Still an issue in 2.0.0 (4b3ebee)

**Comment by cckozie** [comment]
Fixed in x2.2.0 (2375ae5)
