### ISSUE TITLE
Alignment Tool: Words returned to the word list due to un-merge of Greek sometimes do not get properly sequenced

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2936]
rc2
I am not sure how I caused this to happen. It occurred after multiple merge/unmerge activities.
![image](https://user-images.githubusercontent.com/8171759/31556942-90b55c94-b00c-11e7-8052-096c27643d6d.png)

**Comment by cckozie** [comment]
I've seen this happen frequently when unmerging Greek words that have words aligned to them. See these screenshots. 
Original alignment:
![merge1](https://user-images.githubusercontent.com/8171759/34572612-6cd237d6-f137-11e7-911b-1eccc40de4e0.PNG)
After merging Greek words:
![merge2](https://user-images.githubusercontent.com/8171759/34572628-76f0dd94-f137-11e7-911e-3214b33e2433.PNG)
After unmerging Greeek words:
![merge3](https://user-images.githubusercontent.com/8171759/34572654-8adc066c-f137-11e7-83a9-96fad7ab3883.PNG)

**Comment by richmahn** [comment]
Fixed in https://github.com/translationCoreApps/wordAlignment/pull/24 which was merged. Moving to In QA.

**Comment by cckozie** [comment]
Looks good.
