### ISSUE TITLE
Extraneous text on User card

### ISSUE THREAD

**Issue by russp41** [unfoldingWord/translationCore#2940]
translationCore 0.8.0-rc.2 in Windows 10

In the instructions on the User card, the following text has invalid HTML that is showing on the card? 

&quote;Continue to Project&quote;

**Comment by mannycolon** [comment]
@neutrinog added some linting settings that are causing this issue. Please don't forget to set this html settings off

**Comment by benjore** [comment]
See #2937

**Comment by da1nerd** [comment]
fyi. @klappy and I talked about this off hand a few weeks ago. Eventually the goal would be to abstract out all the text from the components so things can be localized. That would satisfy the lint test and allow the use of special HTML entities.

For now I don't see a reason why we shouldn't just disable that linting rule mentioned by @mannycolon .
We'd just need to add the following to the `rules` block in `.eslintrc`:

```
"react/no-unescaped-entities": "off"
```

Then revert the escaped entities to their human readable form.

**Comment by mannycolon** [comment]
@neutrinog Thanks for the information.

**Comment by mannycolon** [comment]
# Tasks 
- [ ] [2] set "react/no-unescaped-entities" off
- [ ] [2] Find extranous html text and make it human readable again.
