### ISSUE TITLE
Slow initial conversion/loading of existing projects after upgrade from version 0.7.0 to 0.8.0

### ISSUE THREAD

**Issue by russp41** [unfoldingWord/translationCore#2945]
tC Version 0.8.0-rc.2
Windows 10, i5, 8GB RAM

After upgrading from tC 0.7.0 to tC 0.8.0, it took 2.5 minutes after clicking on the Project button before the projects list was displayed. There were 52 projects in the tC 0.7.0 C:\Users\<user>\translationCore folder that were moved to the C:\Users\<user>\translationCore\projects folder in this process. During the 2.5 minutes, there was no indication that anything was happening. 

After the projects were loaded, clicking on the Project button after subsequent restarts of tC resulted in the projects list being displayed after less than 1 second.

I suggest that a spinner or progress bar be displayed while projects are being loaded/converted on the initial attempt of loading projects after upgrading to 0.8.0.

My translationCore folder contents at:
https://www.dropbox.com/s/cg9bca8zx9pu7ah/translationCore_070b.zip?dl=0

**Comment by benjore** [comment]
[10] Need a SPIKE to spec this out (not just for Windows): 
- a progress bar (with a line underneath saying what needs to be done)
- figure out ways to speed things up 

Overlap with #1990

**Comment by benjore** [comment]
Need Design for the progress bar (2 of 52 projects migrated)

**Comment by benjore** [comment]
![image](https://user-images.githubusercontent.com/13352518/36105287-d86ed8ee-0fd9-11e8-8c2c-8abd561ffc9f.png)

![image](https://user-images.githubusercontent.com/13352518/36105299-de7aa7cc-0fd9-11e8-835d-1e9fc64532ed.png)

- [ ] Add whatever verbiage applicable for what is happening, e.g. "Copying Hindi resources" etc.

**Comment by benjore** [comment]
SPIKE: What would it take to make this happen? 

QUESTION: Should we move the resources to the core app? This would make side-loading more difficult.
