### ISSUE TITLE
Wrong verbiage on alert button after selecting None of the Above on the licensing screen

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2948]
rc2
The project has already been imported so "Cancel Import" makes no sense. I'd suggest just "Cancel" or "OK". @benjore - your thoughts?
![image](https://user-images.githubusercontent.com/8171759/31577510-68d2bd24-b0d5-11e7-872e-4d2611a6b63a.png)

**Comment by benjore** [comment]
"Cancel"
