### ISSUE TITLE
Windows only: Can only view folders when importing local projects

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2954]
rc2
Cannot see files inside of selected folder. When "Select Folder" is clicked, it looks like it imports the top project in the folder.
![image](https://user-images.githubusercontent.com/8171759/31626800-ae2c753a-b270-11e7-963a-0bfac1fa336c.png)

**Comment by RoyalSix** [comment]
- Look at using a npm module for abstracting all file system input calls

**Comment by benjore** [comment]
Need to be able to drill into a folder to select a file. 
Should always select a file.

**Comment by PhotoNomad0** [comment]
### Tasks:
- [ ] [1] Change need to remove folder selection parameter for compatibility with windows and linux.
- [ ] [3] Add Unit tests

**Comment by PhotoNomad0** [comment]
stumbled across the solution in electron documentation:

```
   /**
     * The browserWindow argument allows the dialog to attach itself to a parent
     * window, making it modal. The filters specifies an array of file types that can
     * be displayed or selected when you want to limit the user to a specific type. For
     * example: The extensions array should contain extensions without wildcards or
     * dots (e.g. ‘png’ is good but ‘.png’ and ‘*.png’ are bad). To show all files, use
     * the ‘*’ wildcard (no other wildcard is supported). If a callback is passed, the
     * API call will be asynchronous and the result will be passed via
     * callback(filenames) Note: On Windows and Linux an open dialog can not be both a
     * file selector and a directory selector, so if you set properties to [‘openFile’,
     * ‘openDirectory’] on these platforms, a directory selector will be shown.
     */
    showOpenDialog(browserWindow: BrowserWindow, options: OpenDialogOptions, callback?: (filePaths: string[]) => void): string[]; (edited)
```

----------
And of course both parameters are currently specified, which only works on Mac.

**Comment by PhotoNomad0** [comment]
Being fixed in PR https://github.com/unfoldingWord-dev/translationCore/pull/3131
