### ISSUE TITLE
Windows only: menu bar shows full path of the current project

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2955]
![image](https://user-images.githubusercontent.com/8171759/31626694-5a1d8498-b270-11e7-980d-5494c0d28bb1.png)

**Comment by PhotoNomad0** [comment]
My recollection is that @klappy mentioned that this is likely due to parsing path with \ rather than / on windows, and there is a library function for that.

**Comment by PhotoNomad0** [comment]
### Tasks:
- [ ] [4] Change parsing of Project title to be OS dependent
- [ ] [6] Add Unit tests

**Comment by bspidel** [comment]
change works correctly on my windows 10 machine
