### ISSUE TITLE
When a project is selected that has missing verses, the app returns to the projects screen after running the project validation.

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2957]
rc2
Normally the flow would go from project validation to tool selection. With missing verses it just returns to the project list without explaining why. If the tool is manually selected, the project will open with an empty word list for missing verses, as expected.

**Comment by PhotoNomad0** [comment]
- [ ] [4] - Fix workflow
- [ ] [4] - Write Tests

**Comment by PhotoNomad0** [comment]
@cckozie - Cannot reproduce this anymore in 0.8.1.  Somebody is fixing things before I get to them.

**Comment by cckozie** [comment]
Cannot reproduce in 0.8.0-alpha.11
