### ISSUE TITLE
.Net framework install dialog remains after installation

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2962]
rc2 Win32
.Net framework was installed during the tC installation, but this dialog remains after the installation was completed.
![image](https://user-images.githubusercontent.com/8171759/31667327-23b3295a-b31d-11e7-8277-ea7094d3e34d.png)

**Comment by cckozie** [comment]
I haven't figured out how to retest this yet.

**Comment by da1nerd** [comment]
I still haven't seen this issue occur.

**Comment by cckozie** [comment]
closing this as I can't figure out how to test
