### ISSUE TITLE
User Feedback

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2963]

**Comment by benjore** [comment]
![image](https://user-images.githubusercontent.com/13352518/35886181-ce037bea-0b55-11e8-9be1-59a8bbb2756b.png)

![image](https://user-images.githubusercontent.com/13352518/35886199-d5188812-0b55-11e8-90fe-ba44071c4423.png)

**Comment by da1nerd** [comment]
the ui part of this is done. @benjore how do you want this submitted? Are we sending it as an email to the helpdesk or is there another method of submission?

**Comment by da1nerd** [comment]
@jag3773 I'm marking this as blocked for now until we can find a secure solution for submitting feedback.

I was unable to implement the solution you proposed using GApps due to 
1. an inability to connect or,
2. throttling due to low ip reputation.

**Comment by da1nerd** [comment]
I have this working with creating tickets in the helpdesk, however the api is requiring an email/user id of an authenticated user. I can user help@door43.org for now, but it might be nice to have the ticket tied directly to the user's email address if they provide it. For now I'll just put their email in the message body.

**Comment by da1nerd** [comment]
The UI for this is finished. The only thing blocking this issue now is the inability to create issues with user emails.

If I use a user email I get the following error `{"error":"User not registered. Insufficient access priviledges."}`. However, if I use the helpdesk email the ticket is successfully created.

**Comment by da1nerd** [comment]
I've opened an issue regarding this problem at https://github.com/helpyio/helpy/issues/786

**Comment by da1nerd** [comment]
Note regarding the previous comment. If an email is not already registered with helpy the api requires a name as well so an account can be created.

**Comment by jag3773** [comment]
@neutrinog Can you use the email address as the username too?

**Comment by cckozie** [comment]
@benjore I do not see this dialog represented in this issue. Do we want it as part of feedback? If so, do we want to suggest that they may not want to use their real name?
![image](https://user-images.githubusercontent.com/8171759/37118050-879b9de8-2218-11e8-8cab-425908ea5816.png)

**Comment by benjore** [comment]
@neutrinog @cckozie Can we just use the username they have already signed in with and make the email field required? That would make the above screen unnecessary, correct?

**Comment by cckozie** [comment]
@benjore Do we really want to require an email address? 
Should we just include name as an optional field on the first screen rather than show this one? 
(we don't ask for either in tS)

**Comment by cckozie** [comment]
@neutrinog @jag3773 Where does the feedback show up? How can I view it?

**Comment by jag3773** [comment]
@cckozie It goes to the helpdesk.

@neutrinog As I see it, we still want the initial implementation, if they don't provide an email then the form is sent the way you had it, using the help email as the from address.

If they do provide an email, then use that as the email field and the username field.  No UI changes should be necessary.

**Comment by cckozie** [comment]
1. Remove the second dialog that asks for email address and name
2. Add the alert that warns the user that they are about to send data over the Internet if they have not previously clicked the "do no show again" box
![image](https://user-images.githubusercontent.com/8171759/37164666-92269fb2-22c0-11e8-9d84-b3897ed27f34.png)
3. Detect when there is no Internet connection and display the corresponding alert
![image](https://user-images.githubusercontent.com/8171759/37164812-f719df88-22c0-11e8-841c-5e88a066eb15.png)

**Comment by da1nerd** [comment]
An email address is **always** required. If they choose to use their own email address a user name is also required if their email is not already registered with the helpdesk. Subsequent requests will not need a username.

@cckozie the dialog will only be shown if you try to send feedback using an email not already registered with the helpdesk.

@benjore we cannot use the username of the logged in user because feedback is available when users are logged out as well.

**Comment by cckozie** [comment]
@jag3773 @benjore Please weigh in on Joel's comments above.

**Comment by da1nerd** [comment]
@cckozie @benjore @jag3773 I remembered why I added that name field. Email addresses are not valid user names. If you like I could strip out the email characters so we can still use it as the base for the name.
e.g. `jondoe@gmail.com` would be `jondoe`

**Comment by jag3773** [comment]
Yes, please @neutrinog

**Comment by cckozie** [comment]
1. Feedback is not sent and console error is created:
![image](https://user-images.githubusercontent.com/8171759/37659999-5e699fb8-2c1f-11e8-8d90-93f12136e351.png)
2. Please move the hint text to where the cursor appears when the user clicks in the text field.
![image](https://user-images.githubusercontent.com/8171759/37660383-4e5c7914-2c20-11e8-8124-d561e76a7df2.png)
3. I'm still not seeing the "you're about to use the Internet" warning, although that may be because of 1. above in this comment.

**Comment by da1nerd** [comment]
1. @cckozie I've tested sending feedback on linux and on mac and cannot reproduce the error you are seeing. 

2. Regarding the placeholder text. Do you think we should just remove it entirely since it's the exact same wording as the input label?

3. I'll add an internet confirmation dialog.

**Comment by cckozie** [comment]
@neutrinog 
Looks like 1. is fixed in the latest build.
I'm fine with deleting the hint text.
Are there reasons other than no Internet connection that would cause the feedback would fail?

**Comment by da1nerd** [comment]
@cckozie actually if there is no internet you'll get a nice error dialog that asks you to try again later.
I just tested for that yesterday.

Looking at the error it appears to be more data related, however I've long since had a working submission in place so it's hard to tell what happened.

Could you send me the exact build you used in that test? It might be worth investigating a little bit more just to be sure it's not a random fluke that may come up again.

**Comment by cckozie** [comment]
@neutrinog I'm  not keeping the builds around for more than a few days, and I don't have that one anymore.
Concerning the error dialog, I asked the question because if no Internet connection is the only thing that would cause the error, you should use the existing dialog rather than a new one.
![image](https://user-images.githubusercontent.com/8171759/37789043-e6175024-2dd0-11e8-8f85-cb5a94a2c835.png)

**Comment by da1nerd** [comment]
@cckozie ok I added that alert shown above.
