### ISSUE TITLE
Allowed to open non-Titus projects when in developer mode (Alignment Tool)

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2979]
0.8.0
Start in non-developer mode.
Import a non-Titus project.
Warning is displayed that only Titus projects are supported.
Change into developer mode.
Select the non-Titus project.
Now the project validation stepper is run and the project can be launched with Alignment tool, although the project opens to a blank screen.
Also, if the project is imported when in developer mode the user is able to continue through the project validation stepper and open the project.
![image](https://user-images.githubusercontent.com/8171759/31782485-9fb5b5c8-b4c0-11e7-8c00-a910bf5d3973.png)

**Comment by benjore** [comment]
See also #2884
