### ISSUE TITLE
Fix Local User Sign In Dialog

### ISSUE THREAD

**Issue by RoyalSix** [unfoldingWord/translationCore#2987]
The text on the dialog broke and shows ```quote``` instead of actually showing a ```"``` symbol

**Comment by RoyalSix** [comment]
<img width="754" alt="screen shot 2017-10-19 at 1 48 41 pm" src="https://user-images.githubusercontent.com/16184018/31793602-8dd2803e-b4d4-11e7-8d06-24384aa7b4cf.png">

**Comment by benjore** [comment]
Dup of #2937
