### ISSUE TITLE
Mock Git API Requests For Testing

### ISSUE THREAD

**Issue by RoyalSix** [unfoldingWord/translationCore#2997]
The git api request test fail occasionally due to over use not the actual test failing
use ```mock``` library

**Comment by RoyalSix** [comment]
@benjore

**Comment by benjore** [comment]
Did @neutrinog do this at some point in time?

**Comment by da1nerd** [comment]
I wrote some tests for the GitApi helper class awhile back. See https://github.com/unfoldingWord-dev/translationCore/blob/develop/__tests__/GitApi.test.js.

I'm not sure what your situation is but the concept should be similar.

1. `mock` the module you don't want to actually call.
2. get an instance of the mocks (for later assertions if needed)
3. run tests and make assertions.

If you need to mock a response from GitApi you can create a [manual mock](https://facebook.github.io/jest/docs/en/manual-mocks.html) in `src/js/helpers/__mocks__/GitApi.js`. Creating manual mocks can be simple or complicated depending on your needs.

> HINT: there's another mock `DownloadHelpers.js` in that same location that illustrates some custom setters for configuring responses from the mock object.

**Comment by da1nerd** [comment]
If I just preached to the choir I apologize :)

**Comment by benjore** [comment]
Note: may need to assess if this is still needed before implementing it.
