### ISSUE TITLE
Spike: Research how to Check Project for Issues

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#301]
As a user, I want to know if there is an issue with my project, so that I don't think tC is broken.

**Comment by RoyalSix** [comment]
We already have moderately robust tests on most our main functions, so I am taking this task in the direction of thinking about what it takes to start, load and check a project without running into issues. What are the requirements?
- Requiring the user to have internet to perform actions that access the internet.
Providing feedback if the users tries to do so
This includes making sure all of our online functionality works, and giving corresponding feedback messages for those that don’t
Requiring a manifest defined to our standards
Taking their manifest and finding what we need and making our own, or give the user feedback that there is something wrong with theirs that would be impossible to start a project with.
Requiring all related project files to exist in the filesystem, before trying to access them (Advanced users may mistakenly delete important files)
If this happens we either need to regenerate the files or clear old files and give the user feedback
Requiring the necessary tasks have been completed before a tool load and ensuring it has loaded completely
We should be able to catch if a tool loads successfully, if not give the user feedback to try again.
Requiring the tC app is getting responses from the corresponding tool.
This is 100% reliant on the tool maker, if this does not happen correctly the user should be informed of this, and have the ability to reload the tool, as well as inform the tool maker.
This also may mean having tools go through a series of tests before they are accepted into the tC “core apps”
We need to recognize which requirements are dependent on another, and which ones will not be immediately detectable. 
We need to catch the user from trying to perform “app crashing” tasks.
We need to determine which requirement tests need to happen on a basis of start-up, loading tools, and checking.
We need to be able to give the user options to “fix” their project

**Comment by RoyalSix** [comment]
We already have moderately robust tests on most our main functions, so I am taking this task in the direction of thinking about what it takes to start, load and check a project without running into issues. What are the requirements?
1.	Requiring the user to have internet to perform actions that access the internet.
a.	Providing feedback if the users tries to do so
b.	This includes making sure all of our online functionality works, and giving corresponding feedback messages for those that don’t
2.	Requiring a manifest defined to our standards
a.	Taking their manifest and finding what we need and making our own, or give the user feedback that there is something wrong with theirs that would be impossible to start a project with.
3.	Requiring all related project files to exist in the filesystem, before trying to access them (Advanced users may mistakenly delete important files)
a.	If this happens we need to regenerate the files and give the user feedback
4.	Requiring the necessary tasks have been completed before a tool load and ensuring it has loaded completely
a.	We should be able to catch if a tool loads successfully, if not give the user feedback to try again.
5.	Requiring that the tC app is getting responses from the corresponding tool.
a.	This is 100% reliant on the tool maker, if this does not happen correctly the user should be informed of this, and have the ability to reload the tool, as well as inform the tool maker.
b.	This also may mean having tools go through a series of tests before they are able to be loaded.
6.	We need to recognize which requirements listed above are dependent on another, and which ones will not be immediately detectable. 
7.	We need to catch the user from trying to perform “app crashing” tasks.
8.	We need to determine which requirement tests need to happen on a basis of start-up, loading tools, and checking.
9.	We need to be able to give the user options to either “fix” their project or fix it for them (if possible)
