### ISSUE TITLE
Alignment Tool: Should not be able to un-merge a middle top word

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3019]
If three or more top words (Greek) have been merged, the user is able to un-merge a middle word which causes the Greek words to no longer be in the proper order.

**Comment by benjore** [comment]
- [x] Don't let the user start dragging the middle word (preferably), so that the second word cannot be taken out (as opposed to splitting it into three parts)
- [ ] Add a hover box that has a circle with a slash through it and says, "Cannot un-merge a middle word."

**Comment by PhotoNomad0** [comment]
@neutrinog - where is new the PR for this?
