### ISSUE TITLE
GL Support

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#3027]
# Epics and High-level Stories
See Epics below for links and expand for nested stories.

- Expanding USFM 3 support
- GL Alignment Data from D43 Resource Catalog via USFM 3
- Consuming GL Alignment Data
- Error Handling Verse Changes and Alignment Data
- Exporting Alignment Data
- Alignment Prediction

**Comment by benjore** [comment]
UI strings is outside the scope of this epic

Other things to consider for GL support 
- [x] Selecting a GL
