### ISSUE TITLE
USFM import assigns misleading names to projects

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3037]
[es-419_luk_text_ulb.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/1437975/es-419_luk_text_ulb.usfm.zip)
When this project is imported to tC, it gets the name es_luk. That implies that the language is es (Spanish) rather than es-419 (Latin American Spanish).

See also #2959 and #3038

**Comment by benjore** [comment]
Covered in #2959
