### ISSUE TITLE
Round trip USFM import to Door43 to translationStudio to tstudio import does not work

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3038]
(The portion of this issue that deals with project naming is in issue #2959 and #3037 )
[es-419_luk_text_ulb.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/1438013/es-419_luk_text_ulb.usfm.zip)
1. Import this file into tC
2. Upload it to Door43
3. Import it into tS desktop (note that it gets a blank book name in tS)
4. Export it as a project file from tS (note that it gets an inappropriate name)
5. Importing the tstudio file into tC causes this to happen. (Same result regardless of whether the previously imported USFM project has be removed from tC or not)
![image](https://user-images.githubusercontent.com/8171759/32329898-6100c27c-bfac-11e7-973d-20545fd401c4.png)

**Comment by PhotoNomad0** [comment]
- [ ] [4] Fix problem exporting to ts-desktop
- [ ] [4] Fix problem re-importing to tC
- [ ] [8] Tests

**Comment by PhotoNomad0** [comment]
It looks like ts-desktop is mangling the manifest when migrating package versions.

**Comment by PhotoNomad0** [comment]
Observations about tS import:
- needs manifest fields: package_version, type, resource <= this part seems straight forward (package_version to 7)
- expects source to be in format /chapter/chunk.txt, but tC puts content in chapter.json <= this would be significant rework.

**Comment by PhotoNomad0** [comment]
@benjore -  Do you want me to dig into breaking down the chapter json files into chunks so ts-desktop can edit the text?  I am wondering if this is already part of a future issue.

**Comment by benjore** [comment]
@PhotoNomad0 At this point we are not looking to be able to import tCore projects into tStudio. I would, however, like to be able to export a project from tC as USFM, import it into tStudio, export it back out of tS, and import it back into tCore. Can you check and see if this works?

**Comment by PhotoNomad0** [comment]
@benjore @cckozie - have verified that we can do round trip of exporting USFM from tC, importing that USFM to tS, then exporting USFM from tS, and importing back to tC.  

Note the big problem is that tC will not import over an existing project, so the existing project must be removed along with any WA and tW data.

**Comment by PhotoNomad0** [comment]
@cckozie - Importing tC projects into tS is not supported.

**Comment by cckozie** [comment]
0.8.0-alpha.11
Verified that both of the following scenarios work:
Scenario A
1. Export tC project to USFM
2. Import USFM project into tS
3. Export tS project to Door43
4. Import Door43 project into tC

Scenario B
1. Export tC project to USFM
2. Import USFM project into tS
3. Export tS project to local tstudio file
4. Import tstudio file project into tC
