### ISSUE TITLE
tC should strip leading and trailing spaces on URL entered for import from Door43

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3039]
Neither leading or trailing spaces are obvious on the screen, but they do prevent a successful import. Stripping them should make it much more user friendly, since copying and pasting the URL is a likely process, and picking up those spaces is a common occurrence.

**Comment by RoyalSix** [comment]
## Tasks:
- [x] [1] Handle Leading Spaces On Imported URL
- [x] [1:30] Write Tests For URL Entering For Door43
