### ISSUE TITLE
Importing tstudio project reports the last verse as missing when it is not

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3058]
beta.96
[fr_tit_text_ulb.tstudio.zip](https://github.com/unfoldingWord-dev/translationCore/files/1443614/fr_tit_text_ulb.tstudio.zip)
This occurs both when importing from Door43 and locally.
It reports that 3:15 is missing, but it is in the project.
Maybe it's because 3:15 is the only verse in the chunk??

**Comment by PhotoNomad0** [comment]
Tested with 0.8.1 on windows.  It is only showing error for missing verse at 1:1.
Was able to reproduce on Mac 0.8.1

**Comment by PhotoNomad0** [comment]
- [ ] [4] Understand problem
- [ ] [4] Fix problem
- [ ] [4] Tests for Fix

**Comment by PhotoNomad0** [comment]
It looks like this is fixed in the current develop branch.  Waiting for a build to verify.

**Comment by PhotoNomad0** [comment]
@cckozie - Looks like this is working.  Tested 0.8.1-alpha 11 on Windows.

**Comment by cckozie** [comment]
Works in 0.8.1-alpha.11
