### ISSUE TITLE
Cannot import local tstudio projects on Windows

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3061]
beta.96
I get this message on all local tstudio projects (yes, they do import on Mac). No errors in the console.
![image](https://user-images.githubusercontent.com/8171759/32448443-8278bca4-c2d4-11e7-8f1d-1cc169901cbd.png)

**Comment by PhotoNomad0** [comment]
I was able to import a tstudio file on windows using 0.8.1.  Cannot reproduce.

**Comment by cckozie** [comment]
Cannot reproduce in 0.8.0-alpha.11
