### ISSUE TITLE
Project opens to blank screen in both tW and WA

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3062]
beta.96
https://git.door43.org/TC_SAVE/es_luk
Opens correctly on Mac. Could this be related to #2967?
![image](https://user-images.githubusercontent.com/8171759/32449525-660e85fa-c2d7-11e7-896b-ab62b94bbc16.png)

**Comment by PhotoNomad0** [comment]
### Tasks:
- [ ] [10] Fix blank screen on Windows.
- [ ] [10] Add Unit tests

**Comment by PhotoNomad0** [comment]
@cckozie - two notes here:
1. You are running in developer mode, because app only supports Titus.
2. I see the same import problem on Mac - empty screen in word alignment tool and big crash log in console.

**Comment by PhotoNomad0** [comment]
@cckozie @benjore - Recommend closing this issue.  This is about Luke which we don't currently support (verified with @mannycolon).  Verified that the app works properly when developer mode is OFF: it warns user that the tools only work for Titus.

**Comment by cckozie** [comment]
@PhotoNomad0 It opens fine in tW on my Mac with no 'big crash' log in the console. We technically do not support non-Titus, but it should work in tW.

**Comment by PhotoNomad0** [comment]
@cckozie Hmm...I do see a crash log and empty screen on Mac the first time I tried to open.  After that it opened fine.

Also double-checked on Windows and seeing the same behavior (failed first time, success the second time).  Now I have something to check.

**Comment by PhotoNomad0** [comment]
@cckozie - I now cannot reproduce the crash on either windows or Mac using the latest release.

**Comment by PhotoNomad0** [comment]
Added blocked, because I cannot reproduce anymore.  Library fix?
