### ISSUE TITLE
On highres monitor, Import button not shown on screen.

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#3085]
When I am running the app full screen on a highres monitor (1080 pixels vertically), and then do ‘Import online project’.  If there are more search results than can fit on screen, the Import button is pushed off screen and it won’t let me scroll down to see the import button.  But if I resize the height of the app to make it shorter (for example drag the bottom up), the import button appears.

I would expect the import button to stay visible regardless of length of list or size of app window.

![screen shot 2017-11-07 at 10 33 32 am](https://user-images.githubusercontent.com/14238574/32501882-3cef9026-c3a7-11e7-8619-d298b8026962.png)

**Comment by richmahn** [comment]
- [x] [3] Fix hi-res Door43 import button issue
- [x] [3] Write test for hi-res issue to confirm buttons are in view

**Comment by cckozie** [comment]
I'm not seeing any difference.
![image](https://user-images.githubusercontent.com/8171759/33894847-9bd230d8-df24-11e7-8791-8d1d2a951cc6.png)

**Comment by richmahn** [comment]
@PhotoNomad0 It it work ok for you? Still works fine for me.

**Comment by cckozie** [comment]
This is also sensitive to how high the tC window is. The shorter the window, the more likelihood that the display will be correct. These screenshots were taken at 1080p.
![scrn1](https://user-images.githubusercontent.com/8171759/33951582-f72696b0-dff4-11e7-8b41-d6000f0da585.png)
![scrn2](https://user-images.githubusercontent.com/8171759/33951589-fe391522-dff4-11e7-9630-15013b5e75c0.png)
![scrn3](https://user-images.githubusercontent.com/8171759/33951599-058c0942-dff5-11e7-89fe-782892c11120.png)

**Comment by cckozie** [comment]
I'm going to pass this for now even though there are still some cases where it doesn't work properly.
