### ISSUE TITLE
Update the Greek text

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#3104]
Grab the latest books from https://git.door43.org/Door43/bhp after 11/10.

**Comment by jag3773** [comment]
Text available at https://git.door43.org/Door43/BHP .

**Comment by klappy** [comment]
@PhotoNomad0: Here's what remains to be done...
- Download the above books
- Write tests/code to convert those books and put them in the `resources/grc/bhp/v0/[bookId]` path.
- Update the chapter/verse index to cover all books now included, New Testament, `bhp/v0/index.json`
- Verify with @jag3773 that the version remains `v0`.

**Comment by PhotoNomad0** [comment]
@klappy - What are the counts in the index.json file.  Are these supposed to be the number of entries for each verse in the chapter json files?  Is this file even used anymore?  The bhp is showing up for other books now even though I have not yet updated the index.json.

**Comment by klappy** [comment]
While it may not be fully implemented the plan is to use it for defining the expected number of verses in a chapter, as well as how many chapters. There are a few places it is used but not everywhere it should be. It also assumes no verses are skipped so it's more like what is the verse number of the last verse.

**Comment by PhotoNomad0** [comment]
It does seem to be a BHP word count, for example 17 words in titus 1:1:

```
  "tit": {
    "1": {
      "1": 17,
      "2": 12,
...
```

**Comment by klappy** [comment]
That must be a mistake in the function that generated it originally. I think it recursively scanned the object for object count. Looks like it went to far!

**Comment by cckozie** [comment]
0.8.1-alpha.12-8a1618d
It appears that all BHP files in tC are using the label "Strongs", while the BHP files at https://git.door43.org/Door43/BHP are using the label "Strong" (no ending s). Jesse says that it will be fixed by reimporting after issue #3204 is implemented.
I am passing this now even though that problem does exist, and it prevents me from reasonably being able to look for other problems.
