### ISSUE TITLE
Refactor Project Import

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#3108]
Diagram at https://docs.google.com/drawings/d/1yd4Ww3vklV_bsE-xE0XnfZQc5geWQhTooAFvNRa2n4s/

Add robust tests!  Possibly review all the closed issues relating to imports to get a list of items that should be tested, https://github.com/unfoldingWord-dev/translationCore/issues?utf8=%E2%9C%93&q=is%3Aissue%20import%20is%3Aclosed%20-label%3ATask%20 .

**Comment by RoyalSix** [comment]
## Notes:
ProjectLoadingActions.js should handle project selection / loading.
ProjectDataLoadingActions.js should handle loading the tool data.

## Files Architecture / Functionality:
#### OnlineImportActions: 
This should put the project details into the store.
Input: url from a user action.
Output: none. returns when done.
- ImportOnlineHelpers:
This should handle all the actual fs calls and any logic unrelated to the dispatcher (redux).
This should take a url from door43 and clone the repo to the FS import folder
This may contain some basic error handling for using the gogs and git API.
- LocalImportActions
- usfmProjectConversionHelpers
- tStCProjectConversionHelpers

ProjectMigrationActions
- ProjectMigrationHelpers

ProjectValidationActions
- ProjectValidationHelpers


MyProjectsActions
- MyProjectsHelpers

**Comment by klappy** [comment]
Attempting to keep the clarity of the diagram, the folder/file structure should mimic the diagram. 

### Actions
Actions should be very light-weight with little to no logic outside of getting the state to call the helpers to set the state. Dispatching other actions is expected.

### Helpers
Helpers should hold all the logic and do not require getting or setting state. They should handle all web/fs calls.

### Functions
All functions should be built with TDD, in that tests are written first with small modular goals in mind. Each function should be fairly small and not a lot of nested logic. Our previous approach had lots of conditional logic and nesting that complicated both testing and maintainability. Keeping them short and factoring out nested logic into new functions keeps the code maintainable and testable.

### Skeleton File/Folder Structure for refactor
Some helpers need to be organized by their type such as conversions, migrations, and validations to improve maintainability and make them easier to find.
Root path prepended to all paths below: `./src/js/`

- Local Import Workflow (wrapper)
  - `actions/LocalImportWorkflowActions.js`
  - `helpers/LocalImportWorkflowHelpers.js`
- Online Import Workflow (wrapper)
  - `actions/OnlineImportWorkflowActions.js`
  - `helpers/OnlineImportWorkflowHelpers.js`
- Project File Conversions
  - `actions/FileConversionActions.js`
  - `helpers/FileConversions/`
    - `./usfmFileConversionHelpers.js`
    - `./translationStudioFileConversionHelpers.js`
    - `./translationCoreFileConversionHelpers.js`
    - `./zipFileConversionHelpers.js` (shared tS and tC)
- Project Moving
  - `actions/ProjectImportFilesystemActions.js`
  - `helpers/ProjectImportFilesystemHelpers.js`
- Project Migrations
  - `actions/ProjectMigrationActions.js`
  - `helpers/ProjectMigrations/`
    - `./oneTypeOfMigrationHelpers.js`
    - `./secondTypeOfMigrationHelpers.js`
    - `./thirdTypeOfMigrationHelpers.js`
- Project Validations
  - `actions/ProjectValidationActions.js`
  - `helpers/ProjectValidations/`
    - `./mergeConflictHelpers.js`
    - `./missingVersesHelpers.js`
    - `./duplicateVersesHelpers.js`
    - `./manifestValidationHelpers.js`

- My Projects
  - `actions/MyProjectsActions.js`
  - `helpers/MyProjectsHelpers.js`

- Project Loading
  - `actions/ProjectLoadingActions.js`
  - `helpers/ProjectLoadingHelpers.js`

**Comment by cckozie** [comment]
Some child stories are still in progress

**Comment by cckozie** [comment]
All of the child stories are complete so closing this now.
