### ISSUE TITLE
[0] SPIKE Refactor Import: Sync up as Team to discuss approach 

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#3117]

**Comment by RoyalSix** [comment]
## Notes:
ProjectLoadingActions.js should handle project selection / loading.
ProjectDataLoadingActions.js should handle loading the tool data.

## Files Architecture / Functionality:
#### OnlineImportActions: 
This should put the project details into the store.
Input: url from a user action.
Output: none. returns when done.
- ImportOnlineHelpers:
This should handle all the actual fs calls and any logic unrelated to the dispatcher (redux).
This should take a url from door43 and clone the repo to the FS import folder
This may contain some basic error handling for using the gogs and git API.
LocalImportActions
- usfmProjectConversionHelpers
- tStCProjectConversionHelpers

ProjectMigrationActions
- ProjectMigrationHelpers

ProjectValidationActions
- ProjectValidationHelpers
