### ISSUE TITLE
The user should be warned if there is no Internet connection when searching for Door43 projects.

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3151]
Currently tC just returns the "No project matching your search criteria was found." message. 
Instead, we should display the "Unable to connect to the server. Please check your Internet connection." alert.

**Comment by mannycolon** [comment]
# Tasks
- [ ] [2] Research implementation for no internet connection when searching for Door43 projects
- [ ] [2] Implement alert when no internet connection when searching for Door43 projects

**Comment by cckozie** [comment]
I'm not seeing any change in 0.8.1-alpha.13-242084e. The Search alert comes up momentarily and then I get the No matching projects... message on the search page.

**Comment by cckozie** [comment]
Same problem in 0.8.1-alpha.13-7eb4883

**Comment by cckozie** [comment]
Fixed in  0.8.1-alpha.13-18b49c2
