### ISSUE TITLE
The timeout is too long when the Internet connection is lost during download of Door43 project

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3152]
The current timeout appears to be about 9 minutes. 2 minutes is probably more appropriate.

**Comment by benjore** [comment]
@cckozie What happens at 9 minutes?

**Comment by cckozie** [comment]
@benjore This message is displayed:
![inet](https://user-images.githubusercontent.com/8171759/33385230-f4062acc-d4dc-11e7-8cf6-7c669b902070.png)

**Comment by richmahn** [comment]
- [ ] [4] Shorten timeout for when Internet connection is lost during Door43 project download
- [ ] [3] Write test to verify timeout for Door43 project download

**Comment by richmahn** [comment]
@cckozie When I start a download and kill my internet connection, it times out in 15 seconds after killing it. How did you go about testing this? How to reproduce?

**Comment by richmahn** [comment]
@cckozie Possibly how git behaves on each platform? I am on Windows. What OS did you see this on, and can you also try it on Windows?

**Comment by cckozie** [comment]
@richmahn I was testing it on Mac the same as you mentioned above. My Windows machine is currently broken. I'll let you know when I get it running again and am able to test it there.

**Comment by cckozie** [comment]
@richmahn On my Windows machine it took about 11 minutes to time out after killing the Internet connection.

**Comment by richmahn** [comment]
@cckozie How and exactly when do you kill your connection? I assume just turn off wifi after the download starts?

**Comment by cckozie** [comment]
@richmahn I select the file for download, click the Import button, and then ASAP either turn wifi off or put it in airplane mode (same result with either).

**Comment by cckozie** [comment]
I'm going to close this issue since it seems like too much work to get what was asked for. Issue #3154 will help resolve the problem so at least the user won't have to force close tC.
