### ISSUE TITLE
No error is displayed when attempting to Upload to Door43 when there is no network connection 

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3153]
The "Unable to connect to the server. Please check your Internet connection." alert should be displayed.

**Comment by mannycolon** [comment]
# Tasks
- [ ] [4] Research how to add an alert when attempting to Upload to Door43 when there is no network connection.
- [ ] [3] Add alert when attempting to Upload to Door43 when there is no network connection.

**Comment by cckozie** [comment]
Still not working in 0.8.1-alpha.13-7eb4883
