### ISSUE TITLE
Expanding USFM 3 support

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#3184]
## Notes
The following changes are needed as there are many dependencies for these changes. Maintaining punctuation and non-word markers such as footnotes via Verse Objects allows us not to lose any data while importing/exporting USFM 3. This ensures all data in the original USFM 2 files are able to be preserved and not lost. 

USFM imports to tC have data/markers that occurs outside of a verse and are not currently preserved in any way. We don't currently have a use case for them inside of tC other than upon export. In order to preserve them upon export, we need to send the original imported USFM file to the JSON to USFM converter to preserve everything not in a verse, as the verse should already preserve what was imported. We do not need to preserve the data for anything other than while exporting at this point.

There are no known blocking dependencies to start working on this.

- USFM.js: Maintain punctuation and non-word markers such as footnotes via Verse Objects
  - USFM.js: Preserve punctuation and non-word markers in USFM parsing via Verse Objects
  - USFM.js: Support punctuation and non-word markers in USFM generation via Verse Objects
- USFM.js: Preserve data/markers outside of verses from an imported USFM file when exporting

## Verse Object Proposal
https://github.com/unfoldingWord-dev/translationCore/issues/3093

Reference for data structure: https://github.com/unfoldingWord-dev/translationCore/wiki/Alignment-Data-Structure:-USFM-3

**Comment by jag3773** [comment]
@klappy and @PhotoNomad0 It seems like it would be a valuable use of time to write a test that grabs all the translations available in https://api.door43.org/v3/catalog.json and runs the conversion on them to make sure there aren't any other outliers in our published dataset.
