### ISSUE TITLE
GL Alignment Data Import as Target Language Project from USFM 3 File

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#3186]
- GL Alignment Data Import as Target Language Project from USFM 3 File
  - USFM.js: Improved USFM 3 to Verse Objects
  - tC Helpers: Split Verse Objects to Target Verse String and Alignment Data

Alignment data for target language project import will be handled in: #3559

**Comment by klappy** [comment]
## Tasks
[8] USFM3 Import: Tests for Split Verse Objects to Target Verse and Alignment Data
[8] USFM3 Import: Helper to Split Verse Objects to Target Verse and Alignment Data
[8] USFM3 Import: Changes to USFM.js library as needed, release and update

**Comment by klappy** [comment]
## New Tasks
[4] Fix Occurrence(s) bug
[6] Use VerseObjects instead of WordObjects
[12] Write Migrations for WordAlignment Data from wordObjects to verseObjects
[6] Update USFM import to support VerseObjects from USFM.js
[6] Update/Fix broken USFM tests

**Comment by cckozie** [comment]
Need USFM3 file to test.

**Comment by PhotoNomad0** [comment]
#### Known issues:
~https://github.com/unfoldingWord-dev/translationCore/issues/3757 - Unmerging Greek words changes word order~
https://github.com/unfoldingWord-dev/translationCore/issues/3758 - USFM import does not preserve all header info

**Comment by cckozie** [comment]
I'm not sure that it's the import that's broken, but the exported file looks like it has all of the data and no alignments show up in the imported project. (The exported project was 100% aligned)

**Comment by klappy** [comment]
@cckozie: The current use case is to import via the tC_resources for the GL languages. We discussed in a standup last week with @benjore and @jag3773 to not fix the use case of importing the exported file in the application just yet. That will be handled in a separate story. We brought that up so that we could pass these stories but this particular one does pose a problem for QA testing.

@benjore and @jag3773 can you weigh in on how to proceed?

**Comment by benjore** [comment]
I need to be able to import a USFM3 file and use it as a work-in-progress project in the word alignment tool.

**Comment by PhotoNomad0** [comment]
#### Tasks:
- [x] [4] extract and save alignments on USFM import (generateTargetLanguageBibleFromUsfm)
- [x] [4] update unit tests
- [x] [4] PR reviews
