### ISSUE TITLE
USFM.js: Maintain punctuation and non-word markers such as footnotes via Verse Objects

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#3190]
- USFM.js: Maintain punctuation and non-word markers such as footnotes via Verse Objects
  - USFM.js: Preserve punctuation and non-word markers in USFM parsing via Verse Objects
  - USFM.js: Support punctuation and non-word markers in USFM generation via Verse Objects

**Comment by PhotoNomad0** [comment]
### Tasks (using TDD):

- [ ] [8] Write and resolve test cases for USFM parsing to verse objects
- [ ] [8] Write and resolve test cases for verse objects conversion to USFM

**Comment by cckozie** [comment]
Holding until #3424 and #3485 are fixed.

**Comment by cckozie** [comment]
The "maintained" elements do no in the output file generated by the USFM Export option.

**Comment by cckozie** [comment]
0.8.1-alpha.13-6dfca4e
Footnotes do not appear in USFM output.
Need #3209 to pass before I can really test.

**Comment by cckozie** [comment]
0.8.1-alpha.15-633b904
https://git.door43.org/tc06/en_eph_text_reg
Footnotes still do not appear in exported USFM file.
[en_eph_reg.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/1707268/en_eph_reg.usfm.zip)

**Comment by cckozie** [comment]
translationCore 0.8.1-alpha.15
Footnotes still do not appear in the exported usfm file if the project came from Doo43 or from a tstudio file. If the project came from a USFM file, then footnotes do appear in the exported USFM file.
I assume the same is true for other "unused" USFM markers.
/p and /s are not preserved when exporting to USFM3 (see #3808 )

**Comment by klappy** [comment]
The problem came from requesting not showing certain markers, whoever picked up that story got a little aggressive and filtered them out during the import instead of on display in the scripture pane. @PhotoNomad0 addressed that and added the filtering on scripture pane and removed it from USFM import.

The problem still exists on project imports as they have an import process that likely does the same thing but during their import since they have to be treated differently in the beginning. (see #3780 )
