### ISSUE TITLE
Console error and no response to Close button in tW project

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3198]
alpha.1
[fr_tit_text_ulb.zip](https://github.com/unfoldingWord-dev/translationCore/files/1473358/fr_tit_text_ulb.zip)

Load this project with tW, then click Cancel, then Save & Continue, then Skip until it gets to the group "chosen one, chosen ones...". At that point the console error is displayed and the Close button on the Attention dialog does not work.
![image](https://user-images.githubusercontent.com/8171759/32817715-e9963950-c984-11e7-8b68-a7a63a829477.png)

**Comment by richmahn** [comment]
- [ ] [4] Fix action button for closing tW project
- [ ] [3] Write test for closing tW project

**Comment by RoyalSix** [comment]
Not sure what is going on but I am getting this error after doing the above steps.
It happens on the press ```Save & Continue``` step and the app gets locked up.

**Comment by cckozie** [comment]
This is not fixed in 0.8.1-alpha.13-7eb4883

**Comment by cckozie** [comment]
Have to wait for the new develop branch since tW is not in current build.
