### ISSUE TITLE
Refactor Build Process to Build off of Branches

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/translationCore#3203]
Builds should be automatically triggered for these branches:

* [x] `develop`
* [x] `release-*`

Builds that are created of release branches should include the version string indicated in the release branch.  For example, a release branch named `release-v0.9.0` should have the version code `v0.9.0` encoded into the build.  The main reason for this is so that we can use the last build from the release branch as what we publish for the release.

* [ ] Last component of this is to meet with the team to explain the build process.

**Comment by da1nerd** [comment]
would you like me to add some validation to the version number and branch name? 
e.g. if the version in the package.json does not match the version in the branch name then I could throw an error stating as such. That would help to enforce updating the version number and naming branches correctly.

**Comment by da1nerd** [comment]
@jag3773 we might need s3 for this. Surge works great until we run into file size limits. Right now that uncompressed dmg is causing us issues.

**Comment by da1nerd** [comment]
we can use this app to list files in a bucket https://github.com/unfoldingWord-dev/s3_list-zip

**Comment by da1nerd** [comment]
for now we will stick with using surge. We will upload individual builds to their own sub domains. e.g. `linux64.develop.tc.unfoldingword.surge.sh`
 In this way we will have 12 total domains storing builds with a single additional domain just to hold the build notes html.

**Comment by da1nerd** [comment]
@jag3773  This has been completed
