### ISSUE TITLE
Encode tW Links in BHP

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/translationCore#3204]
We want to be able to tie our translation words to the original language. (Greek and Hebrew).

We need the generated USFM3 to have tW encoded in it like `\w αβρααμ|lemma="Ἀβραάμ" strong="G00110" x-morph="Gr,N,,,,,,GMS,I" x-tw="rc://*/tw/dict/bible/other/abraham"\w*.`

The mapping may be many-to-one or one-to-many.

We are mapping the source languages with tW based on the strongs numbers and the list of occurrences. 
Start with the list of occurrences and try to find the strongs number in those locations and insert the word at that location.. 

> Note: we don't need to worry about the old testament right now.

## This is a one time process. Once we've generated this mapping we won't even need list of occurrences.

**Comment by neutrinog** [comment]
@jag3773 will a strongs number only appear under a single tW? Or might a strongs number appear under multiple tWs?

**Comment by da1nerd** [comment]
@jag3773 I have this mapping tool working.

### config.yaml bugs
I'm discovering the config.yaml is missing lots of occurrences. For example in James 1:1 I believe the first word `\w Ἰάκωβος|lemma="Ἰάκωβος" strong="G23850" x-morph="Gr,N,,,,,NMS,"\w*,` should be mapped to `jamessonofzebedee`.
However, the config.yaml does not include James 1:1 in the list of occurrences even though the tW word has a matching Strong's number.

In addition, there are a large number of invalid words within the config.yaml.

### word bugs

Some of the words are missing a **Word Data** section so I'm not finding any Strong's for those words.

---

Here's a list of errors I'm getting not including the un-matched instances [errors.log](https://github.com/unfoldingWord-dev/translationCore/files/1490446/errors.log)

And here is a sample mapping of James [60-JAS.usfm.txt](https://github.com/unfoldingWord-dev/translationCore/files/1490459/60-JAS.usfm.txt)

**Comment by da1nerd** [comment]
* [x] search by occurrences and inject the link
* [x] perform a general search by strong's (but consult the false positives) and log the misses. book,chapter,verse,term,text

**Comment by da1nerd** [comment]
If a word cannot be found then just ignore it.

Creates issues for each of the files that is missing the strongs numbers here https://git.door43.org/Door43/en_tw/issues .

**Comment by da1nerd** [comment]
@jag3773 what should I do if there are multiple word matches for a single strong's?

For example `\w ἐν|lemma="ἐν" strong="G17220" x-morph="Gr,P,,,,,D,,,"\w*` matches both `other/onhigh` and `other/conceive`,

**Comment by da1nerd** [comment]
Fyi, there are over 15,000 unique passage occurrences of multiple words, but only 487 unique strong's numbers with multiple words.

The most frequently used strong's and their words are:
* `G17220` (2703 occurrences): `other/onhigh`; `other/conceive`
* `G30040` (2185 occurrences):` kt/call`; `other/report`
* `G15190` (1674 occurrences): `kt/inchrist`; `other/partial`
* `G41600` (553 occurrences): `other/creation`; `other/bear`; `other/commit`; `other/imitate`

**Comment by cckozie** [comment]
Note self: Ensure that the problem of "Strongs" vs "Strong" in issue #3104 is also fixed when this one is implemented.

**Comment by jag3773** [comment]
@neutrinog Let's discuss these in our meeting today.

**Comment by da1nerd** [comment]
There is an issue in the current encoding process. See https://github.com/unfoldingWord-dev/door43.org/issues/806

**Comment by da1nerd** [comment]
I've fixed the missing links in usfm milestones. I cannot fix things like the following:

> Some of the phrases aren't being recognized, like "God the Father" here https://git.door43.org/Door43/UGNT/src/tw_occurrences/57-TIT.usfm#L79 .  Lines 79-80 should be tagged with a milestone that refernences godthefather.md tW

because the tW word is missing a strong number. If we can update tW with the correct strong number the script will pick it up.

**Comment by jag3773** [comment]
@benjore Titus is available at https://git.door43.org/Door43/UGNT/src/master/57-TIT.usfm .
