### ISSUE TITLE
Truncate fields on the project card if they wrap into more than two lines

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3222]
In this example the language field should be truncated after the language name. When the user hovers over the language name, the full name/code data should be displayed in a popup.
![project card](https://user-images.githubusercontent.com/8171759/32953643-736e3d7e-cb76-11e7-978e-731a4892f34a.png)

Unit test is part of ProjectCard.test.js

**Comment by benjore** [comment]
- [ ] bring the language tag to the front

**Comment by cckozie** [comment]
This was working but is broken again in 0.8.1-alpha.13-242084e
![image](https://user-images.githubusercontent.com/8171759/34130987-85d6d3de-e40f-11e7-9354-5a13f018f568.png)

**Comment by PhotoNomad0** [comment]
@cckozie - it looks like you just lucked upon a window of combined langID and langName lengths that fails to truncate (between 20 and 23 characters).

**Comment by cckozie** [comment]
Tooltip with full text is not readable on top project.
![image](https://user-images.githubusercontent.com/8171759/35410620-a6d63234-01db-11e8-86fb-89409898fbd3.png)
