### ISSUE TITLE
Standardize on vertical alignment of languages icon

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3225]
It is raised above the text on the Door43 search screen, and below the text on the project cards.
![image](https://user-images.githubusercontent.com/8171759/32956642-f08b85fc-cb7e-11e7-9f21-bebdc93e345b.png)

![image](https://user-images.githubusercontent.com/8171759/32956653-fb484494-cb7e-11e7-8361-dd879aca0afb.png)

**Comment by benjore** [comment]
The top image is correct with the `A` on the baseline.

**Comment by benjore** [comment]
Copy the CSS settings from the one and copy it to the other. (Suggestion)

**Comment by cckozie** [comment]
0.10.0-72cec56
The vertical alignment and size of the icon is correct when the language name is truncated.
![image](https://user-images.githubusercontent.com/8171759/39761488-dae1587a-529d-11e8-80e5-d7ddc26b3f83.png)

**Comment by RoyalSix** [comment]
Are we not using an ellipsis for the online import project language name as well? @cckozie @benjore

**Comment by cckozie** [comment]
@RoyalSix Yes, we wrap the details to 2 lines and truncate after that. What is shown in the screenshots is correct for wrapping and ellipses.

**Comment by cckozie** [comment]
0.10.0-40cc7f1 
![image](https://user-images.githubusercontent.com/8171759/40131333-487a8480-58ff-11e8-8d7f-1cf81095647c.png)

**Comment by RoyalSix** [comment]
<img width="542" alt="screen shot 2018-05-17 at 7 56 51 am" src="https://user-images.githubusercontent.com/16184018/40185634-e5b2fca2-59a7-11e8-9150-80cf6eb6eb67.png">
Is this the desired behavior?

**Comment by cckozie** [comment]
@RoyalSix 
There is still a discrepancy in the vertical alignment depending on how many lines get wrapped. Is this as close as we can get to consistency, or was this just considered "good enough"?
![image](https://user-images.githubusercontent.com/8171759/40328815-4d482924-5d0d-11e8-83fe-28f33e9273ad.png)
