### ISSUE TITLE
Windows only: tC icon is missing on the project loading dialog

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3226]
0.8.1-alpha.11
![image](https://user-images.githubusercontent.com/8171759/32956785-7140c87e-cb7f-11e7-8aca-89e9b1207e42.png)

**Comment by da1nerd** [comment]
@cckozie this appears to work correctly in build 0.8.1-alpha.12.

**Comment by cckozie** [comment]
@neutrinog I agree and will close the issue.
