### ISSUE TITLE
Project Import: Local File Selection

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/translationCore#3229]
Verify *file* that is selected is a `.zip`, `.usfm`, or `.tstudio`.

**Comment by mannycolon** [comment]
# Tasks

- [ ] [4] write file selection action in localImportActions.js
- [ ] [2] Write unit tests for selectProjectAndMoveToImports action.

**Comment by cckozie** [comment]
@mannycolon Why do we have .tcore as one of the allowed file extensions for imports?

**Comment by cckozie** [comment]
I'm still curious ^^^ but will pass it anyway.
.zip is not supported but I don't know why it was added to this issue since we don't support .zips.
