### ISSUE TITLE
Project Import: Verify manifest exists

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/translationCore#3236]
Error if not a Scripture project

**Comment by richmahn** [comment]
- [ ] [2] Import - Verify manifest exists - Write code
- [ ] [2] Import - Verify manifest exists - Write tests

**Comment by cckozie** [comment]
0.8.1-alpha.13-4ef6c94 
The user should get a more friendly/helpful message when a manifest is not found.
Currently displays this:
![image](https://user-images.githubusercontent.com/8171759/34063387-5df0ccf8-e1b7-11e7-90d1-b56a0eb42a6b.png)
Change the verbiage to: "Unable to find the manifest for project [url or path/file of project]. It will not be loaded."
(don't show the brackets)

**Comment by RoyalSix** [comment]
I guess no one saw my question in #3384 :(

**Comment by cckozie** [comment]
The error message is now correct, although an error is thrown in the console. Passing this and writing up a new issue related to the console error.(#3648)
