### ISSUE TITLE
Project Import: Missing verses check

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/translationCore#3240]

**Comment by cckozie** [comment]
[es-419_luk_text_ulb.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/1437975/es-419_luk_text_ulb.usfm.zip)
When importing this project (maybe all USFM projects with missing verses), the Continue button is disabled on the Missing Verses page.
![image](https://user-images.githubusercontent.com/8171759/34005669-486202ae-e0c1-11e7-8e4b-a85f6d7f0324.png)

**Comment by PhotoNomad0** [comment]
This should be fixed in https://github.com/unfoldingWord-dev/translationCore/pull/3394.
