### ISSUE TITLE
Project Import: Move a project from imports folder to projects folder

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/translationCore#3241]
* [ ] Check to see if it overwrites an existing project

See https://github.com/unfoldingWord-dev/translationCore/issues/3030

**Comment by RoyalSix** [comment]
## Notes:
 - Consider hiding the actual projects folder that tC is using, or else users may still try to drop their folders in there
   - Or even using a special way to flag projects that have been through the verification process.

**Comment by mannycolon** [comment]
# Tasks
- [ ] [4] Write action/helper to move a project from the `imports` folder to the `projects` folder if that project name isn't found in the `projects` folder
