### ISSUE TITLE
Integration Tests for Core API

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#325]

**Comment by ihoegen** [comment]
* TODO:
  * 1. Event listener testing. Includes register, remove, and emit.
  * 2. CheckStore testing. Includes put and get.
  * 3. IO testing. Input and Ouput JSON, along with text. No clue how to test.
  * 4. CheckStore logging. No clue how to test.
  * 5. Alert creation and clearing. No clue how to test.
  * 6. Initialize CheckStore.
  * 7. Get logged in user. No clue how to log in an user.
  * 8. Update manifest.
  * 9. Save project.
  * 10. Settings API.
  * After this stuff, CoreStore and CoreActions can be tested, also with electron-mocha
  
* Also TODO, stuff inside constructor:
  * 1. React
  * 2. ReactBootstrap
  * 3. CheckModule
  * 4. Modules
  * 5. GitApi
  * 6. PopoverApi
  * 7. NotificationApi
  * 8. ReportFilters and tools
  * 9. Inital git status.
  * For stuff inside the constructor, maybe there should just be a test to check the types.
