### ISSUE TITLE
User feedback on aligning the Hindu ULB

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3252]
[Titus Hindi ULB_notes_tC AT.pdf](https://github.com/unfoldingWord-dev/translationCore/files/1491470/Titus.Hindi.ULB_notes_tC.AT.pdf)

Bugs should be filled out as sub stories, taking note of comments in https://docs.google.com/document/d/1GBAzCda7Od7sAwsDHgdOfv25uMrqBlwyuHUYVPRVxxQ/ .

**Comment by benjore** [comment]
All these issues have been accounted for.
