### ISSUE TITLE
Alignment tool scrolls up after dropping/removing a word in a row that is scrolled down to

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3253]
alpha.12
The same thing happens when dropping or removing a word to or from a row that was scrolled to.
Before dropping the word:
![image](https://user-images.githubusercontent.com/8171759/33078080-3dfd4332-ce97-11e7-899f-8ad275391424.png)

After:
![image](https://user-images.githubusercontent.com/8171759/33078101-4cb33242-ce97-11e7-8946-6f4a5ae58736.png)

**Comment by klappy** [comment]
## Tasks:

[2] Debug and determine cause of scrolling bug
[4] Address alignment tool scrolling bug
[1] Review PR of alignment scrolling bugfix

**Comment by cckozie** [comment]
0.8.1-rc.5-852f639
Work on Windows. Need to test on Mac.

**Comment by cckozie** [comment]
0.8.1-rc.6-4b73715
Works on Mac.
