### ISSUE TITLE
Improper error message is displayed when export to USFM is canceled

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3283]
alpha.12
![image](https://user-images.githubusercontent.com/8171759/33092199-13bd01e8-cebf-11e7-80e8-da8ab066e9a8.png)

Change the verbiage to be: "Export to USFM was canceled."

**Comment by benjore** [comment]
Delete this message.

**Comment by cckozie** [comment]
This was taken care of in issue #3850
