### ISSUE TITLE
Change the verbiage on the alert displayed when export to CSV is canceled

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3284]
alpha.12
Current:
![image](https://user-images.githubusercontent.com/8171759/33092716-8ee62d3a-cec0-11e7-9253-0bed43a8bdf5.png)
 Change the verbiage to be: "Export to CSV was canceled."

**Comment by benjore** [comment]
Remove the cancel notification entirely.

~Also remove the cancel notification for the USFM import.~
