### ISSUE TITLE
Windows errors in build 12

### ISSUE THREAD

**Issue by ChrisJarka** [unfoldingWord/translationCore#3290]
Related to the https://github.com/unfoldingWord-dev/translationCore/issues/3289 issue.....

When I am in the Alignment Tool area - anything that I click on results in no response.
This is true for: 

- Any link in the top menu - black bar - that disappears when I clicked on it
- Any blue link in the progressive menu bar (User, Project, Tool)
- The "Project" button at the bottom of the screen

I needed to click the close the window X to get out of the program.

**Comment by cckozie** [comment]
This has been fixed.
