### ISSUE TITLE
Alignment Tool Percentage Complete Refinement

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/translationCore#3291]
## Story

As a user, I want to see the percentage complete of my alignment project based on words aligned so that the display is an accurate reflection of work done.

## Notes

This is a refactor of #2866 .  Current implementation only counts as complete when a whole verse has been aligned.  However, in many cases not every word will be able to be aligned in a verse.  Hence, someone may align a whole book except 1 word in each verse and the alignment tool will still report 0% aligned.  This is discourage and misleading.

The user expects the percentage to be calculated based on words aligned.

**Comment by benjore** [comment]
- [ ] % complete - each word bank word is worth one "point", each Greek word is worth one "point". E.g. if one "English" word is aligned to one "Greek" word, 2 "points" have been completed.

**Comment by lrsallee** [comment]
This system seems to make the English and Greek equal. In my understanding, it is more important that each Greek word be represented by something in the text. The biggest issue we face in aligning the ULB and UGNT is the necessity to break up long Greek sentences, which can only be accomplished by adding extra words/phrases to the ULB. In a 'normal" verse, it is typical to finish a successful alignment with a few English words left over. I propose that we either count only the OL words aligned, or weight them higher than the GL words.

**Comment by cckozie** [comment]
@lrsallee Issue #3059 is also related to this. Once that is implemented, a verse will not get the check mark until all Greek words have at least one word aligned to them.

**Comment by da1nerd** [comment]
@benjore @lrsallee  I'm calculating this based on the % of greek words that have been aligned. Is that acceptable to everyone?

**Comment by benjore** [comment]
@neutrinog That's OK with me.

**Comment by benjore** [comment]
To finish this issue, we need to do scoring according to both the GL & the Greek words. (based on stakeholder feedback)

**Comment by benjore** [comment]
Superseded by #4773
