### ISSUE TITLE
ScripturePane: Cleanup defunct code & fix linting errors

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#3299]

**Comment by PhotoNomad0** [comment]
#### Tasks:
- [x] [1] Cleanup linting errors
- [x] [2] Remove old code
- [x] [4] Unit tests
- [x] [2] PR Review
- [x] [2] PR Review #2

**Comment by PhotoNomad0** [comment]
~~@benjore - I wonder if this is already completed.  Don't see linting errors now, and I am so far not finding any unused code in this ScripturePane Project.~~

found a few linter warnings and added some observations below:

**Comment by PhotoNomad0** [comment]
#### Notes - Found:

**duplicate code:** 
- ~~lexiconEntryIdFromStrong()s & lexiconIdFromStrongs() (also in wA).~~
- ~~BooksOfTheBible (also BooksOfBible & Bible) that has four copies: tC ('./common/BooksOfTheBible'), ./components/BooksOfTheBible, resources ('./tC_resources/resources/books'), Scripture Pane, tW, tN.~~

**methods not used:**
- LexiconLookup()

#### Updated 1/3/2018:

Feedback from Jay - duplicate code listed above doesn't need to be removed.
