### ISSUE TITLE
Old Testament Support

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#33]
As a user I want to have OT resources so that I can check my OT translations.
- [x] Hebrew OT instead of Greek NT showing in T-Pane
- [x] RTL displaying Hebrew
- [ ] Hebrew Lexicon

**Comment by klappy** [comment]
@jag3773: Related issue and notes from Door43 repo: https://github.com/unfoldingWord-dev/Door43/issues/382

> We need to import Strongs data from https://github.com/openscriptures/HebrewLexicon. This will show up as the tW for the Hebrew OT.
> 
> Possibly helpful: https://github.com/jag3773/strongs-xmltodokuwiki.
> 
> Note: it would be nice to import the BDB dictionary information as well, just not sure how all that will look atm.

**Comment by klappy** [comment]
https://github.com/unfoldingWord-dev/Door43/issues/381

> We need to import Hebrew from https://github.com/openscriptures/morphhb.
> 
> This process will entail:
> 
>  Convert text to USFM
>  Import to API via tools/uwb/usfm_tS_import.py
>  Import parsing information and work with @neutrinog to make this available in the app. See unfoldingWord-dev/ts-android#1001. Possibly helpful: https://github.com/jag3773/strongs-xmltodokuwiki.

**Comment by jag3773** [comment]
@klappy @RoyalSix Note that for Hebrew/Aramaic Lexicon support I put some notes and links in  https://git.door43.org/Door43/UHAL/src/master/README.md#initial-inclusion-in-tc.  The XML files linked to there should provide the necessary data to actually show the lexical glosses that are referenced in the text.

**Comment by RoyalSix** [comment]
Awesome! I didn't know there was information on my issue outlined on this epic wow....
