### ISSUE TITLE
translationWords: Make GroupData ContextId & Quote based on references in BHP/UGNT

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#3304]
### The previous English based tW data for the checks/menu is located: 
- repo: `tC_resources`
- path: `./resources/en/translationHelps/translationWords/v6/kt/groups/[book_id]/[article_id]`
- generated from tW occurrences in the English tW repository.

### The new UGNT/Greek based  tW data for the checks/menu needs to be located:
- repo: `tC_resources`
- path: `./resources/grc/translationHelps/translationWords/v6/kt/groups/[book_id]/[article_id]`
- generated from the UGNT with tW links in the `\k-s` and `\k-e` milestones with `x-tw` attributes.

### The previous format was:
```json
[
  {
    "priority": 1,
    "comments": false,
    "reminders": false,
    "selections": false,
    "verseEdits": false,
    "contextId": {
      "reference": { "bookId": "tit", "chapter": 1, "verse": 7 },
      "tool": "translationWords",
      "groupId": "blameless",
      "quote": "[ulb_quote]",
      "occurrence": 1
    }
  },
  {
    "priority": 1,
    "comments": false,
    "reminders": false,
    "selections": false,
    "verseEdits": false,
    "contextId": {
      "reference": { "bookId": "tit", "chapter": 2, "verse": 8 },
      "tool": "translationWords",
      "groupId": "blameless",
      "quote": "[ulb_quote]",
      "occurrence": 1
    }
  }
]
```

### The new format needs to be:
```[
  {
    "priority": 1,
    "comments": false,
    "reminders": false,
    "selections": false,
    "verseEdits": false,
    "contextId": {
      "reference": { "bookId": "tit", "chapter": 1, "verse": 7 },
      "tool": "translationWords",
      "groupId": "blameless",
      "quote": "[ugnt_word]",
      "strong": "[strong_id]",
      "occurrence": 1
    }
  },
  {
    "priority": 1,
    "comments": false,
    "reminders": false,
    "selections": false,
    "verseEdits": false,
    "contextId": {
      "reference": { "bookId": "tit", "chapter": 2, "verse": 8 },
      "tool": "translationWords",
      "groupId": "blameless",
      "quote": "[ugnt_word]",
      "strong": "[strong_id]",
      "occurrence": 1
    }
  }
]
```

### Previously:
- a yaml file that told which book/chapter/verse for where each word occurred.

### New data needs to be extracted from:
- json that uses verseObjects extracted from the USFM.
- located: `./resources/grc/bibles/ugnt/v0/[book_id]/[chapter].json`
- Loop through following file to generate the tW group data contextIds in the files.
```json
{
  "1": {
    "verseObjects": [
      {
        "type": "text",
        "text": "\n"
      },
      {
        "tag": "p",
        "type": "paragraph",
        "text": "\n"
      },
      {
        "text": "Παῦλος",
        "tag": "w",
        "type": "word",
        "lemma": "Παῦλος",
        "strong": "G39720",
        "morph": "Gr,N,,,,,NMS,",
        "tw": "rc://*/tw/dict/bible/names/paul"
      },
      {
        "type": "text",
        "text": ",\n"
      },
      {
        "text": "δοῦλος",
        "tag": "w",
        "type": "word",
        "lemma": "δοῦλος",
        "strong": "G14010",
        "morph": "Gr,N,,,,,NMS,",
        "tw": "rc://*/tw/dict/bible/other/servant"
      }
    ]
  }
}
```

## Other notes:
- New data has three categories: [kt, names, other] and the old data only had two: [kt, other].
- If the occurrence in the UGNT word has more than 1 of the same tW links in the verse, make sure to include it in the group data.
- Not all `x-tw` attributes are found in the `type: word` verseObjects. Sometimes they are found in `type: milestone` verseObjects. These are used when a Greek phrase(multiple words) is tagged to a single tW article/check.

**Comment by richmahn** [comment]
- [ ] [5] GroupData ContextId & Quote based on references in BHP/UGNT for tW
- [ ] [3] Writes tests for #3304

**Comment by cckozie** [comment]
0.8.1-alpha.16-7f62850
No translationHelps folder in /Users/cckozie/translationCore/resources/grc
![image](https://user-images.githubusercontent.com/8171759/36212968-fc2d8360-116a-11e8-9e2c-79fe018d00d6.png)

**Comment by richmahn** [comment]
I don't think this is really testable by QA, as it just adds data, but as you pointed out, in the build there is no data. I'm guessing a change to the tC_Resources repo doesn't cause a new build. Will check on that.

**Comment by richmahn** [comment]
Ok, realized that you were looking in the user directory's resources directory which we didn't have this copying to at all. We are making another PR to do that.

**Comment by richmahn** [comment]
Expected user resources solved in #3831. Making this a QA Watch for when that story goes through QA.

**Comment by cckozie** [comment]
@richmahn So where does this issue copy the data to?

**Comment by cckozie** [comment]
Data is in the app but not exposed to the user at this point. Can't really test until #3831 is done.

**Comment by cckozie** [comment]
Do we care that in the file system the path contains "V0" instead of "V6"?
![image](https://user-images.githubusercontent.com/8171759/36450353-447aac14-1653-11e8-8740-430cbc380d64.png)

**Comment by cckozie** [comment]
Per @jag3773 , V0 is correct.

**Comment by jag3773** [comment]
Just to clarify, the UGNT is at version 0 right now, but the English tW text is at version 8 right now.
