### ISSUE TITLE
translationWords: Update CheckCard to display Gateway Language tW Title instead of Greek quote

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#3305]
After updating tW to use greek quotes the Check card was discovered to display the greek quote instead of the Title from the Index/Article.
(Issue relates only to the text on the CheckCard.)
## Note: 
- The title of the check shows up in three places (side menu, check info card, tHelps)
- The GL word/phrase being checked shows up in two places (highlighted in the Scripture Pane, spelled out in the check card)
- The Greek word/phrase being checked should be highlighted, but should not appear anywhere else.
- Once selected and the user clicks `Save`, the Target Language selection should show up 4 places (spelled out in the side menu, highlighted in the left side of the check card, spelled out in the right side of the check card, highlighted in the Scripture Pane)

![image](https://user-images.githubusercontent.com/13352518/36269458-db48e0ac-123e-11e8-9d9c-059737a2e432.png)

![image](https://user-images.githubusercontent.com/13352518/36269435-d148e8b8-123e-11e8-8e5e-335adf5c6c7a.png)

**Comment by richmahn** [comment]
Note to @cckozie: this addresses what you were wanting to be able to see in QA Fail #3304 so should close both. Will add #3304 as a QA Watch.

**Comment by richmahn** [comment]
- [ ] [6] Change CheckCard to use GL instead of Greek
- [ ] [3] Write CheckCard tests for pulling from GL tW resource
