### ISSUE TITLE
Fix issues with update version script

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#3311]
The update version script has a few issues and addressed by using `npm version` command.

**Comment by cckozie** [comment]
@klappy Is the Task label on this by mistake? If so, is there anything I should be testing on it?

**Comment by klappy** [comment]
@cckozie: I wasn't sure whether to call it a task or a story. It was work that was done weeks ago and I didn't have a PR to include it in. So I made an issue to track the work.
