### ISSUE TITLE
Invalid links showing up in tW blue bar

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3315]
![image](https://user-images.githubusercontent.com/8171759/33446013-597b9242-d5c4-11e7-9644-489d2226b7cd.png)

NOTE: In 0.9.0, 'light' is in the 'other' category, not 'kt', so the check displayed above does not show up in tC.

**Comment by jag3773** [comment]
Ideally that would be converted to a hyperlink that loads the Metaphor tA article.

**Comment by benjore** [comment]
Add support in tW to tA.

**Comment by jag3773** [comment]
Add support for links according to http://resource-container.readthedocs.io/en/latest/linking.html

Include language and resource type.

Specify that English is the fallback for any language that may not have the resource.  For example, a link to a Hindi tA article that doesn't exist should fall back to the English one.

**Comment by cckozie** [comment]
@benjore 
As noted in the first comment, 'light' is now in the Other group and not in Key terms, so testing this particular problem is not straight forward.
I did hack the tW resources to copy the entry from the Other folder to the kt folder and updated the kt index.json file to also include it. If that is a legitimate way to test it, then the problem still remains.
This is a screenshot from 1.0.2 (6ab77c0):
![image](https://user-images.githubusercontent.com/8171759/46816792-5194a880-cd43-11e8-897a-4503acfeb88a.png)

**Comment by elsylambert** [comment]
Retested on 2.0.0 (ca6c273). Not seeing this issue.
