### ISSUE TITLE
Quotes Not Displaying Correctly From BHP/UGNT

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3316]
The quotation marks from the BHP are not being displayed correctly. Here are the first few words of 5:3
![image](https://user-images.githubusercontent.com/8171759/33447898-2db0f03e-d5ca-11e7-8df8-1bedfa8522ce.png)

In the tC resources folder this shows up as follows:
![image](https://user-images.githubusercontent.com/8171759/33448020-8ac157b4-d5ca-11e7-8f16-06261265ecc8.png)

Then in the tC scripture pane is looks like this:
![image](https://user-images.githubusercontent.com/8171759/33448174-f1fa0fe8-d5ca-11e7-9156-6ee16a8ed10a.png)

The English for this is `“Peace and safety”,`.  The quotation marks are supposed to be there but they aren't being shown properly.

In addition, there is a close quote and comma at the end of https://git.door43.org/Door43/BHP/src/master/53-1TH.usfm#L1355 that are not being displayed.

**Comment by benjore** [comment]
Will be fixed #3185 or #3186

**Comment by cckozie** [comment]
Still not seeing quote marks in UGNT in 0.8.1-alpha.15-633b904
