### ISSUE TITLE
Project Migration Module: Add latest version number to manifest.json file

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#3322]

**Comment by PhotoNomad0** [comment]
### Tasks:
- [ ] [2]  Add version to manifest.json
- [ ] [4] Add version tests

**Comment by PhotoNomad0** [comment]
@benjore - Blocked until versioning requirements resolved.
Is this going to start with "1" or some other value.

**Comment by PhotoNomad0** [comment]
Feedback from Jesse is to start with 1.
