### ISSUE TITLE
App locks up in tW

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3323]
0.8.1-alpha.12-8a1618d
[fr_mrk_text_ulb.zip](https://github.com/unfoldingWord-dev/translationCore/files/1522708/fr_mrk_text_ulb.zip)
Load a project in tW and click on various items in the verse menu. It may be dependent on project size in terms of how many clicks it will take to lock up. In this Mark project it usually only takes a few clicks. Most of the time there is nothing in the console, but one time I did get this:
![image](https://user-images.githubusercontent.com/8171759/33499338-2809105a-d69a-11e7-8646-1ca0b2fcd0b1.png)

See also issue #3370

**Comment by jag3773** [comment]
I'd suggest skipping tests on the tW tool for now since large parts of it are going to be rewritten very soon in #2148 , #3097, #3273, etc.

**Comment by cckozie** [comment]
Appears to be fixed in 0.8.1-alpha.13-65c49d1
