### ISSUE TITLE
How do we Handle corrupted projects in tC projects folder

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord/translationCore#3352]
How do we Handle corrupted projects in tC projects folder that aren't fixed by migrations and validations process

**Comment by benjore** [comment]
- [ ] If there is a corrupted project that cannot be opened:
  - [ ] The app cannot crash
  - [ ] Give the user the message: "Your project is corrupted and cannot be opened. If you have questions, contact help@door43.org." Add a `Cancel` button
