### ISSUE TITLE
Write manifest migrations from tStudio to tC

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord/translationCore#3366]
- Manifests coming from tS with a package_version lower than 3 need to be tweaked a bit to work in tC.

- The tweaking is happening somewhere in the project validation process when it should happen in the migrations process.

**Comment by mannycolon** [comment]
@jag3773 @benjore This should probably be part of this sprint

**Comment by benjore** [comment]
@mannycolon does this need to be a new story or can it just be a task?

**Comment by PhotoNomad0** [comment]
@mannycolon - This is already addressed in https://github.com/unfoldingWord-dev/translationCore/pull/3367

**Comment by mannycolon** [comment]
@PhotoNomad0 Did we removed the unnecessary code from the previous implementation?

**Comment by PhotoNomad0** [comment]
### Tasks:
- [ ] [1] Fix version 3 migration and move into migrate.
- [ ] [1] Add version 3 unit test.

**Comment by PhotoNomad0** [comment]
PR is https://github.com/unfoldingWord-dev/translationCore/pull/3367

**Comment by cckozie** [comment]
0.8.1-alpha.13-530cee8
https://git.door43.org/168b7e635905dd89/uw-gal-hsl
I'm not sure that this problem is related to migrating the project, but since I see "Cannot read property 'manifest' of undefined" in a console error, I'm guessing it is.
![image](https://user-images.githubusercontent.com/8171759/34111786-58b5c75a-e3d0-11e7-9891-e4eb069b29ee.png)

**Comment by PhotoNomad0** [comment]
@cckozie - this is a broken project.  It has no data.  the usfm file only has one line:

> \id

 TIT EN_ULB fr_fr_ltr Tue Nov 14 2017 13:53:19 GMT-0500 (EST) 

> tc

**Comment by PhotoNomad0** [comment]
@cckozie - interesting bug.  See the crash immediately after import, but if I restart the app it will open.

**Comment by PhotoNomad0** [comment]
### Task
- [ ] [3] Research what is not getting set up after import 
- [ ] [2] Fix initialization
- [ ] [3] Unit tests
- [ ] [1] PR review 1
- [ ] [1] PR review 2
