### ISSUE TITLE
Word Alignment comes up with blank screen

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3368]
alpha.12-8a1618d
This project loads properly in tW but comes up blank in alignment.
https://git.door43.org/TC_SAVE/abu_tit_text_reg
![image](https://user-images.githubusercontent.com/8171759/33729172-6e921330-db42-11e7-9339-dc0368adbbae.png)

**Comment by cckozie** [comment]
0.8.1-alpha.13-18b49c2
It may have to do with which tool is used to open the project first. If I open Alignment first after the import it opens fine, but then when I change to tW, it opens to a blank screen.

**Comment by benjore** [comment]
- [ ] Gracefully handle missing chapters. 
- [ ] Something wrong with the ContextID

**Comment by cckozie** [comment]
This is no longer a problem in 0.8.1-alpha.13-65c49d1
