### ISSUE TITLE
Automatic builds don't update the app version number

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord/translationCore#3376]
- This is important because we have migrations that rely on this app version number changing.

**Comment by da1nerd** [comment]
This was by design. Could you elaborate on the issue?

**Comment by da1nerd** [comment]
@mannycolon could you describe the issue in detail here since we can't seem to get together? :)

**Comment by benjore** [comment]
@cckozie Is this still an issue?

**Comment by cckozie** [comment]
@benjore I'm not sure. I suspect they're referring to something other than the version number that shows up in the app.
