### ISSUE TITLE
Importing USFM projects causes console error and blank alert dialog

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3386]
[hi_tit.usfm 2.zip](https://github.com/unfoldingWord-dev/translationCore/files/1552131/hi_tit.usfm.2.zip)
Same behavior with many (maybe all) USFM projects
![image](https://user-images.githubusercontent.com/8171759/33892568-b832b28a-df1e-11e7-88a2-6304fe9ddbf4.png)

**Comment by mannycolon** [comment]
@cckozie Usfm import isnt supported in that build
