### ISSUE TITLE
Project gets deleted after being imported and opened in tW

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3393]
Imported https://git.door43.org/TC_SAVE/en_tit and opened it in tW.
Clicked on the Projects icon in the menu bar.
I was returned to the Projects page but my imported projects is not listed there.
When I attempt to import it again I get the "Project has already been imported." alert.
The project is not in the Projects folder, but it is in the Imports folder.
The same thing happens with the Word Alignment tool.
If rather than clicking on the Project icon in the menu bar I click on the Tool icon, I can then open the project in the selected tool. 
Clicking anything else that takes me out of the loaded project causes it to be deleted.

**Comment by RoyalSix** [comment]
# Tasks
 - [ ] [3] Debug Workflow For Projects That Do Not Get Fully Imported

**Comment by mannycolon** [comment]
@cckozie @RoyalSix This should be handled by #3419 which is currently in review

**Comment by cckozie** [comment]
It was not fixed by #3419 and is still broken in 0.8.1-alpha.13-18b49c2

**Comment by PhotoNomad0** [comment]
### Task
- [ ] [2] Research what is not getting set up after online import 
- [ ] [2] Fix initialization
- [ ] [3] Unit tests
- [ ] [2] PR review 1
- [ ] [2] PR review 2

**Comment by cckozie** [comment]
Looks like this was fixed in 0.8.1-alpha.13-d0985d1. Need to test on Windows.

**Comment by PhotoNomad0** [comment]
Not seeing this problem on develop branch.  Next will try the last dev build.

**Comment by PhotoNomad0** [comment]
@cckozie - See the problem in build translationCore-win-x64-0.8.1-alpha.13-e36f42c, but translationCore-win-x64-0.8.1-alpha.13-d0985d1 does not have it.

**Comment by cckozie** [comment]
Need to wait for new develop build since tW is not supported in 0.8.1 release.
