### ISSUE TITLE
Door43 project import ends with "The project you selected has an invalid manifest" alert

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3395]
0.8.1-alpha.12-7f6897c
https://git.door43.org/168b7e635905dd89/uw-gal-hsl
The project imports correctly into tS.
If I export from tS to a tstudio file, I can then successfully import the project into tC.

**Comment by RoyalSix** [comment]
This is a good example of a project that needs to be migrated.
@cckozie @jag3773  What is the correlation of the manifest versioning in this project to the version of tS? Because we state in the import process we do not support tS versions lower than 11.

**Comment by RoyalSix** [comment]
# Tasks
- [ ] [2] Add The Manifest Ver 3 Check Before Checking For Required Fields

```ProjectValidationActions.setUpProjectDetails```

**Comment by cckozie** [comment]
@benjore Are we sticking with the tS version 11 or greater, or should our project migration now handle older projects?
If we're sticking with version 11 and greater, maybe we should issue an alert when the user attempts to import something older and suggest that they us tS to upgrade the project and then try agin.

**Comment by cckozie** [comment]
@RoyalSix  I'm closing this and creating a new issue for future consideration.

**Comment by cckozie** [comment]
This is no longer a problem in  0.8.1-alpha.13-1042daa
