### ISSUE TITLE
Unable to reimport a project when the import is ended by an error or the user cancels out of a validation step

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3396]
If an import encounters and error, or if the user cancels in the validation phase, the project cannot be reimported. An attempt to reimport causes the Project has already been imported. alert to be displayed. The project is not in the Projects folder at that point, but it is in the Imports folder.

**Comment by RoyalSix** [comment]
@cckozie @benjore Should we make a recent imports spot ?

**Comment by cckozie** [comment]
@RoyalSix I believe our decision was that anytime an error is encountered or the user cancels before the validation is complete, the imported files are deleted so that the import can be retried. (Issuing a warning message with that info is in another issue).
@benjore Did I get that right?

**Comment by benjore** [comment]
@cckozie @RoyalSix That is correct.

**Comment by PhotoNomad0** [comment]
### Tasks
- [ ] [4] Remove project on validation cancel.
- [ ] [4] Remove project on error.

**Comment by mannycolon** [comment]
@PhotoNomad0 Sorry i did not write here that was working with this in my last PR. Since we spoke about it in stand up yesterday didnt think anyone would pick it up
