### ISSUE TITLE
Warn user if project is too old to be used in tC

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3409]
Currently if the user attempts to import a project that is from pre-v11 tS, the import fails with a message indicating that the project has an invalid manifest. It would be better to change the alert in that case to suggest that they use tS to upgrade the project and then try again.

NOTE: This may have been fixed in 0.8.1. The 2 projects listed below are at manifest version 3 and they do successfully load in 0.8.1. In 0.9.0 they cannot be loaded because of the temporary fix implemented to prevent the possible loss of checking data in 0.7 projects. This will likely not be an issue after #4333 is completed. I'm added that as a dependency.

NEEDS MESSAGE
PROJECTS TO TEST WITH:
https://git.door43.org/168b7e635905dd89/uw-gal-hsl
https://git.door43.org/6fe72becd4c445fa/uw-tit-pt-br

**Comment by benjore** [comment]
Dup of #4491 ?
