### ISSUE TITLE
Unused USFM markers appear in text

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3424]
0.8.1-alpha.13-4ef6c94
https://git.door43.org/qa99/en_heb_text_reg
This was recently fixed but was broken in the refactor.
![image](https://user-images.githubusercontent.com/8171759/34062795-1f714be0-e1b4-11e7-9b5d-37af344df8d5.png)

**Comment by PhotoNomad0** [comment]
### Task
- [ ] [3] Research what got dropped 
- [ ] [2] Fix filtering
- [ ] [3] Unit tests
- [ ] [2] PR review 1
- [ ] [2] PR review 2

**Comment by PhotoNomad0** [comment]
@cckozie @benjore - this is USX formatting in this book, not USFM.  From manifest, it was generated by an old version of ts-android before we switched to USFM.  Not sure we want to support this is tc.  If a user has an old version like this, they can import it into a newer version of ts-android which should migrate it to USFM.

**Comment by cckozie** [comment]
@PhotoNomad0 I think you may be right on that point. What say you @benjore?
Unfortunately with an USFM version there is another problem, truncated text when quote marks are encountered. This was written up in #3485 for Word Alignment. Would fixing it here (or there) fix the problem in both tools?
![quotes](https://user-images.githubusercontent.com/8171759/34310370-ecd67fd4-e71c-11e7-82a2-9f1b41f9fe7f.png)

**Comment by cckozie** [comment]
We're not supporting USX files at this point.
