### ISSUE TITLE
Clean up Imports folder after user attempts to import a project that already exists

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3428]
0.8.1-alpha.13-530cee8 
The user properly receives the Project already exists message and the import is canceled, but the project remains in the Imports folder. Currently that is not a problem except that it prevents importing after deleting the project out of the Projects folder, but it may cause issues once we implement the archive feature.

Solution: 
When the user clicks `Import` (any form of import),  clear the Imports folder.

**Comment by benjore** [comment]
Might be covered by #3559 or #3763

**Comment by benjore** [comment]
Make sure it resolves #4080
