### ISSUE TITLE
Issue the duplicate project message as soon as it can be determined to be a duplicate

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3429]
Currently the message "The project you selected (project name) already exists.
Reimporting existing projects is not currently supported." is displayed to the user at the end of the validation stepper. It would be much more user friendly to display it as soon as we know. That should be before the validation stepper for Door43 projects, before or after the license page for tstudio projects (depending on whether or not we know the license), and after the project info page for USFM imports.

**Comment by benjore** [comment]
This issue will be superseded by #3559 #3763
