### ISSUE TITLE
tC imports renamed pdf and mp3 files as legitimate projects

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3432]
0.8.1-alpha.13-18b49c2
[_tS Sort.pdf.txt.zip](https://github.com/unfoldingWord-dev/translationCore/files/1572250/_tS.Sort.pdf.txt.zip)
[_test1.mp3.txt.zip](https://github.com/unfoldingWord-dev/translationCore/files/1572287/_test1.mp3.txt.zip)

**Comment by PhotoNomad0** [comment]
Current validation checks for one of `\id`, `\h`, or `\v`.
The mp3 has both `\h`, or `\v` in it.
The pdf has `\v`.

Adding a space after the checks will reject the test files.

**Comment by PhotoNomad0** [comment]
#### Tasks
- [ ] [2] Fix USFM import validation
- [ ] [2] Unit tests
- [ ] [2] Review PR
- [ ] [2] Review PR #2
