### ISSUE TITLE
Downloading Door43 project overwrites existing project

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3434]
I imported a project from USFM and then uploaded it to Door43. 
I then opened the project in tW and edited one of the verses.
I then imported the project from Door43 and opened it in tW.
The verse that I edited was now overwritten by the non-edited one in the Door43 project.
The imported file is still in the Imports folder.

**Comment by mannycolon** [comment]
- [ ] [4] Debug why downloading a Door43 project overwrites an existing project.
- [ ] [5] Fix bug with overwritten projects when downloading the same project from door43.

**Comment by cckozie** [comment]
Need to wait for build that has tW.
