### ISSUE TITLE
When unmerging Greek words the available target is very narrow and is active for only a very small movement of the Greek word.

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#3435]
## Specs
- [x] Make the new "drop box" 1/4 the size of the current alignment boxes (1/2 of the new alignment boxes) (related to #2925 )

**Comment by PhotoNomad0** [comment]
@neutrinog - Why is this in Review - don't see a PR attached.

**Comment by da1nerd** [comment]
@PhotoNomad0 see the merged PR in the history above.
