### ISSUE TITLE
Do not automatically open Developer Tools in 0.8.1 release

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3478]

**Comment by klappy** [comment]
@cckozie @benjore: Shouldn't this be v0.8.1? That's the next increment that I'm aware of. There isn't a v0.8.1 yet.

**Comment by cckozie** [comment]
@klappy Yes, I think you're right.

**Comment by cckozie** [comment]
Cannot test until we get a build from develop
