### ISSUE TITLE
Allow all New Testament books in non-developer mode for 0.8.1 limited release

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3479]
Currently when not in developer mode there is only a console error and no user message when attempting to open a non-Titus project when not in Developer mode.

**Comment by mannycolon** [comment]
# Tasks
- [ ] [3] Review/find helper function that checks if a project is a NT bible project.
- [ ] [4] Allow all New Testament books in non-developer mode

**Comment by cckozie** [comment]
Works in Sandbox. Need to retest in develop.
