### ISSUE TITLE
Word Alignment does not handle quotes marks

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3485]
0.8.1-alpha.13-46601e0
PROBLEM 1
[59-HEB.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/1579985/59-HEB.usfm.zip)
It appears that when a quote mark is encounter it causes the app to hang. We need to make sure that both single quote and double quote marks are properly handled.
After reloading the app and it sets the verse to the one with the quote marks, when the quote mark is encountered it stops adding words to the word list.
It also causes the target text to get truncated in the scripture panes.
![image](https://user-images.githubusercontent.com/8171759/34267060-178d6f1c-e641-11e7-8b71-5c419d2211e3.png)
1. Import the attached Hebrews USFM file
2. Open it with Word Alignment tool
3. Click on Heb 1:5. The app will lock up.
4. Restart tC and reopen the project with Word Alignment
5. Notice the truncated word list and verse in the scripture pane.

PROBLEM 2
I assume the following problem may be related to quote marks as well.
[55-1TI.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/1580100/55-1TI.usfm.zip)
1. Import the 1Timothy USFM file
2. Open it with Word Alignment tool
3. Close the Chapter 1 verse list in the menu panel
4. Click on the Chapter 3 header.
5. The app freezes with no console errors

**Comment by PhotoNomad0** [comment]
The current usfm-js library strips out usfm quotes.

**Comment by cckozie** [comment]
0.8.1-rc.5-852f639
[41-MAT.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/1591521/41-MAT.usfm.zip)
Single quotes are causing a similar problem. See Matt 2:6
![image](https://user-images.githubusercontent.com/8171759/34415396-1f5d7a66-ebb4-11e7-8d51-9ce507a7f724.png)

**Comment by mannycolon** [comment]
- handle straight quotes and curly quotes

**Comment by PhotoNomad0** [comment]
When I test with the current develop branch, on USFM import I see all of Mat 2:6.  And on USFM import I see all of Heb 1:5

**Comment by PhotoNomad0** [comment]
Also testing with translationCore 0.8.1-rc.6-4b73715, I see all of Mat:

![screen shot 2017-12-28 at 8 25 29 pm](https://user-images.githubusercontent.com/14238574/34427186-5a8235c4-ec0d-11e7-96b9-fa3ec92737fa.png)

And Hebrews is similar.
