### ISSUE TITLE
Create diagrams for tC architecture and the API abstraction

### ISSUE THREAD

**Issue by EllDoubleYew** [unfoldingWord/translationCore#35]
As a translation core developer I want to have diagrams describing the modular architecture of translation core as well as the different kinds of abstractions implemented in the API so that I have a better idea of how to write my modules.

![](https://files.slack.com/files-pri/T1GNLDHH6-F21J568UX/fullsizerender.jpg)

![](https://files.slack.com/files-pri/T1GNLDHH6-F21J56DFZ/fullsizerender.jpg)

**Comment by klappy** [comment]
Here's my notebook sketch:
![image](https://cloud.githubusercontent.com/assets/118073/17811689/d98a4bde-65f1-11e6-95db-d770e9b42643.png)

**Comment by EllDoubleYew** [comment]
![tcmodulararchitecture](https://cloud.githubusercontent.com/assets/7133050/18364904/44683ba4-75de-11e6-97c2-30bdb120176e.jpg)
![coreapiabstraction](https://cloud.githubusercontent.com/assets/7133050/18364907/4834fa1a-75de-11e6-81d9-2638a29e5a15.jpg)
