### ISSUE TITLE
No image is displayed on the project loading dialog

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3522]
This was first noticed on Windows in 0.8.1-rc.3-d8d4486 but has gotten worse.
In 1.0.0 (e375ee0) is also happens frequently on Mac.

![image](https://user-images.githubusercontent.com/8171759/34386755-d8664fb2-eaef-11e7-9d57-28af459672d1.png)

**Comment by benjore** [comment]
Retest after #5127 is completed @RoyalSix

**Comment by cckozie** [comment]
Still fails in 1.1.0 (c6414a7)

**Comment by cckozie** [comment]
Still an intermittent problem in  1.1.3 (240da43)

**Comment by cckozie** [comment]
Mostly fixed in 1.2.0-f58a0ac
I tested about 15 project loads. It failed once and worked all of the other times, so I'll pass it for now.
