### ISSUE TITLE
"Loading your project data" alert does not show tC logo

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3525]
0.8.1-rc.3-5d19d3f 
This seems to happen after tC has not loaded a project for a while.
![image](https://user-images.githubusercontent.com/8171759/34394653-378cb1b8-eb20-11e7-80ee-bb51e4cf5142.png)

**Comment by benjore** [comment]
@cckozie Can you verify if this is still a problem and leave instructions for reproducing it? Thanks!

**Comment by cckozie** [comment]
I have not seen this problem for a long time so I am closing it.
