### ISSUE TITLE
tC does not recognize Git as being installed after installation on "clean" Windows machine

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3538]
0.8.1-rc.6-4b73715
I started with a "clean" machine having uninstall both tC and Git. I also deleted both of the translationCore folders, one in the user's directory and one in the hidden AppData/Roaming directory.
I ran the rc6 installation with the option to install Git checked.
When I started tC this error message came up even though Git had been installed:
![image](https://user-images.githubusercontent.com/8171759/34425923-d145fe78-ebf6-11e7-87d7-02e50aa0e453.png)
I clicked the Close translationCore button, then restarted tC and it started properly.

**Comment by da1nerd** [comment]
This may be happening just when tC is started immediately after the installation. In that case it's very likely the environment is stale and doesn't know about git yet. That would explain why tC works when restarting it. @cckozie what happens if you perform the install but uncheck the option to launch tC after exiting the setup, then start it manually?

**Comment by cckozie** [comment]
@neutrinog If I uncheck the option to launch and then start it manually it does work.
I also tested it by rebooting after uninstalling git and tC and deleting all of the tC folders. In that case I did get the error after clicking Finish with the launch checkbox enabled.

**Comment by da1nerd** [comment]
ok I'm 99% certain it's an issue with a stale environment. The easiest solution would be to remove the option of automatically starting tC after installation. I'm not sure how complicated it would be to manually reload the environment either as a part of the installation or part of the initial application boot up process.

**Comment by benjore** [comment]
Superseded #4960
