### ISSUE TITLE
tW Hindi: Update the Scripture Pane

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#3550]
Note that this means that the selected GL (`projectDetailsReducer.currentProjectSelectedGL[<tool name>]`) should SHOW in the Scripture Pane as well as, no matter what GL is selected, be an option in the Bible selector for the Scripture Pane (per Jesse/Ben clarification on Slack)

**Comment by richmahn** [comment]
Note that this means that the selected GL (`projectDetailsReducer.currentProjectToolsSelectedGL[<tool name>]`) should SHOW in the Scripture Pane as well as, no matter what GL is selected, be an option in the Bible selector for the Scripture Pane (per Jesse/Ben clarification on Slack)

**Comment by PhotoNomad0** [comment]
#### Tasks:
- [ ] [3] Implement showing selected GL
- [ ] [3] Implement showing selected GL as scripture pane option.
- [ ] [6] Unit tests
- [ ] [6] PR Review

**Comment by richmahn** [comment]
No longer needed as https://github.com/unfoldingWord-dev/translationCore/pull/3967 fixes all this.

**Comment by cckozie** [comment]
The GL does not show in the scripture pane after doing a clean install.
Start with a clean machine (uninstall tC, delete translationCore folders in both user aned Application Support folders)
Install tC
Import a project and go through validation stepper
Load the project with tW
Notice that only the Greek and target language are displayed in the scripture pane.
Go back to the Tools page and select a different GL for tW
Load the project with tW again and notice that the GL is still not displayed in the scripture pane.

Now add the previously selected GL to the scripture pane
Go back to the Tools page and select a different GL for tW
Load the project with tW and notice that the scripture pane now does display the selected GL

**Comment by mannycolon** [comment]
@cckozie Can you still recreate this issue above

**Comment by cckozie** [comment]
0.8.1-alpha.22-21f62ad 
Now it just loads the GL and not either the Greek or target language.
After clean install and loading without changing default (English) GL
![spane1](https://user-images.githubusercontent.com/8171759/37234802-a2c5ad2c-23bf-11e8-9010-144ef5d30563.png)
.
After changing the GL to Hindi
![spane2](https://user-images.githubusercontent.com/8171759/37234819-afa0d86e-23bf-11e8-835d-19ef9ef98ff3.png)
.
After manually adding Greek and target it does work correctly.

**Comment by mannycolon** [comment]
**Per slack conversation:**

The behavior above is expected behavior for the first time you load tC with a new tool and new project.
A long time ago Ben said to only display the ULB in the first load of tC. In other words, the first time that the settings for the scripture pane are set.

**Comment by benjore** [comment]
@mannycolon Default view for the Scripture Pane should be: 
left: Gateway Language ULB - center: target language - right: blank

**Comment by mannycolon** [comment]
@benjore ok.
