### ISSUE TITLE
tW Hindi: tHelps works

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#3552]

**Comment by richmahn** [comment]
- [ ] [2] Verify tHelps works with Hindi translationWords

**Comment by richmahn** [comment]
Verified it works.

**Comment by cckozie** [comment]
Hindi does show up in the tHelps pane. None of the embedded links there work, but that is not related to Hindi.

**Comment by cckozie** [comment]
I spot checked some of the kt text in the tHelps pane and that looks good. Depending on other issues to fix the link problems.
