### ISSUE TITLE
[0] Cut Release 0.8.1

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/translationCore#3595]
Follow Release Notes at https://docs.google.com/document/d/1-dJvDrxjIYwiUKUnH-E8qZel-DCDhsgM8iR-n9Cm57w/edit#heading=h.kwwwpmel1ulv

**Comment by klappy** [comment]
Looks like Travis errored out: https://travis-ci.org/unfoldingWord-dev/translationCore/builds/324670401

Made OSX build manually. Uploading all downloads from http://tc-release.unfoldingword.surge.sh/
