### ISSUE TITLE
No tC default tools found error in 0.8.1

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3606]
I think this is caused by the Continue button on the project info screen being enabled before the language selection is complete because of how slow the type ahead feature performs. This is how I can recreate it on both Windows and Mac:
1. Select a good (no missing verses or merge conflicts) usfm file to import 
2. Make a selection on the copyright page
3. On the project info page, type in a language code in that field and quickly click Enter, then immediately click on the Continue button as soon as it is enabled.
4. The tools screen comes up with no tools available and this in the console log:
![image](https://user-images.githubusercontent.com/8171759/34542548-a763e434-f0a2-11e7-9721-eaf1bbc7fa2c.png)
5. Go back to the projects page and you'll see that the project did not get a legitimate name.
6. Go to the Edit Project Details, enter data for the missing fields and click save. Notice that the entered fields are saved, but the project still does not have a name.

**Comment by cckozie** [comment]
Here's a little different symptom, but I suspect it is caused by the same problem.
Steps 1-3 same as above.
On the tools screen I selected tW.
The tW tool opened with a blank screen, an error in the console, and a project name of just "_"
Fairly easy repeatable using [45-ACT.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/1717637/45-ACT.usfm.zip)
 
![image](https://user-images.githubusercontent.com/8171759/36117572-be2ca526-0fff-11e8-9196-4216644244a2.png)

**Comment by mannycolon** [comment]
@cckozie Ok I will take a look at it. Thanks.

**Comment by benjore** [comment]
@cckozie Have you ever seen this issue show up when NOT in developer mode?

**Comment by cckozie** [comment]
@benjore Yes. It is easy to reproduce on my Windows machine with any project. I'm pretty sure it's caused by a race condition that causes problems when leaving the Project Information page after setting the language. The language selection portion of that page needs to be totally refactored. See #3560 and #3664.

**Comment by PhotoNomad0** [comment]
#### Tasks:
- [ ] [16] Fix race condition allowing continue if project information is not complete
- [ ] [8] Unit Tests
- [ ] [8] PR Review
