### ISSUE TITLE
How to delete projects?

### ISSUE THREAD

**Issue by ChrisJarka** [unfoldingWord/translationCore#361]
Not finding a way to delete projects from tC - I thought that if I deleted them from the tC folder that they would be gone from the program.
No. As you can see from this screen shot - the folder is empty but the projects are still listed in tC.

![projects where there are none](https://cloud.githubusercontent.com/assets/9850185/20806406/c0ac8144-b7c8-11e6-9b17-5eb4cc94d09c.png)

**Comment by klappy** [comment]
This should be addressed in the latest release. Let use know if it isn't.
