### ISSUE TITLE
Failure on import from Door43

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3616]
https://git.door43.org/toddlprice/rmr-x-bsa_mat_text_ulb
![image](https://user-images.githubusercontent.com/8171759/34613923-40bb4e58-f1f5-11e7-9199-63fc98f4e628.png)
Same problem in 0.8.1-alpha.13-65c49d1

**Comment by cckozie** [comment]
In 0.8.1-alpha.15-b862dfd I sometimes get the invalid project message and sometimes it just generates console errors with no error message but it does not import but remains in the imports folder.

**Comment by cckozie** [comment]
The problem still exists in 0.8.1-alpha.24-ffc2bed 
There is no user warning that the import was not successful
The project remains in the import folder and does not show in the project list
![image](https://user-images.githubusercontent.com/8171759/37368918-98cc0488-26d5-11e8-81e9-40289cf2539b.png)

**Comment by elsylambert** [comment]
Retested in 2.0.0 (4b3ebee). similar to #5387 Error message does not show the reason of failure. Not seeing a blank screen Alert screen.
