### ISSUE TITLE
Add support for OT aligning

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#3617]
- [ ] (M) Add importing OT projects
- [x] (M) Render alignment boxes RTL  

![image](https://user-images.githubusercontent.com/13352518/37262421-0c597900-2571-11e8-8e49-437bcf9ab4f9.png)

**Comment by PhotoNomad0** [comment]
@benjore - looking at your screenshot, `1:1` is not clear on UHB which side the chapter number is on.  Typically in RTL support, the roman numerals are rendered in normal LTR within the overall RTL language.  For example this would be wrong in the case of UHB pane:

![screen shot 2018-11-14 at 4 30 56 pm](https://user-images.githubusercontent.com/14238574/48513838-e56a0080-e82a-11e8-9d11-6cf357273617.png)

Can you clarify?  

@cckozie

**Comment by benjore** [comment]
That is correct. LTR or RTL references should appear the same way, e.g. 1:2. The mock-up is incorrect.

**Comment by da1nerd** [comment]
The rtl rendering is covered by https://github.com/unfoldingWord-dev/translationCore/issues/3655

**Comment by da1nerd** [comment]
@PhotoNomad0 aren't  you working on importing OT projects? Should this issue be assigned to you?

**Comment by cckozie** [comment]
Tested in child issues
