### ISSUE TITLE
Alignment Tool: Retain grayed out word in wordbank for words that have already been used

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#3623]
![image](https://user-images.githubusercontent.com/13352518/34892118-a3a71a94-f79d-11e7-9ded-66ec77f8ba11.png)

**Comment by ChrisJarka** [comment]
Much better than just disappearing off of the list of words!

**Comment by benjore** [comment]
When fixing this one, please make sure that issue #2936 is considered.

**Comment by da1nerd** [comment]
@benjore I cannot complete this issue without some fundamental changes to tC core.
Currently a lot of the logic for wordAlignment is inside tC core.

I know what needs to be done to fix this and it is fairly straight forward, however I need to be sure it won't affect other things. It might be helpful to get a few of the other developers together so we can discuss what needs to change.

> Note: the issue has to do with information required for sorting the words in the list. I have them staying in the list right now, however they are all at the bottom.

**Comment by da1nerd** [comment]
Also, I could probably do the required refactoring and finish this issue in a day or two.

**Comment by da1nerd** [comment]
I just remembered we'll need certain information once we begin implementing MAP. This changes how I was imagining resolving this a little.

**Comment by da1nerd** [comment]
@benjore it turns out this issue is mildly influenced by #2258. So I'm going to use this opportunity to set the state for working on that issue. With #2258 in mind, I think I have a clear idea on how to display used words without making any breaking changes. If that needs to change I'll request a meeting.
