### ISSUE TITLE
UI Changes for Translation Correct, Nothing to Select

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#3629]
![image](https://user-images.githubusercontent.com/13352518/34441937-71ad3a74-ec84-11e7-8c68-9099a729fbb6.png)

![image](https://user-images.githubusercontent.com/13352518/34441942-7737449e-ec84-11e7-885a-e54410b400ad.png)

![image](https://user-images.githubusercontent.com/13352518/34441944-7bad424e-ec84-11e7-9155-91f2aedbbe7c.png)

![image](https://user-images.githubusercontent.com/13352518/34441950-8228f1a4-ec84-11e7-923f-2ab86a35c8fa.png)

**Comment by mannycolon** [comment]
Verified on b1cd66e
