### ISSUE TITLE
Project name shows as 'undefined' on Door43 project not found alert

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3646]
https://git.door43.org/Danjuma_Alfred_H/sw_tit_text_ulb
![image](https://user-images.githubusercontent.com/8171759/34799583-fbbcb028-f625-11e7-8911-12c2325a582f.png)

**Comment by elsylambert** [comment]
Retested in 2.0.0 (4b3ebee). This is the Alert displayed:
![image](https://user-images.githubusercontent.com/51806180/64913259-bc482400-d70a-11e9-9460-cd9a078ed345.png)

**Comment by cckozie** [comment]
Per above comment, this has been fixed and is still fixed in 2.2.0 (2375ae5)
