### ISSUE TITLE
Render alignment boxes for the Hebrew as RTL

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#3655]
![image](https://user-images.githubusercontent.com/13352518/46312461-bfdeab80-c58a-11e8-87f8-4ce3cf197de2.png)

- [x] The alignment boxes align right (for Hebrew)
- [x] The Hebrew text aligns right
- [x] If multiple Hebrew (RTL) words are added to the same alignment box, the first word needs to go on the right, and the second word on the left.

**Comment by PhotoNomad0** [comment]
Verified in https://tc-builds.door43.org/build/feature-mcleanb-4078/translationCore-win-x64-1.1.0-f7ddd78.setup.exe

**Comment by cckozie** [comment]
1.1.0 (e6a76d9) 
The alignment boxes for Hebrew are being rendered as RTL, but it looks like line feeds are being inserted into the boxes when words are merged.

![image](https://user-images.githubusercontent.com/8171759/49392970-a4f8f680-f6f5-11e8-9251-deede894fa8a.png)

![image](https://user-images.githubusercontent.com/8171759/49393022-c2c65b80-f6f5-11e8-989a-d30161af76b7.png)

![image](https://user-images.githubusercontent.com/8171759/49393118-fa350800-f6f5-11e8-8fcf-6ea7d95b1acb.png)

**Comment by neutrinog** [comment]
@cckozie please provide the book, chapter, and verse to replicate.

**Comment by da1nerd** [comment]
@cckozie how are you even loading Genesis? The tools won't allow me to open it.

**Comment by cckozie** [comment]
@neutrinog You need to download the Hebrew content. It is not yet bundled in the build.

**Comment by da1nerd** [comment]
I added a fix for this in https://github.com/translationCoreApps/wordAlignment/pull/106

**Comment by cckozie** [comment]
Can't test until #5543 is fixed.

**Comment by cckozie** [comment]
Works in 1.1.0 (4d06842)
