### ISSUE TITLE
Search for Update (for tC)

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#3662]
Note: Could possibly be implemented to update content as well as the app ( #3175 ).

**Comment by da1nerd** [comment]
@jag3773 @benjore 
Hashing out some of the requirements here...

### The first requirement is clear from the title of this issue.
1. allow users to check if an update for the app is available.

### Once an update is identified how do you want to proceed?
1. user clicks on a button which opens the download page in their browser.
2. user clicks on a button to download the app
  * a progress dialog is shown (with cancel button)
  * once complete they click ok and are shown where the installer is.
3. user clicks download and it is automatically downloaded and installed (only applicable for Windows).

For starters I'd suggest making the user manually run the installer. I've set up auto installers before and the infrastructure can get very complicated. Electron has some support in this area, but it's definitely not a drag and drop solution. Besides all that, it would only be of benefit on windows. So I think any sort of auto installer would be a waste of time.

**Comment by jag3773** [comment]
@benjore and I prefer option 2 all things considered.

**Comment by benjore** [comment]
![image](https://user-images.githubusercontent.com/13352518/35885257-e96cb9b2-0b52-11e8-8952-14ef89716a3e.png)

![image](https://user-images.githubusercontent.com/13352518/35885264-ef280078-0b52-11e8-981d-81b71df5c231.png)

![image](https://user-images.githubusercontent.com/13352518/35885277-f96e31ce-0b52-11e8-9d40-2442239b2116.png)

![image](https://user-images.githubusercontent.com/13352518/35885287-ffd054e8-0b52-11e8-9a49-5ee714cefa4d.png)

![image](https://user-images.githubusercontent.com/13352518/35885312-111da656-0b53-11e8-90d1-f7e861efdead.png)

![image](https://user-images.githubusercontent.com/13352518/35885320-1693f5ea-0b53-11e8-9fa7-117554c20e5b.png)

![image](https://user-images.githubusercontent.com/13352518/35885326-1ad3d0b2-0b53-11e8-8c5b-2be7537222d4.png)

**Comment by da1nerd** [comment]
search here for the latest update https://github.com/unfoldingWord-dev/translationCore/releases

**Comment by cckozie** [comment]
@RoyalSix Why did you close this issue?

**Comment by cckozie** [comment]
I will need a build posted on the tC releases page in order to test this.

**Comment by cckozie** [comment]
Every Internet action requires displaying and processing this alert unless the Do not show again box has previously been check for the user's session.
![image](https://user-images.githubusercontent.com/8171759/38337211-001bd1d0-382a-11e8-9d97-52d53ab18940.png)

**Comment by cckozie** [comment]
The problem of not showing the Internet warning has been fixed, but I still have no way to test the function.

**Comment by cckozie** [comment]
https://git.door43.org/qa91/es-419_tit_ulb
The fix has introduced a different problem with missing verses. Now with this project, the missing verses screen is displayed twice; first directly following the "importing" alert, and the second following the "loading your project" alert. The second time it is displayed the Continue button is disabled.
With the previous build this problem did not occur.
First display of missing verses screen:
![image](https://user-images.githubusercontent.com/8171759/39377397-9b6dbff2-4a1a-11e8-953d-9c3d6b214db1.png)

Second display of missing verses screen:
![image](https://user-images.githubusercontent.com/8171759/39377249-125b6ec6-4a1a-11e8-8d29-089b764ccc6c.png)

**Comment by cckozie** [comment]
Tested on 0.9.0 after 0.9.1 was released.

**Comment by cckozie** [comment]
This works in some cases but not all.
1. On my Windows 64 machine:
If the download file does not exist on the local machine, it all works well.
If the download file does exist on the local machine and I choose the replace option, the download runs as expected, but when the download is complete (as indicated by the % complete progress bar), it sits on that screen for another 75 seconds before setting focus on the Explorer window. Since there is no indication that anything is happening, the user will be tempted to think the app is broken and cancel the import.

2. On my Windows 32 machine it is worse when the download file already exists. After the progress bar indicates completion of the download, the blue progress bar goes back to gray even though it still indicates 0/82MB remaining. Then after waiting more than 10 minutes for it to actually complete and remove the downloading alert and set focus to Explorer, I gave up waiting.

This problem does not exist on my Mac.

**Comment by jag3773** [comment]
Confirming that it works as expected on Linux Mint 18.

**Comment by da1nerd** [comment]
@cckozie I cannot reproduce this error on windows 64bit and I do not have a 32 bit machine.
I am using windows 10.

The download finishes correctly and quickly whether or not the file already exists.

**Comment by da1nerd** [comment]
The only think I can think of is a process was still using the file that was already downloaded so it was blocking the new download. If you still encounter this error make sure no processes are accessing the existing file.

**Comment by cckozie** [comment]
I'm closing this until there is evidence that we need 32 bit support
