### ISSUE TITLE
Cannot import a USFM project that has an invalid id tag (unrecognized book)

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3667]
If a USFM file has a unrecognized book identifier, the user should be able to fix it on the project information screen. 
Currently the user is prevented by doing such and the following message is displayed:
![image](https://user-images.githubusercontent.com/8171759/35069075-14b9348a-fba7-11e7-9ea6-b3cb1dde27b1.png)

**Comment by benjore** [comment]
Related to #3608

**Comment by cckozie** [comment]
Fixed in v0.9
