### ISSUE TITLE
Console errors when opening the first project after install (Windows 64bit)

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3688]
0.8.1-alpha.14-1820928 
Console errors in tW on Windows
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/a569ffcf-6662-47e1-814f-c3b00bb83fca)
I did not see any errors when opening the same project in Word Alignment. I did not see the errors when opening the project in alignment the second time, or on other projects in either tool.  Looks like a first project/tool only bug.

**Comment by PhotoNomad0** [comment]
@cckozie @mannycolon - I am not seeing this with latest dev build.

**Comment by cckozie** [comment]
Not seeing in 0.8.1-alpha.14-d4966fa
