### ISSUE TITLE
User name, project name, and tool name disappear from menu  bar

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3697]
0.8.1-alpha.15-b862dfd
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/0f10582e-122b-4742-a008-19477ec3e35a)
The reappear when hovering over the menu bar.
This happens randomly in alignment when dragging words back to the word list. Sometimes as you begin dragging the word, the text in the menu bar flashes one or more times. Then occasionally when the word is dropped in the word list the menu bar text stays hidden.
I'm assuming this is a React 16 issue since I've never seen it before.

**Comment by RoyalSix** [comment]
Is this a duplicate of 3698? @cckozie

**Comment by RoyalSix** [comment]
Is this a duplicate of #3698? @cckozie

**Comment by cckozie** [comment]
Yes.

**Comment by cckozie** [comment]
This was not able to be fixed because the devs were not able to replicate it, but it is still a problem. Maybe can find a fix in the future. Fix attempt was made on #3698

**Comment by cckozie** [comment]
This appears to have been fixed
