### ISSUE TITLE
Intermittent text in menu bar

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#3698]
0.8.1-alpha.15-b862dfd
The issue above still exists, and now I see another one on the Mac.
The text on the menu bar sometimes disappears.
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/0f10582e-122b-4742-a008-19477ec3e35a)
The text reappears when hovering over the menu bar.
This happens randomly in alignment when dragging words back to the word list. Sometimes as you begin dragging the word, the text in the menu bar flashes one or more times. Then occasionally when the word is dropped in the word list, the menu bar text stays hidden.
I'm assuming this is a React 16 issue since I've never seen it before.

**Comment by benjore** [comment]
Note: the intermittent text in the menu bar is covered in #3698 .

**Comment by RoyalSix** [comment]
@cckozie Me and @richmahn are not able to reproduce the problem, tried different variations as well. 
Are you able to reproduce still? If so are there more steps not outlined here? Thanks

**Comment by cckozie** [comment]
@RoyalSix It is a Mac only problem. Yes, it does still occur in 0.8.1-alpha.15-b862dfd. This is the project I'm using. Open it in alignment tool and drag aligned words back to the word list. Try dragging them slowly and fast. I saw the error this time on the third word I dragged.
[English_tit.zip](https://github.com/unfoldingWord-dev/translationCore/files/1679839/English_tit.zip)

**Comment by cckozie** [comment]
It may be slightly better in 0.8.1-alpha.15-53e1b0c, but I am still able to create the problem. I'm going to reopen the dup issue and through it in the backlog.
