### ISSUE TITLE
Address why an empty authorization file still permits api calls

### ISSUE THREAD

**Issue by EllDoubleYew** [unfoldingWord/translationCore#37]
As a translation core developer I want to know why an empty .auth file still allows me to pull data from git/gogs so that I know if I can start working towards removing it completely.

**Comment by RoyalSix** [comment]
So i ran a few test with some python scripts and found the following information:
1. GitHub was serious when they said you have a limit of 60 unauthenticated api calls.
2. The auth token cannot have spaces in the call ie. "access_token = 12345ROYALSIX789" is different from "access_token=12345ROYALSIX789" (I already made the change in slack)
3. Our access token is authenticated for 1000 api calls per hour
:+1:
