### ISSUE TITLE
Setup JSDOC with ReadTheDocs

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/translationCore#3700]
We will attempt to use sphinx-js (described here: https://hacks.mozilla.org/2017/07/introducing-sphinx-js-a-better-way-to-document-large-javascript-projects/), which uses http://usejsdoc.org under the hood.

**Comment by jag3773** [comment]
This is not completed yet.

@neutrinog ReadtheDocs does support mkdocs, would something like https://github.com/Degree53/doxdown do what we need for deployment?

**Comment by da1nerd** [comment]
I'll check it out.

**Comment by da1nerd** [comment]
@jag3773 I checked out that library. It's very brittle. I ran it and it choked on a bunch of  "syntax errors". It apparently can't read jsdoc very well.

Also, the error output gives no hint as to where the error occurred. So it would be incredibly painful to normalize all the doc strings. 

e.g.

```
doxdown -s src/js -o dox

/home/joel/.config/yarn/global/node_modules/jsdoctypeparser/lib/index.js:53
          throw new Lexer.SyntaxError(e.message, typeExp, e.offset);
          ^
TypeLexerSyntaxError: Expected "!", "(", "*", "...", "=", "?", "function", "module", "{" or [a-zA-Z_$] but end of input found.:

^
```

> Edit: I think it could work, but a dependency of a dependency is out of date and is not being maintained.
