### ISSUE TITLE
[0] Update USFM Import to support VerseObjects from USFM.js 

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#3724]
Looks like even though USFM.js VOs was mapped to verse strings, there’s an error during the import. 
`/Volumes/Github Workspace/translationCore/src/js/actions/Import/LocalImportWorkflowActions.js:67`
```Error: Objects are not valid as a React child (found: TypeError: verseParts.join is not a function). If you meant to render a collection of children, use an array instead.```

**Comment by PhotoNomad0** [comment]
Is this the task to use VOs in project json instead of strings?  If so, then maybe we need to make this an issue.

**Comment by klappy** [comment]
This task is to ensure that the VOs from the USFM.js library get converted to strings like they have been prior to the change to VOs.
