### ISSUE TITLE
0] Schedule & Meet with Joel to do the "hand-off" of the UI Localization & builds

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#3730]

**Comment by benjore** [comment]
@mannycolon Can you head this up? Maybe get a couple more people to join you and set up a time when it works for all of you to meet with Joel to hand this off. Thanks!

**Comment by mannycolon** [comment]
@benjore Ok, no problem.

**Comment by klappy** [comment]
Can we close this task now?

**Comment by richmahn** [comment]
No response and I'd say we can close, so closing.
