### ISSUE TITLE
Missing verses screen appears before license screen and non-missing verses reported as missing  on USFM import

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3732]
0.8.1-alpha.15-ab5cb00 
This is repeatable following these steps.
1. Import  [php_usfm_NId.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/1683207/php_usfm_NId.usfm.zip) and click OK when you get the invalid USFM project Alert.
2. Import [php_usfm_badId.txt.zip](https://github.com/unfoldingWord-dev/translationCore/files/1683212/php_usfm_badId.txt.zip), choose CC-BY-SA as the license, choose 'Philippians' as the book and 'pt-br' as the language code. 
4. Launch the project with tW, then click on the project icon in the menu bar to return to the projects page.
3. Import [en-x-demo1_php_text_reg.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/1683220/en-x-demo1_php_text_reg.usfm.zip). Notice that the Missing Verses page comes up and it looks like all of the verses are missing. Click OK and notice that the License page now comes up.

That third file does not have any missing verses, but does one merge conflict.
I'm guessing this might have to do with the fact that the import of the first file ends early because we don't recognize it as a valid USFM file. It may be that we're not fully cleaning up after the abend.

**Comment by elsylambert** [comment]
Retested in 2.0.0 (4b3ebee). Not seeing this issue. Step 4. after import file, License screen comes up followed by Merge conflicts screen. Not seeing missing verses.
