### ISSUE TITLE
[0] Auto-export alignment data on Door43 upload, file chooser for normal export

### ISSUE THREAD

**Issue by RoyalSix** [unfoldingWord/translationCore#3733]

**Comment by RoyalSix** [comment]
@cckozie @benjore Since we are auto generating the users alignments when they upload to door43, should we alert the user this is happening? It could go right before the ```Uploading {projectName} to Door43. Please wait...``` alert. 
Thoughts?

**Comment by cckozie** [comment]
@RoyalSix I don't think it's necessary. I would expect most users will assume that we're uploading all of the project data.
