### ISSUE TITLE
Show occurrence number for language being aligned

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#3740]
## User Story

As an aligner, I want to know the occurrence order of duplicate words so that I can get them in the correct order & easily identify which is which.

**Comment by jag3773** [comment]
Note, Perry suggested a superscript number on the words.

**Comment by benjore** [comment]
![image](https://user-images.githubusercontent.com/13352518/35824003-01508964-0a77-11e8-9850-1d714524176d.png)

Superscript `1` aligned right.

**Comment by cckozie** [comment]
Occurrence numbers should only be displayed for the language being aligned, not for the Greek.

**Comment by da1nerd** [comment]
@cckozie the numbers have been removed from the Greek in https://github.com/translationCoreApps/wordAlignment/pull/27
