### ISSUE TITLE
Internet warning error bug introduced in 0.8.1-alpha.15-0452b15

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3743]
When logging in to a door43 account, the "You are about to transmit data..." Alert is display as usual. However, when the "Do not show...again" checkbox is checked, the check does not show up but the alert box flashes and stays unchecked as it was. This worked properly in the previous build.
Even though in the alert the box was unchecked, after clicking Access Internet the app behaves as though the "Do not show...again" box was checked.

**Comment by RoyalSix** [comment]
# Tasks
- [ ] [3] Internet warning bug: Debug Checkbox for data submission
