### ISSUE TITLE
Pop-over for `AT`

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#3745]
## User stories

As a user I want understand what `AT` means so I can know how best to check my translation. 

## Specs

- Underline `AT` as if it were a hyperlink
- Create a pop-over when `AT` shows up in the tN check info card (blue card) that says "Alternate Translation"

![image](https://user-images.githubusercontent.com/13352518/35824790-98566d5e-0a79-11e8-9c6f-7dc5490c41de.png)

![image](https://user-images.githubusercontent.com/13352518/35824805-a9d0c5b6-0a79-11e8-957a-47ea653a5fc2.png)

**Comment by benjore** [comment]
@jag3773 Are there any other abbreviations we should do this for?

**Comment by benjore** [comment]
Content team will fix this by changing `AT` to `Alternate Translation` in the text.

**Comment by jag3773** [comment]
See https://git.door43.org/Door43/en_tn/issues/908 .
