### ISSUE TITLE
Localized User Interface UI

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#3750]
![image](https://user-images.githubusercontent.com/13352518/35886657-69b572e0-0b57-11e8-99fc-ee5eea8824ce.png)

![image](https://user-images.githubusercontent.com/13352518/35886666-7286561e-0b57-11e8-96b3-ccaf4eb5e358.png)

![image](https://user-images.githubusercontent.com/13352518/35886672-781c1da2-0b57-11e8-8e12-d439055f18b6.png)

![image](https://user-images.githubusercontent.com/13352518/35886681-7d8c27fa-0b57-11e8-91a6-62820278db53.png)

**Comment by da1nerd** [comment]
This is done. just need to prepare a PR

**Comment by cckozie** [comment]
1. The spacing of the text "I have read..." is messed up
2. The dropdown box is not the standard one that appears in other  places in tC. See example in bottom image.
![image](https://user-images.githubusercontent.com/8171759/37042885-f4e2eedc-2124-11e8-94bd-222ef0b35ff8.png)

![image](https://user-images.githubusercontent.com/8171759/37042987-32ad7b42-2125-11e8-9b1a-ae301df9dcbb.png)
