### ISSUE TITLE
Fix issues with USFM3 alignment export

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#3756]
See a couple problems still with USFM3 alignment export:

* verse markers are not at beginning of line 
* unaligned chapters are not included in the output

**Comment by PhotoNomad0** [comment]
See a couple problems still with USFM3 alignment export:
* verse markers are not at beginning of line 
* unaligned chapters are not included in the output

**Comment by PhotoNomad0** [comment]
Note that the first item is also broken in USFM export.

**Comment by PhotoNomad0** [comment]
#### Tasks:
- [x] [4] add output of non aligned chapters
- [x] [4] update unit tests
- [ ] [4] PR Review

**Comment by PhotoNomad0** [comment]
fixing ID tag format to be:

TIT EN_ULB Kiswahili_sw_ltr Wed Jul 26 2017 22:14:55 GMT-0700 (PDT) tc

**Comment by PhotoNomad0** [comment]
Fixed in two PRs:
`verse markers are not at beginning of line` fixed in: https://github.com/translationCoreApps/usfm-js/pull/33
`unaligned chapters are not included in the output` fixed in https://github.com/unfoldingWord-dev/translationCore/pull/3868

**Comment by cckozie** [comment]
@benjore @jag3773 In unaligned verses, sometimes multiple words show up on the same line. Is that an issue we care about? (See lines 1615 and 1617 below)
![image](https://user-images.githubusercontent.com/8171759/36446339-a2390984-1646-11e8-8b96-acb2026838c7.png)
[English_tit.zip](https://github.com/unfoldingWord-dev/translationCore/files/1741672/English_tit.zip)
[57-TIT_3.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/1741676/57-TIT_3.usfm.zip)

**Comment by cckozie** [comment]
Waiting for input from @jag3773 on whether multiple words per line is acceptable.

**Comment by cckozie** [comment]
@mannycolon Why did you close this issue?

**Comment by cckozie** [comment]
Need to have only 1 word per line in the USFM3 exported file.

**Comment by PhotoNomad0** [comment]
@jag3773 @benjore @cckozie - Sounds like design by complaint here.  There is no formatting spec here, just preference?

**Comment by jag3773** [comment]
@PhotoNomad0 One word per line.  See the example at http://resource-container.readthedocs.io/en/ubxf/ubxf.html .

**Comment by jag3773** [comment]
To be clear, I'm expecting that the input USFM file of the UGNT could be exported and that the exported file would yield the same thing I imported.

[Titus 3:8](https://git.door43.org/Door43/UGNT/src/branch/master/57-TIT.usfm#L659) is a good test case, I think, for this.  Notice there is an [opening quote](https://git.door43.org/Door43/UGNT/src/branch/master/57-TIT.usfm#L670) and [closing quote](https://git.door43.org/Door43/UGNT/src/branch/master/57-TIT.usfm#L677) in that verse and other punctuation as well.

**Comment by PhotoNomad0** [comment]
> To be clear, I'm expecting that the input USFM file of the UGNT could be exported and that the exported file would yield the same thing I imported.

@jag3773 @benjore @cckozie @klappy  - Here is part of the problem with using an example in place of a spec (especially one that is significantly hand edited): the current examples (UGNT) have lots of inconsistencies of white space in milestone and word tags.  So to make export and import identical will not be possible without significant redesign of USFM import/export and tc storage to preserve spacing within the milestone and word markers.  If we add an exception for white space within these markers we can meet this requirement.  

Also note there are two different double quotes currently being used (", “), and many others possible in Unicode spec.

**Comment by cckozie** [comment]
I agree that we need to be more clear and specific in such situations. Currently when comparing the imported vs exported file I have been ignoring white space, differences in the actual quote characters (as long as they were similarly single or double) , and whether or not there were verse markers for blank verses. I'm quite sure that I do not understand the full impact of such differences, so it would be helpful for all of us to have a spec defining the details of what is needed/expected.

**Comment by jag3773** [comment]
@PhotoNomad0 Are we in better shape now that https://git.door43.org/Door43/UGNT/pulls/55 is merged?  My main concern is consistency.  If we can get a reproducible conversion that is lossless then I'll be happy.

Also, anything we can do to make the UGNT formatting more consistent will help everyone.

**Comment by PhotoNomad0** [comment]
@jag3773 - am pulling the UGNT fixes in on another issue.

**Comment by cckozie** [comment]
Looks much better and easier to read now. All verse markers have their own line. All words have their own line. No more \zaln-e\*,\zaln-s | on the same line.
