### ISSUE TITLE
Spike: List biggest ROI Tests

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#376]

**Comment by ihoegen** [comment]
In my opinion, we should begin this with going over our old test, and making sure that we are testing for error catching as well. Non-happy-path testing is something that would be important to the application. 
So below is an outline of how this should go:

- ~~ModuleAPI~~
    - NHP tests were already integrated, but should be separated from the HP tests, so confusion can be averted. 
- ~~LoadOnline~~
    - NHP tests were integrated, but we should continue with them, possibly trying .git extensions that aren't real. 
- ~~PackageManager~~
    - Since package manager relies heavily on callbacks, we should test for null callbacks. 
    - Also, strings tend to be the favorite type of input, so we should test against other forms of input for the functions as well.
- ~~Upload~~
    - All functions need NHP test for invalid data types.
- ~~ImportUsfm~~
    - Most functions have NHP tests, they just need to be separated out for readability. 
- ~~CoreActions~~
    - This is a tough one to do NHP tests, because it can pretty much work no matter what. However, we could try null callbacks. 
- AccessProject
    - Lot's of potential for NHP tests with this one, mostly because we can try tons of combinations of 
- CheckDataGrabber 
    - Can try with invalid modules that aren't installed

Now on to tests that need to be implemented, that are yet to

- ~~ReportGenerator~~ 
    - Let's try writing tests for this, along with the ReportFilters functions.
- ProjectManifest
    - This defines translationCore projects, and we should make sure this holds consistent. 

And that is it, for what isn't a React Component.

**Comment by RoyalSix** [comment]
Sounds good, I'll keep what I'm working on in the "in progress" section so we can not butt heads  :)

**Comment by RoyalSix** [comment]
I ran across react-addons-test-utils. It looks like it would be super useful for our project. Will be posting more about this later.
