### ISSUE TITLE
Localized UI

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#3765]

**Comment by jag3773** [comment]
Isn't this a duplicate of https://github.com/unfoldingWord-dev/translationCore/issues/2003 ?

**Comment by benjore** [comment]
@jag3773 Yes, but #2003 doesn't show up on the roadmap. For a quick workaround for our meeting, I added this one. 

In a perfect world, roadmap stories that are progressing through the "Work-in-Progress" pipelines would show up on the roadmap.

**Comment by PhotoNomad0** [comment]
@benjore - what remains to be done here that isn't in https://github.com/unfoldingWord-dev/translationCore/issues/4125?

**Comment by benjore** [comment]
This is only a placeholder for the Roadmap label.
