### ISSUE TITLE
App crashes when opening expanded scripture pane

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3770]
Introduced in Version 0.8.1-alpha.15
[53-1TH.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/1717355/53-1TH.usfm.zip)
Import and load with tW
Click on "body, bodies" in the menu
Expand the main scripture pane
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/1f05416f-067b-49b0-9c30-5254ba094bc0)

**Comment by richmahn** [comment]
- [ ] [2] Fix QA Fail for App Crashing when opening expanded scripture pane

**Comment by cckozie** [comment]
Not seeing the problem anymore in 0.8.1-alpha.16-2079663.
