### ISSUE TITLE
All USFM markers (including \p & \s) & punctuation need to be preserved in USFM3 export

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#3808]
As a user, I want all USFM markers & punctuation to be preserved on USFM3 export so that I do not get the impression that tC is losing data. 

## Notes: 
- [ ] When complete, the round trip (import-export-import) needs to work.

**Comment by benjore** [comment]
This may be a dup of #3780

**Comment by benjore** [comment]
@jag3773 Should the USFM3 preserve all the markers + alignment data, or is it just the alignment data?

**Comment by jag3773** [comment]
Yes, any inbound USFM markers should be preserved.

**Comment by PhotoNomad0** [comment]
I think this may be finished already.

**Comment by benjore** [comment]
@cckozie Can you verify if this is completed or not?

**Comment by cckozie** [comment]
@benjore USFM3 export is still broken. I will let you know once I've been able to test.

**Comment by cckozie** [comment]
Waiting on #3185
