### ISSUE TITLE
[0] Write JSdocs ensure Sphinx builds for 3656

### ISSUE THREAD

**Issue by bspidel** [unfoldingWord/translationCore#3830]
@benjore Please review

The purpose of this feature is to display where possible, booknames in the preferred language of the translator.

When translating to a target language (OL) from a Gateway Language (GL) and Greek manuscript the booknames will occur in 3 languages 
  [Greek]   [Gateway]   [Target]
up till now the Target has always been English. 
There is another language set as the "Locale" which is the preferred language of the user.
Going forward the target language will be that displayed in the project manifest or English if the locale does not match the target language.

---

The iplementation of this feature is separated into 2 parts: 

1. The first is to ensure that the tartget language name is placed into the project manifest from the USFM project at project import during conversion to a tC project

1. make use of the translated name when it matches the user's locale. There are five places where this can occur.

   1. Check pane
   1. Title of Expanded Scripture Pane
   1. Title of Expanded Checking Pane
   1. Project panel in the Home Screen
   1. Side Menu

**Comment by benjore** [comment]
The Greek book name shouldn't show up. 

The first preference is that the Book name be in the target language. If that is not available, then use the book name in the GL. If that is not available, then use the book name in English. 

So order of preference: Target > GL > English.
