### ISSUE TITLE
Footnotes in a verse cause selection problems

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3853]
## User Story

As a checker, I want to be able to complete a check on a verse that has a footnote so that I am able to complete checking my entire translation and not just verses with no footnotes.

This is probably a result of work on #3190 and it should have been caught there.
53-1TH.usfm.zip
Import this project and open it with tW.
Click on the "brother, brothers" menu option
In verse 3:2 double click the word brother, then click Save
You will receive the "Some selections are invalid..." message and will not be able to save the selection. No errors in the console.

**Comment by PhotoNomad0** [comment]
This looks like a different issue than #5051

**Comment by da1nerd** [comment]
@cckozie do you still have this project? It's not attached to this issue.

**Comment by da1nerd** [comment]
I found the project to test. 
This appears to be resolved.

**Comment by cckozie** [comment]
Works in 1.1.0 (edc48cb)
