### ISSUE TITLE
Lexicon data not showing in scripture pane popovers in tW

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3862]
In tW:
![image](https://user-images.githubusercontent.com/8171759/36319660-3bc380de-1309-11e8-9d93-513abb800e2c.png)

In Alignment:
![image](https://user-images.githubusercontent.com/8171759/36319516-c120d3f4-1308-11e8-9893-643e19b4a6c5.png)

**Comment by cckozie** [comment]
Looks like this may have been fixed in 0.8.1-alpha.21-320865f

**Comment by PhotoNomad0** [comment]
#### Tasks:
- [ ] [4] Fix ScripturePane initialization to load strong's numbers
- [ ] [4] Update unit test
- [ ] [4] PR Review

**Comment by mannycolon** [comment]
@PhotoNomad0 Did I address this issue in 4025?
