### ISSUE TITLE
VerseCheck: "Select Translation for" Gateway Text Aligned with UGNT Quote

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#3864]
## Specs: 
- This covers selection instructions. This is currently Greek and needs to be the GL translation. 

## Note: 
- The title of the check shows up in three places (side menu, check info card, tHelps)
- The GL word/phrase being checked shows up in two places (highlighted in the Scripture Pane, spelled out in the check card)
- The Greek word/phrase being checked should be highlighted, but should not appear anywhere else.
- Once selected and the user clicks `Save`, the Target Language selection should show up 4 places (spelled out in the side menu, highlighted in the left side of the check card, spelled out in the right side of the check card, highlighted in the Scripture Pane)

![image](https://user-images.githubusercontent.com/13352518/36269458-db48e0ac-123e-11e8-9d9c-059737a2e432.png)

![image](https://user-images.githubusercontent.com/13352518/36269435-d148e8b8-123e-11e8-8e5e-335adf5c6c7a.png)

Related to #3863

**Comment by richmahn** [comment]
@RoyalSix I assume you know this or will easily figure it out, but the selected gateway language is easily found through `projectDetailsReducer.currentProjectToolSelectedGL[<tool name>]`. Tool Cards should automatically populate this for their given tool with `en` when they are constructed.

**Comment by RoyalSix** [comment]
# Tasks
- [ ] [2] Get the GL word/phrase from the reducer to populate verse check
- [ ] [1] PR Review
