### ISSUE TITLE
Bug: UGNT Milestones causing words missing from Word Alignment

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#3867]
I found a bug that was introduced weeks ago but just came across it. It appears that when we imported the tW tagged greek. It included milestones in the UGNT that appear to be excluded from the greek words in the alignment. For example, Titus 1:1, has the greek words for Jesus Christ that are missing from the Word Alignment tool. 

It looks like we need to update the logic that generates the topWords in the Alignment, to support the new data structure. It needs to iterate through the milestones and use the verseObjects of type word in the children attribute of the milestones.

Changes will likely need to be performed in the function `generateBlankAlignments()` in the file `WordAlignmentLoadActions.js:120`.

**Comment by PhotoNomad0** [comment]
#### Tasks:
- [x] [8] Fix alignments logic
- [x] [8] Unit Tests
- [x] [4] PR Reviews

**Comment by cckozie** [comment]
@klappy I see that there are still 4 tasks with time remaining related to this issue. Is it really ready for testing?

**Comment by PhotoNomad0** [comment]
@cckozie - Ready

**Comment by cckozie** [comment]
@klappy @PhotoNomad0 Wondering what is the correct way to test that this has been fixed. I imported the aligned en-tit from d43. What I'm seeing in Word Alignment and tW seem to agree for Jesus Christ in 1:1. Is that evidence that this has been fixed? Are there other or better ways to test it? Would a thorough comparison of everything in Titus be a solid indicator? Is there any easier way? Could I test it pragmatically by comparing the data in a USFM3 export with the data in the tw resource?

![wa](https://user-images.githubusercontent.com/8171759/36561132-75e26b44-17d8-11e8-86ef-bf6482b55675.png)
![tw](https://user-images.githubusercontent.com/8171759/36561138-79d2a322-17d8-11e8-9f78-d08b85522015.png)

**Comment by klappy** [comment]
@cckozie: The easiest way to test this is to load a new project that has not been aligned and ensure that the greek words for "jesus" and "christ" are in the greek boxes ready to be aligned. Previously those words when found together were tagged for tW with a milestone that had them nested, and didn't show up in a new project's alignment tool.

**Comment by cckozie** [comment]
Looks good per Klappy's suggestion on testing.
