### ISSUE TITLE
Localize tC Apps

### ISSUE THREAD

**Issue by da1nerd** [unfoldingWord/translationCore#3891]
Now that tC core is localized (https://github.com/unfoldingWord-dev/translationCore/issues/3750) we need to support localizing the apps/tools.

- [x] define interface for apps checking which locale is selected
- [x] set up locale in apps.

We will localize:

* [x] wordAlignment
* [x] translationWords

**Comment by da1nerd** [comment]
I created a new npm module that acts like an interface between tC core and the tools.
https://github.com/translationCoreApps/tc-tool

**Comment by da1nerd** [comment]
translationWords is done as well, however I need to update tc-tool so it defaults to english instead of crashing if the selected language isn't found.

**Comment by da1nerd** [comment]
This is all done once the two PR's are merged in!

**Comment by cckozie** [comment]
I'm holding all of the localization issues until all of the related issues have made it to QA.

**Comment by da1nerd** [comment]
@cckozie I realized I still need to create crowdin projects for the tools so we can receive the latest locale structure when updates come into the repo.

**Comment by cckozie** [comment]
Passing all held localization issues with remaining problems in newer issues.
