### ISSUE TITLE
The Project Information page is displayed with all of the fields blank momentarily after the Continue button on it is clicked

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3893]
After completing all of the fields on the project info page and then clicking Continue, all of the fields are cleared and the page is redisplayed momentarily before continuing in the validation stepper.
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/27113189-5ca6-40cd-9cf4-3b12ea954c34)

**Comment by elsylambert** [comment]
Retested in 2.0.0 (4b3ebee). Not seeing this issue.
