### ISSUE TITLE
Bugfix: Restore keyterm (\k) milestone support in resources.

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#3896]
Fixes are in two PRs: 
- https://github.com/translationCoreApps/usfm-js/pull/34
- https://github.com/translationCoreApps/tC_Resources/pull/22

**Comment by cckozie** [comment]
@PhotoNomad0 Is there anything I can test to see if this was actually done?

**Comment by PhotoNomad0** [comment]
Quickest way would be to check ugnt resource files, json.  Should not see zaln in them. Nothing is exposed in app.

**Comment by cckozie** [comment]
OK, I'm seeing them in the ugnt bible.
