### ISSUE TITLE
Alignment Tool: Able to put Target Language out of order

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#3899]
![image.png](https://images.zenhubusercontent.com/55e5f3984f7a08fbb7f4a658/6d63798f-fdc0-44a7-bf0c-2786b32f300a)

See "God for" and "man the" instead of "for God" and "the man". 

Project: https://git.door43.org/Door43/en_ulb/src/branch/ulb_alignment

**Comment by benjore** [comment]
https://git.door43.org/lrsallee/en_1ti

Note: Larry had this problem with 0.8.1. I'm using translationCore 0.8.1-alpha.16-2079663 and imported his project. The words started out of order but once I dragged them back into the wordbank, I can't get them out of order.

**Comment by benjore** [comment]
<img width="1440" alt="screen shot 2018-04-19 at 5 23 05 pm" src="https://user-images.githubusercontent.com/13352518/39021469-7eb94414-43f6-11e8-9117-3a0671abaf07.png">

Notice first word, second row. `of` and `the` are in the wrong order.

**Comment by da1nerd** [comment]
@benjore just to clarify. Are you requesting that users be able to align target language words out of their original order? Or do you want to always enforce they are in the expected order?

**Comment by da1nerd** [comment]
ok I just realized this issue was created early this year. Since then the wA has been completely changed and I believe this issue resolved.
At first glance I thought you wanted to keep the order in which the words were added to alignments instead of sorting them according to their appearance in the target verse.

**Comment by cckozie** [comment]
This has been fixed in 0.10
