### ISSUE TITLE
Create an Alpha Release for review by the English & Hindi Content Teams

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#3924]
- [ ] Only for Titus. 
- [ ] label release as 0.9alpha

Purpose: so the content teams can verify that the text is being displayed correctly in the tW tool.

Follow instructions in our [Docs](https://docs.google.com/document/d/1-dJvDrxjIYwiUKUnH-E8qZel-DCDhsgM8iR-n9Cm57w/edit#heading=h.kwwwpmel1ulv) for the release.

**Comment by jag3773** [comment]
I added "- [ ] label release as 0.9alpha"
