### ISSUE TITLE
Scripture Pane Does not render nested milestone for the ULB

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#3925]
See problem that ULB words within nested milestones are not shown in Scripture Pane.  For example In Titus 1:5 in the English ULB (Gateway Language) the words "things not yet complete" are not displayed

**Comment by PhotoNomad0** [comment]
![missing text](https://user-images.githubusercontent.com/14238574/36801949-632c9120-1c81-11e8-962c-2a5af51e7926.png)
 Here is what is missing: text circled on left is not shown on right pane.

**Comment by PhotoNomad0** [comment]
But the words are in the en ULB:

      {
        "tag": "zaln",
        "type": "milestone",
        "lemma": "ὁ",
        "morph": "Gr,RD,,,,ANP,",
        "occurrence": 1,
        "occurrences": 2,
        "strong": "G35880",
        "content": "τὰ",
        "children": [
          {
            "tag": "zaln",
            "type": "milestone",
            "lemma": "λείπω",
            "morph": "Gr,VIPPA,ANP,",
            "occurrence": 1,
            "occurrences": 1,
            "strong": "G30070",
            "content": "λείποντα",
            "children": [
              {
                "text": "things",
                "tag": "w",
                "type": "word",
                "occurrence": 1,
                "occurrences": 1
              },
              {
                "text": "not",
                "tag": "w",
                "type": "word",
                "occurrence": 1,
                "occurrences": 1
              },
              {
                "text": "yet",
                "tag": "w",
                "type": "word",
                "occurrence": 1,
                "occurrences": 1
              },
              {
                "text": "complete",
                "tag": "w",
                "type": "word",
                "occurrence": 1,
                "occurrences": 1
              }
            ]
          }
        ]
      },

**Comment by PhotoNomad0** [comment]
This is using WA in build translationCore 0.8.1-alpha.19-a71fdcb

**Comment by mannycolon** [comment]
@PhotoNomad0 thanks

**Comment by mannycolon** [comment]
### Updated list of checks missing highlighted word in ULB

- exhort, exhortation
Titus 2:15
- God
Titus 2:5
Titus 2:11
- godly, godliness
Titus 2:12
- grace, gracious
Titus 3:15
- Savior, savior
Titus 2:10
Titus 3:6
- testimony, testify
Titus 1:13
- word of God, words of God, word of Yahweh, word of the Lord, scripture, scriptures
Titus 2:5
- world, worldly
Titus 2:12

**Comment by mannycolon** [comment]
## List of checks that have the wrong word occurrence for the highlighted word in the ULB
- God
Titus 2:11
