### ISSUE TITLE
GL words aligned out of sequence

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3946]
0.8.1-alpha.19-a71fdcb
I aligned the words from the word list in sequence and got this result.
The noted words get out of sequence when aligned with the Greek.
![image](https://user-images.githubusercontent.com/8171759/36798287-cfb5294a-1c6f-11e8-800a-c83e28e9b82f.png)

**Comment by benjore** [comment]
@cckozie Did you verify that that was the correct `the` (since the word prior to `church of` is also `the`)?

**Comment by cckozie** [comment]
I did drag them in order from the word list and aligned them in sequence to the Greek. It looks to me like it is a bug in the alignment tool. 
Here is the corresponding section from the USFM3 export:
![image](https://user-images.githubusercontent.com/8171759/36802941-dc60e15a-1c7b-11e8-9ddd-302bde2e750b.png)
If I drag the misplaced "the" to align it with Θεσσαλονικέων instead of ἐκκλησίᾳ, then it does appear in the correct sequence.

**Comment by cckozie** [comment]
Blocked by #4439
