### ISSUE TITLE
Modify the Report Filters for the checkBoxes on proposed changes

### ISSUE THREAD

**Issue by ihoegen** [unfoldingWord/translationCore#396]
Report Filters needs an updating, because proposedChanges has an update that introduces a new check type, and removes the Retained/Replaced type. There may be other checks as well in the future, however, this is all for now.

**Comment by klappy** [comment]
Does this still need to be done?

**Comment by ihoegen** [comment]
Yes, the Retained/Replaced type has not been removed from Report Filters, and we still haven't added the new proposed changes types.
