### ISSUE TITLE
Alignments to EN ULB missing in tWords

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#3963]
![self-controlled](https://user-images.githubusercontent.com/14238574/36851751-fd141aa4-1d37-11e8-80cf-f7b9ae0b36b9.png)

Alignment to self-controlled not shown in tW

**Comment by PhotoNomad0** [comment]
The reason we are not getting highlighting for self-control is because In EN ULB it is aligned to "ἐνκρατῆ", but the Greek word in tW for discipline is "ἐgκρατῆ".  The word "ἐgκρατῆ" seems wrong.  Even with my limited Greek I know g is not a greek letter. It looks like the bug is in UGNT and TW data for Titus. @jag3773

**Comment by PhotoNomad0** [comment]
~I think we parse the tw data from the UGNT now.~

Nevermind the greek word for the tw is in the tw resources.  That will need to be changed also.

**Comment by PhotoNomad0** [comment]
And we will need to migrate project alignment data as well project tw data.

**Comment by PhotoNomad0** [comment]
Found error in UGNT: https://git.door43.org/Door43/UGNT/src/branch/master/57-TIT.usfm#L160

**Comment by PhotoNomad0** [comment]
Fix is in https://github.com/unfoldingWord-dev/translationCore/pull/3969

**Comment by PhotoNomad0** [comment]
Updated spelling:
Fixing spelling for G14680 from convert "ἐνκρατῆ" to "ἐγκρατῆ"
and convert lemma from "ἐνκρατής" to "ἐγκρατής"

**Comment by PhotoNomad0** [comment]
Reference: https://git.door43.org/Door43/UGNT/commit/26281f6bf239b205c6ca985e72392e20afccba4b

**Comment by cckozie** [comment]
The problem with hyphenated words is fixed.
