### ISSUE TITLE
Cannot load a project in word alignment

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3978]
0.8.1-alpha.20-0890ac6
I don't know which issue to fail, so I'm creating a new one.
App hangs on loading screen with this message in the console. Tried multiple projects, new and old, English and Hindi. All fail to load.
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/e794972e-938a-48cf-8bcb-38964165e968)

**Comment by mannycolon** [comment]
@cckozie Please retest this to confirm if my PRs being merged fixed this issue. when build with the commit 2b2c1a3 is done

**Comment by cckozie** [comment]
I have not seen the problem in 0.8.1-alpha.21-f1b0486
