### ISSUE TITLE
Fix loading articles that don't have a version directory

### ISSUE THREAD

**Issue by richmahn** [unfoldingWord/translationCore#3981]
Fix loading resource articles if version directory doesn't exist.

**Comment by richmahn** [comment]
- [ ] [1] Fix loading resource articles

**Comment by cckozie** [comment]
How to test?
Links in tHelps didn't work
Remove article in tHelps

**Comment by cckozie** [comment]
I renamed the apostles.md article and loaded the project with tW
![image](https://user-images.githubusercontent.com/8171759/37106839-65383718-21f8-11e8-953d-97646656645f.png)

**Comment by richmahn** [comment]
The Details error message should give you a better traceback than when it was getting null in the path.join() functino error. Yet I will be fixing this to jut show the article area with a message in #3977  The whole point of this wasn't for the whole app to bomb, but at least give an error message of what article.md file it couldn't load, which it does here. I tried to explain that when telling you how to test. :) I'd say this is still what I was suppose to do because it was causing wordAlignments to not be able to load.

**Comment by cckozie** [comment]
Still seeing the same error screen in 0.8.1-alpha.21-320865f. Holding until #3977 is completed.

**Comment by richmahn** [comment]
Yes, hold until 3977. This makes it so the tW checking is not dependent on the article content existing, and gives a message in the tHelps pane.

**Comment by richmahn** [comment]
Should now be unblocked in latest build.
