### ISSUE TITLE
Importing tstudio project with merge conflict causes UI crash

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#4007]
[en_php_text_reg.tstudio.zip](https://github.com/unfoldingWord-dev/translationCore/files/1797104/en_php_text_reg.tstudio.zip)

Importing this project will show a merge conflict in UI. When you click down arrow, the UI crashes and see this error:

![screen shot 2018-03-09 at 9 04 44 am](https://user-images.githubusercontent.com/14238574/37211171-15b42468-2379-11e8-9759-a1499203ee71.png)

**Comment by cckozie** [comment]
Dup (I think) of #3856

**Comment by PhotoNomad0** [comment]
I agree
