### ISSUE TITLE
App hangs with console error when exporting/uploading to Door43

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4017]
0.8.1-alpha.22-21f62ad 
![image](https://user-images.githubusercontent.com/8171759/37245667-5e735e24-2461-11e8-830c-0565a3545ab5.png)

[57-TIT.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/1799684/57-TIT.usfm.zip)
Import the project 
Try to export it to a door43 repo where it doesn't exist
(although I think it's broken for all project and all repos)

Also see a problem when the repo does already exist. Instead of warning the user, the app hangs with the error only shown in the console.
![image](https://user-images.githubusercontent.com/8171759/37353446-59aa020a-26ad-11e8-9003-1b4869e85b31.png)

**Comment by bspidel** [comment]
Turn console log into an alert and do not hang by placing try catch around log message

**Comment by mannycolon** [comment]
@bspidel I would say catching the error and properly alerting the user with the error message which should be in `error.message`

**Comment by bspidel** [comment]
Questions for @benjore  I can now detect error and allow export to complete. The questions are: 
1) should it stop after first error? 
2) should it display all errors? 
3) Should I work to investigate cause of current errors which are not obvious?

**Comment by bspidel** [comment]
Deprecated. Underlying problem repaired in Issue 4031

**Comment by bspidel** [comment]
@mannycolon What should I do with this now? move to closed?

**Comment by mannycolon** [comment]
@bspidel Move it to in QA
