### ISSUE TITLE
Project validation stepper should catch invalid language names and ids

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4027]
Currently a project that has the name and id switched can be imported even though one for the same languge already exists that has the language fields correct.
Invalid language names/codes should be detected during the project import process, and the user should be required to fix them or cancel the import.

**Comment by cckozie** [comment]
0.10.0-72cec56
https://git.door43.org/tc01/am_1co_text_ulb
https://git.door43.org/tc02/am_1co_ulb
These two projects are the same except that the first one has the language code and language id field values swapped. 
1. I am able to import that project without fixing the language fields. 
2. I am also able to import the second one even though the first one was already imported. (I assume that is #1 is fixed, the second one will no longer be a problem.

**Comment by PhotoNomad0** [comment]
#### Tasks:
- [ ] [5] Fix import validation for language
- [ ] [10] Add unit tests
- [ ] [5] PR Review 4017

**Comment by cckozie** [comment]
0.10.0-9f11991
The import/select now catches invalid language codes. However, it does not catch invalid language names if the language code is valid.
Per Jesse, this is acceptable. The language name should not be null, but anything else is ok.

**Comment by cckozie** [comment]
0.10.0-9f11991
https://git.door43.org/tc01/am_1co_reg
The manifest on this project has an empty language name. When importing it, I am presented with the project details screen where I see the valid language code and the empty language name field. 
I place the cursor in the language code field and hit Enter which causes the appropriate language name to be added.
I click Continue and then see this in the console, the app returns to the Projects page, and the project is not in the projects list or the imports folder.
![image](https://user-images.githubusercontent.com/8171759/40190338-49645086-59c4-11e8-8c68-e55490cf1ed3.png)

**Comment by PhotoNomad0** [comment]
> 0.10.0-9f11991
> https://git.door43.org/tc01/am_1co_reg
> The manifest on this project has an empty language name. When importing it, I am presented with the project details screen where I see the valid language code and the empty language name field.
> I place the cursor in the language code field and hit Enter which causes the appropriate language name to be added.
> I click Continue and then see this in the console, the app returns to the Projects page, and the project is not in the projects list or the imports folder.

@cckozie - Looking at translationCore 0.10.0-a90d7b8 (Travis build #7934). it's working now.
