### ISSUE TITLE
tC should consider a verse that only contains a line feed to be a missing verse

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4036]
[57-TIT2.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/1808585/57-TIT2.usfm.zip)
Verse 1 is missing but there is no Missing Verses warning during the validation import or when selecting the project.

**Comment by benjore** [comment]
Check verse entry + that it is not empty (not white space only)

**Comment by elsylambert** [comment]
Retested in 2.0.0 (4b3ebee). Not seeing this issue. Got the missing verse 1:1 warning.

**Comment by elsylambert** [comment]
Issue exist in 2.0.0 (ade72a0). Missing Verses warning was not given

**Comment by cckozie** [comment]
Still a problem in  2.1.0 (d8f36fe)

**Comment by PhotoNomad0** [comment]
@cckozie @elsylambert - tested above project in 2.1.0 (22cd49a)  and it worked fine for me - saw missing verse indication both on first import and then later when I select to open the project.  Retried many times on opening project.

**Comment by PhotoNomad0** [comment]
@cckozie @elsylambert - tried with old windows laptop - it is very slow but seeing the missing verses alert every time.  Not sure how to proceed with this?  Bug you to retry QA test?

**Comment by elsylambert** [comment]
@PhotoNomad0 I am testing it on the latest build b775824.

**Comment by cckozie** [comment]
@PhotoNomad0 Fails for me on this file running 2.1.0 (22cd49a) 
[55-1TI.usfm.zip](https://github.com/unfoldingWord/translationCore/files/3837938/55-1TI.usfm.zip)
BTW: The missing verses screen is not displayed either during the import or when reselecting the project.

**Comment by elsylambert** [comment]
Verified in 2.1.0 (b775824). Failed with 55-1TI.usfm.zip file but not with 57-TIT2.usfm.zip file. With 57-TIT2.usfm.zip file import, I got Missing verses 1:1 screen. Wondering why different behaviour with different usfm files.

**Comment by PhotoNomad0** [comment]
@cckozie @elsylambert - the 57-TIT2.usfm file has verse that is truly empty.  The 55-1TI.usfm file is technically not empty.  The HTML:

![Screen Shot 2019-11-13 at 5 46 24 AM](https://user-images.githubusercontent.com/14238574/68757045-414f9c80-05d9-11ea-859c-4d00d8e42331.png)

Which results in this verse content:

![Screen Shot 2019-11-13 at 5 45 56 AM](https://user-images.githubusercontent.com/14238574/68757214-8ecc0980-05d9-11ea-9a1a-5b76889f762f.png)

We could make the change that on import we run each verse through the USFM parser to make sure it has something besides whitespace.  The downside of that change would be an additional performance hit each time the project is opened.  We will have to do some measurements to see the performance hit on opening a large book like Isaiah.

**Comment by cckozie** [comment]
@PhotoNomad0 - Oops! Yes you are correct. However, upon further testing I've found that if the line with the verse marker only contains the \v x, and it is followed by a line feed and otherwise empty line, tC does not catch it as a missing verse. Then when loaded into a tool, tC reports the verse as not containing any text. We should probably ignore the line feed when there is no other text, but we'll save that for later. Changing the title and removing the Hotfix Candidate label.

**Comment by cckozie** [comment]
tC correctly reports verse with only a line feed, or white space and a line feed, as missing in 2.2.0 (2375ae5)
