### ISSUE TITLE
App resets the alignments of the first verse when doing an import of USFM3

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4086]
Import a new Titus project from USFM and align the first verse (and optionally others). 
Export the project to USFM3.
Delete the project from the projects folder.
Import the exported USFM3.
Open the project in Word Alignment. You'll get the alignments reset message for verse 1. Other aligned verses load correctly.

The problem does not occur after uploading the same aligned project to Door43 and then importing it from there.

**Comment by PhotoNomad0** [comment]
#### Tasks:
- [ ] [8] fix ordering of alignments on USB import
- [ ] [8] unit tests
- [ ] [8] PR Review

**Comment by PhotoNomad0** [comment]
@cckozie - this Looks like a bug with merged greek word alignments on USFM3 import.  Looking into it.

**Comment by PhotoNomad0** [comment]
Notes:

Issues found:
- generate blank alignments would generate occurrence of 0 for top word if UGNT was nested milestone.
- generate blank alignments would generate occurrence of 0 for top word if UGNT word had punctuation.

**Comment by PhotoNomad0** [comment]
@cckozie - Titus 1:1 was a good choice for testing.  When we added the UGNT with the TW milestones it complicated things.  Titus 1:1 in Greek has a double nested milestone (Jesus and Christ).  This broke alignment occurrence numbers, and therefore export.  It also broke USFM3 import.

**Comment by cckozie** [comment]
0.8.1-alpha.26-6233414 
I'm still seeing the same behavior of the alignments being reset.

**Comment by cckozie** [comment]
[es_tit.zip](https://github.com/unfoldingWord-dev/translationCore/files/1838268/es_tit.zip)

You can test by unzipping this project into the projects folder, open it to see the alignments in 1:1, export it to USFM3, delete the original project, then import the USFM3 file. You will then get the "there have been changes...alignments have been reset" message.
