### ISSUE TITLE
tC should default the Gateway Language selection to the last selected for the chosen project

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4102]
Currently the Gateway Language for a tool always defaults to English. If the project has previously been opened, it should default to the GL which was last selected for that project.
What should the default be if the project had never been opened?

## Specs
- [x] For a project that has not been previously loaded, the dropdown should read "Select Gateway Language". When the user clicks on that, the dropdown of GLs is displayed. ("Launch" button is disabled until a GL is selected.)
- [x] Save the users last GL selection and pre-populate the dropdown with that selection for that project in the future. 
- [x] If a project has not been opened in a Tool, do not "pre-select" any Gateway Language.

**Comment by PhotoNomad0** [comment]
@mannycolon - was waiting for locale strings, but even after merging concourse didn't build.  Is it ignoring crowdin Merges?

**Comment by PhotoNomad0** [comment]
Verified in build translationCore 2.0.0 (3fe9fe0) with locale strings.

**Comment by cckozie** [comment]
2.0.0 (3fe9fe0) 
The specs have been implemented. 
While testing I created 2 new issues that would improve the user experience while on the Tools page. (#6335 and #6336)

**Comment by elsylambert** [comment]
New feature Looks good in 2.0.0 (3fe9fe0).
 
Needs improvements with Hindi as Locale : the String has mistakes. 
![image](https://user-images.githubusercontent.com/51806180/62711264-b736dd00-b9c6-11e9-8bd5-27a16ebe5b9d.png)

**Comment by elsylambert** [comment]
Passing this issue. Will take the crowding issue with GL Team separately.
