### ISSUE TITLE
Don't show any alignment boxes when the verse is blank and there is not Greek text

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4107]
0.8.1-alpha.26-61679a7
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/612c2c67-dc2d-4dec-9ee8-76afc0869867)

**Comment by benjore** [comment]
This needs to be retested when the whole UGNT is brought in (with all the missing Greek verses). Note: the UGNT might have some of the verses in footnotes.

**Comment by cckozie** [comment]
Works in 1.1.3 (240da43)
