### ISSUE TITLE
Extra `'` added to Check Card

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#4127]
![image.png](https://images.zenhubusercontent.com/55e5f3984f7a08fbb7f4a658/563c6969-d2e2-46f7-bac2-d10cf2c4d99b)

See `"of' ... chosen people` Remove the `'` to make `"of ... chosen people`

**Comment by RoyalSix** [comment]
# Tasks
- [ ] [3] Debug Extra Single Quote Being Rendered
- [ ] [3] Implement Fix For Extra Single Quote
- [ ] [2] Write Tests
- [ ] [2] PR Review
