### ISSUE TITLE
USFM3 export puts multiple words on same line when there are quotes

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4129]
Import the Titus ULT project
Open it in Word Alignment
Export it in USFM3
Notice problem in 1:12
\v 12
\w One|x-occurrence="1" x-occurrences="1"\w*
\w of|x-occurrence="1" x-occurrences="1"\w*
\w their|x-occurrence="1" x-occurrences="1"\w*
\w own|x-occurrence="1" x-occurrences="1"\w*
\w prophets|x-occurrence="1" x-occurrences="1"\w*
\w has|x-occurrence="1" x-occurrences="1"\w*
\w said|x-occurrence="1" x-occurrences="1"\w*,"\w Cretans|x-occurrence="1" x-occurrences="1"\w*
\w are|x-occurrence="1" x-occurrences="1"\w*
\w always|x-occurrence="1" x-occurrences="1"\w*
\w liars|x-occurrence="1" x-occurrences="1"\w*,
\w evil|x-occurrence="1" x-occurrences="1"\w*
\w beasts|x-occurrence="1" x-occurrences="1"\w*,
\w lazy|x-occurrence="1" x-occurrences="1"\w*
\w gluttons|x-occurrence="1" x-occurrences="1"\w*." 

## NEED
- [ ] one word per line

**Comment by jag3773** [comment]
This bug #4554 might be related.

**Comment by PhotoNomad0** [comment]
Should be fixed in #5051

**Comment by cckozie** [comment]
Works in 1.1.3 (240da43)
