### ISSUE TITLE
Missing verses screen shows "Save Changes" button instead of "Continue"

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4139]
Go to the Edit Project Details screen of a project
Click on the Cancel button
Select a project that has missing verses
Notice that the text on the continue button is now Save Changes
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/5161712d-cddf-420c-89d7-74d7dc1dc1bb)

**Comment by elsylambert** [comment]
@cckozie Do you have a Project with Missing Verses?

**Comment by cckozie** [comment]
This has been fixed in 2.2.0 (2375ae5)
