### ISSUE TITLE
Change the non-English ULT back to ULB (In this case hindi ULT back to ULB)

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord/translationCore#4140]

**Comment by bspidel** [comment]
S

**Comment by RoyalSix** [comment]
M

**Comment by richmahn** [comment]
S

**Comment by mannycolon** [comment]
M

**Comment by mannycolon** [comment]
# Tasks
- [2] Change Hindi ULT bible manifest to ULB.
- [5] Change Hindi ULT references in the codebase back to ULB.
- [2] Updates unit tests from Hindi ULT to Hindi ULB.
- [3] Code cleanup.
