### ISSUE TITLE
Console Errors in translationWords when clicking "Save & Previous"

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#4143]
In translationWords and clicking on "Save & Previous", see Console Errors:

![previous_next_errors.png](https://images.zenhubusercontent.com/564e463c638e718c995eb353/e30b5485-0010-4911-8537-5602df4abf81)

**Comment by cckozie** [comment]
I'm not seeing the noted console error, but there are other that are noted in #4188.
