### ISSUE TITLE
Fix Localization gaps in tCore

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#4147]
Part of https://github.com/unfoldingWord-dev/translationCore/issues/4125

**Comment by PhotoNomad0** [comment]
#### to be done in tCore:
  - [ ] ~Need to add list of Bible Book Names to localization table~
  - door43 import dialog:
    - [x] localize "Enter URL"
    - [x] localize "Cancel"
    - [x] localize Book drop down
  - Project Cards:
    - [x] localize time ago
  - Tools Page
    - [x] localize gateway language drop down
    - [x] localize WA description
    - [x] localize tW description
   - Missing Verses validation stepper:  
    - [x] localize "verses" 
    - [x] localize Book name
    - [x] localize "Chapter" on left in WA

**Comment by cckozie** [comment]
Need to add list of Bible Book Names to localization table
door43 import dialog:
- [x] localize "Enter URL"
- [x] localize "Cancel"
- [x] localize Book drop down
Project Cards:
- [x] localize time ago
Tools Page
- [x] localize gateway language drop down
- [x] localize WA description
- [x] localize tW description
Missing Verses validation stepper:
- [x] localize "verses"
- [ ] localize Book name (there are several inconsistencies related to localizing the book name. I wrote them up in #4205
- [x] localize "Chapter" on left in WA
