### ISSUE TITLE
Console errors in tools regarding locale keys

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4188]
0.8.1-alpha.28-050acd8 
Same thing happens when opening the expanded scripture pane, and when clicking Save & Next or Save & Previous
Also when clicking Save on the Edit and Comments dialogs. Comments are saved but edits are not.
Probably related to work done on #2004
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/b69359d8-8f94-4879-8541-a723255f6019)

**Comment by elsylambert** [comment]
Retested in 2.0.0 (4b3ebee). Not seeing this issue.
