### ISSUE TITLE
Alignment problems in ULT

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4206]
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/e2d8b634-e627-4414-9f0f-f68f15589276)

**Comment by PhotoNomad0** [comment]
Fixed in PR: https://github.com/translationCoreApps/tC_Resources/pull/39

**Comment by PhotoNomad0** [comment]
@cckozie - you will have to delete resources before testing this since we cannot bump the version number.

**Comment by cckozie** [comment]
@PhotoNomad0 NP. I thought doing an install replaces all of the resources. Is it dependent on version #?
