### ISSUE TITLE
Wrong localized text related to supported projects/tools

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4208]
I think this is using the Hindi version of the older text
English:
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/d06d5e2c-fd96-40ca-afb7-924feaa3c469)

Hindi:
![image](https://user-images.githubusercontent.com/8171759/37945487-2305369a-3146-11e8-860d-6c1f0fa997a3.png)

English:
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/1583c2e2-9d27-43ac-aa86-c8aeaa2b5c48)

Hindi:
![image](https://user-images.githubusercontent.com/8171759/37945673-e477bfb4-3146-11e8-84d4-237928b7bf54.png)

**Comment by bspidel** [comment]
I don't think any code changes are necessary. the two tags to have updated translations in Hindi are:
tools.select_tool_from_list  
projects.books_available

**Comment by RoyalSix** [comment]
Local Testing: `LGTM`
Code Review: `Pending...`
