### ISSUE TITLE
tW edits not being saved

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4212]
0.8.1-alpha.28-29223a3 
Comments are saved but edits are not. Probably related to missing locale keys and work remaining on #2004

**Comment by RoyalSix** [comment]
@neutrinog This might be a duplicate issue. I was assigned to this one to make sure that tW edits are working after #2004 is fixed. Let me know if you have any questions I can help with.

**Comment by da1nerd** [comment]
@RoyalSix @cckozie I just tested this and edits are working just fine in tW.
I tested with 0.8.1-alpha.28-36a2019.

However, it should be noted that I get a ton of warnings when opening the tW tool.
![warnings](https://user-images.githubusercontent.com/166412/38267927-b33a264e-3731-11e8-8fbc-393bb22aa345.png)

**Comment by cckozie** [comment]
@neutrinog @RoyalSix 
Just tested in alpha.28-36a2019. Edit is not saved and I get this in the console when I do a "normal" verse edit (not in the expanded scripture pane).
![image](https://user-images.githubusercontent.com/8171759/38272735-ba388616-374f-11e8-80b8-1051d27a801e.png)

**Comment by da1nerd** [comment]
I just realized you are talking about the verse check tool. This has been fixed. https://github.com/translationCoreApps/VerseCheck/pull/101
