### ISSUE TITLE
Time ago is not updated when locale is changed

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4216]
0.8.1-alpha.28-29223a3
The time ago field on the project cards is not updated when the locale is changed, but rather when the screen is refreshed by navigating to another screen and then back again.
After changing locale to Hindi:
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/18346d24-d27d-4206-b198-7e778ded4dac)

After navigating away and back:
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/f5ef746a-04c1-4e2f-ac97-7b3005bb239c)

**Comment by elsylambert** [comment]
Retested in 2.0.0 (4b3ebee). Not seeing this issue.

**Comment by elsylambert** [comment]
Duplicate Issue
