### ISSUE TITLE
Need to update copyright notices

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4218]
Dates should be 2017-2018
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/da070169-835b-4cbd-a668-9b28e349a81a)

Also for Windows installer, dates should be updated and "Based on earlier work..." text should be added 
![image](https://user-images.githubusercontent.com/8171759/38265916-d80d21c8-373c-11e8-8a86-123afa641736.png)

**Comment by RoyalSix** [comment]
@cckozie where exactly should `Based on earlier work` be added?

**Comment by cckozie** [comment]
@RoyalSix I think it should be added directly below the Copyright (C)... line in the installer's License dialog.

**Comment by cckozie** [comment]
Looks good. Added #4256 to reconcile difference between the app's notice and the Windows installer.
