### ISSUE TITLE
Releases build should not automatically open the developer tools

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4222]

**Comment by da1nerd** [comment]
@cckozie the release builds don't open the developer tools. The last release build was 12 days ago and I just checked that it's working correctly. It looks like the builds you've been testing have all been from the develop branch.

**Comment by da1nerd** [comment]
Technically when this whole release process started we should have created a `release-v0.9.0` branch and any fixes to the release would be merged into it for QA testing.
