### ISSUE TITLE
Missing localizations for edit verse not being checked

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4225]
translationCore 0.9.0 (from http://tc-release.unfoldingword.surge.sh/)
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/6dcf3a5c-a710-4383-9881-56a3e095e22e)

**Comment by elsylambert** [comment]
Retested in 2.0.0 (4b3ebee). Not seeing this issue.
