### ISSUE TITLE
Incorrect data in VerseEdits.csv

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4235]
0.9.0 Travis build #7360
This problem was introduced with #2004, Edit verse not being checked.
When editing was done in tW:
1. The groupid column now always reflects the chapter number
2. The groupName column is always blank
3. The occurrance column is always blank
4. The quote column is always blank
5. The gateway Language Quote column contains the group name even when the edit was done in the expanded scripture pane on a verse other than the one being checked. @benjore - What is the desired behavior for this case?              

When editing was done in alignment:
The gateway Language quote, groupid, and groupName columns all reflect the chapter number. @benjore - What should these columns reflect?

**Comment by benjore** [comment]
For now, all of the fields listed above should be blank. 

Long term (NOT to be done now), 3 new fields will need to be created `activeBook` `activeChapter` `activeVerse` (actual names are negotiable). This would give the context needed to make all the above fields about which check was open make sense (for the tW tool). All of the above fields for the Word Alignment tool would still be blank except for the 3 new fields mentioned in this paragraph, which would still give helpful context.

**Comment by RoyalSix** [comment]
@benjore Should I only be making these blank for the verse edits? That is what has been done.
