### ISSUE TITLE
Language names are not localized on change locale dialog

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4259]
Not sure if they should be or not.
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/66d5522f-834d-4395-b3f9-3fcc0bf28535)

**Comment by jag3773** [comment]
That screenshot looks like the names *are* localized.

**Comment by elsylambert** [comment]
Retested in 2.0.0 (4b3ebee). Needs decision on this one.

**Comment by jag3773** [comment]
FWIW, that is what I would expect it to look like.

**Comment by cckozie** [comment]
Closing based on Jesse's comment.
