### ISSUE TITLE
\s and \p markers are being displayed in check pane

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4263]
0.9.0
![image](https://user-images.githubusercontent.com/8171759/38378084-41eed4e8-38c2-11e8-9906-f4b7c8d83c3a.png)

![image](https://user-images.githubusercontent.com/8171759/38378202-8a70cc8a-38c2-11e8-8505-0954a6a73702.png)

**Comment by benjore** [comment]
@cckozie can you attach the file?

**Comment by benjore** [comment]
Dup of #4082 ??
@benjore  No, #4082 has to do with the scripture pane. This one is for the checking pane. The behavior is different for \s & \p here and \m there.

**Comment by benjore** [comment]
## Note 
- Keep the data, do not display it
- Display the data in verse edit
- Data should be exported
- make changes in tC-uitoolkit

**Comment by benjore** [comment]
Related to #5051

**Comment by PhotoNomad0** [comment]
Looks like VerseCheckContainer.render() in tw is calling usfmjs.removeMarker() directly.  It could be calling this removeMarker() in the tc-ui-toolkit.

**Comment by PhotoNomad0** [comment]
Should be fixed in #5051

**Comment by PhotoNomad0** [comment]
@cckozie - verified in https://tc-builds.door43.org/build/release-v1.0.2/translationCore-win-x64-1.0.2-34ddb63.setup.exe

**Comment by cckozie** [comment]
Works in 1.0.2 (a18aef8)

**Comment by PhotoNomad0** [comment]
@cckozie - broke verse edit in tW - new lines were being stripped out.

**Comment by PhotoNomad0** [comment]
Verified fix in https://tc-builds.door43.org/build/release-v1.0.2/translationCore-win-x64-1.0.2-2950c03.setup.exe

**Comment by cckozie** [comment]
No problems found in 1.0.2 (ac3d66a)
