### ISSUE TITLE
SPIKE: Investigate compatibility of 0.9 and older projects

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4278]
1. Determine which of them are handled properly by our migrations, and which are not.
2. Determine the level of effort required to prevent migrating project that would be broken by the migrations.
3. Determine the level of effort required to alert the user that there are unmigrated projects.
4. Determine the level of effort required to warn the user that a selected project cannot be opened in 0.9.

**Comment by PhotoNomad0** [comment]
Projects for testing tW:
- https://git.door43.org/pjoakes/ceb_jas_text_ulb_L- old tc project that just shows an empty screen tw.  Checking data is broken down by chapter/verse.  Where new projects are by keyterm.  This looks like a major migration effort to accommodate.
- https://git.door43.org/toddlprice-for-testing/rmr-x-bsa_mrk_text_ulb - opens to error screen in tw (and can do that only in developer mode).  Seems to be that projects/rmr-x-bsa_mrk_ulb/.apps/translationCore/index/translationWords has words not found in our project.  This looks like a throw away file.  It looks like we only have tw data in the app for the following books and only titus is officially supported in this app:

![screen shot 2018-04-06 at 3 18 43 pm](https://user-images.githubusercontent.com/14238574/38440036-f7dd8ea2-39ad-11e8-898b-1635b51ceecc.png)

**Comment by PhotoNomad0** [comment]
Observations on testing projects:
- Cannot find any WA projects older than 0.8.1.  I think 0.8.1 was first release with support for WA tool.
- 0.8.1 WA projects we already migrate the minor differences.  Uses same data structure as 0.9.0
- very old tw projects look like checking data is broken down by chapter/verse. Don't know how that works or the effort to migrate them.
- the other tw projects that I can find are for books we don't yet support.  That would be significant effort to add these to tw resources, and don't even know if all the UGNT has been tagged yet.

Note: only real tw projects I could find are here: https://git.door43.org/pjoakes

**Comment by PhotoNomad0** [comment]
The one issue to be addressed is for future support of TW.  If new releases of the app remove tw key words, it looks like the app will open to an error screen.  We will need to fix the app to fail gracefully.

**Comment by PhotoNomad0** [comment]
Still needed:
- [ ] estimate of effort to migrate old TW projects.
- [ ] real world examples (not test) of old tw projects to evaluate compatibility (other than in Perry Oaks and todd Price's D43 accounts)  (currently only support Titus officially, and only have data for 1th through phm).

**Comment by benjore** [comment]
"This project contains data from an old version of translationCore which is not supported in this release. For help opening this project or to restart checking, please contact help@door43.org."

**Comment by benjore** [comment]
[sw_tit_text_ulb_L3 copy.zip](https://github.com/unfoldingWord-dev/translationCore/files/1899919/sw_tit_text_ulb_L3.copy.zip)

**Comment by cckozie** [comment]
0.7.0 Project
[rmr-x-bsa_tit_text_ulb.zip](https://github.com/unfoldingWord-dev/translationCore/files/1899921/rmr-x-bsa_tit_text_ulb.zip) - tC project folder

[rmr-x-bsa_tit_text_ulb7.tstudio.zip](https://github.com/unfoldingWord-dev/translationCore/files/1901004/rmr-x-bsa_tit_text_ulb7.tstudio.zip)

**Comment by cckozie** [comment]
Using build from 4/11/18
Scenarios in which the user is prevented from using the project:
1. Importing 0.7 project from Door43
2. Upgrading the app from 0.7.0 and 0.8.0

Scenarios in which the user is **NOT** prevented from using the project
1. Importing the tstudio project locally

**Comment by cckozie** [comment]
There should not be a case where there is a local tstudio project that has checking data, so this looks good for now. I'm creating a new issue to deal with this error message taking precedence over the messages that indicate the tC does not support the type of project being imported. #4324
