### ISSUE TITLE
tC UI toolkit: Verse Check

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#4311]

**Comment by mannycolon** [comment]
@RoyalSix I thought the idea of moving the UI components into `tc-ui-toolkit` was to separate the business logic from the UI components but it looks like you moved the verse check exactly as it was before.

**Comment by RoyalSix** [comment]
@mannycolon I actually did alot of refactoring. If you check the components, the only one that has logic is in `VerseCheck.js` and the modal component. 

I will move the rest of the logic out. I left it in there so that we could test it.
