### ISSUE TITLE
Wrong text on Skip Check card

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4342]
Before localization:
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/541b05db-9122-4c79-81b4-8d7d9aeae0b2)

After localization:
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/7a1bdce0-c4db-43c7-9df4-202e83db1ea3)

**Comment by cckozie** [comment]
Open a Titus project in tW.
Go to any check
Click Cancel
Click Save & Next

**Comment by mannycolon** [comment]
For QA testing please wait for after we have the `tc-ui-toolkit` in the tools.

**Comment by cckozie** [comment]
@PhotoNomad0 The text is correct now, but it is not localized. Is that a problem with this issue or another one? (Nothing is localized in the new tW except for items in the menu bar)
