### ISSUE TITLE
When project is selected, verse edits are overwritten on some projects

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#4344]
Here is an example project to reproduce this:
[English_tit.zip](https://app.zenhub.com/files/65028237/b79edd06-8cad-4953-9384-458437a6b010/download)

When you open the project, will see string `##### Serious Bug ####` prepended to Titus 1:1 (this was in the English_tit.usfm file in project folder).

The cause of the problem seems to be that tcore is reimporting the usfm file in the project folder each time the project is selected.

An alternate way to recreate this problem in a new or existing project (only if it has alignments):
- export project to door43 - this creates the usfm file in the project folder.
- make verse edits to project.
- then select a different project.
- then select your previous project.  Will see that verse edits have been removed.

**Comment by cckozie** [comment]
I moved the following issue to #4347 

I was working on a project that had several edits and no alignments. There was no usfm file in its folder.
I partially aligned verse 1 of the project, then uploaded to Door43.
I then made an edit to verse 4 of the project.
When I then attempted to upload to Door43 I was warned that there were edits that would invalidate alignments. I took the Cancel option.
I reopened the project to verify that both the edit and alignments were still intact, and they were.
Each time after editing a verse, when choosing to Upload I now get that warning even though my only alignments are on 1:1 and I have not edited that verse.
When I reopen the project I see that my edits have been removed, but the edit icon is shown for the edited verses.

**Comment by PhotoNomad0** [comment]
> I was working on a project that had several edits and no alignments. There was no usfm file in its folder.
> I partially aligned verse 1 of the project, then uploaded to Door43.
> I then made an edit to verse 4 of the project.
> When I then attempted to upload to Door43 I was warned that there were edits that would invalidate alignments. I took the Cancel option.
> I reopened the project to verify that both the edit and alignments were still intact, and they were.
> Each time after editing a verse, when choosing to Upload I now get that warning even though my only alignments are on 1:1 and I have not edited that verse.
> When I reopen the project I see that my edits have been removed, but the edit icon is shown for the edited verses.

@cckozie - there are two issues here:
- it looks like there is a bug that we test for changes in word counts even on verses that have not been aligned.
- the other is this issue, that every time you open the project, it resets the text back to the last time you uploaded to D43.
