### ISSUE TITLE
Support for udt and ulb projects at the same time

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#4352]
## User Story

As an aligner, I want to align in tC a dynamic and literal project for the same language/book so that I can align then both without doing file gymnastics to do it.

## Spec
- tC should be able to support importing multiple translation styles for the same book/language combo
- tC should be smart enough to never open multiple projects for the same book/language combo

**Comment by jag3773** [comment]
I'd suggest a solution similar to https://github.com/unfoldingWord-dev/translationCore/issues/1991 where we embed the book's short code into the path.  For example, `en_ulb_gen`.  This should probably be implemented in https://github.com/unfoldingWord-dev/translationCore/issues/3421 .

Using the proposed new field in the manifest will be a slower to implement and less flexible.

**Comment by benjore** [comment]
Subsumed by #3421
