### ISSUE TITLE
Add build number to the displayed version number

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4355]
As a tester I need a build number (or other unique identifier) to be available for viewing in the running app in order to know for sure which build I am testing. (This has not been the case in the release branch)

**Comment by benjore** [comment]
#4306 Maybe should be done with this.

**Comment by da1nerd** [comment]
note to self. We'll use the commit hash for now and can append it to the `.env` file during build time.
We'll need to update tc to then read the environment variable and display it properly.

**Comment by cckozie** [comment]
re: comment left in #4306, so I don't know if I'm testing the concourse build, but this is what I'm seeing from the build in surge develop; "translationCore 0.10.0-9d56594 (undefined) "

**Comment by da1nerd** [comment]
@cckozie the build numbers will not work in surge. I'm not doing any backwards compatibility updates to surge since that will soon be deprecated in favor of concourse.

**Comment by da1nerd** [comment]
@cckozie are you still seeing this issue? If you use the builds from concourse you should get the build number.

**Comment by cckozie** [comment]
It is working with the Concourse builds.
