### ISSUE TITLE
Inconsistent handling of alignments in projects upgraded from 0.8.1

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4361]
[en_tit.autoaligned_in_0.8.1.zip](https://github.com/unfoldingWord-dev/translationCore/files/1943560/en_tit.autoaligned_in_0.8.1.zip)

Deleted the 2 translationCore folders to simulate clean machine
Installed released version of tC 0.8.1
Imported Titus from usfm
Fully aligned all chapters
Compressed the project folder and saved the zip file
Uploaded to Door43

Installed tC 0.9.0 rc3
Selected to Export to USFM3
Warned that there had been changes and alignments would be reset
Chose Cancel option so as to not modify the project
Selected the project
Word Alignment showed 100% complete
Opened project in Word Alignment and all alignments were in tact

Closed tC
Deleted the project
Unzipped the saved project and moved to the projects folder
Restarted tC
Selected to export the project to USFM3
Again received the warning that alignment had been invalidated
Clicked the Export button and exported the project
(It took 20+ seconds before the dialog to choose the file name and location came up. wrote up in #4362)
Word Alignment now shows 33% complete
When opened in Word Alignment it is clear that the alignments have been reset

Closed tC
Deleted the project
Reopened tC
Imported the project from Door43
Word Alignment tool indicates 100% complete
Verified 100% by opening the project in Word Alignment

**Comment by RoyalSix** [comment]
## Tasks
- [ ] [2] PR Review
- [ ] [4] Fix Upgrade Bug

**Comment by RoyalSix** [comment]
Notes:
Invalidness is coming from: 
- Wrong amount of occurrences for letters. i.e. `a`, `an`, `s`

Path to fix:
- Run migrations to fix occurrences before exporting to usfm
