### ISSUE TITLE
Need an indication of processing after selecting to export a project

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4362]
I assume this has to do with checking for broken alignments/selections.
After upgrading from 0.8.1 and choosing to export a project to USFM3 that now had invalidated alignments, it took 20+ seconds on my Mac to bring up the dialog to choose a file name and folder for the export. There should be some indication of processing during that time.
The same problem exists when exporting to Door43.

- [x] For any export or upload, there should be a tC logo spinner while tC is figuring out what's going on. (need to present the dialog earlier)

Note: Export to USFM2 does not have this same delay.

**Comment by RoyalSix** [comment]
This has already been done.

**Comment by cckozie** [comment]
This does work in 2.0.0 (3727b58), but is not consistent with uploading to Door43. Wrote up #6417 to deal with that.

**Comment by elsylambert** [comment]
Have similar observations as in #6417. 
2.0.0 (3727b58)-The spinner works fine while exporting to Door43 and USFM export.
