### ISSUE TITLE
ERROR text where verse check should be

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4388]
0.9 build from 4/25 (save behavior in the previous build
There are actually two issues.
1. The missing verses check is skipped when importing this file
2. The ERROR and missing verse check in tW

[abu_tit_text_reg.tstudio.zip](https://github.com/unfoldingWord-dev/translationCore/files/1949228/abu_tit_text_reg.tstudio.zip)

![image](https://user-images.githubusercontent.com/8171759/39278788-be5fc156-48ba-11e8-9556-a1c7bfe5f44c.png)

**Comment by benjore** [comment]
May be related to #4330

**Comment by cckozie** [comment]
https://git.door43.org/qa91/es-419_tit_ulb
The fix has introduced a different problem with missing verses. Now with this project, the missing verses screen is displayed twice; first directly following the "importing" alert, and the second following the "loading your project" alert. The second time it is displayed the Continue button is disabled.
With the previous build this problem did not occur.
First display of missing verses screen:
![image](https://user-images.githubusercontent.com/8171759/39377397-9b6dbff2-4a1a-11e8-953d-9c3d6b214db1.png)

Second display of missing verses screen:
![image](https://user-images.githubusercontent.com/8171759/39377249-125b6ec6-4a1a-11e8-8d29-089b764ccc6c.png)
