### ISSUE TITLE
Bug: More than one tW in same verse not functioning properly

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#4389]
![image.png](https://images.zenhubusercontent.com/55e5f3984f7a08fbb7f4a658/332ba102-421d-4653-81d8-0971eb68c1a4)

From Klappy "In preparing for the demo, I’m using the current build on surge of v0.9.0. I noticed that tW checks for words with more than one in the same verse is broken and only lets you check the first one, and the menu acts as if both are open."

**Comment by richmahn** [comment]
Unable to reproduce. Need steps, environment, etc. to determine the cause. @klappy @benjore @cckozie

**Comment by klappy** [comment]
It may be just the project I'm working with. If you can help explain why it's doing it, we can figure out if it's a problem to be worried about or not.

[English_tit.zip](https://github.com/unfoldingWord-dev/translationCore/files/1956172/English_tit.zip)

**Comment by cckozie** [comment]
This appears to be a problem with the project as I cannot replicate it with any other project.
