### ISSUE TITLE
Update ULT to fix Questionable tW highlighting in Titus 1:15

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4410]
v0.9.0
![image](https://user-images.githubusercontent.com/8171759/39497826-a3d2a16e-4d6a-11e8-9e7c-7dcd8cd0f610.png)

![image](https://user-images.githubusercontent.com/8171759/39497764-63bb6e94-4d6a-11e8-8e2b-4cad747b96aa.png)

![image](https://user-images.githubusercontent.com/8171759/39497889-e4896d28-4d6a-11e8-9726-7b6ed82addd8.png)

**Comment by jag3773** [comment]
Unfortunately, that is incorrect.  This is how it should be:

* καθαρὰ == "are pure"
* καθαροῖς == "who are pure"

How do we fix this?  I'd suggest a 0.9.1 that addresses #4333 and this issue at least @benjore .

**Comment by lrsallee** [comment]
I believe this is a ULT alignment issue, not a tW issue. Perry needs to correct this in his Titus alignment file.

**Comment by lrsallee** [comment]
Current alignment is:
<img width="760" alt="tit_1-15_wrong" src="https://user-images.githubusercontent.com/5585656/39527134-bc53764e-4dee-11e8-9b59-bad44cb4722d.png">


But it should be:

<img width="753" alt="tit_1-15_correct" src="https://user-images.githubusercontent.com/5585656/39527154-c8312826-4dee-11e8-8ab4-7ea5ec02e97c.png">

**Comment by pjoakes** [comment]
OK, so in this case, are2 and pure2 go before are1 and pure1.  I was thrown off by trying to put the numbers in order. But since it makes no difference in English, we should change the order of clauses to match the Greek. I will do that.

**Comment by benjore** [comment]
@jag3773 We need a link! @lrsallee @pjoakes

**Comment by benjore** [comment]
Correction: Just hack the data, rather than bringing in a new resource.

**Comment by richmahn** [comment]
- [ ] [3] Hack the data to fix ULT
- [ ] [1] PR Review for #4410

**Comment by pjoakes** [comment]
OK, pull request #1770 addresses this problem.
