### ISSUE TITLE
Suggest adding a "<1%" indicator for percentage complete on tools cards

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4414]
v0.9.0
I have a Mat project with 3 completely aligned verses. On the Word Alignment card it indicates 0% complete. That initially scared me since I know I had completed some alignments. If there is some completed work (checks or alignments) but less that 1%, showing something like "<1%" would allow the user to see that some actually have been completed.

**Comment by PhotoNomad0** [comment]
Addressed in https://github.com/unfoldingWord-dev/translationCore/pull/6489

**Comment by PhotoNomad0** [comment]
Verified in Verified in translationCore 2.0.0 (697040c)

**Comment by cckozie** [comment]
Looks good in 2.0.0 (f5ff634)

**Comment by elsylambert** [comment]
Verified in  2.1.0 (d0a11e7) for regression testing. Looks good.
