### ISSUE TITLE
Alignment completion circles show some completions for chapters without any alignments

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4418]
v0.9.0
[en_tit (2).zip](https://github.com/unfoldingWord-dev/translationCore/files/1969144/en_tit.2.zip)

There are no alignments in chapters 2 and 3.
When the project is loaded in alignment, the circles for chapters 2 and 3 show no completions, but when the chapter group is opened, then a percentage complete is shown.
Also, when a new project (no alignments) is first loaded into the alignment tool, the same problem exists.

![image](https://user-images.githubusercontent.com/8171759/39553040-5f492212-4e31-11e8-8b8a-a6d6a35b2e7c.png)

**Comment by benjore** [comment]
Front matter, chapter headings, section headings, etc. should not be counted in the progress circle.

**Comment by PhotoNomad0** [comment]
#### Tasks:
- [ ] [10] Fix WA tool progress
- [ ] [5] Unit tests
- [ ] [5] PR Review for [4418]

**Comment by PhotoNomad0** [comment]
Fixed in PR: https://github.com/unfoldingWord-dev/translationCore/pull/4485

**Comment by PhotoNomad0** [comment]
Blocked until Joel finishes WA rewrite.

**Comment by PhotoNomad0** [comment]
@cckozie - Looking at translationCore 0.10.0-a90d7b8 (Travis build #7934). It's fixed now.

**Comment by cckozie** [comment]
0.10.0-155c8db
This project has not been aligned, but the tool card shows 9% and the chapter 3 circle shows about 30%.
[es-419_tit_ulb.zip](https://github.com/unfoldingWord-dev/translationCore/files/2023558/es-419_tit_ulb.zip)
![image](https://user-images.githubusercontent.com/8171759/40321691-80af7afa-5cf5-11e8-9af8-a1eff9a764b3.png)

**Comment by cckozie** [comment]
0.10.0-9d56594 (undefined)
I can't tell if this is really fixed because of very strange  behavior. I also don't know if the problems are because of work done on this issue or others.
I imported a fresh English Titus project from USFM.
Opened the project in wA and clicked on Chapter 2. Zero % complete indicated as expected.
![align1](https://user-images.githubusercontent.com/8171759/40925566-a6ae3d3c-67df-11e8-9fc7-ec577448e8a4.png)

I aligned 2:1 and got the checkmark, but still zero % complete indicated.
![align2](https://user-images.githubusercontent.com/8171759/40925642-d0f07cae-67df-11e8-9048-5d1a7cbb88fe.png)

I clicked on verse 2:2 and now it shows 100% complete
![align3](https://user-images.githubusercontent.com/8171759/40925747-02fd5a0a-67e0-11e8-9b1a-2fe516508756.png)

I clicked on Chapter 3 and now Chapter 2 shows 50% complete
![align4](https://user-images.githubusercontent.com/8171759/40925780-1badfd2a-67e0-11e8-82ff-db976125a913.png)

I clicked successively on 2:3, 2:4, and 2:5, and not it shows about 25% complete.
![align5](https://user-images.githubusercontent.com/8171759/40925834-3fd3b064-67e0-11e8-994f-ae25f22e5139.png)

**Comment by PhotoNomad0** [comment]
@cckozie @benjore - nuts!  I fixed one issue and uncovered a bigger one.

**Comment by PhotoNomad0** [comment]
This has two more problems:
- that we were not counting verses with blank alignments - that was quick to fix.
- that progress is not updated until user clicks another verse.  This is an existing problem that I am trying to understand.

**Comment by PhotoNomad0** [comment]
It looks like with the rewrite of the WA tool that the alignment data is not saved until after progress bars are updated.  Talking to Joel.

**Comment by PhotoNomad0** [comment]
Blocked - waiting for Joel to update WA to load all alignments.
