### ISSUE TITLE
Drop tc_resources submodule & Implement as NPM module

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#4425]
1. Drop tc_resources as a submodule and make it just a folder
   1. create branch and make changes
      > git checkout -b feature-bspidel-4425
      > git submodule deinit -f tC_resources
      > git rm tC_resources
      > git commit -m "Removed submodule "
      > rm -rf .git/modules/tC_resources
      > git push origin feature-bspidel-4425
   2. create new space and clone new translationCore
       >  git clone git@github.com:unfoldingWord-dev/translationCore.git
       > git pull origin feature-bspidel-4425
   3. test for missing submodule
      > npm run load-apps
      > npm run update-apps
      1. note that tC_resources is not mentioned on console
2. Write a script that uses the `source content updater` to verify that the resources currently packaged with tC are the latest version of Hindi and English resources.
- Every time we make a release run such script to have the latest version of resources (English, Hindi, greek only at this point) packaged with tC
- Write code that determines if the user has resources that are older than the resources packaged with tC and if so then move these resources from the tC codebase/build/package to the user folder where resources belong.
   - for each resource in package directory for ['en', 'hi', 'grc'] 
       - check to see if date: doublincore.modified is newer in users local directory
          - if so copy resource to users resources
          - if no date in users resource then copy from package

**Comment by RoyalSix** [comment]
## Tasks
- [x] [1] Setup NPM Module
