### ISSUE TITLE
Make the UI design with mock data

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#4426]
Per @cckozie and @benjore on slack:
For unsuccessful download of the Dynamic Source Content Update use the following as alert message 'Failed to download source content updates.'

Also, It would probably be good to put 'Retry' and 'Cancel' options on the alert. If the failure was caused by no Internet connection, then that alert should be used instead of a custom one for this issue.

**Comment by cckozie** [comment]
Local timestamps are not being displayed. Not sure if the problem should be attributed to this issue or to #4833.

**Comment by mannycolon** [comment]
@cckozie If the resource was never downloaded in tC then there would not be any local timestamps. Where these resources with missing local timestamps previously downloaded in your local resources folder?

**Comment by cckozie** [comment]
@mannycolon The only time I have seen a timestamp on any resource is for the Greek on a clean install. Even after downloading all resources I do not see any other timestamps.

**Comment by cckozie** [comment]
Problems have been moved to new issues.

**Comment by cckozie** [comment]
Passing this issue. Added #5065 to "fix" problems with the update failed dialog.
