### ISSUE TITLE
Word Alignment Tool: Partial Invalidation

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#4429]
When invalidating an alignment after an edit, only invalidate what is required (instead of the entire verse).

**Comment by benjore** [comment]
@neutrinog ^^^

**Comment by da1nerd** [comment]
These are the rules I'm following for validation.

## source token is updated

* single - break alignment
* merged - break alignment

## target token is updated

* single - break alignment
* merged - remove from alignment. *do not break alignment*.

## source token is removed

* single - break alignment
* merged - break alignment

## target token is removed

* single - break alignment
* merged - remove from alignment. *do not break alignment*.

**Comment by benjore** [comment]
@neutrinog Is this one ready to go? I'm moving it to `In QA`. Move it back out if it's not done.

**Comment by cckozie** [comment]
There are at least 3 issues that need to be fixed on this one: (not failing it as I assume you're not finished and am moving it back to Current Phase)
1. If I make an edit to delete a word out of the verse, and that word appears multiple times in the verse, all of the other instances of that same word get sent back to the word list.
2. Subsequent verses to the one having the edit made in the alignment tool also get partial reset as I click on each verse.
3. Change the sentence "The alignments for the current verse have been reset." in the alert to "Some alignments for the current verse have been reset.

**Comment by cckozie** [comment]
Here's another scenario that @RoyalSix found :
Open project in tW
Select 'a servant' and 'an apostle' for the apostle check in 1:1
Switch to the alignment tool
Edit 1:1 to change an apostle to a apostle and change a servant to an servant
The wA tool shows the resetting error but noting gets changed.

**Comment by da1nerd** [comment]
this is ready for QA again.
