### ISSUE TITLE
Update tC Launcher Logo

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#4431]
![image.png](https://images.zenhubusercontent.com/55e5f3984f7a08fbb7f4a658/1a8213f9-faa8-4d2c-a145-00a053b4584b)

From @timjore 

Should look like this: 
![image](https://user-images.githubusercontent.com/13352518/39821399-c309c18a-536d-11e8-9df0-7022634e9480.png)

**Comment by RoyalSix** [comment]
## Tasks
- [ ] [1] Switch out old tc icon
