### ISSUE TITLE
ERROR displayed where scripture pane should be in alignment tool

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4433]
0.10.0-7f20ffa
This problem prevents me from testing other issues.
Load a project with alignments.
Open tW and edit a verse that had been aligned.
Open wA and navigate to the verse with the edit.
See the error
[en_tit.zip](https://github.com/unfoldingWord-dev/translationCore/files/1976039/en_tit.zip)

![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/0d7cd656-9aa8-4264-8183-a489ebe5e71e)

**Comment by cckozie** [comment]
I may have caused this myself.

**Comment by da1nerd** [comment]
this will be fixed after I finish refactoring wA (in the next day or so)
