### ISSUE TITLE
Aligned words disappear

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4439]
0.10.0-72cec56
Load an unaligned project in  word alignment. Drag a word from the word list to an alignment box. The word is not displayed there.
This screenshot was taken after dragging 'Paul' to box under 'Παῦλος'
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/1717db12-e0f7-4daa-8d2f-66d7d8c18e4f)

**Comment by da1nerd** [comment]
this will be fixed after I finish refactoring wA (in the next day or so)
