### ISSUE TITLE
SPIKE: How do we center the menu?

### ISSUE THREAD

**Issue by EllDoubleYew** [unfoldingWord/translationCore#448]
This was almost done at one point but now everything is refactored and we cant use refs anymore. There needs to be a concrete approach to doing this that does not use findDOMNode(element). No idea how this is going to be done but we gotta figure out the right way to do it.

**Comment by RoyalSix** [comment]
Why can't we use refs?

**Comment by klappy** [comment]
@mannycolon: Have you written up your new approach anywhere? If so can you add it or link to it here?
