### ISSUE TITLE
Cannot open any project in tW

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4500]
0.10.0-af82837 
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/2bd596d6-0eb6-43f2-87cf-5737c1571027)

**Comment by da1nerd** [comment]
this is due to a premature PR merge in tW.

**Comment by cckozie** [comment]
Fixed in 0.10.0-a90d7b8
