### ISSUE TITLE
Percent complete is not always accurate

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4501]
0.10.0-155c8db
[en_tit (1).zip](https://github.com/unfoldingWord-dev/translationCore/files/2024161/en_tit.1.zip)
This may have been caused by work on #3059.
I aligned the last couple of words in chapter 3 of this project. The circle still does not indicate 100% complete. All of the verses in this project show the check mark, and yet the word alignment tool card shows 98%. When I reloaded the project in wA the circle now does show 100%. The word alignment card still shows 98% on both the Tools page and Home page.
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/5bc32346-762b-48c9-b370-1c9aa2b9f6a4)

**Comment by PhotoNomad0** [comment]
@cckozie - part of the issue seems to be that chapter progress is not updated immediately.  If I click on another verse after finishing the alignment, then the chapter progress updates.

**Comment by cckozie** [comment]
Looks good in 2.0.0 (4b3ebee)
