### ISSUE TITLE
Add Edit Verse, Comment, and Bookmark to Word Alignment Tool 

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#4538]
## User Story

As an aligner who doesn't have editing privileges, I want to be able to leave a comment in the text so that I can easily make suggestions to editors. 

As an alignment manager, I want to easily edit and receive comments from the pre-alignment process. 

## Breakdown
- [M] Title bar UI + icons
~- [] Edit modal UI~
- [M] Comment modal UI
- [S] Connect Verse Edit modal back-end (reducers & actions)
- [M] Comment modal back-end (reducers & actions)
- [M] Bookmark toggle back-end (reducers & actions)

~- [L] "Alignment Complete" toggle actions + Previous & Next buttons~
 ~- [ ] When alignment complete is toggled on:~
   ~- [ ] Accept all suggestions~
  ~- [ ] Remove the WordMAP buttons & info button and display the navigation buttons ("Previous" + "Next")~
~- [L] Font actions UI + actions + 3-dot menu button~
  ~- [ ] Save font size as project-tool settings (so if I return to the project, my font sizes persist)~
  ~- [ ] Add projectsettings.json, capture data here~
  ~- QUESTION - what do we want to do with these settings?~
~- [L] "Display suggestions" UI + actions~
  ~- [ ] Save "display suggestions" as project setting ~
  ~- [ ] If suggestions are on the screen and the toggle is turned off, reject all~
  ~- [ ] Keep saving alignments, just don't display suggestions (when toggle is off)~
~  - [ ] Remove WordMAP buttons + info button when toggled off~

**Comment by benjore** [comment]
- Move alignment boxes into a card
- Building the tab bar (blue bar)
- Add badges - For each edit (or comment) increase the badge number
- Update Bookmark to include new badge UI

**Comment by lrsallee** [comment]
The dialog boxes for commenting and settings look fine. The things that I don't like are 1) having the "+" symbol take space from the Greek word section, and 2) having to do an extra mouse click to get to the edit icon, as well as other features. I would much prefer to have these icons always visible. For example, they could be on the right side of the blue "Align" bar, next to where you show the bookmark icon.

**Comment by lrsallee** [comment]
I admit that this concern partly grows out of my frustration with the current process to edit a verse in the alignment tool. I have to click twice to get to the verse, and then five times to return to the verse when I finish editing. Please, please, make this easier.

**Comment by jag3773** [comment]
@lrsallee It would still be a single click, when you hover on the "+" the options pop up.

Also, due the way the cards flow, the + button is unlikely to consume any noticeable space from the Greek.

**Comment by lrsallee** [comment]
@jag3773 That's nice that it has a hover feature—although not a cool as the hoverboard that Back to the Future promised us. But in practice, all it does is hide the icons behind a second step. I don't have to click the "+", but I do have to point to it, and then point to the one I want before I can click on it. That is another separate operation before I can click on what I want. I'm comfortable pointing with my nice wireless Mac mouse, and it is still a "busywork" step IMO. For someone working with a trackpad or a poor quality mouse, or for someone who is not all that comfortable finding small targets with a cursor, this is an unnecessary frustration, IMO. Plus, they have to know and remember that the icons they can't see are hidden there. I don't think there is any reason to put the users through that.

**Comment by jag3773** [comment]
I do understand your concern's @lrsallee .  However, the point of the Alignment tool is *alignment*, not editing (even though our teams are currently edit focused).  I'm all for reducing keystrokes, so if we can work out a solution that doesn't distract from the main point of the tool and allows a 1 click edit I'm in.

**Comment by lrsallee** [comment]
@jag3773 I might also make the same case for the comment tool. I expect that aligners in any GL are going to find a lot of issues, just as we did in English. If they don't edit the text, they will often want/need to make comments for those who will edit. In that case, I believe they will want the comment icon to be more accessible.

**Comment by benjore** [comment]
Mockups have been updated. Try again!

**Comment by lrsallee** [comment]
@benjore Yes, IMO those are much better.

**Comment by pjoakes** [comment]
I was searching for a plus symbol and not finding it. I guess that's what I get for being late to the party...

**Comment by richmahn** [comment]
@pjoakes You can click the "edited" drop-down next to "benjore commented on May 25" at the top and then click on the 3rd one from the top (at the time I write this) to see how it was with a +.

**Comment by PhotoNomad0** [comment]
@benjore - For clarity, in the alignment area title bar, these icons are actionable?  This seems inconsistent with tW where they are indicators only.  We need to investigate what is standard practice to indicate something is a clickable icon (e.g. colors, border, etc.).

**Comment by cckozie** [comment]
UI Mockups - Title Bar:
<img width="779" alt="Title bar" src="https://user-images.githubusercontent.com/8171759/71601671-1df59800-2b1a-11ea-9a53-e2337dfda4dd.png">

**Comment by cckozie** [comment]
UI Mockups - Edit
<img width="782" alt="Edit 1" src="https://user-images.githubusercontent.com/8171759/71601693-32d22b80-2b1a-11ea-9e76-3fda6cd4cc2e.png">

<img width="785" alt="Edit 2" src="https://user-images.githubusercontent.com/8171759/71601704-3e255700-2b1a-11ea-8457-06bbd002d9b2.png">

<img width="784" alt="Edit 3" src="https://user-images.githubusercontent.com/8171759/71601716-4c737300-2b1a-11ea-9df2-7fec3bbcc204.png">

<img width="775" alt="Edit 4" src="https://user-images.githubusercontent.com/8171759/71601724-55644480-2b1a-11ea-9e7b-fa6bdeb710c3.png">

**Comment by cckozie** [comment]
UI Mockups - Comments
<img width="779" alt="Comment 1" src="https://user-images.githubusercontent.com/8171759/71601754-6f9e2280-2b1a-11ea-94d2-4983bb0930a9.png">

<img width="785" alt="Comment 2" src="https://user-images.githubusercontent.com/8171759/71601756-788ef400-2b1a-11ea-83e5-b8e35cfad9df.png">

<img width="770" alt="Comment 3" src="https://user-images.githubusercontent.com/8171759/71601761-804e9880-2b1a-11ea-9586-18b86e0afd50.png">

**Comment by cckozie** [comment]
UI Mockups - Bookmark
<img width="775" alt="Bookmark" src="https://user-images.githubusercontent.com/8171759/71601782-9e1bfd80-2b1a-11ea-9fe5-b9bb1f95d875.png">

**Comment by PhotoNomad0** [comment]
@birchamp @cckozie - do we need a story for csv exporting the WA comments, bookmarks?

**Comment by PhotoNomad0** [comment]
@birchamp @cckozie - the current Verse Edit dialog is a stepper dialog that looks like:

![Screen Shot 2020-01-03 at 2 01 29 PM](https://user-images.githubusercontent.com/14238574/71743160-d16bce80-2e31-11ea-93ae-1d86e998778f.png)

I am updating it to look like in the mock up above.  But just note that this will also change how it looks in the Enhanced Scripture Pane.

**Comment by birchamp** [comment]
>  do we need a story for csv exporting the WA comments, bookmarks?

Per @jag3773 - I think the expectation is that the same info that already gets exported from these features will also get exported when used in the wA tool, at least for starters.

**Comment by cckozie** [comment]
Since it was decided to not include the last 3 features under "Breakdown" above, we will need issues to cover adding those features.

**Comment by birchamp** [comment]
Removed toggle WordAlignment suggestions from breakdown and created issue:
[Toggle WordAlignment suggestions#6638](https://app.zenhub.com/workspaces/uw---all-57a4b0551bff6d0c6f35e8eb/issues/unfoldingword/translationcore/6638)

Removed font settings from breakdown and created issue:
[Change fonts and store settings with project #6637](https://app.zenhub.com/workspaces/uw---all-57a4b0551bff6d0c6f35e8eb/issues/unfoldingword/translationcore/6637)

Removed Previous/Next navigation from breakdown and created issue:
[Change WordAlignment workflow to user previous and next buttons to navigate verses #6639](https://app.zenhub.com/workspaces/uw---all-57a4b0551bff6d0c6f35e8eb/issues/unfoldingword/translationcore/6639)

**Comment by cckozie** [comment]
Watch for:
Missing translation key when editing in scripture pane of tN or tW
![image](https://user-images.githubusercontent.com/8171759/74290158-9beeb680-4cf6-11ea-824a-136ebc0d2ca5.png)

**Comment by cckozie** [comment]
All child projects have passed QA.
