### ISSUE TITLE
tC Drops some USFM markers on USFM3 export/import

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/translationCore#4554]
In the USFM output from tC 0.9.1 some `\s5` markers are not being preserved.

Compare: 23 of them in https://git.door43.org/unfoldingWord/en_ult/src/commit/3f5c5cd4a4358ca3cac9792818cfa575311149f6/57-TIT.usfm but only 19 in https://git.door43.org/unfoldingWord/en_ult/src/commit/4d1d9fac71aa084bee2ea1aab66f539602026301/57-TIT.usfm.  You can see Larry's fix here https://git.door43.org/unfoldingWord/en_ult/commit/405298c80c1eac8524a1cc534b902be8b21234b3 .

- [ ] /p
- [ ] /s5
- [ ] /q
- [ ] others??

Need a SPIKE to be able to break it down smaller.

Related to #4559 

------------
Edit @photonomad - Updated title to be more clear that this is an USFM3 export issue.
Found issues:

Scope of this issue: 
- USFM3 export does not preserve chapter front matter => this looks small to fix to USFM3 export to output the "front" verse

The following is covered in #4645
- verses with \q and \s5 markers will have unaligned words q & s in WA => medium change to verse parsing?  May just need to run through USFM filter before parsing.
- verses with \q and \s5 markers will be flagged as invalidated and will be reset on USF3 export => seems to be due to same issue as above trying to match USFM marker to word in verse.

**Comment by lrsallee** [comment]
tC also dropped the  \p in 1ti1:1 which followed the chapter marker.

**Comment by lrsallee** [comment]
Just saw that the \p markers in the original are not followed by spaces, as other markers are. I'm wondering if that is causing a problem for tC. If so, it would be easy to add spaces after the \p markers throughout the ULT. I may run quick test on a book and see what happens.

**Comment by lrsallee** [comment]
Nope, adding space to \p has no effect. Will leave this to the experts. :)

**Comment by lrsallee** [comment]
tC also dropped all the \q markers in 1Ti 3:16.

**Comment by PhotoNomad0** [comment]
It looks like the usfm data is being preserved on input to tCore as expected:
- markers before first chapter marker are preserved in headers.
- markers between chapter marker and first verse of chapter are preserved in front matter ("front" verse)
- markers between verses are stored as part of previous verse.

Example headers:
```
[
    {
        "tag": "id",
        "content": "TIT unfoldingWord Literal Text"
    },
    {
        "tag": "ide",
        "content": "UTF-8"
    },
    {
        "tag": "h",
        "content": "Titus"
    },
    {
        "tag": "toc1",
        "content": "The Letter of Paul to Titus"
    },
    {
        "tag": "toc2",
        "content": "Titus"
    },
    {
        "tag": "toc3",
        "content": "Tit"
    },
    {
        "tag": "mt",
        "content": "Titus"
    },
    {
        "type": "text",
        "text": "\n"
    },
    {
        "tag": "s5",
        "type": "section"
    }
]
```

Example of chapter 1:
```
{
    "1": "Paul, a servant of God and an apostle of Jesus Christ, for the faith of God's chosen people and the knowledge of the truth that agrees with godliness,",
    "2": "with the certain hope of everlasting life that God, who does not lie, promised before all the ages of time.",
    "3": "At the right time, he revealed his word by the message that he trusted me to deliver by the command of God our Savior.\n\n\\s5",
    "4": "To Titus, a true son in our common faith. Grace and peace from God the Father and Christ Jesus our Savior.\n\\p",
    "5": "For this purpose I left you in Crete, that you might set in order things not yet complete and ordain elders in every city as I directed you.\n\n\\s5",
    "6": "An elder must be without blame, the husband of one wife, with faithful children not accused of reckless behavior or undisciplined.",
    "7": "It is necessary for the overseer, as God's household manager, to be blameless. He must not be arrogant, not be easily angered, not addicted to wine, not a brawler, and not a greedy man.\n\n\\s5",
    "8": "Instead, he should be hospitable and a friend of what is good. He must be sensible, righteous, godly, and self-controlled.",
    "9": "He should hold tightly to the trustworthy message that was taught, so that he may be able both to encourage others with good teaching and correct those who oppose him.\n\n\\s5\n\\p",
    "10": "For there are many people, both rebellious, empty talkers and deceivers, especially those of the circumcision.",
    "11": "It is necessary to stop them. They are upsetting whole families by teaching for shameful profit what they should not.\n\n\\s5",
    "12": "One of their own prophets has said, \"Cretans are always liars, evil beasts, lazy gluttons.\"",
    "13": "This statement is true. Therefore, correct them severely, so that they may be sound in the faith,",
    "14": "not paying any attention to Jewish myths or to the commands of people who turn away from the truth.\n\n\\s5",
    "15": "All things are pure to those who are pure. But to those who are corrupt and unbelieving, nothing is pure, but both their minds and their consciences have been corrupted.",
    "16": "They profess to know God, but they deny him by their actions. They are detestable, disobedient, and unfit for any good work.\n\n\\s5",
    "front": "\\p"
}
```


now investigating USFM export...

**Comment by PhotoNomad0** [comment]
Imported the USFM3 file on DCS site and it appears that the USFM markers are preserved.   This is looking like a USFM3 export problem only.

**Comment by PhotoNomad0** [comment]
Right now it looks like there is a problem that USFM export is not outputting chapter front matter.

Looking at quotes issue.

**Comment by PhotoNomad0** [comment]
> tC also dropped all the \q markers in 1Ti 3:16.

@lrsallee - Have a question on trying to reproduce the 1ti 3:16 and the missing quotes.  I am not seeing that problem when I import the text at https://git.door43.org/unfoldingWord/en_ult/src/branch/master/55-1TI.usfm and export it again as USFM2.  Do you have a project you can share that has alignments?

**Comment by PhotoNomad0** [comment]
Hmm...see issue exporting aligned verse with USFM3.  1ti 3:16 has words q and s in unaligned words (USFM markers) says verse is invalidated on USFM3 export even if the q&s are not aligned.

**Comment by PhotoNomad0** [comment]
#### Tasks:
- [ ] [2] Fix support for "front" verses
- [ ] [4] Add unit tests
- [ ] [2] PR review [4554]

**Comment by cckozie** [comment]
0.10.0 (4add745) 
It's much better but not perfect.
I imported [57-TIT.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/2170731/57-TIT.usfm.zip) and aligned a few words.
I exported USFM3 to this file [55-1TI3.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/2170736/55-1TI3.usfm.zip)
The imported file has 17 \p markers and the exported file has 16.
The imported file has 6 \q markers and the exported file has none.
The imported file has 45 \s5 markers and the exported file has 34.

**Comment by PhotoNomad0** [comment]
@cckozie - one file here is titus and the other is 1 timothy.

I did import your Titus zip project and aligned the first verse: 
- I have 8 \p markers in both import and export.
- there are no \q markers in imported file and export
- **there are 23 \s5 markers in imported file and 19 in the export.**  It looks like getOrderedVerseObjectsFromString() is broken that treats '\s5\n' as a text object ignoring the token (any marker that contains text).

**Comment by cckozie** [comment]
@PhotoNomad0 - Oops! Copied in the wrong file. The stats were correct. Here's the actual imported file [55-1TI.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/2172354/55-1TI.usfm.zip)
