### ISSUE TITLE
Update Submit Feedback Mechanism

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/translationCore#4555]
The submit feedback mechanism needs to be updated to send messages into our new system.  @neutrinog contact me to discuss the details of the updates.

We'll want to use SendGrid to send the message. 

See [Sendgrid API docs](https://sendgrid.com/docs/API_Reference/api_v3.html).  Get the api key from @jag3773.  The destination email should be set to help@door43.org.

**Comment by da1nerd** [comment]
We'll add integration for SendGrid in this function https://github.com/unfoldingWord-dev/translationCore/blob/develop/src/js/helpers/FeedbackHelpers.js#L17

No changes should need to be made to the UI.

**Comment by cckozie** [comment]
@jag3773 Where can the user feedback messages be viewed?

**Comment by cckozie** [comment]
0.10.1 (4a8ea79)
1. Feedback does not get sent if 'Include application logs' is checked.
2. The entered email address does not appear on the Trello card.

**Comment by RoyalSix** [comment]
Once this builds I will move to in QA

**Comment by cckozie** [comment]
@neutrinog  - The failure does occur in 0.10.1 (4a8ea79) on my machine when attempting to send feedback with the logs when a project is open in the wA tool. After that, it fails from anywhere until you restart tC. Please try that before just putting in the try/catch.

**Comment by da1nerd** [comment]
@cckozie I've added support for correctly handling circular json objects. Please check out the build for `6315307 (v0.10.1)`

**Comment by da1nerd** [comment]
e.g. https://s3-us-west-2.amazonaws.com/tc-builds.door43.org/translationCore-macos-x64-0.10.1-6315307.dmg

**Comment by cckozie** [comment]
0.10.1 (e6997db)
Feedback gets sent prior to user agreeing to Internet usage.
1. Log out (to clear Internet usage agreement)
2. Log in (do not click the check box on the 'about to use the Internet' dialog)
3. Open project in wA
4. Open send feedback dialog, enter message text, and click submit
5. Click the checkbox on the 'about to use the Internet' dialog
The feedback gets sent before clicking the 'Access Internet' button. (This does not happen when sending feedback from the projects page)
The first time I tried this test I got this message in the console:
![image](https://user-images.githubusercontent.com/8171759/42642537-afb2293e-85bc-11e8-92ec-275dd1b938ed.png)

**Comment by cckozie** [comment]
0.10.1 (88b725c) 
User feedback function fails to establish Internet connection
1. Log out
2. Log in to Door43 without checking the 'Do not show again' box on the Internet warning dialog
3. Open a project in wA
4. Open the user feedback dialog, enter a message, and click Submit
5. When the Internet warning appears, check the checkbox, then click the Access Internet button
The Internet warning dialog stays on the screen for about 7 seconds, then disappears
Nothing then appears to happen until about 30 seconds when the Unable to connect to the server alert is displayed even though I have a good Internet connection. This error is displayed in the console:
![image](https://user-images.githubusercontent.com/8171759/42769290-5dbe530e-88e7-11e8-84fb-e751f499924c.png)
Clicking the Submit button again produces the same outcome
The user feedback function is the only one that thinks there is not Internet connection. I am able to search for and import D43 projects as well as upload projects to D43.

**Comment by da1nerd** [comment]
@cckozie this error  you showed above is indeed a network error. There's nothing we can do except maybe decrease the amount of time you have to wait until the alert appears.
Since you are only seeing this with the feedback the network problem will be with the sendgrid servers.

The best you or anyone else could do in this case would be to try again.

**Comment by cckozie** [comment]
@neutrinog Does the feedback actually work for you from inside wA?
This is what I'm seeing in an older build (e6997db from 7/11)
- Feedback is successful within a couple seconds from both the projects page and tools page
- Feedback is successful but takes about 30 seconds from alignment tool

This is what I'm seeing in the latest build (88b725c) 
- Feedback is successful within a couple seconds from both the projects page and tools page
- Feedback is not successful from alignment tool. Cannot connect to server message is displayed after about 30 seconds.

**Comment by da1nerd** [comment]
The feedback is working for me. I tested it on both the linux and macOS builds.
I do see what you are saying with the slow submission in wA. I think this is due to serializing all of the data loaded by the tool. We could avoid that by excluding some of the data.

**Comment by cckozie** [comment]
Sending feedback does work from within the tools in 0.10.1 (2f933f7), but there needs to be some indicator that something is happening between the time when the Submit button is clicked and when the Success or Failure message is displayed.

**Comment by cckozie** [comment]
Still no processing indicator in 0.10.1 (b411d84), but the success message is displayed almost immediately after sending.
