### ISSUE TITLE
Tokenizer: Alignment tool drops the number "430" from Gal 3:17.

### ISSUE THREAD

**Issue by lrsallee** [unfoldingWord/translationCore#4559]
The number is missing from the English list. In my project, I edited the text for other reasons, confirming that it was present in the code. However, when I saved that edit, the number was still missing from the list.

**Comment by da1nerd** [comment]
I have confirmed this issue. This is a deficiency in https://www.npmjs.com/package/string-punctuation-tokenizer

**Comment by mannycolon** [comment]
> I have confirmed this issue. This is a deficiency in https://www.npmjs.com/package/string-punctuation-tokenizer

@neutrinog string-punctuation-tokenizer is actually a NPM package that we own haha

**Comment by da1nerd** [comment]
exactly! Just pointing it out so we know what to fix :)

**Comment by cckozie** [comment]
1.0.0 (4bd6856)
![image](https://user-images.githubusercontent.com/8171759/46312673-60cd6680-c58b-11e8-9090-acf02fa4870a.png)

**Comment by cckozie** [comment]
I'm not seeing any difference in this build vs what was released in 1.0
1.0.0 (ea3713f) 
![image](https://user-images.githubusercontent.com/8171759/46312927-22847700-c58c-11e8-9e9c-a3701549e618.png)

**Comment by cckozie** [comment]
1.0.2 (6ab77c0)
The number 430 now appears in the scripture pane for the target language, ULB, and UDB, but it does not appear in the ULT, UST, or word bank. For whatever reason, it also does not appear in the local resource json files for the ULT and UST.
This test was performed after running a resources download for English.
![image](https://user-images.githubusercontent.com/8171759/46768815-4001c100-ccaf-11e8-9f8b-a302f3a016c3.png)

**Comment by cckozie** [comment]
[49-GAL.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/2493708/49-GAL.usfm.zip)

**Comment by RoyalSix** [comment]
@cckozie I believe the UST and ULT simply do not contain numbers in that verse. I was able to fix the word list

**Comment by RoyalSix** [comment]
https://tc-builds.door43.org/build/release-v1.0.2/translationCore-macos-x64-1.0.2-a5a105b.dmg

**Comment by cckozie** [comment]
Works in 1.0.2 (8c6f266) (ULT and UST are missing the number in their texts)
