### ISSUE TITLE
Fix duplicate username in Successful Project Upload dialog

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#4577]
Wondering if this has to do with app localization.

To duplicate: 
- Upload a project to Door43

![Screen Shot 2018-06-06 at 4.45.06 PM.png](https://images.zenhubusercontent.com/55e5f3984f7a08fbb7f4a658/f7ac9297-0144-4ad2-8982-9ba1787dea62)

**Comment by elsylambert** [comment]
##1.2.0 (b219729) 
Still seeing this issue, Names are doubled. when Project is uploaded to Door43.
![image](https://user-images.githubusercontent.com/51806180/60606744-e6d04500-9d89-11e9-9bed-0d59d1440c37.png)

**Comment by elsylambert** [comment]
Verified in #1.2.0 (299b3f7). The issue has been fixed for the duplicate username in Successful Project Upload dialog.
