### ISSUE TITLE
Expanded scripture pane shows alignments for one verse in tW

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4612]
0.10.0 (e6fe53e) 
When in tW, the expanded scripture pane shows the alignments for the verse that was in focus when the expanded pane was opened. I don't know if that is the desired behavior or not. Should we keep it as is, or show all alignments, or show no alignments?
![image](https://user-images.githubusercontent.com/8171759/41370285-d6666548-6f0c-11e8-91cc-c5e8bf0954f9.png)

**Comment by benjore** [comment]
It is functioning correctly - showing all selections + alignments.
