### ISSUE TITLE
Update UGNT to ver. 0.2

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#4618]
Pending the UGNT ver 0.2 release.

Available in the catalog at https://git.door43.org/Door43-Catalog/el-x-koine_ugnt .

**Comment by jag3773** [comment]
Available in the catalog at https://git.door43.org/Door43-Catalog/el-x-koine_ugnt .

**Comment by cckozie** [comment]
Spot checked 1.0.0 (a40ef81). Differences in 1Peter were correct.
