### ISSUE TITLE
wA Tool Bug: target words showing up out of order in alignment box

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#4619]
From Larry

>In the alignment tool, there is a problem with the order of the English words when dropped on “Θεσσαλονικέων.” It reads “the of Thessalonians.” I can’t figure out why. Please see https://git.door43.org/katalakay/en_1th.

This example happens in 1:1 in the above project (using v.0.9.1)

**Comment by cckozie** [comment]
After moving the words back to the word list, this is not a problem in 0.10.0 (e6fe53e).
However, I did get the changes have caused alignments to be reset on 4 of the 10 aligned verses. This needs more investigation. We need to make sure that these issues do not occur when users upgrade from 0.9 to 0.10.

**Comment by cckozie** [comment]
I loaded the project in 0.9.1 and verified that the words were out of order.
I upgraded to 1.0.0 (e375ee0).
Upon loading the project in wA in 1.0, the words now occur in the correct sequence.
I did not get any alignments reset messages.
Closing the issue.
