### ISSUE TITLE
Side Menu design inconsistencies

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#4627]
# Translation Words Tool Menu

The menu in this tool has two minor visual issues.

## Group Progress Circle Color

Color of progress circle doesn't appear to match any other blue on the screen. See screenshot below.
NOTE: This is fixed in  0.10.0 (a48d474)
## Menu Filter Width

Width of the Menu Filter Background does not fill the entire width of available space. See the same screenshot below.
NOTE: This has changed in  0.10.0 (a48d474), but is still an issue. I think the empty space is the space that was previously used by the vertical scroll bar. It is still a problem.

![Screen Shot 2018-06-18 at 6.00.20 PM.png](https://images.zenhubusercontent.com/568146ca638e718c995faa57/d46b8d09-7d59-4885-9f8f-fdcf4021f82d)

# Word Alignment Tool Menu

Menu in this tool seems to have more issues than translationWords tool.
NOTE: These problems are fixed in 0.10.0 (a48d474)

### Chapter 2

In the below screenshot Chapter two has an awkward height difference that makes it 2x-3x of the normal height. 

![Screen Shot 2018-06-18 at 5.51.17 PM.png](https://images.zenhubusercontent.com/568146ca638e718c995faa57/dd902edf-8b34-4ef3-a133-9a896d7fabe6)

### Chapter 3 

Chapter 3 has nearly a 2x difference when not selected but normal when selected.

![Screen Shot 2018-06-18 at 6.17.04 PM.png](https://images.zenhubusercontent.com/568146ca638e718c995faa57/76e79800-1822-4a5a-a76b-daecd0b0c027)

![Screen Shot 2018-06-18 at 6.17.17 PM.png](https://images.zenhubusercontent.com/568146ca638e718c995faa57/87bc717c-c186-4511-8bf2-bb4b16db80cc)

## Group Progress Bars not working

Look at the above screenshots when Chapter 1 is selected and notice that the progress bar is stuck as if no work was done whether selected or not.

**Comment by cckozie** [comment]
All but two of these issues have been fixed.
The problem with the filter UI width has been moved to #4633 
The problem with the percentage complete is part of #4319

**Comment by benjore** [comment]
Is this still a problem?

**Comment by cckozie** [comment]
1.1.3 (240da43)
The first issue noted, color of the progress circle, is true in terms of the tW tool. However. It is exactly the same color as the blue bar on the left side of the words in the word bank in wA.
The second issue noted, the gap in the background of the menu filter, has been fixed in the new menu.
Closing the issue.
