### ISSUE TITLE
Alignment Problem on Project Details Prompt

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#4630]
On the new project details prompt.  In certain cases the "Language Name" and "Translation Identifier" fields to not line up vertically.  The issue seems to be that heights of the different fields seem to change when there are warnings, and in the case of the "Language Name", it get's even taller when no text is in field.  

First case - no warnings - lines up:
![Untitled3.png](https://images.zenhubusercontent.com/564e463c638e718c995eb353/32f86df0-1a5e-415b-889e-bcb1d0b244d2)

Second case - warnings with text - lines up:
![Untitled.png](https://images.zenhubusercontent.com/564e463c638e718c995eb353/b4a15e2c-2b39-434b-ad01-8b2eec404455)

Third case - warnings, but with no text in Language name and the component get's taller:
![Untitled2.png](https://images.zenhubusercontent.com/564e463c638e718c995eb353/92a9d907-fcc4-438a-9be6-9e70d0b18ddf)

**Comment by elsylambert** [comment]
Retested in 2.0.0 (4b3ebee). Issue still exists.

**Comment by cckozie** [comment]
No longer seeing the problems in 2.2.0 (2375ae5)
