### ISSUE TITLE
Alignment Complete Toggle

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#4661]
## User Story

As an aligner, I want to be able to indicate that a verse's alignment is complete even if there are unaligned words so that tC will indicate that all verse alignments are complete. 

## Specs
- [x] If all of the target & original language words are aligned, the toggle switches on automatically
- [x] If there is any edit or invalidation to the verse when the toggle is on, then the toggle switches off automatically.
- [x] The toggle is directly linked to the green checkmark in the side menu
- [x] Abbreviate the WordMAP buttons + add pop-overs with a 1-second delay
  - [x] "Refresh MAP-generated suggestions."
  - [x] "Accept all MAP-generated suggestions."
  - [x] "Reject all MAP-generated suggestions."

## Notes
- This issue does not address other new features seen in the mockups. 

![image.png](https://images.zenhubusercontent.com/55e5f3984f7a08fbb7f4a658/4d4b995b-1471-4e79-9519-c8a62d6713a7)

![image.png](https://images.zenhubusercontent.com/55e5f3984f7a08fbb7f4a658/8a7fbad5-c4f4-4260-bffa-b450c250ba54)

**Comment by da1nerd** [comment]
notes to self.
* We'll need to store the completion state in a file within the project.
* If the api validation method finds invalid alignments we'll need to reset the completion.
* The api method to check if the verse is finished will need to be updated to read the completion state.

**Comment by cckozie** [comment]
Not seeing the toggle in  0.10.0 (0ef3ec4)

**Comment by da1nerd** [comment]
Here's the last PR that adds the actual toggle switch https://github.com/translationCoreApps/wordAlignment/pull/52

**Comment by cckozie** [comment]
Testing on project 
[en_ult_tit_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/2180727/en_ult_tit_book.zip)

## Specs
- [ ] If all of the target & original language words are aligned, the toggle switches on automatically  (NOT ALWAYS WORKING. SEE v. 3:4)
- [x] If there is any edit or invalidation to the verse when the toggle is on, then the toggle switches off automatically.
- [x] The toggle is directly linked to the green checkmark in the side menu
- [x] Abbreviate the WordMAP buttons + add pop-overs with a 1-second delay
  - [ ] "Refresh MAP-generated suggestions." (NO POPUP)
  - [ ] "Accept all MAP-generated suggestions." (NO POPUP)
  - [ ] "Reject all MAP-generated suggestions." (NO POPUP)

**Comment by cckozie** [comment]
@neutrinog Are these problems that will go away when the Hindi is updated?
![image](https://user-images.githubusercontent.com/8171759/42572624-7649dde6-84df-11e8-8246-5343dcea8dce.png)
![image](https://user-images.githubusercontent.com/8171759/42572766-d5a08880-84df-11e8-875a-5c9cfcab29be.png)

**Comment by da1nerd** [comment]
@cckozie yes.
I see the hindi file already updated in the repo. So the latest develop build should have that, though it will just display English since no one has actually localized it yet.

**Comment by cckozie** [comment]
0.10.1 (88b725c)
Alignment Complete Toggle does not automatically get set when 'all of the target & original language words are aligned'
[en_ult_1ti_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/2198473/en_ult_1ti_book.zip)
Open this project and finish aligning 1:1 so that all of the words in the word list have used and all of the Greek have at least one word aligned to them. The alignment complete switch does not toggle to On.

**Comment by da1nerd** [comment]
@cckozie I followed your instructions with the latest build (`2f933f7`) and the alignment complete toggle works properly.

I tested this on Linux and macOS.

**Comment by cckozie** [comment]
Works in 0.10.1 (2f933f7)
