### ISSUE TITLE
Bottom buttons on translation words window are not contained within pane on low res device

### ISSUE THREAD

**Issue by bspidel** [unfoldingWord/translationCore#4667]
## Story Explanation
Buttons overlap pane boundry

# Steps to Repeat
1 Set device for 720p
2 Load project
3 Launch Translation Words
Note bottom edge of bottom buttons are outside of pane

### User Story

As a [type of user], I want [some goal] so that [some reason].

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by RoyalSix** [comment]
![screen shot 2018-06-28 at 2 23 45 pm](https://user-images.githubusercontent.com/16184018/42056382-a20d9de6-7adf-11e8-90ed-6d8c2a08ac7c.png)

**Comment by benjore** [comment]
#5779
