### ISSUE TITLE
Need to fail gracefully when opening an unaligned book in tW

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4678]
0.10.0 (3c6ba1c)
When opening an unaligned book in tW the user gets an ugly system error message and the app crashes.
![image](https://user-images.githubusercontent.com/8171759/42331222-8345aa7e-803a-11e8-957b-fb61d7567b03.png)

**Comment by benjore** [comment]
@cckozie Can you give steps to reproduce this one? (After the release is fine.)

**Comment by cckozie** [comment]
Import a Matthew project and open in tW.
[41-MAT.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/2237534/41-MAT.usfm.zip)

**Comment by benjore** [comment]
@cckozie Can you verify that this is only occurs in developer mode?

**Comment by cckozie** [comment]
@benjore Yes, it's only in dev mode. The Load button is disabled on projects that are not Titus unless in dev mode.
