### ISSUE TITLE
Rev 5:12 of the ULT gets truncated in the scripture pane

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4688]
0.10.0 (0ef3ec4)
![image](https://user-images.githubusercontent.com/8171759/42400155-1ab68cb0-8136-11e8-820a-7bca62ded811.png)

Related to #5051

**Comment by benjore** [comment]
I suspect it is a mishandling of the `\pi` markers. Also in Revelation 5:13, 7:10, 7:12.

**Comment by PhotoNomad0** [comment]
This Should be fixed in #5051

**Comment by PhotoNomad0** [comment]
@cckozie - verified in https://tc-builds.door43.org/build/release-v1.0.2/translationCore-win-x64-1.0.2-34ddb63.setup.exe

**Comment by jobbyp** [comment]
![image](https://user-images.githubusercontent.com/38230054/47530280-24ceae00-d878-11e8-8033-299b4dd30d52.png)

Revelation 18 does not have verse 25 and tC shows it as a broken link. can this be removed

**Comment by cckozie** [comment]
Fixed in 1.0.2 (3943b93)
