### ISSUE TITLE
Some source boxes show green background on verses which have had text deleted

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4700]
0.10.1 (66bbba3)
1. Do a usfm2 export of a partially aligned project.
2. Edit the usfm2 export file to delete a couple verses that had been aligned.
3. Import the edited file and choose the Overwrite option
4. Open the reimported project in wA.
Alignment screen before the reimport:
![image](https://user-images.githubusercontent.com/8171759/42479288-b638d8d2-839d-11e8-96f8-df4e5d6b24ac.png)

Alignment screen after the reimport:
![image](https://user-images.githubusercontent.com/8171759/42479303-ccb25304-839d-11e8-8215-d67da8a2fa2d.png)

**Comment by da1nerd** [comment]
This has been fixed. I'm waiting for some feedback on #3899 before creating a PR since I've already done work there that may conflict.

**Comment by cckozie** [comment]
Works correctly in 0.10.0 (4a8435c) and 0.10.1 (bb230ee)
