### ISSUE TITLE
Build downloads are slow on Concourse server

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4704]
Today one download timed out. The next one worked but took over 11 minutes. Speedtest was showing 10-20 MB but the download was running at .5MB.
All downloads now take 2 - 5 times as long as they did on the surge server.

**Comment by jag3773** [comment]
The builds are hosted on S3, if we really need faster downloads we can put CloudFront on top of the S3 bucket which would speed them up.

**Comment by cckozie** [comment]
This is now N/A
