### ISSUE TITLE
wA Button Refinement

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#4706]
### Features / Specifications
- [x] If there are no MAP suggestions on the screen, the "Accept" and "Reject" buttons should be inactive.
  - [x] So if MAP makes suggestions, both buttons will be active. If they click one of the buttons, then the action is performed and both buttons become inactive again. 
  - [x] "Refresh" should always be active
- [ ] The "Refresh" button needs some indication that it is doing something. Previous specs had a toast appear. 

### Definition of Done
- [ ]
- [ ]
- [ ]

**Comment by cckozie** [comment]
0.10.1 (ee3f8f5)
When there are existing suggestions for a verse and the Refresh button is clicked, the 'No new suggestions' toast is not being displayed.

**Comment by da1nerd** [comment]
It appears that has not made it into the build yet. It should work in build `b30f24`.

**Comment by cckozie** [comment]
Works in 0.10.1 (b411d84)
