### ISSUE TITLE
Overwrite/merge of usfm project fails when not in developer mode

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#4717]
## Build
tCore build 0.10.1 (b64ddc5)

### Error:
Overwrite/merge of usfm project fails when not in developer mode

 ### Steps to reproduce
  - switch out of developer mode
  - import Titus USFM file to create new project
  - make a couple alignments
  - export as USFM3 file
  - reimport the USFM3 file just exported
  - set project details that same and click overwrite
  - select overwrite project
  - will see message that only New Testament projects are supported even though this is a Titus project.

**Comment by cckozie** [comment]
I moved this problem to #3559
