### ISSUE TITLE
Errors in console with project that is missing first verse.

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#4719]
### Build:

Found in translationCore 0.10.1 (b64ddc5) 

### Error:

![error.png](https://images.zenhubusercontent.com/564e463c638e718c995eb353/3741a9dc-5f70-46ac-88c5-5cff863204fa)

### Project:

https://git.door43.org/photonomad0/Test_Projects/raw/branch/master/fr_tit_text_ulb.tstudio

**Comment by PhotoNomad0** [comment]
@neutrinog - seeing this in WA with any project when you select a verse that is empty in target translation.

**Comment by da1nerd** [comment]
that error does not appear to be related.

**Comment by PhotoNomad0** [comment]
My goof - had an old file in wa node_modules
