### ISSUE TITLE
Had to delete translationCore folder from user folder to get build  0.10.1 (b64ddc5) to install and run

### ISSUE THREAD

**Issue by bspidel** [unfoldingWord/translationCore#4720]
### User Story
After several attempts to install and start (the first time) the referenced build on a Win10 maching, I removed c:\\Users\Owner\translationCore
The next attempt to install/start succeeded

The installs apparently succeeded but when starting tCore from the desktop Icon, the splash screen would show loading but never complete.

Also true for build 0.10.1 (2f933f7)

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by cckozie** [comment]
Cannot duplicate
