### ISSUE TITLE
Project information card on large display truncates left side of language information

### ISSUE THREAD

**Issue by bspidel** [unfoldingWord/translationCore#4721]
### User Story
On a 23 inch monitor in portrait mode, the left side language information if the project information pane of the project page is truncated.

![projectpage.PNG](https://images.zenhubusercontent.com/56a017e5638e718c996041e9/8a39c21f-be1e-49d8-a4df-c55a595a1b9d)

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by cckozie** [comment]
@bspidel Might this be a problem with the resolution set for the driver for the monitor? On my 27" monitor I'm not seeing that problem (although the frame could use some reformatting).
![image](https://user-images.githubusercontent.com/8171759/43013283-0ae83dbe-8c0e-11e8-91ec-a0ca4ef22684.png)

**Comment by cckozie** [comment]
The same problem exists on my laptop screens if I have the dev tools sidebar open.
![image](https://user-images.githubusercontent.com/8171759/45713164-eac10c80-bb53-11e8-9210-9fae6d35bab0.png)

**Comment by cckozie** [comment]
Dup of #4578
