### ISSUE TITLE
Why is the release labeled 0.10.1 instead of 0.10?

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4732]
### Prerequisites

* Put an X between the brackets on this line if you have done all of the following:

- [ ] I have searched the [issues](https://github.com/unfoldingWord-dev/translationCore/issues) of this repository and believe that this is not a duplicate.

### Description

[Description of the issue]

### Steps to Reproduce

**Screenshots**

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

### Context

**Enviorment**
| Tech         | Version |
|--------------|---------|
| tc           | v0.?.?  |
| build #      |         |
| OS           |         |

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by PhotoNomad0** [comment]
@cckozie - I think manny already fixed this.

**Comment by cckozie** [comment]
Current is 0.10.0 (26126c1)
