### ISSUE TITLE
Changing to Another Language, some text not localized.

### ISSUE THREAD

**Issue by bspidel** [unfoldingWord/translationCore#4737]
### User Story
Build x64, Win10, 0.10.1, 2f933f7
The following strings are not Localized:
 - Browser bar 
     - app name, 
 - Home page: 
     - App name, Tool names, 
     - instructions: app name, 
 - Tool Page: Tool names, 
 - Project Page: Book titles and languages, gateway language selection: language names 
 - Statement of faith, 
 - license

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by PhotoNomad0** [comment]
I think some of those are intentional (see nonTranslatable.js).  Also legal documents have to be vetted in every local, not just translated.  Also data in manifests we do not localize.

**Comment by cckozie** [comment]
These are all working as designed or included on other issues.
