### ISSUE TITLE
Error in Console log: No Checker in WA tool

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#4746]
### Fails
 - [ ] Opening WA tool on Titus Project

![Screen Shot 2018-07-20 at 6.43.17 AM.png](https://images.zenhubusercontent.com/564e463c638e718c995eb353/e85898fc-c558-4174-8724-4c8acbb4a69f)

**Comment by cckozie** [comment]
Still an issue in 2.0.0 (4b3ebee)

**Comment by cckozie** [comment]
Not seeing this error in 2.2.0 (2375ae5). There are other errors that should get caught based on #6733
