### ISSUE TITLE
In tW tool, Check shown as completed though no selection has been made

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#4747]
### Fails
 - [ ] In tW tool, Apostle is shown as completed though no selection has been made (note that it only seems to be this first check selected):
![Screen Shot 2018-07-20 at 6.55.45 AM.png](https://images.zenhubusercontent.com/564e463c638e718c995eb353/0a6ba2f7-a7f6-494d-81b5-21b7fc615e33)

## Additional Context:

Happens in this project with no alignments:

[en_tstf_tit_book.zip](https://app.zenhub.com/files/65028237/885c1883-f1a6-4640-82ee-f7ffb9760e69/download)

**Comment by benjore** [comment]
Dup of #4774
