### ISSUE TITLE
Broken link icons appear then quickly disappear by verses that have reset alignments

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4768]
0.10.0 (26126c1)
https://git.door43.org/tc02/es_fail_tit_book

Load this project in wA and note the alignments in 1:1
Switch over to tW and go 1:1 in the group 'apostle...'
Select words 'a servant'
Click Save
Click Save & Continue
Click on the group 'blameless'
Expand the scripture pane and open verse 1:1 for editing
Change the words 'a servant' to 'an apostle'
Click Next, then choose a reason and click Save
Click OK on the 'alignments reset' alert (I'm writing up the multiple alerts problem elsewhere)
Close the expanded scripture pane
Load the project in wA and notice that the broken link displayed by verse 1:1 briefly appears and then disappears

Ben: In this case, the icon should not appear at all. The warning is sufficient notification for the user that something has been invalidated.

**Comment by da1nerd** [comment]
Further description of what's happening.

This is due to the user having the verse opened when it was invalidated. 
Visiting a verse removes the broken link icon because they have "viewed it".

**Comment by elsylambert** [comment]
Retested in 2.0.0 (4b3ebee). Not seeing this issue.
