### ISSUE TITLE
'some selections are no longer valid' alert is not displayed when edits are performed in word alignment

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4769]
The tW 'some selections are no longer valid' alert should be displayed when edits performed in wA affect tW selections. 
Load a Titus project and make some selections in tW
Open the project in wA
Make an edit in wA that invalidates one of the tW selections done above
Notice that the 'some selections are no long valid' message is not displayed, so the user has no idea that they have broken a selection.

- [ ] The message should show up immediately in wA
- [ ] The message should also show up when I load tW and load the invalidated check

**Comment by da1nerd** [comment]
There are lots of complications in this pattern that will need to be discussed in detail. The tricky part will be to maintain continuity between the tools while at the same time keep them loosely coupled.
Fixing this without proper planning will cause trouble for us in the future.

**Comment by da1nerd** [comment]
Also this isn't a bug because it was never a feature in the first place ;)

**Comment by cckozie** [comment]
Still broken in 1.0.0 (e375ee0)

**Comment by PhotoNomad0** [comment]
@cckozie - it looks like this has been fixed

**Comment by cckozie** [comment]
The referenced alerts are displayed as expected in 2.1.0 (0a80f05)

**Comment by elsylambert** [comment]
The alert is displayed in wA for invalidation in 2.1.0 (d0a11e7).
