### ISSUE TITLE
Check marks displayed in tW when there is no selection

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4774]
0.10.0 (9b04f29)
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/d25b7def-917f-4f3c-985b-2c24778e6262)

1. I imported this file [57-TIT.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/2232923/57-TIT.usfm.zip)

2. I fully aligned verse 1:1 
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/cfa67b36-8178-42cc-838f-0d3b2dedfb4b)
3. I went back to the projects page, then loaded the project in tW. Notice that the first check has the check mark even though no selection has been made.

**Comment by benjore** [comment]
Note: 

- The checkmark above the check window shows correctly. 
- The progress circle for each check group also works correctly. 
- The filter filters correctly (even though it doesn't match with the improper green checkmark)

**Comment by cckozie** [comment]
It appears that tW is using the flag for completions in wA. Setting the Alignment complete switch on a verse in wA causes the checkmark to be displayed by that verse in tW.

**Comment by da1nerd** [comment]
The verse complete status from wA was mistakenly connected to tW. We'll just need to point the tW state to this instead
