### ISSUE TITLE
Alignment reset warning is not appearing in wA when edits are performed in tW

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4775]
## Specs
- [ ] Whenever a tool is opened and there are invalidated checks/alignments, throw the invalidated data  warning.

0.10.0 (9b04f29)
[57-TIT.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/2232952/57-TIT.usfm.zip)

1. Import a good Titus usfm2 project and fully align verse 1:1 as in this screenshot
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/cfa67b36-8178-42cc-838f-0d3b2dedfb4b)

2. Click on verse 1:2 in the menu
3. Switch over to tW and edit verse 1:1 to change 'an apostle' to 'the apostle'
4. Load the project in wA and notice that the alignments reset alert is not displayed, but the broken link icon is displayed on verse 1:1
5. Complete the alignment with the new word
6. Edit the verse in wA to change it back to the original 'an apostle'. Notice that the alignments reset warning and the edit icon are displayed, but the broken link warning is not. (This may be the desired behavior since the focus is on the verse that was edited.) The broken link is displayed if the focus is on a different verse when the editing on 1:1 is performed.
Ben: This is desired behavior because the broken link disappears when you navigate to a verse that has been invalidated. 
![image](https://user-images.githubusercontent.com/8171759/43278114-b3d7a502-90cf-11e8-8a12-14d08f931889.png)

**Comment by elsylambert** [comment]
Retested in 2.0.0 (4b3ebee). Not seeing this issue.
