### ISSUE TITLE
Check box used where radio functionality enforced

### ISSUE THREAD

**Issue by bspidel** [unfoldingWord/translationCore#4780]
### User Story
As a user, I want the check boxes on the Online Import Project Search page to be replaced by radio buttons instead of check boxes, as only one may be selected, so that I can use my intuition when selecting a project
### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by cckozie** [comment]
duplicate
