### ISSUE TITLE
Question about reimporting project with missing verses

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4782]
When reimporting a project with missing verses in the reimport file, do we want the primary button on the Missing Verses page to have the text 'Overwrite' or 'Continue'?
In that same case, do we want the text on the 'Canceling...' alert to be the same on a reimport as on a standard import?
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/4d1dc43e-0adb-4ed2-af4d-ad42b479af1a)

![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/f9453a60-371a-4c05-874d-d2f1876771a5)

**Comment by benjore** [comment]
"Overwrite" should be "Continue"

I'm fine with the "Cancel Import" staying the same.

**Comment by cckozie** [comment]
No longer a problem in 2.0.0 (4b3ebee)
