### ISSUE TITLE
Empty green Greek box in wA project

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4784]
0.10.0 (6492329)
CASE 1: (STILL BROKEN IN 1.0.0 (0fe0fb6) )
[en_alck_tit_book 2.zip](https://github.com/unfoldingWord-dev/translationCore/files/2241423/en_alck_tit_book.2.zip)
I'm not sure of the steps to recreate this. The attached project is the result of multiple reimports with some changed text.
Clicking the Refresh button indicates there are no new suggestions
Clicking the Accept button clears the green background
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/30e5a459-4db8-4acb-9c13-322eabce74ef)

I'm not sure this is the same use case, but here is one way to replicate the problem.
This is a fully aligned and partially checked English Titus project. Drop this project in the projects folder.
[en_alck_tit_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/2236156/en_alck_tit_book.zip)

This is a usfm2 English Titus project with edits made to the first 3 verses of chapter 1. Import this file and give it the same language (en) and translation id (alck), then choose the overwrite options.
[57-TIT-four.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/2236160/57-TIT-four.usfm.zip)

This is the alignments of 1:3 before the overwrite
![image](https://user-images.githubusercontent.com/8171759/43327873-3475c3bc-9182-11e8-9a83-acb5a4151135.png)

This is the alignments of 1:3 after the overwrite. Notice that there is an empty green box for τοῦ which before the reimport was merged with Σωτῆρος. The change caused to this verse from the reimport was Savior being changed to savior.
![image](https://user-images.githubusercontent.com/8171759/43327894-41518c06-9182-11e8-94d0-7a0fc05715ad.png)

CASE 2: (THIS IS FIXED IN 1.0.0 (0fe0fb6))
1. Open an unaligned project in the wA tool
2. Join any two Greek words
3. Click Refresh
![image](https://user-images.githubusercontent.com/8171759/43415474-3d100494-93fb-11e8-92b1-a12e33ee68fe.png)

![image](https://user-images.githubusercontent.com/8171759/43415396-0f3dab2a-93fb-11e8-89f5-05334cc7e295.png)

**Comment by cckozie** [comment]
I'm not sure this is the same use case, but here is one way to replicate the problem.
This is a fully aligned and partially checked English Titus project. Drop this project in the projects folder.
[en_alck_tit_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/2236156/en_alck_tit_book.zip)

This is a usfm2 English Titus project with edits made to the first 3 verses of chapter 1. Import this file and give it the same language (en) and translation id (alck), then choose the overwrite options.
[57-TIT-four.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/2236160/57-TIT-four.usfm.zip)

This is the alignments of 1:3 before the overwrite
![image](https://user-images.githubusercontent.com/8171759/43327873-3475c3bc-9182-11e8-9a83-acb5a4151135.png)

This is the alignments of 1:3 after the overwrite. Notice that there is an empty green box for τοῦ which before the reimport was merged with Σωτῆρος.
![image](https://user-images.githubusercontent.com/8171759/43327894-41518c06-9182-11e8-94d0-7a0fc05715ad.png)

**Comment by da1nerd** [comment]
@cckozie there's an empty green box because Word MAP is suggesting that the two words be split instead of joined. Anything green is a suggestion, even if it's just a source token.

The accuracy of this will be improved as we improve Word MAP.

**Comment by cckozie** [comment]
Seems like if it thinks they should be joined there should be suggested alignments for them too. I think a user will find it confusing to see empty green boxes after clicking Refresh. Need @benjore to weigh in on this.

**Comment by cckozie** [comment]
[en_impt_tit_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/2259716/en_impt_tit_book.zip)
THIS IS FIXED IN 1.0.0 (0fe0fb6) 
When I return all words in a verse to the word list and then click Refresh, several suggestions are made for alignments, and one or more Greek word boxes show a green background even though no English word has been suggested. This is the case on pretty much any verse.

![image](https://user-images.githubusercontent.com/8171759/43679422-79062fb2-97ea-11e8-86f4-9f50f04486e0.png)

**Comment by da1nerd** [comment]
This is related to #4700. It's actually a duplicate.

**Comment by benjore** [comment]
Goal A: WordMAP should only make suggestions to Greek words that have no alignment and have not been merged. WordMAP should only make suggestions to target words that are in the word bank.

Goal B: There should never be a time where an alignment box is green but there is no suggested alignment in the box.

**Comment by PhotoNomad0** [comment]
@neutrinog - no PR here to review, but was "In Review"

**Comment by da1nerd** [comment]
you just merged it in!

**Comment by cckozie** [comment]
Case 1 is fixed in 1.0.0 (71a9a28)
