### ISSUE TITLE
As a user, I want to make a comment on a verse check that has no selection so that I can note why I am not making a selection

### ISSUE THREAD

**Issue by bspidel** [unfoldingWord/translationCore#4789]
### User Story
I can comment on a verse check
1  that has no verse text
2 that has no keyword text selected

But I cannot comment on a verse for which I have made no selection.
What if I want to explain why there is no selection?

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by cckozie** [comment]
@bspidel I don't understand your description. I have no trouble commenting on any verse in tW.
Verses without selections come up automatically in Select mode, so if that's the case you first need to click Cancel, then Comment.
Let me know if you're seeing something else.
