### ISSUE TITLE
Launching tW warns of invalidated alignments but filtering on invalidated shows "No results"

### ISSUE THREAD

**Issue by bspidel** [unfoldingWord/translationCore#4796]
#### Steps to Repeat:
- Install tCore x64, Win10, 0.10.0, 6ea8367
- Import titus project with all words aligned
- Launch tW
- Note alert about invalidated alignments
- Filter on "Invalidated"
- Note response of "No result"

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by cckozie** [comment]
@bspidel The warning is about invalidated alignments (wA stuff), not reset selections (tW stuff). This  is a known issue.
