### ISSUE TITLE
I see USFM tags in Expanded Verse Check Pane.

### ISSUE THREAD

**Issue by bspidel** [unfoldingWord/translationCore#4799]
### User Story
Steps to Repeat:
1 install Build: x64, Win10, 0.10.0, 6ea8367
2 load titus
3 Launch tW
4 Select Believe Titus 1:15
5 Open Expanded Verse Check
6 Scroll to verse 9

Note USFM tags in attached image ![usfm-tags.PNG](https://images.zenhubusercontent.com/56a017e5638e718c996041e9/c1bca58d-42c6-4894-9ff2-745534695cd9)

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by cckozie** [comment]
@bspidel Working as designed. Those usfm tags need to be there so they can be edited.
