### ISSUE TITLE
Sync Error for own project

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#48]
When getting my own project from D43, I can work on the checking and when I try to sync I get this:
![screen shot 2016-08-19 at 10 42 25 am](https://cloud.githubusercontent.com/assets/118073/17813578/e4dbc1cc-65f9-11e6-9d7f-fd07f408e568.png)

My project has this in the .git/config:

```
[remote "origin"]
    url = https://git.door43.org/klappy/ilo_luk_text_ulb.git
```

**Comment by klappy** [comment]
Looks like when I click Yes, even though it already existed on my account, it works after that.

**Comment by ihoegen** [comment]
So it actually uses the repo property of the tc-manifest.json when it comes to pushing to remote repositories. It also updates this tc-manifest on the disk
