### ISSUE TITLE
Broken link icons are not being displayed in wA when the selected verse is edited

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4801]
0.10.0 (d8df89a) 
https://git.door43.org/ult-pre-alignment/en_tit

Import this fully aligned Titus project.
Open in wA.
Make and save an edit to the verse that is selected. Notice that the broken link icon is never displayed.
Probably related to #4768

**Comment by benjore** [comment]
This is working correctly. Superseded by #4768
