### ISSUE TITLE
Multiple issues with alignments

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4803]
0.10.0 (d8df89a) 
[57-TIT.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/2251405/57-TIT.usfm.zip)
These problems do not occur every time the steps are followed. Seems like about 50% of the time.
Errors:
1. Invalidated alignments alert is displayed in tW even though no verse edits were made
2. Invalidated alignments alert is displayed after navigating to the Home page
3. Existing alignments are reset after uploading to Door43 and opening project in tW (data loss)
4. All verses with no alignments show the broken link icon
See the alignment.mov.zip file in slack

Steps:
1. Import and load the project in wA
2. Upload project to Door43
3. Partially align 1:1
![image](https://user-images.githubusercontent.com/8171759/43556735-ec03524a-95c6-11e8-816f-e302a02ddfbf.png)
4. Upload project to Door43
5. Open project in tW
6. Navigate to Home screen

**Comment by cckozie** [comment]
I have verified that I see the same failures occur without doing the uploads to Door43

**Comment by cckozie** [comment]
An even more streamlined set of steps:
Import the file and then compress or save it for retests
1. Move the project to the projects folder
2. Load the project in wA
3. Align the word Paul in verse 1:1
4. Quickly click on the project folder in the menu bar
The invalidated alignments alert is displayed on the home page, the aligned words have been moved back to the words list, and all verses with no alignments show the broken link icon in wA. This problem occurs about 50% of the times I perform the steps. If the alert is not displayed on the Home page, then frequently it will be displayed when the project is reopened in wA and the alignment will be reset.
I'm seeing the problem on both Mac and Windows

**Comment by cckozie** [comment]
I'm assuming this is or is related to the same issue as above.
Import and load in wA https://git.door43.org/ult-pre-alignment/en_act
When the tool opens the app appears to be hung for several seconds (cannot scroll, etc)
When allowed to, click on the project folder in the menu bar. Several seconds after returning to the home page the invalidated alignments alert is displayed and the app appears to be locked up again for a few seconds. After several seconds I can clear the alert and then select another project, but when I get to the tools page, clicking the Load button on one of the tools does not respond for several more seconds. When that project is loaded I again see the invalidated alignments alert and most verses are displaying the broken link icon.

**Comment by da1nerd** [comment]
@cckozie I can't accurately test the project with just the exported usfm. You need to zip up the project folder so I have all the metadata as well.

**Comment by da1nerd** [comment]
However, I was able to replicate the problem with my own project. Looks like there is a race condition. Should be relatively easy to fix.
