### ISSUE TITLE
Import Pre-aligned ULT

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#4805]
### User Story

As a [type of user], I want [some goal] so that [some reason].

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by benjore** [comment]
Needs to have the 0.10 release so that we can export to USFM3.

**Comment by PhotoNomad0** [comment]
Rich's script already updated this, so no additional work needed.

**Comment by cckozie** [comment]
Need to figure out how to verify it's the latest in tC.
