### ISSUE TITLE
Scripture Pane shows +Bible pane even when no resources are available

### ISSUE THREAD

**Issue by bspidel** [unfoldingWord/translationCore#4807]
### User Story
Having loaded all available resources, the Translation Words and word alignment Scripture Panes still wastes real-estate showing Icon for adding a resource. With Build: x64, Win10, 0.10.0, d8df89a

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by cckozie** [comment]
Added to #4788
