### ISSUE TITLE
Translation Words loads resource when none selected

### ISSUE THREAD

**Issue by bspidel** [unfoldingWord/translationCore#4808]
### User Story
- Steps to Repeat
   - Having loaded all resources in scripture pane
   - Attempt to load one more (you cannot select anything) just click load
   - Even with no selection, a new copy of last resource will be loaded
   - Was able to load 20 copies of Hindi before giving up.

- With Build: x64, Win10, 0.10.0, d8df89a
- Note Word alignment does not have this behavior until you remove resources then attempt to re-add them

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by cckozie** [comment]
dup of #4788
