### ISSUE TITLE
Expanded Scripture Pane does not label target language column

### ISSUE THREAD

**Issue by bspidel** [unfoldingWord/translationCore#4815]
### User Story
- The first column of the Expanded Scripture pane for both tW and word alignment does not have a label.
- With Build: x64, Win10, 0.10.0, d8df89a
### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by cckozie** [comment]
Dup of #4394
