### ISSUE TITLE
Expanded Scripture Pane does not show all selected language resources.

### ISSUE THREAD

**Issue by bspidel** [unfoldingWord/translationCore#4816]
### User Story
- Expanded Scripture pane for both Translation Words and Word alignment doesn't show all columns. 
- It reasonably shows 4 columns but no more. Instead it horizontally scrolls even when it has lots of real-estate to make dialog wider 
- or resize columns narrower.
- With Build: x64, Win10, 0.10.0, d8df89a

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by cckozie** [comment]
Currently working as designed. Other issues address user specified sizing options.
