### ISSUE TITLE
Translation Words Expanded Scripture Pane Editor shows USFM Markup

### ISSUE THREAD

**Issue by bspidel** [unfoldingWord/translationCore#4817]
### User Story
- Edited Titus 2:13
- Editor showed USMF markup at end of verse
- Used Build: x64, Win10, 0.10.0, d8df89a

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by cckozie** [comment]
@bspidel This is working as designed. The user needs to be able to edit the USFM tags.
