### ISSUE TITLE
Problem with duplicate popovers when hovering over the icons in the menu elements in tW

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4818]
0.10.0 (6f1cb6a)
The popover with the gray background is preferred. The broken link icon disappears in the black background. (It seems that the dark background popover is only displayed when there is a broken link icon)
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/92b0681d-ba98-4520-ab64-54cab36a9b0b)

![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/c990e052-d1c2-4610-82dd-f03d847fa0f1)

**Comment by PhotoNomad0** [comment]
Needs to be added to tCore.

**Comment by da1nerd** [comment]
@PhotoNomad0 just added this to tC and waiting for a build.

**Comment by cckozie** [comment]
Fixed in 1.0.0 (fa926a3)
