### ISSUE TITLE
Expanded Scripture pane verse editor warns of broken links where there were none.

### ISSUE THREAD

**Issue by bspidel** [unfoldingWord/translationCore#4819]
### User Story
- With Build: x64, Win10, 0.10.0, d8df89a
- Open Word Alignment tool
- Edit verse Titus 2:13
- Make a change
- Close editor
- Note alert

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by cckozie** [comment]
Dup of other issues. Fixed in 0.10.0 (6f1cb6a) .
