### ISSUE TITLE
Alignment complete toggle not automatic

### ISSUE THREAD

**Issue by bspidel** [unfoldingWord/translationCore#4820]
### User Story
- Using fully aligned Titus
- Verses are not marked as "Alignment Complete"
- Using Build: x64, Win10, 0.10.0, d8df89a
 

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by cckozie** [comment]
This is a known issue and was approved as is for 0.10.
@benjore Do we want the switch to toggle automatically for pre-0.10 projects in later releases?

**Comment by cckozie** [comment]
Included as part of #4914
