### ISSUE TITLE
App allows users to import usfm3 projects from Door43 but indicate that all verses are missing

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4822]
0.10.0 (6f1cb6a)
https://git.door43.org/tCore-test-data/AlignedUlb_hi
The project is imported but the book name is not picked up and all verses are reported as empty.
Need to either warn and block the user from importing usfm3 from Door43, or fully implement #4552.

Block them from importing it.

**Comment by PhotoNomad0** [comment]
#### Tasks
- [ ] [8] Fix mistaken USFM import of online projects
- [ ] [8] Add unit tests
- [ ] [8] PR Review [4822]

**Comment by cckozie** [comment]
1.0.2 (6ab77c0) 
https://git.door43.org/Door43-Catalog/en_ulb/src/branch/master/43-LUK.usfm
https://git.door43.org/Door43-Catalog/en_ulb/raw/branch/master/43-LUK.usfm

Error message incorrectly indicates that multiple books are the problem.
![image](https://user-images.githubusercontent.com/8171759/46765271-33c43680-cca4-11e8-852e-67170c4ea46c.png)

**Comment by PhotoNomad0** [comment]
@cckozie @benjore - this is different issue related to how the app. processes URLs.  It parses the url "https://git.door43.org/Door43-Catalog/en_ulb/src/branch/master/43-LUK.usfm" to pull out the user and repo names to create a new URL such as "https://git.door43.org/Door43-Catalog/en_ulb.git".  How do we want to handle urls going forward?  What error messages do we want to show for various ulrs to different servers? or invalid paths such as to specific raw files (that are not repos) or invalid paths?  The current approach is very simplistic.

**Comment by cckozie** [comment]
@PhotoNomad0 - I'm not sure what is meant by 'this is different issue'. The current implementation does block the user from importing the usfm project, it just displays the incorrect reason that it was blocked.
I would expect that any time the url does not point to a legitimate tC project repo (either a valid tStudio or tC project) that an alert would be displayed indicating such. 
Currently when a user enters a non-Door43 url the following alert is displayed. I think that would be appropriate for this situation as well.
![image](https://user-images.githubusercontent.com/8171759/46839063-bf5fc500-cd81-11e8-8a5d-dc5ae5dd3434.png)

**Comment by PhotoNomad0** [comment]
@cckozie - specifically this is not importing a project, but trying to point to a specific file on door43.  But your suggested approach sounds good to me and simpler.  I'll start looking into what this will take to implement and am presuming @benjore will be OK with that.

**Comment by PhotoNomad0** [comment]
@cckozie - verified fix in https://tc-builds.door43.org/build/release-v1.0.2/translationCore-win-x64-1.0.2-429bca2.setup.exe

**Comment by cckozie** [comment]
Works in 1.0.2 (f005f02)  for URLs referencing the USFM files. There is still a problem with the URL referenced in the first comment above.
