### ISSUE TITLE
Continue button disabled on project details screen for some existing 0.9.1 projects

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4823]
0.10.0 (1fc250f)
[existing.9.1.zip](https://github.com/unfoldingWord-dev/translationCore/files/2259142/existing.9.1.zip)
These are projects that were in the projects folder in tC 0.9.1 when the upgrade was done to 0.10.0.
Notice that all of the fields have valid data, but the Continue button is disabled.

![image](https://user-images.githubusercontent.com/8171759/43671411-2dfb31d8-975f-11e8-84ac-67623be16f80.png)

**Comment by PhotoNomad0** [comment]
@cckozie - looks like we are failing in the case of opening an old project that has preexisting validation failures.  The complication with the stepper is that we want continue button initially disabled when someone is editing project details, but in other cases we want it to be initially enabled if project details are valid.
