### ISSUE TITLE
Write helper function that gets the list of the local timestamp of the resources locally installed

### ISSUE THREAD

**Issue by bspidel** [unfoldingWord/translationCore#4833]

**Comment by mannycolon** [comment]
My Findings regarding #4833
- We currently don't have a manifest for bibles. For example, `English ULT` doesn't have a manifest for the entire Bible only for the specific books. The same is true for resources such as `translationAcademy`, `translationWords`, and `translationNotes`.

- Questions:
  - What timestamp do we use the bibles/resource modified timestamp or the book's modified timestamp?
- There are multiple scenarios we would have to consider if we use the specifics books timestamp? maybe we'll have to reconsider the code that we have currently written?
  - Do we want to write code that downloads the entire bible when only one specific bible needs to be updated based on that specific bibles modified timestamp? or do we just download the specific book that was modified? meaning that our data structure of the list of resources that need to be updated may have to change?

**Comment by cckozie** [comment]
Local timestamps are not being displayed. Not sure if the problem should be attributed to this issue or to #4426.

**Comment by mannycolon** [comment]
@cckozie If the resource was never downloaded in tC then there would not be any local timestamps. Where these resources with missing local timestamps previously downloaded in your local resources folder?

**Comment by cckozie** [comment]
Problems have been moved to new issues.

**Comment by cckozie** [comment]
Appears to work.
