### ISSUE TITLE
Need to remove overwrite of resources on install of app

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#4857]
### User Story

As a end user starting with 1.0.0 release, I don't want my downloaded resources to be clobbered when ever I upgrade the app, since I may have downloaded a lot of resources and don't want to go through the time/effort/cost of doing that all over.

### Features / Specifications

- [ ] remove feature that reinstalls resources when build number changes, but only when resource folder does not exist.
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by benjore** [comment]
@PhotoNomad0 Can you further explain what is going on here? Does this mean that the app is automatically updating all the existing (base) resources on update? Or does this mean that any additional resources I may have added are erased (and then need to be re-downloaded)? Or something else?
