### ISSUE TITLE
Change Scripture Pane to no longer use hard coded ult or ulb for gateway bible

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#4858]
## User Story

As a user who speaks Hindi, I want the aligned Hindi IRV to show up by default in the Scripture Pane (when I select Hindi as the GL) as the "source text" so that I can understand what is going on.

As a developer, I want tC to be smart enough to look for the aligned Hindi IRV (instead of the ULT/ULB) so that I don't have to hard code all the GL aligned literal (and dynamic) Bibles.

## Notes: 
- Scripture Pane should no longer use hard coded ULT or ULB for the default gateway bible, but should show supported gateway bibles in that language (determined by checking level, alignments, etc.)
- All Bibles in that GL (e.g. both literal & dynamic) should show up in the Scripture Pane (this is covered elsewhere). 
  - By default, the target language, all GL translations, and original language should show up in the Scripture Pane (this is covered elsewhere). 
  - This will be the same for both tools.
- From spike https://github.com/unfoldingWord-dev/translationCore/issues/4859, here are a list of areas where ult/ulb has been hard-coded:
  - ~SettingsMigrationActions.migrateCurrentPaneSettings1() - handles remapping of old bible ids for 'ulb-en',  'udb-en', or 'udt'.~ **This are needed migrations** 
  - ~SettingsMigrationActions.migrateCurrentPaneSettings4() - handles remapping of old bible ids for 'ulb-en',  'udb-en', 'udt-en','udt-hi', 'udb-hi'.~ **This are needed migrations** 
  - ~ResourcesHelpers.chapterGroupsData() -  hard coded to en ult to get chapter count~
  - ~WordAlignmentHelpers.convertAlignmentDataToUSFM() - hard coded to en ult to get chapter count~ **Spoke to @benjore about doing using the EN ult index for versification and concluded it is acceptable for now.** 
  - ~bibleHelpers.isProjectMissingVerses() - hard coded to en ult to get verse counts~ **Spoke to @benjore about doing using the EN ult index for versification and concluded it is acceptable for now.** 
  - ~manifestHelpers.generateManifestForUsfmProject() - sets up manifest for imported project: ult as source, probably could be left alone.~
  - ~manifestUtils.setUpDefaultUSFMManifest()  - creates in manifest for default USFM project: ult as source, probably could be left alone.~  Can be removed, no longer used
  - ~**tW:** settingsHelper.loadCorrectPaneSettings() - initialize sources shown in scripturePane in tw 
  gl bible hard-coded to ult, ulb.~ **It is acceptable for now until we implement identifiers for aligned bibles**
  - ~**tW:** checkAreaHelpers.getAlignedGLText() - checks for either ulb or ult as aligned bible in language~ **It is acceptable for now until we implement identifiers for aligned bibles**

**Comment by mannycolon** [comment]
- Where/when is the index.json file generated for bible resources?

**Comment by mannycolon** [comment]
## Findings:

- Where/when is the index.json file generated for bible resources?
- Should the GL for the project be selected earlier in the process?
- Can we use the hard-coded `En ULT` index.json ? are they all the same?
- Should we stamp bible resources as `GatewayLanguage/Aligned resource` in their manifest?
   - `"alignedGL": true`

**Comment by mannycolon** [comment]
Create a list of chapter & verse numbers base off the `En ULT` to replace the hardcoded references of the `En ULT`

**Comment by mannycolon** [comment]
Already using versification list (index.json) off of `En ULT`. No Changes needed for now.
