### ISSUE TITLE
wA reports changes made and alignments invalidated in newly imported USFM3 projects

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4865]
0.10.0 (dfbdeb1) 
[57-TIT.3.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/2270888/57-TIT.3.usfm.zip)
Import this file an open in wA
The alert is displayed indicating that changes have been made and alignments invalidated
Broken links are displayed by several verses
Broken links are also displayed by verses that were not aligned but now have suggestions.
Broken links are also displayed by verses that were aligned in a previoius version of tC, and MAP thinks some of the alignments are incorrect. (Guessing at this. Some words were returned to the word list, and it looks like the alignments were probably wrong, but they were made by a person in the previous version. One example of this is if different GL words are aligned to two Greek boxes for the same Greek word.)

Why does the app think that changes were made? What is it measuring against since this is a new import?

**Comment by cckozie** [comment]
Is this the same as #4912?

**Comment by bspidel** [comment]
More data:

I imported https://git.door43.org/tCore-test-data/English_tit into 1.0.2 (7ccb0dc)

- It said there were invalidations but wA tool card said 100%
- When I launched tool some broken links were shown
- When I clicked on them the link badge went away without me doing anything else
- When I exited the tool without any changes the wA tool card progress was 80%

**Comment by cckozie** [comment]
2.0.0 (4b3ebee) 
After importing the reference file:
wA tool card shows 80% and invalidations
All of the invalidated verses have one or two words in the word bank, assumed because of changes to the UGNT
I think this is now working as expected.
