### ISSUE TITLE
Load project data when project is selected

### ISSUE THREAD

**Issue by da1nerd** [unfoldingWord/translationCore#4884]
The project data must be loaded when the project is loaded.
This is required to support other tool features.

**Comment by benjore** [comment]
Need more detail. What is the scope?

**Comment by da1nerd** [comment]
~I think this is mostly done by some cleanup work I had done in September.~

## Update
We still need to combine the logic in `ProjectLoadingActions.openProject` and `ProjectDataLoadingActions.loadProjectData`. The `openProject` method is already hooked up to the project selection.

This may involve refactoring the project reducers.

**Comment by da1nerd** [comment]
note to self.
Project and tool loading have been separated into `openProject` and `openTool`.

**Comment by da1nerd** [comment]
This is just about finished. There's a bit of temporary hacky code, but I want to get the current changes in first to avoid too many merge conflicts.

Once #5541 is merged in we'll be ready to tidy things up and then start working on #3562

**Comment by da1nerd** [comment]
In order to complete #5599 we will need to load the groups data when the project is selected as well.

initializing project groups will be split into two independent functions
1) copy group data from resources to the project. For when a project is selected so the tools can calculate things for display on the page listing the tools. And
2) load the group data from the project and store it in redux. For when a tool is selected to render the menu (and maybe other things?).

**Comment by da1nerd** [comment]
This is a rough outline of what's currently happening with the groups data

## Loading groups index
* look for tool translationHelps in the selected gateway language (this will need to be triggered any time the gateway language changes)
* find the most recent version of the translationHelps
> inside the versioned translationHelps folder there are folders for each category
* inside each category is an index.json file which contains a list of ids and names
* the index.json file is loaded and stored in redux for use in validating the context id (is this actually needed?)
* at any rate this loading should occur when a tool is selected.
* a chapter index will be generated in the absence of an index.json (or really... just the absence of the tool translationHelps)

## Loading groups data
* find the data path in the project
* look for a .categories file that lists the loaded categories.
* read the .categories file and inspect the `loaded` property to determine which categories have already been copied into the project
* if the category has not already been copied into the project go ahead and copy it then update .categories to indicate it has been loaded
* load all of the now copied group data from the project directory and store it in redux keyed by the category name.
* this loaded groups data is used to validate the context, it also receives from processing in tc before being used in the menu.

## External use
groups data and index are both used in the tc-ui-toolkit for rendering the menu

**Comment by da1nerd** [comment]
Right now when loading the groups index for chapter-based checks the name of the chapter is being localized directly and stored in the groups index. This is an unnecessary step and only serves to couple data loading with locale. This indirectly influences the usage of the group index when generating csv.

If the menu were to perform the localization directly we could simplify the index loading and avoid using the group index in the csv export. This would further decouple groups from tC so that in the future we may move it entirely into the tools.

@RoyalSix thoughts?

**Comment by da1nerd** [comment]
I see that the group index in the resources contain localized names for all of the indices based on the gateway language. So not localizing the chapter-based group index departs from that common structure and could introduce confusion. Perhaps instead of representing two forms of the index we could simply not generate a chapter-based index and instead use the target book chapters as the basis for the menu.
However, we still need a layer of abstraction between the help/chapter-based-index-thing and the context id so  we would still need to account for that at some level. I'm not seeing an ideal path at the moment.

**Comment by RoyalSix** [comment]
@neutrinog I think that is a good idea. Maybe something that should be done after decoupling the groups data/index more.

**Comment by PhotoNomad0** [comment]
Verified in https://tc-builds.door43.org/build/develop/translationCore-macos-x64-1.1.0-ac75c11.dmg

**Comment by cckozie** [comment]
Holding all of these until I can verify both tools end to end.

**Comment by cckozie** [comment]
Don't see an problems in 1.1.0 (1034612)
