### ISSUE TITLE
Create a build for performance testing the book of Acts

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#4894]
### User Story

As a performance tester, I want to load Acts in the tW tool so that I can test to see if there is optimization that is needed.

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by PhotoNomad0** [comment]
@benjore @cckozie - not necessary to create a new build.  Using the latest develop build (which has the updated UGNT), I was able to import Larry's aligned en acts.  Using developer mode I was able to open it in tW.  It was quite slow navigating on my Windows machine.

Tested with:
```
From the `develop` branch:
Linux build 1658311 (v1.0.0) is ready for download.
macOS build 1658311 (v1.0.0) is ready for download.
Windows x64 build 1658311 (v1.0.0) is ready for download.
Windows x32 build 1658311 (v1.0.0) is ready for download.
```
