### ISSUE TITLE
"Gateway Language Quote" in the CSV export is showing incorrect data

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#4901]
### User Story

As a user, I want the "Gateway Language Quote" to show the correct information so that I know what I'm checking against.

### Features / Specifications

- [ ] Currently the "GL Quote" is displaying the Group Name data instead of the GL Quote. 

### Definition of Done

- [ ]
- [ ]
- [ ]

## Notes
- Related to #4902

**Comment by benjore** [comment]
Need Screenshots

**Comment by benjore** [comment]
<img width="1415" alt="screen shot 2018-10-05 at 3 18 37 pm" src="https://user-images.githubusercontent.com/13352518/46558235-0c3f2980-c8b2-11e8-982f-c67359aeafdd.png">

Note: the `gateway Language Quote` is actually the `Gateway Language groupName`. It should be the actual GL quote, that is, the same thing that is highlighted in the GL in the Scripture Pane which is the same as `Please select the translation for: "Savior"`

**Comment by PhotoNomad0** [comment]
Verified in https://tc-builds.door43.org/build/develop/translationCore-macos-x64-1.1.0-1034612.dmg

**Comment by cckozie** [comment]
Works in 1.1.0 (1034612)
