### ISSUE TITLE
Accept and Reject buttons should be disable anytime there are no suggestions being displayed in wA

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4904]
[57-TIT3full.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/2295130/57-TIT3full.usfm.zip)

Import and load this project in wA
Go to verse 2:5
Drag the aligned word 'word' back to the word list
Click the Refresh button
Drag the remainder of the words back to the word list
Notice that both the Accept and Reject buttons are still enabled
May be related to #4784

![image](https://user-images.githubusercontent.com/8171759/44233223-db236200-a168-11e8-9976-00b3fca5b2c9.png)

**Comment by da1nerd** [comment]
This is a duplicate of #4700 .
