### ISSUE TITLE
User is notified of reset alignments on usfm3 project import even though all alignments are complete

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4912]
1.0.0 (a40ef81)
[57-TIT3full.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/2300752/57-TIT3full.usfm.zip)

When this project is imported and loaded in wA the user is notified that changes have caused alignments to be reset. Verse 1:12 has the broken link icon, but when selected it shows that there are no unaligned words in either the word list or Greek.
The same notification appears if the project is loaded in tW or exported to USFM3 or uploaded to Door43.

**Comment by benjore** [comment]
Hypothesis: this is caused by the white space issue in #5133 . Let's retest this once #5133 is completed.

**Comment by elsylambert** [comment]
Retested in 2.0.0 (4b3ebee). Not seeing this issue.
