### ISSUE TITLE
Problems with timestamps displayed on project page

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4927]
- [x] The time should only reset when the project is selected. 
  - [x] Consider adding a project setting file with a timestamp in there for when it was selected. (settings.json)

This is a placeholder for future testing based on report from Larry.
Larry Sallee [Yesterday at 8:13 AM]
I just noticed that the time stamp in my tC 0.10 project list does not appear to work. Every book I have worked on in the past few days now says “a few seconds ago.”

7 replies
Chris Kosieracki [1 day ago]
Hmmm, interesting. Thanks Larry. I'll do some testing and write up the issue.

Chris Kosieracki [1 day ago]
@Larry Sallee Just to clarify, are those projects you recently imported from Door43 or ones that have just been sitting on your local machine? (The timestamp is applied on the local machine, so any imported project will reflect the time of import. Also, the timestamp displayed is only updated when the project page is navigated to.)

Larry Sallee [1 day ago]
@koz These are projects that I had in 0.9. I opened them in 0.10 and edited them and realigned them yesterday. The time stamp on those said “a few seconds ago” this morning. Right now, it says “2 minutes ago.” I has been a full day.

Larry Sallee [1 day ago]
This is low importance, but I wanted you to know.

Chris Kosieracki [1 day ago]
:+1:

Chris Kosieracki [1 day ago]
Are you on Windows or Mac?

Larry Sallee [1 day ago]
Mac

**Comment by cckozie** [comment]
2.0.0 (bd37460) 
en_ult_tit_book is the only project I have opened today. I did load the latest build before starting work today. The "time ago" displayed on all of the other is incorrect.
![image](https://user-images.githubusercontent.com/8171759/62218784-bffa3400-b372-11e9-8a43-ffdf36824303.png)
![image](https://user-images.githubusercontent.com/8171759/62218813-cab4c900-b372-11e9-8cee-ad2d7a0a9113.png)

**Comment by richmahn** [comment]
@benjore @cckozie We will have a last opened time stamp in a settings file. Yet before a project is open, what should I go by to show its last opened/access date in the projects page? Should I go by what we were using, the last ACCESS time of <projectdir>/.apps/translationCore (which often gets accessed when you start tC) or should it be just by the last modification date of manifest.json, or some other save file? Or should it be “never opened”?

**Comment by richmahn** [comment]
Been decided by @benjore that we show "Never Opened" (in the selected locale) if the user has never opened this project with my settings.json feature.

**Comment by richmahn** [comment]
Verified in build 5a65c0e

**Comment by elsylambert** [comment]
Works fine in 2.0.0 (3727b58).

**Comment by cckozie** [comment]
Looks good in  2.0.0 (3727b58)
