### ISSUE TITLE
Not able to Sync project

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#493]
When I attempt to sync my project, I get this error.
To recreate, I deleted my checkdata folder to get the project to load, once it loaded, I tried to sync.

git.js:226 remote: error: failed to lock refs/heads/master        
To https://git.door43.org/klappy/ilo_luk_text_ulb.git
 ! [remote rejected] master -> master (failed to lock)
error: failed to push some refs to 'https://65df9be2817778ac81e055b34a615bb4d351929a@git.door43.org/klappy/ilo_luk_text_ulb.git'

**Comment by ihoegen** [comment]
@klappy Looking on Door43, it appears to have synced successfully. Also, I was unable to recreate the issue, and that appears to be more of an issue with git than it is tC.

**Comment by klappy** [comment]
Okay, I'll try it again. Thanks!
