### ISSUE TITLE
Alignments invalidated message pops up when dragging words back to the word list

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4933]
1.0.0 (0fe0fb6)
[aig_algn_gal_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/2315553/aig_algn_gal_book.zip)

Load the attached project in WA.
Select verse 1:4. 
Starting with first word "τοῦ", unalign the words from left to right. 
After unaligning the group "τῶν ἁμαρτιῶν", split the pair. 
Unalign the next word "ἡμῶν". 
Click on verse 1:3. 
Note the I alignments invalidated message and the broken link icon on 1:4

**Comment by da1nerd** [comment]
~@PhotoNomad0 I cannot reproduce this issue. I used the project attached above and followed your steps. I don't get any notice about invalidated alignments.~

Ah nvm. I was finally able to reproduce it. Must have followed the steps incorrectly the first time.

**Comment by da1nerd** [comment]
I've simplified the steps to reproduce even more.

1. load the project
2. select 1:4
3. split the "τῶν ἁμαρτιῶν" pair
4. perform any other alignment action such as (un)aligning, merging, splitting, etc.
5. select 1:3

**Comment by da1nerd** [comment]
The alignment data is stored correctly, both on disk and in the reducer. However, for some reason when we make a change after the split we lose one of the source tokens from the alignment data.

**Comment by da1nerd** [comment]
I've narrowed down the problem to the alignment compiler. The compiler was updated recently so I must have introduced a bug that was not covered in the unit tests.

**Comment by da1nerd** [comment]
After some further digging I now think the issue is not in the compiler but in the renderer.

**Comment by da1nerd** [comment]
finally figured out the issue. I'm surprised this issue didn't surface earlier. When splitting alignments I neglected to re-render the alignment data which caused some indices to get out of sync. This has been corrected and will submit a PR soon.

**Comment by cckozie** [comment]
Fixed in 1.0.0 (71a9a28)
