### ISSUE TITLE
Tool card GL dropdown if there is no GL support

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#4936]
## User story

As a user, I want an intelligible indication if there is no support for a book/tool combo so that I don't think that something is broken.

## Specs
- [ ] If there is no GL that supports a book/tool combo, then the GL dropdown should display "None  available"

**Comment by PhotoNomad0** [comment]
Also making it not clickable on request from Manny and Ben.

**Comment by cckozie** [comment]
This is somewhat in conflict with #4975 since it specifies to hard-code the wA tool to English.
Other than that, it works in 1.0.0 (e375ee0)
