### ISSUE TITLE
The wrong word (occurrence) sometimes gets returned to the word list when edits are performed outside of tC

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4938]
1.0.0 (8bada03)

[57-TIT3full.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/2316192/57-TIT3full.usfm.zip)

1. Import the attached usfm3 project
2. Export it to usfm2
3. Edit verse 1:1 in the exported file to change 'Paul, a servant' to 'Paul, the servant' and save the file
4. Import the edited file choosing the overwrite options
5. Load the project in wA
Note that the new 'the' has been paired with 'knowledge and all of the other 'the' words have been moved to the word list.
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/b042b331-b37b-499e-80ad-5a2c89ffc749)

**Comment by da1nerd** [comment]
This is happening because the introduction of the new word `the` has a propagating affect because it changes the occurrences count for `the`. Something else is going on too because all of the `the`s should be in the word bank.

**Comment by da1nerd** [comment]
@cckozie it appears this was inadvertently fixed by https://github.com/translationCoreApps/wordAlignment/pull/78

**Comment by PhotoNomad0** [comment]
Moving to QA for retest

**Comment by cckozie** [comment]
@PhotoNomad0 Should this be In QA rather than QA Done?
