### ISSUE TITLE
Accepting a WordMAP suggestion as the final alignment does not automatically trigger the "alignment complete toggle"

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#4940]
### User Story

As an aligner, I want the accepting of a WordMAP suggestion as the final needed alignment to automatically trigger the "alignment complete" toggle so that I don't have to do the added step of toggling it even though all the target and original language words have been used.

### To reproduce the bug
- Align an entire verse except for a WordMAP suggestion
- Either click accept or click on the target word (to accept it)
- Note that even though all the target + original language words are used, the "alignment complete toggle does not automatically toggle

![Screen Shot 2018-08-24 at 3.21.13 PM.png](https://images.zenhubusercontent.com/55e5f3984f7a08fbb7f4a658/4a6b7885-1134-47a6-a443-b3edf59037c8)

![Screen Shot 2018-08-24 at 3.21.36 PM.png](https://images.zenhubusercontent.com/55e5f3984f7a08fbb7f4a658/a3440b2e-4df1-461e-b650-8b4bc7d0f952)

**Comment by da1nerd** [comment]
@benjore The completion toggle works as expected for me. However, I'm also using code that has not been merged in yet. I'd suggest re-testing this after #4957 and #4946 are accepted.

**Comment by benjore** [comment]
@cckozie Can you retest this now that the two issues mentioned above have been closed.

**Comment by cckozie** [comment]
1.0.0 (8adaf14) 
Senario A:
After manually aligning all non-suggested words, and then accepting (either via the Accept button or clicking on the suggested word(s), the Alignment complete switch is correct set to on.
Scenario B:
It does not work in this scenario.
1. Accept the suggested word(s)
2. Moves one or more of the accepted suggestions back to the word bank
3. Click the Refresh button
4. Accept the suggestions
Note that the Alignment complete switch remains in the off position

**Comment by cckozie** [comment]
Not working in 1.0.2 (6ab77c0) 
Imported this project file
Partially aligned verse one as shown here:
![image](https://user-images.githubusercontent.com/8171759/46770502-4dba4500-ccb5-11e8-94d0-b607b7a52bca.png)

Navigated to verse 1:2. God showed as suggestion. Manually aligned other words as shown here:
![image](https://user-images.githubusercontent.com/8171759/46770595-a12c9300-ccb5-11e8-8f96-dd93a22561da.png)

Clicked on the Accept button. Alignment complete did not switch on.
![image](https://user-images.githubusercontent.com/8171759/46770704-1304dc80-ccb6-11e8-96d5-d0d1a263132e.png)

 Moved 'God' back to word bank, clicked refresh, then clicked on the 'God' suggestion. Switch did not toggle on.

**Comment by cckozie** [comment]
Works in 1.0.2 (f005f02) .
