### ISSUE TITLE
BUG: Invalidation of data during export/import process

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#4941]
### User Story

From Larry, 

I am having a problem with tC 0.10.1 in 1Pe ULT. There are two verses, 1:25 and 2:8 which will not stay aligned no matter what I do. I have aligned each of them at least 4 times, and have even made and then undid random edits. Each time I copy the project to Door43, it get a broken alignment error. The project is at https://git.door43.org/lrsallee/en_ult_1pe_book

This is what 1:25 should look like:
![image (4).png](https://images.zenhubusercontent.com/55e5f3984f7a08fbb7f4a658/106d96d4-7ec7-4746-a995-09241f4d20ab)

This is the alignment for 2:8
![image (5).png](https://images.zenhubusercontent.com/55e5f3984f7a08fbb7f4a658/dccdbe7c-3006-4fa7-9604-36f0bb599e29)

**Comment by da1nerd** [comment]
This is occurring because there is a `\m` marker in the source text that is not on it's own line. When this marker appears inline with other text `word-aligner` chokes and the error is interpreted as a corrupt alignment.

Going a little deeper, the text is parsed by `usfm-js` which produces invalid objects in this case.

**Comment by da1nerd** [comment]
When `usfm-js` receives the following output:

```
\v 25 but the word of the Lord remains forever."
\m This word is the gospel that was proclaimed to you.
```

It produces two verse objects:
```json
[{
   "text": "but the word of the Lord remains forever.\"",
   "type": "text"
},
{
   "content": "And this is the word of the gospel that was proclaimed to you.",    
   "tag": "m"
}]
```

`word-aligner` chokes over this output.

I'm not certain if `usfm-js` is not supporting the full USFM spec, or if the verse has invalid markup.

**Comment by PhotoNomad0** [comment]
Need to check whether the m tag should have text attribute rather than content. Content is intended for non-translated text.

**Comment by PhotoNomad0** [comment]
On second thought. Also need to update usfm-js to add type attribute.

**Comment by PhotoNomad0** [comment]
Looks like the \m marker is a type of paragraph marker.  So we need to tweak usfm-js to handle it like paragraph marker so that text following is not treated as content of the \m marker, but as text.

Looking further - There are a whole set of paragraph markers that we need to treat similarly to `\p` marker: https://ubsicap.github.io/usfm/paragraphs/index.html

**Comment by PhotoNomad0** [comment]
@neutrinog - And word aligner should not choke over this content or any similar content.  Is the Choking on USFM3 import or export?

**Comment by PhotoNomad0** [comment]
### Need to do in usfm-js:

USFM.js - all paragraph markers in the USFM spec need to be added into `MARKER_TYPE` as type `paragraph`.  Also need add the paragraph markers under `MARK_CONTENT_AS_TEXT`

**Comment by da1nerd** [comment]
@PhotoNomad0 by choke I mean the word aligner is indicating the verse has invalid alignments because it sees half the verse as missing.

Thanks for the tips above. I'll work on fixing those.

**Comment by da1nerd** [comment]
I have prepared a PR which adds support for those additional paragraph markers. https://github.com/translationCoreApps/usfm-js/pull/38

Once that PR is merged in we'll need to update dependencies in order:
- [ ] word-aligner to use latest version of usfm-js
- [ ] tc to use latest version of word-aligner.

**Comment by cckozie** [comment]
Works in 1.0.0 (e375ee0)
