### ISSUE TITLE
Use selections from tW (and tN?) as saved alignments in WordMAP (in wA tool)

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#4946]
### User Story

As a user who has done work in a checking too, I want that work to simplify my work in the wA tool so that I'm awed by how amazing tC is (and I save a bunch of time).

### Features / Specifications

- [ ] Start with per project
- [ ] Later per language
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by da1nerd** [comment]
The tW data is still being directly managed by tC. 
In order to foster decoupling tW from tC I'll create a new action in tW that will handle loading selection data for the entire book.

**Comment by da1nerd** [comment]
To speed things up I may skip migrating parts of the selection state into the tool. Since map is running asynchronously we can query directly from the disk on each request without a performance hit to the UI.
This will allow us to migrate tW state management at a later time.

**Comment by da1nerd** [comment]
This is finished and just waiting till after the 1.0 code freeze for review.

**Comment by cckozie** [comment]
1.0.0 (ea3713f)
Did several spot checks and it appears to be working.
