### ISSUE TITLE
Reimport is broken

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4949]
1.0.0 (963d269) 
It looks like this was broken between 1.0.0 (71a9a28) and 1.0.0 (573966a)
1. After clicking Overwrite on the Project you selected already exists alert, the user is returned to the projects page rather than the tools page. (The alert remains on the screen longer than it did when reimport was working correctly)
2. Text that was changed in the reimported file is ignored. The project text remains unchanged.
No errors in the console.
3. If the user clicks Cancel rather than Overwrite, and then clicks Cancel Import, the alert disappears and the app stays on the project details screen.
4. As in 3. above, if the user clicks Continue Import on the Cancelling now will abort... alert, the import is not continued and the app goes back to the projects page.

**Comment by PhotoNomad0** [comment]
I suspect that this is due to merging a recent PR that refactored project selection.  
https://github.com/unfoldingWord-dev/translationCore/issues/4915

**Comment by da1nerd** [comment]
I reviewed my edits and could not identify any problems.

@cckozie could you provide some sample projects to debug with? Also, did you experience this while importing from online or localy?

**Comment by cckozie** [comment]
@neutrinog - Reimport is only supported with local usfm files

Import this project [57-TIT3full.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/2338197/57-TIT3full.usfm.zip)
Import this project taking the Overwrite options [57-TIT-changes.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/2338215/57-TIT-changes.usfm.zip)

Notice during the second import the notification that verse 1:2 is missing. The other change in this file is in verse 1:1 the text 'Paul, a servant' is changed to 'Paul, the servant'.
Notice that when the import is complete you are returned to the projects page rather than the tools page
Open the project in wA and notice that the text in verse 1 has not changed and verse 1:2 is not missing as it should be

**Comment by PhotoNomad0** [comment]
@neutrinog @cckozie  - this is not due to Joel's commits, someone changed the options dialog in the source download updater and now some of the two button prompts are now reversed.  Looking into this now.

**Comment by PhotoNomad0** [comment]
Working on a PR to fix dialog behavior.
