### ISSUE TITLE
Problems found with dynamic source content update

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4953]
1.0.0 (963d269)
I don't know if these are actual bugs or as the result of the epic not being finished.

1.  ~~Ben's mockup shows an 'Unselect all' checkbox, but it does not appear in the app~~
2. [#4967] There is no local timestamp on any of the resources which seems to incorrectly indicate that there are no GL resources on my machine. (After a clean install or 1.0, a single local timestamp does appear by grc)
3. [#4967]The online timestamps are suspect. In the catalog I see en_ult and en_ust both show 8/25/18 but on the selection screen it shows en as 2017-11-29. Two thirds of the online dates are 2018-08-16. The timestamp for ceb is 0001-01-01.
4. [#4967] After downloading the hi sources, the local timestamp remains blank. (Same for all updated resources)
5. [#4970] When the update is performed while in a tool, the downloaded content is not available in the resources dropdown list until the user reloads the project in the tool.
6. [#4968] If the user selects to Check for content updates when there is no Internet connection, the Cannot connect to serve alert is correctly displayed. However, after restoring the Internet connection, when the Check for content updates is clicked, nothing happens. 
7. [#4968] If the user loses the Internet connection during a download, it appears that some resources may get updated. In one test of this downloading ru, one of the Bibles made it and the other didn't. In that case, what will get displayed as the local date? Is a partial download the desired behavior?
8. [#4982] After updating en I now have the ulb, udb, ult, and ust.
9. [#4982] I deleted the local resources folder for en ust tit. After performing an update for en, the en ust tit was not added. Is that the desired behavior?
10. After doing a fresh install of 1.0, there are 30 languages listed on the selection page. After selecting all and running the download, there are now these 8 in the list. Seems strange.
![image](https://user-images.githubusercontent.com/8171759/44874928-505f5e80-ac62-11e8-87f8-2d5b1115c497.png)

11. [#4965] Headers and 'Select all' on selection screen are not localized
![image](https://user-images.githubusercontent.com/8171759/44912315-5bac9b80-acef-11e8-9e31-3459b0f5b81d.png)

12. [#4965] The 'OK' button on all 4 alert messages is not localized
![image](https://user-images.githubusercontent.com/8171759/44915528-c9a99080-acf8-11e8-92ea-854cae769200.png)

**Comment by benjore** [comment]
For issue 1... if the user can select all and deselect all by checking and unchecking the `Select All` box, this is sufficient for me.
