### ISSUE TITLE
Cannot accept alignment suggestion when alignment contains multiple suggestions.

### ISSUE THREAD

**Issue by da1nerd** [unfoldingWord/translationCore#4957]
Here is an alignment suggestion

![image.png](https://images.zenhubusercontent.com/55e49c194f7a08fbb7f49f09/fb7d3b6e-4d27-458b-992f-aa775b65738f)

When clicking on "of" to accept that word this is the result (as expected)
![image.png](https://images.zenhubusercontent.com/55e49c194f7a08fbb7f49f09/cfd15394-b962-46c3-9526-4cd208f86e08)

Now when I click on "the" the accepted word switches.
![image.png](https://images.zenhubusercontent.com/55e49c194f7a08fbb7f49f09/b0feeae8-1e36-4037-a47d-3b0ad031bdb4)

From this point I can repeat clicking on "of" and "the" and the accepted word will toggle back and forth.
This is occurring on  this commit https://github.com/translationCoreApps/wordAlignment/pull/74/commits/9fef371f49e845427fc52a1db280a374ef1365c7. However, I believe this will also be the case for the latest commit to master https://github.com/translationCoreApps/wordAlignment/commit/45797044b053d5edf19b057dc862c8a0028781db.

**Comment by da1nerd** [comment]
I've narrowed this down the a bug in the alignment compiler. I've added two unit tests to replicate the issue.

**Comment by da1nerd** [comment]
This is now fixed. Ended up being a typo.

**Comment by cckozie** [comment]
Works in 1.0.0 (ea3713f)
