### ISSUE TITLE
Localization issues with the source content updater

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord/translationCore#4965]
11. Headers and 'Select all' on selection screen are not localized
![image](https://user-images.githubusercontent.com/8171759/44912315-5bac9b80-acef-11e8-9e31-3459b0f5b81d.png)

12. The 'OK' button on all 4 alert messages is not localized
![image](https://user-images.githubusercontent.com/8171759/44915528-c9a99080-acf8-11e8-92ea-854cae769200.png)

**Comment by cckozie** [comment]
Fixed in 1.0.0 (fbe8a1c)
