### ISSUE TITLE
timestamps issues in the source content updater

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord/translationCore#4967]
2 There is no local timestamp on any of the resources which seems to incorrectly indicate that there are no GL resources on my machine. (After a clean install or 1.0, a single local timestamp does appear by grc) 
[It appears that we do not show the local resource unless there is a newer one online.]

3  - The online timestamps are suspect. In the catalog I see en_ult and en_ust both show 8/25/18 but on the selection screen it shows en as 2017-11-29. Two thirds of the online dates are 2018-08-16. 

  -  ~The timestamp for ceb is 0001-01-01.~ This is a problem with the catalog.  Moved to https://github.com/unfoldingWord-dev/translationCore/issues/4976

4 After downloading the hi sources, the local timestamp remains blank. (Same for all updated resources)
[After downloading the resources they no longer show on the selecton screen.]

**Comment by PhotoNomad0** [comment]
@cckozie @jag3773  - The ceb time is an error in the catalog for ulb.

**Comment by cckozie** [comment]
Where do the online timestamps come from? (Last modified date for the language/resource)
Where are the local resource timestamps stored? (catalog_modified_time in manifiest.json in the language resource)

**Comment by cckozie** [comment]
Passing this issue but asking the question of why there is no manifest file associated with lexicons.

**Comment by jag3773** [comment]
@cckozie The lexicons are not yet published in the catalog, it is still from an old import.
