### ISSUE TITLE
 When the update is performed while in a tool, the downloaded content is not available in the resources dropdown list until the user reloads the project in the tool.

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord/translationCore#4970]

**Comment by benjore** [comment]
@mannycolon What is the simplest solution to this? Can the tool be refreshed after updating the resources?

**Comment by mannycolon** [comment]
@benjore When the download finishes we can just load the new resources whenever the user has a tool opened.

**Comment by cckozie** [comment]
Fixed in 1.0.0 (e375ee0)
