### ISSUE TITLE
Overwriting USFM3 file with USFM2 file results in lots of bad stuff

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#4981]
I started with this Project in tC: https://git.door43.org/benjore/en_ult_1jn_book 

Then I downloaded the USFM2 file on that page: https://git.door43.org/benjore/en_ult_1jn_book/src/branch/master/1jn.usfm . I overwrote the first file with the second file. 

Now there are a lot of `<li>` markers showing up throughout. 

![Screen Shot 2018-09-05 at 12.03.26 PM.png](https://images.zenhubusercontent.com/55e5f3984f7a08fbb7f4a658/e92e2743-ba05-40ce-84df-7c4f9f88e9cc)

**Comment by cckozie** [comment]
I'm not seeing the problem in  1.1.3 (240da43)
