### ISSUE TITLE
 ULB and UDB inconsistencies with the source content updater

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord/translationCore#4982]
8. After updating en I now have the ulb, udb, ult, and ust.

9. I deleted the local resources folder for en ust tit. After performing an update for en, the en ust tit was not added. Is that the desired behavior?

**Comment by mannycolon** [comment]
Per @benjore on slack `keep all of them` (`ulb`, `udb`, `ult` and `ust`)

**Comment by cckozie** [comment]
Passing this issues. I added issue #5064 for consideration as a fix for 9.
