### ISSUE TITLE
Scripture Pane shows (+ resource) when 6 are displayed and no more are allowed 

### ISSUE THREAD

**Issue by bspidel** [unfoldingWord/translationCore#4986]
### User Story
As a User I do not want to see (+Resource) when no more are available, so that I will not waste time trying to add another.

Steps to repeat
  - Launch tool
  - Add to Scripture pane
  - Note that after all resources have been added, the +Resources icon is still in the Scripture Pane. 

### Features / Specifications

- [ ] If all the resources have been added, don't show the (+Resources) in the Scripture Pane
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by benjore** [comment]
I am able to get more than 6 panes. Is this still an issue?
