### ISSUE TITLE
Cannot open up expanded scripture pane if en ult is missing

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#5029]
### Observed:
Opening up expanded scripture pane if en ult is missing.

### To reproduce:
delete the ult bible in the resource/en folder.  Then open an acts project.  Open wa tool.  then on the scripture pane click on the expand button.  The UI will show an error.

### Problem details:
It looks like tc-ui-toolkit is hardcoded to use en_ult.  Found this line in tool: `var verseNumbers = Object.keys(biblesWithHighlightedWords['en']['ult'].bibleData[chapter]);`

### Specs 
- [ ] link it to the literal text of the GL they selected

**Comment by PhotoNomad0** [comment]
Screen capture of crash:

![crash](https://user-images.githubusercontent.com/14238574/45321414-503d4980-b513-11e8-9edb-ae79674f9be5.png)

**Comment by elsylambert** [comment]
Retested in 2.0.0 (4b3ebee). Issue still exists. Not seeing the any crashing errors but expand button  in scripture pane does not work. Click on Expand button does nothing.

**Comment by cckozie** [comment]
This has been fixed in 2.2.0 (2375ae5)
