### ISSUE TITLE
Downloading resources for all the languages dramatically slows down opening WA for Acts.

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#5030]
### to reproduce:
Do "check for content updates", and then selected all languages and download.
Select an Acts project and open WA tool. It will take a very long time to open.

### Additional Info:
- It looks like we are loading every bible into memory when tool is started. 
- Observe that resourceReducers ADD_NEW_BIBLE_TO_RESOURCES is called for each bible of each language.
- It look like tCore will need to determine which bibles are absolutely necessary to open when tool is launched.
- On my old windows machine (with just en and grc loaded - 5 bibles total) it takes 21 seconds to open WA, then first verse switch was 16 sec and switches after that 7 sec.
Loading all language resources and starting with a fresh import it then takes 1 min 35 seconds to open WA,  then first vs switch was about 30 sec and  switches after that 15 sec.

**Comment by cckozie** [comment]
1.0.0 (e375ee0)
Passing for now as performance is marginally acceptable. See my comments on #5031
