### ISSUE TITLE
Performance issues again

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5031]
1.0.0 (dc79cf3)
[en_act.T.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/2368634/en_act.T.usfm.zip)

On my Mac this project now takes 49 seconds to load in wA. Switching between chapters or verses takes 12 seconds.

It now takes 105 seconds to load in tW, and 18 seconds to switch between groups or verses.

**Comment by PhotoNomad0** [comment]
@cckozie - how many languages have you downloaded?  Wonder if this is related to https://github.com/unfoldingWord-dev/translationCore/issues/5030.

**Comment by PhotoNomad0** [comment]
@cckozie - On my old windows machine (with just en and grc loaded - 5 bibles total) it takes 21 seconds to open WA, then first verse switch was 16 sec and switches after that 7 sec.
Loading all language resources and starting with a fresh import it then takes 1 min 35 seconds to open WA,  then first vs switch was about 30 sec and  switches after that 15 sec.

**Comment by cckozie** [comment]
@PhotoNomad0 - You're probably correct. I've downloaded everything.

**Comment by PhotoNomad0** [comment]
@cckozie - should soon have a fix for #5003 that should address this.

**Comment by cckozie** [comment]
1.0.0 (67500fe)
With only en, grc, hi, and ru resource on my Mac it takes 17 seconds to load the project in wA.
With all available resources on Mac it takes 43 seconds to load the project in wA.

**Comment by PhotoNomad0** [comment]
@cckozie - this should be fixed with this PR: https://github.com/unfoldingWord-dev/translationCore/pull/5034

**Comment by cckozie** [comment]
1.0.0 (e375ee0)
With all resources downloaded:
- Loading Acts in wA is now much better , 24 seconds vs 49 seconds before
- Loading Acts in tW is now slightly better, 55 seconds vs 105 seconds before

With only en, grc, and hi resources local:
- Loading Acts in wA takes 10 seconds
- Loading Acts in tW takes 26 seconds (this needs to be improved)
Why are we loading both wA and tW when the user selects to load tW?

**Comment by cckozie** [comment]
I am going to pass this issue even though I don't think the current performance levels are acceptable, especially in loading a project in tW.
I have written up issues #5057 and #5058 to deal with this post 1.0.
