### ISSUE TITLE
Zip resources files that are package with the tC build

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord/translationCore#5036]
Bibles books are zipped and unzipped after being copied to the user's resources folder

**Comment by mannycolon** [comment]
## Performance when generating a new resources folder in the user path.

### With zipped resources 

1st 1 min 18 seconds 78
2nd 2 min 37 sec 157
3rd 1 min 18 sec 78
4th 1 min 7 sec 67
5th 1 min 6 sec 66

(78+157+78+67+66)/5 = 89.2 seconds

### With unzipped resources 

1st  2 min 35 sec 155
2nd 2 min 15 sec 135
3rd 1 min 17 sec 77
4th 1 min 50 sec 110
5th 1 min 26 sec 86

(155+135+77+110+86)/5 = 112.6 seconds

**Comment by cckozie** [comment]
@mannycolon - To try to test this I deleted the resources folder and then started tC. 
In 1.0.2 (f005f02) it takes 78 seconds on my Mac which is exactly the same amount of time it takes when opening 1.0.0.
Is there another way to test this, or is it possible that the fix wasn't in the f005f02 build?

**Comment by cckozie** [comment]
Tested with empty projects folder and no resources folder
1.0.0 (4bd6856) Time to Get Started - 87 seconds
1.0.2 (a18aef8) Time to blank screen - 83 seconds

**Comment by cckozie** [comment]
Works in 1.0.2 (f005f02)
