### ISSUE TITLE
tC Crashes On Tool Open (Alignment Verse Must Be a Number)

### ISSUE THREAD

**Issue by RoyalSix** [unfoldingWord/translationCore#5038]
### Prerequisites

* Put an X between the brackets on this line if you have done all of the following:
- [X] I have searched the [issues](https://github.com/unfoldingWord-dev/translationCore/issues) of this repository and believe that this is not a duplicate.

### Description
These projects do not open

### Steps to Reproduce
Start with a fresh resources folder (directly after install)
Try to open the following projects in either tool
`https://git.door43.org/sweettenda/btm_eph_text_udb.git`
`https://git.door43.org/ukum1/aku_2ti_text_ulb.git`

**Screenshots**
<img width="1280" alt="screen shot 2018-09-12 at 10 06 38 am" src="https://user-images.githubusercontent.com/16184018/45441976-8c88bb00-b675-11e8-84fb-756a49ff190c.png">
<img width="1280" alt="screen shot 2018-09-12 at 10 06 24 am" src="https://user-images.githubusercontent.com/16184018/45441977-8c88bb00-b675-11e8-8ce9-94e40e947b5a.png">

### Context

**Enviorment**
| Tech         | Version |
|--------------|---------|
| tc           | v1.0.0  |
| build #      | 36ba4bb |
| OS           |  macOS  |

### Additional Information
After it crashes, and I reload and open the same project and the same tool, it still crashes.

**Comment by cckozie** [comment]
2.0.0 (4b3ebee) 
Both projects open in all 3 tools.
