### ISSUE TITLE
menu stepper project is blue when logging in but no project is selected

### ISSUE THREAD

**Issue by bspidel** [unfoldingWord/translationCore#5039]
### Prerequisites

* Put an X between the brackets on this line if you have done all of the following:

- [x ] I have searched the [issues](https://github.com/unfoldingWord-dev/translationCore/issues) of this repository and believe that this is not a duplicate.

### Description

When logging in, project in menu stepper is blue but no project is selected

### Steps to Reproduce

1. Having logged in and selected a project,
2. Log out then log back in.
3. On stepper, project folder is blue. Should it be grey?
4. Continuing to project shows no project selected

**Screenshots**
![blueproject](https://user-images.githubusercontent.com/4968713/45452938-56ffc400-b6ad-11e8-8ec3-0d9782125386.PNG)

**Expected behavior:** [Expected project to be grey]

**Actual behavior:** [It is blue]

### Context

**Enviorment**
| Tech         | Version |
|--------------|---------|
| tc           | v1.0.0  |
| build #      |   (36ba4bb)       |
| OS           |  x64 Win10       |

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by cckozie** [comment]
Not a bug. Blue indicates that it is clickable.
