### ISSUE TITLE
A critical error has occurred message in both wA and tW

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5041]
Happens in both 1.0.0 (dc79cf3) and 1.0.0 (36ba4bb)
Happens in many but not all projects (maybe non-aligned projects?)
[es-419_luk_text_ulb.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/2377309/es-419_luk_text_ulb.usfm.zip)
![wa error](https://user-images.githubusercontent.com/8171759/45470628-20996780-b6f4-11e8-9cc0-d9bedda4c080.png)

**Comment by PhotoNomad0** [comment]
@cckozie - it looks like this crash is due to WA loading chapter front matter.  Think I have a quick fix.

**Comment by cckozie** [comment]
Fixed in 1.0.0 (e375ee0)
