### ISSUE TITLE
Scripture pane selections of en_ulb get changed to en_ult.

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#5048]
Whenever app is opened, scripture pane selections of en_ulb get migrated to en_ult.  So if I have en_ulb and en_ult selected in scripture pane, the next time I open app I will end up with two instances of en_ult and no en_ulb.  Since ulb is once again in the resources (or downloadable), it is a valid resource to be shown.  We should probably remove this migration from the current app.

**Comment by PhotoNomad0** [comment]
Verified in https://tc-builds.door43.org/build/release-v1.0.2/translationCore-win-x64-1.0.2-3943b93.setup.exe

**Comment by benjore** [comment]
Is this the same as #5287?
Yes, I closed it.

**Comment by cckozie** [comment]
Works in 1.0.2 (8c6f266)
