### ISSUE TITLE
Selecting CCO License More information has useless links

### ISSUE THREAD

**Issue by bspidel** [unfoldingWord/translationCore#5049]
### User Story
When importing a usfm file I was asked to select a licence
I clicked on See More. This took me to license page
Clicking on "publiciy or privacy" or "endorsement" links redirects to same page which offer no information about the links. Further search is disabled on window where web pages are displayed

As a user, I want see information about privacy or endorsement when I click on links so that I can learn more about them.

### Features / Specifications

- [ ] Links should point to information related to the link
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by cckozie** [comment]
All of the links on the CC0 See more page go to the appropriate CC pages, either the actual license or the FAQ.
