### ISSUE TITLE
Loading tools often does not show logo until just before tool appears.

### ISSUE THREAD

**Issue by bspidel** [unfoldingWord/translationCore#5052]
### Prerequisites

* Put an X between the brackets on this line if you have done all of the following:

- [ ] I have searched the [issues](https://github.com/unfoldingWord-dev/translationCore/issues) of this repository and believe that this is not a duplicate.

### Description
when loading and reloading wA and tW, the loading box has only the word "Loading..." but no logo. It is inconsistent but happens sometimes.

### Steps to Reproduce

1. Go to tools page
2. Click on launch for a tool
3. Note loading alert
4. Return to Tools page
5. Load the other tool
6 Note loading alert

Sometimes the logo is there sometimes it is not.

**Screenshots**
![loading blanks](https://user-images.githubusercontent.com/4968713/45576291-97de1100-b844-11e8-8105-fffac03dbad0.PNG)

**Expected behavior:** [Spinning logo]

**Actual behavior:** [Sometimes I do not see spinning logo]

### Context
I am filled with anguish, longing for the return of the spinning logo.
 
**Enviorment**
| Tech         | Version |
|--------------|---------|
| tc           | v1.0.0  |
| build #      |     (e375ee0)     |
| OS           |   x64, Win 10      |

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by cckozie** [comment]
Dup of #3522
