### ISSUE TITLE
Get Hindi Titus working in tW

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5062]
### User Story

As a [type of user], I want [some goal] so that [some reason].

### Features / Specifications

- [ ] Make sure "Please select the translation for: XYZ" shows in Hindi. 
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by benjore** [comment]
Publish as the initial Hindi IRV. Pull that into the catalog and into tC.

**Comment by klappy** [comment]
@jag3773 Here is the export of Anil's Hindi Titus aligned project in usfm3.

[hi_57-TIT.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/2390251/hi_57-TIT.usfm.zip)

**Comment by klappy** [comment]
@jag3773 My understanding is the following will get Hindi in tC for Titus tW tool as a gateway option:

1. Somehow you will publish the file I attached to the catalog.
2. A developer runs a script to update the resources packaged in the build.
3. We test to make sure it shows up.
