### ISSUE TITLE
Inconsistency in the way we handle USFM3 content as a resource and as an import file

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5074]
1.0.0 (e375ee0) 
(I have the latest English resources downloaded)
I downloaded and imported the USFM3 file at https://git.door43.org/unfoldingWord/en_ult/src/branch/master/45-ACT.usfm (I assume this is the same file that gets downloaded during resources download)
The system alerted me that Acts 19:41 was a missing verse
I loaded the imported project in wA
There I see that the text is shown in the ULT, but is missing in the target (imported file) and Greek.
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/f5adc59d-5162-48ff-923c-73f5ea324c6e)

The text looks a little strange in both the USFM3 file and the json file in the resources folder. Is this because there is no Greek text and consequently no alignments?
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/5148cbbc-b70a-4775-ab12-006b78007cad)
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/4fa0442c-c274-4688-826a-9116d70b4897)

1. Should this verse be included in the Greek? (I don't think it is one that is generally regarded as not being in the oldest Greek manuscripts)
2. Should tC handle the text differently depending on whether it is an imported project file or a resource file?

**Comment by benjore** [comment]
It appears that this is an issue with the UGNT. It should have 41 verses, but it merges 40 & 41 together.

**Comment by benjore** [comment]
@jag3773  has fixed the UGNT. It will be pushed to the catalog soon.

**Comment by benjore** [comment]
This is also an issue for 2 Cor 13:14 (13:12 actually contains the content for 12-13, 13:13 contains the content for 14 and 13:14 has nothing).

**Comment by benjore** [comment]
Will be fixed by #5079

**Comment by benjore** [comment]
There is still a problem of how the data is being handled. It appears that if a resource is imported as a resource it is displayed differently than the same resource being sideloaded (see Acts 19:41 above).

**Comment by cckozie** [comment]
I am looking into this further. The differences may have been an operator error problem.

**Comment by jag3773** [comment]
@cckozie There was definitely a problem in the UGNT, which we've fixed (there may still be an operator error problem!).

Note: The 2 Corinthians 13 versification issue *will not be changed*.  So you should expect to see the oddity in 2 Corinthians 13:14 until we get the ULT updated to match the UGNT.

The issue in Acts should disappear once the UGNT 0.4 is pulled in.
