### ISSUE TITLE
USFM markers and text missing in exported USFM3 files

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5075]
1.0.0 (e375ee0) 
Imported file [45-ACT.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/2397446/45-ACT.usfm.zip)

Exported file [45-ACT-export.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/2397449/45-ACT-export.usfm.zip)

I imported the file (which is the USFM3 file from the master on DCS), loaded it in wA, and then exported it. The exported file is missing several of the USFM markers. Some examples:
The \p on line 10, 317
The \s5 on line 757, 44559, 44929
The \q on line 1385, 2625, 2651
All of the verse text on line 44557 (probably related to #5074)
There may be others...
Not all of the USFM markers get stripped. The exported file has some of the \p, \5, and \q markers in tact.

**Comment by PhotoNomad0** [comment]
@cckozie - Are you sure you have the right USFM file here?  when I did usfm export with the same build I see the markers that were missing in your file.  The exported file above has some inconsistencies that look hand edited.

In my export, some newlines are missing before markers and dropped ugnt verses are formatted differently, but the markers are there.

[45-ACT-export.3.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/2398076/45-ACT-export.3.usfm.zip)

**Comment by cckozie** [comment]
@PhotoNomad0 Not sure what to say here. I did not do any hand editing of the file. I did open it in TextWrangler but never saved it from there.
I did a second export and it exactly matches my first export except for the timestamp on the first line.
I also did a CSV export to confirm that I had not done any editing of the project. 
I did run this test after previously forcing an update of the English resources, but don't see how that could account for what we're seeing.

**Comment by cckozie** [comment]
It looks like I must have actually imported an older version of the Acts USFM3 file. I retested with the current version of the file and see that I did not loose and p, q, m, or s5 markers. I will do further testing, but am closing this issue for now.
