### ISSUE TITLE
importing 0.9 project crashes app with critical error

### ISSUE THREAD

**Issue by bspidel** [unfoldingWord/translationCore#5082]
### Prerequisites

* Put an X between the brackets on this line if you have done all of the following:

- [x] I have searched the [issues](https://github.com/unfoldingWord-dev/translationCore/issues) of this repository and believe that this is not a duplicate.

### Description

When importing a 0.9 project, the app crashed with the following critical error: 
A critical error has occurred
TypeError: Cannot read property 'targetBible' of undefined

### Steps to Reproduce
1 Open tC
2 Online import the project https://git.door43.org/tCore-test-data/am_1co_ulb
3. See error

**Screenshots**

**Expected behavior:** [successful import]

**Actual behavior:** [application crash]

### Context

**Enviorment**
| Tech         | Version |
|--------------|---------|
| tc           | v1.0.0  |
| build #      |  e375ee0       |
| OS           |  x64 Win10       |

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by cckozie** [comment]
Project imports and opens properly in both tW and wA in 1.1.3 (240da43)
