### ISSUE TITLE
Problems with USFM3 formatting

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5086]
There are several books in the catalog that have usfm3 formatting problems. Some of them get fixed when a project is exported, and some of them do not. It appears that many of them are related to text that has quote marks in it. We should probably fix as many of these issues as we can assuming that we will likely get other people's usfm3 projects at some point and they may have similar issues.
Examples of formatting not getting fixed when exporting
Matthew 8:32 snippet from catalog:
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/a9957faf-e4b3-4903-a305-176bad18ef08)
Matthew 8:32 snippet from USFM3 export:
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/8a6ae2b3-a435-471a-af95-f3910c29feeb)

Matthew 9:15 snippet from catalog:
![image](https://user-images.githubusercontent.com/8171759/45843997-c184b580-bce6-11e8-89b9-ca459d2dd581.png)
Matthew 9:15 snippet from USFM3 export:
![image](https://user-images.githubusercontent.com/8171759/45844111-0c9ec880-bce7-11e8-82f5-d6058027cfca.png)

Matthew 27:33 snippet from catalog:
![image](https://user-images.githubusercontent.com/8171759/45845985-2989ca80-bcec-11e8-95e8-0b47cc26b809.png)

Matthew 27:33 snippet from exported usfm3:
![image](https://user-images.githubusercontent.com/8171759/45846027-46be9900-bcec-11e8-97d6-1a5723b91efa.png)

Here are some examples of where the formatting was fixed in the exported usfm3:
Matthew 4:6 snippet from catalog:
![image](https://user-images.githubusercontent.com/8171759/45845152-f0505b00-bce9-11e8-8c50-711641c7e489.png)
Matthew 4:6 snippet from USFM3 export:
![image](https://user-images.githubusercontent.com/8171759/45845389-943a0680-bcea-11e8-8416-28450bebf40b.png)

2 Cor 6:2 snippet from catalog:
![image](https://user-images.githubusercontent.com/8171759/45847830-f0ecef80-bcf1-11e8-832e-3e68368385f2.png)

2 Cor 6:2 snippet from usfm3 export:
![image](https://user-images.githubusercontent.com/8171759/45847885-2eea1380-bcf2-11e8-8947-133a143ab6a2.png)

**Comment by PhotoNomad0** [comment]
This will be fixed as part of https://github.com/unfoldingword-dev/translationcore/issues/5051.  The \w and \zaln markers will be placed at start of line on export.

**Comment by PhotoNomad0** [comment]
@cckozie - verified in https://tc-builds.door43.org/build/release-v1.0.2/translationCore-win-x64-1.0.2-34ddb63.setup.exe

**Comment by cckozie** [comment]
1.1.3 (240da43) 
I believe that the export now fixes the problems, but the problem in the source text of 2COR still exists.

**Comment by cckozie** [comment]
1.2.0 (b485978) 
The catalog source still looks the same.
The usfm3 export now looks different, and there are verse markers in the middle of some lines. Is that OK?
Apparently that is OK. Pinging Robert'.
