### ISSUE TITLE
Reports will sometimes not generate

### ISSUE THREAD

**Issue by EllDoubleYew** [unfoldingWord/translationCore#509]
When you try and generate a report, certain cases will give the error undefined(Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `ReportItem`. See https://fb.me/react-warning-keys for more information.)

It tends to happen more when you change the same check twice.

**Comment by ihoegen** [comment]
Any specific instances that cause this?

**Comment by ihoegen** [comment]
Fixed it, PR is out. It's caused by not having keys tied to the proposed changes options, and when multiple types of proposed changes are selected.
