### ISSUE TITLE
[0] SPIKE: Optimize Tool Loading

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5094]

**Comment by RoyalSix** [comment]
Top Candidates For Optimization:
- [ ] `sendProgressForKey`
- [ ] ``

**Comment by RoyalSix** [comment]
Notes: Rating is based on 1 - 10 scale of estimated performance gain from increasing efficiency of function
- Project Loading Actions`loadAllGroupsData` 8
- ToolCard `render` calling `getGatewayLanguageList` 5
- Resource Actions`loadBooks` 4
- `getFoldersInResourceFolder` 3
  - `getAllLanguageIdsFromResourceFolder`
  - `getValidResourcePath`
