### ISSUE TITLE
Reinstall after failed install completes in 1 minute

### ISSUE THREAD

**Issue by bspidel** [unfoldingWord/translationCore#5104]
### Prerequisites

* Put an X between the brackets on this line if you have done all of the following:

- [x] I have searched the [issues](https://github.com/unfoldingWord-dev/translationCore/issues) of this repository and believe that this is not a duplicate.

### Description

Attempted to install/load latest build. After 30 minutes of waiting, I killed loader. I immediately installed same downloaded build and it completed in 1 minute

### Steps to Reproduce

1. Download build  1.0.0 (4bd6856) x64
2. Double click to install on Win10 desktop
3. Check to auto launch
4. Wait 30 minutes for load to complete
5. Kill loading tC
6. Repeat steps 2-3
7. Notice that load completes in about a minute

**Screenshots**

**Expected behavior:**Expected it to load on first try

**Actual behavior:** Loaded on second attempt to install

### Context

**Enviorment**
| Tech         | Version |
|--------------|---------|
| tc           | v1.0.0  |
| build #      |  (4bd6856)        |
| OS           |  Win10       |

### Additional Information

Did not pre remove resources or projects

For previous builds I have pre removed projects and or resources and build would install/load on first attempt.

**Comment by cckozie** [comment]
This is not a bug
