### ISSUE TITLE
A critical error has occurred message encountered

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5105]
I have again encountered the critical error message when writing a script to test that all NT projects could be opened in both wA and tW. I'm not sure, but I think the error occurred when I was in wA and clicked the tool icon on the menu bar. I then created a script specifically to test for that problem.
The script sequentially loads all of the NT USFM3 projects that I downloaded from https://git.door43.org/unfoldingWord/en_ult/. It imports the project, then loads it in tW, and then loads it in wA. Several times it failed after loading Acts in wA and then returning to the tools page. One time if made it through the entire NT and then failed at the same place when loading Matthew on the second loop.
After several failures I closed all other apps to see if that would help. It actually seems to fail more often in that scenario. Because of the console error message I though maybe it didn't have time fo fully load the json file, so I put in a delay of five seconds after wA is loaded before the tool icon in the menu bar is clicked. This time it made it through the entire NT once, then failed after loading Luke.
As far as I can tell there has not been any data loss, so it is probably not necessary to deal with this for 1.0, but it probably does need to be investigated to help confirm that is true.
The steps followed in the test script are as follows:
1. Import the first/next book from a local folder
2. Choose the CC-BY-SA license and click Continue
2. Give it a unique translation id and click Continue
3. Click Continue if the Missing verses screen is diplayed
4. Load the project in tW
5. Click OK if the invalidated alignments alert is displayed
6. Click the tool icon in the menu bar
7. Load the project in wA
8. Click the tool icon in the menu bar
9. Click the Go to projects button
10. Go to step 1.

Here are a couple of console error screenshots.
![wa crash](https://user-images.githubusercontent.com/8171759/46021235-d1651680-c0a5-11e8-8b60-4a407c074d9c.png)

![crash2](https://user-images.githubusercontent.com/8171759/46021262-e346b980-c0a5-11e8-946e-63a4722cd94b.png)

**Comment by da1nerd** [comment]
This is due to tC manually reading data from the project instead of asking the tool for it. This will be fixed by #4884.

As a temporary fix I can add some error handling to tC.

**Comment by mannycolon** [comment]
@neutrinog FYI: I noticed you are referencing #4884 but it is closed? did you mean to reference that issue number or a different one?

**Comment by da1nerd** [comment]
Tada! it's now reopened. :) I must have accidentally closed it because it's definitely not done yet.

**Comment by cckozie** [comment]
Need to retest with 1.0.2 build. The last test I ran with the lastest (at that time, 10/3 I think) 1.0.0 build, the program did not crash with the indicated error, and there were messages in the console that seemed to indicate that the error was trapped, but the app did slow significantly as the script made its way through all of the NT books.

**Comment by cckozie** [comment]
1.0.2 (6ab77c0)
The test script loaded the entire NT 3 times with no degradation in performance. It then failed while loading Mark in tW during the 4th loop. Unfortunately I was on hangouts when it failed so was not able to see the failure or console messages. I'm going to pass this for now and note in  #4884 to rerun this test when it is in QA. Use the tC_Test_Loading sikuli script.
I will also run the script tonight after removing the call to reload tC after a failure.
