### ISSUE TITLE
Re-Add Target & Original languages to Scripture Pane (tW & wA)

### ISSUE THREAD

**Issue by bspidel** [unfoldingWord/translationCore#5119]
## User Story

As a user, I want to be able to close the target language and the original language in the Scripture Pane in the wA and tW tools and then go back in and re-add them back in, so that I never get stuck unable to load the Target & Original language into the Scripture Pane. 

## Specs
- [ ] Show the target & original languages into the Scripture Pane dropdown
- [ ] make sure they work

===

### Prerequisites

* Put an X between the brackets on this line if you have done all of the following:

- [x] I have searched the [issues](https://github.com/unfoldingWord-dev/translationCore/issues) of this repository and believe that this is not a duplicate.

### Description

The scripture pane add resources tool will allow you to select grc but it will not load it. If you leave the tool and come back then it is there.

### Steps to Reproduce

1. Launch Word Alignment
2. Delete Original Language
3. Try to add it
4. Does not appear

**Screenshots**

**Expected behavior:** see grc nt

**Actual behavior:** nothing

### Context

**Enviorment**
| Tech         | Version |
|--------------|---------|
| tc           | v1.0.0  |
| build #      | 4bd6856        |
| OS           | x64 Win10        |

**Comment by PhotoNomad0** [comment]
From discussion with @benjore:

Dropdown language selections:
- target language should be like `Kiswahili (sw) (Target Language) (Current Project)`
- language code for original language should show `(Original Language)`

**Comment by PhotoNomad0** [comment]
Verified in https://tc-builds.door43.org/build/develop/translationCore-macos-x64-1.1.0-66be15e.dmg

**Comment by cckozie** [comment]
Works in 1.1.1 (f6a4c6b)
