### ISSUE TITLE
Improve the workflow for changing and commiting changes to submodules

### ISSUE THREAD

**Issue by EllDoubleYew** [unfoldingWord/translationCore#512]
As it currently stands it can be confusing to pull the new submodules. The only sure-fire way to do it is to manually go into each repo for each submodule and pull before you commit to the main TC repo. It is difficult. We need to research and implement a better way to update these submodules.

**Comment by ihoegen** [comment]
@EllDoubleYew @mannycolon @RoyalSix When developing for submodules, you have the following commands at your disposal:

`npm run pull-apps`: What this does is goes into each submodule and checkouts to the latest version of master for each submodule. Helpful for after you're done developing, about to add code you've already pushed. This was recently fixed today. 

`git submodule update`: This will checkout the submodules to whatever commit is designated by the current state of develop. Very helpful for if you're like me, and develop your submodules directly in the tC_apps folder. 

`git submodule foreach --recursive ANY COMMAND HERE`: This is by far the nicest tool at your disposal, allowing you to act out commands on all the submodules. That's how pull-apps works, by checking out to master and pulling for every submodule. Let your imagination run wild on this one.
