### ISSUE TITLE
Sometimes badge hint does not display on mouse over

### ISSUE THREAD

**Issue by bspidel** [unfoldingWord/translationCore#5120]
### Prerequisites

* Put an X between the brackets on this line if you have done all of the following:

- [X] I have searched the [issues](https://github.com/unfoldingWord-dev/translationCore/issues) of this repository and believe that this is not a duplicate.

### Description

Having edited a verse not being checked, the badge panel does not show with multiple badges when performing mouseover the badge area.

### Steps to Reproduce

1. Select project en_test_tit_book
2. Launch translationWords
3. Select christ 1:1 in menu
4. Expand Scripture Pane
5. Edit verse 1:4
6. add some words
7. Check grammar
8. Click Save
9. click close

Note badges on 1:1 and 1:4
Verify that badge hint will show on mouseover

**Screenshots**

**Expected behavior:** panel with all badges

**Actual behavior:** crickets chirping

### Context

**Enviorment**
| Tech         | Version |
|--------------|---------|
| tc           | v1.0.0  |
| build #      | 4bd6856        |
| OS           | x64 Win10        |

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by cckozie** [comment]
This is not a bug.
Badge hints on mouse-over are only supposed to be displayed when more than 1 badge (icon) is related to the verse/check.
