### ISSUE TITLE
importedSource is not being written on USFM2 import 

### ISSUE THREAD

**Issue by bspidel** [unfoldingWord/translationCore#5122]
### Prerequisites

* Put an X between the brackets on this line if you have done all of the following:

- [x] I have searched the [issues](https://github.com/unfoldingWord-dev/translationCore/issues) of this repository and believe that this is not a duplicate.

### Description

When importing a raw USFM 2 file, I expected to see the unparsed source stored in the generated  project.

### Steps to Reproduce

1. Import a USFM 2 book
2. Look in projects directory
3. Note there is no importedSource folder contianing original usfm2

**Screenshots**

**Expected behavior:** importedSource folder

**Actual behavior:** stored as USFM3 in project folder which is much harder to read

### Context

**Enviorment**
| Tech         | Version |
|--------------|---------|
| tc           | v1.0.0  |
| build #      | 4bd6856       |
| OS           | x64 Win10        |

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by cckozie** [comment]
Not seeing the problem in 2.0.0 (4b3ebee)
