### ISSUE TITLE
Software update is broken for Win64

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5130]
I don't have any way to test the 1.0 build functionality until something later is available, but we need to either fix it or somehow verify that this problem does not exist in 1.0.
Running Check for software update from version 0.10.1 (bb230ee) on my Window 64 machine.
It correctly found the 1.0 release, but when I clicked Download, it downloaded the Win32 setup file. When running that install file a message is displayed stating that it can't be installed on my machine.
![image](https://user-images.githubusercontent.com/8171759/46320163-aba6a880-c5a2-11e8-9089-162a270f1827.png)

**Comment by da1nerd** [comment]
builds for this are ready at http://tc-builds.door43.org/build/release-v1.0.1/

**Comment by jobbyp** [comment]
![image](https://user-images.githubusercontent.com/38230054/47727438-c36d5d00-dc32-11e8-9292-58c9dd2bc24d.png)

The installer (translationCore-win-x32-1.0.2-0159185.setup) does not install the application in a 64 bit processor even with a 32bit OS.

**Comment by cckozie** [comment]
Per Jobby it works in 1.0.2 (5ebb84f)). He's creating a separate issue for being unable to install 32 bit on 64 bit machine.
