### ISSUE TITLE
Fix USFM3 export: USFM3 export strips out spaces between punctuation

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5133]
### User Story

As a translator, I want whitespace preserved so that my text displays properly.

### Features / Specifications

Also see #5063
- [ ] There are times that punctuation should be `, "` (with space) for instance, `Jesus said, "Come to me...` but there are also times when the punctuation should be `,"` (without space) for instance, `"Come to me," Jesus said...`
- [ ] Preserve all spaces in between punctuation

To reproduce:
- Load a Titus USFM2 project where Titus 1:12 reads `One of their own prophets has said, "Cretans are always liars, evil beasts, lazy gluttons."` (should have a space between the comma and double quote)
- Go into WA and align a word
- Go back to the project card and export as USFM3
- Note in the USFM3 file that it reads `\zaln-e\*,"` in the `\v 12` content
- Import this USFM3 file as a new project. Note that now in the Scripture Pane it is also without a space

Note that it isn't just `, "` but also any number of punctuation marks, e.g. `, '`, `. "`, etc.

### Definition of Done

- [ ] 
- [ ]
- [ ]

**Comment by PhotoNomad0** [comment]
Needs to be fixed in usfm3 export method which is doing a simplistic join(' ') in getOrderedVerseObjectsFromString()

**Comment by PhotoNomad0** [comment]
@richmahn - you should be able to get a quick turn-around on this.  All you need to do is merge in https://github.com/unfoldingWord-dev/translationCore/pull/5213.

**Comment by PhotoNomad0** [comment]
fixed as part of https://github.com/unfoldingword-dev/translationcore/issues/5051

**Comment by richmahn** [comment]
Assigned to @PhotoNomad0 since he fixed it.

**Comment by cckozie** [comment]
Works in 1.0.2 (b84794c)
