### ISSUE TITLE
Import Strong's Lexicon as the OT Lexicon

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5134]
### User Story

As a Old Testament aligner, I want a Hebrew Lexicon in the Word Alignment Tool so that when I find some obscure word I don't know I can get a quick definition.

### Features / Specifications

- [ ] Import Strong's Lexicon
- [ ] When the user clicks on a Hebrew word (in the Scripture Pane or in the wA tool), the gloss that is displayed comes from Strong's
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by jag3773** [comment]
The lexicon to import is at https://github.com/openscriptures/HebrewLexicon .  Data to import is in https://github.com/openscriptures/HebrewLexicon/blob/master/HebrewStrong.xml .

You probably want to pull in the `<meaning>` and `<usage>` data.  Make sure that you encode the strong's numbers in the same format used by the Hebrew text (see https://github.com/unfoldingWord-dev/translationCore/issues/3414 and https://git.door43.org/unfoldingWord/UHB ).

**Comment by jag3773** [comment]
@benjore If possible, it would be much better to pull in https://github.com/eliranwong/unabridged-BDB-Hebrew-lexicon .

**Comment by jag3773** [comment]
Note that entries from that BDB lexicon can be viewed using this tool https://marvel.bible/tool.php?bdb=H6 .

**Comment by PhotoNomad0** [comment]
> @benjore If possible, it would be much better to pull in https://github.com/eliranwong/unabridged-BDB-Hebrew-lexicon .

@benjore @jag3773 - it looks like this repo has a lot of html to parse and remove.  Think I had a python script that did some of that for web converter.

**Comment by PhotoNomad0** [comment]
@benjore @jag3773 - have the Hebrew Lexicon working in the app now.  Where do I find the definitions for the missing Hebrew morphology?

**Comment by PhotoNomad0** [comment]
<img width="444" alt="screen shot 2018-11-21 at 11 51 20 am" src="https://user-images.githubusercontent.com/14238574/48865232-d7b0ff80-ed83-11e8-906b-c4d312ecdc4a.png">

@benjore - this is how it looks so far, but missing some morphology.

**Comment by jag3773** [comment]
Morph codes at http://openscriptures.github.io/morphhb/parsing/HebrewMorphologyCodes.html .

**Comment by PhotoNomad0** [comment]
<img width="440" alt="screen shot 2018-11-24 at 6 23 35 am" src="https://user-images.githubusercontent.com/14238574/48969302-e11faf00-efb1-11e8-854a-59bd4864984d.png">
<img width="436" alt="screen shot 2018-11-24 at 6 24 01 am" src="https://user-images.githubusercontent.com/14238574/48969304-e3820900-efb1-11e8-89dd-363fd241bb60.png">
<img width="434" alt="screen shot 2018-11-24 at 6 24 32 am" src="https://user-images.githubusercontent.com/14238574/48969307-e67cf980-efb1-11e8-9aa2-c07e3c4f1341.png">

@jag3773   - here are a few examples.  How does this look?

**Comment by PhotoNomad0** [comment]
@benjore - How does this look? ^^^

**Comment by PhotoNomad0** [comment]
@benjore @jag3773 - also the first example of the three is a multipart word.  In the morphology, I just displayed the parts separated with colons as the both the Strong's and source morphology are.  Is that sufficient?  Should we use `/` as a delimiter as other references do?  Or maybe separate out the prefix as Biblearc does?

**Comment by PhotoNomad0** [comment]
> > @benjore If possible, it would be much better to pull in https://github.com/eliranwong/unabridged-BDB-Hebrew-lexicon .
> 
> @benjore @jag3773 - it looks like this repo has a lot of html to parse and remove. Think I had a python script that did some of that for web converter.

@jag3773 The current word popup only supports simple text.  Will look into how we can add html support so we can show the rich formatting like in the example at https://marvel.bible/tool.php?bdb=H6

**Comment by PhotoNomad0** [comment]
<img width="432" alt="screen shot 2018-11-26 at 5 33 04 am" src="https://user-images.githubusercontent.com/14238574/49017139-efe69d00-f13c-11e8-8e78-82d6bcda9ff0.png">

@benjore @jag3773 - here is an alternate formatting option.

**Comment by jag3773** [comment]
@PhotoNomad0 Ideally we could show a separate pop-up for each part of the word.  In your multipart word example, I would love to see 3 pop ups, each one giving the information relevant for that part of the word.

I like your formatting of the lexicon entry in the latest example.

**Comment by PhotoNomad0** [comment]
@jag3773 - and how should we arrange those popups on the screen?

**Comment by PhotoNomad0** [comment]
OK, think I get it.

**Comment by PhotoNomad0** [comment]
![screen shot 2018-11-28 at 8 29 06 am](https://user-images.githubusercontent.com/14238574/49154982-cf0e7b00-f2e7-11e8-8eb8-7ba44e53c0ff.png)

Here is an example from BibleArc - they are showing prefix info at the bottom.  It seems it would probably be easier for the user if we show all the parts in a single pop up rather than making the user have to click on a specific letter.

**Comment by PhotoNomad0** [comment]
![screen shot 2018-11-28 at 8 54 01 am](https://user-images.githubusercontent.com/14238574/49156360-3679fa00-f2eb-11e8-874e-afe7054b0196.png)

@benjore @jag3773 - how about something like this?

**Comment by jag3773** [comment]
Looking good.  I don't think there is a need for the "Strongs" line for the prefixes and suffixes -- looks like the morphology line is giving all that is needed.

I would prefer to put the main word information first and then the prefix and/or suffix information after that, like the Biblearc pop up does it.  That will front the most important information for the user.

**Comment by PhotoNomad0** [comment]
@jag3773 - here is some content from uhb (Gen 41:8).  Is the format of the first word here correct?  I would expect the strongs to have two parts like the morph string and similar to the strongs in the second word below.

```
      {
        "text": "חֲכָמֶ֑י​הָ",
        "tag": "w",
        "type": "word",
        "lemma": "חָכָם",
        "strong": "H2450",
        "morph": "He,Aampc:Sp3fs"
      },
      {
        "text": "וַ​יְסַפֵּ֨ר",
        "tag": "w",
        "type": "word",
        "lemma": "סָפַר",
        "strong": "c:H5608a",
        "morph": "He,C:Vpw3ms"
      },
```

**Comment by PhotoNomad0** [comment]
I wonder if it is just suffixes that are different in strongs?

**Comment by jag3773** [comment]
Suffixes generally will not have Strongs numbers.

**Comment by PhotoNomad0** [comment]
So prefixes are added to strongs numbers as in "c:H5608a", but not suffixes?

**Comment by jag3773** [comment]
Yes, that's what I'm seeing.

**Comment by PhotoNomad0** [comment]
Note:  @jag3773 suggested on a private channel:

- if we swapped a strongs number in for `d` or `c` would your code automatically pick up the lexicon entry for it @bruce.mc?

- need to add message "Morphology not found" when it is missing in UHB since it is not yet complete.

**Comment by cckozie** [comment]
Can't fully test until #5543 is fixed.

**Comment by cckozie** [comment]
Works as best I can tell in 1.1.0 (4d06842). Really need someone with Hebrew expertise to verify. I assume that any issues will be exposed and raised by the aligners.
