### ISSUE TITLE
Remove unnecessary reload of tool

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord/translationCore#5135]
### User Story

As a user, I want to open a project with a tool and be able to go back to the stepper's tools page and relaunch the same tool without it reloading the tools data again.

## Explanation
- When Im within a tool and go back to home stepper tool's page and select the same tool again it reloads the tools data when it should display the tool view again without having to load the data again

## Notes
- When the user clicks `Launch` from the Home Screen, it does this. Make the Tool card function the same way.
- [ ] If the categories selections have changed, then a reload is necessary
- [ ] The functionality of the Launch button in the Home Screen needs to have the same functionality as the Launch button on the Tools page.

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by mannycolon** [comment]
- Now data reload may be required if category names are changed by the user

**Comment by mannycolon** [comment]
Verified on 89d7abe

**Comment by elsylambert** [comment]
Verified on  1.2.0 (70f669f). Able to load the Projects tools without reloading the data. Not seeing any issues.

**Comment by cckozie** [comment]
1.2.0 (736956e)
Appears to work correctly without reloading the data. May want to retest after #6168 and #6250 get through.
