### ISSUE TITLE
Improvements to scrolling of the group menu

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5140]
When the user manually scrolls the menu, it should stay in that position until the user moves it. (Fixed in wA in 1.0.2 (b84794c))

When the app automatically scrolls it (as in tW), the highlighted element should always stay in view. There is probably no need for auto-scrolling in wA.

Current problems with auto-scrolling:
Word Alignment scenario A:(Fixed in 1.0.2 (b84794c))
When the scroll bar is not at the top and the user clicks on a verse, that verse is moved to the top which causes more screen changes (and user disorientation) than desired/necessary.

Word Alignment scenario B: (Fixed in 1.0.2 (b84794c))
Screen shot 1
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/f8e97c6a-6066-4e4c-9a81-b1f6160ffa45)

Scrolled manually to next element (1:18)
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/5f90bda3-758b-4908-aab6-5d1e92808289)

Clicked on verse 1:18. Notice that it is now no longer in view.
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/a58c9c1c-5755-445c-b8cc-43fc9a82654b)

translationWords: (This is still a problem in 1.0.2 (b84794c))
The same problem (selected element not in view) exists when the user clicks Save & Continue after making a selection on the last menu element on the screen.
In that case, the menu should be scrolled down just enough so that the selected check remains at the bottom of the visible menu.
After making selection
![image](https://user-images.githubusercontent.com/8171759/46374417-4d3b0200-c656-11e8-81a4-03492de5e280.png)

After clicking Save & Continue
![image](https://user-images.githubusercontent.com/8171759/46374490-6ba0fd80-c656-11e8-8bac-02b479d01877.png)

**Comment by PhotoNomad0** [comment]
@neutrinog - is not yet in the build.  You can either do a PR to tC, or wait for my PR to get merged which will include this tc-ui-toolkit fix.

**Comment by da1nerd** [comment]
@PhotoNomad0 it was brought into tC with this PR. see the attached builds. https://github.com/unfoldingWord-dev/translationCore/pull/5314

**Comment by PhotoNomad0** [comment]
@cckozie - Here are the builds:

https://tc-builds.door43.org/build/release-v1.0.2/translationCore-win-x32-1.0.2-a18aef8.setup.exe
https://tc-builds.door43.org/build/release-v1.0.2/translationCore-win-x64-1.0.2-a18aef8.setup.exe
https://tc-builds.door43.org/build/release-v1.0.2/translationCore-macos-x64-1.0.2-a18aef8.dmg
https://tc-builds.door43.org/build/release-v1.0.2/translationCore-linux-x64-1.0.2-a18aef8.deb

**Comment by cckozie** [comment]
Tested in 1.0.2 (b84794c) which is later than 1.0.2-a18aef8.deb.
Failure 1: The problem described in the top comment related to translationWords has not been fixed.
Failure 2: The fix appears to have broken the feature that closes the open group when the user clicks on the 'V' of the group name. Instead, it now leave the group open and activates the first element in the group. This is the case in both tW and wA.

**Comment by PhotoNomad0** [comment]
@neutrinog - it looks like the tc-ui-toolkit is up to 0.11.4 in 1.0.2.  So this should be in.  Just need to verify in recent build.

**Comment by PhotoNomad0** [comment]
@neutrinog @neutrinog - I tried to verify that this is in the current build, but didn't know how to test `Failure 1: The problem described in the top comment related to translationWords has not been fixed.` listed above

**Comment by cckozie** [comment]
I also see another problem in 1.0.2 (8c6f266) related to the Failure 2 comment above. Clicking on the V does now close the group as expected, but now when the group is open, in wA clicking on the group name closes the group. The group should only be closed if the user clicks on the V or on another group name as it works in tW and as it worked in 1.0.0.

**Comment by cckozie** [comment]
I've consolidated the current issues here. Now testing with  1.0.2 (0159185)
Failure 1:
translationWords:
The same problem (selected element not in view) exists when the user clicks Save & Continue after making a selection on the last menu element on the screen.
In that case, the menu should be scrolled down just enough so that the selected check remains at the bottom of the visible menu.
After making selection
![image](https://user-images.githubusercontent.com/8171759/46374417-4d3b0200-c656-11e8-81a4-03492de5e280.png)

After clicking Save & Continue
![image](https://user-images.githubusercontent.com/8171759/46374490-6ba0fd80-c656-11e8-8bac-02b479d01877.png)

Failure 2:
Clicking on the V does now close the group as expected, but in wA now when the group is open, clicking on the group name closes the group. The group should only be closed if the user clicks on the V or on another group name as it works in tW and as it worked in 1.0.0.

Failure 3:
1. Open a book in wA
2. Open a chapter that has more verses than fit on the screen
3. Click on the bottom verse on the screen (verse 17 on my Macbook)
4. Click on the Alignment Complete switch to set it
5. Scroll the menu up just enough to see the next verse (verse 18 on my Macbook)
6. Click on the newly displayed verse
The selected verse is now scrolled off the bottom of the screen.
[menu scrolling.mov.zip](https://github.com/unfoldingWord-dev/translationCore/files/2526585/menu.scrolling.mov.zip)

Currently, when the second verse past the bottom of the menu (verse 19 on my Mac) is clicked, it is scrolled to the top of the menu, and clicking on subsequent verses also scrolls them to the top. This is probably a good thing (contrary to my comment about no reason to auto-scroll in wA). If it is just as 'easy' to make clicking on verse 18 behave the same as 19 and above, that would be preferable. It that is more work than just keeping 18 in view, I will write it up as a separate issue.

**Comment by PhotoNomad0** [comment]
@cckozie @benjore  - OK here is how I understand the group navigation should behave:

- on click of menu title:
  - if not the active group, select group and expand
  - if it is the active group, make sure it's expanded and select first element

- on click of the expand icon:
  - if not the active group, select group and expand group
  - if it is the active group, expand group

- on click of the collapse icon:
  - collapse the group (it's only shown on active group)

Does that match your expectations?

**Comment by cckozie** [comment]
@PhotoNomad0 - There is one change to your description that will make it work as it did in the past: Whenever the user clicks on a group name, regardless of whether or not it is currently expanded, the first element of the group should be activated.

**Comment by PhotoNomad0** [comment]
@cckozie  - to clarify, if the current group is already expanded, when you click on the group title, you want the selected item to be changed to the first element?
@PhotoNomad0 - Yes. That is the way it worked in 1.0.0.

**Comment by PhotoNomad0** [comment]
### Note
~Worked with Kos and made one difference from above.  Due to quirks in React scrollIntoView(), made change that when scrolling up will scroll item to top of screen instead of just at bottom of screen.~

Was able to get it to work - turned out it was not a react problem, but chromium problem that our older version of chromium does not support options in scrollIntoView() and was able to get it to scroll to bottom by passing false as parameter.

**Comment by PhotoNomad0** [comment]
Tested in build: https://tc-builds.door43.org/build/release-v1.0.2/translationCore-win-x64-1.0.2-f3e86ca.setup.exe

**Comment by cckozie** [comment]
In wA it now scrolls the selected issue to the bottom when there should not be any scrolling. Per first comment above: 'When the user manually scrolls the menu, it should stay in that position until the user moves it.'
[scrolling wa.zip](https://github.com/unfoldingWord-dev/translationCore/files/2539350/scrolling.wa.zip)

**Comment by PhotoNomad0** [comment]
@cckozie - Found that toggling the alignments complete button caused a screen redraw which in turn scrolls the selected item.  Didn't see an easy solution, so handed off to @mannycolon to see if he could find a solution.

**Comment by PhotoNomad0** [comment]
@cckozie - tested in https://tc-builds.door43.org/build/release-v1.0.2/translationCore-win-x64-1.0.2-7ccb0dc.setup.exe

Just a quick fix to scroll to the top of the screen when off the screen.  Seems to be better, but still scrolls sometimes when it should not.  At least now does not scroll to bottom of screen.

**Comment by cckozie** [comment]
1.0.2 (7ccb0dc)
Scrolling in tW works ok.
Scrolling in wA still has issues. Created new issue #5379 for these problems and passing this one so that we don't hold 1.0.2.
