### ISSUE TITLE
When user adds the Hindi IRV to the scripture pane, the Hindi ULB also gets added

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5158]
1.0.0 (ea3713f)
[projects.zip](https://github.com/unfoldingWord-dev/translationCore/files/2447342/projects.zip)

1. Unzip the attached file into the projects directory
2. Load the en_ult_tit_book project in tW
3. Add the English ULT to the scripture pane
4. Return to the projects page
5. Load the hi_ult_tit_book project in tW
6. Add the Hindi IRV resource to the scripture pane
Notice that both the Hindi IRV and ULB get added

**Comment by benjore** [comment]
I think this will be covered by #4858

**Comment by elsylambert** [comment]
Retested in 2.0.0 (4b3ebee). Not seeing this issue.
