### ISSUE TITLE
Create 1.0 changelog

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5162]
### User Story

As a [type of user], I want [some goal] so that [some reason].

### Features / Specifications
- [x] Run the changelog generator script in translationCore root directory
- [x] Commit and push the updated CHANGELOG.md file to the branch.
- [x] Merge the translationCore `release` branch into `master`.
- [ ] In project on github (https://github.com/unfoldingWord-dev/translationCore) click on releases, and click on “draft a new release” button. Set the tag version for release number, `v1.0.0`.  Set target to ‘master’.  Set “Release Title”, like ‘translationCore v1.0.0’
- [ ] The latest builds from the translationCore `release` branch should be manually uploaded to the release entry.  These should be the exact same binaries that QA tested.
- [x] Get the release notes from the Product Owner.  
- [x] Update the links to CHANGELOG.md as to the release on github.
- [x] If the release notes are in a Google Doc, convert to mdCopy the markdown from your forum post and save to the release description.
- [x] Also download a PDF of the release notes.  And then upload the PDF to the release assets.
- [ ] Click “Save Draft” and then send the link to Product Owner to review.
- [ ] After Product Owner review, edit release, make any final changes as required, then click “Publish release”.

### Definition of Done

- [ ]
- [ ]
- [ ]

## Additional Context
Followed instructions at: https://docs.google.com/document/d/1-dJvDrxjIYwiUKUnH-E8qZel-DCDhsgM8iR-n9Cm57w/edit#heading=h.cpjfjflacbxg

**Comment by cckozie** [comment]
The link in the 1.0.0 Release Notes now correctly sends the user to the page that now includes the 1.0.0 change log.
