### ISSUE TITLE
SPIKE: Find the best way to pipe feedback from the app to the developers

### ISSUE THREAD

**Issue by EllDoubleYew** [unfoldingWord/translationCore#517]

**Comment by ihoegen** [comment]
So we have a couple of options, and very few when it comes to free options. All of the following are compatible with Node.js, and have NPM packages.

- Rollbar
    - https://rollbar.com/
    - Free plan: Up to 5000 errors a month, only 30 days of data retention
    - Pros:
        - Seems to be all inclusive.
    - Cons: 
        - Limmited by price. 
- Nodemailer
    - https://community.nodemailer.com/
    - Is simply just an email client. We could send emails to an account dedicated to handling crash reports.
    - Pros:
         - Unlimited errors
         - Free
     - Cons:
         - A lot of setup
- HockeyApp
    - https://hockeyapp.net/
    - Pros:
         - Unlimited errors
         - Free plan supports up to 2 apps
         - Developed and maintained by Microsoft
        - Allows for user tracking.
     - Cons:
         - Honestly can't find any. 

Now in terms of implementations, I think we should go with HockeyApp. I also think that we could link it directly to the `console.error` modal, and give users an option to send the error to us, or we could just send it automatically. We could also allow users to write their own comments, describing how they got to the error, or use `desktop-screenshot` to even grab a screenshot as well. HockeyApp would also allow for their to be an easy to access text box where users could write their feedback to us.

**Comment by ihoegen** [comment]
@klappy Here's the results on my research for a feedback system, I think HockeyApp is the way to go.

**Comment by RoyalSix** [comment]
+1  for hockey app

**Comment by ihoegen** [comment]
Alright Hockey App is how I'll do it

**Comment by ihoegen** [comment]
Was there another issue associated with this @klappy @benjore ?
