### ISSUE TITLE
wA tools slows and becomes unusable

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5174]
### Description

Reported by Larry when aligning Romans. The app slows down and he needs to close tC after aligning each chapter in order to keep it usable.

### Steps to Reproduce

Import this usfm2 project.
[45-ACT.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/2455944/45-ACT.usfm.zip)

1. Starting with verse 1:1
2. Click the Alignment complete switch.
3. Click on the next verse
4. Repeat steps 2 and 3 until the chapter is finished
5. When the chapter is complete, open the next chapter.
6. Repeat steps 2 - 5 watching for a significant slowdown in performance
On my Mac, the app is pretty much unusable by the time I get to 2:16. When I get to 2:20 it takes 30 seconds to change to the next versed.

Nothing telling in the console.

**Expected behavior:** 
The app should not slow significantly as it is being used.

**Actual behavior:** 
See above

### Context

**Enviorment**
| Tech         | Version |
|--------------|---------|
| tc           |  1.0.0 (8adaf14)  |
| build #      |         |
| OS           |      Mac   |

### Additional Information
I suspect this may have something to do with the weird scrolling in the group menu. I can fully align the entire book of Acts without seeing a significant performance problem as long as I do not scroll the group menu beyond the verses that fit on the screen, 17 verses in the case of my Mac. Once I get beyond the 17 verses the scrolling becomes strange. Verse 18 gets scrolled off of the screen once I click on it, verses 19 and following automatically get shifted to the top of the menu. #5140 addresses the scrolling weirdness issue.

**Comment by da1nerd** [comment]
The majority of the performance loss is in `changeCurrentContextID@ContextIdActions.js` and accounts for over 60% of the time. There's some rendering that could be improved but those are negligible compared to the context change.

Plan of attack:
- [ ] optimize context changing (tc)
- [ ] optimize menu rendering (tc-ui-toolkit)

### Update
The entire book is being read and parsed each time the context changes. We should only load the book once and cache it. This should be easy to fix and should drastically improve performance. However, now that we have dynamic content update the cache will need to be cleared if a book is updated.

**Comment by da1nerd** [comment]
@cckozie while working on this I also discovered what I think accounts for roughly 75% of the tool loading time and could probably be removed. I'll open a new issue with details.

**Comment by da1nerd** [comment]
Here's a new issue describing how we should be able to greatly improve the performance of loading tools. As a side benefit this should also improve the performance of the application overall. 
https://github.com/unfoldingWord-dev/translationCore/issues/5284

**Comment by da1nerd** [comment]
This is in the latest builds 

https://tc-builds.door43.org/build/release-v1.0.2/translationCore-win-x32-1.0.2-a18aef8.setup.exe
https://tc-builds.door43.org/build/release-v1.0.2/translationCore-win-x64-1.0.2-a18aef8.setup.exe
https://tc-builds.door43.org/build/release-v1.0.2/translationCore-macos-x64-1.0.2-a18aef8.dmg
https://tc-builds.door43.org/build/release-v1.0.2/translationCore-linux-x64-1.0.2-a18aef8.deb

**Comment by cckozie** [comment]
It is either fixed or WAY better in 1.0.2 (5ebb84f)
