### ISSUE TITLE
In the alignment tool, selected words in the word bank should automatically be unselected when navigating to a different verse or clicking outside of the word bank

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5175]
## Specs

- [ ] Whenever a user has any words selected in the word bank of the wA tool...
  - [ ] If the user clicks anywhere that does not select another word, the words should deselect (WordMAP buttons, words that are already aligned, Scripture Pane, side menu, etc.)

### Description

If a user selects one or more words in the word bank for aligning and then navigates to a different verse, the words in the word bank corresponding to the previously selected words, automatically get  (remain) selected.

### Steps to Reproduce

Open a project in wA.
Select one or more words in the word list as though you were going to align them.
Navigate to a different verse
Notice you now have different words pre-selected.

**Screenshots**

**Expected behavior:** 
Any selected words should automatically be unselected when navigating to a different verse.
@benjore - Should the unselect also happen when the user clicks any of the word map buttons, and/or a verse edit is performed? Other times?

**Actual behavior:** 
See above

### Context

**Enviorment**
| Tech         | Version |
|--------------|---------|
| tc           | v0.?.?  |
| build #      |         |
| OS           |         |

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by cckozie** [comment]
From Robert:
![Screenshot_20190523_102411](https://user-images.githubusercontent.com/8171759/58214264-b2616780-7cba-11e9-92e2-63acbd36ced4.png)


I haven't tried to repeat it but here's how I remember it happened: 1/ some alignment was done (including the ἐμαυτόν), 2/ I selected some words on the left in order to align them, 3/ I then decided to edit the verse, 4/ After editing some words were still selected (I vaguely remember that it looked a little strange), 5/ I dragged the already selected words across into ἁγιάζω and somehow "myself" got aligned again.

**Comment by mannycolon** [comment]
@cckozie @benjore Is this a dup of #5930?

**Comment by elsylambert** [comment]
Verified in 2.0.0 (8a6a8c5). Not seeing any issues. The Selected words in the word bank gets deselected when navigated to another verse or edit in Scripture pane.

**Comment by cckozie** [comment]
Yes, #5930 is actually a dup of this one. It should have just been closed.
