### ISSUE TITLE
update the langnames.json to the latest

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5187]
### User Story

As a user, I want tC to automatically pull in the latest language codes from tD so that my new language codes show up in tC as expected.

### Features / Specifications

- [ ] As part of the build process, update the langnames.json to the latest
- [ ] source/assets/languages/json
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by jag3773** [comment]
URL and info at https://api-info.readthedocs.io/en/latest/td.html .

**Comment by da1nerd** [comment]
@benjore is there a new language I can check for to see if this is working properly?

**Comment by PhotoNomad0** [comment]
@neutrinog - this was in review, but don't see a PR.

**Comment by da1nerd** [comment]
That's because it was just a concourse update.

**Comment by cckozie** [comment]
Test language code: kan-x-palligaru

**Comment by cckozie** [comment]
Works in 1.0.2 (f005f02)
