### ISSUE TITLE
tW tool card % complete calculation

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5191]
## Notes
- Make sure that #4416 is not causing problems. Make sure that the user sees 100% complete if all of the checks have been completed.

**Comment by cckozie** [comment]
1.1.0 (e6a76d9) 
I cannot fully test this until #5326 is fixed.
However, there is currently a significant problem in that after opening a mostly completed (97%) project in tW and then returning to the Tools page, the % complete now shows 0%.
[en_tit (2).zip](https://github.com/unfoldingWord-dev/translationCore/files/2641604/en_tit.2.zip)
Before opening in tW:
![image](https://user-images.githubusercontent.com/8171759/49406989-c6b9a400-f71c-11e8-9375-26d68f95bd83.png)

After opening in tW:
![image](https://user-images.githubusercontent.com/8171759/49407013-d638ed00-f71c-11e8-86e7-4e6d4ede9c5a.png)

**Comment by RoyalSix** [comment]
## Tasks
- [x] [3] Fix Bug In Initial Percent Calculation

**Comment by cckozie** [comment]
Fixed in 1.1.0 (4d06842)
