### ISSUE TITLE
tW tool loading the group menu based off of user selections on tool card

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5192]

**Comment by RoyalSix** [comment]
- [ ] [4] Load group data from FS based on selection

**Comment by cckozie** [comment]
1.1.0 (413b11c) 
Key terms: I see that in the UGNT kt data there is a separate group for both 'life' and 'live', but in the menu I see a single group for 'life, live, lived, lives, living, alive'. This group contains verses for only the Titus UGNT kt of 'life'. The verse and kt listed in the UGNT kt of 'live' does not appear anywhere in the menu. I've pinged Ben and Jesse about this.
