### ISSUE TITLE
RTL support in Scripture Pane

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5194]
![image](https://user-images.githubusercontent.com/13352518/46560131-309e0480-c8b8-11e8-8cf1-6f2dc5fbd4c7.png)

*Scripture Pane + Expanded Scripture Pane*
- [ ] RTL languages should have their whole "sub-pane" switched
  - [x] Top line: Language on the right, "ULT" on the left
  - [x] Second line (not in the mockup): "Original Language", "Gateway Language" or "Target Language" will show up under the top line, aligned right
  - [x] the `X` will be on the left side
  - [x] The scroll bar will appear on the left side (as needed)
  - [x] The reference will appear on the right side, but displayed LTR (not RTL), just like English!
  _Note: on other issue the reference will appear as `verse:chapter`_
  - [x] The text will appear RTL

**Comment by PhotoNomad0** [comment]
found another issue - verse editor:
![Screen Shot 2020-05-27 at 7.53.45 AM.png](https://images.zenhubusercontent.com/564e463c638e718c995eb353/8b742149-a7ec-4d0a-9871-2901e08079df)

**Comment by PhotoNomad0** [comment]
For SP I think this should be:
such as: 
![Screen Shot 2020-05-27 at 7 33 06 AM](https://user-images.githubusercontent.com/14238574/83014769-46ac8b80-9fed-11ea-9be2-0479cc0ffa52.png)

**Comment by PhotoNomad0** [comment]
@birchamp - Screenshot for review:
![Screen Shot 2020-05-27 at 10 39 22 AM](https://user-images.githubusercontent.com/14238574/83034571-669c7900-a006-11ea-81ac-d83d8404156f.png)

**Comment by PhotoNomad0** [comment]
@birchamp @cckozie @elsylambert  - Updated screenshot to reflect feedback from Alex that when reference is written in English it is shown in chapter:verse order.
![Screen Shot 2020-05-28 at 8 36 01 AM](https://user-images.githubusercontent.com/14238574/83142504-96a75300-a0be-11ea-985c-1181b491fbd1.png)

**Comment by PhotoNomad0** [comment]
And:
![Screen Shot 2020-05-28 at 8 41 28 AM](https://user-images.githubusercontent.com/14238574/83142858-133a3180-a0bf-11ea-9bf6-47354040004e.png)

**Comment by PhotoNomad0** [comment]
Verified in translationCore 3.0.0 (a74a650)

**Comment by cckozie** [comment]
From the first comment:
![image](https://user-images.githubusercontent.com/13352518/46560131-309e0480-c8b8-11e8-8cf1-6f2dc5fbd4c7.png)

*Scripture Pane + Expanded Scripture Pane*
- [ ] RTL languages should have their whole "sub-pane" switched
  - [x] Top line: Language on the right, "ULT" on the left
  - [x] Second line (not in the mockup): "Original Language", "Gateway Language" or "Target Language" will show up under the top line, aligned right (from Koz - I assume he means aligned according the the top line)
  - [x] the `X` will be on the left side
  - [x] The scroll bar will appear on the left side (as needed)
  - [x] The reference will appear on the right side, but displayed LTR (not RTL), just like English!
  _Note: on other issue the reference will appear as `verse:chapter`_
  - [x] The text will appear RTL

All look good in 3.0.0 (5b5cbbc) 
![image](https://user-images.githubusercontent.com/8171759/83795793-a1855900-a665-11ea-98c8-91cbf753c9d0.png)

**Comment by elsylambert** [comment]
@cckozie I am not seeing this change in 3.0.0 (cbed56b) with Philemon(Ar) project. Can you please attach an OT project to test?
- X is left aligned.
<img width="928" alt="Screen Shot 2020-06-07 at 4 05 56 PM" src="https://user-images.githubusercontent.com/51806180/83978940-dc42f780-a8d8-11ea-88de-17855233bf09.png">

**Comment by cckozie** [comment]
@elsylambert - Looks like they broke it in between the builds we tested. Go ahead and fail it.
![image](https://user-images.githubusercontent.com/8171759/83980194-5a070300-a8d9-11ea-8da1-47f9271bc6fc.png)

**Comment by elsylambert** [comment]
Not seeing this changes in 3.0.0 (cbed56b).

**Comment by PhotoNomad0** [comment]
@elsylambert Yes it looks like it was broken in a subsequent PR.

**Comment by PhotoNomad0** [comment]
@elsylambert Fixed in translationCore 3.0.0 (dad3c32) @cckozie

**Comment by elsylambert** [comment]
<img width="1212" alt="Screen Shot 2020-06-08 at 11 19 50 AM" src="https://user-images.githubusercontent.com/51806180/84049751-ce45b300-a97a-11ea-89fd-07c348b543ab.png">
@PhotoNomad0

**Comment by elsylambert** [comment]
Looks good in 3.0.0 (dad3c32). There are some inconsistencies in displaying the Target language in scripture pane, written up in #6981 .
