### ISSUE TITLE
RTL support in Side Menu

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5195]
![image](https://user-images.githubusercontent.com/13352518/46561172-1e25ca00-c8bc-11e8-9885-22cb5847c7e4.png)

*Side Menu*
The side menu is displaying mostly correctly (the book name is on the right, the reference is to the left (but aligned LTR - `[book]:[verse]`) and the selection is on the left of that. 
- [ ] Align the text to the right of the side menu (leave the icons on the left)
Note: left-right scrolling is an issue that will be dealt with elsewhere.

**Comment by PhotoNomad0** [comment]
@birchamp @cckozie - On this one it looks like the screenshot is incorrect - the reference should be to the right of the book name.

**Comment by birchamp** [comment]
No the ref shouldn't be to the right of the book name.  The problem that Ben points out is the order of the chapter and verse should be reversed.  I'll confirm with Alex, but what Ben is saying above is that it should read:
`[verse text] [verse number]:[chapter number] [Book]`

**Comment by birchamp** [comment]
@PhotoNomad0 I confirmed with Alex. Yes. 
~~`[verse text] [verse number]:[chapter number] [Book]`~~

**Comment by birchamp** [comment]
@PhotoNomad0 Per Donny Duvall - "don't think I've actually seen it all written out on one line like that before.  What you have is consistent with what I would expect."

**Comment by PhotoNomad0** [comment]
Verified in translationCore 3.0.0 (a74a650)

**Comment by elsylambert** [comment]
3.0.0 (0f8fc18). 

<img width="553" alt="Screen Shot 2020-06-03 at 11 41 14 PM" src="https://user-images.githubusercontent.com/51806180/83712423-bde8ad80-a5f3-11ea-8433-38793ca208c4.png">
Side Menu shows up as [verse text] [chapter number]:[verse number] [Book].
as oppose to 

> @PhotoNomad0 I confirmed with Alex. Yes.
> `[verse text] [verse number]:[chapter number] [Book]`

@birchamp @cckozie Just a confirmation, We discussed that if written in English Numerals, the order should be  [chapter number]:[verse number] [Book].

**Comment by birchamp** [comment]
@elsylambert @cckozie Sorry about that.  Yes, you're correct. 
[chapter number]:[verse number] [Book].

**Comment by cckozie** [comment]
Looks correct in 3.0.0 (5b5cbbc)

**Comment by elsylambert** [comment]
Side Menu looks good in 3.0.0 (cbed56b).
