### ISSUE TITLE
RTL support in Check Info Card

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5196]
![image](https://user-images.githubusercontent.com/13352518/46560996-57116f00-c8bb-11e8-929b-4c4179eab3aa.png)

*Check Info Card*
- [ ] For all the different modes (Select, Edit, Comment, Regular)
  - [ ] Align title & subtitle to the right
  - [ ] Move the "expand" button to the left

**Comment by PhotoNomad0** [comment]
@birchamp @cckozie - ~On this one it looks like the screenshot is incorrect - the reference should be to the right of the book name.~ screenshot is correct.

**Comment by PhotoNomad0** [comment]
Note - items needed to fix
![Screen Shot 2020-05-31 at 7 00 08 AM copy](https://user-images.githubusercontent.com/14238574/83350828-eaa77700-a30c-11ea-8bd2-721026e47087.png)

**Comment by PhotoNomad0** [comment]
@cckozie @elsylambert - on the screenshot above the `has been translated as: "...` should not be circled - it is correct.  Hard for me to interpret right to left.

**Comment by PhotoNomad0** [comment]
Note: interesting on the group menu that ellipsis is showing up on the right when text overflows.

**Comment by PhotoNomad0** [comment]
Verified in translationCore 3.0.0 (cab30f7)

**Comment by cckozie** [comment]
*Check Info Card*
- [ ] For all the different modes (Select, Edit, Comment, Regular)
  - [x] Align title & subtitle to the right
  - [x] Move the "expand" button to the left

Looks good in 3.0.0 (5b5cbbc)

**Comment by elsylambert** [comment]
3.0.0 (cbed56b).
Not seeing the expand button in tN and tW.
<img width="1212" alt="Screen Shot 2020-06-07 at 4 16 34 PM" src="https://user-images.githubusercontent.com/51806180/83979164-532cc000-a8da-11ea-950b-b36fc7c57b0f.png">

Expand button appears only when there is arabic text in the "Please select translation for" pane
<img width="1212" alt="Screen Shot 2020-06-07 at 4 20 51 PM" src="https://user-images.githubusercontent.com/51806180/83979318-7dcb4880-a8db-11ea-851e-f015c085d7c7.png">

**Comment by PhotoNomad0** [comment]
@birchamp @elsylambert - Is this a new requirement?

**Comment by elsylambert** [comment]
The issue related to Expand button will be addressed by #6943

**Comment by elsylambert** [comment]
Looks good in 3.0.0 (dad3c32).
