### ISSUE TITLE
RTL support for target languages in Word Alignment Tool (wA)

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5197]
![image](https://user-images.githubusercontent.com/13352518/46560632-11a07200-c8ba-11e8-9e9e-26820d904d76.png)

![image](https://user-images.githubusercontent.com/13352518/46560888-f2eeab00-c8ba-11e8-8698-d03e2154819d.png)

*wA Tool* 
- [ ] wA: The RTL target languages need to be right-aligned in the word box. 
- [ ] wA: The blue bar should be on the right of a word box if it is RTL
- [ ] wA: As multiple RTL words are added to the same Greek word, they need to order themselves from RTL in alignment box. 

## Notes
- Hebrew (Original Language) RTL support is covered by #3655

**Comment by da1nerd** [comment]
The word list and alignments parts are completed by https://github.com/translationCoreApps/wordAlignment/pull/104.

**Comment by PhotoNomad0** [comment]
@birchamp @cckozie @neutrinog - In the latest build it looks like none of these items are saved out correctly.
![Screen Shot 2020-05-21 at 7 49 02 AM copy](https://user-images.githubusercontent.com/14238574/82556612-1cb02080-9b38-11ea-82bb-7b502e4206ee.png)

**Comment by PhotoNomad0** [comment]
Also for OT:
![Screen Shot 2020-05-21 at 7 55 44 AM](https://user-images.githubusercontent.com/14238574/82556845-8af4e300-9b38-11ea-81b3-145d9b69170e.png)

**Comment by cckozie** [comment]
This was better in 2.1.2
<img width="853" alt="rtl1" src="https://user-images.githubusercontent.com/8171759/82560155-7fa0b800-9b36-11ea-974d-06e220e9c600.png">
I'm actually seeing the same thing in the latest 2.2.0 (b749003)
![image](https://user-images.githubusercontent.com/8171759/82561692-69e0c200-9b39-11ea-9dd1-e02fae6530fe.png)

**Comment by PhotoNomad0** [comment]
@cckozie @elsylambert - could you try this project? 
[58-PHM_ar.usfm.zip](https://github.com/unfoldingWord/translationCore/files/4662739/58-PHM_ar.usfm.zip)

**Comment by PhotoNomad0** [comment]
@cckozie @elsylambert - I am seeing the same thing on my windows machine with the above project.  USFM import issue?

**Comment by cckozie** [comment]
@PhotoNomad0 - I'm seeing the same as you with that project. Even tried reimporting designating LTR on the details page and that, of course, makes it wrong in the scripture pane too. Very strange!

**Comment by PhotoNomad0** [comment]
Note:

I found that the WA tool is reading the language direction settings from `./phm/manifest.json`, but when you edit the project the changes are saved to `./manifest.json`. 

looks like the fix would be in loadTargetLanguageBook() - currently the settings from`./manifest.json` override the other manifest's language name and code, but not direction.

**Comment by PhotoNomad0** [comment]
Verified in translationCore 3.0.0 (a444d5f)

**Comment by PhotoNomad0** [comment]
found another issue - verse editor:
![Screen Shot 2020-05-27 at 7.53.45 AM.png](https://images.zenhubusercontent.com/564e463c638e718c995eb353/8b742149-a7ec-4d0a-9871-2901e08079df)

**Comment by PhotoNomad0** [comment]
@cckozie @elsylambert ^^^

**Comment by PhotoNomad0** [comment]
Since this is the same verse editor as used in Enhanced SP, will fix it as part of 5194.

**Comment by elsylambert** [comment]
wA:Comments Box should write from Right to left

**Comment by elsylambert** [comment]
<img width="1221" alt="Screen Shot 2020-06-01 at 3 45 50 PM" src="https://user-images.githubusercontent.com/51806180/83447843-08fd9780-a41f-11ea-8545-9f76d50f10d0.png">
Looks good in 3.0.0 (c8646fa). Individual components like side menu bar and verse edits are covered in separate issues.

**Comment by cckozie** [comment]
3.0.0 (c8646fa)
@birchamp - 1) What should be the result in the scenario where the project is in an LTR language and the user selects the LTR option and the font for an RTL language? Do we even care?
2) Is the correct title for the field "Language Font" or just "Font"? 
Current implementation shows this: (the truncation of the words in the word bank is written up in #6957)
![image](https://user-images.githubusercontent.com/8171759/83547464-dcea2100-a4c7-11ea-8082-1f912f894b6c.png)
<img width="1191" alt="french arabic" src="https://user-images.githubusercontent.com/8171759/83547529-ff7c3a00-a4c7-11ea-9373-2e6b0059f769.png">
![image](https://user-images.githubusercontent.com/8171759/83548289-29822c00-a4c9-11ea-9cbe-790c782c762b.png)

**Comment by birchamp** [comment]
@cckozie 
1. We'll leave that up to the users. 
2. Good call.  Font makes more sense.  

That last screen shot seems pretty odd.  Maybe @PhotoNomad0 can tell us what's going on there.

**Comment by cckozie** [comment]
From first comment:
- [x] wA: The RTL target languages need to be right-aligned in the word box. 
- [x] wA: The blue bar should be on the right of a word box if it is RTL
- [x] wA: As multiple RTL words are added to the same Greek word, they need to order themselves from RTL in alignment box. 
These requirements were all met in 3.0.0 (5b5cbbc)
