### ISSUE TITLE
Text selection is missing in verse check

### ISSUE THREAD

**Issue by da1nerd** [unfoldingWord/translationCore#5199]
### Prerequisites

* Put an X between the brackets on this line if you have done all of the following:

- [x] I have searched the [issues](https://github.com/unfoldingWord-dev/translationCore/issues) of this repository and believe that this is not a duplicate.

### Description

After making a selection in tW the text preceding the selection is missing. If I de-select the text it re-appears.

I've reproduced this issue on Linux and macOS.

### Steps to Reproduce

1. Open this project [en_test_tit_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/2462354/en_test_tit_book.zip)
2. Open tW
3. make a selection
4. Save the selection and notice the selected text disappears.

**Screenshots**

The text before selection
![image](https://user-images.githubusercontent.com/166412/46700859-d01e0880-cbd2-11e8-9e3e-6114b8bfb739.png)

The text after selection
![image](https://user-images.githubusercontent.com/166412/46700827-bc72a200-cbd2-11e8-890e-045f03a08d44.png)

### Context

**Envionment**

| Tech    | Version   |
|---------|-----------|
| tC      | v1.0.2    |
| build # | 6ab77c069 |
| OS      | Ubuntu    |

### Additional Information

You can test this against the appropriate build at http://tc-builds.door43.org/build/release-v1.0.2/

**Comment by cckozie** [comment]
Works correctly in 1.1.3 (240da43)
