### ISSUE TITLE
Need indication of waiting after selecting multiple words to be dragged in wA

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5201]
- [ ] Option 1: Remove the delay so that it is immediately draggable (Much more preferable)
- [x] Option 2: Change the cursor to a spinner. 

### Description
After the user has selected multiple words in the word bank to be dragged, there is a delay before they can be actually be dragged. There should be some visible indication that the computer is processing during that time so that the user does not get frustrated trying to drag the words before that movement is allowed.

### Steps to Reproduce

1. Open a project in wA
2. Click on several words in the word bank
3. Immediately after clicking the final word attempt to drag the words to a target
4. Notice that the words were not dragged

**Screenshots**

**Expected behavior:** 
The user would expect that either the words would be immediately available to be dragged, or that there would be a visual indication that something is delaying the ability to drag them.

**Actual behavior:** 
See above

### Context
This frustrates me everytime I try to do a multi-word drag and I have to attempt it multiple times

**Enviorment**
| Tech         | Version |
|--------------|---------|
| tc           | v0.?.?  |
| build #      |         |
| OS           |         |

### Additional Information
MacbookAir i7, 1.6Ghz, 8G, 128 G  SSD

**Comment by benjore** [comment]
- [ ] Look to improve performance (to eliminate need for spinner)
- [ ] Add a spinner.

**Comment by richmahn** [comment]
Seems it wasn't a delay in rendering as it clearly renders to a blue button even when you try to drag and can't. For some reason there is no delay if you start to drag an unselected word (when other buttons are selected) and it becomes blue, the event continues to go smoothly. Yet seems like when you click a word, the event listener get removed and then added again to all the items, causing the delay. This can even be see in this demo of selecting multiple images with the same versions of React and React DnD: https://codesandbox.io/s/react-multiple-dnd-untyz

So option 1 was a no go. Option 2 was possible to make a spinning mouse cursor and then have it go away in 1 second from clicking. There is no way to know (no callback) when the event listener is ready that I could find, so just a timed function call was all that was possible.

**Comment by mannycolon** [comment]
Verified on 2d82863

**Comment by cckozie** [comment]
2.0.0 (3727b58) 
A spinner is now displayed when any word in the word bank is clicked, and the words can be dragged when the spinner stops.
This is less than an ideal solution since the spinner is displayed after every click on a word in the word bank indicating that the app is busy and user input will be ignored. That is really not the case since the user can select words in the word bank without any delay between them even though the spinner is spinning. The busy only needs to be indicated when the user attempts to drag the multiselected words.

**Comment by elsylambert** [comment]
2.0.0 (aa663e3). Able to drag multiple words after the spinner stops. Spinner is shown on every single word selection from the word bank. Unselected words are immediately draggable.
