### ISSUE TITLE
Publish UHB to Catalog

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5202]
### User Story

As a [type of user], I want [some goal] so that [some reason].

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by jag3773** [comment]
Resource is available in the catalog (see https://git.door43.org/Door43-Catalog/hbo_uhb).  The subject is listed as `Hebrew Old Testament`, which is the subject endpoint that tC should look to.

**Comment by jag3773** [comment]
Available at https://api.door43.org/v3/subjects/Hebrew_Old_Testament.json .
