### ISSUE TITLE
Make updating `langnames.json` part of the build process

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5206]
### User Story

As a user, I want each tC build to have the latest list of language codes so that I don't have to wonder why my language isn't showing up.

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by benjore** [comment]
@neutrinog have you already done this?

**Comment by da1nerd** [comment]
yes

**Comment by benjore** [comment]
@cckozie This is the language code that caused this issue to be created `kan-x-palligaru`
