### ISSUE TITLE
Hindi IRV has tokenization issues

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5214]
The Hindi ULB and UDB are correct for Titus 1:1. The IRV has the word for God split into two words.
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/e1299192-6b3b-417b-92ce-25d5266da5d1)

**Comment by PhotoNomad0** [comment]
@benjore  @cckozie - looks like word split is in our resources and in the catalog.  It looks like IRV needs to be re-exported to the catalog with the latest tCore release.  Then we can update it in tCore

**Comment by elsylambert** [comment]
Retested on 2.0.0 (ca6c273). Not seeing this issue.
