### ISSUE TITLE
Missing text in the scripture pane

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5228]
1.0.1 (50bc39b) 
There are words missing from the scripture pane that do exist in the resources folder.
As first observed in wA after adding the UST and ULB to the scripture pane:
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/532a5e24-ecdf-4a1d-b147-293e94f40b58)

I downloaded the latest English resources and did not see any change. 

I then switched over to tW and saw this problem as well, although I have not been able to recreate it.
![image](https://user-images.githubusercontent.com/8171759/46968868-0992c000-d07a-11e8-8c80-2e3aab6e0718.png)

**Comment by mannycolon** [comment]
@cckozie Here it is

**Comment by cckozie** [comment]
1.0.1 (9872178)
The case shown above is now fixed, but here is another failure case:
![image](https://user-images.githubusercontent.com/8171759/47040288-86419f00-d14b-11e8-80a5-4224f57fd9a2.png)

![image](https://user-images.githubusercontent.com/8171759/47040418-d3be0c00-d14b-11e8-8924-8b894452c781.png)

**Comment by mannycolon** [comment]
@cckozie Here it is again when you get a chance.

**Comment by cckozie** [comment]
Works in 1.0.2 (a5a105b)
