### ISSUE TITLE
USFM3 exports rename projects to the ULB

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5233]
## To Recreate bug 

1. Import an English project (e.g. download this file to PC and do local import: https://git.door43.org/unfoldingWord/en_ust/src/branch/master/62-2PE.usfm). 
2. Nickname it as `UST`. 
3. Do some alignments. 
4. Export the project as USFM3. 
5. Note that in the beginning/header info, it is labeled as `EN_ULT`

## Note
- Larry and @richmahn found this issue. I have not done extensive testing on it, but was able to recreate it first try.

**Comment by bspidel** [comment]
![62-2pe](https://user-images.githubusercontent.com/4968713/47060207-b06e7d80-d19a-11e8-8129-9a61d436d114.PNG)

When I imported the referenced project on x64 Win10 tC v1.0.2 (cab77c0) I received the attached alert.

**Comment by PhotoNomad0** [comment]
@bspidel - I think you tried to do an online import here.  It is subtle, but @benjore is actually downloading the file and then doing a local USFM import.

**Comment by PhotoNomad0** [comment]
Verified in https://tc-builds.door43.org/build/release-v1.0.2/translationCore-win-x64-1.0.2-3943b93.setup.exe

**Comment by cckozie** [comment]
I assume Ben meant give it a transaction id of UST, not nickname.
Works in 1.0.2 (5ebb84f)
