### ISSUE TITLE
Optimize Initial loading of tC

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5234]
### User Story

As a [type of user], I want [some goal] so that [some reason].

### Features / Specifications

- [ ] NOT referring to the first-time startup
- [ ] Create Spike as task
- [ ]

### Definition of Done

- [ ] Target = 7 seconds
- [ ]
- [ ]

**Comment by mannycolon** [comment]
I was able to reduce the startup time from **~1m 08s - 1m 32s** to **~9s - 15s**

**Comment by cckozie** [comment]
1.1.0 (c6414a7)
On my Mac:
Opening on clean install: 63 seconds
 Subsequent to initial install: 6 seconds

Previous build 1.1.0 (5b1d1cc):
Opening on clean install: 1:16 seconds
Subsequent to initial install: 20 seconds
