### ISSUE TITLE
Expanded Scripture Pane Dialog is not updating displayed text after edit.

### ISSUE THREAD

**Issue by da1nerd** [unfoldingWord/translationCore#5236]
### Prerequisites

* Put an X between the brackets on this line if you have done all of the following:

- [x] I have searched the [issues](https://github.com/unfoldingWord-dev/translationCore/issues) of this repository and believe that this is not a duplicate.

### Description

When editing a verse using the scripture pane the dialog is not reflecting the edits until you close the dialog entirely. See gif below.

### Steps to Reproduce

1. Go to a tool
2. Click on expansion icon that opens the scripture pane dialog
3. Edit a verse

**Screenshots**

![bug](https://user-images.githubusercontent.com/166412/47038189-b120f880-d135-11e8-8547-2379da2a1b88.gif)

**Expected behavior:** The dialog should display the changes.

**Actual behavior:** The dialog is display the old text.

### Context

**Enviorment**
| Tech         | Version |
|--------------|---------|
| tc           | v1.0.2  |
| build #      |         |
| OS           |   linux      |

**Comment by elsylambert** [comment]
Retested in 2.0.0 (4b3ebee). Not seeing this issue.
