### ISSUE TITLE
wordAlignment tool shows broken alignments after import of USFM2 project

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#5244]
### User Story

As a Checker, I want wordAlignment to not show broken alignments when I open a new project that has no existing alignments.

## Additional Context

To reproduce import the following project and then open WA:

 [https://app.zenhub.com/files/65028237/ba2d4332-ebb8-44bc-ab59-b425c1c401cd/download](https://app.zenhub.com/files/65028237/ba2d4332-ebb8-44bc-ab59-b425c1c401cd/download)

**Comment by benjore** [comment]
Could not reproduce

**Comment by cckozie** [comment]
No longer a problem in 1.2.0 (b485978)
