### ISSUE TITLE
Add option to not show warning again to "Invalidated" warning

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5259]
### User Story

As an aligner who invalidates hundreds of verses per day, I want to be able to shut off the "invalidated" warning so that I don't get premature carpal tunnel.

### Features / Specifications

- [ ] This setting should be persisted like the Internet Access warning - If the user changes, it resets. If the app is opened, it resets. 
- [ ]
- [ ]

### Definition of Done

- [ ] 
- [ ]
- [ ]

### Mockups
![image.png](https://images.zenhubusercontent.com/55e5f3984f7a08fbb7f4a658/a47b8a0d-d6ad-4a62-a614-328e783e8ce8)

**Comment by PhotoNomad0** [comment]
Checked with Tested with https://tc-builds.door43.org/build/release-v1.0.2/translationCore-win-x64-1.0.2-0159185.setup.exe

**Comment by cckozie** [comment]
Works in 1.0.2 (5ebb84f)
