### ISSUE TITLE
WordMAP: Add Lemma Fallback

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5267]
### User Story

As a [type of user], I want [some goal] so that [some reason].

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by da1nerd** [comment]
There are two implementations of adding lemma to wordMAP

* alignment memory will be indexed on both the word and the lemma. Then when calculating confidence we can determine if a prediction matches alignment memory by reading the index for the word an lemma keys.
* then the statistical algorithms could be extended to use lemma by basically copy-pasting all the algorithms and changing the index lookup key to the lemma. With that we'd have double the algorithms with slightly different weighting when calculating the final confidence.

**Comment by cckozie** [comment]
Can't test until #5543 is fixed.

**Comment by cckozie** [comment]
Appears to work in 1.1.0 (4d06842) . Only did spot testing of a few cases.
