### ISSUE TITLE
Having loaded 7 projects from door43, all include tc_version: 6 in manifest.

### ISSUE THREAD

**Issue by bspidel** [unfoldingWord/translationCore#5275]
### Prerequisites

* Put an X between the brackets on this line if you have done all of the following:

- [x] I have searched the [issues](https://github.com/unfoldingWord-dev/translationCore/issues) of this repository and believe that this is not a duplicate.

### Description

When a project is imported, it is supposed to be migrated. Part of that should be marking the checking tool used to update the project. Current bug is that tc_version is not updated. 

### Steps to Reproduce

1. Download usfm file like: TBD
2. Import as local file
3. Check manifest

Note tc_version: 6. Should be 1.0.2

**Screenshots**

**Expected behavior:** tc_version: 1.0.2

**Actual behavior:** tc_version: 6

### Context

**Enviorment**
| Tech         | Version |
|--------------|---------|
| tc           | v1.0.2  |
| build #      | 6ab77c0 |
| OS           |    x64 Win10     |

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by PhotoNomad0** [comment]
@bspidel - I think this is expected behavior.  When we do migration, the manifest version will be updated the match the manifest version in package.json (e.g.   "manifestVersion": "7").

**Comment by cckozie** [comment]
This is not a bug. It is operating as expected. The tc_version in the manifest file refers to the manifest version and not the actual version of tC.
