### ISSUE TITLE
Performance regression in wA

### ISSUE THREAD

**Issue by da1nerd** [unfoldingWord/translationCore#5277]
### Prerequisites

* Put an X between the brackets on this line if you have done all of the following:

- [x] I have searched the [issues](https://github.com/unfoldingWord-dev/translationCore/issues) of this repository and believe that this is not a duplicate.

### Description

A performance regression was introduced to wA recently.
The effect is loading a project in wA takes a very long time when the project is loaded for the first time e.g. the project had no `.apps` dir.

### Steps to Reproduce

1. Delete the `.apps` dir for a project
2. open it in wA
3. Wait for a very very long time.

### Context

**Enviorment**
| Tech         | Version |
|--------------|---------|
| tc           | v1.0.2  |
| build #      |         |
| OS           |    linux     |

**Comment by cckozie** [comment]
Works in 1.0.2 (f005f02)
