### ISSUE TITLE
Add the "Glossary" panel to the left side of the available tools screen

### ISSUE THREAD

**Issue by EllDoubleYew** [unfoldingWord/translationCore#528]
This will allow users to search through their tools and render a list of the tools available

**Comment by mannycolon** [comment]
<img width="334" alt="screen shot 2017-01-25 at 2 56 54 pm" src="https://cloud.githubusercontent.com/assets/17072300/22306804/a742ad70-e30e-11e6-9e65-b5aa2c7e9858.png">

**Comment by ihoegen** [comment]
@klappy, @mannycolon and I have decided to Veto this for now
