### ISSUE TITLE
1.0.1 Appears to lose text in the Check pane

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5286]
1.0.1 (4ad2f22)
This has been broken post 1.0.0
[57-TIT.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/2496271/57-TIT.usfm.zip)

1. Import this project and load it in tW
2. Go to verse 3:1 under authority
3. Double click individually on 'and' and 'authorities' 
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/38b87bfb-7ced-48e6-8de1-93b3628c5cfc)
4. Click Save
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/e382bf72-836a-474b-b013-40a08027d812)

**Comment by mannycolon** [comment]
Verified on `macOS build 4ae68da (v1.0.1)`

**Comment by mannycolon** [comment]
@cckozie ^^

**Comment by cckozie** [comment]
Works in 1.0.2 (8c6f266)
