### ISSUE TITLE
App hangs in wA 

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5298]
1.0.0 (4bd6856)
This was reported by Larry. He was doing editing and aligning in Matthew. Per Larry, "I finished editing verse 7:11, and was waiting for it to let me go back to the alignment page. It hung waiting for the popup box telling me I had done edits and needed to realign. I waited about 30 seconds, and then closed tC. It hangs on me about every 12-15 verses when I am editing every verse of a large book (Mat). I end up closing it often."
![image](https://user-images.githubusercontent.com/8171759/47324280-c362d100-d624-11e8-9ddb-e5f51467e6aa.png)

I wrote a script to sequentially edit each verse in wA. It made it to verse 1 in chapter 6, then got into a mode where there was a long delay (more than 1 minute) from the time of a click to the app's response. This is what was in the console at that point:
![image](https://user-images.githubusercontent.com/8171759/47324421-513ebc00-d625-11e8-8c2b-0a5c6c706882.png)

I ran the test again. This time the script performed almost 400 edits before the app became pretty unresponsive. Here is a chart that shows how many seconds it took from clicking the Save button on an edit until the edit dialog was closed.
![image](https://user-images.githubusercontent.com/8171759/47329245-9371f880-d639-11e8-9a3c-41a4be739570.png)
During the unresponsive times one of the translationCore helper processes is consuming ~130% of the processor.

**Comment by cckozie** [comment]
Ran this scripted test on 1.0.2 (f005f02) tracking the time for screen changes
1. Load Matthew project in wA
2. Align verse 15:1
3. Open expanded scripture pane
4. Change one word in verse 5:1 (I substitute 'some' and 'several' prior to 'Pharisees')
5. Align the changed word
6. Repeat steps 3-5
![image](https://user-images.githubusercontent.com/8171759/47569658-cba75e80-d8f9-11e8-9fee-0d74d6011c07.png)

Timing definitions:
Save time = time from clicking Save on the edit dialog until when the dialog disappears
Reset time = time from edit dialog disappearing until the alignment reset alert appears
Vanish time = time from clicking OK on alert until alert disappers
Expand time = time from clicking expanded scripture pane icon until expanded scripture pane appears
1, Save time =   2.33, Reset time = 3.51, Vanish time = 2.00, Expand time = 3.97
2, Save time = 2.35, Reset time = 4.52,   Vanish time = 1.29, Expand time = 3.59
3, Save time = 2.35, Reset time = 3.50,   Vanish time = 2.00, Expand time = 3.68
4, Save time = 2.37, Reset time = 4.93,   Vanish time = 1.30, Expand time = 3.71
5, Save time = 2.34, Reset time = 2.93,   Vanish time = 1.99, Expand time = 4.24
6, Save time = 2.33, Reset time = 5.51,   Vanish time = 1.29, Expand time = 3.71
7, Save time = 2.44, Reset time = 5.20,   Vanish time = 1.29, Expand time = 4.47
8, Save time = 2.34, Reset time = 4.81,   Vanish time = 1.32, Expand time = 4.05
9, Save time = 2.35, Reset time = 3.17,   Vanish time = 2.01, Expand time = 4.25
10, Save time = 2.34, Reset time = 3.52,   Vanish time = 1.99, Expand time = 4.05
11, Save time = 2.32, Reset time = 4.84,   Vanish time = 1.30, Expand time = 4.63
12, Save time = 2.36, Reset time = 2.89,   Vanish time = 2.28, Expand time = 5.39
13, Save time = 2.35, Reset time = 4.84,   Vanish time = 1.27, Expand time = 3.75
14, Save time = 2.33, Reset time = 3.17,   Vanish time = 1.96, Expand time = 4.21
15, Save time = 2.35, Reset time = 4.81,   Vanish time = 1.27, Expand time = 5.92
16, Save time = 2.34, Reset time = 3.08,   Vanish time = 1.99, Expand time = 3.63
17, Save time = 3.54, Reset time = 5.26,   Vanish time = 1.28, Expand time = 4.67
18, Save time = 2.37, Reset time = 4.81,   Vanish time = 1.28, Expand time = 3.59
19, Save time = 2.33, Reset time = 4.84,   Vanish time = 1.27, Expand time = 4.09
20, Save time = 2.36, Reset time = 5.40,   Vanish time = 1.98, Expand time = 4.16
21, Save time = 2.35, Reset time = 6.44,   Vanish time = 2.00, Expand time = 3.99
22, Save time = 2.36, Reset time = 3.05,   Vanish time = 2.30, Expand time = 4.33
At this point it took more than 30 seconds to open the expanded scripture pane. There was nothing unusual in the console.
This is pretty repeatable on my Mac. It appears to always take 21 or 22 iterations of the script to get to a failure state.

**Comment by da1nerd** [comment]
[en_ult_mat_book_busted.zip](https://github.com/unfoldingWord-dev/translationCore/files/2507462/en_ult_mat_book_busted.zip)

**Comment by da1nerd** [comment]
@cckozie could you run your test script again but this time copy **everything** from the console and post it here in a file? I need a log of all the actions that are being performed so I can determine if there is a race condition.

**Comment by cckozie** [comment]
@neutrinog With the current build there is nothing other than the usual 'unexpected file found in target' and 'checker is not a function' messages in the console when the app slows to a standstill running either of the scripts.
I'd suggest the best route may be to manually go through the steps outlined in the second comment above. On my Mac it seems to alway take about 21 iterations to get to a failure mode.

**Comment by da1nerd** [comment]
I did but was unable to reproduce it.

**Comment by cckozie** [comment]
@neutrinog I just reproduced it first try doing all of the work manually instead of my script and again it took 22 iterations for the app to become unusable (30+ to respond to clicks).
This is something that needs to be fixed for 1.0.2, so if you are not able to fix it, please pass along whatever thoughts you have to someone else on the team that you think is most capable of taking it on.

**Comment by da1nerd** [comment]
@cckozie ok I've identified it as being a memory leak. Still hunting down the source. Could be anywhere at this point.
The application was consuming 10GB of memory on my system after repeated edits.

**Comment by da1nerd** [comment]
I have simplified the reproduction of this issue. Simply repeatedly opening and closing the expanded scripture pane will cause the application to freeze after about 20 iterations.

I've replicated this in both wA and tW. 

The top level function being called is `getBiblesWithHighlightedWords` inside `tc-ui-toolkit/src/ScripturePane/helpers/bibleHelpers.js`

**Comment by da1nerd** [comment]
Memory leak seems to be focused around the `verseArray` function.

**Comment by da1nerd** [comment]
I think I've narrowed it down to this.
For some reason jsx is not getting garbage collected when added to an array even when the array is thrown away.

e.g. 
```jsx
verseSpan.push(
        <span>
          hello world
        </span>
      );
```

if I generate an array of say 50 jsx objects and then throw it away I obviously consume a certain amount of memory.
If I then perform the above operation 10000 times I "should" use about the same amount of memory (depending on when GC is called) because in each loop the array is thrown away. But.... instead the memory keeps building up.

**Comment by PhotoNomad0** [comment]
@neutrinog - in other places we just store the text in an array, not the jsx.  Maybe we could make that change here?

**Comment by PhotoNomad0** [comment]
Also thinking adding the jsx in the array makes the array huge.

**Comment by PhotoNomad0** [comment]
@cckozie - tested with https://tc-builds.door43.org/build/release-v1.0.2/translationCore-win-x64-1.0.2-36c4430.setup.exe

Edited all of Mat 1, and didn't see any slowdowns.  But I'm sure you have better tests.

**Comment by cckozie** [comment]
1.0.2 (ac3d66a)
I'm not seeing any difference in this build.
With the project open and some alignments done, the highest memory usage of any of the translationCore helpers is 248MB. When the app appears to hang, it goes to 2.2GB.
Ignore the 'Reset time' in this list. It is 0 now that we have the check box to not show the invalidated alignments alert.
Note that the test process described to create the failure includes editing and aligning, not just editing.
1, Save time = 1.66, Reset time = 0.00, Vanish time = 1.39, Expand time = 3.62
2, Save time = 1.65, Reset time = 0.00, Vanish time = 1.32, Expand time = 3.98
3, Save time = 1.69, Reset time = 0.00, Vanish time = 1.35, Expand time = 3.39
4, Save time = 1.67, Reset time = 0.00, Vanish time = 1.38, Expand time = 3.47
5, Save time = 1.66, Reset time = 0.00, Vanish time = 1.32, Expand time = 3.43
6, Save time = 1.83, Reset time = 0.00, Vanish time = 1.32, Expand time = 3.44
7, Save time = 1.69, Reset time = 0.00, Vanish time = 1.30, Expand time = 5.19
8, Save time = 1.66, Reset time = 0.00, Vanish time = 1.29, Expand time = 3.37
9, Save time = 1.74, Reset time = 0.00, Vanish time = 1.34, Expand time = 3.36
10, Save time = 1.81, Reset time = 0.00, Vanish time = 1.31, Expand time = 3.63
11, Save time = 1.67, Reset time = 0.00, Vanish time = 1.28, Expand time = 6.30
12, Save time = 1.66, Reset time = 0.00, Vanish time = 1.33, Expand time = 3.27
13, Save time = 1.68, Reset time = 0.00, Vanish time = 1.28, Expand time = 3.33
14, Save time = 1.69, Reset time = 0.00, Vanish time = 1.29, Expand time = 5.54
15, Save time = 2.11, Reset time = 0.00, Vanish time = 1.31, Expand time = 3.25
16, Save time = 1.68, Reset time = 0.00, Vanish time = 1.28, Expand time = 6.17
17, Save time = 1.67, Reset time = 0.00, Vanish time = 1.36, Expand time = 3.53
18, Save time = 1.68, Reset time = 0.00, Vanish time = 1.70, Expand time = 3.22
19, Save time = 1.71, Reset time = 0.00, Vanish time = 1.30, Expand time = 3.29
20, Save time = 10.48, Reset time = 0.00, Vanish time = 48.84, Expand time = 20.71

**Comment by cckozie** [comment]
1.0.2 (eb69ffb)
Ran some additional tests to try to see if it could be isolated to the scripture pane.
TEST A:
Modified the script to use the select pane editor in tW instead of the expanded scripture pane in wA. Did not experience the performance issues.
TEST B:
Modified the script from A to use the expanded scripture pane in tW for editing. Did not experience the performance issues.
TESTC:
Went back to the original script doing the editing in wA, but added a delay of 10 seconds (about the time required to switch between tW and wA) in each iteration. Did experience the performance problem at exactly the same point as without the delay.

**Comment by cckozie** [comment]
Modified TEST A above to use a Matthew project. Did not experience the performance issue.
Modified TEST B above to use a Matthew project. The app did hang.
Pretty conclusive that the problem is in the expanded scripture pane.

**Comment by mannycolon** [comment]
Before my last fix, tC used to hang on me about every 12-15 verses when I am editing every verse of a large book (Mat). After my fix it now takes 55-60 verses

**Comment by cckozie** [comment]
My results running the test in the second comment above on build 1.0.2 (1681fcf) 
It appears that the actual memory consumption is still a problem, but I'm not seeing a significant slow down in using the app. It does occasionally 'stall' for a short time, but does seem to recover on it's own up until a point which is much later than it was in the past. I can now get about 100 iterations +- 10 before the app appears to freeze.

Process memory usage and time to complete edit and align operation. The test ended when the app took more than 30 seconds to respond to any interaction.
![image](https://user-images.githubusercontent.com/8171759/48368976-c7f63480-e67a-11e8-8999-faf63e5add4f.png)

**Comment by cckozie** [comment]
1.1.3 (2c25b41)
The system appears to recover pretty well from the high memory usage now. The highest consuming process consumption does grow to above 900MB on my machine, but it does manage to free up memory over time and get back down into the 400+MB range before growing more. 
Even with the growing memory consumption the performance did not appear to suffer. The test results for a full iteration of edit, save, realign remained in the 15-17 seconds range for the entire test of 100 iterations.
