### ISSUE TITLE
tW selections getting reset in error

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5306]
1.0.2 (a5a105b)

[53-1TH.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/2507365/53-1TH.usfm.zip)

1. Import this project and load it in tW
2. Click on the group for Christ, Messiah
3. On each verse in the group, double click on 'Christ', click Save, then click Save & Continue
('Christ' does not appear in 2:7 because the verse is incomplete in the project)
4. Navigate back to the Projects page
5. Navigate to the Tools page
6. Load the project with tW
Notice that the 'Some selections are no longer valid...' alert is displayed, and some of the verses in the Christ, Messiah group display the broken link icon and those selections have been cleared.

**Comment by benjore** [comment]
Could not reproduce

**Comment by cckozie** [comment]
No longer a problem in 1.2.0 (b485978)
