### ISSUE TITLE
Check mark is not persisted for saved selections when there are multiple instances of check in same verse

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5326]
1.0.2 (b84794c)
This has been broken post the 1.0.0 release

[en_test_rom_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/2515637/en_test_rom_book.zip)
1. Open the attached project in tW
2. Make selections for each of the verses under 'authority..' and click Save, then Save & Continue
3. Note that the check mark is displayed for each of the verses
4. Navigate back to the tools page
5. Load the project again with tW
Notice that the check mark for the first selection for Romans 13:1 is not being displayed and reclicking Save or Save & Continue does not set it.
![image](https://user-images.githubusercontent.com/8171759/47512708-5d539500-d842-11e8-8c0b-aa878062f4ad.png)

**Comment by PhotoNomad0** [comment]
Verified in https://tc-builds.door43.org/build/release-v1.1.1/translationCore-macos-x64-1.1.1-947818a.dmg

**Comment by cckozie** [comment]
Fixed in 1.1.1 (f6a4c6b)
