### ISSUE TITLE
Sometimes there is a missing chapter in WA tool

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#5332]
### User Story
Larry would like to align all his EN ULT Mat chapters, but Chapter 11 was missing in WA tool.
 
- it would be good to not lose chapters.  _This may have been fixed in 1.0.2 (issue to prevent writing alignment data until all alignment data was loaded)._
- should warn user when chapter cannot be loaded in WA.  

## Additional Context

Chapter 11 verses were present, and alignment data was present.
It turned out that there was an empty WA index file (⁩`⁨.apps⁩ ▸ ⁨translationCore⁩ ▸ ⁨index⁩ ▸ ⁨wordAlignment⁩ ▸ ⁨mat⁩ ▸  chapter_11.json`).  tCore logged an error in console when trying to load as a json file.  This index file does not contain critical information, only flags that verse has been edited.  But it needs to be valid for WA to display the chapter.

**problem project:** https://git.door43.org/tCore-test-data/en_ult_mat_book

## Work around

- imported a USFM2 mat project and opened in WA tool which generated a fresh chapter_11.json index file that was copied into his project.  Just losing any flags that verse was edited.

## Specs
- [ ] warn the user if something can't be loaded
- [ ] identify and fix what is causing the problem

NEED: exact text for the warning.

**Comment by elsylambert** [comment]
Retested in 2.0.0 (4b3ebee). With the attached project, I am seeing chapter 11 in wA tool.
