### ISSUE TITLE
translationWords selections are not being saved to index files in v1.0.2

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#5335]
## Story Explanation

this is blocking https://github.com/unfoldingWord-dev/translationCore/issues/4416

### Fails
 - [ ] progress on tW tool card no longer works - it reads selection status in tW index files and selection status is not being updated in the index files anymore.

## Additional Context

- this worked in v1.0.0 - maybe was broken during optimization?
- seems to be issue in saveState() that selections in prevState are updated to newState before saveState is called.  Looks like we are modifying the state object for contextId rather than making a clone.

**Comment by PhotoNomad0** [comment]
@cckozie - verified in build https://tc-builds.door43.org/build/release-v1.0.2/translationCore-win-x64-1.0.2-5ebb84f.setup.exe

For testing, you will have to open tw first before index files get updated from checkdata.  After that you should see progress on tw tool card for any selections that were made.

**Comment by cckozie** [comment]
Works in 1.0.2 (5ebb84f)
