### ISSUE TITLE
Fix progress bar in word Alignment where "Alignment Complete" is used. 

### ISSUE THREAD

**Issue by bspidel** [unfoldingWord/translationCore#5339]
### Prerequisites

* Put an X between the brackets on this line if you have done all of the following:

- [x] I have searched the [issues](https://github.com/unfoldingWord-dev/translationCore/issues) of this repository and believe that this is not a duplicate.

### Description

Word alignment progress indicator does not take "Alignment Complete" toggles into account.

### Steps to Reproduce

1. Import Jude project
2. Launch Word Alignment
2. Set all verses to Alignment Complete
3. Note Progress bar does not move
4. Actually align a verse
5. Note Progress bar moves

**Screenshots**

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

### Context

**Enviorment**
| Tech         | Version |
|--------------|---------|
| tc           | v1.0.2  |
| build #      | develop        |
| OS           |  x64 Win10       |

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by cckozie** [comment]
Not a problem in 1.2.0 (b485978)
