### ISSUE TITLE
[0] SPIKE: optimize initial tC loading

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5344]
### User Story

As a [type of user], I want [some goal] so that [some reason].

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by benjore** [comment]
#5234 is the story

**Comment by mannycolon** [comment]
On my Mac it takes tC 1 min 34s to start up

**Comment by mannycolon** [comment]
https://www.reddit.com/r/electronjs/comments/7fy05o/speed_up_electron_start_up/
https://blog.atom.io/2017/04/18/improving-startup-time.html
https://gist.github.com/paulcbetts/da85dd246db944c32427d72026192b41
