### ISSUE TITLE
Cannot persist selection for God in TW Mat 15:6

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#5351]
### User Story

As a checker, I want to be able to save all my selections and have them persist.  But Mat 15:6 gets invalidated when I re-enter tW.

## Additional Context

To reproduce:
- load project `https://git.door43.org/lrsallee/en_ult_mat_book`
- open tW and select `God` and make selection for Mat 15:6 and click `save` and `save continue`
- exit tW and select a different project
- then select the en_ult project again and open TW.  Then will get prompt that some selections are invalid.

![screen shot 2018-10-31 at 6 57 34 am](https://user-images.githubusercontent.com/14238574/47784150-231f4300-dcdb-11e8-8c17-98dbaac9d1c9.png)

Seems to be a problem with invalidation checker is choking on second instance of 'of God' in footnote:
![screen shot 2018-10-31 at 6 59 39 am](https://user-images.githubusercontent.com/14238574/47784037-d2a7e580-dcda-11e8-89b3-9334ddda5903.png)

**Comment by mannycolon** [comment]
Maybe caused by the unfiltered text being used in the selection process. Fixed may be as simple as using the filter target language string instead of the unfiltered text.

**Comment by richmahn** [comment]
- [ ] [4] Research why selections are not persisting
- [ ] [4] Implement fix
- [ ] [2] Tests for #5351
- [ ] [2] PR review #5351

**Comment by PhotoNomad0** [comment]
It looks like this is because the project also has "of God" in a footnote which is not being stripped out before checking.

**Comment by cckozie** [comment]
Works in 1.1.0 (ac75c11)
