### ISSUE TITLE
UGNT content change resulted in projects with invalid checks.

### ISSUE THREAD

**Issue by bspidel** [unfoldingWord/translationCore#5354]
### Prerequisites

* Put an X between the brackets on this line if you have done all of the following:

- [x] I have searched the [issues](https://github.com/unfoldingWord-dev/translationCore/issues) of this repository and believe that this is not a duplicate.

### Description

[In pursuit of #4416, it was discovered that while the progress bar can indicate 100%, some projects have a check that does not show up in menu but is counted when computing progress. At least one case of invalid keyword was found in UGNT which has not yet been resolved. 

This issue is for an update to project migration to rebuild indexes which might have an invalid keyword.

This issue is blocked by the next UGNT update.

In en_tit there are 2 words "live" and "life" which at one time were treated separately. Now they are one article.

### Steps to Reproduce

1. import project en_tit
2. Look at tW progress. Should indicate 99%

**Screenshots**

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

### Context

**Enviorment**
| Tech         | Version |
|--------------|---------|
| tc           | v0.?.?  |
| build #      |         |
| OS           |         |

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by cckozie** [comment]
Looking for this to be fixed by #4416
