### ISSUE TITLE
In some instances tC is incorrectly adding usfm closing tags, deleting opening tags, and deleting text

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5356]
1.0.2 (8af364e) 
--Imported text A:
\im The most important document in the history of the English language is the \bk King James   
Version\bk* of the Bible...
--Exported textA: (Notice extra \bk* tag)
\im The most important document in the history of the English language is the 
\bk King James Version\bk*
\bk* of the Bible..

--Imported text B:
\ili 1 \k The Messiah\k* is the one promised by God, the one who would come and free God's
--Exported text B: (Notice missing \k tag and 'The Messiah' text)
\ili 1 
\k*
is the one promised by God, the one who would come and free God's

Imported file: [usfm header testA.txt.zip](https://github.com/unfoldingWord-dev/translationCore/files/2536150/usfm.header.testA.txt.zip)

USFM2 exported file: [head_test.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/2536153/head_test.usfm.zip)

**Comment by PhotoNomad0** [comment]
@cckozie - good test cases that expose the limitations of our method of saving headers in simplified format with each tag on a new line.  Putting these into our unit tests.

**Comment by PhotoNomad0** [comment]
@cckozie - verified in https://tc-builds.door43.org/build/release-v1.0.2/translationCore-win-x64-1.0.2-ac3d66a.setup.exe

**Comment by cckozie** [comment]
Works in 1.0.2 (ac3d66a)
