### ISSUE TITLE
The text on the Greek popups in the scripture pane do not get updated when the locale is changed

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5361]
1.0.2 (f3e86ca) 

When the user has wA open and then changes the locale, the language is changed in the Greek popup in the alignment area, but not in the scripture pane. If the project is reopened in the tool, then the proper language appears in the popups in both places. 

![image](https://user-images.githubusercontent.com/8171759/47865130-6821a300-ddc9-11e8-9f9b-c55bb68bd459.png)

![image](https://user-images.githubusercontent.com/8171759/47865238-aae37b00-ddc9-11e8-919c-c19a3fadcbe3.png)

**Comment by elsylambert** [comment]
Retested on 2.0.0 (ca6c273). Not seeing this issue.
