### ISSUE TITLE
% complete on word alignment card always shows 0%

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5370]
1.0.2 (36c4430) 
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/6fef17c2-8374-44e5-b767-65b7cd8079ac)

![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/af01cc71-b754-435e-8e15-f6a95ddbbf7c)

**Comment by RoyalSix** [comment]
@cckozie I found there is an issue with counting "Alignment complete" toggled checks. 
Do you know if these checks were completed by the toggle or they actually have the word list and every Greek word aligned?

**Comment by cckozie** [comment]
@RoyalSix As I mentioned on the tread about this in the channel, the % complete on the tool card is not related to the alignment complete switch or the check marks. It is the number of words in the book that are aligned compared to the total number of words in the book. (The number of words is the count of both target language and Greek words)

**Comment by RoyalSix** [comment]
@cckozie Ok. So theoretically if I went through and didn't align a single word but switched all the toggles to complete, then I should have 0% complete in the tool card?

**Comment by cckozie** [comment]
@RoyalSix Yes, that is correct. Weird, but correct:)

**Comment by PhotoNomad0** [comment]
@cckozie - testing with https://tc-builds.door43.org/build/release-v1.0.2/translationCore-win-x64-1.0.2-ac3d66a.setup.exe  on windows.

It has about 12 projects with some alignments, and all of those seem to be showing about the right progress on the wa toolcard.  Can you send me a broken project or information to reproduce?

**Comment by PhotoNomad0** [comment]
Oops, posted wrong number above, fixing.

**Comment by cckozie** [comment]
@PhotoNomad0 
[en_joel_mat_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/2550477/en_joel_mat_book.zip)

**Comment by cckozie** [comment]
@PhotoNomad0 I also now tested with a new Titus project. I fully aligned 3 verses. Went to the Tools page and see 7% complete. Went back to the 3 verses and unaligned 1 word in each. Now seeing 0% on the wA tool card.

**Comment by cckozie** [comment]
Here's the one from the screenshot. Note that the difference may be that in the tool it counts it as aligned if the Alignment Complete switch is on. On the tool card it doesn't count those unless all the words are aligned.
[en_tttt_rom_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/2550651/en_tttt_rom_book.zip)

**Comment by PhotoNomad0** [comment]
On the WA toolcard progress, it currently counts verses as all aligned or nothing - this is how it has been for a long time. 

Also it is not aware of the complete toggle - that was a later addition not yet factored in.

**Comment by PhotoNomad0** [comment]
Covered In #4773
