### ISSUE TITLE
Alignment Complete Toggle Does Not Always Work

### ISSUE THREAD

**Issue by RoyalSix** [unfoldingWord/translationCore#5373]
### Prerequisites

* Put an X between the brackets on this line if you have done all of the following:

- [X] I have searched the [issues](https://github.com/unfoldingWord-dev/translationCore/issues) of this repository and believe that this is not a duplicate.

### Description
The alignment complete toggle does not switch on. 

### Steps to Reproduce

1. Load a fresh project, open wA
2. Use every word in the word list to align to the Greek words, but do not use every Greek word. i.e. there should be some greek words that have multiple target language words aligned to them
3. Now move the extra target language words to the empty Greek words until all the Greek words have an alignment
4. The alignment complete should be toggled at this point because 
  - All the words from the word list have been used
  - All the Greek words have an alignment

**Screenshots**

**Expected behavior:** The alignment to be automatically toggeld on

**Actual behavior:** Alignment toggle does not turn on

### Context

**Enviorment**
| Tech         | Version |
|--------------|---------|
| tc           | v1.0.2  |
| build #      | N/A         |
| OS           |   OSX      |

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by cckozie** [comment]
This is the same issue as #5374 where there is a better description on how to replicate the problem. The steps outlined above do not always cause a failure.
