### ISSUE TITLE
Scenarios where Alignment Complete fails to automatically get set

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5374]
1.0.2 (ac3d66a) 
SCENARIO A:
1. Load a Matthew project and align verse 15:7 as shown here:
![image](https://user-images.githubusercontent.com/8171759/48017749-b6e67a00-e0f4-11e8-82a6-193e73c334e8.png)
2. Drag the word 'said' to the Greek word 'Ἠσαΐας'
3. Drag the word 'he' to the Greek word as shown below
Note that the alignment complete does not get set.
![image](https://user-images.githubusercontent.com/8171759/48017908-1b093e00-e0f5-11e8-8027-18b599bfffb0.png)

1.1.3 (4f85a74)]
SCENARIO B:
1. Open any project in wA
2. Align all words in the word list to all of the Greek words but leaving one Greek word empty. 
3. Merge the empty Greek word to the one next to it.
Note that the Alignment complete switch does not get toggled.

**Comment by elsylambert** [comment]
Retested on 2.0.0 (ca6c273). Not seeing this issue.
