### ISSUE TITLE
Source content updater offers resource just updated

### ISSUE THREAD

**Issue by bspidel** [unfoldingWord/translationCore#5376]
### Prerequisites

* Put an X between the brackets on this line if you have done all of the following:

- [x] I have searched the [issues](https://github.com/unfoldingWord-dev/translationCore/issues) of this repository and believe that this is not a duplicate.

### Description

Source content updater offers to update resources that have already been successfully updated

### Steps to Reproduce

1. Go to 'Actions'
2. Click on 'Check for content updates'
3. Select all
4. Click download
5. Repeat Steps 1 and 2

Note a resource may be visible which was just updated

**Screenshots**

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

### Context

**Enviorment**
| Tech         | Version |
|--------------|---------|
| tc           | v1.0.2  |
| build #      | 36c4430        |
| OS           | x64 Win10        |

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by cckozie** [comment]
Additional information:
I believe that sometimes this is due to tC reporting all downloads as being successful even when one or more of the resources for one of the languages did not actually get downloaded or moved to the resources folder.

**Comment by elsylambert** [comment]
Retested on 2.0.0 (ca6c273). Not seeing this issue. Downloaded only few resources and after the download, cannot find them in the list.
