### ISSUE TITLE
Reference data missing in VerseEdits file of CSV export

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5377]
The following columns are blank in all cases (regardless of where the edit was made):
gateway Language Quote
groupId
groupName
occurence
quote

**Comment by cckozie** [comment]
1.1.0 (2ba28f8) 
1. The gateway Language Quote field shows the group Name, not the GL quote.
2. The gateway Language Quote, groupId, groupName, occurance, and quote should all be blank when the edit was performed external to tC.

**Comment by RoyalSix** [comment]
I believe the first issue is in #4901
I can fix the second issue.

**Comment by PhotoNomad0** [comment]
Seeing errors  on CSV export.  Paths are wrong.

<img width="910" alt="screen shot 2019-01-03 at 12 09 11 pm" src="https://user-images.githubusercontent.com/14238574/50651185-99952700-0f50-11e9-8c49-ff0163b4fe81.png">

testing on build https://tc-builds.door43.org/build/bugfix-mcleanb-3989/translationCore-macos-x64-1.1.0-8720d95.dmg

**Comment by PhotoNomad0** [comment]
@RoyalSix - is this because I opened the WA tool before CSV export?

**Comment by RoyalSix** [comment]
@PhotoNomad0 How come you are testing on a build from your branch?
Can you try on the develop build and provide exact steps to repeat.

**Comment by PhotoNomad0** [comment]
@RoyalSix - sorry pasted wrong link.  Testing with https://tc-builds.door43.org/build/develop/translationCore-macos-x64-1.1.0-9e93ea9.dmg

Double checked and still see the problem.

**Comment by PhotoNomad0** [comment]
@RoyalSix - Issue seems to be pre-existing.

**Comment by PhotoNomad0** [comment]
verified with https://tc-builds.door43.org/build/develop/translationCore-macos-x64-1.1.0-9e93ea9.dmg
