### ISSUE TITLE
Edits made outside of tC should not show a tool name for the edit in the CSV file

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5378]
It appears that they now all show 'wordAlignment' as the tool for edits made externally. The tool should probably be blank in those cases. We may want to add another column to indicate an external edit (or we could put something like 'external edit' in the tool column).

## Specs
- [ ] Show `[External edit]` in the tool column

**Comment by RoyalSix** [comment]
@cckozie Do you have a project with edits made externally? If not how would I replicate that?

**Comment by cckozie** [comment]
@RoyalSix The best way to test this is to do a usfm2 export of a project, make some changes in the exported file, then reimport that file. That way you'll know which edits were make outside of tC.
BTW: I'm also reopening this issue

**Comment by RoyalSix** [comment]
@cckozie thanks somehow I closed accidentally

**Comment by RoyalSix** [comment]
@cckozie I am still having trouble replicating this issue. It does not show verse edit changes at all for me

**Comment by cckozie** [comment]
@RoyalSix In 1.1.0 (4f79403) I am seeing the edits, but they still show up as having been made in Word Alignment. In this project I used a text editor to change a word in verse 1, delete verse 2, and add a word in verse 3. They all show in the csv file.
[VerseEdits.csv.zip](https://github.com/unfoldingWord-dev/translationCore/files/2695694/VerseEdits.csv.zip)

**Comment by cckozie** [comment]
1. Import a project
2. Export the project to USFM2 (no alignments)
3. Edit the exported file to make changes to the verse texts
4. Save the edited USFM file
5. Import the edited file using the same translation id as the original and choose the overwrite options
6. Export the file to CSV
7. Examine the VerseEdits CSV file

**Comment by cckozie** [comment]
Works in 1.1.0 (773355b)
