### ISSUE TITLE
In wA, when the user scrolls the group menu, the app should not automatically scroll it to another place.

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5379]
This is a follow-on to #5140 which was passed without being completed in order to get 1.0.2 released.
When the user scrolls the group menu in word alignment, it the menu should not be moved/scrolled again until the user moves it. Currently it jumps around based on where it is set and what happens with the Alignment Complete switch.

**Comment by elsylambert** [comment]
Unable to replicate in 2.0.0 (ca6c273).
