### ISSUE TITLE
tC loses some data in usfm files if the line does not begin with a usfm tag

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5380]
1.0.2 (7ccb0dc) 
**Input file text A:**
\s1 The Preaching of John the Baptist\x - \xo 3.0 \xta Compare with \xt Mk 1.1-8;
Lk 3.1-18; \xta and \xt Jn 1.19-28 \xta parallel passages.\x*
**Exported file textA:**
\s1 The Preaching of John the Baptist\x - \xo 3.0 \xta Compare with \xt Mk 1.1-8;
\xta and \xt Jn 1.19-28 \xta parallel passages.\x*

**Input file text B:**
\v 15 Adam \f + \fr 3.20: \fk Adam: \ft This name in Hebrew means ‚Äúall human beings.‚Äù\f*
named his wife Eve, \f + \fr 3.20: \fk Eve: \ft This name sounds similar to the Hebrew
word for ‚Äúliving,‚Äù which is rendered in this context as ‚Äúhuman beings.‚Äù\f* because she
was the mother of all human beings.
**Exported file text B:**
\v 15 Adam \f + \fr 3.20: \fk Adam: \ft This name in Hebrew means ‚Äúall human beings.‚Äù\f*
named his wife Eve, \f + \fr 3.20: \fk Eve: \ft This name sounds similar to the Hebrew
\f* because she
was the mother of all human beings.

**Input file text C:**
\v 3 √âl es el resplandor glorioso de Dios,\f c \fr 1.3: \fk Resplandor: \ft Cf.
Jn 1.4-9,14\fdc ; tambi√©n Sab 7.25-26, donde algo parecido se dice de la sabidur√≠a.\f*
la imagen misma de lo que Dios es y el que sostiene todas las cosas con su palabra
poderosa. Despu√©s de limpiarnos de nuestros pecados, se ha sentado en el cielo, a la
derecha del trono de Dios,
**Exported file text C:**
\v 3 √âl es el resplandor glorioso de Dios,\f c \fr 1.3: \fk Resplandor: \ft Cf.
\fdc ; tambi√©n Sab 7.25-26, donde algo parecido se dice de la sabidur√≠a.\f*
la imagen misma de lo que Dios es y el que sostiene todas las cosas con su palabra
poderosa. Despu√©s de limpiarnos de nuestros pecados, se ha sentado en el cielo, a la
derecha del trono de Dios,

**Input file text D:**
\v 8 whoever believes in me should drink. As the scripture says, ‚ÄòStreams of life-
giving water will pour out from his side.‚Äô‚Äù \f + \fr 7.38: \ft Jesus' words in verses
37-38 may be translated: \fqa ‚ÄúWhoever is thirsty should come to me and drink.
\fv 8\fv* As the scripture says, ‚ÄòStreams of life-giving water will pour out from
within anyone who believes in me.‚Äô‚Äù\f*
**Exported file text D:**
v 8 whoever believes in me should drink. As the scripture says, ‚ÄòStreams of life-
giving water will pour out from his side.‚Äô‚Äù \f + \fr 7.38: \ft Jesus' words in verses
\fqa ‚ÄúWhoever is thirsty should come to me and drink.
\fv 8\fv* As the scripture says, ‚ÄòStreams of life-giving water will pour out from
\f*

input file: [usfm body testD.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/2554426/usfm.body.testD.usfm.zip)

exported file: [57-TITd.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/2554427/57-TITd.usfm.zip)

**Comment by PhotoNomad0** [comment]
@cckozie - verified issue fixed in https://tc-builds.door43.org/build/release-v1.0.2/translationCore-win-x64-1.0.2-b2a7195.setup.exe

**Comment by cckozie** [comment]
Looks good in 1.0.2 (eb69ffb)
