### ISSUE TITLE
tC removes spaces between adjoining usfm markers

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5381]
1.0.2 (7ccb0dc) 

**Input file text A:**
\v 2-7 They presented their offerings in the following order:
\tr \th1 Day \th2 Tribe \th3 Leader
\tr \tcr1 1st \tc2 Judah \tc3 Nahshon son of Amminadab
\tr \tcr1 2nd \tc2 Issachar \tc3 Nethanel son of Zuar
\tr \tc1 Judah \tc2 Nahshon son of Amminadab \tcr3 74,600
\tr \tc1 Issachar \tc2 Nethanel son of Zuar \tcr3 54,400
**Exported file text A:**
\v 2-7 They presented their offerings in the following order:
\tr\th1 Day \th2 Tribe \th3 Leader
\tr\tcr1 1st \tc2 Judah \tc3 Nahshon son of Amminadab
\tr\tcr1 2nd \tc2 Issachar \tc3 Nethanel son of Zuar
\tr\tc1 Judah \tc2 Nahshon son of Amminadab \tcr3 74,600
\tr\tc1 Issachar \tc2 Nethanel son of Zuar \tcr3 54,400

input file: [usfm body testD.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/2554426/usfm.body.testD.usfm.zip)

exported file: [57-TITd.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/2554427/57-TITd.usfm.zip)

**Comment by PhotoNomad0** [comment]
This should be fixed in PR https://github.com/unfoldingWord-dev/translationCore/pull/5390

**Comment by PhotoNomad0** [comment]
This should be fixed in PR https://github.com/unfoldingWord-dev/translationCore/pull/5390

**Comment by PhotoNomad0** [comment]
@cckozie - verified issue fixed in https://tc-builds.door43.org/build/release-v1.0.2/translationCore-win-x64-1.0.2-b2a7195.setup.exe

**Comment by cckozie** [comment]
Looks good in 1.0.2 (eb69ffb)
