### ISSUE TITLE
tC removes keyword usfm markers

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5382]
1.0.2 (7ccb0dc) 

**Input file text:**
\k keyword \k*

**Exported file text:**
\k*

input file: [usfm body testD.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/2554426/usfm.body.testD.usfm.zip)

exported file: [57-TITd.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/2554427/57-TITd.usfm.zip)

**Comment by PhotoNomad0** [comment]
Notes:

- seeing conflicts with our non-standard `\k-s` word marker
- verse spans not yet supported in tCore, we import them fine, but not displayed in app.

**Comment by PhotoNomad0** [comment]
@cckozie - verified issue fixed in https://tc-builds.door43.org/build/release-v1.0.2/translationCore-win-x64-1.0.2-b2a7195.setup.exe

Note that we do not fully support verse spans in tCore.

**Comment by cckozie** [comment]
Looks good in 1.0.2 (eb69ffb)
