### ISSUE TITLE
Problem with usfm links

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5383]
1.0.2 (7ccb0dc)
input text:
\v 1 But you, speak what fits with faithful instruction.
The traditional translation of verse 1, as given in
\jmp RSV|link-href="prj:RSV52 GEN 1:1" link-title="Revised Standard Version"\jmp*,
may be appropriate.
Storehouses, as used here, refers to large buildings with walls and roof, where grain was
kept until needed. (See illustration: \jmp Storehouse|link-href="figures/storehouse.png"
link-title="Ancient storehouse"\jmp*)

exported text: 
\v 1 But you, speak what fits with faithful instruction.
The traditional translation of verse 1, as given in
\jmp RSV|link-href="prj:RSV52 GEN 1:1" link-title="Revised Standard Version"\jmp*,
may be appropriate.
Storehouses, as used here, refers to large buildings with walls and roof, where grain was
kept until needed. (See illustration: \jmp Storehouselink-title="Ancient storehouse"\jmp*)

Notice that the text ' |link-href="figures/storehouse.png" ' is missing in the exported file.

**Comment by PhotoNomad0** [comment]
Tested with: [links.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/2558898/links.usfm.zip)

**Comment by PhotoNomad0** [comment]
This should be fixed in PR https://github.com/unfoldingWord-dev/translationCore/pull/5390

**Comment by PhotoNomad0** [comment]
@cckozie - verified issue fixed in https://tc-builds.door43.org/build/release-v1.0.2/translationCore-win-x64-1.0.2-b2a7195.setup.exe

**Comment by cckozie** [comment]
Looks good in 1.0.2 (eb69ffb)
