### ISSUE TITLE
Add latest Portuguese & Spanish locale strings

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord/translationCore#5385]
### User Story

As a [type of user], I want [some goal] so that [some reason].

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by PhotoNomad0** [comment]
@cckozie - verified in https://tc-builds.door43.org/build/release-v1.0.2/translationCore-win-x64-1.0.2-914876a.setup.exe
