### ISSUE TITLE
tC adds extra closing \bk* markers

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5389]
[57-TIT-intro.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/2557778/57-TIT-intro.usfm.zip)
1.0.2 (7ccb0dc)
Input file text:
\bk Mark\bk* the title is used of Jesus in three ways: the Son of Man acts with divine

Exported file text:
\bk Mark\bk* the title is used of Jesus in three ways: the Son of Man acts with divine\bk*

Imported file: [usfm intro test.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/2557784/usfm.intro.test.usfm.zip)

Exported file: [57-TIT-intro.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/2557778/57-TIT-intro.usfm.zip)

**Comment by PhotoNomad0** [comment]
Have a fix in the usfm-js module that will fix this specific issue.  But I notice that on import tCore itself strips out embedded word tags ('\w') as part of parsing out alignment.  But in the case there is no alignment, on export it does not restore the tags.

**Comment by PhotoNomad0** [comment]
@cckozie - verified in https://tc-builds.door43.org/build/release-v1.0.2/translationCore-win-x64-1.0.2-914876a.setup.exe

**Comment by cckozie** [comment]
Works in 1.1.0 (8b1ff72)
