### ISSUE TITLE
Recently imported project crashes translationWords tool

### ISSUE THREAD

**Issue by bspidel** [unfoldingWord/translationCore#5392]
### Prerequisites

* Put an X between the brackets on this line if you have done all of the following:

- [x] I have searched the [issues](https://github.com/unfoldingWord-dev/translationCore/issues) of this repository and believe that this is not a duplicate.

### Description

Having just imported a test project: https://git.door43.org/tCore-test-data/am_1co_ulb launching tW crashes app.

### Steps to Reproduce

**Screenshots**
![wacrash](https://user-images.githubusercontent.com/4968713/48155862-f1d5e280-e299-11e8-939b-e8aeaf652c13.PNG)

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

### Context

**Enviorment**
| Tech         | Version |
|--------------|---------|
| tc           | v1.0.2  |
| build #      | 7ccb0dc        |
| OS           |  x64 win10       |

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by benjore** [comment]
Could not reproduce in 1.1.3

**Comment by cckozie** [comment]
works in https://git.door43.org/tCore-test-data/am_1co_ulb
