### ISSUE TITLE
tC fails to display text in the scripture pane when it is preceded by the \qt marker

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5397]
1.0.2 (eb69ffb)
It does show correctly in the tW check pane and in the word bank

[55-1TI-qt.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/2563838/55-1TI-qt.usfm.zip)

![image](https://user-images.githubusercontent.com/8171759/48231549-2027f080-e374-11e8-801a-f0c7eb28bec9.png)

![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/afac4d65-620a-4b94-90a0-06a11f21e6ba)

![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/510e66cd-a12a-4d10-8738-f91beb170015)

![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/dfff792b-0bf6-4a2e-8068-172334ebfb91)

**Comment by PhotoNomad0** [comment]
Discovered that node_module dependencies are hard coded in tc-ui-toolkit, and dependency checkers don't alert you to that.  So it was locked to older usfm-js package.  updating tc-ui-toolkit, to fix.

**Comment by PhotoNomad0** [comment]
Verified working in https://tc-builds.door43.org/build/release-v1.0.2/translationCore-win-x64-1.0.2-12d7d75.setup.exe
