### ISSUE TITLE
Verse overlaps chapter section header in verse check pane

### ISSUE THREAD

**Issue by bspidel** [unfoldingWord/translationCore#5400]
### Prerequisites

* Put an X between the brackets on this line if you have done all of the following:

- [x] I have searched the [issues](https://github.com/unfoldingWord-dev/translationCore/issues) of this repository and believe that this is not a duplicate.

### Description

When making keyword selection in Mat 24:15, The Ghotuo target language has section headers that when wrapping, overlap verse below. See attachment 

### Steps to Reproduce

1. Import aaa_mat_text_reg
2. Launch translationWords
3. Make the word "when" selected in 24:15
4. Note overlap of "24:15" and "Therefore"

**Screenshots**
![checkoverlap](https://user-images.githubusercontent.com/4968713/48305871-5c885780-e500-11e8-8249-5728627dbbe6.PNG)

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

### Context

**Enviorment**
| Tech         | Version |
|--------------|---------|
| tc           | v1.0.2  |
| build #      | 914876a        |
| OS           |  x64 Win10       |

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by elsylambert** [comment]
Retested on 2.0.0 (ca6c273). Not seeing this issue.
