### ISSUE TITLE
Resolve remaining issues that are still causing some level of memory leak in the scripture pane

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord/translationCore#5403]
### User Story

As a user, I want to be able to make multiple verse edits in the scripture pane without the app hanging so that I don't risk losing my work.

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by da1nerd** [comment]
This is related to https://github.com/unfoldingWord-dev/translationCore/issues/5298 though the situation has been greatly improved. Instead of freezing after reopening the scripture pane 13 times it takes 80-100 reopens.

**Comment by cckozie** [comment]
1.1.3 (2c25b41)
The system appears to recover pretty well from the high memory usage now. The highest consuming process consumption does grow to above 900MB on my machine, but it does manage to free up memory over time and get back down into the 400+MB range before growing more.
Even with the growing memory consumption the performance did not appear to suffer. The test results for a full iteration of edit, save, realign remained in the 15-17 seconds range for the entire test of 100 iterations.
I'm closing the issue.
