### ISSUE TITLE
Selecting Hindi as Gateway language does not automatically display it in Scripture Pane

### ISSUE THREAD

**Issue by bspidel** [unfoldingWord/translationCore#5405]
### Prerequisites

* Put an X between the brackets on this line if you have done all of the following:

- [x] I have searched the [issues](https://github.com/unfoldingWord-dev/translationCore/issues) of this repository and believe that this is not a duplicate.

### Description

Having selecting Hindi as Gateway the language at tW launch does not automatically display Hindi as Gateway Language in Scripture Pane. You have to manually add it.

### Steps to Reproduce

1. Go to 'Tool Card'
2. Click on 'Gateway Language'
3. Scroll down to and Click 'Hindi'
4. Click launch

Note Hindi is not in Scripture pane but it is in check pane and help pane.

**Screenshots**

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

### Context

**Enviorment**
| Tech         | Version |
|--------------|---------|
| tc           | v1.0.2  |
| build #      | 1681fcf        |
| OS           | x64 Win10        |

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by benjore** [comment]
Dup of #4742
