### ISSUE TITLE
wA Edit/Comment/Bookmark: Title bar UI + Icons

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5406]
see UI design at https://github.com/unfoldingword/translationcore/issues/4538

**Comment by PhotoNomad0** [comment]
@benjore @cckozie - trying to find the UI mockup for this, but without luck.

**Comment by PhotoNomad0** [comment]
@birchamp @cckozie @elsylambert - have a test build for this issue:

[Linux build 2.1.0 (5ffddb9)](https://tc-builds.door43.org/build/feature-mcleanb-5406/translationCore-linux-x64-2.1.0-5ffddb9.deb) is ready for download.
[macOS build 2.1.0 (5ffddb9)](https://tc-builds.door43.org/build/feature-mcleanb-5406/translationCore-macos-x64-2.1.0-5ffddb9.dmg) is ready for download.
[Windows x64 build 2.1.0 (5ffddb9)](https://tc-builds.door43.org/build/feature-mcleanb-5406/translationCore-win-x64-2.1.0-5ffddb9.setup.exe) is ready for download.
[Windows x32 build 2.1.0 (5ffddb9)](https://tc-builds.door43.org/build/feature-mcleanb-5406/translationCore-win-x32-2.1.0-5ffddb9.setup.exe) is ready for download.

**What is working:**
- wA toolbar icons show state, but are not yet clickable.
- group menu filters: 
  - can filter by verse edits, bookmark, comments
  - badges work.

Here is a test project that has a bookmark and comment for testing: 
[en_alcz_tit_book 2.zip](https://github.com/unfoldingWord/translationCore/files/4015599/en_alcz_tit_book.2.zip)

**Comment by cckozie** [comment]
@PhotoNomad0 Test build looks good to me.

**Comment by PhotoNomad0** [comment]
@cckozie - Ready for more tire kicking.  Verified in translationCore 2.1.0 (9782150).

Should soon have a version with actionable icons.

**Comment by cckozie** [comment]
The horizontal sizing of the alignment area has changed a little from the previous build. The vertical scroll bar for the alignment area is no longer directly against the word bank as it was previously. (@birchamp - Do we care about this?)
Then in 2.1.0 (46a3795)
<img width="1440" alt="align" src="https://user-images.githubusercontent.com/8171759/71832753-33664700-3071-11ea-8750-203f5ffd2859.png">

Now in 2.1.0 (9782150)
<img width="1440" alt="alignA" src="https://user-images.githubusercontent.com/8171759/71832890-73c5c500-3071-11ea-8790-b221fefda400.png">

**Comment by cckozie** [comment]
2.1.0 (9782150)
Decided horizontal sizing was fine as is.
