### ISSUE TITLE
wA Edit/Comment/Bookmark: UI and back-end for Comments and Bookmarks

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5409]

**Comment by PhotoNomad0** [comment]
This should make Comments and Bookmarks fully functional in WA tool (Verse Edit is still pending).

Verified in translationCore 2.1.0 (9be0e63)

Builds are here: https://github.com/unfoldingWord/translationCore/actions/runs/32942120

**Comment by elsylambert** [comment]
Verified in v2.1.0(c42350b). Saved comment and the bookmark on a verse is lost when switch to next verse.
- Saved comment on Tit 1:2 and added the bookmark.
- Move to 1:3.
- Switch back to 1:2 and the comment and bookmark are not there. However the left side menu shows the Comment and bookmark Icon.
![image](https://user-images.githubusercontent.com/51806180/73469925-1ada0b80-4355-11ea-99a2-a52f83609b6c.png)

**Comment by PhotoNomad0** [comment]
@elsylambert - having trouble reproducing the problem you are seeing on Mac - translationCore 2.1.0 (c42350b). Will take a look at windows

**Comment by PhotoNomad0** [comment]
@elsylambert - I'm seeing this problem on Windows only...very strange.

**Comment by PhotoNomad0** [comment]
Verified latest windows build b3e4a9d. builds at:  https://github.com/unfoldingWord/translationCore/actions/runs/33124141

**Comment by elsylambert** [comment]
Verified in 2.1.0(b3e4a9d). Issue with the Comments and bookmark data being lost has been resolved in Windows.

**Comment by cckozie** [comment]
Looks good in 2.1.0 (aed42f3) on Mac.
