### ISSUE TITLE
Cannot load UGNT into scripture pane with "Add Resources" loader

### ISSUE THREAD

**Issue by bspidel** [unfoldingWord/translationCore#5412]
### Prerequisites

* Put an X between the brackets on this line if you have done all of the following:

- [x] I have searched the [issues](https://github.com/unfoldingWord-dev/translationCore/issues) of this repository and believe that this is not a duplicate.

### Description

Once it has been closed, A user cannot load UGNT into scripture pane with "Add Resources" loader. It shows up in dropdown list but does nothing.

### Steps to Reproduce

1. Go to 'tW'
2. Click on 'X on UGNT scripture pane'
3. Scroll down to 'UGNT' in Add Resource List
4. Click on UGNT
5. Note that nothing happens.

**Screenshots**

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

### Context

**Enviorment**
| Tech         | Version |
|--------------|---------|
| tc           | v1.0.2  |
| build #      | 1681fcf        |
| OS           | x64 Win10        |

### Additional Information

Note that if you launch the other tool, it will come back.

**Comment by cckozie** [comment]
Dup of #5119 ?
