### ISSUE TITLE
tC's listing of languages on the resource selection page is case sensitive but should not be

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5437]
1.0.2 (1681fcf) 

![urdu.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/7caac3a1-9a11-4d7c-a5fa-fa898cbffa33)

This causes tC some problems. If the user selects all (or both of them) to download, only the one with mixed case is downloaded and the other one still appears in the resource selection screen. When the all lower case one is then selected, the app shows the alert stating that the download was successful, but it still does not appear in the resources folder and it does continue to be shown on the resource selection screen.
Downloading the mixed case one loads the ULB.
Downloading the lower cased one loads the tW.
Choosing to download them both actually loads both the ULB and tW even though the lower case one still remains on the resource selection page.

It looks like the all lower case one has been added since 1.0.0.

tC should disregard the case when downloading resources.
How do we want to handle these situations?
- What do we show as the language name?
- What do we show as the language code?
- Is this true everywhere in tC? (Resource update selection screen, scripture pane dropdown, project card, others?)

[1] Resolve questions for 5437
[3] Locate place for change for 5437
[6] Write code for 5437
[4] Write and execute unit test cases for 5437
[2] Manage PR for 5437

### Proposal
- Throughout app over time we migrate toward 
   - Language names to be mixed case
   - Language codes are lower case
   - Ordering is case insensitive
   - Filtering is case insensitive
- This issue covers content updates
- An issue for each context perhaps in an epic

**Comment by PhotoNomad0** [comment]
@cckozie @benjore - in tCore we are treating language codes as just text.  That can cause a lot of problems in the app where we are bringing in resources from the catalog that have all different cases for the same language (and different language descriptions).  Maybe the quickest solution would be to convert every language code to lower case for use in the app.  It seems that allowing mixed case language codes would require adding a lot of extra code for every check or load of local and remote resources.

**Comment by benjore** [comment]
@PhotoNomad0 That works for me.

**Comment by cckozie** [comment]
1.1.0 (8b1ff72)
There is now only one of the two (Urdu Devanagari script (ur-Deva)) in the source content selection screen, but when it is selected and downloaded only the Bibles folder comes down. The translationHelps folder is not downloaded but should be.

**Comment by PhotoNomad0** [comment]
@bspidel - I think these changes in tc-source-content-updater only:

#### Convert languageID to lower case 
- https://github.com/translationCoreApps/tc-source-content-updater/blob/develop/src/helpers/parseHelpers.js#L207

#### Do case insensitive compare of languageID
- https://github.com/translationCoreApps/tc-source-content-updater/blob/develop/src/helpers/parseHelpers.js#L129

**Comment by cckozie** [comment]
Workds in 1.1.0 (2ba28f8)
