### ISSUE TITLE
App crash/hang

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5442]
1.0.2 (1681fcf)
This is related to issue #5441 
This first time I noticed the issue described in 5441, when tC 1.0.2 opened the screen was completely blank with errors in the console. After close tC I was able to restart it. 
I have not been able to reproduce this crash/hang.
![image](https://user-images.githubusercontent.com/8171759/48583505-e6fbfd00-e8ec-11e8-8cc0-a1fa34be10ef.png)

**Comment by elsylambert** [comment]
Retested on 2.0.0 (ca6c273). Not seeing this issue.
