### ISSUE TITLE
Bundle Hebrew Bible & Lexicon as a part of the build process

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5475]
### User Story

As a user, I want [some goal] so that [some reason].

### Features / Specifications

- [ ] Create a new migration to add any bundled resource (e.g. the Hebrew Bible & Lexicon) if it is missing
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by cckozie** [comment]
Can't fully test until #5543 is fixed.

**Comment by cckozie** [comment]
Works in 1.1.0 (4d06842)
