### ISSUE TITLE
Put translationCore app on a diet with Electrino (If possible)

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord/translationCore#5477]
### User Story

As a tC user, I want a smaller tc's bundle size so that I can have room for other apps on my computer and memory 

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by benjore** [comment]
@mannycolon Is this still a good idea to explore? I don't recall all the history on this, or why it was brought back to `New Issues`.

**Comment by mannycolon** [comment]
@benjore Yes, this is still a good idea. I created it but never brought it up to the team and did not know where to put it for you to look at.

**Comment by mannycolon** [comment]
Never mind I just checked the electrino repo and it is in its early stages of development and it's not ready for production

**Comment by benjore** [comment]
@mannycolon Can we close this issue then?
