### ISSUE TITLE
Exporting Alignments with numbers fails

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#5513]
#### Larry's description of the problem:

Just loaded 1.0.2 and went back to Gal 3:17 in the ULT to finish aligning the number “430” that 1.0 could not display. Had checked off the “do not show” notification previously. After I finished aligning, I tried to upload to Door43. Get the broken alignment warning. Rechecked that all verses showed green checks. Uploaded anyway. This wiped out the alignment of 3:17. Realigned and tried to upload, but get the same error. 

#### Analysis

It looks like on upload and  export word-aligner is treating the “430” as text rather than a word to be aligned. 

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by PhotoNomad0** [comment]
Found that word-aligner merge was not accepting numbers as alignment words.

**Comment by PhotoNomad0** [comment]
Verified in translationCore-win-x64-1.0.3-0fa00d3.setup.exe

**Comment by cckozie** [comment]
@PhotoNomad0 Should this be in the 1.1.0 build? It does not appear to be.

**Comment by PhotoNomad0** [comment]
@cckozie - Not yet, but good reminder.  Will make a PR.

**Comment by PhotoNomad0** [comment]
@cckozie - verified in https://tc-builds.door43.org/build/develop/translationCore-win-x64-1.1.0-d7708ab.setup.exe - do not get error when I exported aligned Gal 3:17

**Comment by cckozie** [comment]
1.1.0 (c6414a7)
This appears to be fixed, but I had to load an old version in order to do the alignments. Need to retest when #5543 is fixed.

**Comment by cckozie** [comment]
Works in 1.1.0 (4d06842)

**Comment by cckozie** [comment]
This is broken again in 1.1.0 (ac75c11)
[49-GAL.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/2738343/49-GAL.usfm.zip)

1. Import the attached project
2. Load in wA
3. Align the number 430 in verse 3:17
![image](https://user-images.githubusercontent.com/8171759/50857005-eb272280-1351-11e9-899f-736f2b051017.png)
4. Upload the project to Door43. Note that the alignments reset alert is displayed
5. Load the project again in wA. Note that the alignment actually has not be reset
6. Return to the projects page and load a different project in wA
7. Return to the projects page and and select the Galatians. Note that the alignments reset alert is displayed and that after clicking the OK button, the wA tools card shows 1 reset alignment
8. Load the project wA and note that the alignment has been reset

**Comment by PhotoNomad0** [comment]
@cckozie - on step 4 above, did select cancel or export at the alignments reset prompt?

**Comment by cckozie** [comment]
@PhotoNomad0 Export

**Comment by PhotoNomad0** [comment]
@cckozie - found that fix for 1.0.3 was not in 1.1.0

**Comment by PhotoNomad0** [comment]
Verified in https://tc-builds.door43.org/build/develop/translationCore-macos-x64-1.1.0-b47c7fb.dmg

**Comment by cckozie** [comment]
Works in 1.1.0 (7c2a84b)
