### ISSUE TITLE
Remove Invalidation link only when Alignment Complete is toggled

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5520]
### User Story

As a curious checker, I want the invalidation link to stay on the verse (in wA) until the Alignment Complete toggle is turned on so that my workflow allows me to see what happened without forcing me to immediately fix the invalidation.

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

## Notes
- Based on user feedback (Jobby)

**Comment by PhotoNomad0** [comment]
Verified in Develop build translationCore 2.1.0 (3d944e3) _**this is not in release v2.1.0 **_
Develop builds here: http://tc-builds.door43.org.s3-website-us-west-2.amazonaws.com/build/develop/

**Comment by cckozie** [comment]
Works in 2.1.0 (ed1c32c)

**Comment by elsylambert** [comment]
Looks good in 2.1.0 (ed1c32c)

**Comment by elsylambert** [comment]
2.1.2 (44c92e9). Seeing the invalidations removed in wA when the invalidated verse is opened.

**Comment by elsylambert** [comment]
This was not part of 2.1.0 Release
