### ISSUE TITLE
Upload to Door43 is broken

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5534]
1.1.0 (8b1ff72) 
[en_ult_tit_book 2.zip](https://github.com/unfoldingWord-dev/translationCore/files/2654474/en_ult_tit_book.2.zip)

I'm getting this message on any upload to Door43
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/cb0c74ce-f26a-4d8e-9c22-7a933b515066)

**Comment by da1nerd** [comment]
@cckozie can you provide the project  you were using?
If possible I'd like to have the entire directory not just the exported usfm.

**Comment by da1nerd** [comment]
This was an easy fix. Projects that had not been initialized for git were failing to upload. Now all projects are initialized before performing git operations.

**Comment by cckozie** [comment]
Appears to be fixed in 1.1.0 (c6414a7).
Can't fully test until #5543 is fixed.

**Comment by cckozie** [comment]
Fixed in 1.1.0 (4d06842)
