### ISSUE TITLE
Cannot import from Door43

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5542]
1.1.0 (c6414a7)
![image](https://user-images.githubusercontent.com/8171759/49739303-2a7d2900-fc57-11e8-856e-723dded01b2b.png)
https://git.door43.org/qa99/en_ulb_gal_book
This is a recently uploaded project.

**Comment by da1nerd** [comment]
@cckozie the import failed because there's nothing in that project. Open https://git.door43.org/qa99/en_ulb_gal_book in your browser. There's no code and no branches.

**Comment by da1nerd** [comment]
If there is a bug it's with uploading projects. Can you test uploading some projects and make sure the content actually get's there?
