### ISSUE TITLE
Delay in upload to Door43 but not in export to USFM

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5550]
1.1.0 (4d06842) 
[en_ulb_gen_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/2665354/en_ulb_gen_book.zip)
This project does not have any alignments, thus when exporting to USFM the user is not given the option to include alignments. However, when uploading to Doo43, the app appears to hang for about 6 seconds (on my Mac). I assume this 'hang' time is due to the app thinking that there are alignments and is thus checking for reset ones.

**Comment by elsylambert** [comment]
Retested on 2.0.0 (ca6c273). Not seeing this issue.
