### ISSUE TITLE
Anomalies in wordMap

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5554]
1.1.0 (4d06842) 
[en_ult_tit_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/2668301/en_ult_tit_book.zip)

![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/a8cfaf6b-5fbe-49f4-aee0-83a8eaa4d602)

**Comment by benjore** [comment]
I think this is expected behavior since there is only one `and` in the word bank. (The word `kai` can also me `even`, `also`, `namely`, which I think is what's happening for the first instance.)

**Comment by cckozie** [comment]
OK.
