### ISSUE TITLE
Add progress and invalid check count APIs to wA tool

### ISSUE THREAD

**Issue by da1nerd** [unfoldingWord/translationCore#5598]

**Comment by cckozie** [comment]
@neutrinog Is there anything I can test for this issue?

**Comment by da1nerd** [comment]
not really. Once https://github.com/unfoldingWord-dev/translationCore/pull/5612 is merged in wA will be completely hooked up to display the invalid checks and the progress.

**Comment by cckozie** [comment]
Holding all of these until I can verify both tools end to end.
