### ISSUE TITLE
Opening old project with in tCore the rename prompt is automatically dismissed

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#5618]
### User Story

As a user, when I open old projects I don't want to have to rename prompt to just flash on screen, but to wait until I click on it.

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

## Additional Context
- can reproduce problem with this project: [es-419_tit_no_git.zip](https://github.com/unfoldingWord-dev/translationCore/files/2695874/es-419_tit_no_git.zip)

**Comment by da1nerd** [comment]
@PhotoNomad0 see attached PR for a fix.

**Comment by cckozie** [comment]
Works in 1.1.0 (b287d3d)

**Comment by cckozie** [comment]
1.1.0 (9e93ea9)
The project (re)named alert is now not being displayed at all.

**Comment by da1nerd** [comment]
I think this has been corrected in the latest code.

**Comment by cckozie** [comment]
1.1.0 (3e1d1ee) 
The project named alert is not being displayed when projects are imported.
The alert is only being displayed when a project is actually renamed because of editing project details.

**Comment by da1nerd** [comment]
I see. You **want** the renamed alert to be displayed after the initial import no matter what. And it's currently only being displayed after an explicit rename. Is that right?

**Comment by da1nerd** [comment]
During import if a project has been been renamed display the alert.
This is basically always true for usfm imports and some times true for projects.

**Comment by PhotoNomad0** [comment]
Verified in https://tc-builds.door43.org/build/develop/translationCore-macos-x64-1.1.0-326e9df.dmg

**Comment by cckozie** [comment]
Works in 1.1.0 (326e9df)
