### ISSUE TITLE
VerseEdits.csv has some extra data and some wrong data

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5623]
1.1.0 (2ba28f8) 
1. When the edit is performed in the tW expanded scripture pane, the following fields should be populated by the data from the current check, not the verse being edited (unless they are the same verse): 
activeBook, activeChapter, activeVerse, gateway Language Quote, groupId, groupName, occurrence, quote

2. When the edit is performed in wA, the following fields should be populated with 'N/A'. (Or should this be localizable?)
gateway Language Quote, groupId, groupName,	occurrence, quote

3. When the edit is performed external to tC, all of the fields listed in 1. and 2., as well as the tags and gateway Language Code should be populated with 'N/A'.

**Comment by RoyalSix** [comment]
@cckozie Should I keep the `tool` field as `[External Edit]` like it says here #5378 or should I change it to `N/A`

**Comment by cckozie** [comment]
@RoyalSix Leave it as [External Edit]. I'll change the comment above.

**Comment by cckozie** [comment]
Works in 1.1.0 (442929d)
