### ISSUE TITLE
Problems with reset alignments in projects with missing verses

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5630]
1.1.0 (773355b) 
I put the critical tag on it because this problem has broken a lot of my scripts.
[en_act.T.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/2713153/en_act.T.usfm.zip)

Issue 1:
1. Import the attached project and note that the alignment reset alert is not displayed during project validation (DO NOT LOAD THE PROJECT IN A TOOL). 
2. Return to the projects page
3. Select a different project
4. Return to the projects page
5. Select the imported project. Note that the alignments reset alert is now displayed.
6. Load the project in wA
7. Scroll to verse 19:41 and note that it does display the broken link icon.

Issue 2:
1. Restart tC
2. Import the attached project giving it a different translation id.
3. After the project validation is complete, load the project in wA.
I have seen two different scenarios at this point:
Scenario A:
The project loads to an empty screen.
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/5934bf52-1cab-4a9e-89f3-82c90a79e0b3)
Scenario B:(if the project actually loads)
4. Scroll to and select verse 19:41 and note that the broken link icon is NOT displayed.
5. The app appears to hang for several seconds. When it is again active, all of the verses in Chapter 19 show the broken link icon.

**Comment by PhotoNomad0** [comment]
@cckozie - testing with the latest develop build https://tc-builds.door43.org/build/develop/translationCore-macos-x64-1.1.0-b287d3d.dmg:
Both issues now seem to be fixed already.

**Comment by cckozie** [comment]
Issue #2 has been fixed in 1.1.0 (b287d3d).
There is still a problem related to issue #1. (Should this actually be in #5598?
 The reset alignments are still handled differently when the project is imported and immediately loaded vs when it is selected and then loaded starting on the projects page.
Also, although the wA tool card shows 2 reset alignments, I can only find one in the project. That one is at verse 19:41, the missing verse. 
When the project is imported, the reset alignments alert is displayed at the end of the validation process, but the wA tool card shows 0 broken links.
![image](https://user-images.githubusercontent.com/8171759/50600837-025ca080-0e78-11e9-924a-29e791f31854.png)

After returning to the projects page and selecting a different project, then going back to the projects page and selecting the imported project, the tool card now shows 2 broken links.
![image](https://user-images.githubusercontent.com/8171759/50600973-6aab8200-0e78-11e9-8c1d-902405b49830.png)

**Comment by cckozie** [comment]
I moved the issue #1 problems to #4672
