### ISSUE TITLE
Project Opens To Blank Screen

### ISSUE THREAD

**Issue by RoyalSix** [unfoldingWord/translationCore#5632]
### Prerequisites

* Put an X between the brackets on this line if you have done all of the following:

- [x] I have searched the [issues](https://github.com/unfoldingWord-dev/translationCore/issues) of this repository and believe that this is not a duplicate.

### Description
The following  [usfm](https://github.com/unfoldingWord-dev/translationCore/files/2712535/57-TIT.usfm.zip) project does not open

### Steps to Reproduce

1. Download / unzip the project
2. Select it
3. Open with all categories selected

**Screenshots**
<img width="1280" alt="screen shot 2018-12-27 at 5 43 51 am" src="https://user-images.githubusercontent.com/16184018/50482213-6c69d700-099a-11e9-8a00-e89d3b25992a.png">

### Context
Note: This only happens on the first time loading the usfm project.

**Enviorment**
| Tech         | Version |
|--------------|---------|
| tc           | v0.?.?  |
| build #      | 808e7b5 |
| OS           |  OSX     |

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by RoyalSix** [comment]
I think I found this cause of this issue.
Not sure why it wasn't showing in the past. But basically, I traced it down to simply the tool not rendering.

It doesn't even enter the component will mount. This section is returning false when I believe it should be returning true https://github.com/translationCoreApps/tc-tool/pull/20

@neutrinog

**Comment by da1nerd** [comment]
ok I discovered the root of the bugs. There are 2.

1. the new method to open projects is not being called during an import
2. there was a bug in one of the reducers.

**Comment by da1nerd** [comment]
This has been fixed in https://github.com/unfoldingWord-dev/translationCore/pull/5612
