### ISSUE TITLE
tC should not consider missing verses as having reset alignments

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5640]
1.1.0 (b287d3d) 
[en_act.T.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/2721619/en_act.T.usfm.zip)

Verse 19:41 is missing in the attached project. tC is counting that as a reset alignment and displays the broken link icon by it in wA.

**Comment by PhotoNomad0** [comment]
Verified in develop build translationCore 2.1.0 (ed1c32c)

**Comment by cckozie** [comment]
Not seeing the problem in 2.1.0 (ed1c32c)

**Comment by elsylambert** [comment]
Looks good in 2.1.0 (ed1c32c)
