### ISSUE TITLE
When doing USFM import, no longer get project renamed dialog after import

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#5647]
### User Story

Import a USFM file that does not have name matching spec, and user does not get warning dialog that project was renamed.
 
https://tc-builds.door43.org/build/develop/translationCore-macos-x64-1.1.0-ac75c11.dmg

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by da1nerd** [comment]
@PhotoNomad0 can you attach a sample usfm file?

**Comment by elsylambert** [comment]
Retested on 2.0.0 (ca6c273). Not seeing this issue.
