### ISSUE TITLE
tC hangs when importing "bad" projects from Door43

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5649]
1.1.0 (ac75c11)
This has been broken since the release of 1.0.2
Try to import from https://git.door43.org/richmahn/en_tn_mat.git and https://git.door43.org/uday/en_tw.git
App hangs. Nothing in the console.

**Comment by benjore** [comment]
- [ ] Needs to have a useful message.

**Comment by cckozie** [comment]
1.2.0 (b485978) 
App no longer hangs, but error message is not correct. Added the project links to #5691.
