### ISSUE TITLE
Remove "(Part 1)" from the "tW tool"

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5652]
### User Story

As a [type of user], I want [some goal] so that [some reason].

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by PhotoNomad0** [comment]
Verified in https://tc-builds.door43.org/build/develop/translationCore-macos-x64-1.1.0-7c2a84b.dmg

**Comment by cckozie** [comment]
Works in 1.1.0 (7c2a84b)
