### ISSUE TITLE
Checkmark is not cleared in tW when selections are reset because of verse edits

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5654]
1. Open a project in tW
2. Make a selection in any verse
3. Save the selection
4. Edit the verse in such as was as to invalidate the selection
5. Save the edit
6. Notice the the selections no longer valid alert is displayed, but that the checkmark on the check is not removed, and both the checkmark and the edit icon are displayed when hovering on the verse.

The problem gets fixed when the tool is reloaded.

**Comment by benjore** [comment]
May be fixed when the menu in #4443 is brought into tW. (#5688)

**Comment by cckozie** [comment]
This is mostly fixed in 1.1.1 (f6a4c6b) 
The remaining problem of the edit icon not being shown on the verse when it was edited in the expanded scripture pane while another check was active will be fixed in #5776.
