### ISSUE TITLE
"Unlocked Insecure Open Stuff" popup displayed when hovering on the project name in the menu bars

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5656]
1.1.0 (3e1d1ee) 
Happens on both the stepper bar and menu bar
![image](https://user-images.githubusercontent.com/8171759/50979842-fa76af00-14bc-11e9-9abd-ddb060091b54.png)

**Comment by cckozie** [comment]
Does not show in 1.1.0 (b47c7fb)

**Comment by richmahn** [comment]
@cckozie You had a project opened that is actually titled “Unlocked Insecure Open Stuff” (“id”:“algn”,“name”:“Unlocked Insecure Open Stuff”, https://git.door43.org/tc01/aig_algn_gal_book/src/branch/master/manifest.json). What should it say instead with a mouse over?

**Comment by richmahn** [comment]
Moved to "In QA" as I assume you thought this text was coming from some code rather than the project's name.

**Comment by cckozie** [comment]
Rich is right. It is the project's nickname. (Project came from  McLean's repo
