### ISSUE TITLE
Deselect Project when project details edited

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5657]
### User Story

As a user, I want a project that has been selected and then the project details are edited to be deselected so that tC doesn't get confused.

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by PhotoNomad0** [comment]
Verified in https://tc-builds.door43.org/build/release-v1.1.1/translationCore-macos-x64-1.1.1-000d36b.dmg

**Comment by cckozie** [comment]
Works in 1.1.1 (2c1a054)
