### ISSUE TITLE
Change non-standard colors to standard colors

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5669]
1.1.0 (326e9df) 
![image](https://user-images.githubusercontent.com/8171759/51194583-f37ee080-18b0-11e9-80b5-8c2c0cfd132a.png)

- [x] Toggle should be the tC dark blue **Fixed in 1.2.0 (3ae9fb5)**

![image](https://user-images.githubusercontent.com/13352518/56607737-de5fcf00-65ce-11e9-9647-8ceb19941368.png)
- [x] The `1` and `2` circles should be dark blue **Fixed in 1.2.0 (3ae9fb5)**
- [x] The checkboxes should be dark blue also **Fixed in 1.2.0 (3ae9fb5)**

![image](https://user-images.githubusercontent.com/13352518/56607837-123af480-65cf-11e9-86e4-bd3eecfee2c0.png)
- [x] Verify that the checkboxes are dark blue **Fixed in 1.2.0 (3ae9fb5)**

![image](https://user-images.githubusercontent.com/13352518/56607897-31d21d00-65cf-11e9-8a28-f877bc59a442.png)
- [x] light blue should be dark blue **Fixed in 1.2.0 (3ae9fb5)**

![image](https://user-images.githubusercontent.com/13352518/56818732-e194ce00-680d-11e9-8d8b-dec581d258f0.png)
- [x] Change the blue in the circular progress indicators in the side menu to the same green as the checkmark **Fixed in 1.2.0 (3ae9fb5)**

**Comment by cckozie** [comment]
All noted problems are fixed in 1.2.0 (3ae9fb5)

**Comment by elsylambert** [comment]
Verified in 1.2.0 (3ae9fb5). All the mentioned button/checkboxes are are in dark blue as excepted.
