### ISSUE TITLE
Verse Edit Box Height Flex

### ISSUE THREAD

**Issue by RoyalSix** [unfoldingWord/translationCore#5670]
### Prerequisites

* Put an X between the brackets on this line if you have done all of the following:

- [X] I have searched the [issues](https://github.com/unfoldingWord-dev/translationCore/issues) of this repository and believe that this is not a duplicate.

### Description
Verse Edit Box does not expand vertically correctly

### Steps to Reproduce

1. Open tC
2. Go to any project
3. Open tW, and edit a verse
4. Adjust the vertical height of tC to the smallest it can be. 
5. Note the verse edit panel is unually small

**Screenshots**

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

### Context

**Enviorment**
| Tech         | Version |
|--------------|---------|
| tc           | v0.?.?  |
| build #      |         |
| OS           |         |

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by cckozie** [comment]
2.0.0 (ca6c273) 
This is ok now. On my Mac full screen there are 6 lines viewable in the edit box. With the window minimized there are now 5 lines viewable in the edit box.
