### ISSUE TITLE
tW Group Scroll Not Working After First Open

### ISSUE THREAD

**Issue by RoyalSix** [unfoldingWord/translationCore#5671]
### Prerequisites

* Put an X between the brackets on this line if you have done all of the following:

- [X] I have searched the [issues](https://github.com/unfoldingWord-dev/translationCore/issues) of this repository and believe that this is not a duplicate.

### Description
After opening tW the previous group menu item is scrolled to but after selecting another check it no longer scrolls

### Steps to Reproduce

1. Open tW
2. Click on a check from the menu
3. Note the check does not get scrolled to

**Screenshots**

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

### Context

**Enviorment**
| Tech         | Version |
|--------------|---------|
| tc           | v0.1.1  |
| build #      |  1034612  |
| OS           |   OSX   |

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by cckozie** [comment]
Not a problem in 2.0.0 (ca6c273)
