### ISSUE TITLE
Selection effects the display of the target language in the Scripture Pane

### ISSUE THREAD

**Issue by bspidel** [unfoldingWord/translationCore#5675]
### Prerequisites

* Put an X between the brackets on this line if you have done all of the following:

- [x] I have searched the [issues](https://github.com/unfoldingWord-dev/translationCore/issues) of this repository and believe that this is not a duplicate.

### Description
When adding or clearing selections, the visibility of the target language in the scripture pane toggles on and off.

### Steps to Reproduce

1. Go to 'translationWords'
2. Click on 'a verse check' without a selection
3. Make selection and save it
4. Note that target language disappears from scripture pane
5. Clear the selection
6. Note that the target language reappears in scripture pane

If a selection already exists then target language disappears from scripture pane.
Pane toggles on and off as you traverse from verse check to verse check with and without selections

**Screenshots**

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

### Context

**Enviorment**
| Tech         | Version |
|--------------|---------|
| tc           | v1.1.0  |
| build #      |  773355b       |
| OS           |   Win10      |

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by da1nerd** [comment]
Some additional notes. Here's a diff between the previous commit https://github.com/unfoldingWord-dev/translationCore/commit/bca11e182620b31be29422355afbfa4deeb98961 and the commit with the error https://github.com/unfoldingWord-dev/translationCore/commit/773355bd149682a586cd562249244a74e47b0c1f (the very next commit)

Here's the file diff

```
.compilerc
__tests__/UsfmFileConversionHelpers.test.js
package-lock.json
package.json
src/js/actions/MyProjects/ProjectLoadingActions.js
src/js/actions/USFMExportActions.js
src/js/helpers/FileConversionHelpers/UsfmFileConversionHelpers.js
```

**Comment by da1nerd** [comment]
@bspidel @PhotoNomad0 fyi I could not reproduce this error on linux. Running the latest commit on develop with a fresh node_modules and the latest version of the tools.

**Comment by PhotoNomad0** [comment]
Verified in https://tc-builds.door43.org/build/release-v1.1.0/translationCore-macos-x64-1.1.0-91c4488.dmg

**Comment by cckozie** [comment]
Works in 1.1.0 (63dffc7)
