### ISSUE TITLE
See Problem that Scripture Pane in wA shows last selection made in tW

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#5678]
## Additional Context

see in https://tc-builds.door43.org/build/release-v1.1.0/translationCore-macos-x64-1.1.0-91c4488.dmg

![Screen Shot 2019-01-16 at 11.34.04 AM.png](https://images.zenhubusercontent.com/564e463c638e718c995eb353/47feb0cd-a48b-4756-921f-b4417a7917b6)

**Comment by PhotoNomad0** [comment]
Looks like this was fixed in https://github.com/unfoldingWord-dev/translationCore/pull/5682

**Comment by cckozie** [comment]
Works in 1.1.0 (63dffc7)
