### ISSUE TITLE
Chapter does not open when clicked on in wA menu

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5680]
1.1.0 (91c4488)
Open a project in wA
Close the selected chapter
Click on a different chapter. Note that the chapter does not open to display the verses.
The only way to open the chapter now is to click on the > symbol (twice is the target chapter is not selected)
![image](https://user-images.githubusercontent.com/8171759/51264466-2c37bc00-197c-11e9-9448-72ecea3927a5.png)

**Comment by PhotoNomad0** [comment]
Fixed by @richmahn in https://github.com/unfoldingWord-dev/translationCore/pull/5682

**Comment by cckozie** [comment]
Works in 1.1.0 (63dffc7)
