### ISSUE TITLE
Verbiage Update: what books are supported

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5681]
### User Story

As a [type of user], I want [some goal] so that [some reason].

### Features / Specifications

![image.png](https://images.zenhubusercontent.com/55e5f3984f7a08fbb7f4a658/88f20cff-d8df-4dc7-bac2-74e465483fd4)
![image.png](https://images.zenhubusercontent.com/55e5f3984f7a08fbb7f4a658/aecf317b-e73f-4ec2-af8a-51f3eacbb11d)
- [ ] "In this version of translationCore, the translationWords tool and the Word Alignment tool support New Testament projects." Should now read, "In this version of translationCore, the translationWords tool supports projects from the New Testament and the Word Alignment tool supports projects from the whole Bible."
- [ ] Change verbiage on the Online Import page and the 
- [ ] Change verbiage on the Tool Page of the startup stepper

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by cckozie** [comment]
Fixed in 1.1.1 (f6a4c6b)
