### ISSUE TITLE
Greek Showing In Selection Pane Instead Of GL

### ISSUE THREAD

**Issue by RoyalSix** [unfoldingWord/translationCore#5684]
### Prerequisites

* Put an X between the brackets on this line if you have done all of the following:

- [X] I have searched the [issues](https://github.com/unfoldingWord-dev/translationCore/issues) of this repository and believe that this is not a duplicate.

### Description
The greek word is being displayed instead of the GL word in the selection instructions.
i.e. `Please select the translation for: {greek word}` ** Hindi GL selected **

### Steps to Reproduce

1. Open tC
2. When at the tools page select Hindi as the gateway language
3. Note the selection pane instructions on the right side. The blue bold word is not correct

**Screenshots**
![image](https://user-images.githubusercontent.com/16184018/51271117-c4c54080-196a-11e9-84a3-a9870546b1c0.png)

**Expected behavior:** Whatever GL has been selected in the Tool Card dropdown should ALWAYS be the language that shows in the check card (the only exception is if there is missing data in the GL, then there is a fall-back to the Original Language). Whether the GL shows in the Scripture Pane or has been removed should be immaterial. 

**Actual behavior:** When the GL is removed from the Scripture Pane, the GL effectively changes to Greek. 

### Context

**Enviorment**
| Tech         | Version |
|--------------|---------|
| tc           | v1.1.0  |
| build #      |  63dffc7 |
| OS           |   OSX  |

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by cckozie** [comment]
Fixed in 1.1.1 (f6a4c6b)
