### ISSUE TITLE
App indicates reset alignments when edits are done that do not actually affect alignments

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5685]
1.1.0 (1034612)

App indicates reset alignments when edits are done that do not actually affect alignments
1. Import https://git.door43.org/qa99/en_full_tit_book
2. Load the project in wA
3. Unalign some of the words as shown here:
![image](https://user-images.githubusercontent.com/8171759/51210178-bbd75f00-18d7-11e9-9251-05be8cc4e723.png)
4. Load the project in tW
5. In verse 1:1 under 'apostle', change the text "an apostle" to "the apostle", give it a reason, then Save
6. Note that the 'some selections no longer valid' alert is displayed
7. Note that when that alert is dismissed, the invalidated alignments alert is incorrectly displayed.
8. Return to the tools page and note that the wA tool card incorrectly indicates that there is one broken alignment.

**Comment by cckozie** [comment]
I've confirmed that wA is inaccurately indicating alignments have changed due to the propagating effect of word occurrences.
e.g. Since there were other `the`s aligned in the verse their occurrence number changed which invalidated the alignment.

Resolving this is tricky because we need to make sure that rearranging words still causes an invalidation. Instead of doing a straight diff on the two alignment versions I think we can solve this by
1. performing a textual comparison of the alignments
2. performing a relative position comparison of the alignments.

**Comment by PhotoNomad0** [comment]
Verified in https://tc-builds.door43.org/build/release-v1.1.1/translationCore-macos-x64-1.1.1-000d36b.dmg that we no longer get the alignment changed message when "an" is changed to "the".

**Comment by cckozie** [comment]
1.1.1 (2c1a054)
The problem describe in the first comment has been fixed, but now the reset alignments alert is not displayed when the alignment is then again broken.
To test:
1. Follow steps 1 - 8 above
2. Load the project in wA
3. Align the words as shown here:
![image](https://user-images.githubusercontent.com/8171759/52595317-3b8f1580-2e13-11e9-8023-250d25a2d034.png)
4. Load the project in tW
5. In verse 1:1 under 'apostle', change the text "the apostle" to "an apostle", give it a reason, then Save
6. Notice that the reset alignments alert is NOT displayed
7. Go to the tools page and notice that it indicates 1 broken alignment

**Comment by da1nerd** [comment]
@cckozie I just tested this with the latest 1.1.3 code and the reset alignments dialog is being displayed correctly.

**Comment by cckozie** [comment]
Works in 1.1.1 (2c1a054) - really 1.1.3
