### ISSUE TITLE
Source Content Update Downloads Fail Frequently

### ISSUE THREAD

**Issue by bspidel** [unfoldingWord/translationCore#5689]
- [x] Stop the frequent download failures
- [ ] Optimize the process to improve time to update content. 

Related to #4998

### Prerequisites

* Put an X between the brackets on this line if you have done all of the following:

- [x] I have searched the [issues](https://github.com/unfoldingWord-dev/translationCore/issues) of this repository and believe that this is not a duplicate.

### Description

Selected all resources to download. Failed after downloading about 10 resources
Repeated 3 times with same behavior. Each time, list of resources got shorter
On 5th download of a handful of resources after about 5 minutes there were no more folders being created but download alert was still spinning.
Stopped after about 20 minutes.

### Steps to Reproduce

1. Go to 'Action -> Check for Content Updates'
2. Click on 'All'
3. Click 'Download'
4. Repeat till hang or no resources to download

- Downloaded 769 mb of resources less initial installation

- After restart, update claimed there were 2 remaining resources plt and tl.
another update completed successfully. Now, no more resources to update.

**Screenshots**

**Expected behavior:** [What you expect to happen]

Expected that single update would have downloaded all resources

**Actual behavior:** [What actually happens]

Took 6 tries and a restart to complete.

### Context

**Enviorment**
| Tech         | Version |
|--------------|---------|
| tc           | v1.1.0  |
| build #      | 63dffc7        |
| OS           |  Win 10       |

### Additional Information

Here is console before killing process
https://gist.github.com/f22c3b804a63be485d8caf3609b42b6f

**Comment by PhotoNomad0** [comment]
@benjore @cckozie - seems to be frequent socket timeouts.  Suspect this is related to updating packages used as suggested by dependabot since this now is happening frequently on good connections.

**Comment by mannycolon** [comment]
@PhotoNomad0 How is dependabot related to this issue?

**Comment by RoyalSix** [comment]
https://tc-builds.door43.org/build/develop/translationCore-macos-x64-1.2.0-cf77eea.dmg

**Comment by elsylambert** [comment]
Not seeing any issue in 1.2.0 (9f6a878). Able to download all source content successfully.

**Comment by cckozie** [comment]
1.2.0 (9f6a878)
Attempted download of en, es-419, and fr. Download failed. 70 Mbit connection.
Retry failed as well.
![image](https://user-images.githubusercontent.com/8171759/61305435-70333e80-a7b0-11e9-8096-9bcf9f6d4b11.png)

**Comment by RoyalSix** [comment]
Note: This is an issue with a missing parameter

**Comment by cckozie** [comment]
Works in 2.0.0 (99b8027). Updated all resources with tool loaded. It took over 7 minutes, but succeeded. Retested on Projects page and resource updates were successful.

**Comment by elsylambert** [comment]
I had downloaded all the source content on July 17, 2019 and thats the date shown in my Resources folder for the Content 17.7.2019. But when I tried to "Check for Content Update", it shows
![image](https://user-images.githubusercontent.com/51806180/61665440-febd2980-aca2-11e9-9915-6fdd25d8309b.png)

On July 17, after I had downloaded all the contents it was showing this message "All content is up-to-date". 

It should still be showing the "All content is up to date" message.
The resources to download list should only show languages that are not on the machine, or those that have been updated since they were put on the machine either through a download or a tC upgrade.

**Comment by RoyalSix** [comment]
@elsylambert I did the following and was not able to recreate the error.
1. Download all resources
2. Check for updates, the alert says `All source content is up to date.`
3. Restart tC
4. Check for updates, the alert says `All source content is up to date`

855642f

**Comment by elsylambert** [comment]
Source Content Update works fine in  2.0.0 (9016823).
Submitted a separate issue for the Resources dates #6281
