### ISSUE TITLE
Alignment completions are not maintained in USFM3 exports

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5692]
1.1.0 (63dffc7) 
When fully aligned USFM3 projects are imported, tC indicates 0% complete. On the Home page it indicates 100%.
This is a change from 1.0.2 where it indicated 100% on both the tool card and Home page. A project that shows 100% on the wA card in 1.0.2 shows 0% on the wA card after upgrading to 1.1.0.
The Alignment complete status is not maintained in USFM3 files.
1. Import this project https://git.door43.org/tc02/en_ovwr_tit_book
2. Note that the wA tool card indicates 100% complete
3. Export the project to USFM including alignments
4. Reimport the exported project giving it a different translation id
5. Note that the wA tool card indicates 0% complete
6. Load the project in wA
7. Note that all verses are fully aligned, but the Alignment complete switch is in the off position on all verses

**Comment by cckozie** [comment]
1.1.1 (f6a4c6b) 
@benjore - This seems like a partial solution. Is it acceptable for 1.1.1?
After importing the exported USFM 3 file, the tool card now shows 100% complete.
However, when the project is loaded in wA, there are no checkmarks on the verses, no completions shown in the circle on the verse tile, and the Alignment complete switch is not set. In the original project imported from Door43, all three indicators (checkmark, circle, and Alignment complete switch) were set.

**Comment by benjore** [comment]
This is, in essence, lost data. Correct me if I'm wrong, but if we get the "Alignment complete" toggles  to persist, then we get the checkmarks & circles for free, right? 

Assumption: that this data has been (and can be) captured in the USFM3 spec.

**Comment by cckozie** [comment]
The % complete indicated on the wA card is now 100% after the import, as it should be.
However, when loaded in wA the problem listed as #7 above still exists. After the project is imported from USFM3, it should look identical to what was in the project exported; i.e. all of the checkmarks should be shown and the Alignment complete switch should be On on all of the verses.

**Comment by cckozie** [comment]
Works in 1.1.3 (240da43)
