### ISSUE TITLE
No localization for checkbox labels on translationWords tool card.

### ISSUE THREAD

**Issue by bspidel** [unfoldingWord/translationCore#5696]
### Prerequisites

* Put an X between the brackets on this line if you have done all of the following:

- [x] I have searched the [issues](https://github.com/unfoldingWord-dev/translationCore/issues) of this repository and believe that this is not a duplicate.

### Description

TranslationWords tool card has some missing localization. Namely
- Key Terms
- Other Terms
- Names

### Steps to Reproduce

1. Change locale to HI
2. Navigate to tool page
3. Verify checkbox labels are Hindi

**Screenshots**

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

### Context

**Enviorment**
| Tech         | Version |
|--------------|---------|
| tc           | v1.1.0  |
| build #      | 63dffc7        |
| OS           |  Win 10       |

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by benjore** [comment]
dup of #5756
