### ISSUE TITLE
After importing self-owned repo then changing the tid, tC does not offer to rename door43 version

### ISSUE THREAD

**Issue by bspidel** [unfoldingWord/translationCore#5702]
### Prerequisites

* Put an X between the brackets on this line if you have done all of the following:

- [x] I have searched the [issues](https://github.com/unfoldingWord-dev/translationCore/issues) of this repository and believe that this is not a duplicate.

### Description

Renaming imported self owned project does not offer to rename repo on door43 
Similar to #5532 This problem does not show error.

### Steps to Reproduce

1. Import an online project that you own (ne_ulb_luk_book)
2. After import, edit project details, change the translation id to ulbb
3. Click "Save Changes"

Note does not offer to rename online repo

**Screenshots**
Console.log

Migration error: Error: ENOENT: no such file or directory, scandir 'C:\Users\Owner\translationCore\imports\ne_bob_luk_book\.apps\translationCore\checkData\verseEdits\luk'
ProjectDetailsActions.js:392 no old selected project File Name
2ProjectLoadingActions.js:177 DEPRECATED: toolsReducer is deprecated.
get toolsReducer @ ProjectLoadingActions.js:177
generate @ C:\Program Files (x86)\translationCore\resources\app.asar\node_modules\tc-tool\dist\connectTool\makeProps.js:74
makeToolProps @ C:\Program Files (x86)\translationCore\resources\app.asar\node_modules\tc-tool\dist\connectTool\makeProps.js:34
_preprocessProps @ C:\Program Files (x86)\translationCore\resources\app.asar\node_modules\tc-tool\dist\api\ApiController.js:138
_triggerMapToProps @ C:\Program Files (x86)\translationCore\resources\app.asar\node_modules\tc-tool\dist\api\ApiController.js:196
triggerWillConnect @ C:\Program Files (x86)\translationCore\resources\app.asar\node_modules\tc-tool\dist\api\ApiController.js:316
_callee$ @ ProjectLoadingActions.js:97
tryCatch @ C:\Program Files (x86)\translationCore\resources\app.asar\node_modules\regenerator-runtime\runtime.js:62
invoke @ C:\Program Files (x86)\translationCore\resources\app.asar\node_modules\regenerator-runtime\runtime.js:296
prototype.(anonymous function) @ C:\Program Files (x86)\translationCore\resources\app.asar\node_modules\regenerator-runtime\runtime.js:114
step @ C:\Program Files (x86)\translationCore\resources\app.asar\node_modules\babel-runtime\helpers\asyncToGenerator.js:17
(anonymous) @ C:\Program Files (x86)\translationCore\resources\app.asar\node_modules\babel-runtime\helpers\asyncToGenerator.js:28
run @ C:\Program Files (x86)\translationCore\resources\app.asar\node_modules\core-js\library\modules\es6.promise.js:75
(anonymous) @ C:\Program Files (x86)\translationCore\resources\app.asar\node_modules\core-js\library\modules\es6.promise.js:92
flush @ C:\Program Files (x86)\translationCore\resources\app.asar\node_modules\core-js\library\modules\_microtask.js:18
_tickCallback @ internal/process/next_tick.js:61

**Expected behavior:** [What you expect to happen]

Expected it to offer to let me rename online repo

**Actual behavior:** [What actually happens]

Just saved renamed repo without changing online version

### Context

**Enviorment**
| Tech         | Version |
|--------------|---------|
| tc           | v1.1.0  |
| build #      | 63dffc7        |
| OS           | Win10        |

### Additional Information
Tried several combinations of rename to existing versions and unique versions.

One time it did ask to rename repo but cannot recall sequence. It was not expected sequence.

**Comment by cckozie** [comment]
Still an issue in 2.0.0 (ca6c273)

**Comment by elsylambert** [comment]
Not an Issue in 2.2.0 (2375ae5).
