### ISSUE TITLE
Upload to Door43 of system renamed file seems confused

### ISSUE THREAD

**Issue by bspidel** [unfoldingWord/translationCore#5703]
### Prerequisites

* Put an X between the brackets on this line if you have done all of the following:

- [x] I have searched the [issues](https://github.com/unfoldingWord-dev/translationCore/issues) of this repository and believe that this is not a duplicate.

### Description
- Having imported a file that was renamed by system, upload of renamed but unchanged repo says the following

- ar_ulb_mat_book cannot be uploaded because there have been changes to the translation of that project on your Door43 account.

### Steps to Reproduce

1. Import a project with non-standard name ar_mat_text_ulb
2. Attempt to upload it to doo43 as ar_ulb_mat_book
3. Note error message

**Screenshots**

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

### Context

**Enviorment**
| Tech         | Version |
|--------------|---------|
| tc           | v1.1.0  |
| build #      | 63dffc7        |
| OS           | Win 10        |

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by elsylambert** [comment]
Retested on 2.0.0 (ca6c273). Not seeing this issue.
