### ISSUE TITLE
The Close button text is not localized on the dialog to add resources to the scripture pane

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5705]
1.1.0 (63dffc7) 
![image](https://user-images.githubusercontent.com/8171759/51499248-1d437600-1d8f-11e9-927d-de91639730ed.png)

**Comment by elsylambert** [comment]
Retested on 2.0.0 (ca6c273). Issue still exists.

**Comment by PhotoNomad0** [comment]
Verified now using locale in dialog to add resources to the scripture pane in translationCore 2.1.0 (6e8eecc) .  The close button looks like it has been localized in most languages, but the load button defaults to English (except for hi which has a preliminary translation)

**Comment by PhotoNomad0** [comment]
Seeing problems with setting locale in tools:

It looks like the "dialog to add resources to the scripture pane" does not consistently remember the latest locale when moving from tool to tool. Have you seen this?

Bruce McLean: If I set the locale from English to Spanish on the projects page and then open tN, then the tool page comes up in English. Then I go to tW and see the tool page come up in Spanish. And then I go to WA and see the group menu chapters in Spanish, but the rest of the tool is English.

**Comment by PhotoNomad0** [comment]
@cckozie - OK, looks like the problems setting locale where pre-existing.  So the PR here fixes the stated problem on the issue - moving into QA:

**Verified in build:** now using locale in dialog to add resources to the scripture pane in **translationCore 2.1.0 (6e8eecc)** . The close button looks like it has been localized in most languages, but the load button defaults to English (except for hi which has a preliminary translation)

**Comment by cckozie** [comment]
The text on the Close button is localized in 2.1.0 (5980326).
