### ISSUE TITLE
Add data to CSV export with additional information

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5708]
(Former title: A column for the tW type (Key terms, Other terms, Names) should be added to the translationWords_CheckInformation.csv and selections.csv files)

Since we allow distinguishing between them in the app, it makes sense to do the same in the related csv files. It also may be important for those who would want to check manually using the spreadsheet.

## Specs 
- [x] tW export 
  - [x] Add `Type` column on tW export. Fill with `Key terms`, `Other terms`, and `Names`
- [x] tN export
  - [x] Add Priority 1 to all checks
  - [x] Add `Type` column, fill with the `Head Category`
  - [x] Add `GL Quote` column
  - [x] Add `Occurrence Note` column

![image](https://user-images.githubusercontent.com/13352518/56748851-2f460380-6746-11e9-93f2-ca3f6604c7cd.png)

**Comment by cckozie** [comment]
1.2.0 (3ae9fb5)
The GLQuote column should be based on the GL alignment rather than what is in the tsv file. 

The highlighted GL quotes in this sample of metaphors in the Titus tsv file are different than the highlighted ULT words for the check, and are thus incorrect.
![image](https://user-images.githubusercontent.com/8171759/60924940-07a40900-a268-11e9-8466-03c835fc4f4a.png)

**Comment by cckozie** [comment]
Looks good in 1.2.0 (9f6a878)
Needs regression

**Comment by elsylambert** [comment]
Verified in 2.0.0 (459884d). Looks good.

**Comment by richmahn** [comment]
@cckozie @benjore This needs to go into QA Fail from my own findings. I realized if you make a comment, reminder or selection in Hindi, which records the Gateway language code and Gateway language quote (hi, and the Hindi Bible selected text), in the CSV export it still shows up as English as I'm ignoring that data from the saved data for the event. I have made a fix already.

**Comment by elsylambert** [comment]
2.0.0 (99b8027). Still seeing "en" in GL Code and GL Quote  column in Comment/Reminders CSV Export for Hindi GL.

**Comment by elsylambert** [comment]
Not seeing any issues in the latest 2.0.0 (40a9095). GL Code and GL Quote are showing up as "hi" for Hindi Projects in Comments/Reminders CSV Export files.

**Comment by cckozie** [comment]
Looks good in 2.0.0 (aff6765)
