### ISSUE TITLE
Lexicon entries are no longer being displayed in OT books

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5714]
Checked multiple OT books in 1.1.0 (63dffc7) and Lexicon entries are all empty
Renamed both translationCore folders, restarted tC, now I see the Lexicon entries
Tried replacing the uhl index.json file with the one from the failing resources folder. Still seeing the Lexicon entries.
Replaced the uhl folder with the one from failing resources, and not the Lexicon entries are not displayed.

**Comment by PhotoNomad0** [comment]
@cckozie - looks like a problem in updating the lexicon to latest packaged in app.

**Comment by PhotoNomad0** [comment]
@cckozie We are bumping the version number of the latest uhl to 0.1 to make it easy to check for the latest.

**Comment by PhotoNomad0** [comment]
Verified in https://tc-builds.door43.org/build/release-v1.1.0/translationCore-macos-x64-1.1.0-130662e.dmg

**Comment by PhotoNomad0** [comment]
2nd try - verified in https://tc-builds.door43.org/build/release-v1.1.0/translationCore-macos-x64-1.1.0-aa16dd2.dmg
