### ISSUE TITLE
Add worksheets to CSV export: 1 with tN check info, 1 with tN selections

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5724]
Model this off of the tW CSV export (translationWords_CheckInformation.csv). 

And translationNotes_Selections.csv

Change the Selections.csv to translationWords_Selections.csv (Add tool name to all CSV exports. 

= = = 

For the `translationNotes_CheckInformation` CSV file: 
- [ ] Change it to `EN_translationNotes_CheckInformation`
- [ ] Fix `groupName` to show the Group Name (instead of `GroupID`)
- [ ] Add column to include the actual translationNote
- [ ] Add column for "Category" (`tN_Categories`?)

**Comment by PhotoNomad0** [comment]
@benjore - Does this look good to you?  Already implemented in develop:

![Screen Shot 2019-04-04 at 9 09 18 AM](https://user-images.githubusercontent.com/14238574/55558171-7c8c0380-56b9-11e9-8809-b823c1a01b4a.png)

**Comment by benjore** [comment]
Looks good to me!

**Comment by mannycolon** [comment]
@PhotoNomad0 did you open the files?

**Comment by PhotoNomad0** [comment]
@mannycolon - opened, but what would I look for?  @benjore  looked at them on his PC.

**Comment by mannycolon** [comment]
@PhotoNomad0 Don't we need both comments/reminders/selections files for both tools?

**Comment by mannycolon** [comment]
The group index could be used in order to get the group name off of the group id

**Comment by benjore** [comment]
Superceded by #5708
