### ISSUE TITLE
Resources select list does not include all available resources

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5725]
1.1.0 (aa16dd2) 
The resources displayed seems to be dependent on the project. In the 2co project only one of the Hindi Bibles is shown as an option. Happens on both Windows and OSX. Unfortunately I'm not sure of the origin of the project. 

[projects.zip](https://github.com/unfoldingWord-dev/translationCore/files/2789602/projects.zip)

![image](https://user-images.githubusercontent.com/8171759/51644693-b9f44800-1f36-11e9-996c-cd576c549b81.png)

![select2co.PNG](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/80934923-f8c6-4e35-8a50-bdfb11938b33)

![selecttit.PNG](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/81b57ed6-9717-490c-af8f-9a997df81c50)

**Comment by benjore** [comment]
The IRV is only available for Titus, James & Ephesians. Could this be the source of the problem?

**Comment by cckozie** [comment]
User (tester error). The resources not showing are not available.
