### ISSUE TITLE
Cannot edit verses in OT books. (ERROR displayed)

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5726]
1.1.0 (aa16dd2) 
![image](https://user-images.githubusercontent.com/8171759/51645421-bf9f5d00-1f39-11e9-98cb-28af2c2ae2d7.png)
Load an OT project in wA and open the expanded scripture pane.

**Comment by RoyalSix** [comment]
I think this got fixed in 26fdc79. 
I was able to reproduce in the aa16dd2 but not the latest build for develop `1.1.0`

**Comment by cckozie** [comment]
@RoyalSix This needs to be fixed in 1.1.0.  aa16dd2 is the latest build on the 1.1.0 release branch.

**Comment by PhotoNomad0** [comment]
@RoyalSix @cckozie - I can verify this is broken in v1.1.0.

**Comment by PhotoNomad0** [comment]
@RoyalSix @cckozie @mannycolon - I think I found the problem - it only occurs when ult is not loaded into scripture pane.  There is a hard coded reference to the ult in tc-ui-toolkit ChapterView/index.js:

```
    const verseNumbers = Object.keys(bibles['en']['ult'][chapter]);
```

**Comment by PhotoNomad0** [comment]
Verified in https://tc-builds.door43.org/build/release-v1.1.0/translationCore-macos-x64-1.1.0-92d743b.dmg
