### ISSUE TITLE
Make verse edit modal draggable

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5737]
### User Story

As a [type of user], I want [some goal] so that [some reason].

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by mannycolon** [comment]
See: https://material-ui.com/demos/dialogs/#draggable-dialog

**Comment by benjore** [comment]
Related to #5868

**Comment by mannycolon** [comment]
Verified on b50f3ec

**Comment by cckozie** [comment]
The edit modal is draggable, but the user should not be able to drag it out of the main tC window. Currently I am able to drag it off the top of the screen where it cannot be grabbed, and completely out of the window where it cannot be seen and there is no obvious way to get it back. At that point the user is not able to do anything in tC other than close it.
Similar problem noted on #5868.


![image](https://user-images.githubusercontent.com/8171759/60286061-957d0d00-98d4-11e9-8d53-6223fdc4240a.png)



![image](https://user-images.githubusercontent.com/8171759/60286009-79796b80-98d4-11e9-80e5-cee1fc86eaaf.png)

**Comment by cckozie** [comment]
1.2.0 (3ae9fb5)
I am able to drag the edit modal completely off the bottom of the screen.
Per @benjore  that is acceptable behavior.

**Comment by elsylambert** [comment]
Verified in 1.2.0 (05888d5). Verse edit window is draggable and working fine.
