### ISSUE TITLE
Text sometimes flows off the end of the word bank cards (and is inconsistent with the same text dependent on presence of the scroll bar)

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5749]
![image](https://user-images.githubusercontent.com/8171759/52145484-af1c7000-2626-11e9-8af8-9e6b2256de84.png)
-------------------
![image](https://user-images.githubusercontent.com/8171759/52145510-c4919a00-2626-11e9-9690-9c5b3bd0df10.png)

**Comment by benjore** [comment]
Dup of #5440
