### ISSUE TITLE
App breaks when attempting to load a tool after editing project details

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5751]
1.1.0 (92d743b)
1. Restart tC
2. Open the 3-dot menu for any project
3. Choose the Edit Project Details option
4. Add/change project nickname (or make some other change)
5. Save the changes
6. Click on the Tool link in the stepper bar
7. Click the Load button on either tool
8. Note that there is a problem in the tool as displayed below
![image](https://user-images.githubusercontent.com/8171759/52150099-88fdcc80-2634-11e9-9fbf-9f63b109a0a2.png)

**Comment by benjore** [comment]
I think this was fixed in 1.1.3 when we deselected the project after changing project details.

**Comment by cckozie** [comment]
Works correctly in 1.2.0 (b485978)
