### ISSUE TITLE
Parsing the TSV and generating the GroupIndex and GroupData (NPM Module)

### ISSUE THREAD

**Issue by RoyalSix** [unfoldingWord/translationCore#5752]
## Specs
- [ ] Mock data structure: https://docs.google.com/spreadsheets/d/1NMIfdundjjRHo3EknFPLO6to2acQYvm6NL8uXU_0tmQ/edit#gid=495123398 
- [ ] More commentary: https://forum.ccbt.bible/t/translationnotes-tsv-format/57
- [ ] Parsing will occur during source content updater download
- [ ] End result should look similar to https://github.com/translationCoreApps/tC_Resources/tree/master/resources/en/translationHelps/translationNotes/v0
- [ ] En tN TSVs: https://git.door43.org/unfoldingWord/en_tn

**Comment by mannycolon** [comment]
`Tested on build:` Develop (v1.2.0 b7082bf)

**Comment by mannycolon** [comment]
May not be testable until tN is available. However, the data can be downloaded and found in `translationCore/resources/en/translationHelps/translationNotes`

**Comment by cckozie** [comment]
1.2.0 (b7082bf) 
The data is there as noted above.
