### ISSUE TITLE
Create the initial tN tool - tW tool with tN data (for testing SPIKES)

### ISSUE THREAD

**Issue by RoyalSix** [unfoldingWord/translationCore#5753]
- Load data into the tool
- Use fake data. In issue.
Basically same as tW data except for note field, and toolName is translationNotes

**Comment by RoyalSix** [comment]
In order to get the tool to load I did the following.
Copied translationWords alignment data (check information also called the groupsData in tC) from `grc/translationHelps/translationWords` to the same location except for under a new folder `translationNotes`
Copied translationWords markdown files from `en/translationHelps/translationWords` to 
the same location except under a new folder `translatinNotes`

I copied the entire tW tool into an new folder under tC_apps under `translationNotes`

I also changed the namespace in the connect tool api location in translationNotes app folder in the `index.js`

Also under `src/js/helpers/gatewayLanguageHelpers.js` 
I removed some commented out text
<img width="979" alt="screen shot 2019-02-04 at 4 56 18 pm" src="https://user-images.githubusercontent.com/16184018/52247204-d0d35c80-289d-11e9-855c-a3271580f987.png">

I also had to rename all the groupsData checks under `grc/translationHelps/translationNotes` from `tool: translationWords` to `tool: translationNotes` in the contextIds

**Comment by RoyalSix** [comment]
https://tc-builds.door43.org/build/develop/translationCore-macos-x64-1.2.0-45fa8a2.dmg

**Comment by cckozie** [comment]
1.2.0 (b7e490a) 
It fundamentally works.
