### ISSUE TITLE
Use filesystem to handle parent and child categories for the tN tool card (include the hover-over description) - for each GL

### ISSUE THREAD

**Issue by RoyalSix** [unfoldingWord/translationCore#5755]
![image](https://user-images.githubusercontent.com/16184018/52006945-59678c80-249b-11e9-8419-54385cd2761f.png)
![image](https://user-images.githubusercontent.com/13352518/48024449-47798600-e106-11e8-84c0-e354480352cd.png)
![image](https://camo.githubusercontent.com/0ad120a1699d3076fbb174a04c309782063e50ac/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3535653566333938346637613038666262376634613635382f61323333323436342d373038302d346363642d393432362d383636313363393638663664)

**Comment by cckozie** [comment]
1.2.0 (de171a2) 

ISSUE 1:
The subcategory descriptions should appear when a user hovers over the subcategory's title rather than when the user clicks on the title.

ISSUE 2:
"Bad text" and formatting in some hover-over descriptions. Here are a couple examples:
![image](https://user-images.githubusercontent.com/8171759/56811166-bd30f580-67fd-11e9-991e-c804e4720a13.png)
![image](https://user-images.githubusercontent.com/8171759/56812380-5fea7380-6800-11e9-971d-08570bdb32f5.png)

**Comment by PhotoNomad0** [comment]
@cckozie - it looks like the popups are showing the markdown text, rather than the formatted text.

**Comment by PhotoNomad0** [comment]
@benjore - In looking at https://github.com/unfoldingWord-dev/translationCore/issues/2009, was the intent to just show the first Paragraph of the article as the hint?

**Comment by PhotoNomad0** [comment]
@benjore @cckozie - here are a couple of examples for review using our standard Hints.  Also tweaked it to remove some more of the markdown in the helps.  Is this acceptable?

![Screen Shot 2019-04-30 at 7 53 44 AM](https://user-images.githubusercontent.com/14238574/56960163-ed3e0880-6b1d-11e9-9a67-d069f5c150f4.png)

![Screen Shot 2019-04-30 at 7 54 38 AM](https://user-images.githubusercontent.com/14238574/56960168-ef07cc00-6b1d-11e9-8fba-a523cade1032.png)

**Comment by benjore** [comment]
I like it!

**Comment by cckozie** [comment]
Looks good in 1.2.0 (2ca9a91) other than inconsistencies with titles as noted in other issues.

**Comment by PhotoNomad0** [comment]
Verified in 1.2.0 (00ab4a2)

**Comment by cckozie** [comment]
1.2.0 (cc9c5b5)
The hover-overs look good, but I'm holding this until the text alignment problem when there is line wrapping is fixed.

**Comment by cckozie** [comment]
Looks good in 1.2.0 (5ee926c)
