### ISSUE TITLE
Update script to add the tN data to the code base (in build, getting the latest data from the Catalog)

### ISSUE THREAD

**Issue by RoyalSix** [unfoldingWord/translationCore#5758]
2 scripts in package.json
- `update-resources`
- `overwrite-resources`
Files that are being used are in the resources folder in the scripts folder

Include changes to updater dialog
**tN may be excluded in the source content updater**

**Comment by cckozie** [comment]
1.2.0 (b7e490a) 
Data exists after upgrade
