### ISSUE TITLE
Bug: Aligned target words don't merge when Greek words are merged

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5777]
### User Story

As an aligner, I want aligned target words to merge when original language words are merged so that tC doesn't lose my work and make me redo it.

When you have this: 
![image.png](https://images.zenhubusercontent.com/55e5f3984f7a08fbb7f4a658/408f5d14-b6fc-4e46-a3fc-0b5b30c559b9)

And try to merge them together, you incorrectly get this: 
![image.png](https://images.zenhubusercontent.com/55e5f3984f7a08fbb7f4a658/0d3b58c8-c130-44d7-bafe-836fa82f07aa)

When you should get this: 
![image.png](https://images.zenhubusercontent.com/55e5f3984f7a08fbb7f4a658/50021b27-0cda-43a2-b1f7-38c322db850e)

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by cckozie** [comment]
This is no longer a problem in 2.1
