### ISSUE TITLE
Bug: WordMAP Lemma Fallback not behaving as expected

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5778]
### User Story

![image.png](https://images.zenhubusercontent.com/55e5f3984f7a08fbb7f4a658/3a2398a2-154b-4575-ae31-551a13a7ce30)

The lemma fallback is not functioning as expected. The word following `Ἰσαάκ` (Isaac) is `Ἰσαὰκ`. Both have the same Strongs number (but different accents). When "Isaac" is aligned to one and the user clicks "Refresh", the other should be suggested. 

The exact same is the case with `Ἰακώβ` (Jacob) and `Ἰακὼβ`. 

Note: The very first word of this verse `Ἀβραὰμ` (Abraham) works as expected with `Ἀβραάμ`, the last word from Matthew 1:1. Namely, when `Abraham` is aligned to either `Ἀβραὰμ` or `Ἀβραάμ` WordMAP properly does the lemma fallback and suggests `Abraham` for the other. 

Observation: Isaac & Jacob (which don't work) have occurrence numbers on them. Abraham (which does work) does not. 

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by da1nerd** [comment]
Alignments from the current verse are not used as memory in wordMAP.
See here on line 90.
![image](https://user-images.githubusercontent.com/166412/57559648-b646ce80-7337-11e9-9aec-cb89efc2c686.png)

This would be an easy change.

**Comment by elsylambert** [comment]
Retested in 2.0.0 (4b3ebee). Lemma Fallback is working fine.
