### ISSUE TITLE
Verse Check Pane Text Overflow

### ISSUE THREAD

**Issue by RoyalSix** [unfoldingWord/translationCore#5779]
- [x] Verse overflow is only a problem in Select Mode - increase minimum height to 689
- [x] Fix the button overlap in the `Default Mode`

<img width="1280" alt="screen shot 2019-02-07 at 9 00 55 am" src="https://user-images.githubusercontent.com/16184018/52428788-8c230d80-2ab7-11e9-8e6a-58a8c99bdf44.png">

![image](https://user-images.githubusercontent.com/13352518/56226041-15b30680-6038-11e9-8011-e7250c8a6092.png)

**Comment by RoyalSix** [comment]
https://github.com/translationCoreApps/tc-ui-toolkit/compare/bugfix-jay-5779?expand=1

**Comment by mannycolon** [comment]
Verified on 736956e

**Comment by cckozie** [comment]
Looks good in 1.2.0 (736956e)

**Comment by elsylambert** [comment]
Verified in 1.2.0 (736956e). Not seeing any issues of Text Overflow.
