### ISSUE TITLE
Debugging USFM Imports

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#578]
Here's a sample USFM that we can manipulate if we need to get it to work correctly...

[Tyndale English - James.usfm.txt](https://github.com/unfoldingWord-dev/translationCore/files/743536/Tyndale.English.-.James.usfm.txt)

[43-LUK-Pt-Br-ULB.usfm.txt](https://github.com/unfoldingWord-dev/translationCore/files/743537/43-LUK-Pt-Br-ULB.usfm.txt)

(remove .txt since github refused .usfm files)

**Comment by ihoegen** [comment]
I can get the second one to load in just fine, trying to get the first one now

**Comment by klappy** [comment]
If it's missing tags let me know which ones to add.

**Comment by ihoegen** [comment]
@klappy For the book of James one, Having the dots in the file name cause an opening error. Also the abbreviation for James is not `jam`, but `jas`

**Comment by ihoegen** [comment]
And for getting the language, we have two options:

`\id_<CODE>_(Name of file, Book name, Language, Last edited, Date etc.`

or

`\rem data here Language language_code`
