### ISSUE TITLE
Add new filter for wA tool: Unaligned words

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5781]
### User Story

As an aligner, I want to find all verses with unaligned words so that I can ensure 100% of words are aligned.

### Features / Specifications

- [ ] If either a target word is unaligned or an original language word is unaligned, this filter would display it. 
- [ ]
- [ ]
![image](https://user-images.githubusercontent.com/13352518/52490167-bb09b400-2b89-11e9-82f4-5877455d2df8.png)

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by PhotoNomad0** [comment]
Verified in https://tc-builds.door43.org/build/develop/translationCore-macos-x64-1.2.0-f58a0ac.dmg

**Comment by cckozie** [comment]
Works in 1.2.0 (d50041c)
