### ISSUE TITLE
Rev 18:25 and 2 Cor 13:14 are incorrectly considered standard by tC

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5785]
### User Story

![image.png](https://images.zenhubusercontent.com/55e5f3984f7a08fbb7f4a658/263b8189-d878-41fd-9e6b-7dc46545d176)

Both Rev 18:25 and 2 Cor 13:14 are added to and then displayed as missing verses. 

When importing a project without a marker for 18:25, the missing verses will show up in the project import saying that 18:25 is missing. Then if you load the wA tool and navigate to 18:25, the above image will display. If you export to USFM, the `\v 25` will have reappeared. 

### Features / Specifications

- [ ] 
- [ ] 
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by benjore** [comment]
This is a problem with the ULT. Close when the ULT is updated and these verses no longer show up in tC as standard.

**Comment by cckozie** [comment]
1.2.0 (b485978) 
The missing verses dialog is no longer displayed.
The v 25 marker is not added in Revelation.
Should the scripture pane appear as above, or should the UGNT indicate no verse?

**Comment by PhotoNomad0** [comment]
@cckozie @benjore - I am still seeing a missing verse warning in Revelation:

![Screen Shot 2019-04-30 at 12 42 13 PM](https://user-images.githubusercontent.com/14238574/56978562-c85d8b80-6b45-11e9-9928-36f4d638f991.png)

and then in WA the verse still shows up, though empty:

![Screen Shot 2019-04-30 at 12 43 20 PM](https://user-images.githubusercontent.com/14238574/56978579-d0b5c680-6b45-11e9-8901-ceb8386a4847.png)

Seeing similar behavior in 2 Cor if the verse is removed from the project.

**Comment by cckozie** [comment]
The ULT has not been fixed.

![image](https://user-images.githubusercontent.com/8171759/56980520-30aa6e00-6b42-11e9-8592-596713088c70.png)


![image](https://user-images.githubusercontent.com/8171759/56980605-62bbd000-6b42-11e9-8ebc-92a82a80b54a.png)

**Comment by cckozie** [comment]
The problem in tC has been fixed.
