### ISSUE TITLE
Increase Hebrew font size in wA tool

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5789]
- [ ] Increase by 50%

**Comment by mannycolon** [comment]
Tested on `release-v1.1.3` (24c2775)
https://team43.slack.com/archives/G927YPW04/p1550250968017400

**Comment by cckozie** [comment]
The upper section is on 1.1.0 (5b1d1cc)
The lower section is on 1.1.3 (24c2775)
They look the same to me.
![image](https://user-images.githubusercontent.com/8171759/53104767-94d30500-34f5-11e9-960b-7ea1b05c9421.png)

**Comment by mannycolon** [comment]
Sorry @cckozie, I tested this in the wrong build. For some reason `release-v1.1.3` isn't building new builds since February 15.

**Comment by mannycolon** [comment]
`release-v1.1.3` builds are finally working and @neutrinog's changes for the Hebrew text in the drop zone work. However, in the scripture pane the text is still the same size as before. 

<img width="864" alt="screen shot 2019-02-20 at 2 21 30 pm" src="https://user-images.githubusercontent.com/17072300/53118320-d6c27200-351a-11e9-96f3-dce043f6c4a7.png">

**Comment by benjore** [comment]
@neutrinog @mannycolon I showed a screen shot to the stakeholders. Keep the Hebrew font size in the alignment area the same. Increase the Hebrew font size in the Scripture pane until it takes about as many lines as the English ULT.

Also, please reduce the padding above and below the Hebrew words in the alignment area so that the top box height is similar to what it was with the old font size.

**Comment by cckozie** [comment]
I'm moving this to In Progress since it's not really a QA Fail, but rather changed requirements.

**Comment by da1nerd** [comment]
@benjore the extra spacing is due to the font. I don't know Hebrew, but perhaps there can be other characters that extend higher up? If we decrease the padding in those cases we will have too little padding.

**Comment by da1nerd** [comment]
should the scripture pane part be assigned to someone else since I'm not as familiar with that code?

**Comment by benjore** [comment]
That's fine with me

**Comment by PhotoNomad0** [comment]
Cleared with @benjore  that this is OK for Hebrew in Scripture Pane: ![screen shot 2019-02-26 at 10 22 33 am](https://user-images.githubusercontent.com/14238574/53429290-57212100-39ba-11e9-9472-2bde5787f551.png)

**Comment by PhotoNomad0** [comment]
@benjore - does this look good for the alignment area?  Heights are now the same and it seems to have about the same room for ascenders and descenders.

![screen shot 2019-02-26 at 3 51 34 pm](https://user-images.githubusercontent.com/14238574/53486971-3909fe00-3a58-11e9-824b-b27b58d70086.png)

**Comment by PhotoNomad0** [comment]
Verified in https://tc-builds.door43.org/build/release-v1.1.3/translationCore-macos-x64-1.1.3-e6e6f45.dmg

**Comment by cckozie** [comment]
Pinged Larry to see if it's OK for the word to be split in the scripture pane.

![image](https://user-images.githubusercontent.com/8171759/53589581-583a8580-3b55-11e9-9eb5-d22020b48613.png)

**Comment by cckozie** [comment]
Per @benjore - Yes, this does need to be fixed. Zero width joiners, I think. I'm going to create a new issue for this (#5863)
In all likelihood this is not really related to the increased font, and probably is also an issue in other languages (such as Hindi) that use zero width joiners. The scripture pane needs to be fixed so that it does not allow breaking a 'word' that includes a zero width joiner.
