### ISSUE TITLE
Edit Project Details

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#579]
We need a way to edit the project details aka meta data for the project that is stored in the tc-manifest.

**Comment by jag3773** [comment]
For the fields that are in the manifest it would be good to modify them accordingly, see http://resource-container.readthedocs.io/en/latest/manifest.html for details.  Any tC specific information could be put into the .apps/tc/ folder, see http://resource-container.readthedocs.io/en/latest/app_meta.html.

**Comment by klappy** [comment]
Here is a current sample: https://git.door43.org/pjoakes/ceb_jas_text_ulb_L-/src/master/tc-manifest.json
