### ISSUE TITLE
Performance problems while the "Loading your project data" alert is displayed (1.2)

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5801]
1.2.0 (b25e030)

[es-419_luk_text_reg.zip](https://github.com/unfoldingWord-dev/translationCore/files/2857260/es-419_luk_text_reg.zip) (tstudio file)
[es-419_luk_text_ulb.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/2902825/es-419_luk_text_ulb.usfm.zip)

During import of this project the Loading your project data alert is displayed for 72 seconds.
In v1.1.0 it was only displayed for 6 seconds. It may have to do with missing verses.

1.2.0 (b7e490a)
46-ROM.usfm.zip

I imported a Romans usfm2 project.
When selecting the project in v1.1.3, the 'Loading your project data' alert is displayed for less than 5 seconds before the tools page is displayed
When selecting the same project in v1.2, the alert is displayed for 25 seconds before the tools page is displayed.

 1.2.0 (368d706) 
[en_ult_act_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/2962311/en_ult_act_book.zip)
It takes about 90 seconds with this project (15 seconds using 1.1.3 (e1fae24))

**Comment by benjore** [comment]
Could use a spike.

**Comment by PhotoNomad0** [comment]
@benjore - seems that this should be part of 1.2 release - as Kos said above, 1.1.3 runs much faster.

**Comment by mannycolon** [comment]
Tested in e535843 (v1.2.0)

**Comment by cckozie** [comment]
In v1.1.3 and a fully aligned Acts project, the "Loading..." alert was displayed for about 6.5 seconds during the full time from project selection until the alert was dismissed and the Tools page was displayed.
In 1.2.0 (de171a2), the equivalent time is now about 11 seconds, twice as long. 
In testing against an older version of 1.2 I found the time was much longer, 80+ seconds.
So, although there is much improvement over the older 1.2, users of 1.1.3 will see their load times roughly doubled, not a good thing.
I think we may need to rethink the idea of loading all of the data for all of the tools when the project is selected. All we really need to know at that time is how many invalidations there are.

**Comment by mannycolon** [comment]
@cckozie Most of the loading process that used to happen when we Launch the tool was moved back to when we select the project. So Launching the tool is significantly much faster thus selecting a project is slower than in previous versions. In other words, we are basically doing most of the processing when selecting the project unlike in the past when we used to divide the processing time in two (when selecting the project & when launching the tool)

**Comment by cckozie** [comment]
@mannycolon - Yes, I understand the processing sequence and the reasoning for it. However, as more tools become available the tradeoff in when their data is loaded may become less desirable. In many cases the user will be focused on a single tool for some period of time. Currently most users are focused on alignments and each time they select a project they pay the additional price of having the app load the data for tools that they may not ever use.
My comment above was not to criticize the path we have taken, but merely to suggest that we may want to reevaluate that decision at some point to explore some possibilities to make the app more responsive to the way various users may be using it.

**Comment by cckozie** [comment]
I've written up an enhancement request in #6010.
