### ISSUE TITLE
Rename 1.1.1 -> 1.1.3

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5803]
### User Story

As a [type of user], I want [some goal] so that [some reason].

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by da1nerd** [comment]
Looks good to me

**Comment by cckozie** [comment]
The builds show 1.1.3, but the app shows 1.1.1 (2c1a054). Should that be part of the same issue?
