### ISSUE TITLE
Missing Data on OT USFM3 Export

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#5805]
### User Story

As an aligner, I want to be able to align an OT book and export it so that I can change the world.

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

## Additional Context

Larry Sallee [9:23 AM]
@ben_jore I have a major bug in tC 1.1. I completed the alignment of Ruth, saved to Door43, and generated the USFM3 file without incident. I verified 100% alignment. Then I closed tC, and later reopened Ruth in tC. When I did, it showed 40% alignment, and most of my work is missing from tC. Now, I am sure I can import it again from my repo and restore the work, but I’m sure you want someone to check this out. So I’m on hold until you connect me with someone and they tell me what they want to see.

BTW, it weirdly only shows `1` broken link on the tool page.

Larry Sallee [9:27 AM]
https://git.door43.org/lrsallee/en_ult_rut_book. https://git.door43.org/unfoldingWord/en_ult/src/branch/master/08-RUT.usfm.

Larry Sallee [9:31 AM]
Oh no! The USFM3 export blew up at 2:13! All my work appears to be gone.

Larry Sallee [9:33 AM]
project.Zip 
[en_ult_rut_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/2857393/en_ult_rut_book.zip)

**Comment by PhotoNomad0** [comment]
Cannot find cause of data loss.  So creating a test build for Larry with:
- adding more frequent git commits (on context changes) to preserve data.
- adding logging of app console.

**Comment by cckozie** [comment]
[Fri Feb 15 2019.log.zip](https://github.com/unfoldingWord-dev/translationCore/files/2872287/Fri.Feb.15.2019.log.zip)

[en_ult_rut_book 2.zip](https://github.com/unfoldingWord-dev/translationCore/files/2872296/en_ult_rut_book.2.zip)

Had a script running that aligned, edited, and realigned verses in Ruth. At the end of the chapters it checks and compares the % complete before and after it uploads the project to Door43. After uploading it ends and then restarts tC and again compares the % complete.

This morning I was tweaking the script and when it finally finished the book the script ended. I then when to the tools page and noted that it indicated 85% complete. I'm not sure if that is correct or not.

I then took the option to upload to Door43 and receeved the reset alignments alert. I continued with the upload after which it was still indicating 85% complete.

I then closed and restarted tC. When I selected the Ruth project I received the reset alignments alert again. When I got to the tools page it was indicating 62% complete and most of chapter 4 is no longer aligned.

**Comment by cckozie** [comment]
I'm suspicious that this may be a race condition. I modified the script to upload the project after every 5 verses. It then failed twice in a row. When the script exits wA to do the upload, it is in the process of scrolling to the top of the word bank. It may be that wA is not done with its processing when the app moves to the projects page.
Again I get a alignments reset message when selecting to upload to Door43, and again when I restart tC and select the project. It doesn't look to like there's anything significant in the log.
[Sun Feb 17 2019.log.zip](https://github.com/unfoldingWord-dev/translationCore/files/2876089/Sun.Feb.17.2019.log.zip)
[en_ult_rut_book 3.zip](https://github.com/unfoldingWord-dev/translationCore/files/2876090/en_ult_rut_book.3.zip)
![image](https://user-images.githubusercontent.com/8171759/52957990-b054d900-3358-11e9-8809-38852514c7ff.png)

**Comment by PhotoNomad0** [comment]
Notes in testing `en_ult_rut_book 3.zip`:

looking at the git history of the alignment 1.json file, I see:
```
"7398de13 initially nothing aligned",
"3c35db16 - now 1.1 mostly aligned",
"7067f0f8 - 1:1 completely aligned",
"06c5303d - verses 1:1-2 aligned",
"02e467b5 - verses 1:1-3 aligned",
"d432b9da - verses 1:1-3 aligned, 1:4 mostly aligned",
"315a3bcc - verses 1:1-3 aligned, 1:4 alignment array completely emptied (shows ch 1:9 edited at same time)"
```

It looks like the contents of the `alignments` array is completely deleted! not just the bottom words arrays. Since this is happening in the commit before upload, could there be an alignment save happening while alignment data is still being loaded into the reducer?

Here are the different commits pretty formatted if you want to do diffs (added notes at top of files). 
[commits to 1.json.zip](https://github.com/unfoldingWord-dev/translationCore/files/2876982/commits.to.1.json.zip)

**Comment by PhotoNomad0** [comment]
Notes in testing `en_ult_rut_book 2.zip`:

Similar to `en_ult_rut_book 3.zip`, commit "5ca23f73" - has 3:15 alignment array completely emptied and show 4:20 as being completed at same time.

**Comment by cckozie** [comment]
Another one just occurred. The project here was zipped up after the alignments reset alert was issued and before it was actually uploaded. I clicked the X to close the alert, closed and restarted tC. It now shows only 1 alignment broken, but I think there were actually 3.
[en_ult_rut_book 4.zip](https://github.com/unfoldingWord-dev/translationCore/files/2877121/en_ult_rut_book.4.zip)
[Mon Feb 18 2019.log.zip](https://github.com/unfoldingWord-dev/translationCore/files/2877123/Mon.Feb.18.2019.log.zip)

Restarted the script on the same project. After realigning the 3 that were unaligned and then two more, it again went to upload the project and got the reset alignments alert. I don't know that it's significant, but I did notice that the last verse being aligned had a lot of wordMap recommendations. (The script accepts them all). Also noticed that when I click the X on the alignment reset alert and then go back into the project that the alignments have not been reset. It looks like they remain in tact until the app is closed and restarted.
[Mon Feb 18 2019.log 2.zip](https://github.com/unfoldingWord-dev/translationCore/files/2877163/Mon.Feb.18.2019.log.2.zip)
[en_ult_rut_book 5.zip](https://github.com/unfoldingWord-dev/translationCore/files/2877164/en_ult_rut_book.5.zip)

**Comment by cckozie** [comment]
I may actually have it in a failure mode now. Just restarted the script on the same project and it failed again. However, this time I did not receive the alignments reset message, I just noticed that the % complete changed from 76% to 74% after the upload and restart.
[Mon Feb 18 2019.log 3.zip](https://github.com/unfoldingWord-dev/translationCore/files/2877205/Mon.Feb.18.2019.log.3.zip)
[en_ult_rut_book 6.zip](https://github.com/unfoldingWord-dev/translationCore/files/2877207/en_ult_rut_book.6.zip)
Nope, not in a failure mode. Unable to replicate it now.

**Comment by PhotoNomad0** [comment]
@neutrinog - Larry's latest failure with new build:


> I stopped at v. 17 for a meeting and uploaded to D43. I came back to it after the meeting. Did not shut down. I continued to the end of chapter 2. I have tC open, with chapter 2 100% aligned. I uploaded to D43, and also exported the text and alignment data locally. Looking at that file, there is no alignment after 2:17.


[en_ult_rut_book (2).zip](https://github.com/unfoldingWord-dev/translationCore/files/2882028/en_ult_rut_book.2.zip)
[Tue Feb 19 2019.log](https://github.com/unfoldingWord-dev/translationCore/files/2882029/Tue.Feb.19.2019.log)

Below are the changes in git to chapter 2 alignments. It is concerning that there is no record in the git history of his alignments beyond ch 2:17 - though he says he finished chapter 2.  But do see it saved the context id changes for the following verse alignments and saved the completed flag for each alignments.  It’s like it stopped writing the alignment changes to disk.  Maybe more than a coincidence that Larry left tCore setting idle.

```
From most recent:
7a3325b5 Larry Sallee <lrsallee@noreply.door43.org> on 2019-02-19 at 12:12 -- alignments to 2:17
b918c288 translationCore User <unknown> on 2019-02-19 at 12:11 -- no alignments in 2:17
09b21a80 translationCore User <unknown> on 2019-02-19 at 12:08 -- alignments up to 2:15
aa818e74 translationCore User <unknown> on 2019-02-19 at 12:07 -- alignments up to 2:14
```

**Comment by cckozie** [comment]
1.1.2 (c980115)
Error is generated when attempting to upload a project to Door43 that does not already have a repo there.
<img width="1387" alt="1 1 2 error" src="https://user-images.githubusercontent.com/8171759/53054485-1715e780-346a-11e9-81a0-474d9a3bcca4.png">

**Comment by cckozie** [comment]
Now testing with 1.1.2 (343dfec) 
[Tue Feb 19 2019.log.zip](https://github.com/unfoldingWord-dev/translationCore/files/2882864/Tue.Feb.19.2019.log.zip)
[en_ult_rut_book 7.zip](https://github.com/unfoldingWord-dev/translationCore/files/2882865/en_ult_rut_book.7.zip)
Received alignments reset alert when uploading. Clicked the X to dismiss the alert. Loaded the project in wA and alignments were still in tact. Closed and reopened tC and received alignments reset alert when project was selected. wA tool card showed 1 broken link. In wA I see that 3 verses were unaligned starting with the one that had the broken link icon.

**Comment by da1nerd** [comment]
I discovered part of the problem. When a verse is edited the verse validation is performed on the old version of the verse instead of the new version of the verse (race).

**Comment by da1nerd** [comment]
@PhotoNomad0 from the git logs you show in your last comment I'm not certain Larry had the correct build. There should be "Auto save" messages in the git log.

> Update: ok I see the "auto save" in the history. You left those out in your comment.

**Comment by da1nerd** [comment]
OK! I've figured out exactly what's broken.
When a *project is opened* tc will execute `triggerWillConnect` on the tool api which will set things up including subscribing to the tool's redux store. When the *tool is closed* tc executes `triggerWillDisconnect` on the tool api which will tear things down including unsubscribing from the tool's redux store. Therein lies the problem.

* The tool connects when a project is selected
* The tool disconnects when the tool is closed.

Since tools can only reconnect when a project is selected the redux store remain unsubscribed to so the tools do not get any save events.

This bug was introduced when we moved the tool connection into the project selection.

**Comment by PhotoNomad0** [comment]
@cckozie - verified in https://tc-builds.door43.org/build/release-v1.1.2/translationCore-macos-x64-1.1.2-dfa9985.dmg

This is a fix for the problem that when you exit the WA tool then alignments stop saving to disk until new project selected or app restarted.

**Comment by cckozie** [comment]
Getting the Error uploading message as in the comment above from 3 days ago.

**Comment by da1nerd** [comment]
I've identified the upload issue. Working on a fix.

**Comment by mannycolon** [comment]
Tested on `fa21e2e (v1.1.2)`

**Comment by PhotoNomad0** [comment]
Was able to upload my project that would not upload also https://tc-builds.door43.org/build/release-v1.1.2/translationCore-macos-x64-1.1.2-fa21e2e.dmg

**Comment by cckozie** [comment]
1.1.2 (fa21e2e) 
Ran the align, edit, realign, every verse and upload every 3 verses script on Ruth for approximately 80 hours and 40 full alignments with no problems found.
