### ISSUE TITLE
Make git commit every time the menu changes

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5806]
### User Story

As an aligner, I want a git commit every time I change verses so that the possibility of retrieving data increases.

As a checker, I want a git commit every time I change to a new menu item so that the possibility of retrieving data increases.

### Features / Specifications

- [ ] 
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by PhotoNomad0** [comment]
This was added as part of a different issue: https://github.com/unfoldingWord-dev/translationCore/issues/5805

**Comment by cckozie** [comment]
1.1.2 (fa21e2e) 
**PLEASE WAIT FOR AN INDICATION FROM @benjore IF THIS FIX SHOULD BE APPLIED TO 1.1.2 OR HELD OFF UNTIL 1.1.3.**

Commits are not made until after the first upload to Door43. That really isn't sufficient.
I made some alignments, verse edits, and tW selections, and no git commits were made for any of them until I uploaded to Door43.
Once the project was upload the commits were all made as expected when the menu item was changed.

(We should probably consider also committing every time a verse edit is made. I'll write this up in another issue.)
.

**Comment by cckozie** [comment]
View git history by navigating into the project directory and entering 'git log' in terminal.

**Comment by cckozie** [comment]
Works in 1.1.2 (134656f)
