### ISSUE TITLE
 Verify that the `Index.JSON` file is being generated dynamically

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5817]
### User Story

As a [type of user], I want [some goal] so that [some reason].

### Features / Specifications

- [ ]  Verify that the `Index.JSON` file is being generated dynamically. (it is based off of the English ULT). ~Verified that index.json for all tools is overwritten on download of new en_ult.~
- [ ]  look at #5785
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by cckozie** [comment]
@PhotoNomad0 
I need help in figuring out how to test this. This is what I tried:
1. Ended tC
2. Deleted the resources folder
3. Started tC 
4. Deleted a single entry from each of the index.json files found in the folders within ...en/translationHelps/translationWords/v9 folders and then duplicated those files
5. Downloaded the updated English resources
6. Compared the index.json files against the duplicated ones
There were no differences found between the "updated" files and the duplicated tweaked ones

**Comment by PhotoNomad0** [comment]
What we are testing for is that the helps will be regenerated when there is an update to the en ult bible.  My method for testing was changing the `catalog_modified_time` in the en ult manifest. json to be an older date to fool tc into thinking it was an older version. Then updated the en resources. The index.json was regenerated - file times updated - content would be the same. 

Deleting en resource folders would just cause embedded resources to be unzipped.

**Comment by PhotoNomad0** [comment]
Unless en ult was downloaded from catalog, you will not see the index files regenerated.

**Comment by PhotoNomad0** [comment]
@cckozie - reproduced the problem in 1.1.3.  With tCore open - tried deleting en_ult, modified translationHelps/translationWords/v9/kt/index.json and after downloading updated en the contents of index.json were not updated

**Comment by PhotoNomad0** [comment]
@benjore @cckozie 
- ~it looks like the OrigL tw files are regenerated when OrigL is updated, but the en tw helps index.json is not updated~
- ~en_ult is updated,  currently the en tw helps index.json is not updated.~

~Need to know if it needs to update when the ult is updated, and if so then we will need to determine the primary aligned bible for each language.  Could cause some confusion when the ust is aligned.~

**Comment by PhotoNomad0** [comment]
Looks like we are checking the index.json of the bible being regenerated, not the helps

**Comment by cckozie** [comment]
1.1.3 (2c25b41) 
I modified the index.json files in the ult and ust folders, then downloaded the newer source content. Both index.json files were updated correctly.
