### ISSUE TITLE
Develop architecture to consolidate duplicate code between tN & tW

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord/translationCore#5837]
### User Story

As a tC developer, I want both tools (tN & tW) to share duplicate code so that when code needs to be edited/changed/modified/refactor/etc I don't have to change two different codebases. 

### Features / Specifications

- [ ] Suggested implementation: Come up with a HOC that holds only the duplicate code between tN & tW and add it to the respective tools. 
- [ ] Communicate plan with the team before implementation
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by mannycolon** [comment]
I propose creating a Higher Order component to accomplish this. We could call it tool-wrapper (or something else) It will inject the data needed by the tools as props.

See: [Higher Order Components](https://reactjs.org/docs/higher-order-components.html)

**Comment by cckozie** [comment]
1.2.0 (de171a2)
I suspect that some of the issues I've failed may be caused by this work so I'm holding this until they have all been passed. (#6001, #6009, #5832)

**Comment by cckozie** [comment]
Changed my mind, assuming the other issues will turn up problems.
