### ISSUE TITLE
Selection problems after a verse has been edited

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5847]
1.1.3 (4f85a74)
There are two related problems in this scenario; selections reset message is displayed but selections are not actually reset, and the wrong text ends up being highlighted
1. Load a Romans project in tW
2. Navigate to verse 4:12 in the Abraham group
3. Select the text "Abraham became the father"
4. Click Save, then Save & Continue
5. Open the expanded scripture pane
6. Edit verse 4:12 by delete the word "the" between "became" and "father" so that it reads "Abraham became father"
7. Choose a reason code and click Save
8. Notice that the selection reset message is displayed
9. Notice that the verse still displays selections, and that the selection are incorrect in the selection pane, the expanded scripture pane, and the menu
![image](https://user-images.githubusercontent.com/8171759/53509747-1260bd00-3a82-11e9-8f95-3f92014147ff.png)

**Comment by benjore** [comment]
Can't reproduce in translationCore 1.1.3 (fcbe5df)

**Comment by cckozie** [comment]
Looks good in 1.2.0 (b485978)
