### ISSUE TITLE
Cannot upload to Door43 using Linux

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#5853]
### User Story

Robert Hunt cannot upload to his account on Door43 using release-v1.1.2.
The symptoms are that the uploading dialog is on the screen for an extremely long time and gets error:
```
ERROR: v1.1.2 (fa21e2e): Warning: Failed prop type: Invalid prop `children` of type `array` supplied to `ProjectValidationContentWrapper`, expected a single ReactElement.
   in ProjectValidationContentWrapper (created by ProjectInformationCheck)
```
He is using Ubuntu Cosmic (18.10) with KDE desktop manager @RobH123 

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

## Additional Context

@PhotoNomad0 
I was able to reproduce an upload hang using his project on a VM running Linux Mint Mate 19.1 - 64-bit.
Then tested with release-v1.1.3 and it worked.
Created a test build release-v1.1.2-RC2 with the latest fix for git, and that worked for me to upload the first time.  
But that didn't fix things for Robert.
I've tried again starting from scratch and first got a failure, but the upload succeeded on the second attempt.  Here is his project: 
[en_ult_phm_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/2919150/en_ult_phm_book.zip)

**Comment by PhotoNomad0** [comment]
Installed `Kubuntu 18.10` in a virtualbox.  Set it up, installed tCore https://tc-builds.door43.org/build/release-v1.1.2-RC2/translationCore-linux-x64-1.1.2-d218d0f.deb and created a snapshot before I even logged into tCore (speeds up testing to be able to just restore snapshot).  

The first upload attempt I got a popup that an error occurred logging into D43.  
![screen shot 2019-03-01 at 11 21 09 am](https://user-images.githubusercontent.com/14238574/53651302-5b487b00-3c14-11e9-80c9-2ab5ef58f8b5.png)

But when I clicked OK, I got a prompt that upload succeeded.

On second clean test run did not see the error and upload succeeded.
and third clean test run successful.

**Comment by PhotoNomad0** [comment]
Created a test build with additional logging to see where upload may be failing.

https://tc-builds.door43.org/build/release-v1.1.2-RC3/translationCore-linux-x64-1.1.2-e4ce07e.deb

Unfortunately, I can't get it to fail again.

**Comment by PhotoNomad0** [comment]
From @RobH123 

@bruce.mc Don't tell @jag3773 but I upgraded to the next (19.04) version of Ubuntu over the weekend (yeah, I'm a bit bleeding edge :zany_face:) and it just worked first time. This means: 1/ my project files weren't the problem, 2/ Special chars in my user name weren't the problem. It doesn't mean that it'll work again next time but hopefully it will. If it wasn't for the fact that you replicated the problem, I'd say forget about it. But since it is a replicable problem, might be worth adding a few strategic log entries around the problem area so that you guys can keep an eye on it in case some other poor advanced Linux user else hits it. :grinning:

**Comment by PhotoNomad0** [comment]
After several attempts, got a log trace now with the RC4 build, but succeeded on second attempt.

[Mon Mar 04 2019.log.zip](https://github.com/unfoldingWord-dev/translationCore/files/2927096/Mon.Mar.04.2019.log.zip)

**Comment by PhotoNomad0** [comment]
@cckozie - This is not necessarily a fix, since Robert's problem could not be reproduced after adding the git fix.  And Robert no longer has the problem after updating his Kubuntu version.  What this adds is additional logging to capture details if there is a future upload error.  

To test just do an upload to Door43 and will see some logging of the steps that succeeded.  This way we can see what was happening when it hung, and if there is a failure we will hopefully see more detail in the errors.

tested in https://tc-builds.door43.org/build/release-v1.1.3/translationCore-macos-x64-1.1.3-2258fa5.dmg

**Comment by cckozie** [comment]
I have no way to test this.
