### ISSUE TITLE
Scripture pane should not break lines on a zero width joiner

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5863]
![image](https://user-images.githubusercontent.com/8171759/53589581-583a8580-3b55-11e9-9eb5-d22020b48613.png)

This problem was discovered when testing the enlarged Hebrew font issue, and it is probably also an issue in other languages (such as Hindi) that use zero width joiners. The scripture pane needs to be fixed so that it does not allow breaking a 'word' that includes a zero width joiner.

**Comment by PhotoNomad0** [comment]
Looking at the problem with Hebrew and splitting.  It is not so simple, in this example they are using a ZERO WIDTH SPACE (U+200B) in this text,  which does not mean to keep the words together.  There is a ZERO WIDTH JOINER (U+200D) defined, but it looks like that is deprecated and they should use WORD JOINER (U+2060) instead. Ref https://stackoverflow.com/questions/11392312/zero-width-non-breaking-space

**Comment by PhotoNomad0** [comment]
Tested using WORD JOINER (U+2060) and it does keep the words together in Scripture Pane.

**Comment by PhotoNomad0** [comment]
@benjore - this looks like a content issue.  If we try to work around in code, we could annoy people working in other languages.

**Comment by PhotoNomad0** [comment]
@benjore @cckozie - I think @jag3773 and @neutrinog are looking at updating the scripts that generate this content.

**Comment by da1nerd** [comment]
@jag3773 did we decide this would be fixed in the osis converter? https://github.com/unfoldingWord-dev/d43-catalog#convert-osis-to-usfm3

**Comment by da1nerd** [comment]
I've updated the osis convert at https://github.com/unfoldingWord-dev/d43-catalog#convert-osis-to-usfm3 to use the word joiner instead of the zero-width space.

Should I open a PR against https://git.door43.org/unfoldingWord/UHB with the newly converted osis? (where is the osis repo btw.)

**Comment by da1nerd** [comment]
Here's a PR https://git.door43.org/unfoldingWord/UHB/pulls/337

**Comment by jag3773** [comment]
I've updated the UHB in our catalog and my spot check in Ruth chapters 1 and 2 did not show any improper word wrappings.

**Comment by cckozie** [comment]
1.1.3 (eb48234) - On a clean install the UHB version 2.1.1 gets loaded.
However, if it gets installed with 1.1.3 (126c679) or v1.1.2 already on the computer, the UHB does not get updated. v1.4.1 remains as the only UHB. Downloading the Ancient Hebrew resource does replace it with v2.1.1.

With the new UHB (2.1.1) installed, the problem of misplaced line breaks is fixed.

**Comment by PhotoNomad0** [comment]
@cckozie - verified that it also does not upgrade moving from 1.1.2 to 1.1.3.  Looking into it.

**Comment by cckozie** [comment]
1.1.3 (4817b07) - The UHB does now get updated when the tC upgrade is installed.

It appears that the lexical popup populator needs to be updated to handle the new joiner.
The Lemma is now not displayed in the popup for some of the Hebrew words.
Also, there is an extra "Morphology" above the line.
![Screen Shot 2019-04-03 at 11 43 12 AM](https://user-images.githubusercontent.com/8171759/55497252-9a4c6080-5606-11e9-89fd-59232e31a54a.jpg)

![Screen Shot 2019-04-03 at 11 43 19 AM](https://user-images.githubusercontent.com/8171759/55497292-ac2e0380-5606-11e9-9707-a3aef244c580.jpg)

![Screen Shot 2019-04-03 at 11 52 12 AM](https://user-images.githubusercontent.com/8171759/55497490-1181f480-5607-11e9-85c3-ed496b1f8a4a.jpg)

**Comment by PhotoNomad0** [comment]
Verified in https://tc-builds.door43.org/build/release-v1.1.3/translationCore-macos-x64-1.1.3-4817b07.dmg

**Comment by cckozie** [comment]
Lexical info is correct in 1.1.3 (3f886e6)

**Comment by jag3773** [comment]
Note for future reference that I used this to make the replacements in the UHB: https://unix.stackexchange.com/questions/59447/replace-unicode-chars-in-vim .

e.g. a replacement script like this:

    :%s/<Ctrl-v>u200b/<Ctrl-v>u2060/g

Note that you can't copy and paste the above, you have to type it in, you'll see something like this after you've typed that above:
![Screen Shot 2019-07-11 at 1 01 50 PM](https://user-images.githubusercontent.com/107731/61070208-1c091280-a3dc-11e9-9cd2-16bd2219603a.png)
