### ISSUE TITLE
Select multiple words at once in Word Alignment (wA) (in the word bank)

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5885]
### User Story

As an aligner of the UST, I want to select many words at once so that I don't have to click so many times.

### Features / Specifications

- [ ] When one word is selected in the word bank, if the user Shift-clicks another word, select all the words in between. 
  - [ ] If there are words already used in between the selected word and the shift-clicked word, then ignore that one and select all of the unselected words.
- [ ]

![image.png](https://images.zenhubusercontent.com/55e5f3984f7a08fbb7f4a658/ad55143c-a884-4597-8f84-bf24623e8998)

![image.png](https://images.zenhubusercontent.com/55e5f3984f7a08fbb7f4a658/5bf00740-5d63-4ee2-8ddc-5d539edb34a8)

- [ ] To deselect a single word, the user clicks on a word while holding down Cmd (Ctrl for Windows)

![image](https://user-images.githubusercontent.com/13352518/60909295-85a1e900-a243-11e9-9453-f79bce3e4be7.png)

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by PhotoNomad0** [comment]
@birchamp @elsylambert I would suggest a change to the DOD.  In the case of deselecting words, there is no need to hold down command or control.  If you just do a regular click on a selected word, it will just toggle off.

**Comment by PhotoNomad0** [comment]
@elsylambert Issue is fixed in develop branch translationCore 3.6.0 (2bc4476) .

**Comment by elsylambert** [comment]
Looks good in translationCore 3.6.0 (2bc4476). Multiple words can be selected using Shift+ click and for de-selection, regular clicks works as toggle to un-selecte/select. Works as expected.
