### ISSUE TITLE
tC log file does not capture vital data

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5889]
Much of the valuable data shows as [object object] in the log file.
It doesn't seem that the project name is ever captured.

From the console:
![image](https://user-images.githubusercontent.com/8171759/53986427-ccd86b80-40e3-11e9-9239-f2f2e07bdf2b.png)

From the log file:
![image](https://user-images.githubusercontent.com/8171759/53986484-ec6f9400-40e3-11e9-9ce4-0eb84c40759c.png)

**Comment by PhotoNomad0** [comment]
@cckozie - good catch.  I think we should add a log of project name when selected.

The reason we don’t have the Object data in the log is that it makes for MASSIVE log files that includes all the project data.  Also the object data is not very readable - hard to decipher even for the developers.  So we are reduced for now manually adding log entries for data that is important.

There are other options, but they could be time consuming to implement.

**Comment by cckozie** [comment]
@PhotoNomad0 - Seems like we should be logging at a minimum the project name, tool name, and context ID (assuming that is the selection from the group menu). 
There also doesn't appear to be anything logged during imports.

**Comment by PhotoNomad0** [comment]
@cckozie - Yes, I forgot to mention that also.

**Comment by PhotoNomad0** [comment]
@cckozie - Tested in https://tc-builds.door43.org/build/release-v1.1.3/translationCore-macos-x64-1.1.3-dcac667.dmg

Also added extra logging for developers so we can see how long various steps in import, export, and project selection take.

**Comment by cckozie** [comment]
1.1.3 (9d5ff9e) 
I am seeing logged data about imports, uploads, project names, tool menu contexts.
