### ISSUE TITLE
Need an indicator of processing when user selects to upload to Door43

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5892]
1.1.2 (134656f) 
When choosing to upload a fully aligned Acts on my fastest machine it takes nearly 5 seconds from the time the upload is clicked until there is any indication that something is happening.
On my Windows machine it takes 16 seconds until the screen changes.

**Comment by PhotoNomad0** [comment]
This should be addressed in 1.1.3 - shows popup very quickly that starts with loading project data prompt and then the actual uploading data prompt

**Comment by cckozie** [comment]
1.1.3 (126c679)
There is now only about a 1 second delay after clicking the Upload to Door43 option before the first alert is displayed, and both alerts have a spinning icon.
