### ISSUE TITLE
Update tN - tA mappings based on stakeholder interactions

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5920]
## Specs

- [ ] Update categories based on Larry & Perry's categorization (found here: https://docs.google.com/spreadsheets/d/1MCWzmtqetzmZkKj_RouzyJB9b0gLvjLR7ZmiVBJw2fw/edit?ts=5c92ae54#gid=0 )
  - [ ] Update "Head Categories" to include `Discourse` and `Other`
- [ ] If a category is imported that doesn't fall into any category, it should automatically show up in `Other`

**Comment by mannycolon** [comment]
@benjore Hey the following items are missing in the `tn - ta` mapping list 
- figs-we (Forms of We)
- figs-they (Forms of They)

**Comment by benjore** [comment]
Add them both to `Grammar`. I just added them to the spreadsheet too.

**Comment by cckozie** [comment]
1.2.0 (b485978)
There is no "Other" category. Its subcategories appear in the group menu even though not selected.

**Comment by mannycolon** [comment]
Verified in latest build

**Comment by cckozie** [comment]
1.2.0 (cc9c5b5) 
There is now an "Other Terms" category and the correct subcategories lie beneath it. I pinged Ben to verify if "Other Terms" is OK as the first comment specifies "other".

**Comment by cckozie** [comment]
1.2.0 (5ee926c) 
Looks good except the tN category name "Other Terms" needs to be changed to just "Other".

**Comment by cckozie** [comment]
Looks good in 1.2.0 (1612995)
