### ISSUE TITLE
Verbiage: Update hover-over for "Reject" button in wA tool

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5938]
- [ ] Current verbiage: "Reject all MAP-generated suggestions" 
  - [ ] Change to: "Reject all suggestions."
- [ ] Current verbiage: "Accept all MAP-generated suggestions" 
  - [ ] Change to: "Accept all suggestions."
- [ ] Current verbiage: "Refresh MAP-generated suggestions"
  - [ ] Change to: "Refresh suggestions"

**Comment by richmahn** [comment]
@benjore There is also a “Accept all MAP-generated suggestions” and “Refresh MAP-generated suggestions”. Do you want all changed to “<verb> suggestions” or just the reject string?

**Comment by PhotoNomad0** [comment]
Verified in translationCore 1.2.0 (ca7a093)

**Comment by cckozie** [comment]
Looks good in 1.2.0 (ca7a093)

**Comment by elsylambert** [comment]
Verified in 1.2.0 (05888d5). Working fine. Hover-over Verbiage has been changed to "Reject all suggestions." for Reject Button,  "Accept all suggestions." for Accept button and  "Refresh suggestions." for Refresh Suggestion button.
