### ISSUE TITLE
"Loading Project" dialog does not appear until almost the end of the project load

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5942]
### User Story

As a [type of user], I want [some goal] so that [some reason].

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by benjore** [comment]
Dup of #3522 ??

**Comment by cckozie** [comment]
See also #5937

**Comment by mannycolon** [comment]
The problem appears to be in ProjectAPI.js

**Comment by mannycolon** [comment]
Tested in e535843 (v1.2.0)

**Comment by cckozie** [comment]
Looks good in 1.2.0 (d3d469b)
