### ISSUE TITLE
Check for latest resources during build process

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5943]
### User Story

As a [type of user], I want [some goal] so that [some reason].

### Features / Specifications

- [ ] 
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by benjore** [comment]
First need to fix downloading multiple resources at once + downloading hanging.

**Comment by PhotoNomad0** [comment]
Blocked by https://github.com/unfoldingWord-dev/translationCore/issues/6062

**Comment by benjore** [comment]
Team wants to Spike this one, think through when and how is the best way to do this.

**Comment by PhotoNomad0** [comment]
@ben - also need to figure out how we determine which bibles to include in build (or exclude).  Currently our scripts include all bibles for a language (including t4t, which we currently have to remove manually).

**Comment by PhotoNomad0** [comment]
Note:
- this would ~greatly~ slow the build process.  
  - _Edit: I measure about 4 minutes on my PC to update everything vs about 1.5 minutes for moderate resource update - so I estimate between 2 to 8 minutes on concourse to a process that is currently about 20 minutes long.  Not sure what the hard limit is concourse builds._
- we could do this for each release build only
- since the catalog release process is not yet that robust, maybe better if we had a way to toggle this (in the commit) so that we can unblock builds.

**Comment by PhotoNomad0** [comment]
Note: it seems that catalog problems would break all builds if we go this way.

**Comment by PhotoNomad0** [comment]
Note:  

Steps to be done:
- currently get an error when maj-rp and tisch Greek bibles are updated (don't get the error when we build all).  This needs to be fixed first.
- need to update the source content updater script to return error/success flag to support use in build scripts.
- update concourse build scripts to call the resource updater script - add option to disable this through change to tCore source.

**Comment by PhotoNomad0** [comment]
@cckozie @elsylambert - Here is a test build where the bundled resources where updated solely by script.  I have not done any manual removal of bibles we don't normally include in a release.  There probably should be an issue for how we determine what to include or exclude.  Are there any tests you can run to see how well tCore does with updating resources on projects?  It is a complicated issue to get our minds around, but I guess the first step is just to make sure projects and tools can still open with the resource changes.

[Linux build 2.1.0 (536b7e7)](https://tc-builds.door43.org/build/feature-mcleanb-5943/translationCore-linux-x64-2.1.0-536b7e7.deb) is ready for download.
[macOS build 2.1.0 (536b7e7)](https://tc-builds.door43.org/build/feature-mcleanb-5943/translationCore-macos-x64-2.1.0-536b7e7.dmg) is ready for download.
[Windows x64 build 2.1.0 (536b7e7)](https://tc-builds.door43.org/build/feature-mcleanb-5943/translationCore-win-x64-2.1.0-536b7e7.setup.exe) is ready for download.
[Windows x32 build 2.1.0 (536b7e7)](https://tc-builds.door43.org/build/feature-mcleanb-5943/translationCore-win-x32-2.1.0-536b7e7.setup.exe) is ready for download.

**Comment by cckozie** [comment]
@PhotoNomad0 Rudimentary tests work when doing a clean install.
When opened after an upgrade from 2.1 I get a blank screen.
[Thu Dec 26 2019.log.zip](https://github.com/unfoldingWord/translationCore/files/4002851/Thu.Dec.26.2019.log.zip)

![image](https://user-images.githubusercontent.com/8171759/71480491-f7a0c700-27be-11ea-9ea1-c066cb230639.png)

**Comment by PhotoNomad0** [comment]
@cckozie - thanks, oops, good catch.

**Comment by PhotoNomad0** [comment]
@cckozie @elsylambert - have a fixed test build:

[Linux build 2.1.0 (c6f260b)](https://tc-builds.door43.org/build/feature-mcleanb-5943/translationCore-linux-x64-2.1.0-c6f260b.deb) is ready for download.
[macOS build 2.1.0 (c6f260b)](https://tc-builds.door43.org/build/feature-mcleanb-5943/translationCore-macos-x64-2.1.0-c6f260b.dmg) is ready for download.
[Windows x64 build 2.1.0 (c6f260b)](https://tc-builds.door43.org/build/feature-mcleanb-5943/translationCore-win-x64-2.1.0-c6f260b.setup.exe) is ready for download.
[Windows x32 build 2.1.0 (c6f260b)](https://tc-builds.door43.org/build/feature-mcleanb-5943/translationCore-win-x32-2.1.0-c6f260b.setup.exe) is ready for download.

**Comment by elsylambert** [comment]
@PhotoNomad0  Upgrade to 2.1.0 (c6f260b)  is giving a blank white screen at first. Closed tC and restarted , got this error before it opened tC.
![image](https://user-images.githubusercontent.com/51806180/71526046-cdc0d080-28a2-11ea-8bca-ecfc6e0b422e.png)

**Comment by PhotoNomad0** [comment]
@elsylambert - sorry, I tested on windows, but did not see this error.

**Comment by cckozie** [comment]
@PhotoNomad0 
2.1.0 (c6f260b)
I did not see any problems when upgrading from 2.1.0 (7adcd44) or 2.1.0 (ed1c32c) (on Mac)
After doing a clean install, I see this problem when adding resources to the scripture pane. Sometimes I see it and sometimes it works correctly. Can't seem to find the pattern.
![image](https://user-images.githubusercontent.com/8171759/71534376-091fc700-28c4-11ea-882a-697bf7c2c824.png)

**Comment by PhotoNomad0** [comment]
Verified in translationCore 2.1.0 (46a3795).  Builds now contain all the latest en, Greek, hbo and hi bibles.

Haven't been able to reproduce the problem above.

**Comment by cckozie** [comment]
Looks good in 2.1.0 (46a3795). I am no longer seeing the problem on the Load resource button.
