### ISSUE TITLE
tC projects index files are not being updated when new tn or tw resources are added 

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord/translationCore#5951]

**Comment by mannycolon** [comment]
<img width="1234" alt="Screen Shot 2019-04-03 at 5 30 06 PM" src="https://user-images.githubusercontent.com/17072300/55514455-24f88400-5636-11e9-9a74-4fcbb2282894.png">

**Comment by mannycolon** [comment]
Tested on de171a2 (v1.2.0)

**Comment by cckozie** [comment]
1.2.0 (b485978)
Followed Manny's test process on PR #5968 (following) and "Double negatives" show up on the tN tool card unchecked. Their checks do not show on the group menu when the project is loaded.

![image](https://user-images.githubusercontent.com/8171759/56853502-8dade600-68ee-11e9-98e8-da958d7eeaf7.png)

Steps:
1. Deleted `figs-doublenegatives.json` from `(resources/en/translationHelps/translationNotes/v14/figures/groups/tit/)` 
1. Open this Project [en_ulb_tit_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/3096041/en_ulb_tit_book.zip) (Please if you have an old version of this project delete it before importing it)
1. The project opens in the `Double Negatives` (doublenegatives)

**Comment by cckozie** [comment]
In the scenario above I had renamed the doublenegatives file to xxxxfigs-doublenegatives.json rather than deleting it. It appears that may not be a reasonable test since when I actually deleted it "Double negatives" no longer show on the tN tool card.
