### ISSUE TITLE
A critical error has occurred message after import from Door43

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5960]
1.1.3 (3f886e6)
1. Import the project at https://git.door43.org/tc01/en_ultt_tit_book
2. Upload it to your own repo on Door43
3. Load the project in tW
4. Make an edit in a verse and save it
5. Upload the project to Door43 again
6. Select to download the same project from your repo
7. On the project details screen change the translation ID to something other than ultt and click Continue
8. When prompted to rename the repo or create a new one, click on the X in the dialog to dismiss it
9. Note that the new project does not show on the projects page
10. Click the Go to User button 
11. Click the Go to Projects button
12. Note that the new project does now show on the projects page
13. Select the new project
14. Load the new project in wA
The error message is now displayed and the project is not loaded
![image](https://user-images.githubusercontent.com/8171759/55594732-5e002980-5706-11e9-9795-91ac6c343f1d.png)

**Comment by cckozie** [comment]
Should be fixed by #6256

**Comment by cckozie** [comment]
Retested in  2.0.0 (ca6c273), but now there is a bug that does not display the Rename alert.

**Comment by cckozie** [comment]
Retested in 2.0.0 (52c56f7) (a test build), and now the Warning: A critical error has occurred! screen is displayed. 
1. Import a project from your repo
2. On the details screen, change the translation id to something else
3. When the Project renamed alert is displayed, click on the X to close the alert
4. Click on the Go to User button
5. Click on the Go to Projects
6. Click on the Tool icon in the stepper menu
Note that the critical error screen is displayed.
7. Click on the Go to Projects button
8. Select the project just imported
Note that the project will now load

**Comment by elsylambert** [comment]
Still an issue in 2.2.0 (2375ae5)

**Comment by birchamp** [comment]
DoD: Import of ref'd project from Door43 doesn't cause a critical error.

**Comment by mannycolon** [comment]
@cckozie @elsylambert I propose removing the X from the alert and making the user choose between the two options rather than allow them to close out the alert. Thoughts?

**Comment by cckozie** [comment]
@mannycolon - That works for me. Exactly what I suggested for all alerts in #6740.
@birchamp - Any reservations in doing that?

**Comment by mannycolon** [comment]
Verified on d668292

**Comment by elsylambert** [comment]
Looks good in 2.2.0 (db7ab5c). X in the alert has been removed and the project opens/works fine after either of the two actions is selected.

**Comment by cckozie** [comment]
Not able to close the alert with an X now, so unable to cause the failure in 2.2.0 (db7ab5c).
