### ISSUE TITLE
Selections in the Scripture Pane persist when navigating to new verse

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5961]
### User Story

As a tN editor who is constantly highlighting and copying text from the Greek in the Scripture Pane, I want highlights/selections in the Scripture Pane to clear when I navigate to a different verse so that I don't get confused or have to do extra work.

### Features / Specifications

- [ ] From Larry.
- [ ]
- [ ]

## Steps to reproduce
1. Select some Greek text in the Scripture pane
![image.png](https://images.zenhubusercontent.com/55e5f3984f7a08fbb7f4a658/7f025ad0-7e40-41c8-a178-900db23b7564)

2. While the text is still selected, navigate to a new verse. The selection remains in a similar position in the new verse. 
![image.png](https://images.zenhubusercontent.com/55e5f3984f7a08fbb7f4a658/a0c1ef42-2fad-4a62-8b0e-48a45e2588f3)

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by cckozie** [comment]
I am not seeing this problem in 2.1.0 (7adcd44).
Check with Larry after he upgrades.

**Comment by cckozie** [comment]
Larry is not seeing the problem any longer in 2.1
