### ISSUE TITLE
Greek Text Shows with wrong language code, wrong name

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/translationCore#5963]
### Prerequisites

- [x] I have searched the [issues](https://github.com/unfoldingWord-dev/translationCore/issues) of this repository and believe that this is not a duplicate.

### Description

When updating the source content in the app the Greek text shows up as `grc`, which is not the correct language code.  The text in the catalog is at https://git.door43.org/Door43-Catalog/el-x-koine_ugnt , which is langauge code `el-x-koine`.

The language name/display name should be something like "Koine Greek".

See image

### Steps to Reproduce

Actions -> Check for Content Updates

**Screenshots**

See problem here: 
<img width="786" alt="Screen Shot 2019-04-08 at 3 35 44 PM" src="https://user-images.githubusercontent.com/107731/55752613-75952600-5a16-11e9-91ed-c4404a672359.png">

**Expected behavior:** 

Should see "Koine Greek (el-x-koine)"

**Actual behavior:** 

See "grc (grc)"

**Environment**
| Tech         | Version |
|--------------|---------|
| tc           | v1.1.3 eb48234  |
| build #      |         |
| OS           |         |

### Work to be Done

- tc-source-content-updater module:
  - [x] - *.test.js - many places `grc` to `el-x-koine`
  - [x] - resourcesDownloadHelpers.js - downloadAndProcessResource() - `grc` to `el-x-koine`
  - [x] - parseHelpers.js - parseCatalogResources() - line 206 and 207 remove mapping of `el-x-koine` to `grc`
  - [x] - resourcesHelpers.js - makeTwGroupDataResource() - `grc` to `el-x-koine`

- translationCore:
  - [x] - package.json - update scripts "update-resources" and "overwrite-resources"
  - [x] - WordAlignmentHelpers.js - getGreekVerseFromResources() - `grc` to `el-x-koine`, rename method and add Hebrew support

  - [x] - gatewayLanguageHelpers.js - getGatewayLanguageList() - remove special handling for `grc`
  - [x] - gatewayLanguageHelpers.js - getValidGatewayBibles - in comment `grc` to `el-x-koine`
  - [x] - gatewayLanguageHelpers.js - getValidGatewayBiblesForTool - in comment `grc` to `el-x-koine`

  - [x] - ResourcesHelpers.js - getAvailableCategories() - `grc` to `el-x-koine` also add `uhb` if OT
  - [x] - ResourcesHelpers.js - getLanguageIdsFromResourceFolder() - `grc` to `el-x-koine`
  - [x] - ResourcesHelpers.js - getAvailableScripturePaneSelections() - `grc` to `el-x-koine`
  - [x] - ResourcesHelpers.js - getResourcesNeededByTool() - `grc` to `el-x-koine`

  - [x] - ResourcesActions.js - addNewBible() - `grc` to `el-x-koine`
  - [x] - ResourcesActions.js - makeSureBiblesLoadedForTool() - `grc` to `el-x-koine`

  - [x] - BibleHelpers.js -getOLforBook() - `grc` to `el-x-koine`

  - [x] - ProjectDetailsHelpers.getToolProgress() - `grc` to `el-x-koine` also add `uhb` if OT

- WA:
  - [ ] - paneSettingsHelper.test.js - `grc` to `el-x-koine`

- tc-ui-toolkit:
  - [x] - verseHelpers.js  - `grc` to `el-x-koine`

- [x] - rename bundled resources folder from `grc` to `el-x-koine`. ~run "update-resources" script~

**Comment by PhotoNomad0** [comment]
Added list of needed Work to be done at bottom of description.

**Comment by cckozie** [comment]
1.2.0 (de171a2) 
When upgrading from an earlier version of tC, grc still appears in the resources folder and Koine Greek appears twice in the resource selection dropdown list.
![image](https://user-images.githubusercontent.com/8171759/56752214-65d34c80-674d-11e9-9687-68164f0dc189.png)

**Comment by PhotoNomad0** [comment]
@cckozie - the upgrade works if you start with a fresh 1.1.3 install and then run 1.2.0.  Which is the normal use case.

The only way I can reproduce this behavior is to run the 1.2.0, then go back to 1.1.3, and then run 1.2.0.  The problem is that the 1.1.3 version when it runs notices that `grc` is missing and restores it, but it leaves the time stamp for the resources to the 1.2.0 time.  Then when you run the 1.2.0, it sees that the resource time stamp is still for 1.2.0 so it does not do a clean resource reinstall.

@benjore - do we want to add a specific step to remove the `grc` resource if it is still present?  This is not normal user workflow, but not all our users are normal.

**Comment by cckozie** [comment]
It was not my intent to test by going from 1.2 to 1.1.3 and then back again, but after retesting I have to agree with @PhotoNomad0 that's what I must have done. I have testing upgrading from multiple previous releases going back to 0.9 and it appears to be working correctly.
