### ISSUE TITLE
tC is displaying footnotes as text in the UGNT

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5964]
1.1.3 (3f886e6)
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/1ace249b-7c5a-4d8c-9c11-a50973a589b4)
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/41376c90-5b26-4528-a9f1-c88b38c18cd7)

**Comment by PhotoNomad0** [comment]
Verfied in https://tc-builds.door43.org/build/release-v1.1.3/translationCore-macos-x64-1.1.3-f505bc4.dmg

**Comment by cckozie** [comment]
1.1.3 (f505bc4)
The problem of the UGNT footnote being displayed as text has been fixed.
~~But there is now an inconsistency in the way we handle determining whether or not a verse alignment is complete. (This was really not relevant before this fix)
In the use case where the UGNT for the verse is a footnote and the target has no text, the verse is  considered complete (check mark on verse, alignment complete switch is automatically set).
In the use case where the UGNT for the verse is a footnote and the target has a footnote plus text, the verse is not considered complete (no check mark, alignment complete switch not set).~~

**Comment by benjore** [comment]
Let's move the "new problem" to a new issue.

**Comment by cckozie** [comment]
~~In looking at this further, I see that the content is handled differently when the footnote embodies multiple verses. If the footnote is for a single verse, the \fqa marker is used for the alternate text. If the footnote covers multiple verses, the fqa marker is not used, and the alternate text surrounded by brackets.
Working on this maybe should wait until after we have address verse spans.~~

I moved this problem to #5969
