### ISSUE TITLE
Alignment complete not being set in some cases of verses with footnotes

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5969]
1.1.3 (f505bc4)
There is an inconsistency in the way we handle determining whether or not a verse alignment is complete. (This was really not relevant before this fix)
In the use case where the UGNT for the verse is a footnote and the target has no text, the verse is  considered complete (check mark on verse, alignment complete switch is automatically set).
![image](https://user-images.githubusercontent.com/8171759/55914542-07369c00-5bad-11e9-96c7-f63c1a291e4f.png)

In the use case where the UGNT for the verse is a footnote and the target has a footnote plus text, the verse is not considered complete (no check mark, alignment complete switch not set).
![image](https://user-images.githubusercontent.com/8171759/55914603-2c2b0f00-5bad-11e9-95c0-783abe735ac8.png)

In looking at this further, I see that the content is handled differently when the footnote embodies multiple verses. If the footnote is for a single verse, the \fqa marker is used for the alternate text. If the footnote covers multiple verses, the \fqa marker is not used, and the alternate text surrounded by brackets.
Working on this maybe should wait until after we have address verse spans.

**Comment by elsylambert** [comment]
Not seeing this issue in 2.2.0 (2375ae5). 
@cckozie do you have a project with footnote in UGNT?

**Comment by cckozie** [comment]
@elsylambert - John 5:3 and 5:4 both have footnotes in the UGNT (not displayed in tC), but since we are now include the texts for the disputed verses, the UGNT pane is no longer blank. 
I think we can close this since we will probably not run into the situations described in the original comment any more.
