### ISSUE TITLE
Rendering of tW's that span multiple Greek may display incorrectly

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5970]
### User Story

As a user, I want tW's that span multiple words to be rendered correctly so that the checks show up correctly.

### Features / Specifications

- [ ] A block of Original Language text that does not have `...` in it should be treated as a block of contiguous text. 
- [ ] (As you can see in the mockup below, the first occurrence of any word in the "snippet" is being selected in the Greek, instead of the entire block being treated together.)
- [ ] Note: The English is being rendered as expected. 

*This use case is fixed in 1.1.4 (6826f63)*
![image.png](https://images.zenhubusercontent.com/55e5f3984f7a08fbb7f4a658/5f4ee625-cf8e-4aad-82b3-f982f2f26651)

![image](https://user-images.githubusercontent.com/13352518/55963764-0cd9c380-5c39-11e9-92ac-6cbe28b3dad1.png)

![image](https://user-images.githubusercontent.com/13352518/55972837-e5d7bd80-5c49-11e9-8064-df0c3245dd70.png)

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by benjore** [comment]
NOTE: This is a tW problem.

**Comment by benjore** [comment]
I'll post some more examples: 
*This use case is fixed in 1.1.4 (6826f63)*
![image](https://user-images.githubusercontent.com/13352518/56046870-d455ea80-5d09-11e9-8106-54d31dece94e.png)

*This use case is fixed in 1.1.4 (6826f63)*
![image](https://user-images.githubusercontent.com/13352518/56046897-e8015100-5d09-11e9-9b46-ffa3535a3bd1.png)

*This use case is fixed in 1.1.4 (6826f63)*
![image](https://user-images.githubusercontent.com/13352518/56046916-f3547c80-5d09-11e9-87f8-6d8062809160.png)

*This use case is fixed in 1.1.4 (6826f63)*
![image](https://user-images.githubusercontent.com/13352518/56046979-197a1c80-5d0a-11e9-81e9-981d0a6403cc.png)

*This use case is fixed in 1.1.4 (6826f63)*
![image](https://user-images.githubusercontent.com/13352518/56047087-49c1bb00-5d0a-11e9-897b-558949c5a1ff.png)

*This use case is fixed in 1.1.4 (6826f63)*
![image](https://user-images.githubusercontent.com/13352518/56047156-71b11e80-5d0a-11e9-8183-d868023f50d4.png)

*This use case is fixed in 1.1.4 (6826f63)*
![image](https://user-images.githubusercontent.com/13352518/56047633-72968000-5d0b-11e9-8f96-5b128a99cdd1.png)

*This use case is fixed in 1.1.4 (6826f63)*
![image](https://user-images.githubusercontent.com/13352518/56047858-f6506c80-5d0b-11e9-87de-688e1b148eb0.png)

*This use case is fixed in 1.1.4 (6826f63)*
![image](https://user-images.githubusercontent.com/13352518/56048033-429bac80-5d0c-11e9-9c32-a4eafc3f4023.png)

*This use case is fixed in 1.1.4 (6826f63)*
![image](https://user-images.githubusercontent.com/13352518/56048063-534c2280-5d0c-11e9-8700-6b32c010eebc.png)

**Comment by PhotoNomad0** [comment]
@benjore - it looks like my fixes will handle the failures listed above.  So I'm getting close.

**Comment by PhotoNomad0** [comment]
Verified in https://tc-builds.door43.org/build/release-v1.1.4/translationCore-macos-x64-1.1.4-6826f63.dmg

**Comment by cckozie** [comment]
Moved to #6026
~~1.2.0 (a3b50df)~~
~~[en_ult_tit_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/3129115/en_ult_tit_book.zip)~~

~~Scripture pane loses resources when navigating to Titus 1:4 under God the Father.~~
~~I'm not sure that this problem is related to the work on this issue, but it was not a problem in 1.1.3.~~

~~[scripture_pane.mov.zip](https://github.com/unfoldingWord-dev/translationCore/files/3129097/scripture_pane.mov.zip)~~

~~Same problem on 3:5 under Holy Spirit~~
~~And all checks under Jesus~~
~~And 2:5 under Word of God~~

**Comment by PhotoNomad0** [comment]
@cckozie - this issue is actually a fix for 1.1.4 and don't think we have merged it into 1.2.0 yet.  Looking at problem opening this is 1.1.4 first.

**Comment by cckozie** [comment]
@PhotoNomad0 - My bad. Sorry, I can't keep up with all the versions:)

**Comment by cckozie** [comment]
@PhotoNomad0 - This was broken with the big ERROR in 1.1.4-39e7046. Import a usfm3 project and try to load it in tW.
It was working in 1.1.4 (6826f63).
[Tue Apr 30 2019.log.zip](https://github.com/unfoldingWord-dev/translationCore/files/3133027/Tue.Apr.30.2019.log.zip)

**Comment by PhotoNomad0** [comment]
verified in https://tc-builds.door43.org/build/release-v1.1.4/translationCore-macos-x64-1.1.4-ee8fa08.dmg

**Comment by cckozie** [comment]
1.1.4 (ee8fa08)
Multiple checks are highlighted in the group menu.
This was working correctly in 1.1.3
![image.png](https://images.zenhubusercontent.com/55e5f3984f7a08fbb7f4a658/f7504863-c179-40a8-9c13-fe555012ad1b)

Some other examples in [41-MAT.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/3138284/41-MAT.usfm.zip)
Mat 24:30 and 26:24 under Son of Man

**Comment by PhotoNomad0** [comment]
@cckozie - wow, that is a mystery one since I didn't touch group menu. Looking into it.

**Comment by PhotoNomad0** [comment]
@cckozie Trying with `translationCore 1.1.4 (040de06)`:
Did not see the problem with luke projects I had already loaded, but I do see it when I import a new USFM project.

**Comment by PhotoNomad0** [comment]
Fix for group menu items that have array of quote words.

verified in 1.1.4 (23a7fbd)

**Comment by cckozie** [comment]
All fixed in 1.1.4 (e7e858a)
