### ISSUE TITLE
Truncation issues in check pane (tW)

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5971]
### User Story

As a [type of user], I want [some goal] so that [some reason].

### Features / Specifications

- [ ] Should be `"do ... accuse ... falsely"`
- [ ]
- [ ]

![image.png](https://images.zenhubusercontent.com/55e5f3984f7a08fbb7f4a658/9807556c-bb5a-4b64-ad81-c166df535ad0)

![image](https://user-images.githubusercontent.com/13352518/55973069-6bf40400-5c4a-11e9-9ded-7a5196d01922.png)
- [ ] Should be `"they were ... amazed"`

## These are correct: 
![image](https://user-images.githubusercontent.com/13352518/55973222-b7a6ad80-5c4a-11e9-8fdc-9da84ec4ad8c.png)

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by cckozie** [comment]
In 2.0.0 (ca6c273) the referenced problem selections do not exists since many of the ellipsis have been removed.
I expect that the underlying problem will likely be fixed in issue #6301.

**Comment by elsylambert** [comment]
Closing this issue. Not seeing in 2.2.0 (2375ae5).
