### ISSUE TITLE
Alignments are lost when OT projects are exported to USFM3 and then imported

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5972]
1.1.3 (f505bc4)
[08-RUT.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/3069527/08-RUT.usfm.zip)
Import this file
Note that alignments are 100% complete
Export to USFM including alignments
Import the exported USFM file giving it a new transaction ID
Note that alignments are now 0% complete
Load the project in wA
Note that alignment memory appears to be in tact

Exported file: [08-RUT3.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/3069569/08-RUT3.usfm.zip)

**Comment by cckozie** [comment]
I exported the fully aligned project to usfm2 and edited the text on verse 1 to change the first occurence of "when" to "of" so that is now reads "It happened in the days of the judges".
I then  reimported the edited usfm2 file and chose the Overwrite options.
Now all of the "of"s in the verse show as suggestions. Is that related to this issue or something else?
(An additional edit that was on a unique word in the verse was handled correctly.)
![image](https://user-images.githubusercontent.com/8171759/55982626-efb7eb80-5c5e-11e9-96e3-b809b674e3c1.png)

**Comment by PhotoNomad0** [comment]
@cckozie - Not related to this issue.  It is behaving correctly by current design.  It's related to how we keep track of alignments.  Basically when you changed the word count of `of`, it invalidated all of them because we can't be sure which occurrences relate to which alignments.  Then when you open WA wordmap is trying to be helpful.

Anyway it looks like it is behaving like it should.

**Comment by PhotoNomad0** [comment]
Or at least how I expect it should.

**Comment by PhotoNomad0** [comment]
I have determined that to get the invalidation error that would cause Ruth to be reset with Greek, you would have to  directly edit the data files.  Not a supported operation.

@cckozie - shall we close this or put it into QA watch?

**Comment by cckozie** [comment]
@PhotoNomad0 - I am writing a script to attempt to recreate the problem. I'm not convinced yet that we won't lose data.

**Comment by cckozie** [comment]
Ran into #5979 while running the test script. Curious as to whether this may have caused the loss of alignments in my original test.

**Comment by cckozie** [comment]
I think we're good in 1.2.0 (b485978)
