### ISSUE TITLE
Project upload or USFM export w/alignments with invalid alignments will reset all alignments in verse

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#5977]
### User Story

As a user I don't want all alignments removed for a verse on export because of a small change.

#### Backstory
- we changed tCore so WA now does the validation checking whenever a Project is selected, but the USFM export validation is still using old checking code in tCore that will clear all alignments in verse. WA will just invalidate the affected words.
- the only way I think this could be a problem is if the user downloads an updated UGNT that causes an invalidation.  If the user then uploads or exports the project before opening WA, whole verses will have alignments cleared.

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by elsylambert** [comment]
Not seeing this issue in 2.2.0 (2375ae5).
