### ISSUE TITLE
Display the tN correctly in the Scripture Pane

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5982]
Related to #5970, just for tN (not tW). 

It appears there are two problems: 
- [ ] Occurrence issues (as with the tW tool)
- [ ] Greek words with punctuation next to them seem to sometimes not being rendered correctly.

(All screen shots from translationCore 1.2.0 (e6c3273) )

Exhibit A
![image](https://user-images.githubusercontent.com/13352518/56309377-1a96b980-610f-11e9-8642-93632974aa5e.png)

![image](https://user-images.githubusercontent.com/13352518/56309424-2a160280-610f-11e9-841b-dbfb8a1b28ff.png)

Exhibit B
![image](https://user-images.githubusercontent.com/13352518/56309508-53369300-610f-11e9-93d8-257d0cd3c745.png)

![image](https://user-images.githubusercontent.com/13352518/56309585-76614280-610f-11e9-8db1-1d20de21bc18.png)

Exhibit C
![image](https://user-images.githubusercontent.com/13352518/56309732-baecde00-610f-11e9-8184-949b701ebe35.png)

Exhibit D (Same problem as C)
![image](https://user-images.githubusercontent.com/13352518/56309830-ec65a980-610f-11e9-8258-c668644e074f.png)

Exhibit E (Two problems: Wrong `tois` + missing `apistois` (and the tN is missing a `...`)
![image](https://user-images.githubusercontent.com/13352518/56310015-60a04d00-6110-11e9-983a-9f4999ba0c7c.png)

![image](https://user-images.githubusercontent.com/13352518/56310068-875e8380-6110-11e9-8328-b3eeb0c65291.png)

**Comment by mannycolon** [comment]
Verified on d83e51a

**Comment by cckozie** [comment]
1.2.0 (d83e51a) 
I'm writing up a new issue because we may need to do migrations of existing projects. (#6134)
Old project:
![image](https://user-images.githubusercontent.com/8171759/59218298-87658780-8b85-11e9-9d1f-37821037c820.png)

Newly imported project:
![image](https://user-images.githubusercontent.com/8171759/59218451-ea571e80-8b85-11e9-8ae6-da2faeab8ab6.png)

**Comment by mannycolon** [comment]
@cckozie Did you delete it your old translation Notes folder from your English resources and redownloaded it?

**Comment by cckozie** [comment]
@mannycolon - No, but I did do a download of the latest English resources. Shouldn't that replace it?
(I'm not planning to fail this issue because of this problem. Just noted it here and the new issue here.)

**Comment by mannycolon** [comment]
@cckozie I would suggest deleting it and redownloading it. Because we only use the timestamps & resource version to get new resources. We need to add a story to check for new resources based on the version of the parser that was used to parse the resource.

**Comment by cckozie** [comment]
@mannycolon 
Deleted translationNotes folder and restarted tC. No change.
Deleted en folder and restarted tC. No change.
Downloaded latest English resources. No change.
Also, if it is a resources problem, why would newly imported projects be correct and existing 1.1.3 projects be broken?

**Comment by mannycolon** [comment]
@cckozie 
It seems like the old project files cache is not being updated. It is supposed to be updated every time a new resource is downloaded.

**Comment by cckozie** [comment]
I'll update #6134 with the suggestion about the cache.

**Comment by benjore** [comment]
When demoing, include #5998

**Comment by cckozie** [comment]
@mannycolon 
1.2.0 (2372490)
I found one that is wrong that was not on your list. I don't know if it's content or tC, and if it is tC, is it related to this issue or not. Some words in the quote are not highlighted in the ULT or UGNT. Is this the same as the last one we were talking about in the sprint planning?
![image](https://user-images.githubusercontent.com/8171759/59381516-207cd580-8d21-11e9-9b2c-8caad071dc86.png)
![image](https://user-images.githubusercontent.com/8171759/59381589-62a61700-8d21-11e9-83a8-f8df4d5d0fc1.png)

**Comment by mannycolon** [comment]
@cckozie I looked at the TSV file and it looks like we are highlighting the correct text in the ULT. So the `of the` should not be in the information area of the select mode screen.

If I'm not mistaken I think theres another issue somewhere that addresses that bug.


![Screen Shot 2019-06-19 at 2 32 31 PM](https://user-images.githubusercontent.com/17072300/59790963-17e74a80-929f-11e9-972a-1adf830aad4c.png)

**Comment by mannycolon** [comment]
@cckozie #6143 is the issue that will address the bug mentioned above

**Comment by elsylambert** [comment]
@manny - For your review. 
![glquote](https://user-images.githubusercontent.com/51806180/60467661-35b09a00-9c25-11e9-9c42-ab494e5fa906.jpg)
Here is the project: 
[en_uold_tit_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/3347392/en_uold_tit_book.zip)

Please note: Verses titus 1:9, 1:14, 3:14 ; I checked for few verses and these verses have a different glQuote text than whats highlighted in the scripture pane.
Also, there is no Alignment Data for this project.
Here is the json file:

[figs-metaphor.zip](https://github.com/unfoldingWord-dev/translationCore/files/3347415/figs-metaphor.zip)
[figs-doublenegatives.zip](https://github.com/unfoldingWord-dev/translationCore/files/3347421/figs-doublenegatives.zip)

**Comment by mannycolon** [comment]
@elsylambert 

By looking at the alignment data of the English ULT bible I notice we are actually highlighting the correct words. 

See verse 9 of chapter 1 below: (Look specifically at the children (which is an array) in the first object)


```
"9": {
    "verseObjects": [
      {
        "tag": "zaln",
        "type": "milestone",
        "strong": "G04720",
        "lemma": "ἀντέχω",
        "morph": "Gr,V,PPM,AMS,",
        "occurrence": 1,
        "occurrences": 1,
        "content": "ἀντεχόμενον",
        "children": [
          {
            "text": "He",
            "tag": "w",
            "type": "word",
            "occurrence": 1,
            "occurrences": 1
          },
          {
            "type": "text",
            "text": " "
          },
          {
            "text": "should",
            "tag": "w",
            "type": "word",
            "occurrence": 1,
            "occurrences": 1
          },
          {
            "type": "text",
            "text": " "
          },
          {
            "text": "hold",
            "tag": "w",
            "type": "word",
            "occurrence": 1,
            "occurrences": 1
          },
          {
            "type": "text",
            "text": " "
          },
          {
            "text": "tightly",
            "tag": "w",
            "type": "word",
            "occurrence": 1,
            "occurrences": 1
          },
          {
            "type": "text",
            "text": " "
          },
          {
            "text": "to",
            "tag": "w",
            "type": "word",
            "occurrence": 1,
            "occurrences": 2
          }
        ],
        "endTag": "zaln-e\\*"
      },
      {
        "type": "text",
        "text": " "
      },
      {
        "tag": "zaln",
        "type": "milestone",
        "strong": "G35880",
        "lemma": "ὁ",
        "morph": "Gr,EA,,,,GMS,",
        "occurrence": 1,
        "occurrences": 1,
        "content": "τοῦ",
        "children": [
          {
            "text": "the",
            "tag": "w",
            "type": "word",
            "occurrence": 1,
            "occurrences": 1
          }
        ],
        "endTag": "zaln-e\\*"
      },
      {
        "type": "text",
        "text": " "
      },
      ...
    ]
  },
```

The following words are aligned to the Greek word 

```
"children": [
          {
            "text": "He",
            "tag": "w",
            "type": "word",
            "occurrence": 1,
            "occurrences": 1
          },
          {
            "type": "text",
            "text": " "
          },
          {
            "text": "should",
            "tag": "w",
            "type": "word",
            "occurrence": 1,
            "occurrences": 1
          },
          {
            "type": "text",
            "text": " "
          },
          {
            "text": "hold",
            "tag": "w",
            "type": "word",
            "occurrence": 1,
            "occurrences": 1
          },
          {
            "type": "text",
            "text": " "
          },
          {
            "text": "tightly",
            "tag": "w",
            "type": "word",
            "occurrence": 1,
            "occurrences": 1
          },
          {
            "type": "text",
            "text": " "
          },
          {
            "text": "to",
            "tag": "w",
            "type": "word",
            "occurrence": 1,
            "occurrences": 2
          }
        ],
```

**Comment by mannycolon** [comment]
**Same for 1:14**

```
  "14": {
    "verseObjects": [
      ...,
      {
        "tag": "zaln",
        "type": "milestone",
        "strong": "G06540",
        "lemma": "ἀποστρέφω",
        "morph": "Gr,V,PPM,GMP,",
        "occurrence": 1,
        "occurrences": 1,
        "content": "ἀποστρεφομένων",
        "children": [
          {
            "text": "who",
            "tag": "w",
            "type": "word",
            "occurrence": 1,
            "occurrences": 1
          },
          {
            "type": "text",
            "text": " "
          },
          {
            "text": "turn",
            "tag": "w",
            "type": "word",
            "occurrence": 1,
            "occurrences": 1
          },
          {
            "type": "text",
            "text": " "
          },
          {
            "text": "away",
            "tag": "w",
            "type": "word",
            "occurrence": 1,
            "occurrences": 1
          },
          {
            "type": "text",
            "text": " "
          },
          {
            "text": "from",
            "tag": "w",
            "type": "word",
            "occurrence": 1,
            "occurrences": 1
          }
        ],
        "endTag": "zaln-e\\*"
      },
      {
        "type": "text",
        "text": " "
      },
      {
        "tag": "zaln",
        "type": "milestone",
        "strong": "G35880",
        "lemma": "ὁ",
        "morph": "Gr,EA,,,,AFS,",
        "occurrence": 1,
        "occurrences": 1,
        "content": "τὴν",
        "children": [
          {
            "text": "the",
            "tag": "w",
            "type": "word",
            "occurrence": 2,
            "occurrences": 2
          }
        ],
        "endTag": "zaln-e\\*"
      },
      {
        "type": "text",
        "text": " "
      },
      {
        "tag": "zaln",
        "type": "milestone",
        "strong": "G02250",
        "lemma": "ἀλήθεια",
        "morph": "Gr,N,,,,,AFS,",
        "occurrence": 1,
        "occurrences": 1,
        "content": "ἀλήθειαν",
        "children": [
          {
            "text": "truth",
            "tag": "w",
            "type": "word",
            "occurrence": 1,
            "occurrences": 1
          }
        ],
        "endTag": "zaln-e\\*"
      },
   ]
}
```

**Comment by elsylambert** [comment]
Verified in 1.2.0 (8505e23). tN is displayed correctly in the Scripture Pane.
needs regression.

**Comment by cckozie** [comment]
1.2.0 (9f6a878)
Not seeing any issues at this point.
