### ISSUE TITLE
Fix the Nepali issue

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5985]
Most of the projects in this repo have tons of invalidations. There has been a lot of Slack traffic as to what the problem might be. 

1 - Nail down what the problem is
2 - Figure out the best way to solve the problem going forward
3 - Figure out if there is any way to migrate the projects/recover the alignment data for the existing projects

**Comment by benjore** [comment]
Russ Perry   [Apr 1st at 3:17 AM]
@ben_jore We are reviewing some of the alignment work that HTS is doing for the Nepali NT. The project manager had copied the project folder from the aligner's computer to his (PM's) computer, and then the PM uploaded the project to Door43. When I imported the online project and opened it in tC 1.1.2, it shows 61 invalidated alignments. I'm trying to understand how those invalidated alignments happened. No editing of the text was done between the aligner to the PM to my computer. The project is here:
https://git.door43.org/hblamtari/ne_ult_col_book
23 replies

Russ Perry   [16 days ago]
When I imported Acts, it showed 641 invalidated alignments.
https://git.door43.org/hblamtari/ne_ult_act_book (edited)

Ben Jore   [16 days ago]
Do you know what version of tC the aligners used?

Russ Perry   [16 days ago]
1.0.1 @ben_jore

Russ Perry   [16 days ago]
I uninstalled 1.1.2 and installed 1.0.0 (don't have a copy of 1.0.1) and it showed invalidated in that version also but doesn't give a count.

Jobby Prasannan   [16 days ago]
Ben this is something that we had discussed some time ago

Jobby Prasannan   [16 days ago]
this is the same problem with the hindi project aswell

Russ Perry   [16 days ago]
@ben_jore Is this the same as issue #4865? The last question in that issue is one I have also: "Why does the app think that changes were made? What is it measuring against since this is a new import?"

Manny Colon   [16 days ago]
This could possibly be caused by different versions of the app using different versions of the original language.

Russ Perry   [16 days ago]
@mannycolon Is there a list of which version of UGNT was used with each version of tC?

Manny Colon   [16 days ago]
No that I know of

Russ Perry   [16 days ago]
If this true, we need to figure out how to manage this. We can't have thousands of verses go invalid in dozens of GL Bibles just because we change versions of the UGNT.

Russ Perry   [16 days ago]
That would be unmanageable.

Russ Perry   [16 days ago]
But before I jump to that conclusion, it sounds like we need to solve exactly what is causing the invalidations.

Ben Jore   [16 days ago]
There haven't been a thousand changes to the UGNT total. Pretty sure it's not that. (edited)

Russ Perry   [16 days ago]
Must be something else causing it then since Nepali Acts had over 460.

Ben Jore   [16 days ago]
Was it working on the PM's machine?

Ben Jore   [16 days ago]
Can the original guys upload their work on to Door43?

Bruce McLean   [16 days ago]
Taking a look

Bruce McLean   [16 days ago]
If they were using 1.0.0, it looks like it may be an issue with tokenization that was fixed in 1.0.2.  That was to fix problem in Hindi that was splitting some words.  Don’t think we ever released 1.0.1.

Bruce McLean   [16 days ago]
@russperry - if you can get the original project that would help us a lot to be able to migrate it. (edited)

Bruce McLean   [16 days ago]
Specifically would like a copy of the original project before it is opened in tC on another computer.   Maybe it could be zipped up. What was uploaded has no alignments in the first few verses.

Bruce McLean   [15 days ago]
@russperry - any progress trying to find the original project and zipping it up?

Russ Perry   [15 days ago]
Unfortunately, I looked into it today, and I'll not be able to do that. The project went through several changes of hands with a HDD format along the way. @bruce.mc

**Comment by benjore** [comment]
Russ Perry   [Apr 2nd at 6:39 AM]
I plotted a way forward for them to go a book at time and make backups and upload to see if they can isolate it. The alignments weren't completely finished anyway.
26 replies

Ben Jore   [15 days ago]
What can be developed in tC to help simplify this?

Larry Sallee   [15 days ago]
@ben_jore We have been using tC and D43 seamlessly to move alignment projects between users for over a year. At its base, this is a refusal to use the tested, prescribed path.

Ben Jore   [15 days ago]
If they have the bandwidth to upload their projects to dcs, that would be a much simpler method. No prs. Upload to dcs. Import from aligners repos to managers tC. Upload to dcs when done.

Jesse Griffin   [15 days ago]
Is this the right workflow diagram for them: https://forum.ccbt.bible/t/tc-multiple-users-checking-the-same-book/167
CCBT Forum
tC Multiple Users Checking the Same Book
Currently, this is the recommended workflow for allowing multiple people to check the same book of the Bible. Here is the key principle: Only one person should have the project at any one time. Treat the project like a physical object that must be passed from one person to another. Here is an illustration: graph TB; A[Source Project hi_rom]-->B subgraph tC-User1 B[Import to tC]-->C[Check chapters 1-8] end subgraph DCS C-->D[Upload to User1/hi_rom] G e...
Dec 4th, 2018

Bruce McLean   [15 days ago]
If they are not going to use d43, then maybe we should implement an export project to zip, like ts does and renames the extension. (edited)

Bruce McLean   [15 days ago]
@russperry - what version of the app are they using?  If they are using 1.0.0, it would be helpful if we could get some examples of their projects so we could test migrating it to newer versions of tC. (edited)

Russ Perry   [15 days ago]
The Project Mgr is using 1.0.2. I'm not sure about the Greek expert (GE). The PM said the GE has 1.0.1 but you said that wasn't released. He will see the GE in a couple days and I told them to upgrade both to 1.1.2.

Russ Perry   [15 days ago]
@Larry Sallee The issue is not a refusal but they have been figuring this out on their own till I got here.  Comm in English is not seamless when we're face to face, much less via email. They are willing to do what is prescribed, but are still learning.

Bruce McLean   [15 days ago]
@russperry - think I found the problem, it looks like the `DEVANAGARI DANDA` is a punctuation character, but we are interpreting it as a word.

Russ Perry   [15 days ago]
@ben_jore They have the bandwidth and uploading is what I've told them to do now.

Ben Jore   [15 days ago]
The complicating factor with the upload is that they have to treat it like a hot potato... only one person can be working on the same project at the same time... otherwise it will be forked and merging projects is not currently supported.

Russ Perry   [15 days ago]
The process I've told them to follow is:
PM & GE will meet and update tC to 1.1.2
They will together finish aligning Philemon
Upload the project from GE's computer to his Door43 repo
PM will import online project and check/compare alignments
PM will upload the project to his Door43 repo
PM will notify me and I will check it for invalidated alignments
If all is good, PM will submit an STR
From then on, the GE will complete one book at a time and upload to his repo from his home and notify PM, who will continue the process.

Bruce McLean   [15 days ago]
@russperry I wonder if they were using an older version 0.10.1.  Checking to see if that would cause the problems we are seeing.

Russ Perry   [15 days ago]
It was last Oct or Nov when they started playing with alignment.

Bruce McLean   [15 days ago]
0.10.1 was released in Aug 23, 2018

Bruce McLean   [15 days ago]
1.0.0 was released in Sep 28, 2018

Bruce McLean   [15 days ago]
so I think they had 0.10.1

Russ Perry   [15 days ago]
You are probably right. Checked my email archives and the PM tried an alignment of Titus in Aug 2018 to determine the time required for the process so they could give us a quote for the NT. They didn't start the alignment project till Oct, but it is possible he would have given the aligners the version he was using back then. (edited)

Bruce McLean   [15 days ago]
@ben_jore - we probably should create an issue to save the version number of tCore the user is using.  Might help us going forward.  Don’t know how to handle if they load a project in an older version.

Russ Perry   [15 days ago]
So, can you confirm my advice to them to upgrade to 1.1.2 before they start aligning again?

Bruce McLean   [15 days ago]
Doing some testing before confirming that.

Russ Perry   [15 days ago]
@bruce.mc Above you asked for samples of their projects. See the repo here for several books:
https://git.door43.org/hblamtari

Russ Perry   [15 days ago]
That's the PM's repo.

Bruce McLean   [14 days ago]
Sorry, I’ve been slow responding here, but exploring possibility of recovering the alignments.  Seems doable, but won’t know for sure until I try.

Russ Perry   [14 days ago]
Thanks @bruce.mc that's good to hear there is a possibility.

Bruce McLean   [14 days ago]
It looks like there may be a bug in the (1.0.0 to 1.0.2) WA importing from older WA (0.10.1 and lower) that it flags verses as invalid and resets all the alignments, but unfortunately they did not save the project before they opened the project in a newer version before it was saved, so no way of recovering the data without the original project.

Using 1.1.2 or newer would archive all the changes, so we could recover the data.   Will look at the state of some of the other projects.

**Comment by benjore** [comment]
Bruce McLean   [Apr 2nd at 9:22 AM]
@russperry In digging in further, in chapter 1:13 I am seeing a stand-alone character at the end of the line that may be messing up the alignments on importing to 1.0.2 - called `DEVANAGARI DANDA` unicode 964.  Looking into it.
20 replies

Bruce McLean   [15 days ago]
the project version in the manifest means that it could have been done on tCore versions 0.10.0 to 1.0.0.

Bruce McLean   [15 days ago]
@klappy @ben_jore - it looks like the `DEVANAGARI DANDA` is a punctuation character, but we are interpreting it as a word.

klappy   [15 days ago]
That shouldn’t be a problem as long as it’s consistent between versions...

klappy   [15 days ago]
Either way we should have them help us test our tokenizer as step 1.

Bruce McLean   [15 days ago]
It’s been consistent since tCore 1.0.2, when we changed tokenizer

Bruce McLean   [15 days ago]
still trying to figure out how they got the alignment data in the state it’s in.  Will try 0.10.1.

Russ Perry   [15 days ago]
One revolutionary thing I showed them was that they can combine Greek words. They had a lot of words unaligned because they couldn't figure out how to make them fit. So they need to go back over everything anyway.

Ben Jore   [15 days ago]
OK. Make sure they know they can click on the Greek word to get the lexicon info. Also, they can click on multiple words in the word bank to move multiple words at once.

Russ Perry   [15 days ago]
Yes, I showed them those things.

klappy   [15 days ago]
Each language introduced has the potential to introduce new special chars that aren’t identifiable as punctuation or white space without input from the translation team, or somebody that knows that language. I don’t have an answer but think it would be important for us to find these before alignment begins.

klappy   [15 days ago]
@bruce.mc maybe a single page testing app to test your language by pasting in a paragraph of text?

Russ Perry   [15 days ago]
FYI, Nepali uses the same script as Hindi

klappy   [15 days ago]
Many of the languages of the same language family are 98% overlap in characters but differ in that small percentage are typically punctuation and control characters.

klappy   [15 days ago]
I’m trying to figure out what we can learn from this and if we can get out in front of future issues.

klappy   [15 days ago]
I can envision a light wrapper for the tokenizer to test it by the language teams and tell us if they find any issues.

Ben Jore   [15 days ago]
@klappy @bruce.mc I'm thinking through an automated tokenization verification process in tC. The mockup is going to be simple, I'd like to follow up with y'all and see how feasible it would be on the back-end. But basically, it would search through a project and find characters that could be tokenized different ways, then give the user the option of "split it this way, or this way?". Then it could walk the user through the whole project and let them choose how to split words. This could be saved per language. But on importing a new project, if there is a new character that hasn't showed up yet, it would trigger it again. Thoughts?

Bruce McLean   [15 days ago]
It seems like you would have to save the tokenization settings with the project also, or the next person that opens it will get a lot of invalidations.

Bruce McLean   [15 days ago]
@ben_jore @klappy found a list of punctuation characters in unicode - only 584 https://www.compart.com/en/unicode/category/Po
https://www.compart.com/en/unicode/category/Po
Find all Unicode Characters from Hieroglyphs to Dingbats – Unicode Compart
All Unicode Symbols with Names and Descriptions on One Page

Bruce McLean   [15 days ago]
It looks like the latest string-punctuation-tokenizer properly recognizes `DEVANAGARI DANDA` as punctuation, so I suspect a logic bug in the wA tool. @klappy

Russ Perry   [1 day ago]
@bruce.mc @klappy This is one of the issues that may be outstanding. I'm not clear what the resolution of this is. Is there a problem with the alignment data because they used too old a version of tC (0.10.x?) or is there an existing bug in the wA tool that you mentioned, Bruce, in your last post above? Is there an issue for that?

**Comment by PhotoNomad0** [comment]
added comments to https://github.com/unfoldingWord-dev/translationCore/issues/5988 that itemizes issues found.

@benjore - to address the problem, we have already added commits to git to save incremental work and have made changes to WA so it doesn't invalidate the whole verse. 

The only additional thing I can think of to add is maybe on opening old projects, we do a git commit before doing any validation checking, migration, etc. (anything that would change the project). This would protect if there is no saved git history or it is not up to date.

**Comment by PhotoNomad0** [comment]
@cckozie - this just adds git save to old projects before changes are made to project - we hooked into project migration which gets called during project selection, local import, online import, USFM export.  But also added a specific call before project upload.

You might take a look at test instructions at https://github.com/unfoldingWord-dev/translationCore/pull/6051 for ideas how to test, but note that you will see `git log` entries with comment `Migrating Old Project` only when there are unsaved file changes.

Verified in translationCore 1.1.4 (eb0fe46)

**Comment by cckozie** [comment]
1.1.4 (eb0fe46)
Git save was executed during:
- Selection of old project
- Import of USFM project
- Export of old project to USFM w/alignments
- Export of old project to USFM w/o alignments
- Import of old project from DCS
- Upload of old project to DCS
- Import of tstudio project
