### ISSUE TITLE
The actual application log (from the file system) is not attached to the Trello card on the  Door43 Helpdesk

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5990]
1.1.3 (cf7905c) 
Dup of #5836? - yes @PhotoNomad0 
Here is a link to the Trello card: https://trello.com/c/2TqJm73R/77-tc-general-feedback
Here is the log file: [https://app.zenhub.com/files/65028237/5b85b03e-d520-417d-9d75-2d6e7f27e02f/download](https://app.zenhub.com/files/65028237/5b85b03e-d520-417d-9d75-2d6e7f27e02f/download)

**Comment by PhotoNomad0** [comment]
Will be fixed by https://github.com/unfoldingWord-dev/translationCore/pull/6274 - attaches the last 25MB of todays log file to report when selected.

**Comment by PhotoNomad0** [comment]
This was mistakenly closed.

**Comment by elsylambert** [comment]
Working fine in 2.0.0 (8a6a8c5).

**Comment by cckozie** [comment]
2.0.0 (8a6a8c5) 
After performing other tests this morning I tried testing this. The log.zip file did show up in the Forum, but the log.txt file was empty.
[log (1).zip](https://github.com/unfoldingWord-dev/translationCore/files/3506312/log.1.zip)
![image](https://user-images.githubusercontent.com/8171759/63109182-35a6f800-bf4e-11e9-8a32-0cf480f487ce.png)

I have not been able to replicate the problem. Will try again later.

**Comment by cckozie** [comment]
2.0.0 (3727b58) 
I still have not been able to replicate the problem of the log file being empty, so I'm passing it.
