### ISSUE TITLE
Alignments get invalidated when upgrading from 0.9 and 0.10

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5993]
1.1.3 (cf7905c) 
May be related to #5985 
When upgrading from older releases, some alignments get invalidated and sometimes the number of broken links on the tool card do no match up with the change in % complete.
These projects are from 0.9.1
[0.9.1 projects.zip](https://github.com/unfoldingWord-dev/translationCore/files/3109347/0.9.1.projects.zip)

| Project 	| wA% in 0.9.1 	| wA% in 1.1.3 	| wA resets in 1.1.3 	| verses reset                   	|
|---------	|--------------	|--------------	|--------------------	|--------------------------------	|
| en_1ti  	| 3%           	| 1%           	| 4                  	| 1:2, 1:12, 1:14,,1:16          	|
| en_acts 	| 100%         	| 97%          	| 5                  	| 2:47, 3:1, 10:19, 19:40, 19:41 	|
| en_mat  	| 25%          	| 11%          	| 0                  	| None                           	|

These projects are from 0.10.1
[0.10.1 projects.zip](https://github.com/unfoldingWord-dev/translationCore/files/3109351/0.10.1.projects.zip)

| Project         	| wA% in 0.9.1 	| wA% in 1.1.3 	| wA resets in 1.1.3 	| verses reset                              	|
|-----------------	|--------------	|--------------	|--------------------	|-------------------------------------------	|
| en_ult_tit_book 	| 80%          	| 80%          	| 8                  	| 1:4, 1:5, 1:15, 2:10, 2:15, 3:4,3:6, 3:15

**Comment by PhotoNomad0** [comment]
Related to updated ugnt?

**Comment by elsylambert** [comment]
Not seeing this issue with updated ugnt bundled with the app in  2.2.0 (2375ae5).
