### ISSUE TITLE
All translationWord category checkboxes are cleared when existing project is selected after upgrade to 1.2

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5996]
1.2.0 (d3d469b)
Here is a project from v1.1.3 [en_thre_tit_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/3113862/en_thre_tit_book.zip)
This is also a problem with at least some projects imported from Door43. https://git.door43.org/tc01/en_ultt_tit_book

I had several existing projects in 1.1.3 where all 3 tW categories were selected on the tool card. After upgrading to 1.2, when each project is selected the tW tool card now has no categories selected.
Once the category is again selected, it is maintained in 1.2.
For new projects imported after 1.2 is installed, all checkboxes on the tW card are checked as expected.

**Comment by PhotoNomad0** [comment]
@cckozie @benjore - I think this is also a problem in 1.1.4

**Comment by cckozie** [comment]
@PhotoNomad0 - So 1.1.4 was not a branch off of 1.1.3?

**Comment by PhotoNomad0** [comment]
Verified in https://tc-builds.door43.org/build/release-v1.1.4/translationCore-macos-x64-1.1.4-39e7046.dmg

**Comment by PhotoNomad0** [comment]
@benjore - sorry, but I already added this to 1.1.4 since it was the same fix as for 1.2.0

**Comment by cckozie** [comment]
1.2.0 (d50041c)
Does not work with either of the projects reference at the top of the first comment.

It does work in 1.1.4 (39e7046)

**Comment by PhotoNomad0** [comment]
@cckozie - this has been implemented in 1.1.4 first, will get merged into 1.2.0 after it has been verified.  Looking at the projects listed.

**Comment by PhotoNomad0** [comment]
@cckozie - in build https://tc-builds.door43.org/build/release-v1.1.4/translationCore-macos-x64-1.1.4-040de06.dmg, I tested https://git.door43.org/tc01/en_ultt_tit_book and it shows all categories selected.  Looked at en_thre_tit_book.zip and that also shows all categories selected.

**Comment by cckozie** [comment]
@PhotoNomad0 - Interesting. Using 1.1.4 (040de06) and importing the two referenced projects, they do show the category checkmarks on the tW card. However, when importing a new usfm2 or usfm3 file, the checkmarks are still cleared.
I see we have a newer 1.1.4. Downloading now. I'll give it a try.
Still the same in 1.1.4 (23a7fbd)

**Comment by PhotoNomad0** [comment]
Verified in translationCore 1.1.4 (e7e858a)

**Comment by cckozie** [comment]
Works as expected on imports, downloads, and upgrades in 1.1.4 (e7e858a)

**Comment by cckozie** [comment]
1.2.0 (9c1cf66) 
[en_ult_2ti_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/3278653/en_ult_2ti_book.zip)

This problem has reappeared. The attached project was imported in 1.1.4 and never opened in a tool. After loading 1.2 the tW category checkboxes are all cleared.

**Comment by RoyalSix** [comment]
Verified in 7caed9f

**Comment by cckozie** [comment]
Not seeing a problem in 1.2.0 (cf6fd22)
Needs regression

**Comment by elsylambert** [comment]
Verified in  1.2.0 (4b9a560) .
Not seeing any issues.

**Comment by cckozie** [comment]
This problem has reappeared in 2.0.0 (00bca0b)
This project is in a 1.1.4 build and has all tW checkboxes checked on the tool card. After upgrading to 2.0 and selecting it, all tW checkboxes are cleared. (I see the same behavior if I just copy the project into the 2.0 build)
[en_new_rut_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/3432604/en_new_rut_book.zip)

**Comment by cckozie** [comment]
No longer seeing the issue in 2.0.0 (cd0f9f1)

**Comment by elsylambert** [comment]
Not seeing the issue in 2.0.0 (8f84296).
