### ISSUE TITLE
tN data is not being highlighted in the Scripture Pane (or displayed in the Check pane)

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5998]
1.2.0 (d3d469b)
![image](https://user-images.githubusercontent.com/8171759/56671696-b2018c80-667a-11e9-8407-3f4bfaf44255.png)

**Comment by RoyalSix** [comment]
https://team43.slack.com/archives/G927YPW04/p1556846662016500

**Comment by cckozie** [comment]
I'm not seeing any change in the latest build, 1.2.0 (cc9c5b5) and 1.2.0 (5ee926c) 
I tried it with a fresh install. Also tried updating English sources. Still am seeing the same problem.
![image](https://user-images.githubusercontent.com/8171759/57246663-61d3e400-7003-11e9-8763-93f5b67ea0dc.png)

**Comment by RoyalSix** [comment]
@cckozie Can you share the project?

**Comment by cckozie** [comment]
@RoyalSix 
[55-1TI.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/3158813/55-1TI.usfm.zip)

**Comment by benjore** [comment]
Note: It is not actually the entire verse. It is a (large) quote that includes all the verse except the last word. That matches the JSON & the TSV file. This leads me to conclude that it is not a TSV -> JSON converter issue, but a JSON -> Display issue. (This issue shows up in multiple places.) @cckozie

**Comment by cckozie** [comment]
I'm also seeing related (I think) problems in 1.2.0 (1612995) 
[en_ult_mrk_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/3167129/en_ult_mrk_book.zip)

Load this project in tN.
Navigate to 10:30 under Abstract Nouns
Note that there are no highlights in the UGNT, and that the user is instructed to 'Please select the translation for ""'. The same is true for many verses in several categories.
![image](https://user-images.githubusercontent.com/8171759/57538197-8256b380-730d-11e9-8015-e9e71c7b20d9.png)

**Comment by mannycolon** [comment]
The current Mark tsv file does not have an original language quote for `Abstract Nouns Mark 10:30.` Therefore, after my changes, it will not show up in tC.

**Comment by cckozie** [comment]
1.2.0 (2fea0fd) 
The example in the first comment has been fixed.
The check in the Mark example now no longer shows up.
