### ISSUE TITLE
The helps pane is empty in tN

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#5999]
1.2.0 (d3d469b) 
![image](https://user-images.githubusercontent.com/8171759/56671853-f5f49180-667a-11e9-8dec-98205c670593.png)

- [ ] The tHelps pane needs to display the tA article for the category, in the screenshot above, it would be `Abstract Nouns` (i.e. https://door43.org/u/unfoldingWord/en_ta/633054c931/03-translate.html#figs-abstractnouns )

**Comment by cckozie** [comment]
1.2.0 (521546e) 
The tHelps pane is no longer empty, but I seems like there are line feeds are doubled in some sections.

![image](https://user-images.githubusercontent.com/8171759/57642688-956fba80-757d-11e9-89d3-9e243144dde1.png)

![image](https://user-images.githubusercontent.com/8171759/57642944-2777c300-757e-11e9-9531-0121daa87da6.png)

**Comment by RoyalSix** [comment]
daee8ab

**Comment by elsylambert** [comment]
#1.2.0 (f134cbf)
@RoyalSix -tN help pane is displayed, but there is formatting issue in the help pane. Please refer to the comparison between Translation Academy and the help pane, as shown in the snapshot:
Steps to replicate:
- Open the project in tN
- Select the Menu option: Active or Passive.
- Scroll down to " Examples of Translation Strategies applied" section. Please note that the numbering is wrong.

![tN help pane](https://user-images.githubusercontent.com/51806180/60067291-13c09000-96d8-11e9-8e54-97a595767a36.jpg)

This is happening for the following Menus:
Double Negatives, Doublet, Euphemism, Hyperbole and Generalization, Hypothetical Situations, Idioms,  Metaphor, Metonymy, Parallelism, Personification, Reflexive Pronoun, Rhetorical Questions, Simile,

**Comment by RoyalSix** [comment]
It looks like the content is actually wrong.
If you see towards the bottom there are three `1s`
https://git.door43.org/unfoldingWord/en_ta/raw/branch/master/translate/figs-activepassive/01.md
![image](https://user-images.githubusercontent.com/8171759/60212954-1af6b380-9828-11e9-9593-01e11e8bba69.png)

Github is parsing it incorrectly and showing it as `1, 2, 3`
https://git.door43.org/unfoldingWord/en_ta/src/branch/master/translate/figs-activepassive/01.md
![image](https://user-images.githubusercontent.com/8171759/60213027-3d88cc80-9828-11e9-906d-ecbefe4ac41b.png)

**Comment by elsylambert** [comment]
@RoyalSix Yes, Towards the end the numbering is showing as 1, 1, 1... that is the issue in all the mentioned Menu options in my comment "This is happening for the following Menus:
Double Negatives, Doublet, Euphemism, Hyperbole and Generalization, Hypothetical Situations, Idioms, Metaphor, Metonymy, Parallelism, Personification, Reflexive Pronoun, Rhetorical Questions, Simile,"

**Comment by elsylambert** [comment]
Category selections: #poetry and #predectivepast still shows as 1,1,1.

**Comment by RoyalSix** [comment]
I think these are actually problems with the content as you can see here it is 1, 1, 1
https://git.door43.org/unfoldingWord/en_ta/src/branch/master/translate/writing-poetry/01.md
Also here https://git.door43.org/unfoldingWord/en_ta/src/branch/master/translate/figs-pastforfuture/01.md

**Comment by elsylambert** [comment]
@RoyalSix Help pane is not showing up for any Category in 1.2.0 (a3ee18b). 
![help pane missing articles](https://user-images.githubusercontent.com/51806180/60826696-7310ac80-a17c-11e9-935b-d1d57338d043.png)

**Comment by RoyalSix** [comment]
https://tc-builds.door43.org/build/develop/translationCore-macos-x64-1.2.0-cf77eea.dmg

**Comment by elsylambert** [comment]
Verified in 1.2.0 (9f6a878). Help pane in tN is displayed correctly. Other than the content issue with numbering, not seeing any issue with tN help.

**Comment by cckozie** [comment]
Not seeing any missing helps text in 1.2.0 (9f6a878) 
Needs regression
