### ISSUE TITLE
Invalidations are not being displayed on the tW and tN tool cards, and not being properly reset in tN

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6001]
1.2.0 (d3d469b)
(This should possibly be a failure on #5941 or  #5837.)
~[en_test_tit_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/3113199/en_test_tit_book.zip)~
[en_tst_tit_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/3315696/en_tst_tit_book.zip)

Open this fully aligned project and note that there is one tW check in "faith" and one tN check in "abstract nouns" completed on verse 2:2.
In the tW check pane, edit verse 2:2 to change the word "faith" to "belief".
Note that the invalidations alert is displayed.
Go to the tools page
Note that the only card indicating an invalidation is the wA card.
Load the project in tN
Note that on the previously completed check part of the highlights is gone, but there is still a check mark on the check in the menu and in the icon bar, and all of the previously selected text is still displayed on the check's menu tile.
![image](https://user-images.githubusercontent.com/8171759/56675515-e0cf3100-6681-11e9-8459-0fc91aa9dc8f.png)

(If in tN the entire text "sound in faith, in love, and in perseverance" is selected and the same edit is performed, then the entire highlight is removed and the check is not displayed in the icon bar, but the tile in the menu is still as before.)

If an edit is performed that only changes some of a tN selection, the selections reset alert is NOT displayed and tN still shows the partial selection.

**Comment by PhotoNomad0** [comment]
@cckozie - I have made fixes for external edits, but part of the problem is that this project has tN selections made by an older develop version 1.2.0 that saved the quote as a string, not an array of word occurrences.  I believe this is due to @mannycolon 's change to highlight the correct instance of the word.  I don't think we want to write data migrations for an unreleased interim build, but it does open the question about how we deal with changes in the tN quote strings or original language occurrences in the future. @benjore

**Comment by PhotoNomad0** [comment]
@cckozie - still looking at why some selections are not displayed on verse in tN tool.

**Comment by cckozie** [comment]
Works in 1.2.0 (7caed9f)
Needs regression

**Comment by cckozie** [comment]
1.2.0 (cf6fd22)
Not seeing migration errors in console when importing usfm projects, but am now seeing other issues when reimporting a project. 
[58-PHM.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/3321573/58-PHM.usfm.zip)
1. Imported this PHM project
2. Loaded in tN and made selections as instructed in 1:15 (Active or Passive) and 1:13 (Assumed Knowledge)
3. Loaded in tW and made selections as instructed in 1:10 (ancestor) and 1:1 (beloved)
4. Exported to usfm without alignments
5. Edited usfm file to invalidate the selections
[58-PHM.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/3321581/58-PHM.usfm.zip)
6. Imported the edited file choosing the Overwrite option
7. Observed the alert below quickly flash and was returned to the projects page
8. Selected the overwritten project and received the alert below. Cannot get to the tools page.
![image](https://user-images.githubusercontent.com/8171759/60033243-d6bfb380-966d-11e9-8345-cf6fbef677d5.png)

[en_ult_phm_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/3321603/en_ult_phm_book.zip)

**Comment by PhotoNomad0** [comment]
**Notes:**
- the exception occurs while loading tN (`t.api.triggerWillConnect(toolProps);`) and it is thrown by react.
- traced down to call to getSelectionsFromChapterAndVerseCombo().  Quote array was not supported, so correct file name was filtered out.  This led to undefined being passed to path.join().

**Comment by PhotoNomad0** [comment]
verified in translationCore 1.2.0 (4b9a560)

**Comment by cckozie** [comment]
Wrote up #6182 while testing the last use case above.
Also waiting on #5686 and #5832 for final testing.

**Comment by cckozie** [comment]
Now waiting on #6168
