### ISSUE TITLE
Username appears twice on successful DCS upload alert modal

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord/translationCore#6007]
### User Story

As a tC user, I want the successful DCS upload alert to only include my username once so that my OCD doesn't drive me nuts lol.

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]
## Additional Context
![Screen Shot 2019-04-24 at 7.57.14 PM.png](https://images.zenhubusercontent.com/576988c1bf93871ccd9cf7e4/66f5d97c-b08b-4dce-ad54-523b668adca1)

**Comment by benjore** [comment]
Dup of #4577
