### ISSUE TITLE
Spacing issues with the '\add' USFM marker - displaying in Scripture Pane

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#6008]
### User Story
Problems in this issue are related to:
https://git.door43.org/Door43-Catalog/en_t4t/raw/branch/master/44-JHN.usfm

![image.png](https://images.zenhubusercontent.com/55e5f3984f7a08fbb7f4a658/444cc3c3-f196-4d0b-bf0b-3d8ce6eeba13)

![image](https://user-images.githubusercontent.com/13352518/57035000-9bc57480-6c16-11e9-9345-5208e7c74f4a.png)

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by RobH123** [comment]
Related to this, tC 1.1.3 T4T John 18:38 (and other places) shows an EXTRA space after the opening quote. Original field is

\v 38 Pilate said to him, “\add How can anyone know\add* what the truth is?”

**Comment by PhotoNomad0** [comment]
@cckozie - I think I have a fix for the two cases listed - basically I'm adding support for the USFM markers that span (i.e. they have an end tag).  But I want to make sure that I am not breaking other cases with punctuation.  Do you know of some verses that we have had problems with the formatting in the past?  Such as punctuation, Greek with punctuation, and inline USFM markers?

**Comment by cckozie** [comment]
@PhotoNomad0 Nothing really comes to mind. These issues had to do with problem rendering punctation. Not sure if that relates to what you're working on or not. #6036, #6027, #5982, #5063, #4126
I'll make sure to do some tests with in-line USFM markers when it gets to QA.

**Comment by PhotoNomad0** [comment]
@cckozie Thanks, https://github.com/unfoldingWord/translationCore/issues/5063 was particularly helpful.  It doesn't look like this will fix anything new (such as extra spaces issues), but it doesn't seem to break the punctuation spacing.

**Comment by PhotoNomad0** [comment]
Verified in translationCore 2.1.0 (ddad4a)

**Comment by cckozie** [comment]
2.1.0 (ddad4a7) 
It looks like the two cases noted have been fixed, but I'm seeing other discrepancies when comparing the rendered text against previous builds. Specifically:
1. It looks like we're now preventing line breaks/wrapping when a word is followed by the \add marker
2. It looks like were now inserting an extra space when there is a \p marker within a verse (The purple box is the same size in both images) This problem can also be seen in John 18:38 with 2 spaces shown here: is?”  After
This is the rendering in 2.1.0 (ddad4a7) 
<img width="233" alt="t4t after" src="https://user-images.githubusercontent.com/8171759/68605535-329aa580-0472-11ea-91ec-74d38098cfd6.png">

This is how it was rendered in x2.1.0 (605b3a6) - from 10/29/19
<img width="232" alt="t4t before" src="https://user-images.githubusercontent.com/8171759/68604917-1a765680-0471-11ea-8c6d-76bc8615d3c3.png">

**Comment by PhotoNomad0** [comment]
@cckozie - have a test build for you to try.  Tried different spacing approach.

From the `release-vx2.1.0-test.2` branch:
[Linux build 2.1.0 (99ddffe)](https://tc-builds.door43.org/build/release-vx2.1.0-test.2/translationCore-linux-x64-2.1.0-99ddffe.deb) is ready for download.
[macOS build 2.1.0 (99ddffe)](https://tc-builds.door43.org/build/release-vx2.1.0-test.2/translationCore-macos-x64-2.1.0-99ddffe.dmg) is ready for download.
[Windows x64 build 2.1.0 (99ddffe)](https://tc-builds.door43.org/build/release-vx2.1.0-test.2/translationCore-win-x64-2.1.0-99ddffe.setup.exe) is ready for download.
[Windows x32 build 2.1.0 (99ddffe)](https://tc-builds.door43.org/build/release-vx2.1.0-test.2/translationCore-win-x32-2.1.0-99ddffe.setup.exe) is ready for download.

**Comment by cckozie** [comment]
@PhotoNomad0 This now looks good, at least for the 4 problems noted in this issue. I did not observe any other obvious rendering problems.

**Comment by PhotoNomad0** [comment]
Verified in translationCore 2.1.0 (ff63bfd)

**Comment by cckozie** [comment]
Looks good in 2.1.0 (eb708bf)
