### ISSUE TITLE
Items in the tN group menu should appear in alphabetical order

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6014]
1.2.0 (de171a2) 
The entire group menu should appear in alphabetical order. It appears that it is now sorted by top level category and then sorted alphabetically within that category.

**Comment by cckozie** [comment]
Fixed in 1.2.0 (5ee926c)

**Comment by cckozie** [comment]
Apparently this fix has caused problems with groups being skipped during automatic navigation.

**Comment by PhotoNomad0** [comment]
Copied QA fail notes from https://github.com/unfoldingWord-dev/translationCore/issues/6026:

> @PhotoNomad0 - 1.2.0 (1612995)  is a later build (by a few hours)
> In that build I am not seeing the problem described in this issue, but something else that may be related. Now when navigating to 1:4 under God the Father by completing or skipping the previous check, it skips right over the God the Father category (vs 1:4).
> Same is true for category Holy Spirit and Word of God.
> I have no way of knowing if the underlying problem is the same, so l'll gladly put this problem on another issue if you'd like or change the title of this one. Let me know.

Fixing issue that group menu index order is sorted by key rather than localized name.

**Comment by mannycolon** [comment]
Verified on 4d66c2c

**Comment by cckozie** [comment]
Looks good in 1.2.0 (d83e51a)
