### ISSUE TITLE
tN opens with ERROR and blank screen when no categories are selected

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6021]
1.2.0 (b485978)
May be fixed when ISSUE 1 on #5756 is fixed.
[en_ulb_tit_book (1).zip](https://github.com/unfoldingWord-dev/translationCore/files/3124247/en_ulb_tit_book.1.zip)

![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/50b9fbd6-2536-4ae1-9ce1-140699fcc14d)

**Comment by RoyalSix** [comment]
Not showing on latest develop cc9c5b5

**Comment by cckozie** [comment]
1.2.0 (cc9c5b5) 
Launch button is now disabled when no subcategories are selected.
