### ISSUE TITLE
Wrong checkmark icon being displayed on group menu tiles

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6022]
This appears to be a problem in tW and tN but not wA.
Bookmark icon in 1.2.0 (b485978) 
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/7b475e3c-40c9-4c70-b0da-706ebdb1a9db)
![image](https://user-images.githubusercontent.com/8171759/56854012-424b0600-68f5-11e9-85ac-1588dfa4536f.png)
![image](https://user-images.githubusercontent.com/8171759/56855197-c9ee4000-6908-11e9-9616-fd8e74ccf1dc.png)

Bookmark icon in 1.1.3
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/06411cb7-ecc4-4ff3-b874-5998bb2c6b7a)
![image](https://user-images.githubusercontent.com/8171759/56854021-4d9e3180-68f5-11e9-9764-3927306a3d89.png)
![image](https://user-images.githubusercontent.com/8171759/56855193-bba02400-6908-11e9-8891-1bee2ad0e791.png)

**Comment by PhotoNomad0** [comment]
Verified in https://tc-builds.door43.org/build/develop/translationCore-macos-x64-1.2.0-a3b50df.dmg

**Comment by cckozie** [comment]
Looks good in 1.2.0 (a3b50df)
