### ISSUE TITLE
Changing locale does not always affect all strings

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6025]
1.2.0 (b485978) 
I started with a clean install of 1.2.0
I imported a fully aligned Titus project
I loaded the project in tN
I opened the Menu filter
I changed the locale to Spanish
I noted that the screen was now all localized
I navigated back to the projects page
I changed the locale back to English
I reloaded the Titus project in tN
Now the menu bar is in English, but everything else is still in Spanish
The only way to reset it all back to English is by changing locales to something other than English and then back to English while in tN or closing and restarting tC.
The same problem exists in tW.
![image](https://user-images.githubusercontent.com/8171759/56921185-b965d300-6a8a-11e9-991b-a7f97b3e4f74.png)

**Comment by elsylambert** [comment]
Retested on 2.0.0 (ca6c273). Issue still exists.

**Comment by PhotoNomad0** [comment]
Note: have fix now for WA, but other tools still have some failure scenarios.

**Comment by PhotoNomad0** [comment]
@cckozie, @elsylambert - think I have this fixed now along with other misc. locale change quirks.  Here is a test build to try.

From the `release-vx2.1.0-test` branch:
[Linux build 2.1.0 (6b29bff)](https://tc-builds.door43.org/build/release-vx2.1.0-test/translationCore-linux-x64-2.1.0-6b29bff.deb) is ready for download.
[macOS build 2.1.0 (6b29bff)](https://tc-builds.door43.org/build/release-vx2.1.0-test/translationCore-macos-x64-2.1.0-6b29bff.dmg) is ready for download.
[Windows x64 build 2.1.0 (6b29bff)](https://tc-builds.door43.org/build/release-vx2.1.0-test/translationCore-win-x64-2.1.0-6b29bff.setup.exe) is ready for download.
[Windows x32 build 2.1.0 (6b29bff)](https://tc-builds.door43.org/build/release-vx2.1.0-test/translationCore-win-x32-2.1.0-6b29bff.setup.exe) is ready for download.

**Comment by PhotoNomad0** [comment]
@cckozie @elsylambert  - Have this item working in `translationCore 2.1.0 (d77535b)`

Notice that "No Selection Needed" checkbox still always stays in English, even though the help text changes language.  Looking into it.

**Comment by PhotoNomad0** [comment]
@cckozie @elsylambert - have a PR in process to fix localization for "No Selection Needed" checkbox

**Comment by PhotoNomad0** [comment]
@elsylambert @cckozie - verified in translationCore 2.1.0 (0a80f05)

**Comment by cckozie** [comment]
Not seeing any of the noted problems in 2.1.0 (0a80f05)

**Comment by elsylambert** [comment]
Verified in 2.1.0 (d0a11e7). Changing locale affects all string including the "No selection needed".
