### ISSUE TITLE
Scripture pane in tW loses resources when navigating to certain verses

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6026]
1.2.0 (a3b50df) 
[en_ult_tit_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/3129115/en_ult_tit_book.zip)

Scripture pane loses resources when navigating to Titus 1:4 under God the Father.
This was not a problem in 1.1.3.

[scripture_pane.mov.zip](https://github.com/unfoldingWord-dev/translationCore/files/3129097/scripture_pane.mov.zip)

Same problem on 3:5 under Holy Spirit
And all checks under Jesus
And 2:5 under Word of God

**Comment by PhotoNomad0** [comment]
**Note: steps in above:**
- under Godly, select second 2:12
- click cancel 
- click edit verse
- see error pop to select correct translation for current check
- select skip and resources disappear

**Comment by PhotoNomad0** [comment]
@cckozie - not seeing the problem in current build 1.2.0 (c797c44).  Did I miss something in the test steps above?

**Comment by cckozie** [comment]
@PhotoNomad0 - 1.2.0 (1612995)  is a later build (by a few hours)
In that build I am not seeing the problem described in this issue, but something else that may be related. Now when navigating to 1:4 under God the Father by completing or skipping the previous check, it skips right over the God the Father category (vs 1:4).
Same is true for category Holy Spirit and Word of God.
I have no way of knowing if the underlying problem is the same, so l'll gladly put this problem on another issue if you'd like or change the title of this one. Let me know.

**Comment by PhotoNomad0** [comment]
@cckozie - wonder if this related to doing alphabetic sort of group menu?  That the navigation is still going by by key order?

Taking a look.

**Comment by PhotoNomad0** [comment]
@cckozie - yes, looks like the stepping order is now `God`, `godly,`, `God the Father...`.  That is the key order.  But the case insensitive sorted title order is `God`, `God the Father...`, `godly,`

**Comment by PhotoNomad0** [comment]
@cckozie - maybe you should fail https://github.com/unfoldingWord-dev/translationCore/issues/6014, think I have a better fix than the approach I took.

**Comment by cckozie** [comment]
Per request, I failed #6014. Will retest this issue when that one is complete.

**Comment by cckozie** [comment]
Looks good in 1.2.0 (521546e).
Waiting for #6014 for final testing.

**Comment by cckozie** [comment]
All issues noted look good in 1.2.0 (2fea0fd)
