### ISSUE TITLE
Spacing problem in the ULT for Mat 9:6

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6027]
May want to combine with #6036 if they're similar

- [ ] Retain spaces. In the ULT it is `, ... "` (not `,..."`) 
  - [ ] Note: It appears that the `"` below also is missing a space before it

I don't know if this is a problem with the source content or tC, or a source problem caused by tC, but it seems to me that there should be a space between the quote mark and 'he'.
![image](https://user-images.githubusercontent.com/8171759/56979814-3f902100-6b40-11e9-9d08-ab98e68813fe.png)

![image](https://user-images.githubusercontent.com/13352518/58502556-554b3300-814c-11e9-8057-ddcdd054e045.png)

**Comment by birchamp** [comment]
@cckozie it looks like this is fixed in 2.1 - ![Screenshot from 2020-01-06 17-52-31.png](https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/5050dd49-20d4-4975-8efb-756dda13a3e3)

**Comment by cckozie** [comment]
Looks good in 2.1.0 (9782150)
