### ISSUE TITLE
tC crashes when opening a 1.2 project in a prior release

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6029]
- [x] Add the tC version number to the manifest (1.1.4 (e7e858a) - shows as edit version)
- [x] Add version of tC (and prior) with which this project is incompatible. This is minimum version of compatibility (or maximum incompatibility). Warn if that version or previous.
- [x] If the project is trying to be opened in a version that is incompatible, do not open the project, throw an error that says, "This project was created in a newer version of translationCore. Please update to the latest version and try again."
  - [x] Add button to dialog with the "Update to latest version"

= = = =

1.1.3 and prior are unable to read the tW categories correctly from 1.2 projects.
We either need to warn the 1.1.3 and prior users that they need to upgrade before importing the project from a future release, or build backward compatibility into the projects so that they can be read by versions preceding 1.2.0. (Problaby the warning is more realistic)

We do not expect users to go back releases, but it is likely that others on earlier releases would import "future" projects from Door43.

**Comment by PhotoNomad0** [comment]
@benjore @cckozie - What should be the behavior when the users downloads an incompatible version?  We could:
1. abort the download deleting the project from import folder, and show the error message
2. finish the download and import the project.  Then show error and not automatically select the project.

item 1 is easy to do
item 2 may be more complicated - rework to import stepper and hope to not break things.

Would suggest we go for item 1 in v1.1.4 since it is priority, and if deemed necessary we could add item 2 in v1.2.0 or future release.

**Comment by cckozie** [comment]
@PhotoNomad0 @benjore - I'm basically OK with either solution for 1.1.4, but note that #1 would fail to protect against users that copy the project folder from another user or downgrade (unlikely).
We currently protect against all situations for projects from 0.7, I think by checking something in the manifest. How difficult would it be to tap into those routines to add this protection?

**Comment by PhotoNomad0** [comment]
@cckozie @benjore - I was just discussing the import problem, but of course we will check on project load that the project is compatible.  That is easy to add into the current compatibility check.

My thoughts were that we check for valid versions on both download from D43 and when we select a project.

**Comment by cckozie** [comment]
Works for me.

**Comment by PhotoNomad0** [comment]
Verified in translationCore 1.1.4 (b6d9938)

**Comment by cckozie** [comment]
Prevents both project download and project selection in 1.1.4 (e7e858a)
