### ISSUE TITLE
Two checks highlighted in the menu at the same time

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#6035]
![image.png](https://images.zenhubusercontent.com/55e5f3984f7a08fbb7f4a658/f7504863-c179-40a8-9c13-fe555012ad1b)

- [ ] Only one check at a time should show up highlighted. (In this case, there was one verse with two identical checks. Both showed up highlighted in the menu.)

Some other examples:
Mat 24:30 and 26:24 under Son of Man

**Comment by cckozie** [comment]
Dup of part of #5970
