### ISSUE TITLE
The subcategories on the tN card should be displayed in the language of the selected GL

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6056]
- [ ] For tN & tW card, the language of the checkboxes needs to match the language selected in the GL dropdown. 
  - [ ] (First preference: use the data that's in tN/tA/tW. If it doesn't exist (like for the head catagories), then fallback to CrowdIn data.)

As a checker, I would like the categories and subcategories on the tN and tW tool cards to display in the language of the selected GL so that in the case of tN, I will always see the same language on the tools card as in the group menu.

**Comment by mannycolon** [comment]
@benjore Per slack:
> OK. I see. That is fine. That will work. The biggest thing is I want the subcategories on the tool card to match the subcategories on the tool.
So we can modify that issue so that the language on the tool card is changed via locale, not GL selection. But then the subcategories are based on data from tA, and not from the locale. Does that work?

**Comment by mannycolon** [comment]
So we can only display the subcategories in the language of the selected GL not the categories

**Comment by cckozie** [comment]
2.0.0 (00bca0b) 
Categories are still in English. Subcategories are displayed in the GL. Looks good.

**Comment by elsylambert** [comment]
Verified in 2.0.0 (855642f). Categories are in English and Subcategories in GL.

**Comment by elsylambert** [comment]
Need to change  below Sub-category to display in alphabetical order:
![image](https://user-images.githubusercontent.com/51806180/61982049-7e136b80-afc9-11e9-84d6-4e919d5deee6.png)

**Comment by mannycolon** [comment]
@elsylambert Could you please give reasoning why the order should be changed.

**Comment by elsylambert** [comment]
@mannycolon To have them in Alphabetical Order in Hindi.

**Comment by mannycolon** [comment]
@cckozie @elsylambert @benjore They are actually being alphabetical ordered, but the last item `‘‘तुम’’ के प्रारूप` has `‘‘` at the beginning causing it to be sorted to the end.

**Comment by elsylambert** [comment]
Looks good in  2.0.0 (c940391) with the exception in sort order for one sub-category with ‘‘ at the beginning.
