### ISSUE TITLE
Fix reopening app

### ISSUE THREAD

**Issue by ihoegen** [unfoldingWord/translationCore#606]
An error occurs when the app is restarted, and a module opens. It's: `cannot find property view of undefined`

**Comment by klappy** [comment]
Store current running version in LocalStorage and compare on load to the last running version, if it doesn't match, clear local storage and restart.

**Comment by ihoegen** [comment]
I don't think it's a version issue, there may be some left over code from before we moved to a Container-View Structure

**Comment by klappy** [comment]
We're using the version to help us "clean up" just in case there is a change in the local storage between releases.
