### ISSUE TITLE
The % complete indicated on the tN card is inaccurate

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6063]
1.2.0 (1612995)
[en_test_1ti_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/3157902/en_test_1ti_book.zip)
There are 13 checks under "Culture" in this project. 1 of them has been completed. The tN card should show 8% complete, but instead shows 0%.
There are 10 checks in the "Assumed Knowledge and Implicit Information" subcategory and 1 of them has been completed. When it is the only subcategory selected, the tN card should show 10% complete, but instead it show 0%.
![image](https://user-images.githubusercontent.com/8171759/57384970-23f7cc80-7177-11e9-8674-2e42c04bf5a0.png)

![image](https://user-images.githubusercontent.com/8171759/57385064-573a5b80-7177-11e9-90ba-ef5fff1bd216.png)

**Comment by PhotoNomad0** [comment]
Note: the tN selections are false when project is selected and toolcards displayed, but when tN is launched, selections get loaded.  

Looks like same behavior on tW.

**Comment by PhotoNomad0** [comment]
Verified in 1.2.0 (dbca10d)

**Comment by cckozie** [comment]
Works correctly in 1.2.0 (d83e51a)
