### ISSUE TITLE
After installing 1.1.4 (81a1d3d) both English and Hindi show on the resource update selection screen

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6067]
If 1.1.4 (81a1d3d)  has the latest resources bundled with it, they should not show on the screen for selecting resource updates.
They both appear on the page regardless of whether I do a tC upgrade or clean install.

![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/abe6030a-563d-4cd9-9953-5be0c606b066)

**Comment by cckozie** [comment]
Looks like the English is legit because of the T4T.
In comparing Hindi resource folders pre and post download, it looks like the Hindi tA was not included in the build.

**Comment by PhotoNomad0** [comment]
Fixing missing Hindi TA with https://github.com/unfoldingWord-dev/translationCore/pull/6061

**Comment by PhotoNomad0** [comment]
Verified in 1.1.4 (926aece)

**Comment by cckozie** [comment]
In 1.1.4 (9329586) Hindi does not show on the resources update select screen. English does show, and T4T is the only thing downloaded/updated when the English is selected and downloaded.
