### ISSUE TITLE
Project Migration error with tW categories

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#6072]
### User Story

Project tW check selections migration error observed.

#### Testing Process:
In tCore v1.1.3 loaded https://git.door43.org/lrsallee/en_ult_rut_book.  Then ran tCore v1.1.4 and selected the same project - which updated the timestamp in `.categories` for tW (this worked well).  Then ran tCore 1.2.0 and and selected the same project, and on tW toolcard see no categories selected (should default to all categories selected).  Noticed that hasNewGroupsData() did not flag tW resources as updated since the time stamp is newer than the resource time in these resources.  This left .categories as:

`{"current":["kt","other","names"],"loaded":["kt","names","other","almighty","anoint","bless","brother","children","clean","command","covenantfaith","falsegod","favor","fear","forsake","god","good","heart","hope","inherit","israel","judge","life","lord","love","moab","name","peopleofgod","redeem","rest","restore","son","testimony","true","witness","work","yahweh","bethlehem","boaz","david","ephrathah","jesse","judah","judea","leah","rachel","ruth","tamar","afflict","barley","bow","bread","bury","comfort","conceive","confirm","death","elder","family","famine","father","foreigner","gate","generation","glean","grain","hand","harvest","house","kind","offspring","peoplegroup","prosper","reap","rebuke","refuge","reproach","reward","sandal","servant","thresh","wheat","winnow"],"timestamp":"2019-05-10T12:41:22.132Z"}`

This does not seem to be a serious bug.  Even though no categories are selected on tW toolcard (default should be all selected), the user is still able to select categories.  Also the erroneous categories will be removed the second time the project is selected.

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by cckozie** [comment]
Looks good in 1.2.0 (2fea0fd)
