### ISSUE TITLE
Indeterminate selections shown on tW toolcard for Ruth.

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#6073]
### User Story

See a problem in 1.2.0:

Loaded https://git.door43.org/lrsallee/en_ult_rut_book, and turned off all selections.  When I click on "key terms", then "key terms" are selected and "names" also comes up selected as indeterminate.  Looks like a data error that "moab" is both in `kt` and `names` category.

![Screen Shot 2019-05-17 at 8 17 46 AM](https://user-images.githubusercontent.com/14238574/57927539-4dea7680-787c-11e9-9cda-36e2f5dc7739.png)

### Features / Specifications

- [ ] I don't think we should show indeterminate state on tW card even if there are content problems. (from Koz)
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by PhotoNomad0** [comment]
Note: Don't see in indeterminate selections in latest 1.1.4 with updated uhb 2.1.1, but see in 1.2.0.  

In 1.1.4 see with names selected **_(note that Ruth 1:4 is missing)_**:

![Screen Shot 2019-05-17 at 8 13 48 AM](https://user-images.githubusercontent.com/14238574/57927374-c69d0300-787b-11e9-8d25-7afb420b34d2.png)

In 1.2.0 see (also with  uhb 2.1.1):
- select kt and see Ruth 1:4 in tW
![Screen Shot 2019-05-17 at 8 21 04 AM](https://user-images.githubusercontent.com/14238574/57927677-bd606600-787c-11e9-82db-c50f367881d6.png)

- select names and also see Ruth 1:4 in tW (looks like most entries are missing)
![Screen Shot 2019-05-17 at 8 19 00 AM](https://user-images.githubusercontent.com/14238574/57927595-7d997e80-787c-11e9-8bfd-fabf3c8ef8d8.png)

**Comment by PhotoNomad0** [comment]
Note: it looks like moab is both an entry under kt and names, but the app doesn't like that.  Looking at the uhb 2.1.1 it looks like Ruth 1:4 has moab under kt when it should be under names.

**Comment by PhotoNomad0** [comment]
This is due to a content error waiting for fix.

**Comment by PhotoNomad0** [comment]
@benjore -  it seems like we really need to be able to check the content for errors the the check categories and let the user and the content team know.

**Comment by cckozie** [comment]
Not seeing the problem in 1.2.0 (b757c2a) with latest resources.
Is that all that we're looking for now, or do we want enhancements to tC?

**Comment by cckozie** [comment]
If tC work is to be done on this it will be on separate issue.

**Comment by elsylambert** [comment]
Working fine in 1.2.0 (f215a2f)
