### ISSUE TITLE
tW is broken in tC 1.1.4 after updates of ULT and UGNT

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6076]
1.1.4 (9329586) 
(I am assuming it's the new resources that are causing the problem)
Import any usfm file (with or without alignments)
Notice that none of the categories are selected on the tW card
Load the project in twW
Note that all you see is the big ERROR
(I have been able to load projects from DCS in tW)
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/f468c5f3-eedc-44e8-906e-65d7d1b73fdf)

**Comment by PhotoNomad0** [comment]
restored the missing grc tW 0.6
Verified in  1.1.4 (bfefbd0)

**Comment by cckozie** [comment]
Looks good in 1.1.4 (bfefbd0)
