### ISSUE TITLE
tCore Resources do not always update with new version

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#6078]
### User Story

tCore Resources will not update with under following scenario:
- user is running older version of app (after new version is released or during QA soak) and does a local update of resources.  Afterwards when they update to new app the resources do not get updated.

Observed this problem in going back and forth between tCore versions in testing. The reason this can be a problem is that we have made two significant changes to the resources that can cause trouble:
1. moved `grc` language to `el-x-koine` (in 1.2.0) - this may be repaired once they update resources, but may get error screens in tools until updating resources.
2. changed format of checks in (in 1.1.4) - this may only be a nuisance that in some cases wrong greek words highlighted in tW.  To recover, the user would have to delete the resource directory and restart the app.

Suggest adding app version to `source-content-updater-manifest.json` and using that to determine if resources need to be refreshed when starting up the app.  This seems to be more reliable than using the date the resources were last updated locally, and would go a ways in future proofing if user also rolls back to older version of app.

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by PhotoNomad0** [comment]
@cckozie - Verified in 1.1.4 (af13224)

**Comment by cckozie** [comment]
Works in 1.1.4 (d200840)
