### ISSUE TITLE
tC reports successful upload to DCS even though it failed because of differing git histories

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6084]
1.1.4
Upload a project to DCS
Delete the project from the project folder
Import a usfm project for the same book/language/translation id
Upload the new project to DCS.
Note that tC indicates a successful upload even though in the console it shows that it failed.

**Comment by PhotoNomad0** [comment]
Verified in 1.1.4 (804ddb6)

**Comment by cckozie** [comment]
Looks good in 1.1.4 (804ddb6)
