### ISSUE TITLE
Problems with edit icon not displaying on edited verses 

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6088]
1.1.4 (804ddb6)

[en_ult_tit_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/3184661/en_ult_tit_book.zip)

1. Load the attached project in wA
2. Edit verse 1:4 so that it looks as follows:
![image](https://user-images.githubusercontent.com/8171759/57815459-2345d400-773d-11e9-95b0-9083e197b472.png)
3. Load the project in tW
4. Navigate to the Christ, Messiah group
5. Click on verse 1:4
ISSUE A: Note that there is no edit icon on the menu tile or in the icon bar, and when the Verse edit filter is applied, no verses show in the list

**Comment by PhotoNomad0** [comment]
@cckozie - it looks like we had an issue to fix this in 1.2.0 and now am copying those fixes to 1.1.4.

**Comment by PhotoNomad0** [comment]
@cckozie - we already fixed for 1.2.0 in https://github.com/unfoldingWord-dev/translationCore/issues/5832

**Comment by PhotoNomad0** [comment]
Verified in 1.1.4 (f727982)

**Comment by cckozie** [comment]
Works in 1.1.4 (d200840)
