### ISSUE TITLE
Update the Hebrew font

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#6089]
### User Story

@ben_jore Ideally we could have the Ezra font used for Hebrew, http://software.sil.org/ezra/

![image](https://user-images.githubusercontent.com/13352518/58111514-36322b80-7bb7-11e9-8a3d-5dfba6a35e28.png)

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by benjore** [comment]
Does this show up incorrectly in tC?

**Comment by jag3773** [comment]
More info from the slack thread...

Larry Sallee [May 14th at 9:04 AM]
Anyone know why Ezra 6:10 UHB has a display problem? Same square characters on Door43. File text is `\w לֶהֱוֺ֧ן|lemma="הָוָא" strong="H1934"`
![image](https://user-images.githubusercontent.com/107731/59436262-4788e500-8dbd-11e9-862e-a168d4638825.png)

klappy  [1 month ago]
Does it have a display problem in the Consume app?

Larry Sallee  [1 month ago]
@klappy Nope, consume app is OK.

klappy  [1 month ago]
So the data should be fine, maybe a font choice in tC.

klappy  [1 month ago]
I’m using the following font-family in the consume app: `-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Oxygen,Ubuntu,Cantarell,Fira Sans,Droid Sans,Helvetica Neue,sans-serif`

Larry Sallee  [1 month ago]
It looks like a problem with the vowel pointing. Perhaps @jag3773 can spot the problem,

Larry Sallee  [1 month ago]
@jag3773 pointing is weird:
image.png 


Larry Sallee  [1 month ago]
Same in 7:25

Larry Sallee  [1 month ago]
@klappy Just notice that is displays OK in the text in the consume app, but not in the popup lexical window.

klappy  [1 month ago]
I’m unable to recreate the issue in the lexical popup. Is there a specific word and verse? Also what OS/Browser are you using?

Larry Sallee  [30 days ago]
@klappy Latest Chrome on my iMac:
image.png 


Larry Sallee  [30 days ago]
Hmm. Works correctly on Safari.

Larry Sallee  [30 days ago]
Interesting—the D43 display is OK in Safari (https://door43.org/u/unfoldingWord/UHB/dc8522a6e8/15-EZR.html#015-ch-006). Looks like a Chrome and tC issue.
door43.org
Ancient Hebrew: unfoldingWord® Hebrew Bible - 15-EZR.html
unrestricted biblical content in every language

Jesse Griffin  [30 days ago]
@ben_jore Ideally we could have the Ezra font used for Hebrew, http://software.sil.org/ezra/
software.sil.org
Ezra SIL - SIL Language Technology
Supporting literacy, development and translation through language and writing system software.

Jesse Griffin  [23 days ago]
@ben_jore This was actually the issue I was trying to remember yesterday in our call...

Ben Jore  [21 days ago]
I'm finally getting around to this. It seems like everything is rendering fine for me! @Larry Sallee what version of tC were you using? Have you updated the Hebrew text recently?
image.png 


Larry Sallee  [21 days ago]
@ben_jore Away from home today. Will check tomorrow. 1.1.3 and latest Hebrew. Same problem on Door 43 in Chrome, but not Safari. @jag3773 and @klappy were able to replicate. Traced it down to font family.

Larry Sallee  [20 days ago]
@ben_jore Problem still exists.

**Comment by PhotoNomad0** [comment]
Verified in translationCore 1.2.0 (8a7049c)

**Comment by elsylambert** [comment]
Verified in 1.1.4- Cannot find the issue with the Hebrew font. Font size is smaller when compared to 1.2
Verified in 1.2- Hebrew font is displayed fine.

**Comment by cckozie** [comment]
1.2.0 (a3ee18b) 
The new font appears to work correctly. Just noting the difference in size (and possibly boldness)

<img width="246" alt="new" src="https://user-images.githubusercontent.com/8171759/60835367-86c21000-a188-11e9-88da-f7d1f6288360.png"> <img width="246" alt="old" src="https://user-images.githubusercontent.com/8171759/60835368-86c21000-a188-11e9-8420-b1496f56e547.png">
