### ISSUE TITLE
When reopening project in tW, the last used menu selection is not activated and the checkmark is not displayed on checked verse

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6093]
1.1.4 (f727982).
This worked correctly in 1.1.3.
This is the project in the bad state: [en_ulb_tit_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/3198911/en_ulb_tit_book.zip)
The previously made selection does appear to be persisted since it appears in the csv file and the checkmark is displayed in the icon bar.

![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/4d9256f9-428c-429e-b194-3cef2d179adb)

To reproduce:
1. Copy these two projects to your projects folder and unzip them
[en_ulb_tit_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/3199810/en_ulb_tit_book.zip)
[en_ulb_act_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/3199812/en_ulb_act_book.zip)
2. Load the Titus project in tW
3. Navigate to the apostle group
4. Drag to highlight 'an apostle'
5. Click Save
6. Navigate to verse 1:1 in the Christ groupr
7. Double click on 'Christ' to highlight
8. Click Save
9. Click on the project name in the menu bar to return to the Projects page
10. Load the Acts project in tW
11. Click on the project name in the menu bar to return to the Projects page
12. Reload the Titus project in tW.
ISSUE A: Note that the first menu item is active instead of 1:1 in the Christ group
ISSUE B: Notice that the completion circle in the apostle group is not filled in and when it is opened, the selection is still highlighted, but the checkmark and selection is missing on the menu tile.

**Comment by PhotoNomad0** [comment]
@cckozie - on issue A, I can't find where we persist the latest context for a project and tool.  My presumption is that it will always reset when a new project is selected.

on issue B, think I have found a data initialization bug that addresses this.  But I can't explain how it is not a problem in 1.1.3 since the change was made in January.

**Comment by cckozie** [comment]
@PhotoNomad0 - Re: Issue A - For as long as I can remember, tC has remembered where I was in the project in the tool and that is where it loaded to the next time I loaded that project in the tool. This was broken a few months ago, but Joel got it working again. I just reverified that it was working in 1.1.3.

**Comment by cckozie** [comment]
Both issues fixed in 1.1.4 (d200840)
