### ISSUE TITLE
Problems Opening highly edited project in tW in 1.1.4

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#6095]
### User Story

In translationCore 1.1.4 (f727982):
Downloaded this project from D43: https://git.door43.org/lrsallee/en_ult_mat_book
Then launched tW - loading spinner stays on screen and can no longer interact with tCore.
Had to close tCore. On relaunch of tCore I can select the project, but second time I launch tW the app hangs without the spinner displayed.  After a minute, the app seems to start working.

Not seeing any error messages in console of tCore, just long hangs.

On third attempt, tW started launching normally.

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by PhotoNomad0** [comment]
@benjore @cckozie - it looks like the cause of this is 6100 external verse edits queued up to be saved in tW group data (Larry probably edited every verse in WA more than once). Looking to see if way to improve performance here on first open.

**Comment by cckozie** [comment]
I think it would be sufficient for now to just provide an indication of processing between the stepper and the project named alert.
Also between the last overwrite alert and the Loading alert.

**Comment by PhotoNomad0** [comment]
@cckozie - sorry but moving the verse edit updating into the stepper would be a major refactor.

Currently it takes about 2-1/2 minutes on a fast machine to update verse edits the first time you open the above project in tW.

**Comment by PhotoNomad0** [comment]
I have the updating of verse edits down to a couple of seconds now on the first open of the mat ult in tW by creative batching of operations: reduced 6000 unique verse edits down to 1054 edited verses which changed 4032 checks in mat that I grouped into 487 changed groups.  By adding an operation to the group data reducer to set an array of verse edits for a groupId and batching those made it run fast.  Now have 487 file saves instead of 4032.

**Comment by benjore** [comment]
Great work Bruce! Can you make sure to add a spinner (the small one with a message telling the user what is going on) before you move it along? Thanks!

**Comment by cckozie** [comment]
For reference in 1.1.4 (d200840) on my older Mac:
Stepper to Loading alert: 1:40 (no indication of processing)
Loading alert to Tools page: 0:21 (spinner on Loading alert)
Time to open wA: 0:10 (large logo spinning)
Time to open tW: 4:17 (large logo spinning)

When exported to csv, there are 1876 edits displayed. 1076 are tagged as external edits, the remainder as done in wA.

**Comment by cckozie** [comment]
1.1.4 (29dac6c)  on my older Mac:
Stepper to Loading alert: 1:40 (no indication of processing)
Loading alert to Tools page: 0:21 (spinner on Loading alert)
Time to open wA: 0:10 (large logo spinning)
Time to open tW: 0:14 (large logo spinning followed by Loading edits alert with spinner)

 @benjore - The time to open tW is now greatly improved, and the user is aware that processing is taking place. However, I am still concerned that for more than a minute and a half during the import process (from project details page to the tools page) the user has no idea that anything is happening. (I'm not sure it that is what you were asking for in your previous comment about the spinner, but Bruce interpreted it as needed during the opening of tW)
Also, in the process of testing this I've found that tC no longer cleans up after a failed import, so if the user terminates tC because they thought it was hung, they will not be able to run the import again without manually deleting the project from the imports folder, or the projects folder if they reattempted the import. (See #6105)
I think we either need add a processing alert after the stepper now, or highlight this problem in the release notes.

**Comment by mannycolon** [comment]
@cckozie When you say we need to add a `processing alert after the stepper ` are you referring about the project import validation stepper or the regular project selection stepper?

**Comment by cckozie** [comment]
@mannycolon - I'm referring to it during the import process. Once the import has finished, then the project selection process is much faster and the Loading project data alert is displayed fairly quickly.
That alert is eventually displayed during the import as well, but not until more than a minute and a half after I click the Continue button on the Project Details page.

**Comment by mannycolon** [comment]
@cckozie Do we have an issue to address speeding up this process? I was checking through the code that's doing the processing while you wait the 1 min and 40 secs and it looks like it could be speeded up a little bit.

**Comment by cckozie** [comment]
@mannycolon - I think #6010 would cover that.

**Comment by PhotoNomad0** [comment]
@cckozie - verified change in translationCore 1.1.4 (a89d16f)

**Comment by cckozie** [comment]
1.1.4 (a89d16f) on my older Mac:
Stepper to Loading alert: 1:40 (spinner on new Preparing your project data alert)
Loading alert to Tools page: 0:21 (spinner on Loading your project data alert)
Time to open wA: 0:10 (large logo spinning)
Time to open tW: 0:14 (large logo spinning followed by Loading edits alert with spinner)

**Comment by cckozie** [comment]
1.1.4 (a89d16f) 
Per above comment, there is now no dead time now where there is not indication of processing. However, the new alert needs to be presented after the last page of the stepper. The current implementation causes projects with missing verses or merge conflicts to hang during the stepper stage of the import.
This project is missing verse 1:1
[php_usfm_NoVerse1.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/3228574/php_usfm_NoVerse1.usfm.zip)

This project has merge conflicts:
[en-x-demo1_php_text_ulb_mc.tstudio.zip](https://github.com/unfoldingWord-dev/translationCore/files/3228576/en-x-demo1_php_text_ulb_mc.tstudio.zip)

**Comment by cckozie** [comment]
1.1.4 (341bbf5) 
https://git.door43.org/tc01/en_ult_mat_book
The app no longer hangs when importing projects with missing verses or merge conflicts. However, when importing an online project with lots of edits that also has missing verses, the new alert appears between the Project Details page and the Missing Verses page. When Continue is clicked on the Missing verses page, there is no indication of processing for the 1 minute 40 seconds, as before, until the Loading your project data alert is displayed.

**Comment by mannycolon** [comment]
Verified on c8d29c4

**Comment by cckozie** [comment]
1.1.4 (c8d29c4)
The problem with importing Door43 project with missing verses has been fixed.
There appears to be a similar problem relating to renaming Door43 projects that have a lot of edits. I wrote this one up on #6117.
