### ISSUE TITLE
When searching for just a language code, only show results that match 

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#6099]
### User Story

When a user enters `ru` in the language field and clicks `Search`, many results are returned that are not from the `ru` language (but do have `ru` somewhere in the project name). 

![image.png](https://images.zenhubusercontent.com/55e5f3984f7a08fbb7f4a658/004a793d-5bf0-4740-8924-9fbe33d1b197)

### Features / Specifications

- [ ] When searching for the book of Galatians `gal` anything that has `gal` in its name shows up, such as `legal`. Expected behavior would be showing only projects for the book of Galatians. 
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by elsylambert** [comment]
Retested on 2.0.0 (ca6c273). Issue still exists.

**Comment by cckozie** [comment]
This is a dup or #4487
