### ISSUE TITLE
Loading the entire check list slows down the main view

### ISSUE THREAD

**Issue by EllDoubleYew** [unfoldingWord/translationCore#61]
As a checker I want a menu that feels responsive so that when I make changes I know what I change is reflected on the actual data that I am manipulating.

**When any state in the main view changes the re-render is so massive that it really slows down the view as a whole. To combat this we can minimize what is actually re-rendered when any of these states are changed so that the changes are less expensive**

Long term it may be more beneficial to look into where we are using unnecessary states as well. There are certain on hover states in some components floating around in the main view that serve little to no purpose (other than styling, but there are plenty of ways to do that without state).

**Comment by klappy** [comment]
This also affects the UX as scrolling forever to get to the bottom of the check list isn't fun. If we were to only render the "groups" such as the words and not the references in tW, And drill down into the references for checking, it would improve the UX as well.

**Comment by klappy** [comment]
Should be addressed with new UX/UI.
