### ISSUE TITLE
If tC ends during a file import, the user is prevented from importing the project when tC is restarted

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6105]
- [ ] Clear the Import folder before starting a new import

1.1.4 (29dac6c)
tC does not cleans up the imports folder when it is started or an import is started
To replicate:
Start an online import
End tC before the stepper is engaged
Note that the project now exists in the imports folder
Restart tC
Attempt to import the project again
Note:
1. The alert indicating the project already exists is now displayed
2. After canceling the import the project appears on the Projects page
3. When the project is selected, the Book not supported alert is displayed.

**Comment by mannycolon** [comment]
Verified on daee8ab

**Comment by cckozie** [comment]
Needs regression
