### ISSUE TITLE
tC hangs during import of tstudio project

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6106]
1.1.4 (29dac6c) 
I have seen this happen occasionally but it is not easy to replicate. When it happens, It seems to be most likely when importing this project:
[rmr-x-bsa_tit_text_ulb.tstudio.zip](https://github.com/unfoldingWord-dev/translationCore/files/3218064/rmr-x-bsa_tit_text_ulb.tstudio.zip)

Interestingly, when I decide that it is probably hung and then click anywhere on the screen, the import completes as expected. (tC was the foreground app all of the time)

Here is the log. The hang was between 12:31 and 12:44 at which time I clicked on the screen.
[Fri May 24 2019.log.sav.zip](https://github.com/unfoldingWord-dev/translationCore/files/3218066/Fri.May.24.2019.log.sav.zip)

Here is the log of it completing normally.
[Fri May 24 2019-2.log.zip](https://github.com/unfoldingWord-dev/translationCore/files/3218067/Fri.May.24.2019-2.log.zip)

**Comment by elsylambert** [comment]
Not seeing this issue in 2.2.0 (2375ae5).
