### ISSUE TITLE
Percentage complete on wA tool card seems to be incorrect in some situations

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6116]
1.1.4 (4b90ae7)
I thought we were calculating the % complete on the wA tool card based only on the status of the Alignment complete switch. It now appears that it is a combination of the switch and the actual alignments. For example in new unaligned Titus project:
1. Fully align verse 2:1
2. wA tool card shows 2%
3. Switch OFF the Alignment complete switch
4. wA tool card still shows 2%
5. Navigate to verse 2:2
6. Switch ON the Alignment complete switch
7. wA tool card now shows 4%
So it looks like it is counting 1:1 as complete now because all of the target and Greek words are aligned, and it is counting 2:2 as complete because the Alignment complete switch is on.
Is that the expected behavior:

**Comment by cckozie** [comment]
Same results in 2.0.0 (ca6c273)

**Comment by elsylambert** [comment]
Not seeing this issue in 2.2.0 (2375ae5). wA shows <1% when 2:1 is aligned and goes to 0% when the Alignment complete button is togged off.
