### ISSUE TITLE
Need user experience improvements for install and upgrade

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6119]
1.1.4 (c8d29c4) 
On my older Mac it takes more than 10 minutes to install or upgrade tC. On my new Mac it takes about 3 minutes. During this time the only information displayed to the user is the large spinning logo and the word "Loading..."

I believe the average user will believe the system is hung with that much dead time.
For first time users, this is their initial experience, and it is not good.

I suggest we take a common approach (and the one used by tS) during that time by updating the alert dynamically to tell the user what is actually happening; e.g. "Installing English ULT", "Installing Greek text", "Installing translationNotes", etc.

Adding a progress bar would make it even better.

**Comment by cckozie** [comment]
Still a problem in 2.0.0 (ca6c273)

**Comment by elsylambert** [comment]
Not seeing the in 2.2.0 (2375ae5).
