### ISSUE TITLE
App hangs during import with Preparing your project data alert displayed with Missing Verses page in background

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6132]
1.2.0 (2fea0fd)
https://git.door43.org/tc01/en_ult_mat_book
Tried to import this project. Ended tC after waiting 15 minutes.
The problem seems to be related to the project having a missing verse. This may have been fixed in 1.1.4 and not brought forward to 1.2.
[Mon Jun 10 2019.log.zip](https://github.com/unfoldingWord-dev/translationCore/files/3272811/Mon.Jun.10.2019.log.zip)

**Comment by mannycolon** [comment]
Verified on 1b88859
