### ISSUE TITLE
tN requires users to be able to select more than 4 individual selections

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6133]
- [ ] For the tN tool, change the max number of selections to 10
  - [ ] Update the warning for tN to say "10" 

1.2.0 (2fea0fd) 
Some tN's require more than 4 selections to be made. Here's one example:
![image](https://user-images.githubusercontent.com/8171759/59214702-3e113a00-8b7d-11e9-8bf3-ad3e1da51981.png)

**Comment by benjore** [comment]
Verify with Klappy that this won't cause any problems. 

How many selections? 10? Unlimited?

**Comment by benjore** [comment]
Klappy - bump it up to 10. Look for selection bugs (that showed up a long time ago). WordMAP will need to filter how many selections before it will disregard the data.

**Comment by PhotoNomad0** [comment]
@neutrinog - Is there anything that needs to be done with WordMap?  From the logs it looks like it is already ignoring ngrams of more than 5.

**Comment by da1nerd** [comment]
Nope. wordMAP doesn't affect any functionality here. What you see in the logs is a hard limit (implemented in wA) on the size of generated predictions. This was just an uneducated guess for performance of predictions.

**Comment by cckozie** [comment]
1.2.0 (736956e)
It appears to work correctly except that it allows 11 selections (not 10), although when 12th is made, the alert indicates there can only be 10.
Upon further inspection, it appears that tC automatically combines a highlighted last word in a line with a highlighted first word in the next line, which then causes the selections count to be one less than it actually is. Works the same way in tW where it catches more than 4 selections. Seems a minor issue, so I'm passing this.

**Comment by richmahn** [comment]
Ah, that is why I also could make it go to 12 selections sometimes...I was selecting words on the end!

**Comment by elsylambert** [comment]
Verified in 2.0.0 (459884d). Selections are restricted to 10 and the message is displayed if the 11th selection is made. Working fine.
