### ISSUE TITLE
Some tN's are not displayed correctly with older projects

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6134]
1.2.0 (d83e51a) 
This was an existing project upgraded to 1.2.0. (No change after downloading latest English resources)
![image](https://user-images.githubusercontent.com/8171759/59218298-87658780-8b85-11e9-9d1f-37821037c820.png)

This is a newly imported project:
![image](https://user-images.githubusercontent.com/8171759/59218451-ea571e80-8b85-11e9-8ae6-da2faeab8ab6.png)

**Comment by PhotoNomad0** [comment]
@cckozie -Would you attach the project?

**Comment by mannycolon** [comment]
@PhotoNomad0 this bug is related to caching

**Comment by cckozie** [comment]
@PhotoNomad0 I am unable to reproduce in 1.2.0 (c15cbbf)

**Comment by mannycolon** [comment]
@cckozie @benjore @PhotoNomad0  What should we do about this issue? Should it be moved to the `QA Watch List`?

**Comment by cckozie** [comment]
@mannycolon No, I'd prefer that we leave it InQA since I am continuing to test it as I have time when the QA queue gets low. I have not found any problems yet, but have only looked at very small fraction of the verses that have tNs.
I am OK with it being demoed in the next sprint review if that is the concern. I'm reasonably confident that the bugs are gone, but not ready to sign off on it yet.

**Comment by mannycolon** [comment]
@cckozie Ok, but it is currently in `Sprint story backlog` should it be move to `In QA` then?

**Comment by cckozie** [comment]
@mannycolon - My bad. I just glanced at the title and thought we were talking about your issue with tNs not displaying properly. I'm moving it to QA Watch.

**Comment by cckozie** [comment]
This has been fixed.
