### ISSUE TITLE
Project opens with no menu item selected

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6137]
1.2.0 (d83e51a)
[en_test_1ti_book 2.zip](https://github.com/unfoldingWord-dev/translationCore/files/3277947/en_test_1ti_book.2.zip)

Open this project in tN
Note that a check for Assumed Knowledge and Implicit Information verse 4:3 is displayed, but the corresponding menu tile is not selected.

![image](https://user-images.githubusercontent.com/8171759/59296870-96633d00-8c4c-11e9-9e64-a8638ef20adf.png)

**Comment by benjore** [comment]
Could be fixed by #6134

**Comment by cckozie** [comment]
No longer an issue in 2.0.0 (ca6c273)
