### ISSUE TITLE
Information only on improper formatting of cross references in Hindi USFM

### ISSUE THREAD

**Issue by jobbyp** [unfoldingWord/translationCore#6140]
![image](https://user-images.githubusercontent.com/38230054/59348778-02de4a80-8ce6-11e9-9989-002395839b53.png)

### Prerequisites

* Put an X between the brackets on this line if you have done all of the following:

- [x] I have searched the [issues](https://github.com/unfoldingWord-dev/translationCore/issues) of this repository and believe that this is not a duplicate.

### Description

[Description of the issue]

### Steps to Reproduce

**Screenshots**

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

### Context

**Enviorment**
| Tech         | Version |
|--------------|---------|
| tc           | v0.?.?  |
| build #      |         |
| OS           |         |

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by jobbyp** [comment]
https://git.door43.org/Door43-Catalog/hi_ulb
[hi_ulb-master.zip](https://github.com/unfoldingWord-dev/translationCore/files/3281609/hi_ulb-master.zip)

**Comment by jobbyp** [comment]
This text is taken from Genesis 1:1

**Comment by cckozie** [comment]
@jobbyp The cross references in the text are not using the usfm markers required for cross references, so tC just regards them as plain text. 
\v 1 आदि में परमेश्‍वर ने आकाश और पृथ्वी की सृष्टि की। (इब्रा. 1:10, इब्रा. 11:3)

See http://paratext.org/system/files/usfmReference2_4.pdf beginning at page 48 for proper formatting of cross references.

**Comment by cckozie** [comment]
I tested the Hindi Titus project after modifying the usfm for 3:6 to properly format the cross ref markers. tC handles them correctly; they show in the text when editing, but not in the wA word bank, scripture pane, or tN or tW check pane.
\v 6 \x - \xo 3:6 \xt योए. 2:28 \x* जिसे उसने हमारे उद्धारकर्ता यीशु मसीह के द्वारा हम पर अधिकाई से उण्डेला।

**Comment by elsylambert** [comment]
Not seeing this issue in 2.2.0 (2375ae5).
