### ISSUE TITLE
tC crash on USFM import

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6141]
- [ ] If fails, must fail gracefully

 1.2.0 (7e2080f)
This is a Hindi project
[01-GEN.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/3281761/01-GEN.usfm.zip)

![image](https://user-images.githubusercontent.com/8171759/59359310-bac62480-8cf3-11e9-8b94-2fb481cb1e64.png)

This may be due to (invalidly formatted) cross references in the usfm
\s5
\c 1
\s सृष्टि का इतिहास
\p
\v 1 आदि में परमेश्‍वर ने आकाश और पृथ्वी की सृष्टि की। (इब्रा. 1:10, इब्रा. 11:3)
\v 2 पृथ्वी बेडौल और सुनसान पड़ी थी, और गहरे जल के ऊपर अंधियारा था; तथा परमेश्‍वर का आत्मा जल के ऊपर मण्डराता था। (2 कुरि. 4:6)
\s पहला दिन—उजियाला
\p
\

**Comment by richmahn** [comment]
@benjore @cckozie Been investigating this one today and not able to reproduce in 2.0.0 dev build. Was able to reproduce with the build Koz gave in the description, looked at the code at that time and it is no longer like that at all, so has been fixed already, no place in the code to change to make anything "fail gracefully." Putting a re-test label on it.

**Comment by cckozie** [comment]
It no longer fails/crashes in 2.0.0 (15ce3cd). The references now appear in the scripture pane and in the word bank, which I assume is expected behavior since the references do not have the proper usfm encoding.
