### ISSUE TITLE
Incorrect words in the "Please select the translation for" pane

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6143]
## Notes
- [ ] It appears that the fix that was applied to the Scripture Pane needs to be applied in the Checking box as well. It appears to be generating data in the old way

Was a problem in 1.1.4 and still is in 1.2.0 (7e2080f)
![image](https://user-images.githubusercontent.com/8171759/59375863-a5adbd80-8d14-11e9-85c2-fd5a5c23cf46.png)

**Comment by PhotoNomad0** [comment]
**Note:**
- VerseCheckWrapper is defined in `checking-tool-wrapper`.  Which calls `checkAreaHelpers.getAlignedGLText()` which calls `getAlignedText()`
  - find duplicated functions in app:
    - in tCore have `gatewayLanguageHelpers.getAlignedText()`.  Called by `gatewayLanguageHelpers.getAlignedGLText()` which is called by `gatewayLanguageHelpers.getGatewayLanguageCodeAndQuote()` which is called whenever a check entry is recorded.
    - in `tc-ui-toolkit` have `checkAreaHelpers.getAlignedText()` (same as above).  Does not appear to be used in `tc-ui-toolkit` or exported
    - in `checking-tool-wrapper` have `checkAreaHelpers.getAlignedText()` (same as above).  Used by VerseCheckWrapper.
- Scripture pane is in `tc-ui-toolkit` which calls `ScripturePane.getPanes()` which calls `verseHelpers.verseArray()` which calls `highlightHelpers.getWordHighlightedDetails()`

**Comment by PhotoNomad0** [comment]
@cckozie - this same bug will be in CSV output, since we are picking up the first occurrence of a word rather than the correct instance.

**Comment by PhotoNomad0** [comment]
@cckozie - unfortunately it is different function needed by Check area than used by Scripture pane, Scripture pane needed a method that created an array of html spans with the highlights overlaid.  Check area needed a string of words that mapped the strongs number to GL words.

**Comment by PhotoNomad0** [comment]
Verified in translationCore 1.2.0 (4b9a560)

**Comment by elsylambert** [comment]
Verified in #1.2.0 (f215a2f)
Not seeing any issues. "Please select the translation for" pane displays the selections highlighted in the scripture pane.

**Comment by cckozie** [comment]
Looks good in 1.2.0 (a3ee18b)
