### ISSUE TITLE
Allow moving a merged original language word to be directly merged with a different original language word

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6148]
After the implementation of #4791, users are allowed to merge discontiguous original language (ol) words as well as unmerge a middle word in combinations of 3 or more merge ol words.

It would make sense now to allow moving any of the merged words directly to a different ol word (or group) rather than having to first unmerge it by moving it to the small box inserted when a merged ol word is being dragged.

## Behavior

Rules (in this order): 
1. If two Original Language words are unmerged, all aligned target words get invalidated and sent back to the word bank. 
2. If two Original Language words are merged, all aligned target words should be merged as well. 

So in the case of one action that encompasses both of the above rules, the unmerge must be considered first. See examples below: 

## Examples

[Green arrows show which word is being dragged where]
When an unaligned OrigL is merged to an aligned OrigL, nothing should be invalidated:
[1:0 -> 1:1 = 2:1]
![image](https://user-images.githubusercontent.com/13352518/59459089-95afdf80-8de1-11e9-9e22-2aee2fc41109.png)

[1:0 -> 1:many = 2:many]
![image](https://user-images.githubusercontent.com/13352518/59459098-9ba5c080-8de1-11e9-801b-6478f8b59b88.png)

When dragging an aligned OrigL word, the bottom word(s) should follow it, no invalidations should happen: 
[1:1 -> 1:0 = 2:1]
![image](https://user-images.githubusercontent.com/13352518/59458562-546b0000-8de0-11e9-9477-5eda4c5cad30.png)

[1:many -> 1:0 = 2:many]
![image](https://user-images.githubusercontent.com/13352518/59458666-8b411600-8de0-11e9-98e9-0afbd06447e8.png)

[1:1 -> 1:many = 2:many]
![image](https://user-images.githubusercontent.com/13352518/59458814-e6730880-8de0-11e9-8797-5c993b49360f.png)

[1:many -> 1:many = 2:many]
![image](https://user-images.githubusercontent.com/13352518/59458948-3520a280-8de1-11e9-831c-260f5645d5e1.png)

When dragging an OrigL word (aligned or unaligned) onto multiple merged OrigL words, no invalidation of bottom words happens: 
[1:0 -> many:many = many:many]
![image](https://user-images.githubusercontent.com/13352518/59459534-9e54e580-8de2-11e9-9d43-cdc345bdcf49.png)

[1:1 -> many:many = many:many]
![image](https://user-images.githubusercontent.com/13352518/59459540-a44ac680-8de2-11e9-8523-037e274f4a35.png)

[1:many -> many:many = many:many]
![image](https://user-images.githubusercontent.com/13352518/59459553-aad93e00-8de2-11e9-92b5-bc7371673857.png)

When un-aligning merged OrigL words, the bottom words are returned to the word bank: 
![image](https://user-images.githubusercontent.com/13352518/59459898-7dd95b00-8de3-11e9-9102-8d9b427a8c9b.png)

![image](https://user-images.githubusercontent.com/13352518/59459917-85006900-8de3-11e9-8df9-6a08a10c0977.png)

When unmerging and merging (in one action) aligned OrigL words, the unmerge function resets all corresponding bottom words, but the merge function does not reset any bottom words: 
![image](https://user-images.githubusercontent.com/13352518/59460275-520aa500-8de4-11e9-8956-9ce5856af1c0.png)

![image](https://user-images.githubusercontent.com/13352518/59468144-f72e7900-8df6-11e9-98e8-3077d6ce98d0.png)

**Comment by PhotoNomad0** [comment]
**_Note:_**

It looks like moveSourceToken() in WA can be modified to handle special case when merging to preserve the alignments.  Will need to add special handling for single greek word from single word to move previous alignments into new alignment.

**Comment by PhotoNomad0** [comment]
Verified in translationCore 1.2.0 (6390394)

**Comment by cckozie** [comment]
Looks good in 1.2.0 (05888d5) 
Needs regression

**Comment by elsylambert** [comment]
Verified in 1.2.0 (736956e). working fine.
