### ISSUE TITLE
The Door43 repository was not renamed error message when requesting to create a new repo during project rename

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6151]
1.2.0 (2372490)
Upload a project to Door43
Edit the project details to change the translation id
Select the "Create new repo" option on the alert
The Door43 repository was not renamed error message is returned even though the user requested to create, not rename. The new repo actually is created even though there was failure message.

**Comment by elsylambert** [comment]
Retested on 2.0.0 (ca6c273). Not seeing this issue.
