### ISSUE TITLE
Export of ULT Rev fails and user was not notified

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#6153]
### User Story
Larry would like to export the ULT book of revelation to as aligned USFM and upload to D43.

Currently there is an error creating aligned USFM file with this book ([en_ult_rev_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/3297254/en_ult_rev_book.zip)) .  The problem is that this project had an empty alignment for verse 18:25 even though the target verse is not there.  This could be due to UGNT previously having text or a footnote for 18:25.

Unfortunately there are two problems that need to be fixed: 
- on export need to ignore alignments for empty verses.
- fix error handling that exception was not reported giving illusion of upload success.

### Features / Specifications

- [ ]  Fix USFM/alignments need to ignore alignment data for empty target verses.  In WordAlignmentHelpers.convertAlignmentDataToUSFM().  Before the call to UsfmFileConversionHelpers.cleanAlignmentMarkersFromString() we need to add a check if the verse is defined in targetLanguageChapterJSON before processing it.
- [ ] Fix error handling that exception was not reported giving illusion of upload success.  In WordAlignmentActions.getUsfm3ExportFile() on line 48  and error other than invalidation is reported to console, but it is not handled.  It looks like reject should be called to propagate the error to USFM export or D43 upload.

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by PhotoNomad0** [comment]
Verified in translationCore 1.2.0 (85c929c)

**Comment by cckozie** [comment]
Looks good in 1.2.0 (05888d5)
Upload to Door43 does actually succeed.
In USFM export w/alignments, 18:25 is deleted.
I was unable to find a way to test for an upload failure.

**Comment by cckozie** [comment]
1.2.0 (05888d5) 
Upload does succeed.

**Comment by elsylambert** [comment]
Verified in 1.2.0 (736956e). Successfully uploaded the project to D43. Also, Export to USFM does not have the verses 18:25.
