### ISSUE TITLE
Error on screen while loading translationWords

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/translationCore#6157]
#1.2.0 (b1cd66e) 
Steps to re-create:
1. Opened a Project in translationWords and was working fine.
2. Left tC run and hibernated the computer.
3. When logged back in and tried to launch translationWords, the screen was hung for a while and then displayed "ERROR" on the screen.
4. Had to restart tC to bring it back on.

[Wed Jun 19 2019.zip](https://github.com/unfoldingWord-dev/translationCore/files/3306319/Wed.Jun.19.2019.zip)

[en_ulb_tit_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/3306322/en_ulb_tit_book.zip)

Second Occurrence
1. Project was open in tC, was working on tW.
2. tC went inactive for about 30 minutes (while I was attending stand-up meeting and discussion with Koz )
3. Came back to tC and Lauched tN, got the Error screen.
![error screen](https://user-images.githubusercontent.com/51806180/59791829-ea9b9c00-92a0-11e9-9c7a-b6a800da39ce.png)

**Comment by benjore** [comment]
Seems to be a Windows hibernation issue.

**Comment by elsylambert** [comment]
Not an issue in 2.0.0 (ca6c273).
