### ISSUE TITLE
The selection for words in the instructions pane  shows up in English instead of the gateway language

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/translationCore#6159]
#1.2.0 (b1cd66e)
![instruction pane.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/c21719c8-eb66-4239-89b3-3b55bb76afbe)

Steps to re-create:
1. Opened a Hindi Project in tW.
2. In the instructions pane, the word to highlight is displayed in English rather than in Hindi, so the correct selection cannot be made.

[hi_eph_eph_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/3306842/hi_eph_eph_book.zip)

 Koz and I found this issue in my computer, but unable to replicate this issue now.

**Comment by benjore** [comment]
@elsylambert It looks like the project is Hindi, the locale is Hindi, but the GL selected is English. If this is the case, then it is displaying correctly. Can you retest to see if it can be reproduced?

**Comment by benjore** [comment]
Might be related to https://github.com/unfoldingWord-dev/translationCore/issues/6253 .

**Comment by elsylambert** [comment]
@benjore Yes,in the scenario the GL selected was English, hence the display is correct. This issue can be closed.

#6253 can be reproduced in tW and tN.
