### ISSUE TITLE
Add support to the source content updater to handle TSVs base off of the UGNT version it was generated from.

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord/translationCore#6161]
### User Story

As a [type of user], I want [some goal] so that [some reason].

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by mannycolon** [comment]
Per @jag3773 on Slack:
> @ben_jore @mannycolon You also need to be thinking about how tC will get a prior version of the UHB or UGNT if that is called for by the UTN manifest file.  I'm not sure if tC has support for that but the catalog does maintain the historical versions so you should be able to get it if needed. (related to my comment in #wg-content )

**Comment by benjore** [comment]
Dup of #6168
