### ISSUE TITLE
Extra Alert message while importing from translationStudio to tC

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/translationCore#6164]
#1.2.0 (7caed9f).

This alert does not show up in 1.1.4.

Steps to recreate:
- Import a tS project into tC.
- Follow the steps>Continue> after the File has been renamed, it shows up the alert for a few seconds.
- In some cases, the user has to dismiss the alert.
- It sometimes occurs when selecting an existing project.
![tS project into tC.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/2b3d8669-f2ed-40c5-8963-8ae3812c47df)

- The message is not user friendly and should be such that the user can understand.

[Thu Jun 20 2019 (2).zip](https://github.com/unfoldingWord-dev/translationCore/files/3310996/Thu.Jun.20.2019.2.zip)

[en-x-demo1_php_text_ulb_mc.tstudio.zip](https://github.com/unfoldingWord-dev/translationCore/files/3310998/en-x-demo1_php_text_ulb_mc.tstudio.zip)

**Comment by elsylambert** [comment]
[Video_importing tS project.zip](https://github.com/unfoldingWord-dev/translationCore/files/3311006/Video_importing.tS.project.zip)

**Comment by cckozie** [comment]
No longer seeing this problem in 2.0.0 (ca6c273) even on my slow Windows machine.
