### ISSUE TITLE
WIndows and Mac show different server dates for the resources on the resources download page

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6165]
We both installed 1.2.0 (7caed9f) this morning. 
On Mac:
![image](https://user-images.githubusercontent.com/8171759/59870390-1713ee80-935b-11e9-9d30-46d507a1591f.png)

On Windows:

**Comment by elsylambert** [comment]
![Content updates screen](https://user-images.githubusercontent.com/51806180/59870565-c0f77900-9363-11e9-813e-b1a9f3ac8690.jpg)

Windows Screenshot

**Comment by cckozie** [comment]
This appears to be fixed in 2.0.0 (ca6c273)
