### ISSUE TITLE
Update Original Language resources based on tN versioning system

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#6168]
### User Story

As a tC user, I want to tC to be able to handle multiple GLs for tN that use different versions of the Original Languages so that tC doesn't break over needing a newer or older referenced version of tN.

### Features / Specifications

- [x] If UGNT/UHB is updated, the previous version will be deleted unless a version of tN on the system requires it.
- [x] Update the source content updater so that if tN is updated and references a version of UGNT/UHB that is not on the file system, it updates that as well. 
- [x] If tC tries to open a tool that calls for a version of UGNT/UHB that is not on the file system, it is prohibited from doing so, a warning is thrown with an option to download that resource. (Note: this needs to be able to download an older version of UGNT/UHB.)
- [x] Make project loading process support adding older versions of UHB or UGNT bibles based on tN checks

Copied from #6191

- [ ] (L) When the UGNT or UHB is updated: 
  - [ ] Check the manifests for each tN for each GL...
    - [ ] If there is a tN that requires the old version, keep that version of the UGNT/UHB. 
    - [ ] If no tN's require the old version, delete it. 

= = = = = = 

Basic rules: 
1. If tN is updated from a previous version, delete the old version. 
2. If UGNT/UHB is updated, the previous version will be deleted unless a version of tN on the system requires it. 
3. tN can only be opened with the matching version of UGNT/UHB
4. If tC does not have the UGNT/UHB required, the user should be prompted and tC should go get it from DCS
### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by mannycolon** [comment]
- [ ] Need to make project loading process support the usage of older UHB or UGNT bibles based on tN checks

**Comment by cckozie** [comment]
1.2.0 (f3f2aa7)
If the local UGNT version is less than that specified in the manifest, the download succeeds and the user is then allowed to open the project in tN.
If the local UGNT version is greater than that specified in the manifest, the download appears to succeed, but as soon as it completes, the newly downloaded version of the UGNT is deleted from the resources folder. The user is still prevented from opening the project in tN.

**Comment by mannycolon** [comment]
@cckozie can you share the project you used to replicate this problem and the specific steps you took to get to this point.

**Comment by cckozie** [comment]
@mannycolon - I doubt that it is project dependent, but attached is the one I used.
I first opened it in tN to get the new manifest entry.
I closed tC and updated the manifest to indicate it needed UGNT version 0.7
I restarted tC and attempted to load the project in tN. 
When prompted to download the needed source, I clicked the Download button and then watched in the UGNT resources folder to see what happened.

[en_ultt_rev_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/3370599/en_ultt_rev_book.zip)

**Comment by cckozie** [comment]
1.2.0 (05888d5) 
The needed UGNT is now downloaded and persisted on the file system.
Verified that the correct version of the UGNT is used in the projects when opened in tN.
Needs regression

**Comment by elsylambert** [comment]
Verified in 1.2.0 (89d7abe). Working fine.

**Comment by cckozie** [comment]
I noticed this behavior when testing #6541.
The latest UGNT is v0.8 which is on the system.
There is a project that needs UGNT v0.7 for the tN tool.
When attempting to open the project, the user is prompted to download the resource, the download succeeds, and the project opens correctly in tN.
If tC is ended and the UGNT v0.8 is deleted, when tC is restarted UGNT v0.8 is again added to the system, and UGNT v0.7 is deleted.
When the project that needed UGNT v0.7 is again loaded in tN, its manifest is updated to now specify UGNT v0.8.

Is that the expected behavior?
Under what conditions should we expect UGNT v0.7 to remain on the system?

**Comment by mannycolon** [comment]
Whenever the resources are updated and a project is opened its resources are updated if needed which includes the tn files for that project. thus what happened above.

**Comment by mannycolon** [comment]
We should probably not delete the ugnt v0.7 on missing resource copying process (copying a resource from the static folder) if that resource will be needed by a tN resource

**Comment by cckozie** [comment]
1.2.0 (736956e) 
Missed this problem when testing the issue previously, but this change causes a problem when reimporting a project. When reimporting a project with Overwrite, the user received the "The current tool requires a different version of the UGNT" alert incorrectly and when the Download button is clicked, the "Failed to download source content updates." alert is displayed. The project cannot be opened in tN.
To replicate:
1. Import a USFM project. I used this one. [62-2PE.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/3392555/62-2PE.usfm.zip)
2. Load the project in tN
3. Export the project to USFM without alignments
4. Import the exported project choosing the Overwrite options on the alerts
5. Attempt to load the project tN
6. Click the Download button on the different version of UGNT needed alert

**Comment by mannycolon** [comment]
verified on 459884d

**Comment by elsylambert** [comment]
verified on 2.0.0 (459884d). Not seeing any issue with Project import with Overwrite.

**Comment by cckozie** [comment]
Looks good in 2.0.0 (459884d) 
Needs regression
