### ISSUE TITLE
Only display GL's in the GL dropdown list on the tN card if there are tN's defined for the GL/project combination.

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/translationCore#6177]
# 1.2.0 (3d98a37)

This is related to #6174.
Issue 1: The Gateway Language dropdown should not display Hindi as there are no Hindi tN checks for Ephesians. 
![tN Hindi.jpg](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/f9f64946-23a3-45ba-b620-6cce9b92e359)
Issue 2: Still able to Launch and see the below screen:
![image.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/d5a36204-a80e-4361-8559-76c0c96312ff)
It should only show the ones that are selected on the tN card (which we can't see, but suspect all are checked even though hidden from view)

**Comment by benjore** [comment]
@elsylambert Can you explain Issue #2 more fully? I'm not understanding what the problem is.

**Comment by elsylambert** [comment]
@benjore Issue 2: Usually on tN card, we check/un-check the checks and click on Launch button to see the specific Checks.
In this Scenario, There is no tN checks available for Ephesians and there are no check boxes on the card as you can see in the first screenshot, but the Launch button is still enabled and when clicked it opens the project in tN with all the checks.
 It should only show the ones that are selected on the tN card (which we can't see in this case, but suspect that all are checked even though hidden from view)

**Comment by cckozie** [comment]
Still a problem in 1.2.0 (9f6a878) 
Since there are no Hindi tN checks defined for EPH, Hindi should not appear in the GL dropdown.

![image](https://user-images.githubusercontent.com/8171759/61325578-b00f1b80-a7da-11e9-9b98-874de00422a3.png)

**Comment by cckozie** [comment]
In 2.0.0 (cd0f9f1) 
I am no longer seeing Hindi as an available GL for books that do not have Hindi tN's defined. 
While testing this, I noticed that there are several cases where Hindi does not show as an available GL when it should. That was an existing problem not noticed before. It is written up in #6298.

**Comment by elsylambert** [comment]
Not seeing this issue in 2.0.0 (bd37460). When tN resources are not available for a GL, that GL is not available in tN GL Drop-down.
