### ISSUE TITLE
wA tool card shows 0% complete after importing a fully aligned usfm project

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6181]
1.2.0 (b757c2a)
[58-PHM.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/3331674/58-PHM.usfm.zip)
Imported the attached file. wA tool card shows 0%.
After opening in wA and returning to the Tools page it shows 100% complete

**Comment by RoyalSix** [comment]
This one seems to be working on the latest develop build a2e3d31

**Comment by cckozie** [comment]
It is working correctly now in 1.2.0 (f3f2aa7)

**Comment by elsylambert** [comment]
@cckozie .With latest build 1.2.0 (c1dae4b) , the issue has resurfaced. For fully aligned project the tool card shows 0 % and once we open and come back to tool card it shows, 98% or 100 %. 

Testing in progress.

**Comment by RoyalSix** [comment]
I am not able to reproduce this error, if you are still seeing it could you send me your project folder @elsylambert

**Comment by elsylambert** [comment]
@RoyalSix  Not seeing this issue in 2.0.0 (b203700). In the existing projects with 100 % alignments(which were showing 0% previously) are showing 100% now. Imported a fully aligned project and the tool card showed 100%. Seems to be working fine now.

**Comment by elsylambert** [comment]
@cckozie Do you have any fully aligned projects which are showing 0% on the tool card?

**Comment by cckozie** [comment]
@elsylambert In 2.0.0 (b203700) I am seeing 0% after importing both of these. After going back to the Projects page and then back to Tools page it then shows 100%.
[43-LUK.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/3413069/43-LUK.usfm.zip)
[66-JUD.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/3413074/66-JUD.usfm.zip)

**Comment by cckozie** [comment]
2.0.0 (99b8027) 
The above referenced project still showing 0% complete in wA on initial import on Mac.
Apparently a Mac-only issue now.

**Comment by elsylambert** [comment]
2.0.0 (99b8027). This is very strange that I am able to see this issue now on my windows machine with my existing fully aligned project as well as the projects that Koz attached with this issue. which were showing 100% few hours back on the same build and now it shows 0%.

**Comment by cckozie** [comment]
2.0.0 (15ce3cd)
The problem is now intermittent on my Mac.
After running a test that imports a fully aligned Matthew usfm project and doing edits in wA, tW, and tN, then importing the PHM project in the first comment, wA shows 0% after importing it.
![image](https://user-images.githubusercontent.com/8171759/62056223-d2456800-b1e2-11e9-923e-c5a0ec4480b2.png)
Then after ending tC, deleting the imported project, restarting tC and importing it again, the wA tool card now shows 100%. On additional usfm imports wA also shows 0%.
Here is the full log: [Mon Jul 29 2019.log.zip](https://github.com/unfoldingWord-dev/translationCore/files/3442732/Mon.Jul.29.2019.log.zip)

**Comment by RoyalSix** [comment]
Steps to reproduce:
- Load a fully aligned project
- Make verse edits
- Load another fully aligned project from usfm
- Go to tool card

**Comment by cckozie** [comment]
I am no longer seeing the problem in 2.0.0 (cd0f9f1)

**Comment by elsylambert** [comment]
2.0.0 (8f84296). Not seeing tool Card issue in wA.

**Comment by PhotoNomad0** [comment]
@RoyalSix @elsylambert @cckozie - I am seeing this issue in translationCore 2.0.0 (8f84296)

**Comment by PhotoNomad0** [comment]
When I open this project: [en_ult_3jn_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/3457705/en_ult_3jn_book.zip), I see 0% on tW.

It looks like the project selections folder has the data, but the group data has the selections false.  We used to check for this on project open.  Let me check.

**Comment by elsylambert** [comment]
Not seeing issue with the 3Jn project in my machine.
![image](https://user-images.githubusercontent.com/51806180/62310936-9f0c0e80-b458-11e9-80ee-78aec5be462b.png)

**Comment by PhotoNomad0** [comment]
Sorry, I put this on wrong issue ^^^
