### ISSUE TITLE
After overwriting a project during import, the app does not proceed to the Tools page and an error is displayed when selecting the project

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6182]
1.2.0 (b757c2a)
I suspect this was broken by either #5686 (not supposed to be in this build), or #6001 or #5832
Export a project to usfm without alignments
Edit the exported file to make some changes
Import the edited file choosing the Overwrite options
After clicking the Overwrite button on the warning alert, the user is returned to the projects page instead of continuing to the tools page.
When selected, this alert is displayed:
![image](https://user-images.githubusercontent.com/8171759/60210772-4b881e80-9823-11e9-9051-b87f402001ed.png)
[en_ult_phm_book 2.zip](https://github.com/unfoldingWord-dev/translationCore/files/3331721/en_ult_phm_book.2.zip)

**Comment by PhotoNomad0** [comment]
**Note**:
When I open this project in WA, see the above error in the log.  It looks like the contextId is missing in the invalidation log.

**Comment by cckozie** [comment]
Original project: [en_ult_phm_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/3334746/en_ult_phm_book.zip)
Overwrite file: [58-PHM.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/3334750/58-PHM.usfm.zip)

**Comment by PhotoNomad0** [comment]
Note:
This is looking like a resource error.  With empty resources I don't see the error, but with latest resources downloaded I can reproduce.

**Comment by PhotoNomad0** [comment]
It looks like this was broken in some overwrite changes in https://github.com/unfoldingWord-dev/translationCore/pull/6173 - part of #5686

**Comment by PhotoNomad0** [comment]
Verified in translationCore 1.2.0 (f215a2f)

**Comment by cckozie** [comment]
Works correctly in 1.2.0 (f215a2f)

**Comment by elsylambert** [comment]
Veified in 1.2.0 (f215a2f) and found to be working fine.
