### ISSUE TITLE
For tN projects, copy the version number of the UGNT/UHB from which it is based into the tC project manifest.

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#6184]
- [x] Copy the UGNT/UHB version number into the tN content/data/metadata
- [x] Prevent tC from opening up a project in the tN tool where the tN (for the selected GL) has a differing version number of the UGNT/UHB

**Comment by cckozie** [comment]
1.2.0 (f3f2aa7)
tsv_relation":["en/ult","el-x-koine/ugnt?v=0.8","hbo/uhb?v=2.1.7"] text has been added to the project's manifest file.
The user is prevented from opening a project in tN if the UGNT version does not match
The user is given the opportunity to download the needed version.

**Comment by elsylambert** [comment]
Verified in 1.2.0 (05888d5). Not seeing any issues with the UGNT/UHB versions in Project manifest file.
needs regression.
