### ISSUE TITLE
How to handle resource updates in light of the tN tool

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#6191]
- [ ] (L) When the UGNT or UHB is updated: 
  - [ ] Check the manifests for each tN for each GL...
    - [ ] If there is a tN that requires the old version, keep that version of the UGNT/UHB. 
    - [ ] If no tN's require the old version, delete it. 

= = = = = = 

Basic rules: 
1. If tN is updated from a previous version, delete the old version. 
2. If UGNT/UHB is updated, the previous version will be deleted unless a version of tN on the system requires it. 
3. tN can only be opened with the matching version of UGNT/UHB
4. If tC does not have the UGNT/UHB required, the user should be prompted and tC should go get it from DCS

**Comment by mannycolon** [comment]
Dup of #6168
