### ISSUE TITLE
Test other versions of Greek as resources

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#6193]
Mock import the following Greek versions into the Scripture pane to see if anything bad happens. 

- https://git.door43.org/STR/el-x-koine_tisch
- https://git.door43.org/STR/el-x-koine_maj-rp

**Comment by PhotoNomad0** [comment]
Here are the zipped processed Bibles: 
[maj-rp.zip](https://github.com/unfoldingWord-dev/translationCore/files/3352022/maj-rp.zip)
[tisch.zip](https://github.com/unfoldingWord-dev/translationCore/files/3352023/tisch.zip)


unzip these into folder ⁨`resources/el-x-koine⁩/⁨bibles⁩` to use.  Unfortunately when you add these to scripture pane it always loads the ugnt (seems to be a hard coding when it is an original language that we only load the ugnt or uhb bibles).

**Comment by PhotoNomad0** [comment]
@benjore @cckozie @elsylambert - The short answer is that we can process the greek bibles when we download content from catalog, but we need to make some changes to tCore to support more than one bible in the original languages.

I have a fix here - would this be sufficient for this issue?

![Screen Shot 2019-07-03 at 6 36 44 AM](https://user-images.githubusercontent.com/14238574/60585287-5a0f9200-9d5d-11e9-90ef-14be7c47f7be.png)

Note that the Greek bible books other than the ugnt are listed by actual language `el-x-koine⁩` because tCore currently can only have one book each tagged as "original language" for Greek and Hebrew.

**Comment by benjore** [comment]
That looks good to me.

**Comment by PhotoNomad0** [comment]
Slack comment from @benjore - In the Scripture Pane, the abbreviation needs to be updated, `Original Language` is a fine descriptor.

**Comment by elsylambert** [comment]
Tested in 1.2.0 (05888d5).
The different version loads up fine in tC. But the meta data associated with the Greek words are different for the same words in different version. Please refer the snapshots, for word "God" in Greek:
UGNT
![Greek-God](https://user-images.githubusercontent.com/51806180/61058822-f2dd8780-a3c5-11e9-997b-f28476c77682.jpg)
Greek- MAJ-RP
![Greek-majrp](https://user-images.githubusercontent.com/51806180/61058844-fa049580-a3c5-11e9-8c83-bbb27c26bc23.jpg)
Greek-TISCH
![Greek-tisch- god](https://user-images.githubusercontent.com/51806180/61058857-01c43a00-a3c6-11e9-9d11-df0b90079565.jpg)

**Comment by cckozie** [comment]
The additional Greek resources do not cause v1.1.4 to break, but when a user selects them to be displayed in the scripture pane, tC loads the UGNT instead, and the selected resource remains in the dropdown list. There doesn't appear to be a way to get them to load into the scripture pane in 1.1.4.

1.1.3 behaves the same way as 1.1.4.

**Comment by PhotoNomad0** [comment]
Slack comment from @benjore on how to deal with popups on the Greek bibles that are not UGNT: Disable for now. It should be a content fix not a tC fix.

**Comment by PhotoNomad0** [comment]
> The additional Greek resources do not cause v1.1.4 to break, but when a user selects them to be displayed in the scripture pane, tC loads the UGNT instead, and the selected resource remains in the dropdown list. There doesn't appear to be a way to get them to load into the scripture pane in 1.1.4.
> 
> 1.1.3 behaves the same way as 1.1.4.

@cckozie - I presume this is just here to capture previous behavior?

**Comment by PhotoNomad0** [comment]
@benjore - this investigation issue is open ended.  We should probably add definition of done for this as it is already an unsized effort that can continue to creep in scope.

**Comment by PhotoNomad0** [comment]
only ugnt and uhb are clickable now
Verified in translationCore 2.0.0 (1d9a4c5)

**Comment by cckozie** [comment]
2.0.0 (00bca0b)
Able to load the alternate Greek texts into the scripture pane, but not able to click on their words to open the Lexicon.

**Comment by elsylambert** [comment]
Verified in 2.0.0 (00bca0b). Not seeing any issues with Lexicon. New Greek Versions are not clickable and are loaded fine into the scripture pane.
