### ISSUE TITLE
Add "Quote Strings" for the tN

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#6199]
### User Story

As a [type of user], I want [some goal] so that [some reason].

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by PhotoNomad0** [comment]
@benjore - Needs more detail here.

**Comment by mannycolon** [comment]
Add the field "quoteString" to the tN group data files.
```
{
   ...,
   "tool": "translationNotes",
   "quote": [ ... ],
   "quoteString": "χάρις καὶ εἰρήνη",
    ...,
}
```

**Comment by mannycolon** [comment]
Verified on bedda83

**Comment by cckozie** [comment]
1.2.0 (9f6a878)
Seeing the field after updating en tN resources

**Comment by elsylambert** [comment]
Verified in 1.2.0 (9f6a878). The quote string is added for tN resources. Seeing after the resources update.
