### ISSUE TITLE
Update Verbiage on Tool card and import page

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#6203]
### User Story

As a [type of user], I want [some goal] so that [some reason].

### Features / Specifications

![image](https://user-images.githubusercontent.com/13352518/60911408-ac165300-a248-11e9-8fac-6fb2e28c613a.png)

- [ ] On the online project import dialog... Update to say, "translationCore supports projects for any book of the Bible."

![image](https://user-images.githubusercontent.com/13352518/60911616-352d8a00-a249-11e9-93b5-6f3b43c379e3.png)

- [ ] On the tools page... Update to say, "Select a tool and a gateway language from the list. translationCore supports projects for any book of the Bible. However, the project will only open in translationWords or translationNotes if the necessary resources for the selected Gateway Language are on your system. Click "Actions / Check for Content Update" to download the latest.
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by PhotoNomad0** [comment]
@benjore - Need more detail here.

**Comment by mannycolon** [comment]
Verified on c5e5865

**Comment by elsylambert** [comment]
Verified in 1.2.0 (4cdc817). The verbiage has been changed for import page and Tools page.
Needs a little formatting on the Tools page. As highlighted in the screenshot, there should be a space before "However" and the paragraph following it is Justify aligned, so there are more spaces between the words with compared to the first two lines.

![image](https://user-images.githubusercontent.com/51806180/61249212-b772ee00-a722-11e9-882e-4c0c6d691c83.png)

**Comment by mannycolon** [comment]
Verified  on 9f6a878

**Comment by elsylambert** [comment]
1.2.0 (9f6a878). Still seeing extra spaces in the Instruction text after every word in "translationWords or translationNotes if the necessary resources for the selected Gateway Language are on your system. Click "Actions / Check for content updates" to download the latest."
![image](https://user-images.githubusercontent.com/51806180/61299424-0fa30200-a7ae-11e9-8e06-7ebd021fc587.png)

**Comment by mannycolon** [comment]
Verified e79d677

**Comment by elsylambert** [comment]
Looks good in 2.0.0 (459884d).

**Comment by cckozie** [comment]
2.0.0 (459884d)
@benjore - There is difference in capitalization between the text on the tool card and what you specified in the first comment on this issue. 
Text in your comment '... Click "Actions / Check for Content Update" to download '
Text on the  tools page '... Click "Actions / Check for content updates" to download'
Since the text on the tools page actually matches what is on the Actions menu, I assume this is what is desired. Is that correct?

**Comment by benjore** [comment]
That is correct. An opportune following the "spirit of the law"... intentionally or not...

**Comment by cckozie** [comment]
Fixed in 2.0.0 (459884d)
