### ISSUE TITLE
Fix the location of the three-dots icon on the Projects page

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#6204]
![image.png](https://images.zenhubusercontent.com/55e5f3984f7a08fbb7f4a658/9bd336ba-c794-4053-8f61-b43c971f919e)

**Comment by PhotoNomad0** [comment]
@benjore - I presume that you want the icon close to the text "click"?

**Comment by elsylambert** [comment]
1.2.0 (9f6a878). The location of the three dots is fixed in Projects page.
![image](https://user-images.githubusercontent.com/51806180/61300300-b8059600-a7af-11e9-89bd-656906812084.png)

**Comment by cckozie** [comment]
Looks good in 1.2.0 (9f6a878)
