### ISSUE TITLE
tC Crashes On Overwrite

### ISSUE THREAD

**Issue by RoyalSix** [unfoldingWord/translationCore#6211]
### User Story

When overwriting the given project, tC crashes and gives an error relating to the UGNT needing to be updated but that after trying to update, it gets stuck.
projects: 
[55-1TI.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/3366527/55-1TI.usfm.zip)
[en_test_1ti_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/3366531/en_test_1ti_book.zip)

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by cckozie** [comment]
No longer a problem in 2.0.0 (ca6c273)
