### ISSUE TITLE
Need performance improvements when moving to a check in tW

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6214]
These timings were made on my fastest machine.
In 1.1.4 it took ~2 to 2.5 seconds to move to a different check by clicking in the menu in tW.
In 1.2.0 (a3ee18b) it now takes ~ 3 to 3.5 seconds, an increase of about 50%.

**Comment by elsylambert** [comment]
Not seeing this issue in 2.2.0 (2375ae5).
