### ISSUE TITLE
Reset selections should not be exported to the Selections.csv file

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6220]
1.2.0 (3ae9fb5)
The csv file  currently contains selections that were made but have been subsequently reset due to versed edits. When selections get reset, they should no longer be exported to the csv file so as to not to give the impression that the check is completed.

**Comment by cckozie** [comment]
Still a problem in 2.0.0 (ca6c273)

**Comment by PhotoNomad0** [comment]
**Notes:**

From Julip consensus, making the following changes to csv export:
- change Selections.csv to just have the most recent selections for a check - and only if selection is not empty 
- change Reminders.csv to only have the most recent reminder state for a check - and only if enabled

**Comment by PhotoNomad0** [comment]
Verified in translationCore 2.1.0 (605b3a6)

**Comment by cckozie** [comment]
@PhotoNomad0 I suspect this problem was not caused by the work you did here, but in my testing I discovered that edits performed in wA are written twice to the verseEdits file. Interestingly, the timestamp on the writes are 3-4 seconds apart, so it look like some code is running twice.
Do you want me to write up a new issue for that, or should we expand the already expanded scope of this one?

**Comment by PhotoNomad0** [comment]
@cckozie - would prefer new issue since the title of this issue is for selections.

**Comment by cckozie** [comment]
2.1.0 (605b3a6) 
Selections.csv now only has the most recent selections for a check - and only if selection is not empty
Reminders.csv now has only the most recent reminder state for a check - and only if the bookmark switch in set to On
