### ISSUE TITLE
[4] SPIKE: test tN project with ellipses instead of " ... "

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#6224]
### User Story

As a [type of user], I want [some goal] so that [some reason].

### Features / Specifications

- [ ] Here is a sample tN with ellipses 
[en_tn_41-MAT.tsv.zip](https://github.com/unfoldingWord-dev/translationCore/files/3379015/en_tn_41-MAT.tsv.zip)
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by benjore** [comment]
SPIKE for #6222

**Comment by mannycolon** [comment]
@benjore Implementing #6222 would significantly break the TSV parser. Major changes would have to be made that I can't even quantify at this point. The space before and after the ellipsis actually helps in finding the word occurrence number. If it were to me I would suggest not removing spaces before and after ellipsis.

**Comment by mannycolon** [comment]
A potential solution would be to have them make the changes they need to make and us adding spaces before and after the ellipsis just for parsing on the tsv-parser.

**Comment by mannycolon** [comment]
Copied findings on ##6222
