### ISSUE TITLE
Dissimilarities between the Bookmark switch and the Alignment Complete switch

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6226]
- [x] In the images below, the bookmark has the correct font/color scheme. Make the Alignment Complete match. 
- [x] The line under "Book" is the wrong color blue. It should be the same color as the line under URL, User, & Language. (To recreate, click on Language Code, then click Tab.)

![image](https://user-images.githubusercontent.com/13352518/61900399-28649380-aee3-11e9-98bf-1298a9d779a4.png)

1.2.0 (ca7a093)
We missed this on #5669.
The text is different size and/or boldness
The slide portion is a different color when switches are set to On
The slide portion is a slightly different color when switches are set to Off
The color of the button is slightly different with slightly different shading when switches are set to Off

![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/9fbf5474-4924-4b69-b323-d651f28dedf5)

**Comment by elsylambert** [comment]
@mannycolon Please add these ones too: 
1. On tools card, the drop-down for Available GL is light-blue:
![image](https://user-images.githubusercontent.com/51806180/62219025-90035e80-b37b-11e9-98d5-f3405b3668cd.png)
2. While changing Locale: User Interface Language window:
![image](https://user-images.githubusercontent.com/51806180/62221461-ae6b5900-b37f-11e9-9716-99d2be2ebf6a.png)

**Comment by mannycolon** [comment]
Verified on 7a21601

**Comment by elsylambert** [comment]
Looks good in 2.0.0 (71e7de6). Alignment Complete and Bookmark Toggle buttons have same Colours for On/Off Switch. And the Light blue colour has been changed to Dark blue at the import window, tool card and User interface language window.

**Comment by cckozie** [comment]
2.0.0 (71e7de6) 
The lines on the GL and Locale dropdowns were not blue on the Mac.
There are actually slight color differences on the switch in the tools, both when the switches are on and off, although the differences are not very noticeable to the naked eye. I do wonder why we do not have our standard colors defined and then used for all UI elements. Passing anyway.a
