### ISSUE TITLE
Optimize OT Lexicon pop-up

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#6247]
### User Story

From Vipin via Russ (BCS) "the lexicon pop-up in the wA tool for the OT seems to be slow compared to the NT. He says they are seeing 2+ secs to open the lexicon and similar delays for navigating to another verse in the list on the left. The example he showed me was in one of the Kings. He's using tC 1.1.4." 

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by benjore** [comment]
Possibly look into changing the pop-up library, or creating one.

**Comment by mannycolon** [comment]
@benjore This is a performance issue not a pop-up library problem.

**Comment by elsylambert** [comment]
Retested on 2.0.0 (ca6c273). Not seeing any delay in lexicon pop-up.
[Hebrew-lexicon-pop-up.zip](https://github.com/unfoldingWord-dev/translationCore/files/3591598/Hebrew-lexicon-pop-up.zip)

**Comment by cckozie** [comment]
In 2.0 the time to pop up the lexicon is about 1 second on my slow Windows machine and virtually the same in any book, either OT or NT.
Should this be closed or followed up on with Russ?

**Comment by cckozie** [comment]
2.2.0 (2375ae5) Still not seeing any difference of OT vs NT, or even on size of project. Closing.
