### ISSUE TITLE
Missing tW checks

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6250]
1.2.0 (736956e)
Many of the tW checks are missing after loading other projects in  tW.

I noticed after running a number of tests that I am now missing many of the tW checks in 1TH. After stopping and restarting tC, all of the checks now appear as expected.
![image](https://user-images.githubusercontent.com/8171759/61251128-2fd7b000-a71f-11e9-888a-5e65b8f21bf1.png)

To replicate:
1. Restart tC
2. Load this project in tW [en_prct_tit_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/3394314/en_prct_tit_book.zip)
3. Return to the Projects page
4. Load this project in tW [en_ult_1th_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/3394321/en_ult_1th_book.zip)
Note that the only checks displayed are those shown in the left side of the attached image 
5. Restart tC
6. Load the 1TH project in tW
Note that the checks now displayed are those in the right side of the attached image

Probably same bug as in #6212

**Comment by cckozie** [comment]
Looks good in 2.0.0 (aff6765) 
Needs regression

**Comment by elsylambert** [comment]
Not Seeing any issues in 2.0.0 (9016823).
