### ISSUE TITLE
Completion % on tool cards show 100% even if there are missing checks/alignments.

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6251]
As a checker or aligner I don't want the % complete on the tool cards to show 100% until every check/alignment for the tool have been completed so that I am not fooled into thinking projects are complete when they are not.

I'm assuming that 100% is being shown for incomplete projects because of rounding. 
Suggest truncating instead of rounding.

May want to consolidate with #4414.

**Comment by cckozie** [comment]
Still a problem in 2.0.0 (ca6c273) 
17:21 is not fully aligned in this project, yet the wA tool card shows 100%
[en_ult_mat_book 2.zip](https://github.com/unfoldingWord-dev/translationCore/files/3592125/en_ult_mat_book.2.zip)

**Comment by PhotoNomad0** [comment]
Verified in translationCore 2.0.0 (697040c)

**Comment by cckozie** [comment]
Looks good in 2.0.0 (f5ff634)
