### ISSUE TITLE
 Not all of the fields are displayed in the GL in tN and tW on the menu bar 

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/translationCore#6253]
- Open a Hindi project, with English as GL.
- Go Back to Tools page and select Hindi as GL.
- Note that the left menu bar and the Occurrence Notes are still in English.
- Happens vice-versa.

This did work correctly in tW in 1.1.4

**Comment by mannycolon** [comment]
Verified on  855642f

**Comment by elsylambert** [comment]
2.0.0 (9016823) . Issue is fixed for tW. For tN, the Occurrence notes are showing in English #6275 
Needs regression.

**Comment by cckozie** [comment]
Looks good in 2.0.0 (15ce3cd) other than the problem noted on #6275.
