### ISSUE TITLE
Store Settings somewhere other than LocalStorage

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#626]
LocalStorage should be able to be cleared from time to time, and we need to make sure they aren't lost after it is cleared.

**Comment by benjore** [comment]
Question: Do we want this User specific or Project specific?

**Comment by klappy** [comment]
The settings would be user/app level and not specific to each project at this point.

We need to confirm this with Christine Jarka, but this would be user specific, and potentially affected by user profiles if we choose to use them.
