### ISSUE TITLE
Selections with "No Selection Needed" saves the gateawayLanguageQuote as Greek

### ISSUE THREAD

**Issue by richmahn** [unfoldingWord/translationCore#6271]
Making a "No selection needed" and then saving that selection results in the gatewayLanguageQuote of the saved selections .json file have gatewayLanguageQuote in Greek, rather than the user's selected Gateway Language. See this one for Titus 1:1 for "faith" in tW:

```
{
  "contextId": {
    "reference": {
      "bookId": "tit",
      "chapter": 1,
      "verse": 1
    },
    "tool": "translationWords",
    "groupId": "faith",
    "quote": "πίστιν",
    "strong": [
      "G41020"
    ],
    "occurrence": 1
  },
  "selections": [],
  "nothingToSelect": true,
  "userName": "richmahn",
  "modifiedTimestamp": "2019-07-23T14:49:36.668Z",
  "gatewayLanguageCode": "hi",
  "gatewayLanguageQuote": "πίστιν" <<<====== Greek instead of Hindi ===
}
```

This is then reflected wrong in the CSV Export Selections.csv file.

**Comment by cckozie** [comment]
Not seeing a problem in the selections.csv file in 2.0.0 (ca6c273)
