### ISSUE TITLE
In tN, the English text is displayed in the smurf bar instead of the GL

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6275]
- [ ] Whatever GL is selected should be the language displayed in the Menu categories, the Smurf Bar, and the tHelps pane. 

2.0.0 (aff6765)
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/932b8a48-9fc8-4a5f-b9e9-aef5805ae555)

![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/026ec8a2-c3ae-46dc-b6a7-091ec756cd96)

**Comment by PhotoNomad0** [comment]
Note: 
- Manny suggests that maybe the contextId is not getting updated.
- Looks like he is correct, we are using the occurrenceNote from contextId.
- also found that index is hard-coded to en

**Comment by PhotoNomad0** [comment]
Verified in translationCore 2.0.0 (64f2de6)

**Comment by cckozie** [comment]
2.0.0 (c940391) **THIS PROBLEM HAS BEEN MOVED TO ISSUE #6296**
~~@PhotoNomad0 - Why do the Hindi links show up in the smurf bar when the English don't? Is it a formatting problem in the content, or a problem with tC (or both)?~~
![image](https://user-images.githubusercontent.com/8171759/62139134-69c3bd00-b2ae-11e9-841d-01f8b89978b9.png)
![image](https://user-images.githubusercontent.com/8171759/62139165-7b0cc980-b2ae-11e9-88f1-80b942651bf0.png)

![image](https://user-images.githubusercontent.com/8171759/62139201-87912200-b2ae-11e9-952d-0dce10561fe0.png)
![image](https://user-images.githubusercontent.com/8171759/62139225-937ce400-b2ae-11e9-99a1-5007fb1199d6.png)

**Comment by cckozie** [comment]
~~The English link "(See: [[rc://en/ta/man/translate/figs-metaphor]])" is not displayed.
The Hindi link "(देखें: [[rc://hi/ta/man/translate/figs-metaphor]] )" is displayed and additional text that is not in the Occurrence Note then follows in the smurf bar.~~

**Comment by cckozie** [comment]
2.0.0 (cd0f9f1) 
Looks good after separating out #6296 
Needs regression

**Comment by elsylambert** [comment]
Verified in 2.0.0 (bd37460) . As reported in #6296 , Hindi text in Occurrence Notes is repeated twice in Smurf bar.
Initial issue of English Text in Occurrence Notes for a Hindi Project has been resolved.
