### ISSUE TITLE
Feedback window has UI issue

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/translationCore#6285]
- [x] Add a scroll bar when the text gets too long

Include Application logs is not displayed.
![feedback window.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/34fff6f9-3ce8-4a0a-8437-77343fc4aa0b)

To reproduce the problem on the projects screen, Click on send feedback and add lines of text to feedback.

It looks like it needs to be made scroll-able.

**Comment by elsylambert** [comment]
Looks good in 2.0.0 (8f84296) . Scroll bar in feedback window resolved the display issue.

**Comment by cckozie** [comment]
Scrollbar solves the display problem in 2.0.0 (8f84296).
Noticed a problem with the width of the dropdown list. Wrote it up in #5631

**Comment by richmahn** [comment]
I believe you wrote it up in #6310
