### ISSUE TITLE
tC crashes when returning to Tools page

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6289]
2.0.0 (c940391)
Import an aligned usfm project. 
Open the project in tW
Click on the tool icon in the menu bar
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/88864eae-97d3-4850-972a-6c70785bcf5f)
[Mon Jul 29 2019.log 3.zip](https://github.com/unfoldingWord-dev/translationCore/files/3444952/Mon.Jul.29.2019.log.3.zip)

**Comment by mannycolon** [comment]
It looks like it's related to tools progress calculations.

**Comment by PhotoNomad0** [comment]
Verified fix in translationCore 2.0.0 (cd0f9f1)

**Comment by cckozie** [comment]
Not seeing the problem in 2.0.0 (cd0f9f1).

**Comment by elsylambert** [comment]
Not seeing the issue in 2.0.0 (bd37460).
