### ISSUE TITLE
Localization issues

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6292]
2.0.0 (c940391) 

1. Import [57-TIT.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/3447234/57-TIT.usfm.zip)
2. On the tN card change the GL to Hindi
3. Load the project in tN
4. Change the locale to Hindi
![Screen Shot 2019-07-30 at 9.04.29 AM.jpg](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/2ab355af-ad35-4f13-a49d-45f6ed83efe1)
5. Return to the Tools page
6. Load the project in wA
![Screen Shot 2019-07-30 at 9.05.59 AM.jpg](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/be0f6690-0164-4220-9e17-bf008bfe8fa0)
![Screen Shot 2019-07-30 at 9.05.20 AM.jpg](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/a99807cc-f84a-4a61-8a07-dd8a923d6952)

**Comment by PhotoNomad0** [comment]
@cckozie - the problem here is that these strings have not been translated to hi on crowdin (currently 67% complete).  I added some preliminary machine translations on crowdin.

**Comment by PhotoNomad0** [comment]
This should be working in translationCore 2.1.0 (0a80f05).

**Comment by cckozie** [comment]
Not seeing any of the noted problems in 2.1.0 (0a80f05)

**Comment by elsylambert** [comment]
Looks good in 2.1.0 (d0a11e7).

**Comment by cckozie** [comment]
@PhotoNomad0 Do you recall why this was moved from QA Done to Watch List?
