### ISSUE TITLE
Integrate Cypress with tC for integration testing

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord/translationCore#6293]
### User Story

As a [type of user], I want [some goal] so that [some reason].

### Features / Specifications

- [ ] 
- [ ] 

### Helpful Links
- [ ] https://www.cypress.io/blog/2019/09/26/testing-electron-js-applications-using-cypress-alpha-release/ 
- [ ] https://docs.cypress.io/faq/questions/using-cypress-faq.html#Can-I-test-my-Electron-app
- [ ] https://github.com/cypress-io/cypress/tree/develop/packages/desktop-gui/cypress/integration

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by benjore** [comment]
Probably could use a spike to figure out the best, most likely processes that should be added first.

**Comment by birchamp** [comment]
Duplicate with #6536
