### ISSUE TITLE
Update tC to use a newer version of Node and NPM (Same for devs development environment)

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord/translationCore#6294]
- Need to find a stable version. 
- Node 10.12 is the minimum for electronite-packager
- Electron@7.* uses Node v12.8.1

### User Story

As a [type of user], I want [some goal] so that [some reason].

### Features / Specifications

- [ ] Find one of the latest versions that is most stable version 
- [ ] 
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by benjore** [comment]
@mannycolon Can you add to this the versions of each you are proposing we update to?

**Comment by PhotoNomad0** [comment]
@mannycolon - looks like we need to update npm to at least v6.13.4 to fix a security bug: https://www.zdnet.com/article/npm-team-warns-of-new-binary-planting-bug/?ftag=TREc64629f&bhid=20703265992580265961698294056831

**Comment by mannycolon** [comment]
Lets go ahead and do that @PhotoNomad0

**Comment by da1nerd** [comment]
FYI concourse and now github actions are both using node 8.16.1 and npm 6.4.1. I would suggest keeping what we use in CI and what we use locally in sync. So updating one should mean we update the other as well.

**Comment by mannycolon** [comment]
I've found `Node v12.16.3` and `NPM v6.14.4` to be the most stable, supported by electronite-packager and compatible our current electron version.

**Comment by mannycolon** [comment]
Got approval from devs https://unfoldingword.zulipchat.com/#narrow/stream/212547-SOFTWARE.2FtC/topic/Node.20Version.20for.20tC.20Development

**Comment by mannycolon** [comment]
Verified on db7ab5c
