### ISSUE TITLE
Fix Lemma fallback

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#6295]
### User Story

As a [type of user], I want [some goal] so that [some reason].

### Features / Specifications

- [ ] Lemma fallback is currently broken, for this issue, fix it in the current project (ultimately we want lemma fallback for whole language, but that will need to be fixed in another issue)
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by cckozie** [comment]
2.0.0 (cd0f9f1) 
Lemma fallback is now working for words in the same project.
@elsylambert - Please test this one using a Hindi project. I don't recall if I've ever explained the lemma fallback thing to you or not, so let me know if you need more information:)

**Comment by elsylambert** [comment]
Verified in  2.0.0 (8f84296)  for Hindi Project. Lemma Fallback works fine across Projects.
Needs regression.
