### ISSUE TITLE
tA links and extraneous verbiage is showing in tN smurf bar when GL is Hindi

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6296]
2.0.0 (cd0f9f1) 
The Hindi links show up in the smurf bar. They should be suppressed as in the English. Also, the link is repeated and then followed by text that is not in the Occurrence Quote.

![smurf](https://user-images.githubusercontent.com/8171759/62159268-e5d1fb00-b2d6-11e9-9b41-76c128f81e9c.png)
![image](https://user-images.githubusercontent.com/8171759/62139165-7b0cc980-b2ae-11e9-88f1-80b942651bf0.png)

![image](https://user-images.githubusercontent.com/8171759/62139201-87912200-b2ae-11e9-952d-0dce10561fe0.png)
![image](https://user-images.githubusercontent.com/8171759/62139225-937ce400-b2ae-11e9-99a1-5007fb1199d6.png)

The English link "(See: [[rc://en/ta/man/translate/figs-metaphor]])" is not displayed.
The Hindi link "(देखें: [[rc://hi/ta/man/translate/figs-metaphor]] )" is displayed and additional text that is not in the Occurrence Note then follows in the smurf bar.

**Comment by elsylambert** [comment]
@richmahn Hindi text in Occurrence Notes is repeated twice in Smurf bar. The extra text after the tA link is the repetition of the Occurrence Notes.

**Comment by richmahn** [comment]
Verified in translationCore 2.0.0 (a49ad2d)

**Comment by richmahn** [comment]
@cckozie @elsylambert This also fixes Bible links in Hindi GL, such as in the Translation Note of Personification for Titus 2:12 (references Titus 2:11). Mousing over that scripture reference will now pop up the verse. Currently all references to TA and TW are stripped from the occurrence note in the smurf bar.

**Comment by PhotoNomad0** [comment]
Verified in translationCore 2.0.0 (8c6ecbb)

**Comment by elsylambert** [comment]
Looks good in 2.0.0 (52eff0d). Occurrence Notes are showing in Hindi for a Hindi Project.
