### ISSUE TITLE
Original language is showing as an option in the GL dropdown list for wA

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6297]
~~- [ ] Hard code wA tool GL dropdown to just show English (for now... with no way, software, or training on how to translate Lexicons, it will likely be a while before any other GL translates a Lexicon, though the possibility of finding an open-source lexicon remains. If that happens, we'd need to fix the dropdown so that it is dynamically derived.)~~
- [ ] Populate the GL list on the wA card with GLs that have Lexicons.
- [ ] If there is only one GL available for wA, auto-select it instead of displaying "Select Gateway Language"

2.0.0 (cd0f9f1) 
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/44843aff-6a0b-4280-b1a1-a184c49f602c)
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/df336c93-98de-436b-8724-932ac8768114)

**Comment by RoyalSix** [comment]
https://github.com/unfoldingWord-dev/translationCore/blob/develop/src/js/helpers/gatewayLanguageHelpers.js#L49

**Comment by PhotoNomad0** [comment]
Verified in translationCore 2.0.0 (b5c5fee)

**Comment by elsylambert** [comment]
Works as expected in 2.0.0 (b5c5fee). GL is selected as English for wA as currently we have Lexicon in only En.

**Comment by cckozie** [comment]
2.0.0 (2c07d1c)
English is auto-selected for wA if it has the only lexicon available.
I see that now the GLs for both tN and tW are also auto-selected if there is only one available.

**Comment by elsylambert** [comment]
Working fine in  2.0.0 (6da74a1). English is selected as GL for wA by default. Also for tN English is selected by default when no other resources are available.
