### ISSUE TITLE
Content error/mistake in Feedback window with Hindi as Locale

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/translationCore#6304]
When Locale is changed to Hindi, the Alert message has a wrong spelling: See the attached snapshot:
![image.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/20beef4f-f780-456b-9351-5f05c5980936)

@benjore Does Locale fixes goes to the content Team?

**Comment by benjore** [comment]
@elsylambert this is taken care of in CrowdIn. This would be the responsibility of the GL team, in this case Russ.

**Comment by elsylambert** [comment]
Forwarded the correction request to Russ. Will close this issue as soon as I get the confirmation.

**Comment by elsylambert** [comment]
2.0.0 (ac461b4). Correction has been made for Hindi locale.
