### ISSUE TITLE
"Last opened" does not change when the locale is changed

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/translationCore#6306]
- Change the locale to Hindi.
- The "Last opened" timer does not show in Hindi but English while rest of the fields are in Hindi(Selected Locale).
- Open a Project and come back to Project Page, the Last opened timer shows up in Hindi.
- Change the Locale to English.
-The "Last opened" timer does not show in English but still shows Hindi while rest of the fields are in English(Selected Locale).
![image.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/66147b6e-a7f8-4a8f-a518-b7d2c60402e0)

**Comment by benjore** [comment]
Same area of code as #4927

**Comment by richmahn** [comment]
This will be fixed when #4927 is merged in.

**Comment by richmahn** [comment]
Verified in build 5a65c0e

**Comment by cckozie** [comment]
Works in 2.0.0 (3727b58)

**Comment by elsylambert** [comment]
Verified in 2.0.0 (3727b58). Working fine.
