### ISSUE TITLE
Bug exporting project to USFM when canceling export

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord/translationCore#6309]
**Expected behavior:** 
Should be able to cancel a project export to USFM and be able to return to a working app.

**Actual behavior:** 
Screen is locked up when canceling project export to USFM. 

### Additional Information

On export canceled:

![1](https://user-images.githubusercontent.com/17072300/62264019-49018180-b3ec-11e9-8967-3409628bcc00.gif)

Works on export save:

![2](https://user-images.githubusercontent.com/17072300/62264153-d47b1280-b3ec-11e9-9263-d8f5ee574344.gif)

**Comment by mannycolon** [comment]
Verified on 13c98cd

**Comment by cckozie** [comment]
Works as expected after cancelling in 2.0.0 (13c98cd).

**Comment by elsylambert** [comment]
Verified in 2.0.0 (78cd497). Cancelling Export to USFM window works as expected.
