### ISSUE TITLE
% complete not working on tN tools card

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6314]
2.0.0 (8f84296) (This was broken fairly recently)
I opened this project in tN and completed all of the checks. When I returned to the Tools page, I see the % complete on the tN card still at 0%

Before tN checks: [en_ult_3jn_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/3457532/en_ult_3jn_book.zip)

After tN checks: [en_ult_3jn_book 2.zip](https://github.com/unfoldingWord-dev/translationCore/files/3457534/en_ult_3jn_book.2.zip)

![image](https://user-images.githubusercontent.com/8171759/62307149-afb48880-b448-11e9-9d77-f5df2eaa6461.png)
![image](https://user-images.githubusercontent.com/8171759/62307276-ebe7e900-b448-11e9-9160-d5ee197f3424.png)

**Comment by PhotoNomad0** [comment]
@cckozie - verified in translationCore 2.0.0 (03081b5).

Just a note that if you open a project that was opened in the previous broken build, the tN progress may not be updated until the first time you open tN.  After that it should work fine.

**Comment by cckozie** [comment]
2.0.0 (03081b5) 
Works as expected on newly checked projects, and after the first open on older ones.
Needs regression

**Comment by elsylambert** [comment]
Works fine in 2.0.0 (3256e93).
Needs regression
