### ISSUE TITLE
Selections are not saved when GL is switched in tN

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/translationCore#6327]
2.0.0 (78cd497).

Steps to replicate:
- Make few selections in tN with English as GL and save.
![image.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/1044d7cb-e538-460c-8fa0-8aeb9fc27e4d)
- Switch the GL to Hindi and Launch again.
- Note that the selections are missing(e.g Phm 1:10) and some selections are saved but the green check mark is missing.
![image](https://user-images.githubusercontent.com/51806180/62547476-427f6980-b833-11e9-9edf-3f7bf61dadd4.png)
The missing selection is due to the change in the Selection text. In English the selection is different than in Hindi.
![image](https://user-images.githubusercontent.com/51806180/62547065-976eb000-b832-11e9-88a2-12ed973b79a7.png)

- Switch back the GL to English.
![image](https://user-images.githubusercontent.com/51806180/62547773-c0dc0b80-b833-11e9-818e-033e5350d520.png)
Note that the Selection for Phm 1:10 is lost.

**Comment by PhotoNomad0** [comment]
@elsylambert @cckozie @benjore - in the latest build `translationCore 2.0.0 (61fec46)` the behavior is better in that the selections are not lost.  ~Unfortunately it does mark all verses as edited once the GL is changed~ (the verse edits were already in the project from 2/18/2019) :
![Screen Shot 2019-08-06 at 3 13 36 PM](https://user-images.githubusercontent.com/14238574/62570076-488a4000-b85d-11e9-9887-827c0a1361b0.png)
![Screen Shot 2019-08-06 at 3 14 16 PM](https://user-images.githubusercontent.com/14238574/62570088-5049e480-b85d-11e9-884e-a6c2fa6939d8.png)

**Comment by PhotoNomad0** [comment]
Notes about keeping GL checks separated by language for tN:
* save groupData in GL subfolders?  when loading checkData, we filter data loaded by GL?
* migrate existing projects
* ~need to load specific UGNT/UHB version needed for checks when bibles are loaded~ already implemented according to Manny
* ~do not default GL for tN to English.~ in different issue

**Comment by mannycolon** [comment]
@PhotoNomad0 

> need to load specific UGNT/UHB version needed for checks when bibles are loaded

Should be done with the tsv relation field in the project manifest


> do not default GL for tN to English.

Its part of #4102

**Comment by mannycolon** [comment]
@PhotoNomad0 
> need to load specific UGNT/UHB version needed for checks when bibles are loaded

I just verified that this is already happening

**Comment by PhotoNomad0** [comment]
@benjore @elsylambert @cckozie - It seems that now:
- the above issue fixed about not displaying all the selections on GL change
- @mannycolon has made a fix to persist the GL selections
- @mannycolon has verified we are loading the correct version of the OrigLang for the tsv

I don't think we should try to separate checks, since there is not a scenario that we would loose data, just may not be displayed in some GLs.

**Comment by elsylambert** [comment]
Verified in 2.0.0 (92b46cf). Selections are not lost when GLs are switched and also the Green check mark is displayed.
Needs regression.

**Comment by PhotoNomad0** [comment]
It was decided to not save checks separately based on GL, so no more dev work needed on this.

**Comment by cckozie** [comment]
2.0.0 (3fe9fe0) 
There are 2 issues that need to be discussed:
ISSUE 1. After a GL (GL1) is selected, tC will ignore checks in a different GL (GL2) that do not exist in GL1.
Checks in English include Abstract Nouns (top category in screenshot)
![image](https://user-images.githubusercontent.com/8171759/62641612-95c3eb80-b909-11e9-9a6f-ef499351e624.png)

After switching to Hindi, for which I have deleted the Abstract Nouns check, when I go back to English as the GL, Abstract Nouns is no longer displayed as a category.
![image](https://user-images.githubusercontent.com/8171759/62641699-d28fe280-b909-11e9-968d-91eeea2e1a2c.png)

ISSUE2: (I think this is probably as expect/desired)
If a check is made in GL1 and the user switches to GL2 that has a content problem for that check, the proper alert is displayed, but the menu tile shows the checkmark and selected text for GL1.
![image](https://user-images.githubusercontent.com/8171759/62640560-71670f80-b907-11e9-99c5-4f213368fc76.png)

**Comment by cckozie** [comment]
@benjore agrees with ISSUE 1 above.
Import a project that has more defined English tN checks than defined Hindi tN checks
Open the project in English and complete a check that is not defined for Hindi
Return to the tools page, choose Hindi as the GL for tN, and load the project in tN
Return to the tools page, choose English as the GL for tN, and load the project in tN
Note that the completed check is no longer available in the menu

**Comment by cckozie** [comment]
Turns out the missing check problem is really the fact that the sub-category gets unchecked on the tools card. When checked again, the check does show up in English GL.
Wrote up #6347 to deal with the critical error issue.
