### ISSUE TITLE
Import Project with Overwrite fails when tC is running

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/translationCore#6328]
2.0.0 (78cd497) . Tested on windows machine.
Follow steps to import a project locally:
- Downloaded a project from Door43 fully aligned(Import Online Project). https://git.door43.org/lrsallee/en_ult_heb_book
- Exported the Project to USFM without alignments.
- Imported the Project locally with same translation ID, so did an overwrite.
- Cannot Open the project, gives error that "Cannot convert undefined or null to object "
- I checked in tC>Projects Folder> This projects folder the .usfm file was missing.
During the process of export to USFM and Import back the same project locally, losing the.usfm file from Projects folder.
Here is the log file, Please see after 12:40 PM:
[Tue Aug 06 2019.zip](https://github.com/unfoldingWord-dev/translationCore/files/3473346/Tue.Aug.06.2019.zip)
Here is a screen capture:
[Error while loading the project.zip](https://github.com/unfoldingWord-dev/translationCore/files/3473350/Error.while.loading.the.project.zip)

If tC is closed after the USFM export and restarted before the re-import, the project opens fine.

**Comment by cckozie** [comment]
Is this possibly a race condition? I am not seeing the problem with the specified project on either my Mac or Windows machine.

**Comment by PhotoNomad0** [comment]
Hmm...not seeing the problem on my old Windows 10, 64 bit machine running version translationCore 2.0.0 (92b46cf).  Also it worked on old WIndows laptop with Hard Drive - very slow.

**Comment by PhotoNomad0** [comment]
Don't see anything in the log that hints why overwrite may have failed.

**Comment by PhotoNomad0** [comment]
@elsylambert - the screen capture of the error looks like a missing locale string.  What was your locale setting?

**Comment by PhotoNomad0** [comment]
@elsylambert - can you try to recreate this error with latest build and capture a video of the process?

**Comment by elsylambert** [comment]
Tested in 2.0.0 (92b46cf). 
Please see the screen capture:
[2.0.0(92b46cf)reimport.zip](https://github.com/unfoldingWord-dev/translationCore/files/3477580/2.0.0.92b46cf.reimport.zip)

**Comment by PhotoNomad0** [comment]
@elsylambert - I can recreate the problem - if I click more than once on the “Overwrite Project” button on the alert.  Glad your video had sound so I could hear the second click!

**Comment by PhotoNomad0** [comment]
Working on fix to prevent this since this is always a temptation to click again if you don't see something happening.

**Comment by mannycolon** [comment]
Verified on 8b118f2

**Comment by cckozie** [comment]
2.0.0 (3256e93) 
Unable to cause a failure even by clicking on the Overwrite button multiple times.

**Comment by elsylambert** [comment]
Not seeing any issues with Import overwrite in 2.0.0 (3256e93).
