### ISSUE TITLE
When the locale is changed when on the tools page, the localized text on the tool cards does not change until the user changes something on the card 

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6335]
2.0.0 (3fe9fe0) 
Go to the Tools page
Change the locale
Notice that the text in the instructions pane is updated to the new locale, but nothing on any of the tool cards changes.
Uncheck one of the checkboxes or change the GL on one of the tools and notice that the tool cards text is now displayed in the correct locale.

**Comment by elsylambert** [comment]
This is similar to #6306

**Comment by benjore** [comment]
May be fixed with #5937.

**Comment by elsylambert** [comment]
Not seeing this issue in 2.0.0 (aa663e3)
