### ISSUE TITLE
Critical error screen after changing GL's in tN, then opening a category

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6347]
2.0.0 (b5c5fee)
Delete the figs-abstractnouns.json under grammar in the Hind translationNotes folder
Select a Titus project 
Set the tN GL to English and launch it
Make a selection in the Abstract nouns group
Return to the Tools page
Select Hindi as the GL for tN and launch it
Return to the Tools page
Select English as the GL for tN
Click on the "V" to open the Grammar category
The Critical error screen is displayed.

**Comment by benjore** [comment]
Need to investigate if this is an real-life issue (since this list is created dynamically). Can it be tested on a category that is not native in the GL.

**Comment by elsylambert** [comment]
Not seeing this issue in 2.0.0 (ca6c273)

**Comment by cckozie** [comment]
Was informed by devs that this was not a legitimate test. I was unable to find another way to test it since it appears Hindi and English are the only GL's that have updated tN's and they have identical checks. Even though the test may not be legitimate, the problem no longer exists in 2.0.0 (ca6c273).
