### ISSUE TITLE
Correctly handle tA links

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#6351]
This is a follow-up on #6296. Because the way we were detecting links broke on non-English GL's, we chose just not displaying the links as a temporary "fix" to that issue.
See example problems in #6621

## User story

As a speaker of any GL, I want the links to tA articles to work in my GL so that I can learn better translation practices. 

## Specs

- [x] Show all tA links in the Smurf bar as hyperlinks with the Title of the tA article as the clickable text. 
  - [x] When clicked, open the article in the expanded tHelps Pane. This should be the same behavior as clicking on a link in the tHelps pane.
 e.g. Load a Titus project in tN. Navigate to the Metaphor group. Scroll to the bottom of the tHelps pane and click on the "Biblical Imagery - Common Patterns." link.
![image](https://user-images.githubusercontent.com/8171759/77545856-0d369300-6e79-11ea-836a-7d17834e8c98.png)
  - [x] Make this feature work with any GL
  - [x] Avoid all duplication of text (as shown in #6296)

**Comment by da1nerd** [comment]
Two link formats need to be supported.

* RC links `[Metaphor](rc://en/ta/man/translate/figs-metaphor)`
* Markdown links `[Titus 1:13](../01/13/je3r)`

**Comment by da1nerd** [comment]
It appears that the packages involved are [checking-tool-wrapper](https://github.com/unfoldingWord/checking-tool-wrapper), [tc-source-content-updater](https://github.com/unfoldingWord/tc-source-content-updater) and [tsv-groupdata-parser](https://github.com/unfoldingWord/tsv-groupdata-parser). I'm not certain which one of these has the main portion of code, but I would get the tsv-groupdata-parser. Just found these when looking at https://github.com/unfoldingWord/translationCore/pull/6354/files

**Comment by da1nerd** [comment]
Based on a conversation with Rich, it sounds like there are two issues that need to be resolved.
* Displaying the links properly
* Getting links to play nicely with the other UI components (e.g. opening up the resource when clicking a link).

**Comment by da1nerd** [comment]
So far I have made links visible again, added a click handler that passes the event up.

@benjore can you confirm how you want the article displayed? Do you want the sidebar to open  and display the article or do you want the dialog to pop up with the article?

If we display the article in the sidebar how do you want to go back to viewing the original article? On that note, I've only seen one link in each of the notes so far, and those links are to the article that is already available in the side menu. Is there an example of multiple links to different articles? If not this will simply duplicate the functionality of the read more button.

**Comment by da1nerd** [comment]
in order to display the correct title we'll need to add a callback to the tc-ui-toolkit. Something like `onRenderRCLink`. This should give the current link and give the developer an opportunity to rewrite either the title or the href

**Comment by da1nerd** [comment]
the code part here is basically done. I just need to figure out what version to tag them as and then publish the npm modules.

**Comment by PhotoNomad0** [comment]
Verified in translationCore 2.2.0 (d5cfaa9)

**Comment by cckozie** [comment]
Copied from comments on #6621 
2.2.0 (02533e8)
The examples noted on #6621 (A,B, and C) are now displayed as links, but there are still some issues as noted below. 
@birchamp - Please weigh in my color suggestion in the third image below, and on Problem B.

Problem A:
The link text color needs to be a color that has more contrast to the blue background. As is it is barely visible, and virtually invisible after the link has been clicked. (See suggested)
Before clicking:
![image](https://user-images.githubusercontent.com/8171759/79891492-a8fae680-83c6-11ea-8fd3-10efdb67d940.png)
After clicking:
![image](https://user-images.githubusercontent.com/8171759/79891561-c465f180-83c6-11ea-8c1f-2b8d88b4c207.png)
Suggest a color something like this (#3FB7FA):
![image](https://user-images.githubusercontent.com/8171759/79892396-2541f980-83c8-11ea-9621-0c5f10a3052d.png)

Problem B:
Should we be showing the "UST" in this one (It is in the note):
![image](https://user-images.githubusercontent.com/8171759/79892611-6cc88580-83c8-11ea-8cfe-a1d645ce0ccf.png)

Problem C:
I don't think we should allow a line break after the "(See". This happens a lot.)
![image](https://user-images.githubusercontent.com/8171759/79894489-2294d380-83cb-11ea-8377-f51e4cc53e36.png)

Problem D:
This link is not properly displayed
![image](https://user-images.githubusercontent.com/8171759/79894871-b2d31880-83cb-11ea-9f56-7731dad5b52e.png)

**Comment by birchamp** [comment]
@cckozie @neutrinog yes the links should be #3FB7FA and stay that way even after they are clicked.

**Comment by da1nerd** [comment]
@cckozie should `UST` be in the note in the first place? Should the actual note content be updated?

Also, I'm not certain if there is a way to display the "See also" all on one line for all languages. I could however prevent the link text from breaking across a line.

**Comment by da1nerd** [comment]
@cckozie where is that example with the broken link? The book is not shown in the screenshot.

**Comment by da1nerd** [comment]
I opened a [PR](https://github.com/unfoldingWord/tc-ui-toolkit/pull/258) that so far fixes the link colors and prevents the link words from wrapping.

![Peek 2020-04-22 16-39](https://user-images.githubusercontent.com/166412/79968561-7af6ce80-84ba-11ea-8bb9-1b97bafa985c.gif)

**Comment by birchamp** [comment]
"UST" should continue to be displayed as it is in the content.

**Comment by cckozie** [comment]
@neutrinog I assume you're referring to Problem D as the broken link. All of the screenshots are from a Titus project. (sorry I didn't include that)

**Comment by da1nerd** [comment]
@cckozie hm... I don't have 1:6 under Double negatives.

![image](https://user-images.githubusercontent.com/166412/80050507-fb134780-853f-11ea-9494-0ce6ead8cd39.png)

**Comment by cckozie** [comment]
@neutrinog - Do you have the latest resources? 
![image](https://user-images.githubusercontent.com/8171759/80052504-6decd600-84e0-11ea-873c-05f76953ff46.png)

**Comment by da1nerd** [comment]
I get errors when trying to download the resources.
for example:
![image](https://user-images.githubusercontent.com/166412/80052709-8cd18380-8545-11ea-9a35-3b2826d847e7.png)

I'm running the latest code in `develop`.

**Comment by cckozie** [comment]
Hmmm... Yes, I am seeing errors after "forcing" a download.
Latest resources are bundled with the builds. I'm using the one at https://github.com/unfoldingWord/translationCore/actions/runs/84165663

**Comment by da1nerd** [comment]
ok. I can just manually run the script then. However, the above might need to be opened as a bug.

**Comment by da1nerd** [comment]
@cckozie I got the latest resources. Turns out the last part of the link is invalid. It should be `figs-doublenegatives` not `doublenegatives`. So it's not able to locate the article and grab the title. It's an easy fix. Just update the translationNotes for that particular verse and note.

**Comment by PhotoNomad0** [comment]
> I get errors when trying to download the resources.
> for example:
> ![image](https://user-images.githubusercontent.com/166412/80052709-8cd18380-8545-11ea-9a35-3b2826d847e7.png)
> 
> I'm running the latest code in `develop`.

@neutrinog - Yes created an issue for that: https://github.com/unfoldingword/translationcore/issues/6864.  Looks like a webpack configuration problem.  SHould be fixed soon.

**Comment by PhotoNomad0** [comment]
@neutrinog - what is the status of this?  I see a PR attached https://github.com/unfoldingWord/tc-ui-toolkit/pull/258 that has a merge conflict.

**Comment by da1nerd** [comment]
@PhotoNomad0 it's ready.

**Comment by BincyJ** [comment]
@PhotoNomad0 is there any action required by @neutrinog here?

**Comment by PhotoNomad0** [comment]
Problems A & C are fixed in translationCore 2.2.0 (17ae343)

It looks like B & D are content problems.

**Comment by cckozie** [comment]
2.2.0 (64bf0a5) 
When the user has the tHelps pane collapsed (not visible) and then clicks on one of the links in the smurf bar, in addition to the expanded tHelps pane being displayed, the regular tHelps pane is also opened.

Before clicking the link:
![Screen Shot 2020-05-04 at 10 27 21 AM](https://user-images.githubusercontent.com/8171759/80983222-f6794980-8df1-11ea-9cbf-739c7a75bb6e.jpg)

After clicking the link:
![Screen Shot 2020-05-04 at 10 27 33 AM](https://user-images.githubusercontent.com/8171759/80983269-0133de80-8df2-11ea-8291-57b457fff728.jpg)

After closing the expanded tHelps pane:
![Screen Shot 2020-05-04 at 10 29 04 AM](https://user-images.githubusercontent.com/8171759/80983426-27f21500-8df2-11ea-9c41-4307cf31b3d1.jpg)

Issues A and C have been fixed.
Issues B and D appear to be content problems. Content team was notified.

(Also wrote up #6894 while testing this issue)

**Comment by da1nerd** [comment]
@cckozie see the notes on this PR why the context pane opens. https://github.com/unfoldingWord/checking-tool-wrapper/pull/100#issue-399437817. It could be updated, but would require some more drastic refactoring. I've been really good lately and refraining from refactoring all the things ;)

**Comment by cckozie** [comment]
@birchamp - Need you input on this ^^^^

**Comment by cckozie** [comment]
@birchamp directed to write up the opening of the tHelps pane to a new issue. It is now on #6897

**Comment by cckozie** [comment]
The links work properly in 2.2.0 (64bf0a5)

**Comment by elsylambert** [comment]
tA links look good in 2.2.0 (dd79140).
