### ISSUE TITLE
Problems with UGNT and tN versioning

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6359]
2.0.0 (aca7a85)
ISSUE A:
When attempting to load a project in tN that requires an older version of the UGNT, the user is prompted to download it. When the download is complete and the user clicks on the the tN Launch button, the alert indicating that a different version of the UGNT is required again. The user needs to return to the Projects page and then go back to the Tools page in order to get the project to load in tN.

ISSUE B: Per the conversation documented in #6360, this issue is now considered to be expected behavior.
~~tC does not allow a different version of the UGNT to be used for different GLs for the same project. Whatever version of the UGNT was used for the first GL used with the project will be used for all GLs for that project.~~
~~1. Edit the manifest.json file for a project so that it requires and older version of the UGNT (v0.7)~~
~~2. Attempt to launch that project in tN~~
~~3. When alerted that a different version of the UGNT is needed, click the Download button~~
~~4. After the download completes, go back to the Projects page (this step is because of ISSUE A above)~~
~~5. Go the Tools page and launch the project in tN~~
~~6. Return to the tools page~~
~~7. Change the GL for tN and Launch the project~~
~~8. View the manifest for the project and note that the UGNT version again indicates v0.8~~

**Comment by elsylambert** [comment]
Adding my findings in 2.0.0 (94d3a74). Issue A:  
 I followed through these steps:
1. edit hi tN manifest.json to change dependency to ugnt v0.7
2. in tCore, select a project that we have alignments in hi (I used phm)
3. change tN GL to hi which will update the project manifest
4. click launch and get prompt to download.
5. click to download
6. go back to the Projects page
7. Go the Tools page and launch the project in tN
After I launch tN, again it displays the message that I have an older version of UGNT and needs download and I click on download, it downloads again and when I launch tN, it gives the same message. It is going in loops.
I changed the GL to En and launched so now able to open tN

**Comment by mannycolon** [comment]
Verified on cb75770

**Comment by cckozie** [comment]
2.0.0 (3727b58)
The problems described in ISSUE A and in Elsy's comment have been fixed.
Needs regression

**Comment by elsylambert** [comment]
Not seeing the issue in versioning of UGNT and tN in 2.0.0 (aa663e3)
