### ISSUE TITLE
Older versions of the UGNT are deleted when tC is started

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6360]
2.0.0 (aca7a85) 
1. Edit the manifest.json file for a project so that it requires and older version of the UGNT (v0.7)
2. Attempt to launch that project in tN
3. When alerted that a different version of the UGNT is needed, click the Download button
4. After the download completes, go back to the Projects page (this step is needed because of a bug written up in #6359)
5. Go the Tools page and launch the project in tN
6. Return to the Project page
7. End tC
8. Restart tC
9. Note that UGNT v0.7 is no longer on the file system

**Comment by PhotoNomad0** [comment]
@cckozie - I talked with @mannycolon and want to suggest a better test procedure than editing the project manifest.json.

1. edit hi tN manifest.json to change dependency to ugnt v0.7
1. in tCore, select a project that we have alignments in hi (I used phm)
1. change tN GL to hi which will update the project manifest
1. click launch and get prompt to download.
1. click to download
1. go back to the Projects page
1. Go the Tools page and launch the project in tN
1. End tC
1. Restart tC
1. should see that UGNT v0.7 is still in resources

don't forget to restore the hi tn manifest.json

**Comment by cckozie** [comment]
The old version of the UGNT is not deleted when the above steps are followed.

@PhotoNomad0 @mannycolon @benjore - So is there an assumption that the same version of the original language will be used for all corresponding translation notes for a specific GL?
If so, is that a valid assumption.?

**Comment by benjore** [comment]
~~We need to be able to handle the situation where the tN in a GL are pegged to one version of the UGNT for one book and another version of the UGNT for another book.~~

The current structure of the tN manifest only supports the granularity of one version of the UGNT per GL. Unless/until the manifest changes, tC only needs to support on version of the UGNT per GL.

**Comment by mannycolon** [comment]
What @benjore said is whats happening now

**Comment by mannycolon** [comment]
@cckozie 

> So is there an assumption that the same version of the original language will be used for all corresponding translation notes for a specific GL?

Yes

**Comment by cckozie** [comment]
2.0.0 (8a6a8c5) - The older ugnt is not deleted when McLeans steps above are followed.

**Comment by elsylambert** [comment]
2.0.0 (94d3a74) - The older version of UGNT is not deleted from the resources.
