### ISSUE TITLE
GL is not available for selection in tW.

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/translationCore#6363]
2.0.0 (a49ad2d) 
For the projects which were having En/Hi as GL, now showing as None Available for tW.
![image](https://user-images.githubusercontent.com/51806180/62869999-e3b06900-bce6-11e9-8e3d-56dec3cd0962.png)

**Comment by PhotoNomad0** [comment]
@elsylambert - this is due to broken bundled resources.  It should be fixed in the PR https://github.com/unfoldingWord-dev/translationCore/pull/6365.  Will verify when latest build comes through.

**Comment by PhotoNomad0** [comment]
Verified in translationCore 2.0.0 (8c6ecbb)

**Comment by richmahn** [comment]
Fixed in the #6296 build

**Comment by richmahn** [comment]
Verified in Build (8c6ecbb)

**Comment by elsylambert** [comment]
Not seeing the issue in  2.0.0 (52eff0d)

**Comment by cckozie** [comment]
Works correctly in 2.0.0 (a4d181d)
