### ISSUE TITLE
English is showing for a translationWord check on the menu when only Hindi text should be rendered. 

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord/translationCore#6375]
#  Story Explanation
### User Story

As a tC user, I want only Hindi text to show on the menu when I select Hindi as a GL so that I can consistently work on a Hindi project without being confused why English text is found in the check.

Project used: [hi_aaa_tit_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/3498671/hi_aaa_tit_book.zip)

### Features / Specifications

- [ ]
- [ ]
- [ ]

# Screenshots
![Screen Shot 2019-08-13 at 4.00.07 PM.png](https://images.zenhubusercontent.com/576988c1bf93871ccd9cf7e4/99f89e87-7bdf-4e0d-bffc-6e084571f79e)

**Comment by cckozie** [comment]
Still a problem in 2.0.0 (ca6c273)

**Comment by cckozie** [comment]
This is a content problem. I notified Russ Perry.
![image](https://user-images.githubusercontent.com/8171759/78046521-dfe85a00-733c-11ea-9e49-f00932c66bfb.png)
