### ISSUE TITLE
Wrong Selection text and Green check displayed in tN for a verse that has two checks.

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/translationCore#6389]
2.0.0 (cb75770).
Here is the project:
[en_new_1ti_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/3516616/en_new_1ti_book.zip)

Steps to replicate:
1. In tN. make selection for a verse that has two checks. For e.g. In this project,  1ti 6:13 there are two checks in tN under category "Assumed Knowledge..."
2. Make selection for both the verses and save.
3. Selections seems fine on the left side menu bar.
4. Re-open tN and see the Same verse selections. Note that the  left side menu bar has display issue as in the snapshot below:
![image](https://user-images.githubusercontent.com/51806180/63279401-e8d95f00-c276-11e9-8ab1-25f8332cdf5e.png)

Another Case when there are only one selection out of the two verses:
In Phm project, Phm 1:1 there are two checks in tN, seems that the one with the green check is not completed rather one with no checkmark has selections.
This is under the category "Exclusive and Inclusive we". Another Category has the same issue"How to translate Names" in Phm 1:2".
![image](https://user-images.githubusercontent.com/51806180/63279566-36ee6280-c277-11e9-8835-b93ae0b49929.png)

**Comment by PhotoNomad0** [comment]
@elsylambert - In the first case, I only see this error when I exit tN and then open wA and then go back to tN.  Just relaunching tN does not cause this.  And going from tN to tW to tN does not cause it.  It also looks like it is a transient error since if I open a different project and return, the problem clears.

**Comment by PhotoNomad0** [comment]
@elsylambert - In the second case, if I go into WA and back to tN, I see both items have checkmarks even though only one has selections.
![Screen Shot 2019-08-20 at 9 35 12 AM](https://user-images.githubusercontent.com/14238574/63351780-e2f28500-c32d-11e9-8f78-d9dd6081e775.png)

**Comment by cckozie** [comment]
@mannycolon 
I have now seen the same or similar behavior in tW.
Screenshot after completing both checks for the same verse:
![image](https://user-images.githubusercontent.com/8171759/63554207-754b8200-c502-11e9-9cdd-cf338600c98b.png)

Screenshot after loading the project in wA and then returning to tW:
![image](https://user-images.githubusercontent.com/8171759/63554234-8a281580-c502-11e9-8916-06c68538d5a2.png)

**Comment by PhotoNomad0** [comment]
@mannycolon - I found the cause for the leakage of selections.  My fault.  To fix need to change in GroupsDataActions:
```
export const findGroupDataItem = (contextId, groupData) => {
  let index = -1;
  for (let i = 0, l = groupData.length; i < l; i++) {
    const grpContextId = groupData[i].contextId;
    if ((grpContextId.quote === contextId.quote) &&
        isEqual(grpContextId.reference, contextId.reference) &&
        (grpContextId.occurrence === contextId.occurrence)) {
      index = i;
      break;
    }
  }
  return index;
};
```

I have a PR that will be ready soon and can fix it there if you want.

**Comment by PhotoNomad0** [comment]
Hmm...looks like it is not the only problem.

**Comment by elsylambert** [comment]
Tested on 2.0.0 (ca6c273).
Made selection for a verse 2Timothy 1:5, but the green check mark was not displayed.
Later found that 2Timothy 1:5 had content error in a different category.
![image](https://user-images.githubusercontent.com/51806180/64547751-4d7a5d80-d2fb-11e9-8011-58c671cae63c.png)

**Comment by cckozie** [comment]
Not seeing any of the documented problems in 2.1.0 (d8f36fe)
