### ISSUE TITLE
Repo already exists error when uploading to Door43 

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6408]
2.0.0 (d443ae8) 

![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/c33dc7d3-deb9-42a7-8fd7-f4b7fce85f90)

Import search screen shows no repos for the user
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/17164ce6-ccbb-45e4-8d9c-87724bfa6c45)

Door43 shows no repos for user
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/49c240a6-2582-4e2f-af11-6c8004a84458)

I'm guessing that the Door43 account had gotten deleted since when I logged out and tried to log in again I received the invalid username message.
I think the original error message is wrong. Instead of indicating that the repo already exists, it should indicate an invalid username.

**Comment by elsylambert** [comment]
@cckozie Do you still have this project with you?

**Comment by cckozie** [comment]
@elsylambert - I'm closing this issue since there really is no way to test it now that the username and associated repos no longer exists on Door43. I don't think it's something we need to worry about in the future.
