### ISSUE TITLE
Progress on Menu Items not updating after doing a check

### ISSUE THREAD

**Issue by RoyalSix** [unfoldingWord/translationCore#641]

**Comment by mannycolon** [comment]
@RoyalSix i never saw a PR for this?? im wondering if this made it to develop?

**Comment by RoyalSix** [comment]
Its was https://github.com/unfoldingWord-dev/translationCore/pull/653

**Comment by mannycolon** [comment]
@RoyalSix ok cool. just making sure. since i never saw it.
