### ISSUE TITLE
Disable Discontiguous Merge 

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#6413]
- [ ] This feature needs to be limited. Until the rules are able to be fully defined, this feature should be commented out. 
- [ ] ~~Continue correctly displaying imported discontiguous merges, (just don't enable adding new ones)~~

**Comment by jag3773** [comment]
It was determined that disabling this would affect teams using it (including English content team) so it would be better to wait until we can refine it's usage instead of disabling
