### ISSUE TITLE
Need indicator of processing after the Verses Missing screen when selecting an existing project

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6420]
2.0.0 (3727b58)
1. Import a project that has missing verses.
2. Note that after clicking Continue on the missing verses page, the Preparing project data alert is displayed.
3. Return to the projects page
4. Select a different project
5. Return to the projects page
6. Select the project imported in 1. above
7. Note that after clicking Continue on the missing verses page, no alert indicating processing is displayed and it appears locked until the Tools page is displayed.

**Comment by cckozie** [comment]
2.0.0 (e8a2e7c) - This has been fixed.

**Comment by elsylambert** [comment]
Seeing this issue happening in 2.0.0 (cac1580). The screen hung for 30 seconds before it opened the tools page.  The Project has a lot of missing verses.
The amount of time the screen is hung is directly proportional to the number of missing verses.

**Comment by cckozie** [comment]
2.0.0 (cac1580)
When a project with missing verses is imported, there really isn't a problem because the Preparing project data, Project named, etc. alerts are displayed.
But when selecting a previously imported project that has missing verses, no alerts are displayed between the time the user clicks Continue on the Missing Verses page and when the Tools page is displayed.

**Comment by cckozie** [comment]
Works in 2.1.0 (b775824)
