### ISSUE TITLE
tHelps pane is empty in tN and tW

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6421]
2.0.0 (ca6c273) 
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/77911d74-93c5-4074-aa50-45694be6193b)

**Comment by elsylambert** [comment]
Found that the help pane shows up when the Category is selected on the Menu.
-When tC is opened, Help pane is blank.
- Click on the Second category on the Left Menu. Help Pane shows up.
- Go back to the first Category, You can see the Article which was not showing earlier.
- Restart tC. Help pane is Blank again.
Here is a Video snapshot:
[Help pane.zip](https://github.com/unfoldingWord-dev/translationCore/files/3591565/Help.pane.zip)

**Comment by cckozie** [comment]
Looks good in 2.0.0 (4b3ebee)

**Comment by elsylambert** [comment]
Working fine in 2.0.0 (4b3ebee)
