### ISSUE TITLE
Alert Message content showing up HTML Tags/codes

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/translationCore#6423]
2.0.0 (ca6c273).
Some of the Alert messages are showing Tags/codes in the Message content:
- Alert message for content errors.
![image.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/2b3777d1-902a-44cb-81b8-2c3cd3ff7b9a).

- Alert message for Creating new repository.
![image.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/75b953b1-63f0-423d-9d09-935c072b5799)
- Alert message for renaming a Project after import.
![image](https://user-images.githubusercontent.com/51806180/64548569-e067c780-d2fc-11e9-80d5-d0015141069f.png)
- Home Page after user logs in.
![image](https://user-images.githubusercontent.com/51806180/64795398-06cf7200-d54c-11e9-861e-a3a0283f8293.png)

**Comment by PhotoNomad0** [comment]
Verified in translationCore 2.0.0 (e8a2e7c)

**Comment by elsylambert** [comment]
Looks good in 2.0.0 (e8a2e7c).

**Comment by cckozie** [comment]
Not seeing problems in 2.0.0 (e8a2e7c)
