### ISSUE TITLE
Checkmark persists on checks in tN after edits have invalidated the check

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6424]
2.0.0 (ca6c273) 
This problem was previously written up and fixed on #6001, but it is broken again. It appears to only be a problem in tN.
[57-TIT.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/3591552/57-TIT.usfm.zip)
1. Import this fully aligned Titus project
2. Load it in tN
3. Make the suggest selection in 2:2 under Abstract Nouns
![image](https://user-images.githubusercontent.com/8171759/64548537-6cc1bc80-d2f4-11e9-976e-9ec354998ab3.png)
4. Load the project in wA
5. Edit verse 2:2 to change the text "sound in faith" to "sound with faith"
6. Load the project in tN
7. Note that the checkmark has persisted on the check but the highlighting has been reset.
![image](https://user-images.githubusercontent.com/8171759/64548786-f6718a00-d2f4-11e9-9726-4731f33d1715.png)

**Comment by cckozie** [comment]
May be related to/fixed by #6433

**Comment by mannycolon** [comment]
Verified on 399c030

**Comment by elsylambert** [comment]
Looks good in 2.0.0 (399c030). Check mark has been removed and a broken link is displayed when the selections are invalidated after the edit in another tool (wA)

**Comment by cckozie** [comment]
Works correctly in 2.0.0 (399c030). Needs regression since this has now been fixed twice.

**Comment by elsylambert** [comment]
Works fine in  2.1.0 (7adcd44). Broken link is displayed in tN and checkmark removed when a check is invalidated after an edit in another tool.
