### ISSUE TITLE
wA "remembers" menu verse icons from previous project

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6433]
2.0.0 (4b3ebee) 
[57-TIT.usfm 2.zip](https://github.com/unfoldingWord-dev/translationCore/files/3607458/57-TIT.usfm.2.zip)

Import this usfm2 project (no alignments)
Load it in wA
Set the alignment complete switch on 1:1
Make an edit in 1:2
Import the usfm2 file again giving it a different translation id
Load it in wA
Note that the checkmark appears on 1:1, and the edit icon appears on 1:2

wA "remembers" the menu icons for all projects until tC is stopped and restarted.

**Comment by PhotoNomad0** [comment]
Oops - big goof here.

**Comment by PhotoNomad0** [comment]
Verified in translationCore 2.0.0 (a282c74)

**Comment by elsylambert** [comment]
Working fine in 2.0.0 (bbd777c).
