### ISSUE TITLE
Warning: A critical error has occurred! page is displayed after import of tS project

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6435]
2.0.0 (4b3ebee) 
This project imported without errors in 0.8.1
[lno_tit_reg.zip](https://github.com/unfoldingWord-dev/translationCore/files/3616810/lno_tit_reg.zip)
[ino_tit_text_reg.tstudio.zip](https://github.com/unfoldingWord/translationCore/files/4616246/ino_tit_text_reg.tstudio.zip)

**Comment by birchamp** [comment]
@cckozie @elsylambert  Can you retest this now that #6790 has passed?

**Comment by elsylambert** [comment]
Retested in 2.2.0 (6a53472). Still getting the critical screen error after the tS project is imported.
<img width="1792" alt="Screen Shot 2020-05-11 at 10 01 49 AM" src="https://user-images.githubusercontent.com/51806180/81570493-aa3c8500-936e-11ea-9e6d-de67ed92a57e.png">

**Comment by PhotoNomad0** [comment]
Fixed in translationCore 2.2.0 (690092a)

**Comment by cckozie** [comment]
2.2.0 (690092a) 
The critical error screen is no longer displayed after selecting the attached project. However the user is sent to the Projects page rather than the tools page after clicking OK on the project named alert. (Should be fixed by #6908)
Attempting to actually import (rather than just select) the project causes an import failure that should be fixed by #6899

**Comment by elsylambert** [comment]
Not seeing the critical error in tS project in 2.2.0 (690092a).
