### ISSUE TITLE
Existing checks in tN do not show as completed after import from Door43

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6438]
2.0.0 (a282c74) 
https://git.door43.org/TC_SAVE/en_ult_3jn_book
This project was full aligned and all checks completed in tW and tN in 2.0.
When it is downloaded now, wA and tW tools cards show 100%, but tN shows 0%.
When opened in tN, the checks do show the highlighted selections, however, most do not show the check mark in the menu.

The tN checks do show properly when imported into 2.0.0 (ade72a0) (the 2.0 released build).
However, in that build the tN card shows 0% until tN is loaded and then returned to the Tools page. This is written up in #6439.

**Comment by mannycolon** [comment]
Verified on 28ba6a8

**Comment by cckozie** [comment]
All looks good, including the % on the tools card, in 2.0.0 (1654f9b) 
Needs regression

**Comment by elsylambert** [comment]
Looks good in 2.0.0 (9ef4802).
tW and wA shows 100%, tN shows 0% but after selecting the GL option it shows 100%. Is this the expected behaviour that tool card % would show up after GL is selected?@mannycolon @cckozie

**Comment by cckozie** [comment]
@elsylambert - Yes, that is the expected behavior. In tW, all of the checks are based on the original language, so the selected GL has no impact on the % complete.
In tN, the checks are not pegged directly to the original language, so it is possible that the number of checks will vary between GL's. Thus we can't calculate the % complete until we know the GL.

**Comment by elsylambert** [comment]
Regression for 2.1.0. Working fine.
