### ISSUE TITLE
Verse Edit Checking Performance

### ISSUE THREAD

**Issue by RoyalSix** [unfoldingWord/translationCore#6472]
### User Story

As a [type of user], I want [some goal] so that [some reason].

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by PhotoNomad0** [comment]
**Notes:**

Builds:
- Jay's changes, build 420bda8: 
- Latest develop,  28ba6a8 build

Testing in tW, `amazed` using [ULT Mat](https://github.com/unfoldingWord-dev/translationCore/files/3709325/en_ult_mrk_book.zip) 

**Timing of edit and validation checking:**

Mac: 
- **Jays changes:** check edit - Mk 1:27 - 3 sec, SP edit - Mk 2:12 - 3 s 
- **develop branch:** check edit - Mk 1:27 - 5 sec, SP edit - Mk 2:12 - 6 s 

Win 64:
  - **Jays changes:** check edit- Mk 1:27 - 7 sec, SP edit - Mk 2:12 - 8 s 
  - **develop branch:** check edit- Mk 1:27 - 13.5 sec, SP edit - Mk 2:12 - 17.5 s

**Comment by PhotoNomad0** [comment]
Checked in build translationCore 2.0.0 (1654f9b).  Found problem with check edits that you cannot unselect reasons once they have been selected (selection works fine, but unselection does not work):

![Screen Shot 2019-10-10 at 9 55 54 AM](https://user-images.githubusercontent.com/14238574/66575778-88fb8800-eb44-11e9-8306-32a59816726a.png)

Also see problem when you exit tool and re-enter the same tool, you get blank tool:

![Screen Shot 2019-10-10 at 10 00 16 AM](https://user-images.githubusercontent.com/14238574/66575934-d5df5e80-eb44-11e9-93f9-54deb72a9954.png)

**Comment by cckozie** [comment]
2.0.0 (9ef4802)
See all timings in attached spreadsheet. There are several significant improvements compared to the 2.0 release. Improvements > 30% highlighted in green, greater than 20% highlighted in blue.
It is still taking twice as long to check for resets when editing a verse in the scripture pane of tW as compared to editing it in the scripture pane of wA. tN falls in between the two.

Time to test for resets after edit in:
-
tW scripture pane | 14.88
tN scripture pane | 9.6
wA scripture pane | 7.52
  |  
tW check | 6.64
tN check | 4.24

[tC_performance-4802.xls.zip](https://github.com/unfoldingWord-dev/translationCore/files/3726361/tC_performance-4802.xls.zip)

**Comment by elsylambert** [comment]
Tested in 2.0.0 (9ef4802). Significant speed up for Verse Edit checking Performance compared to 2.0 Release.
Here are the timings on Win 64:
Edits in scripture pane: tW-5.50
Edits in scripture pane: tN: 4.32
Edits in scripture pane::tW: 5.30

50-60% time-drop in Saving selections and navigating between checks in tW:
[tC_Performance Improvements in tW (2).zip](https://github.com/unfoldingWord-dev/translationCore/files/3730291/tC_Performance.Improvements.in.tW.2.zip)
