### ISSUE TITLE
Hindi IRV missing certain words in Titus 3:14

### ISSUE THREAD

**Issue by jobbyp** [unfoldingWord/translationCore#6478]
![tC screenshot for Titus 3.png](https://images.zenhubusercontent.com/5bbcda0c3da0ca1ec7638ecf/860ac092-f409-48a6-b1cc-9b70f1976ad4)
### User Story

As a [type of user], I want [some goal] so that [some reason].

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by elsylambert** [comment]
Not seeing this issue in  2.2.0 (2375ae5).
