### ISSUE TITLE
Hindi IRV missing text in Titus 2:3

### ISSUE THREAD

**Issue by jobbyp** [unfoldingWord/translationCore#6479]
![Titus 2.png](https://images.zenhubusercontent.com/5bbcda0c3da0ca1ec7638ecf/90752d35-5a5f-4a16-86a8-0c04cdfa4f58)## Story Explanation
### User Story

As a [type of user], I want [some goal] so that [some reason].

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by cckozie** [comment]
The problem appears to be that when a user upgrades to 2.0, tC doesn't realize that there is a newer version of the IRV available (packaged with the app). It also does not show Hindi on the resources download screen.
I deleted the Hindi folder in resources and restarted tC. That fixes the problem.
It is not a problem if the user does a clean install of tC (no translationCore folder).
This possibly should be added to the 2.0 Release Notes, and probably should be in the 2.0.1 hotfix.

**Comment by elsylambert** [comment]
Not seeing this issue in  2.2.0 (2375ae5).
