### ISSUE TITLE
SPIKE: Research Offline Mode

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#648]
Figure out if there is a way for Electron to disable internet usage. 

See #628  and #644. 

Timebox at 2 Story Points!

**Comment by RoyalSix** [comment]
const win = require('electron').remote.BrowserWindow;
    const focusedWindow = win.getFocusedWindow() || win.getAllWindows()[0];
    focusedWindow.webContents.session.webRequest.onBeforeRequest([], (details, callback) => {
      callback({ cancel: false, requestHeaders: details.requestHeaders })
    })
