### ISSUE TITLE
No Selection Needed value is not saved

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6487]
2.0.0 (9e1bc7a)
Open a project in tW.
Click on the No Selection Needed Checkbox
Click Save 
Click Save & Continue
Go back to the previous check
Note that the No Selection Needed checkbox is not checked
This worked in 2.0.0 (9ef4802) from 10/12

**Comment by PhotoNomad0** [comment]
Verified in translationCore 2.0.0 (f5ff634)

**Comment by cckozie** [comment]
Looks good in 2.0.0 (f5ff634)

**Comment by elsylambert** [comment]
Looks good in  2.1.0 (d0a11e7).
