### ISSUE TITLE
"No selection" menu filter not working correctly

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6490]
2.0.0 (f5ff634) 
https://git.door43.org/tcsave/en_ult_luk_book
This was not working in the 2.0 release.
This project has all tW checks completed, shows 100% on the tW tools card, but has many groups and checks showing in the menu when filtered for "No selection".

**Comment by PhotoNomad0** [comment]
@cckozie - it's looking like the problem is that checks with `no selection needed` are showing up in the `no selection` filter.  Technically there is no selection for these checks.  I can make the logic change if that is what we want.

**Comment by PhotoNomad0** [comment]
@cckozie - it also looks like selected filter does not include items with `no selection needed`.  Should that be changed as well?

**Comment by cckozie** [comment]
@PhotoNomad0 Yes. I think the typical user will use those filter options to easily find completed and more often incomplete checks. So from that perspective, "No selection needed" is the same as "Selection complete" as indicated by the check mark.

**Comment by PhotoNomad0** [comment]
Verified in translationCore 2.1.0 (1a3811f)

**Comment by cckozie** [comment]
2.1.0 (49499fd)
The menu filtering is now working correctly.

**Comment by cckozie** [comment]
@PhotoNomad0 Do you recall why this was moved from QA Done to Watch List?

**Comment by PhotoNomad0** [comment]
@cckozie - no, I do not remember now.  I Put it back.
