### ISSUE TITLE
Project with 100% complete tW checks shows reset checks when imported or reselected

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6491]
2.0.0 (f5ff634) 
This problem existed in the 2.0 release.
https://git.door43.org/tcsave/en_ult_luk_book
This project has 100% complete alignments and 100% complete tW checks. 
When it is imported, the tW card indicates 2 reset selections.
After loading the project in tW and re-completing those reset selections, the tool card again shows 100% and 0 broken links.
![image](https://user-images.githubusercontent.com/8171759/67043925-c5088d00-f0f0-11e9-843f-edca16ca0407.png)
After loading a different project and then going back to this one, I again see 2 reset selections and sometime 99% complete. 
Upon loading the project in tW, I now see a check with the broken link icon and the selection still highlighted.
![image](https://user-images.githubusercontent.com/8171759/67043051-c933ab00-f0ee-11e9-8312-374516bfdb83.png)

Each time I repeat this test, 2:9 under Lord and 12:10 under Forgive are the checks that get reset.
Sometimes when selecting after loading a different project, it shows 100% complete, but 2 reset selections.
![image](https://user-images.githubusercontent.com/8171759/67044086-26c8f700-f0f1-11e9-821e-41d2876ba6ef.png)

(I did look at resources available to download. English was available so I downloaded it. Greek was not available.)

**Comment by PhotoNomad0** [comment]
@cckozie - interesting bug here - it looks like there is a space added to some selections - and this is not valid.  Looking to see how it can be fixed.

**Comment by PhotoNomad0** [comment]
@cckozie Here is an example of the invalid selections: https://git.door43.org/tcsave/en_ult_luk_book/src/branch/master/.apps/translationCore/checkData/selections/luk/2/9/2019-10-16T21_45_55.916Z.json

But the current tCore still adds space under some conditions - investigating.

**Comment by PhotoNomad0** [comment]
**Note**
found bug in getSelectionsFromChapterAndVerseCombo() in checking_tool_wrapper that it does not compare the occurrence.  This is called on invalidation so that the wrong occurrence may be invalidated.

**Comment by PhotoNomad0** [comment]
@cckozie - I found two problems:
- when there are multiple checks in a verse (e.g. `Lord` in Luke 2:9), invalidation would sometimes invalidate the wrong occurrence.  That took a few hours to track down, but an easy fix.
- the selection tool lets you select space between words.  Then later when the book is revalidated, it doesn't like one of the selections being just space and not actually a word - so it gets invalidated.  We could do a few things to resolve that:
  1. we could ignore selections in a selection array that just have spaces - this may be difficult to implement.
  2. we could remove selections in a selection array that just have spaces when we save - this is easier
  3. we could not allow users to select just a space - this may be difficult.

Thinking we should go with 2.  Thoughts?  Think I will post this in wg-tc.

**Comment by PhotoNomad0** [comment]
**Note:**
From wg-tc discussion, fixes to be made as part of this issue:
- Remove selections that are only space(s)
- Trimming leading and trailing spaces on each selection.
- Merge selections that are only separated by space (including unicode spaces)
- fix issue that edits sometimes invalidated the wrong check if there was more than one in the same verse having the same groupId

**Comment by PhotoNomad0** [comment]
Verified in translationCore 2.1.0 (9bdeb06) invalidation issue should be fixed as well as selection fixes/changes.

**Comment by cckozie** [comment]
Looks good in 2.1.0 (49499fd). Spaces cannot be selected. Adjacent selected words are merged in single selection. Punctuation can be selected. Adjacent words separated by punctuation are not merged.

**Comment by elsylambert** [comment]
Verified in 2.1.0 (7adcd44). Selections are working as expected.
