### ISSUE TITLE
URL not accepted when importing project with URL

### ISSUE THREAD

**Issue by ChrisJarka** [unfoldingWord/translationCore#650]
I'm trying to import an online project. So I copied the URL and dropped it into the field. Then I received that the URL was not correct because the program requires the URL to end with a .git. Please help me on what I did wrong?

![cannot import from url tc](https://cloud.githubusercontent.com/assets/9850185/22712474/e78f5916-ed52-11e6-8d30-6fba810fcd6d.png)

**Comment by benjore** [comment]
Duplicate #681
