### ISSUE TITLE
Move reducers only used by tools to the tools’ codebase

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord/translationCore#6501]
### User Story

As a [type of user], I want [some goal] so that [some reason].

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by PhotoNomad0** [comment]
@verified in translationCore 2.2.0 (c65f647)

https://github.com/unfoldingWord/translationCore/actions/runs/38810905
