### ISSUE TITLE
[0] SPIKE: Need performance improvements when editing verses in the scripture pane and check pane

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6504]
2.0.0 (9ef4802)
See all timings in attached spreadsheet. There are several significant improvements compared to the 2.0 release. Improvements > 30% highlighted in green, greater than 20% highlighted in blue.
It is still taking twice as long to check for resets when editing a verse in the scripture pane of tW as compared to editing it in the scripture pane of wA. tN falls in between the two.

Time to test for resets after edit in:
-
tW scripture pane | 14.88
tN scripture pane | 9.6
wA scripture pane | 7.52
  |  
tW check | 6.64
tN check | 4.24

[tC_performance-4802.xls.zip](https://github.com/unfoldingWord-dev/translationCore/files/3726361/tC_performance-4802.xls.zip)

**Comment by cckozie** [comment]
Performance is worse in 2.2.0 (2375ae5)
[tC_performance.csv 4.zip](https://github.com/unfoldingWord/translationCore/files/4390019/tC_performance.csv.4.zip)

**Comment by cckozie** [comment]
New performance measurements in 2.2.0 (d8fd543) 
The verse being edited (Mat 6:13) is fully aligned and has one of the three tW checks completed and the only tN check completed.

Time to test for resets after edits in:
tW scripture pane: 17 seconds (10 seconds in 2.1.2)
tN scripture pane: 9 seconds (6 seconds in 2.1.2)
wA scripture pane: 14 seconds (8 seconds in 2.1.2)

**Comment by cckozie** [comment]
New performance measurements in 2.2.0 (d2e40ce)
The verse being edited (Mat 6:13) is fully aligned and has one of the three tW checks completed and the only tN check completed. In each test case the verse with the completed check was the one selected when the edit was performed. 

Time to test for resets after edits in:
tW scripture pane: Mac - 14 seconds (10 seconds in 2.1.2), Windows - 27 seconds
tN scripture pane: Mac - 6 seconds (6 seconds in 2.1.2), Windows - 8 seconds
wA scripture pane: Mac - 11 seconds (8 seconds in 2.1.2), Windows - 9 seconds

For reference, performing the same edits in the check pane yields these timings in 2.2:
tW check pane edit: Mac - 6 seconds, Windows - 8 seconds
tN check pane edit: Mac - 2 seconds, Windows - 4 seconds

Based on these test, it seems to me the target for testing for resets should be 2 seconds or less on my Mac and 4 seconds or less on my WIndows machine in each case.

**Comment by cckozie** [comment]
There has been a dramatic improvement in the time it takes to test for resets when editing in the scripture pane of tW and wA, and those number are now pretty consistent with editing the scripture pane in tN.
However, it still takes about twice as long to test for resets when editing in the scripture pane as when editing in the check pane of both tW and tN. 
![image](https://user-images.githubusercontent.com/8171759/82482545-a3afbb00-9a9c-11ea-9f50-01b12d46de4e.png)

**Comment by mannycolon** [comment]
Did spike and implementation together which resulted in a `Large` estimate

**Comment by mannycolon** [comment]
Verified on 0f8fc18

**Comment by cckozie** [comment]
There has been a significant improvement in the time it takes to check for reset alignments and checks when editing in the scripture pane of wA and tN. The others remain pretty much the same. The outlier remains editing in the scripture pane of tW, which still takes more the twice as long as editing in the check pane of tW, and 70% longer than editing in the scripture pane of tN or wA.
Passing this one as it was a spike. Added #6963 to deal with the tW scripture pane.
![image](https://user-images.githubusercontent.com/8171759/83713197-18324000-a5ed-11ea-95fb-cd86a9d6c123.png)

**Comment by elsylambert** [comment]
Looks good in 3.0.0 (dad3c32).
