### ISSUE TITLE
My list of online projects is not complete

### ISSUE THREAD

**Issue by ChrisJarka** [unfoldingWord/translationCore#651]
When I uploaded from tS-Desktop to my repo and then in tC signed off and then back on - my list of the available online projects does not include the project just uploaded from tS-Desktop. (Yes, my tC is online.)

It would be nice to have an update list button on the bottom left - or somewhere on the page.
![update online project list](https://cloud.githubusercontent.com/assets/9850185/22713379/308dc29e-ed56-11e6-9bb9-405351563055.png)

**Comment by benjore** [comment]
Make tC fetch data every time this tab is opened.

**Comment by RoyalSix** [comment]
<img width="314" alt="screen shot 2017-02-14 at 1 05 07 pm" src="https://cloud.githubusercontent.com/assets/16184018/22949201/46126236-f2b6-11e6-844b-68fe62f19401.png">
needs to happen on render in file "ImportOnlineContainer.js"
