### ISSUE TITLE
The alert indicating content problems on tN checks is no longer being displayed

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6513]
2.1.0 (3091b6e) 
https://git.door43.org/TC_SAVE/en_ust_rut_book
Import this file
Load in tN
Navigate to 1:16 under Assumed Knowledge
Note that the alert is not displayed
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/e7ff053c-d5d0-4cf9-bf97-04220b32ce28)

In  the 2.0 release this alert is displayed on 1:16 and 2:18 in that group
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/07fb0b0c-3470-45a1-b9d1-94588f57ffff)

**Comment by PhotoNomad0** [comment]
Verified in translationCore 2.1.0 (d8f36fe)

**Comment by cckozie** [comment]
Looks good in  2.1.0 (d8f36fe)

**Comment by elsylambert** [comment]
Verified in 2.1.0 (7adcd44). Alert is displayed for content problems.
