### ISSUE TITLE
enhancement for loading projects

### ISSUE THREAD

**Issue by ChrisJarka** [unfoldingWord/translationCore#652]
Importing projects - would be nice if it worked like the import on translationStudio.

Where the end user can select from Door43 user names or by book or by language.

![import project capture from ts](https://cloud.githubusercontent.com/assets/9850185/22713747/b0b1b498-ed57-11e6-88e5-0de805776855.png)

**Comment by RoyalSix** [comment]
I like this idea as well

**Comment by benjore** [comment]
Covered by #971
