### ISSUE TITLE
Downloaded resources do not appear as available for a GL when they are downloaded on the Tools page

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6526]
2.0
Reported from the field.
[57-TIT.kn.usfm.zip](https://github.com/unfoldingWord/translationCore/files/3806379/57-TIT.kn.usfm.zip)
1. Import this project
2. While on the Tools page, note that (kn) is not available as a GL for tW
3. While still on the Tools page download the (kn) resources
4. When the download finishes, note that (kn) is still not available as a GL for tW
5. Go to the Projects page
6. Return to the Tools page
7. Note that (kn) is now available as a GL for tW

**Comment by PhotoNomad0** [comment]
Verified in translationCore 2.1.0 (22cd49a)

**Comment by cckozie** [comment]
Works in 2.1.0 (22cd49a)

**Comment by elsylambert** [comment]
Working fine in 2.1.0 (7adcd44)
