### ISSUE TITLE
Critical error message after selecting a project

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6527]
2.1.0 (27a1ce3) This is a test build

Start with at least one existing project in tC
1. Import a project
2. When the import completes on the Tools page, return  to the Projects page
3. Upload a project OTHER THAN THE ONE JUST IMPORTED to Door43
4. Select the project that was just uploaded
Note that you get the Critical error screen
In  previous builds, anytime an activity from the 3-dot menu was completed, the previously selected project was unselected. That was done as a fix a while back, but it does not occur in this build.

**Comment by PhotoNomad0** [comment]
@cckozie - may need more detail here - like maybe a video or log.  Having trouble reproducing it with this test build.

**Comment by PhotoNomad0** [comment]
@cckozie - I'm going to create a test build with the fix to close open projects before upload to see if that helps.

**Comment by PhotoNomad0** [comment]
@cckozie - A test build to try:

From the `release-v2.1.0-test.4` branch:
[Linux build 2.1.0 (ec9b8f4)](https://tc-builds.door43.org/build/release-v2.1.0-test.4/translationCore-linux-x64-2.1.0-ec9b8f4.deb) is ready for download.
[macOS build 2.1.0 (ec9b8f4)](https://tc-builds.door43.org/build/release-v2.1.0-test.4/translationCore-macos-x64-2.1.0-ec9b8f4.dmg) is ready for download.
[Windows x64 build 2.1.0 (ec9b8f4)](https://tc-builds.door43.org/build/release-v2.1.0-test.4/translationCore-win-x64-2.1.0-ec9b8f4.setup.exe) is ready for download.
[Windows x32 build 2.1.0 (ec9b8f4)](https://tc-builds.door43.org/build/release-v2.1.0-test.4/translationCore-win-x32-2.1.0-ec9b8f4.setup.exe) is ready for download.

**Comment by cckozie** [comment]
@PhotoNomad0 Test build looks good. I've been unable to recreate the problem with it.

**Comment by cckozie** [comment]
Not seeing the problem in 2.1.0 (d8f36fe)
