### ISSUE TITLE
WordMAP should not treat the translation identifier as being case sensitive

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6534]
2.1.0 (d45bc64)
[6534.zip](https://github.com/unfoldingWord/translationCore/files/3833006/6534.zip)
1. Start with an empty projects folder
2. Drop the two projects from the zip file above into an empty projects folder
3. Start tC
4. Import this USFM file [38-ZEC.usfm.zip](https://github.com/unfoldingWord/translationCore/files/3833011/38-ZEC.usfm.zip) as English with translation ID of 'ust'
5. Load the Zec project in wA
Note that there are no suggestions for any of the verses, either based on exact match or lemma
Here is one example where there should be a suggestion:
Alignments in Judges
<img width="675" alt="jdg" src="https://user-images.githubusercontent.com/8171759/68621620-d77aaa00-0495-11ea-9123-6f0abbfe6248.png">

No suggestion in  Zechariah
<img width="448" alt="zec4" src="https://user-images.githubusercontent.com/8171759/68621637-dfd2e500-0495-11ea-9c37-4375e7aa4a6c.png">

**Comment by cckozie** [comment]
The real problem here is that the wordMAP is treating the translation identifier as being case sensitive in determining language and translation identifier matches.
When tC is validating the uniqueness of language/book/translation id, it treats the tid as not being case sensitive. tC always displays the tid in lower case on the projects page.
For consistency, I believe it would be better to always treat it as non-case sensitive.

**Comment by PhotoNomad0** [comment]
@cckozie - here is a test build to try with Alignment memory using lower case translation ids:

From the `release-vx2.1.0-test.2` branch:
[Linux build 2.1.0 (fcfdbfb)](https://tc-builds.door43.org/build/release-vx2.1.0-test.2/translationCore-linux-x64-2.1.0-fcfdbfb.deb) is ready for download.
[macOS build 2.1.0 (fcfdbfb)](https://tc-builds.door43.org/build/release-vx2.1.0-test.2/translationCore-macos-x64-2.1.0-fcfdbfb.dmg) is ready for download.
[Windows x64 build 2.1.0 (fcfdbfb)](https://tc-builds.door43.org/build/release-vx2.1.0-test.2/translationCore-win-x64-2.1.0-fcfdbfb.setup.exe) is ready for download.
[Windows x32 build 2.1.0 (fcfdbfb)](https://tc-builds.door43.org/build/release-vx2.1.0-test.2/translationCore-win-x32-2.1.0-fcfdbfb.setup.exe) is ready for download.

**Comment by cckozie** [comment]
@PhotoNomad0 Looks good in the test build

**Comment by PhotoNomad0** [comment]
Verified in translationCore 2.1.0 (8b531e4)

**Comment by cckozie** [comment]
Works correctly in 2.1.0 (8b531e4)
