### ISSUE TITLE
Add Webpack code bundling to tC

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord/translationCore#6535]
### User Story

As a tC developer, I want to setup code bunking so that we can have and add the latest access to the latest versions of Javascript and add tree shaking. 

### Features / Specifications

- [ ] Upgrade to latest version of babel.
- [ ] Upgrade to latest version of electron.
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by da1nerd** [comment]
Issue https://github.com/unfoldingWord/translationCore/issues/6383 contains links to some sample projects using webpack. Adding it here as a reference.
