### ISSUE TITLE
Links in tW and tA articles bring up window with message "Cannot find an article for..."

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6541]
2.1.0 (22cd49a) 
Clicking a link in the tW helps pane brings up a window with the error message "Cannot find an article for..."
Clicking the same link a second time does cause the article to be properly displayed.
This appears to be the case on all links regardless of the GL selected
[tW links.mp4.zip](https://github.com/unfoldingWord/translationCore/files/3837852/tW.links.mp4.zip)

In the tN helps pane, the first link clicked appears not to register at all. Clicking the same link again works correctly.
After that, in a different thelps article, clicking links has the same behavior as in tW.
(Links in tN can be found at the bottom of the thelps pane for Metaphor and Metonymy)

**Comment by PhotoNomad0** [comment]
@cckozie - I'm thinking this breakage is from the hooks refactor.

**Comment by cckozie** [comment]
@PhotoNomad0 Seems likely since this worked correctly in 2.0

**Comment by elsylambert** [comment]
Similarly, clicking the links within the translation helps window shows "cannot find an article.." and clicking on it the second time brings up the article.

**Comment by PhotoNomad0** [comment]
@cckozie @elsylambert - have a test build to try out here:

From the `release-vx2.1.0-test.2` branch:
[Linux build 2.1.0 (a95e6be)](https://tc-builds.door43.org/build/release-vx2.1.0-test.2/translationCore-linux-x64-2.1.0-a95e6be.deb) is ready for download.
[macOS build 2.1.0 (a95e6be)](https://tc-builds.door43.org/build/release-vx2.1.0-test.2/translationCore-macos-x64-2.1.0-a95e6be.dmg) is ready for download.
[Windows x64 build 2.1.0 (a95e6be)](https://tc-builds.door43.org/build/release-vx2.1.0-test.2/translationCore-win-x64-2.1.0-a95e6be.setup.exe) is ready for download.
[Windows x32 build 2.1.0 (a95e6be)](https://tc-builds.door43.org/build/release-vx2.1.0-test.2/translationCore-win-x32-2.1.0-a95e6be.setup.exe) is ready for download.

**Comment by elsylambert** [comment]
Verified in 2.1.0 (a95e6be). Links in tW help articles works fine and are getting loaded the very first time. However, there is a 1 second delay in loading of Help pane article itself when navigated from one article to another.
Links in tN help pane are not working at all. Clicking on it even multiple times, does not bring up any results.
Also, tA links within translation help window, do not work.
![image](https://user-images.githubusercontent.com/51806180/68960871-0bf4ab80-079f-11ea-970b-76a5ae599843.png)

**Comment by PhotoNomad0** [comment]
@elsylambert - thanks for feedback.

**Comment by PhotoNomad0** [comment]
@elsylambert - found a logic error I introduced.  This should work better:

From the `release-vx2.1.0-test.2` branch:
[Linux build 2.1.0 (fa6cd3b)](https://tc-builds.door43.org/build/release-vx2.1.0-test.2/translationCore-linux-x64-2.1.0-fa6cd3b.deb) is ready for download.
[macOS build 2.1.0 (fa6cd3b)](https://tc-builds.door43.org/build/release-vx2.1.0-test.2/translationCore-macos-x64-2.1.0-fa6cd3b.dmg) is ready for download.
[Windows x64 build 2.1.0 (fa6cd3b)](https://tc-builds.door43.org/build/release-vx2.1.0-test.2/translationCore-win-x64-2.1.0-fa6cd3b.setup.exe) is ready for download.
[Windows x32 build 2.1.0 (fa6cd3b)](https://tc-builds.door43.org/build/release-vx2.1.0-test.2/translationCore-win-x32-2.1.0-fa6cd3b.setup.exe) is ready for download.

**Comment by elsylambert** [comment]
Looks good in 2.1.0 (fa6cd3b). The links for tA are working fine in both tW and tN within help pane  and in translationHelps window.

**Comment by PhotoNomad0** [comment]
Verified in translationCore 2.1.0 (2216ef6)

**Comment by cckozie** [comment]
Looks good in 2.1.0 (8b531e4)
