### ISSUE TITLE
Content update fails when file doesn't exist

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/translationCore#6559]
### Prerequisites

- [X] I have searched the [issues](https://github.com/unfoldingWord-dev/translationCore/issues) of this repository and believe that this is not a duplicate.

### Description
Attempt to update English content resulted in Failure to update dialog.  The log showed:
`Error getting https://cdn.door43.org/en/tn/v18/tn.zip: Unable to download resources: Error: ENOENT: no such file or directory, open '/home/birch/translationCore/resources/en/translationHelps/translationAcademy/v11/translate/writing-connectingwords.md' `
This is a new tA article., so the file doesn't exist in my resources. Manually creating the file allowed the update to complete.

### Steps to Reproduce
Note: Simply removing the file doesn't produce the error on update. The content must be outdated.
1. On an installation with outdated English content missing a tA article file. 
2. Click Update Content
3. Choose English, and click download.
4. See the generic Update failed/retry error dialog

**Environment**
| Tech         | Version |
|--------------|---------|
| tc           | v 2.0.0 |
| build #      |     8a6a8c5    |
| OS           |     Ubuntu Linux     |

**Comment by cckozie** [comment]
Also fails on Mac on 2.0 - [Mon Nov 18 2019.2.0.log.zip](https://github.com/unfoldingWord/translationCore/files/3858557/Mon.Nov.18.2019.2.0.log.zip)

Also fails on Mac on 2.1.0 (ff63bfd) - [Mon Nov 18 2019.2.1.log.zip](https://github.com/unfoldingWord/translationCore/files/3858577/Mon.Nov.18.2019.2.1.log.zip)

**Comment by elsylambert** [comment]
"Fails to download source content update"
2.1.0 (fa6cd3b)- Verified on Windows.
[Mon Nov 18 2019.zip](https://github.com/unfoldingWord/translationCore/files/3859274/Mon.Nov.18.2019.zip)

**Comment by PhotoNomad0** [comment]
@cckozie @birchamp @elsylambert - I found two bad links in latest en tn in the catalog:

10:42:28 GMT-0500 (Eastern Standard Time) ERROR: v2.1.0 (92d743b): convertLinkToMarkdownLink() - invalid link: **[[rc://en/ta/translate/writing-newevent]]**, resourcesPath: /Users/blm/translationCore/resources, langId: en,{} 
10:42:34 GMT-0500 (Eastern Standard Time) ERROR: v2.1.0 (92d743b): cleanOccurrenceNoteLinks() - occurrenceNote: **This sentence introduces the next part of the story, in which Ruth asks Boaz to perform the role of kinsman-redeemer for her and Naomi. (See: [[rc://en/ta/translate/writing-newevent]])**, resourcesPath: /Users/blm/translationCore/resources, langId: en, bookId: rut, chapter: 3,{} 
10:42:53 GMT-0500 (Eastern Standard Time) ERROR: v2.1.0 (92d743b): tsvToGroupData() - error processing item:,{"Book":"RUT","Chapter":"3","Verse":"1","ID":"jdr3","SupportReference":"writing-newevent","OrigQuote":"וַ⁠תֹּ֥אמֶר לָ֖⁠הּ נָעֳמִ֣י","Occurrence":"1","GLQuote":"Naomi…said to her,","OccurrenceNote":null} 
10:43:12 GMT-0500 (Eastern Standard Time) ERROR: v2.1.0 (92d743b): tsvToGroupData() - error processing file: **/Users/blm/translationCore/resources/imports/en_tn_v18/en_tn/en_tn_08-RUT.tsv** 
10:44:11 GMT-0500 (Eastern Standard Time) ERROR: v2.1.0 (92d743b): convertLinkToMarkdownLink() - invalid link: **[[rc://en/ta/man/grammar-connect-time-simultaneous]]**, resourcesPath: /Users/blm/translationCore/resources, langId: en,{} 
10:44:18 GMT-0500 (Eastern Standard Time) ERROR: v2.1.0 (92d743b): cleanOccurrenceNoteLinks() - occurrenceNote: **Jonahs says that he remembered Yahweh when he had lost hope of being rescued from the sea. (See: [[rc://en/ta/man/grammar-connect-time-simultaneous]],** resourcesPath: /Users/blm/translationCore/resources, langId: en, bookId: jon, chapter: 2,{} 
10:44:18 GMT-0500 (Eastern Standard Time) ERROR: v2.1.0 (92d743b): tsvToGroupData() - error processing item:,{"Book":"JON","Chapter":"2","Verse":"7","ID":"jdr6","SupportReference":"Grammar-connect-time-simultaneous","OrigQuote":"בְּ⁠הִתְעַטֵּ֤ף עָלַ⁠י֙ נַפְשִׁ֔⁠י ","Occurrence":"1","GLQuote":"When my soul fainted within me,","OccurrenceNote":null} 
10:44:24 GMT-0500 (Eastern Standard Time) ERROR: v2.1.0 (92d743b): tsvToGroupData() - error processing file: **/Users/blm/translationCore/resources/imports/en_tn_v18/en_tn/en_tn_32-JON.tsv**

**Comment by PhotoNomad0** [comment]
**Notes:**
- have PR for content problems: https://git.door43.org/unfoldingWord/en_tn/pulls/1307 
- making changes to tC to do better logging of link parsing errors.

**Comment by PhotoNomad0** [comment]
@cckozie - Have logging fix in translationCore 2.1.0 (2216ef6) - it adds details to the log about the link errors that cause the import to fail.

Still need to wait for links to be fixed in Catalog, @jag3773 is scheduled to update the catalog Wednesday.

**Comment by cckozie** [comment]
Waiting for the catalog update

**Comment by cckozie** [comment]
@PhotoNomad0 - How much work would it be to change the download failure dialog to include a reason (if we know it)? In this case, add something like " because of content problem in translationNotes". If the effort is significant I'll just add an issue to the backlog.

**Comment by PhotoNomad0** [comment]
@cckozie - best to add an issue.  Could be a bit involved to propagate the error from source updater module up to tCore and present it as a much simpler summary in tCore.

**Comment by cckozie** [comment]
Added #6574 to address the lack of clarity in the failure notification.

**Comment by PhotoNomad0** [comment]
Have additional error logging in translationCore 2.1.0 (e624b3b)

**Comment by cckozie** [comment]
Not seeing any failures when downloading resources in 2.1.0 (0a80f05) 
Program gracefully recovers from loss of Internet connection after it is restored

**Comment by elsylambert** [comment]
Looks good in  2.1.0 (d0a11e7).
