### ISSUE TITLE
Selecting check box switches tab back to tW

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#656]
From Slack "when selecting one of the check boxes under “Propose Changes”, the tab switches back to “tW” instead of remaining on the “Propose Changes” tab."

Note: If Flag is selected, this is problem does not happen.

**Comment by mannycolon** [comment]
Unless someone else finds a way to make this happen

I think we need t reconsider the workflow for auto selecting the proposed changes tab when clicking on the 'flagged' button.  it seems to be tricky to pull off this feature without it messing with other components.
