### ISSUE TITLE
Update resources and localization for 2.1.0 Release

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#6560]
### User Story

As a [type of user], I want [some goal] so that [some reason].

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by PhotoNomad0** [comment]
@cckozie - have a  build with minimal bundled resources:

From the `release-vx2.1.0-test.2` branch:
[Linux build 2.1.0 (3775a82)](https://tc-builds.door43.org/build/release-vx2.1.0-test.2/translationCore-linux-x64-2.1.0-3775a82.deb) is ready for download.
[macOS build 2.1.0 (3775a82)](https://tc-builds.door43.org/build/release-vx2.1.0-test.2/translationCore-macos-x64-2.1.0-3775a82.dmg) is ready for download.
[Windows x64 build 2.1.0 (3775a82)](https://tc-builds.door43.org/build/release-vx2.1.0-test.2/translationCore-win-x64-2.1.0-3775a82.setup.exe) is ready for download.
[Windows x32 build 2.1.0 (3775a82)](https://tc-builds.door43.org/build/release-vx2.1.0-test.2/translationCore-win-x32-2.1.0-3775a82.setup.exe) is ready for download.

Windows 64-bit is **134.8 MB**

Time to open on Mac: 1:30 (size = 417.5MB)
Time to open on slow Windows machine with SSD: 3:45
Time to open on Windows machine with hard drive: 8:41
<img width="294" alt="min" src="https://user-images.githubusercontent.com/8171759/69370815-48734c00-0c64-11ea-87d2-81ceb09f976b.png">

**Comment by PhotoNomad0** [comment]
@cckozie - And the maximal build here:

From the `release-vx2.1.0-test.3` branch:
[Linux build 2.1.0 (49a287a)](https://tc-builds.door43.org/build/release-vx2.1.0-test.3/translationCore-linux-x64-2.1.0-49a287a.deb) is ready for download.
[macOS build 2.1.0 (49a287a)](https://tc-builds.door43.org/build/release-vx2.1.0-test.3/translationCore-macos-x64-2.1.0-49a287a.dmg) is ready for download.
[Windows x64 build 2.1.0 (49a287a)](https://tc-builds.door43.org/build/release-vx2.1.0-test.3/translationCore-win-x64-2.1.0-49a287a.setup.exe) is ready for download.
[Windows x32 build 2.1.0 (49a287a)](https://tc-builds.door43.org/build/release-vx2.1.0-test.3/translationCore-win-x32-2.1.0-49a287a.setup.exe) is ready for download.

Windows 64-bit is **182.9 MB**

Time to open on Mac: 2:25 (size = 470.7MB)
Time to open on slow Windows machine with SSD: 5:45
Time to open on Windows machine with hard drive - 11:32

<img width="191" alt="max1" src="https://user-images.githubusercontent.com/8171759/69371405-61303180-0c65-11ea-9c05-88ea18a979ef.png">

<img width="184" alt="max2" src="https://user-images.githubusercontent.com/8171759/69371359-4d84cb00-0c65-11ea-9204-d2eed2992a91.png">

**Comment by PhotoNomad0** [comment]
@cckozie - Zulip is down for me, but this looks good.  There is no code differences here.  Just wanted the numbers (size, speed, etc.) as talking points.  But It would be good if you did some update testing on the minimal build to see if there are problems.

**Comment by elsylambert** [comment]
Tested on 64-bit windows machine with a hard disk
For the minimal build Time to open- 8:41
For the maximal build time to open- 11:32

**Comment by cckozie** [comment]
@PhotoNomad0 - I tested download of all resources and basic functionality of minimal build and did not see any issues.

**Comment by PhotoNomad0** [comment]
Verified minimum build in translationCore 2.1.0 (e624b3b)

**Comment by cckozie** [comment]
Looks good in 2.1.0 (0a80f05)

**Comment by elsylambert** [comment]
Looks good in 2.1.0 (d0a11e7).
