### ISSUE TITLE
tCore sometimes gets stuck at invalid login.

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#6568]
### User Story

From Perry:
_  is trying to upload his alignment of Exodus, but he gets this message each time: "Your login has become invalid. Please log out and log back in." He has done that, closed and reopened tC, but no change. 

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by PhotoNomad0** [comment]
**NOTE:**
After looking into the problems reported.  I see the presenting problem here is that the user gets the error message that login in invalid when they try to upload their project.  In the code, we present that error when the user token is empty (even though the user has logged in).  The only path I see that the user token can be empty is when the user logs in we check DCS for pre-existing tokens (`'users/' + user.username + '/tokens'`).  If there is a token in the list for tCore we use it (specifically the sha1), otherwise we create a new one for the user.  But in the tC 2.0.0 build we did not validate the token returned, but just used it.  But I have seen DCS return an empty string as the user's tC token.  I have already made a change in 2.1.0 that at tC login to check that the tC user token is not empty before using it.  And if it is empty we create a new one.  This should fix the problem in the field that Benjamin saw.  Now (in tC 2.1.0) when the user gets the message that their login is invalid, they just need to follow the instructions to log out and back in.  Then a new token will be created for them and that user should not see this problem again.  So I don't see that there is any more we need to do for tC 2.1.0.

**Comment by PhotoNomad0** [comment]
@cckozie - the current release-v2.1.0 build should already address this problem.  Maybe this should go in QA watch?

**Comment by cckozie** [comment]
I don't have anyway to test this, so moving to QA Watch List for now,.

**Comment by cckozie** [comment]
I believe this was fixed in 2.1.
