### ISSUE TITLE
Scripture Pane showing the wrong book

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#657]
The Scripture Pane is showing Mark (all three translations) instead of James. (The check itself is James.) 

![image](https://cloud.githubusercontent.com/assets/13352518/22745635/e23ab052-ede6-11e6-8522-564cb9f0f2ca.png)

**Comment by benjore** [comment]
The check was on James from this repo: https://git.door43.org/tinocobrazil/bible_pt-br_ulb_nt

**Comment by mannycolon** [comment]
@benjore what were your previous steps before encountering this issue. I just want to know so I can try recreating this bug. I think we got it fixed but won't be 100% sure until maybe I try the same workflow you did to encounter this bug.

**Comment by benjore** [comment]
Related to #680
