### ISSUE TITLE
Upgrading to 2.1 causes logins to become invalid

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6587]
2.1.0 (0a80f05) 
1. Delete the translationCore folders
2. Install 1.14 or 2.0
3. Start tC
4. Login to a Door43 account that had been used in 2.1
5. Import a project
6. Upgrade to 2.1
7. Attempt to upload the project to Door43
8. Note the "Your login has become invalid..." alert
This should either be fixed for the 2.1 release or the problem and workaround noted/highlighted in the release notes

**Comment by PhotoNomad0** [comment]
@cckozie - could not reproduce this starting with 2.0.0 and upgrading to 2.1.0.

**Comment by PhotoNomad0** [comment]
@cckozie - could not reproduce this starting with 1.1.4 and upgrading to 2.1.0.  Perhaps a video will help since there seems to be something we are doing differently?

**Comment by cckozie** [comment]
@PhotoNomad0 Here's a video: [loginn.mov.zip](https://github.com/unfoldingWord/translationCore/files/3922603/loginn.mov.zip)

**Comment by cckozie** [comment]
There were two tokens for tC for the user. I deleted them both.
I logged in to 2.0 as that user. Project uploaded without problems.
I upgraded to 2.1. Project uploaded without problems.
I logged out and back in as the same user. Project uploaded without problems.
I deleted the tC folders and restarted tC 2.0.
I logged in as the same user, imported a project, and got the login invalidated error when attempting to upload.
Looking at the settings for that user account I now again see two tokens for tC. Might that be the problem?

**Comment by PhotoNomad0** [comment]
@cckozie - I see from video that you are doing a local import, where I was doing an online import.  Checking to see if that makes a difference.

**Comment by PhotoNomad0** [comment]
@cckozie - OK, was able to reproduce the login invalid warning.  It looks like it requires that there is already a tCore application token on D43.  Then when you login with 2.0.0 it sees that there is already a token on D43 and uses that.  Unfortunately the new version of D43 returns all the tokens as having a sha1 (the actual D43 application token) as an empty string.  This empty string gets saved as the D43 token which means that upload is broken both in 2.0.0 and 2.1.0.

One possible solution would be to warn the user at startup that the login is invalid when they start tCore 2.1.0.

**Comment by PhotoNomad0** [comment]
@cckozie - also we should tweak the upload error message for when the token has been deleted.  Currently just get  the generic `Unable to connect to the server. Please check your Internet connection.`  It looks like we could map the 401 status code to the login is no longer valid message.

**Comment by PhotoNomad0** [comment]
Note: Manny suggests doing this check on Profile page.

**Comment by PhotoNomad0** [comment]
@cckozie @elsylambert Have a test build that should address this:

From the `release-vx2.1.0-test.1` branch:
[Linux build 2.1.0 (6ecdeec)](https://tc-builds.door43.org/build/release-vx2.1.0-test.1/translationCore-linux-x64-2.1.0-6ecdeec.deb) is ready for download.
[macOS build 2.1.0 (6ecdeec)](https://tc-builds.door43.org/build/release-vx2.1.0-test.1/translationCore-macos-x64-2.1.0-6ecdeec.dmg) is ready for download.
[Windows x64 build 2.1.0 (6ecdeec)](https://tc-builds.door43.org/build/release-vx2.1.0-test.1/translationCore-win-x64-2.1.0-6ecdeec.setup.exe) is ready for download.
[Windows x32 build 2.1.0 (6ecdeec)](https://tc-builds.door43.org/build/release-vx2.1.0-test.1/translationCore-win-x32-2.1.0-6ecdeec.setup.exe) is ready for download.

**Comment by cckozie** [comment]
@PhotoNomad0 - The test build correctly prompts when the user upgrades and the login is invalid. Looks good.

**Comment by elsylambert** [comment]
@PhotoNomad0 Verified in  2.1.0 (6ecdeec). Got the prompt for login invalid after upgrade from 2.0. Looks good.

**Comment by PhotoNomad0** [comment]
Verified in translationCore 2.1.0 (19c6637)

**Comment by cckozie** [comment]
2.1.0 (19c6637) 
Prompts for re-login immediately when starting 2.1 with invalid token
Prompts for re-login when uploading if user bypasses prompt during startup
Prompts for re-login when uploading after tokens have been deleted
Does not prompt for re-login immediately when starting 2.1 when tokens have been deleted. (I missed this test last night. I don't think it's worth messing with now)

**Comment by cckozie** [comment]
@PhotoNomad0 
2.1.0 (19c6637) 
Oops! Just noticed that if the user is logged in as a guest, the re-login prompt is displayed each time tC is started.

**Comment by PhotoNomad0** [comment]
@cckozie - local user fix verified in translationCore 2.1.0 (7adcd44)

**Comment by elsylambert** [comment]
Looks good in 2.1.0 (7adcd44).
-Getting prompt for re-login after upgrade from 2.0 to 2.1.
-Unless user does re-login, the prompt comes back when the user tries to upload the project to D43.
- Working fine for Guest login as well.

**Comment by cckozie** [comment]
2.1.0 (7adcd44) 
Works as expected with both Door43 and guest logins

**Comment by cckozie** [comment]
Video for deleting user tokens at https://forum.door43.org/t/problems-uploading-tc-or-ts/508
zulip stream at https://unfoldingword.zulipchat.com/#narrow/stream/207526-wg-tools/topic/General/near/183170106
