### ISSUE TITLE
Cannot return to Tools page after uploading an only project

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6589]
2.1.0 (0a80f05)
This has been broken after 2.0
The tool icon in stepper is disabled after uploading a project to Door43. (The tool name by the icon is also erased)
1. Delete all projects in the project folder
2. Import a USFM project
3. Return to the projects page
4. Click on the Tool icon in the stepper
5. Note that the user is taken to the Tools page
6. Return to the Projects page
7. Upload the project to Door43
8. Note that the Tool icon in the stepper is now disabled. Since the Select button for the project is also disabled, it is now not obvious how the user can get to the Tools page to Launch a tool

**Comment by PhotoNomad0** [comment]
@cckozie - strange situation - it seems that the projects page is caching the selection state and not updating when it has changed...gives me an idea.

**Comment by cckozie** [comment]
@PhotoNomad0 - In 2.0, the last used tool for the project did not get reset and the Tools icon remained enabled after an upload to Door43 was performed.

**Comment by cckozie** [comment]
In 2.1.0 (d0a11e7) I'm seeing the project's Select button being enabled now after an upload to Door43. That is different behavior than we saw in 2.0, but I think it is acceptable as it does fix the noted problem.

**Comment by PhotoNomad0** [comment]
@cckozie - I could try to get back the 2.0 behavior - the current solution was the safest with minimal code changes.

**Comment by elsylambert** [comment]
Verified in 2.1.0 (d0a11e7). After upload to Door43, the select button for the project is enabled, tools  is not. Tools gets enabled only after when I select a Gateway language selection.
