### ISSUE TITLE
Cannot import from Door43 if logged in as a guest and there are no repos for the guest's username

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6591]
2.1.0 (0a80f05)
1. Stop and restart tC
2. Log in as a guest with user name of "me"
3. Click on the FAB
4. Click on Import from Door43
5. Click the Access Internet button
6. Notice bad things as in the video [guest login.mp4.zip](https://github.com/unfoldingWord/translationCore/files/3907883/guest.login.mp4.zip)
If there are repos on Door43 for a user name the same as the guest's name, the problem is not seen.

**Comment by cckozie** [comment]
Looks good in 2.1.0 (ecdb97d)

**Comment by elsylambert** [comment]
Verified in 2.1.0 (6cf4a04) . Not seeing any issue with the guest login.
