### ISSUE TITLE
tC opens with blank screen when upgrading from 2.0

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6597]
2.1.0 (d0a11e7)
Restarting tC does not fix the problem.
Deleting the projects and restarting does not fix the problem.
Deleting the resources folder and restarting did fix the problem.
It continues to work after adding the projects back into the projects folder.
![image](https://user-images.githubusercontent.com/8171759/70256370-f9421680-174d-11ea-8438-3e5ef875e69f.png)
[logs.zip](https://github.com/unfoldingWord/translationCore/files/3928122/logs.zip)
[projects.zip](https://github.com/unfoldingWord/translationCore/files/3928127/projects.zip)

**Comment by PhotoNomad0** [comment]
@cckozie See if this build fixes the problem. I've seen this error sometimes when a bible resource is empty.

From the `release-vx2.1.0-test.2` branch:
[Linux build 2.1.0 (52f1f34)](https://tc-builds.door43.org/build/release-vx2.1.0-test.2/translationCore-linux-x64-2.1.0-52f1f34.deb) is ready for download.
[macOS build 2.1.0 (52f1f34)](https://tc-builds.door43.org/build/release-vx2.1.0-test.2/translationCore-macos-x64-2.1.0-52f1f34.dmg) is ready for download.
[Windows x64 build 2.1.0 (52f1f34)](https://tc-builds.door43.org/build/release-vx2.1.0-test.2/translationCore-win-x64-2.1.0-52f1f34.setup.exe) is ready for download.
[Windows x32 build 2.1.0 (52f1f34)](https://tc-builds.door43.org/build/release-vx2.1.0-test.2/translationCore-win-x32-2.1.0-52f1f34.setup.exe) is ready for download.

**Comment by cckozie** [comment]
@PhotoNomad0 I'm not seeing the failure in the test build. Looks good.

**Comment by PhotoNomad0** [comment]
Verified fix in translationCore 2.1.0 (2123be4)

**Comment by elsylambert** [comment]
Not seeing this issue in 2.1.0 (7adcd44) in my windows machine while upgrading from 2.0 to 2.1

**Comment by cckozie** [comment]
Looks good in 2.1.0 (7adcd44)
tC opens properly after the upgrade and all projects open in all tools
