### ISSUE TITLE
Cannot successfully update Hindi content (Field report)

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6605]
Field report from Russ Perry
I repeatedly am getting this error trying to download the Hindi content via content update in tC 2.0.0 on Win 10. After several failed attempts, I exited tC and removed the `hi` folder in `resources` then restarted tC and tried again. It still failed, although the `hi` folder reappeared and it appears the content successfully downloaded.
[pasted image](/user_uploads/15437/m9pxQ3KBF5_4WuNS-G8-mky5/pasted_image.png)

**Comment by PhotoNomad0** [comment]
**Note** - when I try to download latest hi in 2.1.0, It pulls down `https://cdn.door43.org/hi/tn/v13.7/tn.zip` and I see error `generateGroupsIndex() - error processing entry: bookid: col, groupDataFile: figs-abstractnoun.json, taArticleCategory: translate, groupName: null`

There may be more errors, but the import module will stop at the first.

It looks like hi_tn v13.7 was released on 12-5 and is not currently in the 2.1.0 release (which has v13.6)

**Comment by PhotoNomad0** [comment]
It looks like we are missing `/Users/blm/translationCore/resources/hi/translationHelps/translationAcademy/v10.4/translate/figs-abstractnoun.md`

**Comment by PhotoNomad0** [comment]
Note: that should be **figs-abstractnouns**

**Comment by PhotoNomad0** [comment]
~Created PR to fix content bug: https://git.door43.org/STR/hi_tn/pulls/1~

**Comment by PhotoNomad0** [comment]
Updated PR to fix content bug: https://git.door43.org/STR/hi_tn/pulls/2

**Comment by PhotoNomad0** [comment]
@elsylambert - hi_tn has been fixed in catalog - new version v13.8 downloads and installs in 2.1.0.

**Comment by elsylambert** [comment]
New hi resources are available to download and was able to download the resources successfully in  2.1.0 (7adcd44).
