### ISSUE TITLE
Improper handling of links in tN smurf bar

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6621]
2.1.0 (ed1c32c)
Issue A: Most of the links are not displayed at all

Issue B: Some just show the raw "text"
![image](https://user-images.githubusercontent.com/8171759/71482777-02ad2480-27ca-11ea-8359-e15e4ac3b69e.png)

Issue C: This is different format of raw "text"
This check does not exist in 2.1 so I could not verify whether it is a new bug or not.
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/38b4f949-abe6-423e-b7b3-6b5417cb9da8)

**Comment by elsylambert** [comment]
2.1.0(7adcd44)

<img width="1781" alt="Screen Shot 2020-02-19 at 12 49 11 PM" src="https://user-images.githubusercontent.com/51806180/74860555-df5cac80-5316-11ea-9ea7-a5b6c2d0b2c2.png">

**Comment by elsylambert** [comment]
Not seeing Issue A and B in 2.2.0 (2375ae5) but still seeing Issue C.

**Comment by da1nerd** [comment]
for issue C what is the link `../01/13/je3r` referring to?

**Comment by cckozie** [comment]
2.2.0 (02533e8)
The examples noted above (A,B, and C) are now displayed as links, but there are still some issues as noted below. 
@birchamp - Please weigh in my color suggestion in the third image below, and on Problem B.
Problem A:
The link text color needs to be a color that has more contrast to the blue background. As is it is barely visible, and virtually invisible after the link has been clicked. (See suggested)
Before clicking:
![image](https://user-images.githubusercontent.com/8171759/79891492-a8fae680-83c6-11ea-8fd3-10efdb67d940.png)
After clicking:
![image](https://user-images.githubusercontent.com/8171759/79891561-c465f180-83c6-11ea-8c1f-2b8d88b4c207.png)
Suggest a color something like this (#3FB7FA):
![image](https://user-images.githubusercontent.com/8171759/79892396-2541f980-83c8-11ea-9621-0c5f10a3052d.png)

Problem B:
Should we be showing the "UST" in this one (It is in the note):
![image](https://user-images.githubusercontent.com/8171759/79892611-6cc88580-83c8-11ea-8cfe-a1d645ce0ccf.png)

Problem C:
I don't think we should allow a line break after the "(See". This happens a lot.)
![image](https://user-images.githubusercontent.com/8171759/79894489-2294d380-83cb-11ea-8377-f51e4cc53e36.png)

Problem D:
This link is not properly displayed
![image](https://user-images.githubusercontent.com/8171759/79894871-b2d31880-83cb-11ea-9f56-7731dad5b52e.png)

**Comment by birchamp** [comment]
@cckozie this will be handled in #6351, correct?

**Comment by cckozie** [comment]
@birchamp Yes, this is now a dup as I added all of the error comments from this issue to #6351, except for the one Elsy added which was fixed by the content team. It can be closed.
