### ISSUE TITLE
Projects are missing the latest tN checks in the project.

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/translationCore#6626]
#6600
 To recreate the problem, update to the latest en and hi resources. then open this project: 
[en_alcz_tit_book.zip](https://github.com/unfoldingWord/translationCore/files/4010404/en_alcz_tit_book.zip)

This project only has titus 3:14 under Double Negatives, but latest resources have 4 verse. On the tN card, deselect everything but Figures of Speech/Double Negatives. When you launch with en GL it will only show one verse under Double Negatives. I think the problem started because this imported project started with hi as GL initially. But when GL is changed to en, the additional checks are not being copied into the menu.

**Comment by PhotoNomad0** [comment]
Verified in translationCore 2.1.0 (46a3795)

**Comment by cckozie** [comment]
Looks good in 2.1.0 (46a3795)
Able to switch back and forth between en and hi as GL. The correct checks are displayed in each case.

**Comment by elsylambert** [comment]
Works fine in 2.1.0 (46a3795). Switching between GLs does not effect the tN checks. Checks are displaying fine.
