### ISSUE TITLE
Improve the handling of long words in word bank

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6627]
2.1.0 (ed1c32c) 
The maximum card size is now set to 400 pixels. Is that the correct limit?
When we truncate the word because it's too long, do we want to supply a hover over to show the entire word? OR
Should we provide the scroll bar if there is overflow?
![image](https://user-images.githubusercontent.com/8171759/71483210-5caee980-27cc-11ea-97b3-d7e9f9451f00.png)

**Comment by da1nerd** [comment]
@cckozie I actually just noticed and fixed that issue when fixing #6633. My solution was to support breaking the word and wrapping it so it fits within the wordbank. See https://github.com/unfoldingWord/wordAlignment/pull/239.

Here's a preview:
![image](https://user-images.githubusercontent.com/166412/72522947-5b378500-3891-11ea-8fd7-2aa40afb2d88.png)

**Comment by birchamp** [comment]
@neutrinog I'm sorry, I didn't get to specify this. This should really be a hover over instead of a word wrap.

**Comment by da1nerd** [comment]
@birchamp no problem. To clarify, when you hover over the word do you want a tooltip to be displayed?

**Comment by birchamp** [comment]
Yes, the tooltip should only happen if the word is too long for the word bank width.  @cckozie aren't there other places where we're doing this?

**Comment by mannycolon** [comment]
Verified on 537283a

**Comment by elsylambert** [comment]
Verified in  2.1.0 (fbe92ce) . Tool tip works fine for longer words when hover-over. 
But the hover over stays even when the word is dragged out of the word bank for alignment and overlaps. Can hardly see the word upon dragging. See the snapshot.
![image](https://user-images.githubusercontent.com/51806180/74160094-dec36800-4bea-11ea-9262-630b4a2a5dbc.png)

**Comment by cckozie** [comment]
2.1.0 (537283a) 
ISSUE A:
On Mac, the hover over still shows after dropping the word. It doesn't disappear until the cursor is then moved. (See Elsy's comment above as it is probably worse on Windows since it appears to the right of the word rather than below it)
If possible, the hover over should disappear when the word is selected for dragging. (@neutrinog - Is that possible?)
![Screen Shot 2020-02-10 at 9 50 53 AM](https://user-images.githubusercontent.com/8171759/74165837-4c6f9400-4beb-11ea-82ae-b0abf8dbad6e.jpg)

ISSUE B:
The horizontal spacing between the words in the word bank is now excessive and reduces the number of words that can be displayed without scrolling.
![image](https://user-images.githubusercontent.com/8171759/74187901-13e3b080-4c13-11ea-8b58-bb4ede0a4807.png)

**Comment by da1nerd** [comment]
I've fixed the two issues described above in this PR https://github.com/unfoldingWord/wordAlignment/pull/254

**Comment by PhotoNomad0** [comment]
Verified in 2.2.0 (5170810)

**Comment by elsylambert** [comment]
2.2.0 (2375ae5).
Issue A: is resolved: Hover-over a long word does not overlap the other words and goes away when the word is dragged for alignment.
Issue B-is resolved: The spaces between the Words in word bank looks fine.

**Comment by cckozie** [comment]
2.2.0 (2375ae5)
Both issues have been resolved. Related issue written up in #6764
