### ISSUE TITLE
wA word bank temporarily resizes when a word is beginning to be dragged to the alignment area

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6633]
2.1.0 (46a3795) 
[6633.mp4.zip](https://github.com/unfoldingWord/translationCore/files/4016483/6633.mp4.zip)

I should have caught this when testing #5440. The screen changes as a word is picked up for alignment and then moved out of the word bank is very distracting to the user.

**Comment by PhotoNomad0** [comment]
Verified in translationCore 2.1.0 (9be0e63)

Builds are here: https://github.com/unfoldingWord/translationCore/actions/runs/32942120

**Comment by cckozie** [comment]
2.1.0 (9be0e63)
It is true that the word bank no longer resizes when words are being dragged, but that appears to be because the enhancements made in #5440 have been removed. It appears that the width of the word bank is again fixed and no longer dependent on the length of the words in it.

**Comment by da1nerd** [comment]
If the width of the wordbank should depend on the length of the words then why do we have #6627?
or do you want the wordbank to be flexible up to a maximum width and then use a tooltip for anything larger?

**Comment by cckozie** [comment]
@neutrinog Yes, the previously referenced #5440 was done to allow the word bank to expand in width, but it did not deal with words that were longer than the maximum width.
This issue was written to prevent the temporary resizing as words are selected and drug out of the word bank.

**Comment by mannycolon** [comment]
Verified on 537283a

**Comment by elsylambert** [comment]
Not seeing the issue in 2.1.0 (fbe92ce).  Word Bank expands for lengthy words. Not seeing resizing issue when the word is moved out of the word bank for alignment.

**Comment by cckozie** [comment]
Fixed in 2.1.0 (537283a)
