### ISSUE TITLE
windows builds fail to clone repository

### ISSUE THREAD

**Issue by da1nerd** [unfoldingWord/translationCore#6650]
I believe we are encountering the same issue as described in https://github.com/civetweb/civetweb/issues/812

The clone fails with this error on the windows environment

```
##[error]fatal: filename in tree entry contains backslash: 'reports\report.html'
```
The problem seems to stem from changes in git `2.24.0`. This is the version installed on the virtual environment.

See the following from the [Git 2.25 Release Notes](https://raw.githubusercontent.com/git/git/master/Documentation/RelNotes/2.25.0.txt):

```
 * An earlier update to Git for Windows declared that a tree object is
   invalid if it has a path component with backslash in it, which was
   overly strict, which has been corrected.  The only protection the
   Windows users need is to prevent such path (or any path that their
   filesystem cannot check out) from entering the index.
   (merge 224c7d70fa js/mingw-loosen-overstrict-tree-entry-checks later to maint).
```

**Comment by neutrinog** [comment]
I've opened an issue to update the version of git installed on the windows environments https://github.com/actions/virtual-environments/issues/278

**Comment by da1nerd** [comment]
I've opened an issue to update the version of git installed on windows environments https://github.com/actions/virtual-environments/issues/278

**Comment by da1nerd** [comment]
I've circumvented this problem by following the directions in https://github.com/actions/checkout/issues/116#issuecomment-574673160.

This checks out the first commit which is faster and avoids the history that's breaking git.

**Comment by da1nerd** [comment]
Now we're getting the same error as in #6648

**Comment by da1nerd** [comment]
This was fixed in https://github.com/unfoldingWord/translationCore/pull/6649

**Comment by PhotoNomad0** [comment]
Looking good
