### ISSUE TITLE
Selection invalidations doesn't always work 

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord/translationCore#6656]

**Comment by mannycolon** [comment]
Verified in translationCore 2.2.0 (c65f647)

https://github.com/unfoldingWord/translationCore/actions/runs/38810905

**Comment by cckozie** [comment]
2.2.0 (a121e92)
"Some selections are no longer valid..." alert is issued every time edits are done even if the project does not have any existing selections.

1. Import a project that has no alignments and no checks
2. Open the project in any tool
3. Make an edit to a verse
Note that the "Some selections are no longer valid..." message is displayed even though there are no selections in the project.
This was not a problem in 2.1.0 (9620a2d)  which is a build from 2 days before the one referenced in the previous comment.

**Comment by mannycolon** [comment]
Alert message

"Changes have been detected in your project which have invalidated some selections and some alignments. These verses display an icon of a broken chain next to the reference in the side menu."

**Comment by PhotoNomad0** [comment]
verified in translationCore 2.2.0 (7c41d6c)

**Comment by elsylambert** [comment]
2.2.0 (7c41d6c). Not seeing the issue regarding the Selection Invalidation alert popping up when no selection has been invalidated.

But, when the selection is invalidated, there is no Invalidation Icon on the invalidated verse.
- Open the tW tool, make a selection for a check and save.
- Open tN tool, edit the same verse , changing the text which was selected in step 1.
- Open tW, we get the selection invalidation alert, but cannot find the invalidated icon on the verse. As a result of the icon  not displayed, the filter does not bring up the invalidated verse.

**Comment by mannycolon** [comment]
> 2.2.0 ([7c41d6c](https://github.com/unfoldingWord/translationCore/commit/7c41d6c0df74ec457b8e0c44d893de9f3f9f4c93)). Not seeing the issue regarding the Selection Invalidation alert popping up when no selection has been invalidated.
> 
> But, when the selection is invalidated, there is no Invalidation Icon on the invalidated verse.
> 
> * Open the tW tool, make a selection for a check and save.
> * Open tN tool, edit the same verse , changing the text which was selected in step 1.
> * Open tW, we get the selection invalidation alert, but cannot find the invalidated icon on the verse. As a result of the icon  not displayed, the filter does not bring up the invalidated verse.

@elsylambert Isn't this related to #6675?

**Comment by elsylambert** [comment]
@mannycolon #6675 was about edit icons. For this issue, tested that when there are no invalidations there should not be the alert popping up, which is working fine. 
But when there are invalidations, the alert should be displayed (this is working fine)and the invalidation icon should appear on the verse(This is not working).

**Comment by elsylambert** [comment]
Separating the findings on Selection invalidation to #6785. 

The issue regarding the selection Invalidation alert has been resolved.

**Comment by cckozie** [comment]
2.2.0 (2375ae5) Not seeing invalidations message when no invalidations occurred.
