### ISSUE TITLE
The latest base resources are no longer in the latest build

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6659]
#6943 provided for the latest base resources to be in all builds. That feature has been broken in 2.1.0 (228ed0f)

**Comment by PhotoNomad0** [comment]
I was able to reproduce this in the latest tCore build 2.1.0 (9be0e63).  Investigating...

**Comment by PhotoNomad0** [comment]
It looks like the language and resource update scripts are not even being run on the develop builds.  for example https://github.com/unfoldingWord/translationCore/runs/416927577

![Screen Shot 2020-01-30 at 10 10 23 AM](https://user-images.githubusercontent.com/14238574/73461843-d6487300-4348-11ea-844f-cabc6ca2ffcc.png)

**Comment by PhotoNomad0** [comment]
It looks like it is due to a recent change in build system since older develop builds had this.  For example: https://github.com/unfoldingWord/translationCore/runs/382578484?check_suite_focus=true

**Comment by da1nerd** [comment]
Oops I forgot I disabled those so testing would be faster. UPDATE_RESOURCES needs to be set to true. I'll update that now.

**Comment by PhotoNomad0** [comment]
@neutrinog - yes I just saw that in main.yml.  Do you set that in `.env` or is it a github setting?

**Comment by da1nerd** [comment]
well... at the time I was thinking it would be something configurable at the repo level, but it's not. So I just edited the file and opened a PR. https://github.com/unfoldingWord/translationCore/pull/6662

**Comment by PhotoNomad0** [comment]
@neutrinog - I see it is working now.  Merged your PR.

**Comment by da1nerd** [comment]
glad you caught that before I went to bed for reals!

**Comment by PhotoNomad0** [comment]
Thank @cckozie for catching it.

**Comment by PhotoNomad0** [comment]
Working in translationCore 2.1.0 (c42350b)

Builds here:
https://github.com/unfoldingWord/translationCore/actions/runs/33041887

**Comment by cckozie** [comment]
Latest base resources (el-x-koine, en, hbo, hi) are in both 2.1.0 (e61795c) from github actions and 2.1.0 (aed42f3) from concourse.

**Comment by elsylambert** [comment]
Base resources are available with the latest build 2.1.0(aed42f3)
