### ISSUE TITLE
Windows Electronite build

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/translationCore#6660]

**Comment by da1nerd** [comment]
Here's my visual studio configuration

![Screenshot from 2020-01-31 14-15-14](https://user-images.githubusercontent.com/166412/73541105-31bb5380-4464-11ea-93b2-173262109dab.png)
![Screenshot from 2020-01-31 19-56-57](https://user-images.githubusercontent.com/166412/73541106-31bb5380-4464-11ea-810e-316d90185276.png)
![Screenshot from 2020-01-31 19-57-51](https://user-images.githubusercontent.com/166412/73541107-3253ea00-4464-11ea-84ba-74f3cfb0ff28.png)
![Screenshot from 2020-01-31 19-58-05](https://user-images.githubusercontent.com/166412/73541109-3253ea00-4464-11ea-922e-d1b3ed51a07d.png)

**Comment by da1nerd** [comment]
second attempt failed. I forgot it needed to download a different version of chromium and I didn't have my fast network connected to my computer (mobile phone). So I'll need to start again with my mobile hotspot to avoid timeouts.

**Comment by da1nerd** [comment]
# Electronite Build Instructions for Windows

These are notes I collected while compiling on my machine.

## Preparation
Install needed dependencies and configure appropriate system variables.
You will download about 16 gb of source code, so get a decent internet connection.

# Terminal Commands
The following commands must be ran in the windows command prompt.

## Fetch Code
Create working directory
```cmd
mkdir electron-gn
cd electron-gn
```

Select the electronite source
```cmd
gclient config --name "src/electron" --unmanaged https://github.com/unfoldingWord-dev/electronite
```

Sync *just* electronite
```cmd
gclient sync --with_branch_heads --with_tags --nohooks --noprehooks
```

Checkout the appropriate version of electronite
```cmd
cd src\electron
git checkout v6.0.7-graphite
cd ..\..
```

Checkout modules and run hooks to install electron patches
```cmd
gclient sync --with_branch_heads --with_tags
```

## Build Release

Configure release variant
```cmd
cd src
set CHROMIUM_BUILDTOOLS_PATH=%cd%\buildtools
gn gen out/Release --args="import(\"//electron/build/args/release.gn\") cc_wrapper=\"C:\Users\sandbox\Documents\electronite\electron-gn\src\electron\external_binaries\sccache\""
```

Build
```cmd
ninja -C out/Release electron
```

## Create Distributable

Remove debugging and symbol information
```cmd
electron\script\strip-binaries.py -d out\Release
```

Release
```cmd
ninja -C out\Release electron:electron_dist_zip
```

**Comment by da1nerd** [comment]
I was able to compile electronite 6.0.7 and upload it to https://github.com/unfoldingWord-dev/electronite/releases/tag/v6.0.7-graphite
