### ISSUE TITLE
Version Number missing from the  Win-64 Build

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/translationCore#6664]
Version Number missing from Windows-64 build for the latest v 2.1.0(c42350b).
![image](https://user-images.githubusercontent.com/51806180/73468337-a00ff100-4352-11ea-8281-5396d2f152fb.png)
![image](https://user-images.githubusercontent.com/51806180/73468439-cd5c9f00-4352-11ea-97a2-28504bc2eae6.png)

**Comment by PhotoNomad0** [comment]
Verified in Version 2.1.0 (656673d) Win 64 build:

https://github.com/unfoldingWord/translationCore/actions/runs/35030841

**Comment by elsylambert** [comment]
Not seeing this issue in v2.1.0.(656673d). Version number is available for the build.
