### ISSUE TITLE
Mac builds from github actions are bloated

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6669]
2.1.0 (e61795c) from github actions mac app is 761MB
2.1.0 (aed42f3) from concourse mac app is 499MB

**Comment by PhotoNomad0** [comment]
@cckozie - Looking at latest develop build on github (https://github.com/unfoldingWord/translationCore/actions/runs/34215452).  I see it at 289MB.  Where are you looking?

**Comment by cckozie** [comment]
@PhotoNomad0 I'm looking at the size of the actual app in that Applications folder (translationCore.app).

**Comment by PhotoNomad0** [comment]
@neutrinog - in comparing the same commit build (e61795c) between github and concourse:

| Build System        | Build Size           | Installed App Size           | app.asar size  | extracted app.asar size  |
| ------------- |-------------:|-------------:| -----:|-----:|
| concourse    | 476MB | 476MB | 375MB | 373MB |
| github actions      | 289MB      | 763MB      |   639MB|  636MB|

Looks like there is better compression in the install on github actions, but the app.asar is bloated.  Smells of extra data being included

**Comment by PhotoNomad0** [comment]
@neutrinog - In checking the disk usage of the unpacked app.asar files, it looks like we are including the `/node_modules/electron-prebuilt-compile` directory in the github actions build which is not in the concourse build:

```
blm@MacBook-Pro-2 ~ % du -ah ./tCTemp | sort -n -r | more
1016K   ./tCTemp/node_modules/electron-prebuilt-compile/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/v8_context_snapshot.bin
1016K   ./tCTemp/node_modules/electron-prebuilt-compile/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Resources/v8_context_snapshot.bin
```

**Comment by PhotoNomad0** [comment]
@neutrinog -  It looks like the node_modules directory is 369MB for concourse but 632MB for github actions build.  Maybe the dev dependencies are not being trimmed out?

**Comment by da1nerd** [comment]
I'm not certain this has anything to do with concourse or github actions. I ran the build on my mac and it's producing large builds as well.

**Comment by PhotoNomad0** [comment]
@neutrinog What size did you see after you installed the build on your Mac?

**Comment by cckozie** [comment]
2.1.1 was 685 MB
Electronite is 324MB, smaller than any previous release since 0.9.1.
