### ISSUE TITLE
Make the Edit and Comments dialogs in wA draggable

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6671]
As and aligner I would like both the Edit and Comments dialogs to be draggable so that I can easily move them to see what they are hiding, and to make it more consistent with editing in the expanded scripture pane.

**Comment by PhotoNomad0** [comment]
Verified in translationCore 2.2.0 (35226ce)

**Comment by elsylambert** [comment]
Looks good in 2.2.0 (a121e92).
