### ISSUE TITLE
The exporting project alert should not be dimmed/disabled.

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6672]
The project exporting alert is dimmed (inactive) but should not be. If the export succeeds, there isn't a problem. But if the invalidated alignments alert is displayed, the user is prevented from responding to the alert and must close tC to proceed. At that point the only way to get the project exported to usfm is to check the Do not show again checkbox when it is displayed somewhere else.
Alert after choosing to export to USFM:
![Screen Shot 2019-09-03 at 10.22.04 AM.jpg](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/c8a9a49d-2164-4f6b-ade1-548c0db9d4aa)

**Comment by cckozie** [comment]
[Luke.zip](https://github.com/unfoldingWord/translationCore/files/4216090/Luke.zip)
To replicate this problem:
1. Import the luke.usfm file in the attached zip
2. Import the Re-Import_Luke.USFM file in the attached zip giving it the same language code (hi) and the same translation id of the original project and choosing the Overwrite options. 
(This reimport takes a long time)
DO NOT CHECK THE "DO NOT DISPLAY THIS WARNING AGAIN" CHECKBOX WHEN THE ALIGNMENTS INVALIDATED ALERT IS DISPLAYED. JUST CLICK THE OK BUTTON.
3. Export the project to USFM including alignments
Note that the reset alignments alert is dimmed/disabled so it is impossible to respond to it.

![image](https://user-images.githubusercontent.com/8171759/74685859-67b34400-5195-11ea-85e0-9c5c209870e1.png)

**Comment by PhotoNomad0** [comment]
verified in translationCore 2.1.0 (8bc3450) 

Find under concourse release-v2.1.1 builds

**Comment by cckozie** [comment]
Looks good in 2.1.0 (8bc3450)

**Comment by elsylambert** [comment]
Looks good in 2.1.0 (8bc3450)

**Comment by elsylambert** [comment]
Regression on 2.1.1 (f4b4b6c). Looks good.
