### ISSUE TITLE
Edit icons are no longer displayed on verses in wA when the edits are performed in tN or tW.

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6675]
2.1.0 (537283a)
When edits are performed in wA or performed externally using import with overwrite, the edit icon is shown correctly on the verse in the menu. But when edits are performed in tN or tW (either in the scripture pane or check pane) the edit icon is not displayed in wA.
This was broken sometime between 2.1.0 (228ed0f) from 01/29 and 2.1.0 (e61795c) from 02/01.
To replicate:
Open a project in tW or tN
Edit a previously non-edited verse in either the scripture pane or check pane
Note the verse edited
Open the project in wA
Note that the edit icon is not displayed on the verse tile in the menu

**Comment by PhotoNomad0** [comment]
Verified in translationCore 2.2.0 (7de0e97)

**Comment by cckozie** [comment]
2.2.0 (a121e92) 
1. The edit icon now appears in wA when the edit is performed in the check pane of tN or tW, but it is still not displayed if the edit is performed in the scripture pane of tN or tW.
2. When the edit is performed in wA, the edit icon is not displayed in tN and tW.

**Comment by PhotoNomad0** [comment]
@cckozie - I think I see the trigger for the problem in item 1 - when you edit a verse different than the current verse, it was validating the wrong verse.

**Comment by PhotoNomad0** [comment]
Verified in translationCore 2.2.0 (69c6077)

**Comment by elsylambert** [comment]
2.2.0 (a84ebd0).
1. Edit icon now appears in wA when the edit is performed in the check pane or scripture pane of tN or tW.
2. When edit is done in wA, the edit icon does not appear in tN or in tW.

**Comment by elsylambert** [comment]
This issue still exists in  2.2.0 (a84ebd0)..When edit is done in wA, the edit icon does not appear in tN or in tW.

**Comment by PhotoNomad0** [comment]
@elsylambert - It looks like you are using an older build than  2.2.0 (69c6077).  That was the build I verified it in, and it is the latest.  I'll double check that it is working.

**Comment by elsylambert** [comment]
Verified in 2.2.0 (69c6077). Not seeing the mentioned issue. Edits icons are seen in tN and tW after the edits are made in wA.

**Comment by cckozie** [comment]
2.2.0 (69c6077) 

Edit icons are not being displayed in tN when edits are performed in tW, and vice versa. Wrote this up in a new issue #6743

**Comment by cckozie** [comment]
2.2.0 (69c6077)
Verse edits now are not persisted when the edit is performed in the scripture pane of tN or tW, and the verse being edited is not the one that is in the selected check. I believe this broken by this fix because it was working properly in the 2.2.0 (a84ebd0) build.
1. Load a project with no edits in tN or tW
2. Open the expanded scripture pane
3. Edit a verse that is not the one selected in the check
4. Select a reason code and click Save
5. Note that the edit is not persisted in the expanded scripture pane
6. Navigate to a check that includes the edited verse
7. Note that the edit icon is displayed on the check, but the edit is missing

**Comment by PhotoNomad0** [comment]
Looks like it was applying the edit to the current verse, not the edited verse.

Verified fix in translationCore 2.2.0 (7c41d6c)

**Comment by elsylambert** [comment]
2.2.0 (7c41d6c).
Edit Icon not persisted in tN when edit is made in tW and vice-versa, either from scripture pane or check pane.  However, the edited text is saved.
<img width="1486" alt="Screen Shot 2020-03-11 at 12 28 43 PM" src="https://user-images.githubusercontent.com/51806180/76441682-34c82e80-6396-11ea-84ce-b89d98473dae.png">

**Comment by PhotoNomad0** [comment]
@elsylambert -  I think what you are seeing is the same as the issue that @cckozie opened - edits between TN and TW - https://github.com/unfoldingWord/translationCore/issues/6743

**Comment by elsylambert** [comment]
2.2.0 (7c41d6c). The issue as mentioned in the last comment from koz is not happening. The edited texts are saved when edits are performed in scripture pane and  edits are persistent in the scripture pane and check pane.

**Comment by cckozie** [comment]
Edits are persisted in 2.2.0 (7c41d6c), but the original problem with the edit icons is only half fixed. 
The edit icon is now displayed in wA when edits are performed in the check pane of either tN or tW. 
When edits are performed in the scripture pane of tN or tW on a verse that is not the selected verse in the check, the edit icon is not being displayed in wA.

**Comment by PhotoNomad0** [comment]
Verified in translationCore 2.2.0 (f1fb0cd)

**Comment by cckozie** [comment]
Version 2.2.0 (f1fb0cd)
[en_ult_tit_book.zip](https://github.com/unfoldingWord/translationCore/files/4545749/en_ult_tit_book.zip)
[Tue Apr 28 2020.log.zip](https://github.com/unfoldingWord/translationCore/files/4545752/Tue.Apr.28.2020.log.zip)
I opened the project in tW, made an edit in the check pane to verse 1:6 in the accuse group, then attempted to load the project in wA.
![image](https://user-images.githubusercontent.com/8171759/80488198-954e0380-8923-11ea-9b4b-de67c580ecdb.png)

**Comment by PhotoNomad0** [comment]
@cckozie - Not see this. Where did you get this project?  It looks like the zip file already has the edit in it.

**Comment by cckozie** [comment]
@PhotoNomad0 Yes, I zipped the project after the crash. The project was imported from usfm in a previous build (April 22). I'm assuming that was the 2.1.2 build and any number of scripts had been run against it.
I went back and did a clean install of 2.1.2, imported the Titus usfm project, and loaded it in each of the tools. I then did an upgrade to 2.2 and am not seeing the problem. 
I'm going to move this to QA Watch List and do some more testing on it.

**Comment by cckozie** [comment]
Imported the original usfm file giving it a new tid, made the edit in tW, loaded in wA with no problem.
Zipped up the bad project and added it to a clean 2.1.2 install. Opens in wA with no problem.
Upgraded to 2.2 and the project opens in wA with no problems.
I copied the Matthew project into the projects folder, then again successfully loaded the Titus project in wA.
Went back to use the saved tC main folder in which I saw the problem. Upon loading the project in wA I got the critical errors screen. After restarting tC, opening the project in tW, and then opening it in wA I did see the blank screen error.
Went back to the upgraded from 2.1.2 tC folder. Copied in the Luke ULT project from the folder where I had seen the error. Now I can duplicate the error.
Started over with a new tC folder. Copied in the Luke project from the failing folder. Imported a new Titus project giving it the same tid. Project opens fine tW. Made the edit and then loaded in wA without a problem.
Copied in the Matthew project from the failing folder. Now I see the problem again.

**Comment by cckozie** [comment]
[6675 projects.zip](https://github.com/unfoldingWord/translationCore/files/4546782/6675.projects.zip)
These usfm projects were copied from the catalog about a year ago and have been used for testing ever since. I'm thinking this may have to do with wordMAP since it seems to be project interdependent.
To replicate the failure:
1. Import the Matthew project and load it in each of the tools.
2. Import the Luke project giving it the same translation id as the Matthew project and load it in each of the tools.
3. Import the Titus project giving it the same translation id as the other two projects.
4. Load the Titus project in tW selecting English as the GL
5. In the check pane, edit verse 1:6 in the accuse group and save the edit.
6. Return to the tools page
7. Load the project in wA and not the error.

**Comment by PhotoNomad0** [comment]
> 7. Load the project in wA and not the error.

@cckozie - I think you mean "note".

I think we may be running into available memory limitations.  I'm going to run some tests to see how that has changed with the updated electron.

**Comment by cckozie** [comment]
Moved the failure when opening wA to #6877

**Comment by cckozie** [comment]
2.2.0 (d2e40ce) 
Tested with edits performed in the check pane of both tW and tN
Tested with edits performed in the scripture pane of the selected verse in both tW and tN
Tested with edits performed in the scripture pane of a non-selected verse in both tW and tN
The edit icon appeared in wA on the edited verse in each case.

**Comment by elsylambert** [comment]
2.2.0 (d2e40ce).
Edit icon is displayed in wA when edits are done in tN or tW or both.  Working fine.
