### ISSUE TITLE
Error loading tW selections when checks in catalog have changed

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#6676]
### User Story

See this error in console:
![Screen Shot 2020-02-12 at 9 49 45 AM](https://user-images.githubusercontent.com/14238574/74346094-0e09de80-4d7d-11ea-9131-849d5ad412c1.png)

This happens when I select an affected project.  And the result in this case is that the category `pure, purify...` does not show up in tW.

Looks like a problem in tC getGroupsData() when check is not found, this throws an exception when dereferencing an undefined value rather than setting that selection to false:

```
              const { selections } = loadCheckData(loadPath, groupDataItem.contextId);
```

Can reproduce with this project:

[en_prct_tit_book.zip](https://github.com/unfoldingWord/translationCore/files/4198743/en_prct_tit_book.zip)

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by PhotoNomad0** [comment]
Verified in translationCore 2.2.0 (f898237)

**Comment by cckozie** [comment]
In 2.2.0 (c65f647), a previous build, I do see the error in the console and do not see the pure, purify... group in tW.
In 2.2.0 (b6b7099) I do not see the console error and do see the pure, purity... group in tW.
However, I am still seeing these console errors. 
@PhotoNomad0 Is this something that needs to be fixed?
![image](https://user-images.githubusercontent.com/8171759/74964740-886bdb80-53d9-11ea-8572-1bc0c013e90d.png)

**Comment by elsylambert** [comment]
Verified in  2.2.0 (a121e92). able to see the group- Pure, purify, purification. Not seeing the console errors.

**Comment by cckozie** [comment]
Not seeing the original problem or the "check data could not be loaded" error in 2.2.0 (69c6077)
