### ISSUE TITLE
Verse Edit indications not persisted in tW in case of multiple checks in verse

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#6678]
### User Story

If I edit Tit 1:15 I will immediately see verse edit indication:

![Screen Shot 2020-02-13 at 11.03.31 AM.png](https://images.zenhubusercontent.com/564e463c638e718c995eb353/6bfe8e3d-3544-41e0-9ff2-96d7ef61d4f1)

But when I change to another project and then change back to original project, the verse edit indication is gone:

![Screen Shot 2020-02-13 at 11.04.16 AM.png](https://images.zenhubusercontent.com/564e463c638e718c995eb353/78ea29b1-cb4d-4a6d-bf95-f3bc67d5f49d)

Only seeing this in the case of multiple checks in same verse.

As a [type of user], I want [some goal] so that [some reason].

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by PhotoNomad0** [comment]
Note:

found two issues:

- changes to group menu state are not saved
- on context ID change, should update group menu verse edit and other states from file system

**Comment by mannycolon** [comment]
Verified on a84ebd0.

**Comment by elsylambert** [comment]
Not seeing the issue in 2.2.0 (a84ebd0).  Verse edit indications are persisted in multiple checks in verse.

**Comment by cckozie** [comment]
Looks good in 2.2.0 (69c6077)
