### ISSUE TITLE
Critical errors when opening a tStudio project that has merge conflicts and one that doesn't have conflicts

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6681]
2.2.0 (c65f647) 
<img width="1440" alt="critical error" src="https://user-images.githubusercontent.com/8171759/74488927-4c8cbf80-4e89-11ea-8b83-775288906ff6.png">
[Thu Feb 13 2020.log.zip](https://github.com/unfoldingWord/translationCore/files/4202001/Thu.Feb.13.2020.log.zip)

To replicate:
1. Import [en-x-demo1_php_text_ulb.tstudio.zip](https://github.com/unfoldingWord/translationCore/files/4201994/en-x-demo1_php_text_ulb.tstudio.zip)
2. On Merge Conflicts screen choose the Version 1 option for both conflicts
3. Load the project in wA
Critical error screen in displayed

I'm also seeing the same failure on this project even though it does not have any merge conflicts:
[en_1th_text_reg.tstudio.zip](https://github.com/unfoldingWord/translationCore/files/4202006/en_1th_text_reg.tstudio.zip)

**Comment by cckozie** [comment]
Not seeing the problem in preliminary build 2.2.0 (b8a147d)

**Comment by mannycolon** [comment]
Verified on d2b808b.

**Comment by elsylambert** [comment]
2.2.0 (d2b808b)
The project opens fine in wA and tW. when I opened it in tN and navigated through the categories, I found the critical error screen in one of the category.
<img width="1792" alt="Screen Shot 2020-02-21 at 10 58 31 AM" src="https://user-images.githubusercontent.com/51806180/75050850-d1d02f80-549a-11ea-88c3-5ab32467f355.png">

**Comment by cckozie** [comment]
I see the error in 2.2.0 (d2b808b), but I am not seeing the error when running the latest, 2.2.0 (a121e92)

**Comment by elsylambert** [comment]
Not seeing the critical error message in  2.2.0 (a121e92) .
