### ISSUE TITLE
Critical error when opening a project from Door43

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6682]
2.2.0 (c65f647) 
<img width="1440" alt="critical error2" src="https://user-images.githubusercontent.com/8171759/74487664-af7c5780-4e85-11ea-8a3d-49d755bb39c4.png">
[Thu Feb 13 2020.log 2.zip](https://github.com/unfoldingWord/translationCore/files/4201926/Thu.Feb.13.2020.log.2.zip)

To replicate:
1. Import https://git.door43.org/qa99/abu_tit_reg
2. Load the project in tW
Critical error screen in displayed

**Comment by cckozie** [comment]
2.2.0 (f898237) 
Here is a similar problem:
[projects.zip](https://github.com/unfoldingWord/translationCore/files/4207226/projects.zip)
1. Unzip the projects into the projects folder
2. Restart tC
3. Select the Acts project and load it into wA
4. Return to the Projects screen
5. Select the Titus project and load it into wA
Note the Critical error screen. The Titus project will correctly load in wA if the Acts project isn't loaded in wA first.
<img width="1239" alt="critical error3" src="https://user-images.githubusercontent.com/8171759/74575108-62fb4f80-4f4b-11ea-8cb9-a932a383f406.png">

**Comment by cckozie** [comment]
Not seeing the problem in preliminary build 2.2.0 (b8a147d)

**Comment by mannycolon** [comment]
Verified on d2b808b.

**Comment by elsylambert** [comment]
Looks good in 2.2.0 (d2b808b). Not seeing the Critical error screens.

**Comment by cckozie** [comment]
2.2.0 (b6b7099) Not seeing any problems in either of the 2 described scenarios.
