### ISSUE TITLE
Code displayed in the Selection pane in tN for a Hindi Project

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/translationCore#6686]
This has resurfaced in 2.2.0 (f898237).
Here is the Project:
[hi_irv_act_book.zip](https://github.com/unfoldingWord/translationCore/files/4219874/hi_irv_act_book.zip)

1. [objet].[Object]... shown in the "Please Select translation for:"
![Screen Shot 2020-02-18 at 9.54.34 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/1e0debec-a12a-4b1e-9971-976598e580ea)
2. Help article link is displayed in the smurf bar #6687

**Comment by PhotoNomad0** [comment]
This is the check that is causing problems:
```
{
  "occurrenceNote": "\"इस \"\"बपतिस्मा\"\" संज्ञा का अनुवाद क्रिया के रूप में किया जा सकता है। सम्भावित अर्थ: 1) \"\"उस समय से जब यूहन्ना ने यीशु को बपतिस्मा दिया था\"\" या 2) \"\"उस समय से जब यूहन्ना ने लोगों को बपतिस्मा दिया था\"\" (देखें: [भाववाचक संज्ञा](rc://hi/ta/man/translate/figs-abstractnouns))\"",
  "reference": {
    "bookId": "act",
    "chapter": 1,
    "verse": 22
  },
  "tool": "translationNotes",
  "groupId": "figs-abstractnouns",
  "quote": [
    {
      "word": "ἀρξάμενος",
      "occurrence": 1
    },
    {
      "word": "ἀπὸ",
      "occurrence": 1
    },
    {
      "word": "τοῦ",
      "occurrence": 1
    },
    {
      "word": "βαπτίσματος",
      "occurrence": 1
    },
    {
      "word": "Ἰωάννου",
      "occurrence": 1
    }
  ],
  "quoteString": "ἀρξάμενος ἀπὸ τοῦ βαπτίσματος Ἰωάννου",
  "glQuote": "beginning from the baptism of John",
  "occurrence": 1
}
```

**Comment by PhotoNomad0** [comment]
@elsylambert  - think I found the problem - the original language words for the check are not all tagged in the hi bibles for that verse ("irv", "ulb", "udb"), then tCore is falling back to display the original language quote instead (which is an array in this case and shows up as an array of objects).  It should be giving a content error message instead.

**Comment by PhotoNomad0** [comment]
Verified in translationCore 2.2.0 (36e5ecd)

**Comment by cckozie** [comment]
I'm seeing the content error message on this check in 2.2.0 (a121e92)

**Comment by elsylambert** [comment]
Not seeing the issue in 2.2.0 (a121e92). Getting content error message for the check.
