### ISSUE TITLE
Link is displayed in the smurf bar in tN

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/translationCore#6687]
1. For Hindi Project as reported in #6686
2. In a Titus Project, under abstract Noun. See below.
![Screen Shot 2020-02-18 at 10.12.04 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/759655ed-1921-42b9-ba7e-c96901c61aad)

**Comment by cckozie** [comment]
@elsylambert - I think this is the same problem as in Issue C on #6621. If you agree, please reference this one there and then label this as a duplicate and close it.

**Comment by elsylambert** [comment]
Duplicate of #6621
