### ISSUE TITLE
Duplicated and invalidated checks in tW

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6689]
From Larry: (2.1.0 release)
Any idea why I still have three invalidated tW checks in the Titus ULT project? They are doubled, and won't let me select anything. All the files appear to be right, but I can't make these work.

[en_ult_tit_book.zip](/user_uploads/15437/iqzfxgLD7NGCnDELkxl5Llk0/en_ult_tit_book.zip)

After doing some research on this I discovered that there were duplicate checks in the json files in /translationCore/projects/en_ult_tit_book/.apps/translationCore/index/translationWords/tit.
I deleted the duplicates there and gave the 'fixed' project to Larry.
I made several attempts to replicate the problem using a project with no previous tW selections, but was not able to recreate the problem. 
Project with duplicate tW checks removed. [en_ult_tit_book-twfixes.zip](https://github.com/unfoldingWord/translationCore/files/4228146/en_ult_tit_book-twfixes.zip)

**Comment by birchamp** [comment]
Closing this issue as it is only happening for this specific project. If we see it happen again we will re-address it.

**Comment by cckozie** [comment]
The first referenced project no longer exists in github so I cannot test in 3.0
