### ISSUE TITLE
The 2.1.1 builds are still showing 2.1.0 in the install files and the running app

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6692]
Concourse: From the release-v2.1.1 branch:
Linux build 2.1.0 (8bc3450) is ready for download.
macOS build 2.1.0 (8bc3450) is ready for download.
Windows x64 build 2.1.0 (8bc3450) is ready for download.
Windows x32 build 2.1.0 (8bc3450) is ready for download.

![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/2baf111e-5d21-4151-bcfc-8b7125c65733)

**Comment by cckozie** [comment]
Looks correct in 2.1.1 (17b9e26)

**Comment by elsylambert** [comment]
Working fine. 2.1.1 (17b9e26)
