### ISSUE TITLE
tN is reporting content problems on checks that contain ellipsis

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6695]
2.1.0 (7adcd44)
To replicate:
Delete or rename the main translationCore folder to start with a clean install of 2.1
1. Import this project [57-TIT.usfm.zip](https://github.com/unfoldingWord/translationCore/files/4231456/57-TIT.usfm.zip)
2. Load the project in tN
3. Navigate to the Doublet group
4. Note that the content problem dialog is displayed on the first check for verse 1:8 and the check on verse 2:8
5. Navigate to the How to translate names group
6. Note that the content problem dialog is displayed on the checks for verse 3:12 and 3:13
7. Update the English and Greek resources to the latest
8. Repeat steps 1-7 giving the project a different translation ID and note that the same content problems are reported EXCEPT for the check on 2:8

Manny has determined via #6693 that the problem is in the tsv parser when checks include ellipsis.

**Comment by cckozie** [comment]
@mannycolon 
In the latest, 2.1.1(17b9e26), I'm seeing ugnt versions 0.8 and 0.12. The released version of 2.1.0 (and the previous build, 2.1.1 (5ff4779)) both have ugnt version 0.9 bundled in them. 
(UPDATE: 0.8 is needed by Hindi tN and 0.12 for English tN. 0.9 should not be needed, or if used, should remain on the system after the upgrade)

**Comment by mannycolon** [comment]
Verified on 17b9e26

**Comment by elsylambert** [comment]
Looks good in 2.1.1 (17b9e26).
