### ISSUE TITLE
Need to update copyright notice on the Windows installer

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6718]
The installer shows 2017-2018. It should be 2017-2020
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/7f4fe806-2065-49d6-8582-d0cc41dd9459)

**Comment by da1nerd** [comment]
The license here is pulled from the repository LICENSE.md file. We just need to keep that file up to date. Easy fix :)

**Comment by PhotoNomad0** [comment]
fixed in translationCore 2.2.0 (4496c12)

**Comment by elsylambert** [comment]
Looks good in 2.2.0 (d786804). Year has been changed to 2017-2020.
![image-1589830738356](https://user-images.githubusercontent.com/51806180/82252870-d54e4800-991d-11ea-8075-fa28f973223b.png)
