### ISSUE TITLE
Highlight Selection methods not compatible

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#672]
As a user, I want to be able to switch the Highlight selection mode, so that I can determine which method is best for me.

Words selected in click to select are not shown as selected when in drag to select mode and vice versa. There needs to be a unified way we save these highlighted pieces in the store.

**Comment by EllDoubleYew** [comment]
I want to make sure I understand this story well: Is this on the fact that the first time you go into settings the app will say you are already in drag to select when you are really in click to select?

This would be a quick fix but a temporary workaround would be:

1. Click "Click to Select"
2. Click "Drag to Select" it should look how it did originally at this point
3. Change checks.

This will always change the selection method.

**Comment by klappy** [comment]
This issue is more about highlighting text using one method. Then switch highlight methods, the previous selected text using the other method is no longer visible for any checks done in the previous highlighting method.
