### ISSUE TITLE
Click to Highlight not working in some verses

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#673]
As a user, I am unable to click on some words to highlight them.

Here is one example where I could click "deare" but not "brethren":
<img width="1280" alt="screen shot 2017-02-08 at 11 13 42 am" src="https://cloud.githubusercontent.com/assets/118073/22788361/9c143ff4-eead-11e6-9f68-6ac0facf27c1.png">

**Comment by klappy** [comment]
TypeError: Cannot read property 'length' of undefined
1 File "/Users/klappy/GitHub/translationCore/tC_apps/translationWords/Container.js" line 112 col 8 in Container.addSelectedWord
2 File "/Users/klappy/GitHub/translationCore/tC_apps/translationWords/Container.js" line 106 col 12 in Container.updateSelectedWords

**Comment by klappy** [comment]
#637

**Comment by mannycolon** [comment]
I tried to highlight the target text and could not highlight all the desired words.

BTW - it is painful to click on each word instead of using a click-hold-drag action.

https://youtu.be/oR3h-I78TXM
