### ISSUE TITLE
Resolve various console warnings/errors

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#6733]
Resolve warnings in console:

- DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
- that react life cycle methods are deprecated.

**Comment by PhotoNomad0** [comment]
Some errors:

1.   Not seeing this anymore
![Screen Shot 2020-05-14 at 7 17 27 AM](https://user-images.githubusercontent.com/14238574/81928377-27583c00-95b3-11ea-9a64-5adc7e4afd76.png)

2.  Looks like webpacked font not found.  Not seeing this anymore
![Screen Shot 2020-05-14 at 7 21 33 AM](https://user-images.githubusercontent.com/14238574/81928627-9170e100-95b3-11ea-8b55-f4289fdf10a9.png)

3. Not seeing this anymore
![Screen Shot 2020-05-14 at 7 23 15 AM](https://user-images.githubusercontent.com/14238574/81928790-d85ed680-95b3-11ea-827a-c34fd84559a0.png)

4. Not seeing this anymore
![Screen Shot 2020-05-14 at 7 59 49 AM](https://user-images.githubusercontent.com/14238574/81932036-0e528980-95b9-11ea-9c98-376256b03638.png)

5. fixed 
![Screen Shot 2020-05-15 at 6 10 26 AM](https://user-images.githubusercontent.com/14238574/82039409-ee7f9c00-9672-11ea-9415-39ac42ac7e98.png)

6. Not seeing this anymore
![Screen Shot 2020-05-15 at 6 27 15 AM](https://user-images.githubusercontent.com/14238574/82040831-33a4cd80-9675-11ea-8985-9245923ebd79.png)

7. Not seeing this anymore
![Screen Shot 2020-05-15 at 6 44 33 AM](https://user-images.githubusercontent.com/14238574/82042280-a020cc00-9677-11ea-9563-395b51c0db42.png)

8. first time a tool is shown (tN and tW only):
![Screen Shot 2020-06-08 at 10 45 21 AM](https://user-images.githubusercontent.com/14238574/84044188-3beee080-a975-11ea-8689-5d67eccdcaf3.png)

**Comment by PhotoNomad0** [comment]
Verified in translationCore 3.0.0 (6f6cd79)

**Comment by cckozie** [comment]
Still seeing this one in 3.0.0 (318d196) when opening tN or tW after a clean install. I don't know how to cause the other ones listed. I think it's good enough.
![image](https://user-images.githubusercontent.com/8171759/84317956-48b93300-ab33-11ea-9935-9156d4ad31ab.png)
