### ISSUE TITLE
Improve performance of loading tCore Locales (In other words, make tC startup time faster)

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#6734]
**Note:** Only seeing seeing the slow performance when redux-logger is enabled.

Loading locales is much slower in latest electron when redux-logger is enabled. Need to determine cause.

~Seems to be due to using requires() to load `nonTranslatable.js`.  The requires() seems to be very slow compared to reading a json file.  Maybe either convert to json file or do an import.~ <= this fix was made for tools but does not apply to tCore

**Comment by PhotoNomad0** [comment]
Blocked by #6732

**Comment by cckozie** [comment]
2.2.0 (9ea8fdb) starts in 3 - 4 seconds. Not seeing any change in  2.2.0 (4496c12). I think this was related to startup time for dev builds. If that is the case we need Bruce to weigh in on whether it works as expected. Bruce says it is acceptable as is.

**Comment by cckozie** [comment]
@elsylambert - Please test this on Windows to ensure that the startup time has not increased.

**Comment by elsylambert** [comment]
On my slow windows machine-
First time start up time for the builds:-
2.1.2- 9:47.00
Upgraded from 2.1.2 to 2.2.0(51afa6e).
Time to start up 2.2.0(51afa6e)-14:41.17

@cckozie It has slowed down substantially in 2.2.0.

**Comment by cckozie** [comment]
Windows machine;
2.2.0 (b749003) - 8 seconds on latest build
2.2.0-(d2e40ce) - 14 seconds on build from 4/29/20

**Comment by cckozie** [comment]
Additional information for the first startup on a clean install (on Mac):
2.2.0 (b749003) - 94 seconds, resources folder is 971MB
2.1.2 (44c92e9) - 91 seconds, resources folder is 772MB
Additional information for the first startup on a clean install on WIndows:
2.2.0 (b749003) - 195 seconds with virus scan stopped
2.1.2 (44c92e9) - 295 seconds with virus scan stopped
2.2.0 (b749003) - 225 seconds with virus scan running

**Comment by elsylambert** [comment]
First Startup:
2.1.2- 00:55.16
After upgrade to 2.2.0 (b749003)- 6:02.33
First Startup:
2.2.0 (b749003)- 00:10.13
