### ISSUE TITLE
The "There is a problem with the content for this check" alert is wrongly displayed when loading a project in tW

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6739]
2.2.0 (69c6077) 
[projects.zip](https://github.com/unfoldingWord/translationCore/files/4307492/projects.zip)
[6739.mp4.zip](https://github.com/unfoldingWord/translationCore/files/4307499/6739.mp4.zip)
1. Unzip the projects.zip file into your projects folder
2. Load the Titus project in tW
3. Navigate to verse 1:15 in the group "pure"
4. Navigate to verse 2:5 in the group "pure"
5. Return to the Projects page
6. Load the Ruth project in tW
7. Note that the "problem with content" alert is displayed on the displayed check
8. Navigate to a different check in the same group
9. Navigate back to the initial check seen in step 7
10. Note that the content error alert is not displayed
11. Return to the Projects page
12. Load the Titus project in tW
13. Note that the "problem with content" alert is displayed on the displayed check
14. Navigate to a different check in the same group
15. Navigate back to the initial check seen in step 13
16. Note that the content error alert is not displayed
Seeing this in the console log:
![image](https://user-images.githubusercontent.com/8171759/76233128-b765b800-61f5-11ea-9623-08d7043214fe.png)

**Comment by elsylambert** [comment]
Not seeing this problem in 2.2.0 (d8fd543).

**Comment by cckozie** [comment]
Dup of #6852
