### ISSUE TITLE
Edit icons are not always displayed on edited verses

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6743]
2.2.0 (69c6077) 
SCENARIO A: Edit icons are not displayed on verses in tN when edits are made in the check pane of tW
1. Load a project in tW (I used a Titus project)
2. Edit a non-edited verse in the check pane (I edited 1:6 in the 'accuse' group)
3. Note that the edit icon does appear on the verse
4. Load the project in wA
5. Note that edit icon does appear on the verse
6. Load the project in tN
7. Navigate to the edited verse (1:6 is in the 'Assumed Knowledge' group in the Titus project)
8. Note that the edit icon does NOT appear on the verse

SCENARIO B: Edit icons are not displayed on verses in tW when edits are made in the check pane of tN
I tested making an edit in verse 2:1 in the 'Assumed Knowledge' group of tN

SCENARIO C: Edit icons are not displayed on verses in tN when edits are made in the scripture pane of tW

SCENARIO D: Edit icons are not displayed on verses in tW when edits are made in the scripture pane of tN

**Comment by BincyJ** [comment]
Functionalitybworking but UI missing - medium priority

**Comment by PhotoNomad0** [comment]
Verified in 2.2.0 (690092a), working:
- [ ] Scenario A
- [ ] Scenario B
- [ ] Scenario C
- [ ] Scenario D

**Comment by PhotoNomad0** [comment]
Note:
In reviewing develop build Version 2.2.0 (9ea8fdb), see hang opening rev ult.
[en_ult_rev_book.zip](https://github.com/unfoldingWord/translationCore/files/4628014/en_ult_rev_book.zip)

It is hanging while processing 405 edited verses.  So suspect it is breakage from https://github.com/unfoldingword/translationcore/issues/6791

**Comment by PhotoNomad0** [comment]
Seeing error on verse edit:
```
08:02:28 GMT-0400 (Eastern Daylight Time) ERROR: v2.2.0 (9ea8fdb): projectSaveLocation is undefined 
08:02:28 GMT-0400 (Eastern Daylight Time) ERROR: v2.2.0 (9ea8fdb): saveData(): savePath is undefined or path does not exists undefined 
```

**Comment by PhotoNomad0** [comment]
Verified in translationCore 2.2.0 (4496c12)

**Comment by cckozie** [comment]
2.2.0 (d786804) - Edit icons appear to be working correctly when the edits are performed in one of the tools, but not when the edits are performed via import with overwrite.
[58-PHM-edits.usfm.zip](https://github.com/unfoldingWord/translationCore/files/4647427/58-PHM-edits.usfm.zip)

1. Import https://git.door43.org/TC_SAVE/en_edit_phm_book
2. Import the attached file giving it 'en' for language code and 'edit' for translation ID and choosing the Overwrite options. (The overwrite file has edits to verses 1:1, 1:2, 1:3, 1:13, 1:25
3. Open the project in tN and tW and note that the edit icon is not displayed on any of the verses in in step 2.

**Comment by PhotoNomad0** [comment]
Verified fix is in Version 2.2.0 (4920def)

**Comment by elsylambert** [comment]
Looks good in 3.0.0 (a444d5f) . Edit icon is displayed on verse in a tool when edits are done in another. Edit icon is working fine on the project that was overwritten.

**Comment by cckozie** [comment]
Seeing the edit icons as expected in 2.2.0 (4920def)
