### ISSUE TITLE
Current verse failure switching between books

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#6762]
### User Story

See this error in develop after I open en_ust_jdg_book, launch WA, edit 6:27, Then open a Titus project and launch WA.  It looks like the current verse (contextId) is not being updated (or maybe not soon enough) when project changes, so it was trying to open chapter 6:27 in Titus.

![Screen Shot 2020-03-13 at 10 05 37 AM](https://user-images.githubusercontent.com/14238574/76628103-9f9e7480-6512-11ea-94ac-43f9bcb00ac8.png)

As a [type of user], I want [some goal] so that [some reason].

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by cckozie** [comment]
Added this as a scenario on #6758
