### ISSUE TITLE
Later cleanup tasks

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#6765]
- review main.js commented sections to see if still needed.
- in main.js, `ipcMain.on('open-helper'...` for showing URL -- determine if it works or is even still used.
- currently using patch file `ospath-extra` need to investigate if there is a better approach.
- look for other usage of process.env in tCore to see if they need to use remote process.env.

**Comment by birchamp** [comment]
@PhotoNomad0 please review this issue
