### ISSUE TITLE
Remove webpack from modules to improve debugging

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#6771]
Currently debugging is very slow in checking-tool-wrapper and tc-ui-toolkit due to webpack.

Now that all of tCore will be webpack'd, we no longer need the above modules to be webpacked.  So it would be good to update the scripts to no longer run webpack before publishing the checking-tool-wrapper and tc-ui-toolkit.

**Comment by mannycolon** [comment]
@PhotoNomad0 Is this issue still needed?

**Comment by PhotoNomad0** [comment]
Implemented in Version 2.2.0 (b749003).  Should not see any changes in tC.

**Comment by cckozie** [comment]
Should there be an estimate on this issue?
