### ISSUE TITLE
Integrate Electronite into tC

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/translationCore#6787]
### User Story

As a [type of user], I want [some goal] so that [some reason].

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by PhotoNomad0** [comment]
in translationCore 2.2.0 (17ae343)

**Comment by cckozie** [comment]
Testing is blocked until we are able to render complex scripts.

**Comment by cckozie** [comment]
There appears to be the correct rendering of at least some of the Burmese characters.
![image](https://user-images.githubusercontent.com/8171759/82273748-eca02c00-9943-11ea-9b4f-1288b2ca6f1e.png)
