### ISSUE TITLE
Bundle "Git" with tC installer

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#679]
As a user, I want to be able to install tC and it work without having to figure out how to install Git as well. 

It took some time to get the users machines up and running because almost all of them did not have Git installed.

tS has it bundled and having them install it first was the easiest way to get them up and running.

**Comment by klappy** [comment]
@ihoegen: Any ideas on this one?

**Comment by ihoegen** [comment]
@klappy Just figured out how to check if they have git installed. Currently
working on packaging an installer for Windows, and will get the Mac ones
next.
