### ISSUE TITLE
Critical Error screen when working on wA tool

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/translationCore#6790]
2.2.0 (2375ae5).
Got two critical error screens on two different projects, both while moving down the chapters in wA.
Here is the project:
[hi_irv_act_book.zip](https://github.com/unfoldingWord/translationCore/files/4382399/hi_irv_act_book.zip)
 

<img width="1792" alt="Screen Shot 2020-03-25 at 1 05 18 PM" src="https://user-images.githubusercontent.com/51806180/77565636-e7ba8100-6e9a-11ea-9c48-8a4d960b1a57.png">
Here is the second project:
[en_newl_rev_book.zip](https://github.com/unfoldingWord/translationCore/files/4382431/en_newl_rev_book.zip)

<img width="1792" alt="Screen Shot 2020-03-25 at 12 57 32 PM" src="https://user-images.githubusercontent.com/51806180/77565582-cf4a6680-6e9a-11ea-9d6c-5b2c086aca5f.png">

**Comment by elsylambert** [comment]
Here is the log file:
[Wed Mar 25 2020.log.zip](https://github.com/unfoldingWord/translationCore/files/4382493/Wed.Mar.25.2020.log.zip)

**Comment by cckozie** [comment]
Seeing the same console error and error screen in 2.2.0 (02533e8) using these 2 projects
1. [en_test_act_book (1).zip](https://github.com/unfoldingWord/translationCore/files/4506382/en_test_act_book.1.zip)
2. [en_ult_tit_book.zip](https://github.com/unfoldingWord/translationCore/files/4506384/en_ult_tit_book.zip)

**Comment by elsylambert** [comment]
Got critical error screen in wA tool.
<img width="1904" alt="Screen Shot 2020-04-22 at 4 40 49 PM" src="https://user-images.githubusercontent.com/51806180/80031886-5568c580-84b8-11ea-9ba8-009753342481.png">
[en_prct_tit_book.zip](https://github.com/unfoldingWord/translationCore/files/4518929/en_prct_tit_book.zip)

**Comment by cckozie** [comment]
These are merged here from #6758 
2.2.0 (7c41d6c) 
SEE ALSO: #5960 and #6435
SCENARIO 1:
[projects.zip](https://github.com/unfoldingWord/translationCore/files/4325345/projects.zip)
1. Unzip the attached file into the projects folder
2. Select the Acts project and load it in wA
3. Navigate to verse 19:41
4. Return to the projects page
5. Select the Titus project and load it in wA
Note the critical errors screen
[Thu Mar 12 2020.log.zip](https://github.com/unfoldingWord/translationCore/files/4325364/Thu.Mar.12.2020.log.zip)

![image](https://user-images.githubusercontent.com/8171759/76543800-04939500-6455-11ea-96b9-8141f7fadcc8.png)

SCENARIO 2: (I think it is the same bug as above)
1. Import https://git.door43.org/tc01/en_1th_reg from Door43
2. Load it in wA
3. Navigate to verse 5:3
4. Return to Projects screen
5. Import https://git.door43.org/tc02/English_tit from Door43
6. Load it in wA
Note the Critical Error screen
[Thu Mar 12 2020.log](https://github.com/unfoldingWord/translationCore/files/4326525/Thu.Mar.12.2020.log)

![image](https://user-images.githubusercontent.com/8171759/76565848-885f7880-6479-11ea-9e00-140f64fe37ef.png)

This SCENARIO is from #6762
See this error in develop after I open en_ust_jdg_book, launch WA, edit 6:27, Then open a Titus project and launch WA.  It looks like the current verse (contextId) is not being updated (or maybe not soon enough) when project changes, so it was trying to open chapter 6:27 in Titus.

![Screen Shot 2020-03-13 at 10 05 37 AM](https://user-images.githubusercontent.com/14238574/76628103-9f9e7480-6512-11ea-94ac-43f9bcb00ac8.png)

SENARIO 4:
1. Import this fully aligned project
2. Export the project to USFM without alignments
3. Open the exported file in an editor
4. Delete all of the text for 1:5
5. Import the edited USFM file giving it the same language and translation id as used in step 1
6. Choose the overwrite options on the alerts
7. Load the project in wA
8. Note the critical errors screen 
![image](https://user-images.githubusercontent.com/8171759/77563784-b6888380-6e8f-11ea-89ee-a28135dd09d3.png)

**Comment by cckozie** [comment]
Moved here from #6858
2.2.0 (02533e8) .

Got critical error screen when traversing through the checks in tN. This project was opened and looked fine in 2.1.1 and 2.1.2.
<img width="1904" alt="Screen Shot 2020-04-06 at 9 36 28 AM" src="https://user-images.githubusercontent.com/51806180/79778171-55c15f00-8306-11ea-8284-54d8d518b6c3.png">

Here is the project:
[hi_test_tit_book.zip](https://github.com/unfoldingWord/translationCore/files/4504908/hi_test_tit_book.zip)

After I got the critical error screen, I am not able to open tN at all even after restarting tC. When tN is launched, it throws the Critical error screen.

Resources: tN-v13.8
IRV- v7
Here is the log file: 
[Mon Apr 20 2020.log.zip](https://github.com/unfoldingWord/translationCore/files/4504970/Mon.Apr.20.2020.log.zip)

**Comment by PhotoNomad0** [comment]
> Moved here from #6858
> 2.2.0 ([02533e8](https://github.com/unfoldingWord/translationCore/commit/02533e84f8fa305fe4d768dddba7acfa85164e02)) .
> 
> Got critical error screen when traversing through the checks in tN. This project was opened and looked fine in 2.1.1 and 2.1.2.
> <img alt="Screen Shot 2020-04-06 at 9 36 28 AM" width="1904" src="https://user-images.githubusercontent.com/51806180/79778171-55c15f00-8306-11ea-8284-54d8d518b6c3.png">
> 
> Here is the project:
> [hi_test_tit_book.zip](https://github.com/unfoldingWord/translationCore/files/4504908/hi_test_tit_book.zip)
> 
> After I got the critical error screen, I am not able to open tN at all even after restarting tC. When tN is launched, it throws the Critical error screen.
> 
> Resources: tN-v13.8
> IRV- v7
> Here is the log file:
> [Mon Apr 20 2020.log.zip](https://github.com/unfoldingWord/translationCore/files/4504970/Mon.Apr.20.2020.log.zip)

In testing Joel's new fix, looks like this crash will be fixed with the same fix as https://github.com/unfoldingWord/translationCore/issues/6858

**Comment by PhotoNomad0** [comment]
> These are merged here from #6758
> 2.2.0 ([7c41d6c](https://github.com/unfoldingWord/translationCore/commit/7c41d6c0df74ec457b8e0c44d893de9f3f9f4c93))
> SEE ALSO: #5960 and #6435
> SCENARIO 1:
> [projects.zip](https://github.com/unfoldingWord/translationCore/files/4325345/projects.zip)
> 
> 1. Unzip the attached file into the projects folder
> 2. Select the Acts project and load it in wA
> 3. Navigate to verse 19:41
> 4. Return to the projects page
> 5. Select the Titus project and load it in wA
>    Note the critical errors screen
>    [Thu Mar 12 2020.log.zip](https://github.com/unfoldingWord/translationCore/files/4325364/Thu.Mar.12.2020.log.zip)
> 
> ![image](https://user-images.githubusercontent.com/8171759/76543800-04939500-6455-11ea-96b9-8141f7fadcc8.png)
> 
> SCENARIO 2: (I think it is the same bug as above)
> 
> 1. Import https://git.door43.org/tc01/en_1th_reg from Door43
> 2. Load it in wA
> 3. Navigate to verse 5:3
> 4. Return to Projects screen
> 5. Import https://git.door43.org/tc02/English_tit from Door43
> 6. Load it in wA
>    Note the Critical Error screen
>    [Thu Mar 12 2020.log](https://github.com/unfoldingWord/translationCore/files/4326525/Thu.Mar.12.2020.log)
> 
> ![image](https://user-images.githubusercontent.com/8171759/76565848-885f7880-6479-11ea-9e00-140f64fe37ef.png)

@cckozie @elsylambert - for these two scenarios, it looks like in WA the current contextID is not being cleared out when we change projects.

**Comment by PhotoNomad0** [comment]
Verified in translationCore 2.2.0 (236380d)

**Comment by cckozie** [comment]
2.2.0 (d2e40ce) 
I'm still seeing the problem after loading a project that has fewer chapters than the one previous loaded in wA.
1. Load the Acts project attached to the first comment in wA
2. Navigate to the last chapter (if not already there)
3. Load the Revelation project referenced in the first comment in wA
4. Note that even though Revelation only has 22 chapters, the menu shows 28 chapters
5. Click on one of the chapters greater than 22. Note the critical error screen.

**Comment by elsylambert** [comment]
2.2.0 (d2e40ce). Seeing the same behaviour as @cckozie. Every time a project with a less chapter is opened after a project having more chapters, wA displays extra chapters in the Menu and clicking on it throws error screen.
-Opened a Mathew project (28 chapters) in wA.
- Go to Projects page, open any other project which has less than 28 chapters, say Titus.
- wA in Titus shows 28 chapters in Menu and crashes when clicked on the extra chapter.
- Open any project, it always displays 28 chapters in the Menu, until tC is restarted. 
<img width="1792" alt="Screen Shot 2020-04-29 at 5 24 19 PM" src="https://user-images.githubusercontent.com/51806180/80648526-4f399280-8a3e-11ea-96a2-0c49c9b5accd.png">

**Comment by PhotoNomad0** [comment]
Verified chapters reset in translationCore 2.2.0 (ff3cb3e)

**Comment by elsylambert** [comment]
2.2.0 (ff3cb3e). Not seeing the critical error screen and the chapters for each project are displayed correctly.

**Comment by cckozie** [comment]
Looks good in 2.2.0 (ff3cb3e)
