### ISSUE TITLE
tC sometimes appears to lose Greek words when unmerging them

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6798]
This is a problem in both 2.1.1 and 2.2
This was reported by Larry at https://unfoldingword.zulipchat.com/#narrow/stream/207527-wg-tc/topic/Small.20bugs/near/192317140

[45-ACT.usfm.zip](https://github.com/unfoldingWord/translationCore/files/4405646/45-ACT.usfm.zip)

[issue 6798.mp4.zip](https://github.com/unfoldingWord/translationCore/files/4405647/issue.6798.mp4.zip)

![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/ed6ec089-9715-48e0-bacd-0abfe79bb46b)

After unmerging this error is displayed in the console
![image](https://user-images.githubusercontent.com/8171759/77964091-22aa2380-72a4-11ea-8fac-8416a0ad8292.png)

**Comment by neutrinog** [comment]
found the problem. Some changes were made to the renderer some time last year that slightly introduced this bug.

**Comment by da1nerd** [comment]
This is happening during the `WA:INSERT_RENDERED_ALIGNMENT`. The before state looks right but afterward it's wrong.

The alignment data itself actually looks ok (until the effect gets propagated during the next change). The rendering of the alignments is failing at some point.
![image](https://user-images.githubusercontent.com/166412/80585128-ffa69700-8a3c-11ea-9506-0c80ea03dc5b.png)

I still need to dig through the renderer to see what's happening.

**Comment by da1nerd** [comment]
i was able to create a specific unit test that isolates this bug. Fixing this should now be trivial.

**Comment by PhotoNomad0** [comment]
Verified above issue is working in translationCore 2.2.0 (17ae343)

**Comment by cckozie** [comment]
Not seeing the specific problem described in 2.2.0 (64bf0a5)

**Comment by elsylambert** [comment]
2.2.0 (dd79140). Not seeing this problem.
