### ISSUE TITLE
Target Language Doesn't Update when Loading New Project

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/translationCore#680]
I was looking at a project for the Ora language, then I loaded a new one from online for Mandarin.  I loaded up the iW check but the Scripture pane still showed me the Ora language as the target langauge, see screen shot.
![screen shot 2017-02-09 at 12 19 06 pm](https://cloud.githubusercontent.com/assets/107731/22799252/63c312a0-eec2-11e6-933e-8d5a0f4f8199.png)
I also tried to remove the Ora text and add back in the "target language", but it still loaded Ora again.

I closed the app completely and opened it back up and the Mandarin text is now in the Scripture pane like expected.

**Comment by klappy** [comment]
Confirmed on latest development branch as of 3pm EST today.

<img width="1280" alt="screen shot 2017-02-09 at 2 59 37 pm" src="https://cloud.githubusercontent.com/assets/118073/22800743/5bb6ac28-eed8-11e6-8895-3c2c5f9ad3b2.png">

**Comment by benjore** [comment]
Related to: #657
