### ISSUE TITLE
The (te) resource still shows in the update resource selection screen even after it has been downloaded

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6801]
2.2.0 (2375ae5)
Clear the messages in the console log
Open the source content selection screen
Click on the "Select All" option
Verify that all of the resource checkboxes are actually checked
Click the Download button
Wait for the download to complete successfully
Note that there are no errors in the console log other than possibly a socket timeout
Go back to the content download selection screen
Note that (te) still shows as update available
Note that there is now a te folder in the resources folder
Download the (te) resource
Note that nothing has changed

**Comment by richmahn** [comment]
This was a content issue, where te_iev has "ust" as its identifier in the manifest.yaml file. This caused tC to get confused once there were two "ust" Bibles (te_iev and te_ust). See https://forum.door43.org/t/unable-to-update-telugu-gl-content-update-no-local-date-and-incorrect-online-date/1236/3?u=rich
