### ISSUE TITLE
Jonah 4:2 Highlighting Issue

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/translationCore#6802]
Using tC 2.1.1 and the latest content as of today (UTN v28) I see in the tN tool for Jonah that there is an incomplete highlight of the snippet.  I'm not sure if this is a bug in the code, or some sort of unseen snippet mismatch?

The oddity is that only *part of the snippet* is being highlighted.  In other snippet problems usually there is a content warning dialog that is shown but in this case there is no warning but only part of the highlight is being shown.  According to the snippet and the alignment data the whole phrase "and one who relents from evil" should be highlighted.

The snippet for the relevant check is on this line https://git.door43.org/unfoldingWord/en_tn/src/branch/master/en_tn_32-JON.tsv#L152 of the TSV file.

<img width="1066" alt="Screen Shot 2020-03-31 at 1 31 09 PM" src="https://user-images.githubusercontent.com/107731/78057053-18dff900-7354-11ea-9175-455319d3bc88.png">

**Comment by cckozie** [comment]
Guessing here, but it looks like we're somehow ignoring the first several characters of the first two words when formulating the quoteString
![image](https://user-images.githubusercontent.com/8171759/78241958-db3fb500-74a6-11ea-95da-74055d00745e.png)

**Comment by cckozie** [comment]
In looking at the referenced snippet, the OrigQuote contains the character \u05be, but I'm not seeing that character in the en ULT alignments for Jonah 4:2. Is it breaking when we try to highlight the ULT and can't find that character there?
Whatever the case, we should either highlight properly or display the content problem with check alert

**Comment by RobH123** [comment]
Ok @cckozie @jag3773, **maqaf** is common Heb punctuation. UHB Jonah contains 104 of them but they're ALL between \w words \w*. (Some maqafs DO occur INSIDE words in about half of the OT books, but not in Jonah.)

tX only compares UTN quotes with Heb/Grk. It currently doesn't look at ULT/UST alignments. But those alignments don't include interword punctuation anyway (ULT Jonah correctly contains zero maqafs), so tX couldn't even detect issues with interword maqaf.

I'm a bit confused. Are you sure that the maqaf is the problem in Jonah 4:2? What about the other 103 places in Jonah with maqaf? Is this not a systematic problem, i.e., a bug in the code?

**Comment by jag3773** [comment]
I think #6721 has the fix for this?

**Comment by cckozie** [comment]
Moving this to In QA since we believe the 2.1.2 hotfix will resolve this issue too.

**Comment by cckozie** [comment]
The problem noted in verse 4:2 is now fixed in 2.1.2 (44c92e9)
tC reporting content problem in the second check on 1:2 under Metonymy. Need to check further.
Unicode characters in the resources:
ult:
u'"content": "\u05dc\u05b0\u2060\u05e4\u05b8\u05e0\u05b8\u05bd\u2060\u05d9",\n'
hbo:
u'"text": "\u05dc\u05b0\u2060\u05e4\u05b8\u05e0\u05b8\u05bd\u2060\u05d9",\n'
tN:
u'"quote": " \u05dc\u05b0\u2060\u05e4\u05b8\u05e0\u05b8\u05bd\u2060",\n'

The tN quote starts with a space
The ULT and HBO do not start with a space and they include the trailing characters of \u05d9
Would either of those differences cause the content problem alert?

**Comment by PhotoNomad0** [comment]
@cckozie 

the tN check is ` לְ⁠פָנָֽ⁠`, but the UHB has `לְ⁠פָנָֽ⁠י`.  It looks like the Hebrew Letter Yod (U+05D9) is missing at the end.  As well as an extra space in the check.

**Comment by cckozie** [comment]
Passed this problem to content team. Assuming it's their problem.

**Comment by joeldruark** [comment]
The snippet in Jonah 1:2 should be fixed now.

**Comment by cckozie** [comment]
Still waiting for content updates to be published.

**Comment by cckozie** [comment]
Looks good in 3.0.0 (318d196) 
![image](https://user-images.githubusercontent.com/8171759/84959768-a0bce000-b0c5-11ea-9cfa-9988fc6c83cd.png)
