### ISSUE TITLE
Use Webpack CSS loaders to load CSS files instead of importing in the code. 

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord/translationCore#6805]
### User Story

As a [type of user], I want [some goal] so that [some reason].

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by birchamp** [comment]
DoD: CSS stylings on tC work.  
#6820 Menu bar/header 
background colors

**Comment by mannycolon** [comment]
https://create-react-app.dev/docs/using-the-public-folder
