### ISSUE TITLE
Use Webpack's file loaders to load fonts 

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord/translationCore#6806]
### User Story

As a [type of user], I want [some goal] so that [some reason].

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by PhotoNomad0** [comment]
Note: tried using tips in https://stackoverflow.com/questions/37671342/how-to-load-image-files-with-webpack-file-loader, but does not seem to be working in craco environment.

**Comment by mannycolon** [comment]
https://create-react-app.dev/docs/using-the-public-folder
