### ISSUE TITLE
Builds are now missing commit hash 

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord/translationCore#6811]
### User Story

As a [type of user], I want [some goal] so that [some reason].

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by PhotoNomad0** [comment]
Verified in translationCore 2.2.0 (3e29140)

**Comment by cckozie** [comment]
Seeing the hash in 2.2.0 (3e29140)

**Comment by elsylambert** [comment]
Looks good in 2.2.0 (3e29140).
