### ISSUE TITLE
tW logo not showing on tW card

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6812]
![image](https://user-images.githubusercontent.com/8171759/78380230-2803b880-7599-11ea-9715-6883a11b97a1.png)

**Comment by mannycolon** [comment]
Will be address by https://github.com/unfoldingWord/translationCore/pull/6842

**Comment by cckozie** [comment]
Looks good in 2.2.0 (02533e8)

**Comment by elsylambert** [comment]
2.2.0 (02533e8). tW tool has the icon showing up correctly.
