### ISSUE TITLE
"See more" links on licenses page do not work

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6815]

**Comment by mannycolon** [comment]
<img width="1275" alt="Screen Shot 2020-04-16 at 12 50 22 AM" src="https://user-images.githubusercontent.com/17072300/79415833-51025100-7f7c-11ea-9c43-4b2e289172db.png">

**Comment by PhotoNomad0** [comment]
verified in translationCore 2.2.0 (a352530)

**Comment by cckozie** [comment]
Those links all work in 2.2.0 (02533e8)

**Comment by elsylambert** [comment]
Looks good in 2.2.0 (02533e8).
