### ISSUE TITLE
Licenses pages is displayed after selecting a previous imported project

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6816]
Import a couple projects
Select a different project than the previously selected one
Note that the licenses page is displayed even though a license was previously assigned

**Comment by PhotoNomad0** [comment]
@cckozie - ~not seeing this.  Did USFM import of 1jn, 2jn, and 2pe.  Then went back and opened 1jn - no prompt.~ See this on translationCore 2.2.0 (46f316b), but not seen in development environment.

**Comment by mannycolon** [comment]
verified in translationCore 2.2.0 (a352530)

**Comment by cckozie** [comment]
Not seeing the problem in 2.2.0 (02533e8)

**Comment by elsylambert** [comment]
Not seeing this issue in 2.2.0 (02533e8).
