### ISSUE TITLE
Thinner fonts on primary buttons, dialog title bars, tool menus, and pretty much all text.

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6817]
The primary buttons and dialog title bars (both are elements of white text on blue background) now have what appear to be thinner fonts. Possibly they were bolded in the previous builds?
Here are two comparison examples:
In 2.1.1
![Access Inet 2.1.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/aa0b0910-7aba-4d9a-abc3-2e67f3b51f91)

In Electronite
![Access internet.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/fc320860-5f2d-41ff-ac05-28027aed6d45)

In 2.1.1
<img width="875" alt="tn Buttons 2 1" src="https://user-images.githubusercontent.com/8171759/78391961-044a6d80-75ad-11ea-9469-844c366de2d0.png">

In Electronite
<img width="881" alt="tNButtons2" src="https://user-images.githubusercontent.com/8171759/78391998-188e6a80-75ad-11ea-8d72-7bb11c2cf62b.png">

Here are some others where the primary buttons and/or title should be changed in Electronite. 
<img width="882" alt="tNButtons" src="https://user-images.githubusercontent.com/8171759/78392196-6e631280-75ad-11ea-8cd5-f79284b93a40.png">

<img width="546" alt="btnLaunch" src="https://user-images.githubusercontent.com/8171759/78392198-6efba900-75ad-11ea-9f70-4ee370e42d4f.png">

<img width="771" alt="btnOK" src="https://user-images.githubusercontent.com/8171759/78392199-6f943f80-75ad-11ea-994c-fa7d130fa7c2.png">

<img width="273" alt="home2" src="https://user-images.githubusercontent.com/8171759/78392388-cef24f80-75ad-11ea-9a09-711c758e21a5.png">

<img width="587" alt="home" src="https://user-images.githubusercontent.com/8171759/78392389-cf8ae600-75ad-11ea-9a1f-166f7385df2f.png">

<img width="396" alt="get started" src="https://user-images.githubusercontent.com/8171759/78392394-d0237c80-75ad-11ea-8d9e-73409413e193.png">

<img width="973" alt="expanded helps" src="https://user-images.githubusercontent.com/8171759/78392396-d0bc1300-75ad-11ea-8e90-98ad57165833.png">

<img width="979" alt="add resources" src="https://user-images.githubusercontent.com/8171759/78392401-d1ed4000-75ad-11ea-95e1-dd62849a9ba9.png">

<img width="767" alt="Send feedback" src="https://user-images.githubusercontent.com/8171759/78392402-d1ed4000-75ad-11ea-974d-09d83dbf2070.png">

<img width="915" alt="Import D43" src="https://user-images.githubusercontent.com/8171759/78392403-d285d680-75ad-11ea-9b59-e271a922c76c.png">

<img width="415" alt="guest continue" src="https://user-images.githubusercontent.com/8171759/78392406-d285d680-75ad-11ea-9307-3e7c1c434384.png">

<img width="340" alt="Login" src="https://user-images.githubusercontent.com/8171759/78392407-d285d680-75ad-11ea-9569-923ca13090bd.png">

<img width="350" alt="Login D43" src="https://user-images.githubusercontent.com/8171759/78392409-d31e6d00-75ad-11ea-81bb-f1261f1cd2d7.png">

<img width="440" alt="Continue to project" src="https://user-images.githubusercontent.com/8171759/78392410-d31e6d00-75ad-11ea-8534-47c04409b09c.png">

<img width="924" alt="tC Info" src="https://user-images.githubusercontent.com/8171759/78392411-d3b70380-75ad-11ea-8af6-7407abfb0be1.png">

<img width="783" alt="Export" src="https://user-images.githubusercontent.com/8171759/78392412-d3b70380-75ad-11ea-8bec-a88383a0633a.png">

<img width="156" alt="Alert" src="https://user-images.githubusercontent.com/8171759/78392413-d3b70380-75ad-11ea-9b1f-6963d55cc77b.png">

<img width="429" alt="Cancel Import" src="https://user-images.githubusercontent.com/8171759/78392414-d44f9a00-75ad-11ea-8cfd-e8ead3ae179c.png">

<img width="444" alt="btnOverwrite" src="https://user-images.githubusercontent.com/8171759/78392415-d44f9a00-75ad-11ea-98e9-c0b042deec7c.png">

<img width="763" alt="btnSubmit" src="https://user-images.githubusercontent.com/8171759/78392416-d44f9a00-75ad-11ea-869f-1a9c86bc55cd.png">

<img width="209" alt="btnActions" src="https://user-images.githubusercontent.com/8171759/78392417-d44f9a00-75ad-11ea-9107-ba08de72d4b0.png">

<img width="866" alt="btnContinue" src="https://user-images.githubusercontent.com/8171759/78392418-d4e83080-75ad-11ea-95ed-aa686a153b41.png">

<img width="564" alt="btnSelect" src="https://user-images.githubusercontent.com/8171759/78392419-d4e83080-75ad-11ea-940c-9b0e926d779e.png">

<img width="797" alt="details" src="https://user-images.githubusercontent.com/8171759/78392420-d580c700-75ad-11ea-8271-dd8f9a5a9778.png">

<img width="434" alt="btnDownload" src="https://user-images.githubusercontent.com/8171759/78392421-d580c700-75ad-11ea-8136-26ecd97bb2db.png">

<img width="769" alt="btnOK2" src="https://user-images.githubusercontent.com/8171759/78392423-d580c700-75ad-11ea-86db-67f81a592f63.png">

<img width="773" alt="locale buttons" src="https://user-images.githubusercontent.com/8171759/78392424-d6195d80-75ad-11ea-975a-6de0cfa2c46d.png">

<img width="875" alt="wAButtons" src="https://user-images.githubusercontent.com/8171759/78392426-d6195d80-75ad-11ea-8e02-1668fa12188a.png">

<img width="554" alt="Edit buttonsw" src="https://user-images.githubusercontent.com/8171759/78392427-d6b1f400-75ad-11ea-93ce-b056291df373.png">

<img width="196" alt="btnClose" src="https://user-images.githubusercontent.com/8171759/78392428-d6b1f400-75ad-11ea-8625-16d9bf777b36.png">

<img width="1392" alt="tool menu bar" src="https://user-images.githubusercontent.com/8171759/78392835-88e9bb80-75ae-11ea-9c17-9091e2fb20aa.png">

<img width="243" alt="Tool menu" src="https://user-images.githubusercontent.com/8171759/78392837-89825200-75ae-11ea-9101-f923b1a47cbf.png">

**Comment by cckozie** [comment]
Need feedback from @birchamp on these:
To my eye, the scripture pane text is slightly thinner in the Electronite build. Do we want to change it? (Is the font in 2.2.1 just a darker color?)
in 2.2.1
<img width="762" alt="hebrew 2 1" src="https://user-images.githubusercontent.com/8171759/78393480-8176e200-75af-11ea-9d7a-f782f5a7c78d.png">

In Electronite
<img width="774" alt="hebrew" src="https://user-images.githubusercontent.com/8171759/78393492-8d62a400-75af-11ea-9153-f82a8b3a3cd2.png">

Also, the text in the smurf bar is now thinner, but with the user of both normal and bold fonts the, it may be better now. Thoughts?
In 2.1.1
<img width="867" alt="smurf 2 1" src="https://user-images.githubusercontent.com/8171759/78393812-272a5100-75b0-11ea-8b79-7a5e3765ccbb.png">

In Electronite
<img width="861" alt="smurf bar" src="https://user-images.githubusercontent.com/8171759/78393612-cb5fc800-75af-11ea-82d6-d561e9b29ecf.png">

These also need a decision 
In 2.1.1
<img width="110" alt="step 2 1" src="https://user-images.githubusercontent.com/8171759/78394393-3067ed80-75b1-11ea-9b50-523c5316bfd1.png">

In Electronite
<img width="111" alt="step" src="https://user-images.githubusercontent.com/8171759/78394411-3bbb1900-75b1-11ea-8c30-1a3196691ad6.png">

In 2.1.1
<img width="278" alt="tHelps2 1" src="https://user-images.githubusercontent.com/8171759/78394431-47a6db00-75b1-11ea-9a42-e92c13cc3941.png">

In Electronite
<img width="278" alt="tHelps" src="https://user-images.githubusercontent.com/8171759/78394453-51304300-75b1-11ea-897b-ad4fef07c96b.png">

**Comment by cckozie** [comment]
Should be fixed by #6805 or #6832

**Comment by cckozie** [comment]
This was not fixed by #6805

**Comment by birchamp** [comment]
Guess we need to see if #6832 fixes it.

**Comment by PhotoNomad0** [comment]
Looks like the font and size are OK in the debugger.  In 2.1.2 we have:
![Screen Shot 2 1 2 - 2020-05-11 at 9 49 47 AM copy](https://user-images.githubusercontent.com/14238574/81570398-8b3df300-936e-11ea-9330-91c5da02704b.png)

But in electronite we have:
![Screen Shot electronite - 2020-05-11 at 9 46 07 AM copy](https://user-images.githubusercontent.com/14238574/81570476-a27ce080-936e-11ea-8864-e3d65edf21d4.png)

Looks like the issue might be a new feature: `-webkit-font-smoothing: antialiased;`

**Comment by PhotoNomad0** [comment]
Fixed in translationCore 2.2.0 (690092a)

**Comment by cckozie** [comment]
Looks like the fonts are rendering correctly in 2.2.0 (b749003)
