### ISSUE TITLE
wA in  existing projects throwing critical error screen 

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/translationCore#6819]
2.2 electonite build c0805a9.

Opened the Previously opened projects in wordAlignment tool. For most of the projects, I am getting critical error screen.
<img width="1904" alt="Screen Shot 2020-04-06 at 9 36 28 AM" src="https://user-images.githubusercontent.com/51806180/78564827-0568de00-77eb-11ea-840a-af436ef5dc7d.png">
Here is the log file:
[Mon Apr 06 2020.log.zip](https://github.com/unfoldingWord/translationCore/files/4438695/Mon.Apr.06.2020.log.zip)

**Comment by cckozie** [comment]
I'm not seeing this one on my Mac.

**Comment by PhotoNomad0** [comment]
@elsylambert - Is this failure on Windows? Do you have a project I can use to reproduce this?

It looks like broken resources.

**Comment by elsylambert** [comment]
@PhotoNomad0 Here is the project:
[en_test_3jn_book.zip](https://github.com/unfoldingWord/translationCore/files/4481486/en_test_3jn_book.zip)

**Comment by PhotoNomad0** [comment]
@elsylambert - Thanks for the project, but I am not seeing a problem in the latest build.

**Comment by elsylambert** [comment]
Not Seeing this issue with the project in 2.2.0 (02533e8)

**Comment by cckozie** [comment]
Dup of #6790 (I moved the estimate of 13 to that issue)
