### ISSUE TITLE
Import Fails Silently

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/translationCore#682]
Trying to import https://git.door43.org/551c802a05f3140c/uw-jhn-pt-br.git or https://git.door43.org/f1a6ef405b46d865/uw-phm-pt-br.git fails silently.  Nothing happens when I click the "Import" button.

![screen shot 2017-02-09 at 1 48 39 pm](https://cloud.githubusercontent.com/assets/107731/22802640/c052ea7a-eece-11e6-81e3-011bf49877fd.png)

Error log repots:
```
Uncaught TypeError: Cannot create property 'language_id' on number '3'
```
![screen shot 2017-02-09 at 1 54 18 pm](https://cloud.githubusercontent.com/assets/107731/22802747/4afac396-eecf-11e6-8c81-5cefcc895a89.png)

**Comment by jag3773** [comment]
I tried changing the repo name and the language id to 'pt' here: https://git.door43.org/jag3773/pt_luk_text_ulb -- but that still throws the same error.

**Comment by benjore** [comment]
Related to #691
