### ISSUE TITLE
Header missing in wordAlignment Tool

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/translationCore#6820]
Please see the snapshot below:

<img width="1904" alt="Screen Shot 2020-04-06 at 9 37 41 AM" src="https://user-images.githubusercontent.com/51806180/78565111-6c869280-77eb-11ea-99bd-673f847e9f17.png">

Not able to go back the stepper as the header/stepper part is not seen.
This is happening with some Projects, here are two sample projects:
[hi_irv_act_book.zip](https://github.com/unfoldingWord/translationCore/files/4438730/hi_irv_act_book.zip)
[en_test_act_book.zip](https://github.com/unfoldingWord/translationCore/files/4438734/en_test_act_book.zip)

**Comment by cckozie** [comment]
On my Mac it looks like it's a positioning problem, not that it's missing
![Screen Shot 2020-04-07 at 6 59 56 AM](https://user-images.githubusercontent.com/8171759/78666769-749f0a80-789d-11ea-8281-9270f94aab8f.jpg)

**Comment by cckozie** [comment]
Looks good in 2.2.0 (02533e8)

**Comment by elsylambert** [comment]
Not seeing this issue in 2.2.0 (02533e8).
