### ISSUE TITLE
tC rearranges the resources in the scripture pane after stopping and restarting

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6823]
1. Start by deleting both translationCore folders
2. Import a usfm project
3. Load the project in tW
4. Rearrange the scripture pane to include the resources in this order: current project, UGNT, ULT
5. Return to the projects page
6. Close and reopen tC
7. Import a usfm project
8. Load the new project in tW
9. Note the the scripture pane now shows left to right the ULT  and the current project only

**Comment by birchamp** [comment]
~~DoD: Scripture pane configuration remains the same after restarting tC.~~
DoD: Scripture pane configuration is as it was in previous releases: i.e. target language, original language, others as the user had configured them.

**Comment by PhotoNomad0** [comment]
Notes:

Defining the problem.  Observations: 
- settings path is `~/Library/Application Support/translationCore/settings.json`.  The path looks good.
- see problem that when the app restarts, the tool toolsSettings gets cleared - ~suspect a race condition is happening~.  Confirmed that tCore is writing default settings to file on startup.  It should not be saving until after current settings have been read.  It turns out that there was a path bug hiding LoadMethods.js in develop branch that was exposed in converting from path.datadir().

**Comment by PhotoNomad0** [comment]
Verified in translationCore 2.2.0 (46f316b)

**Comment by cckozie** [comment]
2.2.0 (02533e8)
I set the scripture pane to this arrangement:
![image](https://user-images.githubusercontent.com/8171759/79803631-f6744680-8327-11ea-8473-8cd79ec0eab8.png)
I closed and restarted tC. The scripture pane was rearranged to this:
![image](https://user-images.githubusercontent.com/8171759/79803721-258ab800-8328-11ea-9f01-eb40bcb84315.png)

**Comment by PhotoNomad0** [comment]
@cckozie @birchamp  - I think this has always been the SP behavior : that target language is placed first and original language is second.  I do believe Spidel created an issue to allow complete customization of the order but we have never implemented it.

**Comment by cckozie** [comment]
The scripture resource locations are now as they were prior to 2.2. When reopening a project after a different project, or after a tC restart, the target language is forced to the leftmost pane and the original language is set next to it.
Maintaining the user's arrangement for the project will be handled by #3672.

**Comment by elsylambert** [comment]
2.2.0 (02533e8). Seeing Target language to the leftmost column, Original language and then the additional resources added to the Scripture pane.
