### ISSUE TITLE
Change in initial cursor location when editing a verse 

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6824]
In all previous versions of tC, when a user opens an edit dialog the cursor is set to the end of the verse text.
In the electronite builds, the cursor is set to the beginning of the text. This may not be a defect, but the change in behavior could prove confusing/frustrating for existing users.

**Comment by birchamp** [comment]
@cckozie can you add a screenshot to this?

**Comment by cckozie** [comment]
This appears to have been fixed in 2.2.0 (5214923). (Possibly by the css issue?)
Need to do more testing.

**Comment by PhotoNomad0** [comment]
@cckozie - I see it in tN verse edit (a352530) as well as in SP.

**Comment by PhotoNomad0** [comment]
verified in translationCore 2.2.0 (5774fcc)

**Comment by cckozie** [comment]
Looks good in 2.2.0 (d8fd543)

**Comment by elsylambert** [comment]
Cursor location is at the end of the verse in 2.2.0 (d8fd543). Works fine.
