### ISSUE TITLE
Different font is used on tC startup screen

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6826]
2.1.1
![Screen Shot 2020-04-07 at 9.22.16 AM.jpg](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/c93eea39-b2cf-47f1-ae16-535fd1773ccc)

2.2.0 (3e29140)
![Screen Shot 2020-04-07 at 9.19.49 AM.jpg](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/8cd3ece0-ed21-4610-9816-87c0d04c4947)

**Comment by cckozie** [comment]
Looks the same as 2.1.1 now
![image](https://user-images.githubusercontent.com/8171759/81203321-712a9c00-8f8d-11ea-9496-e974043b0344.png)

**Comment by elsylambert** [comment]
Looks good in 2.2.0 (dd79140).
