### ISSUE TITLE
2.1.2 hotfix release

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/translationCore#6833]
Release Steps Sign Off

### Definition of Done

- [x] QA signs off on specific build in regression testing: current for v2.1.2, enter build number here: 44c92e9 
- [x] Update changelog 
- [x] Update Release Notes - add release notes here: https://github.com/unfoldingWord/translationCore/releases
- [x] Update language database in tCore ~(Note: this has not been updated this for 2.1.2 and is probably not necessary for a point release)~ this is an automatic script run on every build
- [x] Updated resources ~(Note: normally N/A for this point release since we chose not to update resources)~ we only updated en and hbo resources
- [x] Create Mac Build on Mac PC (use same commit as QA signed off on, makes a smaller build, this may no longer be needed for github actions builds?)
- [x] QA does quick check of Mac Build on Mac PC (to make sure resources and features not changed from build in regression testing). 
- [x] Confirm all links to the release download:
  - [x] translationcore.com
  - [x] unfoldingword.org
  - [x] github release page - https://github.com/unfoldingWord/translationCore/releases
  - [x] door43 forum

**Comment by birchamp** [comment]
DoD: 2.1.2 hotfix is published.

**Comment by birchamp** [comment]
[tC_2.1.2_release_notes.txt](https://github.com/unfoldingWord/translationCore/files/4529250/tC_2.1.2_release_notes.txt)

**Comment by cckozie** [comment]
Tested all referenced links.
