### ISSUE TITLE
wordAlignment - the occurrence number is missing when there is a punctuation 

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/translationCore#6837]
Please see the snapshot below: wordAlignment - the occurrence number is missing at one instance while it appear correctly at two other places in the same verse.
![Screen Shot 2020-04-09 at 10.44.44 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/a339d139-444b-4a52-ba52-675ece28906c)
Jehoshaphat: has same lemma and strong number
This is happening in Mathew chapter 1 and verses 2,3,4 and forward where there is genealogy.
Note that there is a punctuation "," between the two occurrences - Jehoshaphat, Jehoshaphat .

**Comment by PhotoNomad0** [comment]
@elsylambert These two words are not exactly the same.  There is a different accent toward the end:

![Screen Shot 2020-04-15 at 8 58 05 AM](https://user-images.githubusercontent.com/14238574/79339861-8153dc00-7ef7-11ea-82b3-d54f4e8f0748.png)
![Screen Shot 2020-04-15 at 8 58 13 AM](https://user-images.githubusercontent.com/14238574/79339874-86b12680-7ef7-11ea-91ae-fa67e0b30276.png)

**Comment by elsylambert** [comment]
Looked up the variation in the two greek words that look very similar in unicodelookup.com. They look exactly the same but has a very minute variation.
Closing this issue.

**Comment by cckozie** [comment]
The accent points in opposite directions
