### ISSUE TITLE
Build number is not shown on Linux local builds

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#6843]
The build number is not shown on Linux (shows as undefined) in local build.  Tested on Linux Mate - local build (both develop and production).  See warning that dotenv failed.

Sidenote - github actions build does show build number.  So this may not be important to fix now.

**Comment by da1nerd** [comment]
that's because the build number is stored in an env file. The release process add this automatically, but if you just run it on your local machine it's blank.

**Comment by PhotoNomad0** [comment]
@neutrinog - I think you need to investigate further.  This is only an issue on LInux - Mac and Windows are fine.  The webpack configuration does copy the .env file.

**Comment by neutrinog** [comment]
there's nothing that edits the .env locally. only CI does that.

**Comment by mannycolon** [comment]
Verified on d8fd543
