### ISSUE TITLE
No indicator of processing after alignments invalidated message when uploading to Door43 

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6845]
2.2.0 (ba86e6a)  and 2.1.1
Project at https://drive.google.com/open?id=1nkSWNnvqHw_QVDaU5dIzNf9GZetrEB4Y

[upload Luke.mp4.zip](https://github.com/unfoldingWord/translationCore/files/4477925/upload.Luke.mp4.zip)

This project came from the field in India. I'm not sure when it was started, but it did get migrated to 2.1.0 and then to 2.1.1. (The screen recording was made using 2.1.1, but it looks the same in 2.2.0)
1. Unzip the project into the projects folder
2. Open the 3-dot menu and choose Upload to Door43
3. When presented with the alignments invalidated alert, click the Export option
Note that there is no indication of processing for several minutes. Eventually the upload succeeded or upload failed alerts will be displayed.

**Comment by mannycolon** [comment]
Verified on 48abded

**Comment by cckozie** [comment]
2.2.0 (40d6f2b) 
This message is now displayed during the alignment resets, and when finished the uploading message is displayed. Seems like the resets are pretty slow, but overall it is about the same duration as in 2.1.2
![image](https://user-images.githubusercontent.com/8171759/82367847-11df7980-99da-11ea-9bf3-fa1e8c207a6d.png)

**Comment by elsylambert** [comment]
Looks good in 2.2.0 (b749003). The alert message showing the Alignment resets is displayed.
