### ISSUE TITLE
"No translationCore default tools found." error message after selecting a project

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6846]
2.2.0 (ba86e6a) 
This worked correctly in 2.2.0 (a9c8b0c) 
Select an existing project or import a usfm project. No tools displayed on the tools page.
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/016750ea-1715-4428-b533-fe80c26b0678)

**Comment by PhotoNomad0** [comment]
@cckozie - This failure is because we are in the process of merging sandbox-electronite into develop. We have the tools merged in, but got stuck merging in the main app in due to github actions being down much of the afternoon.

**Comment by cckozie** [comment]
Not seeing the problem in 2.2.0 (02533e8). Assume Bruce is correct.
