### ISSUE TITLE
Problem detecting reset alignments in upgraded (migrated) projects

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6847]
2.2.0 (a9c8b0c) 
Project at https://drive.google.com/open?id=1nkSWNnvqHw_QVDaU5dIzNf9GZetrEB4Y

This project came from the field in India. I'm not sure when it was started, but it did get migrated to 2.1.0 and then to 2.1.1 and to 2.2.
1. Unzip the project into the projects folder (Save the zipped file for later use)
2. Open the 3-dot menu and choose Upload to Door43
3. When presented with the alignments will be reset alert, click the Export option
There is no indication of processing for several minutes. Eventually the upload succeeded or upload failed alerts will be displayed. (This is written up in #6845)
4. Select the project
5. On the tools page, note that there are 38 invalidations indicated
6. Delete the project from the projects folder
7. Unzip the project into the projects folder
8. Select the project
9. Note that there is no message indicating invalidated alignments, and not indicator of broken alignments on the wA card
10. Load the project in wA
11. Select "Invalidated" from the menu filter
Note that no invalidations are shown

**Comment by birchamp** [comment]
@cckozie is the issue of no invalidations shown only happening for this project above or for any project that is unzipped into the project folder?

**Comment by cckozie** [comment]
@birchamp I know it happens on the referenced project and does not happen on all projects unzipped into the projects folder.

**Comment by PhotoNomad0** [comment]
@cckozie -
- just for clarity: I presume you are stopping tC before step 6 (deleting project) and not trying to remove project while tC is running and project is open.
- Note: I also see the above behavior with translationCore 2.1.2 (44c92e9)

**Comment by PhotoNomad0** [comment]
Notes:
- see the same failure with translationCore 2.1.2 (44c92e9)
- the problem seems to be with the export to USFM failing to align words.
- looking in the project, I see the verse data: `  "49": "\\w उसने|x-occurrence=\"1\" x-occurrences=\"1\"\\w* \\w उनसे|x-occurrence=\"1\" x-occurrences=\"1\"\\w* \\w कहा|x-occurrence=\"1\" x-occurrences=\"1\"\\w*, \\wj \\wj*  “\\w तुम|x-occurrence=\"1\" x-occurrences=\"1\"\\w* \\w मुझे|x-occurrence=\"1\" x-occurrences=\"2\"\\w* ...",`
- this is one of the strange computer generated translations projects
- looks like the problem is this:
```
\it\+wj\w मुझे|x-occurrence="2" x-occurrences="2"\w*
\w अपने|x-occurrence="1" x-occurrences="1"\w*
\w पिता|x-occurrence="1" x-occurrences="1"\w*
\w के|x-occurrence="1" x-occurrences="1"\w*
\w भवन|x-occurrence="1" x-occurrences="1"\w*
\w में|x-occurrence="1" x-occurrences="1"\w*
\f + \f*\f* \f* \f*  \fr 2.49 \fq मुझे अपने पिता के भवन में: \ft यीशु यहाँ पर उन लोगों को यह याद दिलाता है कि वह स्वर्ग से नीचे आया; और उसके सांसारिक माता-पिता से, एक उच्चतम पिता है।\f*    \+wj* \it* \wj \wj*
```

- the multiple end format markers (`\f*`) are causing the usfm parser to choke.

**Comment by PhotoNomad0** [comment]
Verified in translationCore 3.0.0 (0d3b4cf) - seeing 38 invalidations now in WA when opening the project

**Comment by elsylambert** [comment]
3.0.0 (cbed56b).
Got this error when uploading the attached project to D43.
<img width="1212" alt="Screen Shot 2020-06-07 at 4 43 45 PM" src="https://user-images.githubusercontent.com/51806180/83979687-372b1d80-a8de-11ea-9880-0dfad56dda9a.png">

**Comment by elsylambert** [comment]
Not seeing the reported error in the issue. Seeing 38 Alignment resets in wA after re-importing the project.

**Comment by elsylambert** [comment]
Not seeing the issue in 3.0.0 (dad3c32).

**Comment by cckozie** [comment]
Looks good in 3.0.0 (dad3c32).

**Comment by elsylambert** [comment]
Luke 12:35 has reference text that shows up in the word bank (mainly because of the incorrect USFM markers)
