### ISSUE TITLE
Duplicate check in tW 

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/translationCore#6850]
2.1.2 (44c92e9).
Seeing duplicate checks in tW for Ruth 4:17 under the category "Sons" and not able to fix the invalidation.
![image](https://user-images.githubusercontent.com/51806180/79348599-34760280-7f03-11ea-89b9-23927d397d0c.png)
Here is the project:
https://git.door43.org/ElsyLambert/en_ult_rut_book

**Comment by elsylambert** [comment]
This was fixed in 2.1.1.

**Comment by cckozie** [comment]
I verified that this was not a problem in 2.1.1 even with the latest resources.
After upgrading to 2.1.2, I am not seeing it in the upgraded project or in a newly imported one. Testing now with a clean install and a new usfm project. Not seeing the problem there either. 
The duplicate checks did not show in 2.1.0, but they did in 2.1.1.

**Comment by PhotoNomad0** [comment]
@elsylambert @cckozie @birchamp - looking at the project data in ~/translationCore/projects/en_ult_rut_book/.apps/translationCore/index/translationWords/rut/son.json it looks like contains duplicate entries for 4:17 son.  Not sure how that happened unless it was used to test a develop branch that had breakage (i.e. it is a broken project).

Anyway it looks like even though on project import we update the tw checks to latest on the PC, the extra entry is not removed.  May take a few days to fix.

**Comment by PhotoNomad0** [comment]
@elsylambert - not seeing this issue in translationCore 2.2.0 (d6e50a5), but we have made some fixes to how we handle changed resources since the 2.1 releases.

**Comment by elsylambert** [comment]
2.2.0 (d6e50a5). Not seeing duplicate checks in tW in the Ruth Project with the latest resources.
