### ISSUE TITLE
Invalid check warning and then crash screen, but check is not invalid

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#6852]
### User Story

When I opened a rev project in tN and selected check `Abstact Nouns` revelation 1:6, I see invalid check warning.  And when I click ignore I see a crash screen and get this error:
![Screen Shot 2020-04-16 at 6.28.06 AM.png](https://images.zenhubusercontent.com/564e463c638e718c995eb353/ef646817-7216-408e-bdd7-9c772a8095ba)

This may be caused by a race condition because later attempts to open that check succeed.  So the check is not invalid.  

The symptom is that the parameter changeToNextContextId is not a valid function.  See `export const promptForInvalidCheckFeedback = (contextId, selectedGL, moveToNext, changeToNextContextId) => (dispatch, getState) => {` in FeedbackHelpers.js

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by PhotoNomad0** [comment]
It looks like resources are not being cleared from tN when project is changed.  Error message says for rev, but current project is mat.

![Screen Shot 2020-04-16 at 9 48 19 AM](https://user-images.githubusercontent.com/14238574/79464055-9b5cef80-7fc7-11ea-83e8-99b112313f22.png)

**Comment by PhotoNomad0** [comment]
It looks like resources are not being cleared from tN when project is changed.  Error message says for rev, but current project is mat.

![Screen Shot 2020-04-16 at 9 48 19 AM](https://user-images.githubusercontent.com/14238574/79464055-9b5cef80-7fc7-11ea-83e8-99b112313f22.png)

**Comment by PhotoNomad0** [comment]
Verified in translationCore 2.2.0 (02533e8)

**Comment by cckozie** [comment]
Also see #6739 when testing this.

**Comment by cckozie** [comment]
Not seeing the problem in 2.2.0 (02533e8). The steps outlined in #6739 do not create any invalid content alerts, and there are no related errors in the console.

**Comment by elsylambert** [comment]
Not seeing the error in the check "Abstract Noun" Rev 1:6, but got the critical error screen for another check , reported in #6858. 
However, not seeing the Invalid content alert in the checks.

**Comment by elsylambert** [comment]
Not seeing the problem mentioned in #6739.
