### ISSUE TITLE
Multiple tN checks highlighted simultaneously

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6857]
2.1.2 (44c92e9) 
[hi_tit.usfm.zip](https://github.com/unfoldingWord/translationCore/files/4504628/hi_tit.usfm.zip)
[hi_hind_tit_book.zip](https://github.com/unfoldingWord/translationCore/files/4504631/hi_hind_tit_book.zip)

This is a newly imported Hindi USFM project using the latest resources. Note that multiple checks are highlighted, and that one of them shows an English note in the smurf bar even though there is no English notes in the hi-tn tsv file in the catalog.
<img width="1440" alt="abstract_noun_2-2a" src="https://user-images.githubusercontent.com/8171759/79772752-12f78b00-82f6-11ea-972c-7999e7f4fafe.png">
<img width="1440" alt="abstract_noun_2-2b" src="https://user-images.githubusercontent.com/8171759/79772773-1b4fc600-82f6-11ea-85ca-9642b1b3cbf3.png">

<img width="1440" alt="hendiadys_3-3a" src="https://user-images.githubusercontent.com/8171759/79772791-24d92e00-82f6-11ea-8202-6b837c671207.png">
<img width="1440" alt="hendiadys_3-3b" src="https://user-images.githubusercontent.com/8171759/79772823-2d316900-82f6-11ea-9e20-5420fd7820e8.png">

**Comment by elsylambert** [comment]
Seeing the same problem in 2.1.1 Release build 2.1.1 (17b9e26). Found it in HIndi 3Jn too along with the Titus projects.

**Comment by PhotoNomad0** [comment]
@cckozie - following these steps - 

- removed resources folder
- started 2.1.2
- upgraded Hindi resources
- open project
- start tn
- get warning that GL uses older Original Language than most recent (hi tN based on ugnt 0.8)
- click continue
- scroll down to `भाववाचक संज्ञा` (figs-abstractnouns) and select
- only see one entry:

![Screen Shot 2020-04-21 at 6 08 56 AM](https://user-images.githubusercontent.com/14238574/79853899-a2547b00-8396-11ea-8388-df9f59dd20cd.png)

Now will check the case that the latest hi resources have already been downloaded and parsed with older version of app.

**Comment by PhotoNomad0** [comment]
@cckozie - following these steps - 

- removed resources folder
- started 2.1.1
- upgraded Hindi, English, and Greek resources
- open project
- start tn

- scroll down to भाववाचक संज्ञा (figs-abstractnouns) and select
- see five entries (as in first screenshot in description - only 1st is Hindi, the next 4 are actually English checks.  This is the same list as in the original project.

**Comment by PhotoNomad0** [comment]
@cckozie - when the hi resources are updated, it will update checks in the project when it is opened.

Will need the steps you followed to create this project before I know for sure, but I suspect that if we updated the hi resources to the latest in tC 2.1.2, this project would be corrected when opened and it would not be easy to recreate the corrupted checks in the project.

**Comment by cckozie** [comment]
Not seeing this problem in 2.2.0 (ff3cb3e)
