### ISSUE TITLE
Document the electronite build process

### ISSUE THREAD

**Issue by da1nerd** [unfoldingWord/translationCore#6863]
### User Story

As a [type of user], I want [some goal] so that [some reason].

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by da1nerd** [comment]
I put the documentation in the wiki https://github.com/unfoldingWord-dev/electronite/wiki.
I'm going to check how hard it will be to create a script for windows as well. That would simplify it a lot.

**Comment by da1nerd** [comment]
Creating a windows script was actually pretty simple. I'm testing it now on electron 7.2.3

**Comment by da1nerd** [comment]
The windows script works!
The wiki page is finished, though it actually doesn't have a ton of documentation on it since I was able to write all the scripts. there's mostly caveats to keep an eye out for.

**Comment by birchamp** [comment]
@neutrinog can you do a screencast of the process?

**Comment by birchamp** [comment]
@mannycolon in the screencast do you want @neutrinog to talk/walk through what the script is doing?

**Comment by da1nerd** [comment]
I'm putting together several videos for electronite here https://www.youtube.com/playlist?list=PLf7IRQ2kP73kmC8y8gLQoHs4I26LzrRrq

**Comment by da1nerd** [comment]
@birchamp I've finished adding videos that channel above. I embeded a link to that playlist on the electronite wiki page as well.

**Comment by birchamp** [comment]
@mannycolon can you review the links above and let me know if it's sufficient?

**Comment by da1nerd** [comment]
Recently added a video showing how to update the version of electron used for electronite. See [full playlist](https://www.youtube.com/playlist?list=PLf7IRQ2kP73kmC8y8gLQoHs4I26LzrRrq)

**Comment by cckozie** [comment]
The devs will need to review/approve this one.

**Comment by mannycolon** [comment]
Documentation and video tutorials LGTM
