### ISSUE TITLE
Downloading updated content is broken

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#6864]
### User Story

Error downloading updated content in translationCore 2.2.0 (5774fcc) (latest develop)

Also see it in last sandbox build translationCore 2.2.0 (46f316b)

Looks like a dependency has changed.

![Screen Shot 2020-04-22 at 3.05.20 PM.png](https://images.zenhubusercontent.com/564e463c638e718c995eb353/2011028d-9be0-4b27-86da-d43d59c2d867)

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by PhotoNomad0** [comment]
Note:

- after rolling back "tc-source-content-updater" to "0.6.17-build.2" (the version in tc v2.1.2) still see the error.  So now suspecting a dependency has changed, or due to electron being changed.
- on Google, it is looking like it's a common issue is axios, but we are using agentkeepalive.
- could be due to updating node to v12.x?
- or could be 'follow-redirects'?
- found an error in this code (tc-source-content-updater downloadHelpers), the require is returning a `noop` which it should not do:
```
const HttpAgent = require('agentkeepalive');
const HttpsAgent = require('agentkeepalive').HttpsAgent;
```

- tried updating agentkeepalive, follow-redirects, even electron - but still see same fail.
- when I tried setting a breakpoint in agentkeepalive, I see that the agentkeepalive has been replaced with:
```
module.exports = noop;
module.exports.HttpsAgent = noop; // Noop function for browser since native api's don't use agents.

function noop() {}//# sourceURL=[module]
...

```
- looks like related to this issue: https://github.com/webpack/webpack/issues/7953

**Comment by PhotoNomad0** [comment]
Note: looking like the issue is axios.

**Comment by PhotoNomad0** [comment]
Note:
- have a solution: changing the webpack configuration (in craco) and declaring agentkeepalive as external.  Webpack was blocking access to node apis from electron render process (restricting to browser apis)

**Comment by PhotoNomad0** [comment]
Fixing this in PR https://github.com/unfoldingWord/translationCore/pull/6869

**Comment by PhotoNomad0** [comment]
Verified in translationCore 2.2.0 (d6e50a5) 

Downloaded all resources - went quickly without any errors or retries.

**Comment by elsylambert** [comment]
Works fine in 2.2.0 (d6e50a5). Not seeing the error in downloading the resources.

Downloaded all the resources by Select All option , but still one resource "te" remains in the list, even though the resources are downloaded already. Written up separately in #6871.

**Comment by cckozie** [comment]
Downloads work in 2.2.0 (d6e50a5)
