### ISSUE TITLE
Need way to debug tN and tW (and parts of wA)

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#6870]
### User Story

Need way to debug tN and tW (and and parts of wA, e.g. tc-ui-toolkit).  Currently setting a breakpoint in checking-tool-wrapper and tc-ui-toolkit (presuming you can find the line you need) fails - instead it sets the breakpoint at the beginning of the module.  Need an easier way to troubleshoot/debug checking-tool-wrapper and tc-ui-toolkit without adding a huge number of console.logs.

Some options:
- maybe we can find fix to webpack settings of checking-tool-wrapper and tc-ui-toolkit to allow debugging?
- even better maybe we can stop webpacking of the modules since now all of tC is webpacked.

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by birchamp** [comment]
@PhotoNomad0 is this related to #6771?

**Comment by mannycolon** [comment]
is this a dup?

**Comment by mannycolon** [comment]
Dup of 6771

**Comment by mannycolon** [comment]
Dup of 6771
