### ISSUE TITLE
Reported by Perry: Unable to upload a Project to Door43 that was archived on D43 previously.

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/translationCore#6889]
2.1.2 (44c92e9).
Prerequisite : Download a project from Door 43 that was in your Repo.
Steps to replicate:
- Archive the project on Door 43.
- Upload the same Project to D43 from tC.
- See the error as below:
![Screen Shot 2020-05-01 at 1.15.38 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/18622a81-dab9-4843-9153-be0e7b1cab42)

**Comment by elsylambert** [comment]
Information :You cannot upload to a project that is archived on DCS.... you would need to unarchive it first

**Comment by elsylambert** [comment]
@birchamp @cckozie Probably we should consider displaying the right alert message when a project cannot be uploaded to D43 when it is archived on the Repo.

**Comment by birchamp** [comment]
@birchamp checking with @richmahn to see what error is returned.

**Comment by richmahn** [comment]
@birchamp 
If I try to create a repo that was previous archive, I get 409 error and a JSON object saying the repo already exists

If tC is just trying to push a commit, I get this message in Git, which states "richmahn/test is archived"

```
$ git push
Gitea: Unauthorized
Repo: richmahn/test is archived.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by richmahn** [comment]
@birchamp Also, a get of the repo will say it is archived: See payload in this URL response: https://bg.door43.org/api/v1/repos/richmahn/test

```
{
...
  "archived": true,
...
}
```

**Comment by elsylambert** [comment]
@PhotoNomad0 Steps to Archive a Project in DCS:
- Login to DCS and click on the Avatar on the Right-top corner and Go to Profile.
<img width="1792" alt="Screen Shot 2020-05-13 at 10 21 40 AM" src="https://user-images.githubusercontent.com/51806180/81825450-ae9aa680-9504-11ea-83ee-88686046d41e.png">
- Select the project that is to be archived from the list.
<img width="1792" alt="Screen Shot 2020-05-13 at 10 22 20 AM" src="https://user-images.githubusercontent.com/51806180/81825598-d2f68300-9504-11ea-990f-25aad782cc6e.png">
- Click on the settings for the project.
<img width="1792" alt="Screen Shot 2020-05-13 at 10 22 42 AM" src="https://user-images.githubusercontent.com/51806180/81825664-e275cc00-9504-11ea-91cf-13a7f2b05ed1.png">
- Scroll-down to the bottom of the page and note that there is an option to Archive the project.
<img width="1792" alt="Screen Shot 2020-05-13 at 10 24 54 AM" src="https://user-images.githubusercontent.com/51806180/81825748-00dbc780-9505-11ea-8d48-4e53333b1715.png">
- Click on the Archive Repo. Confirm and done.

**Comment by PhotoNomad0** [comment]
@birchamp @cckozie @elsylambert - is there more that we want done here than just adding a message that the project has been archived?  @cckozie had mentioned changing the default message when we don't recognize the response from D43.

Also what text do we want to show on the archive message or the default message?
And do we want to give the option of reporting this?

**Comment by PhotoNomad0** [comment]
Note - see in error log:

![Screen Shot 2020-05-15 at 6 29 25 AM](https://user-images.githubusercontent.com/14238574/82041054-8ed6c000-9675-11ea-99e8-bf9161e88fc4.png)

**Comment by cckozie** [comment]
@PhotoNomad0 The ideas I mentioned related to this problem are in #6915. I would suggest there isn't a need for sending feedback on this one.
@birchamp Will need to supply the verbiage.

**Comment by PhotoNomad0** [comment]
@cckozie - part of the problem here is that the returned message said `unable to access` which covers a lot of possibilities including internet problems and D43 problems.

**Comment by birchamp** [comment]
@PhotoNomad0 Is there a response from the server that is short enough to go on the default/fallback alert? For instance:  "Unable to connect to the server.  Server response: 500 unable to connect"

**Comment by cckozie** [comment]
@PhotoNomad0 Yes, my understanding was that on this issue we just wanted to correct that problem by changing the text on the alert.

**Comment by PhotoNomad0** [comment]
@birchamp Sorry I wasn't clear, but I need a message that can be localized.  Something along the line of "Cannot upload project to Door43 because it has been archived". @cckozie

**Comment by PhotoNomad0** [comment]
or better: "Cannot upload project because it has been archived on Door43".

**Comment by PhotoNomad0** [comment]
Do we want the project name in it?  Like:

"Cannot upload project (${project_name}) because it has been archived on Door43".

**Comment by elsylambert** [comment]
@PhotoNomad0 "Cannot upload project (${project_name}) because it has been archived on Door43". this sounds good. The project name in the message helps.

**Comment by richmahn** [comment]
Is there a way to give a little tip on what a user must do to go unarchive it, or rename their project? Some users might not even know what that means for a repo/project to have been archived, especially if they didn't do it.

**Comment by elsylambert** [comment]
The project ${project_name}) cannot be uploaded because it has been archived on Door43.
Line 2: To Upload this project, kindly unarchive the project on Door43 first or rename the project in translationCore.
@birchamp @cckozie 

> Is there a way to give a little tip on what a user must do to go unarchive it, or rename their project? Some users might not even know what that means for a repo/project to have been archived, especially if they didn't do it.

The usecase here is that the project in the User's Repo is archived. Can someone else archive the project in your Repo? @richmahn

**Comment by PhotoNomad0** [comment]
@elsylambert - I like the `kindly` part - very polite to sensitive users.

**Comment by PhotoNomad0** [comment]
This is what I have:

![Screen Shot 2020-05-15 at 12 52 15 PM](https://user-images.githubusercontent.com/14238574/82075856-ef342480-96aa-11ea-9f7d-e7be61011ca1.png)

**Comment by elsylambert** [comment]
@PhotoNomad0 . Please add "." (Period) in the end, after translationCore.

**Comment by PhotoNomad0** [comment]
Verified in translationCore 2.2.0 (7ccf7e3)

**Comment by cckozie** [comment]
2.2.0 (d786804) The proper alert is now displayed. While testing I noticed a possible problem with how we deal archived projects. Wrote this up on #6932

**Comment by elsylambert** [comment]
Looks good in 2.2.0 (d786804). The alert is displayed properly when the project is archived on D43.
