### ISSUE TITLE
Greek lexical information pop-up

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#689]
# User Story

As a _Greek aficionado_ I want _the Greek information readily accessible_ and I do NOT want _to have to manually close the Greek information_ so that _it is easily accessible and not difficult to navigate/close_.

# Definition of Done

- [ ] Clicking on a Greek word brings up the following information in a pop-over (click w/rootClose): 
  - [ ] Lemma (dictionary entry) 
  - [ ] Morphology
  - [ ] Definition

**Comment by benjore** [comment]
Question: Which info?

**Comment by Thajny** [comment]
![greek stuff](https://cloud.githubusercontent.com/assets/21183377/24416046/0b60c8f8-13a9-11e7-9718-876537009823.png)

**Comment by Thajny** [comment]
Notes: 
To access the greek lexical pop up, the user needs to click the word (not hover). To close this popup, the user will need to click anywhere on the screen to close it.

**Comment by benjore** [comment]
Blocked until we can import UGNT 0.2

**Comment by Thajny** [comment]
![greek stuff 2 0](https://cloud.githubusercontent.com/assets/21183377/24927597/2cf459d6-1ec5-11e7-8166-0ca3c4f54a35.png)
