### ISSUE TITLE
Import of some tStudio projects fail in 2.2

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6899]
2.2.0 (dd79140) 
I was able to import these project in 2.1.2. I am able to successfully import some other tStudio projects. 
Import of these projects fail, and the error message doesn't describe what the problem is.

[es-419_luk_text_reg.tstudio.zip](https://github.com/unfoldingWord/translationCore/files/4589343/es-419_luk_text_reg.tstudio.zip)
[abu_tit_text_reg.tstudio.zip](https://github.com/unfoldingWord/translationCore/files/4589475/abu_tit_text_reg.tstudio.zip)
[ino_tit_text_reg.tstudio.zip](https://github.com/unfoldingWord/translationCore/files/4616232/ino_tit_text_reg.tstudio.zip)

![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/4237a732-9ae2-4c1c-8632-87c6a063adcf)

**Comment by mannycolon** [comment]
Can't replicate in latest develop branch

**Comment by cckozie** [comment]
Still failing in 2.2.0 (d786804)
![image](https://user-images.githubusercontent.com/8171759/82220490-538df880-98e4-11ea-835c-1ac1586f4da5.png)

**Comment by mannycolon** [comment]
@cckozie Can't replicate it locally is there any missing steps in steps above?

**Comment by cckozie** [comment]
@mannycolon - No, I just unzip one of the projects in the first comment and attempt to import it.

**Comment by mannycolon** [comment]
@cckozie Okay, only seeing error in builds not in local development

**Comment by mannycolon** [comment]
Verified on 51afa6e

**Comment by cckozie** [comment]
Able to successfully import the attached projects in 2.2.0 (40d6f2b)

**Comment by elsylambert** [comment]
Not seeing the error message while importing the tS projects in 2.2.0 (b749003).
