### ISSUE TITLE
CSV export- username now showing as Anonymous for all new entries in CSV files

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/translationCore#6906]
2.2.0 (6a53472) 
This worked correctly in 2.1.2
Problem exists in comments.csv, reminders.csv, selections.csv, and verseEdits.csv
CSV Exported to: [en_ult_3jn_bookA.zip](https://github.com/unfoldingWord/translationCore/files/4610871/en_ult_3jn_bookA.zip)
Project: [en_ult_3jn_book.zip](https://github.com/unfoldingWord/translationCore/files/4610876/en_ult_3jn_book.zip)

DoD: All entries in the comments.csv, reminders.csv, selections.csv, and verseEdits.csv files will contain the name of the user who was logged in at the time the activity was performed. The exception is for edits that were performed outside of tC and then reimported with the Overwrite option. Those edits will show Anonymous as the user.

**Comment by PhotoNomad0** [comment]
Verified in translationCore 2.2.0 (4496c12)

**Comment by cckozie** [comment]
2.2.0 (d786804) The correct user name is now written to all CSV files.

**Comment by elsylambert** [comment]
Looks good in 2.2.0 (d786804). The username is displayed correctly in all the CSV files.
