### ISSUE TITLE
tC hangs for over one minute after performing an import with overwrite

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6907]
2.2.0 (690092a) 
This was working properly back on 4/30/20 in build 2.2.0 (ff3cb3e) 
[Mon May 11 2020.log.zip](https://github.com/unfoldingWord/translationCore/files/4611742/Mon.May.11.2020.log.zip)

[6907 projects.zip](https://github.com/unfoldingWord/translationCore/files/4611547/6907.projects.zip)
1. Unzip the attached projects file
2. Import the 57-TIT3full.usfm file
3. Choose English as the GL, load it in tW, and navigate to a different check
4. Import the 57-TIT-change.usfm file giving it the language code of 'en' and the same translation ID as the first import
5. Choose the Overwrite options
6. When the Tools page is displayed attempt to set the tW GL to English
7. Note that the app is hung

**Comment by cckozie** [comment]
2.2.0 (4496c12) 
App is responsive pretty much immediately when the Tools page is reached after the import of the second file.

**Comment by elsylambert** [comment]
Not seeing this issue in 2.2.0 (b749003). tC opens the tools page immediately after the overwrite.
