### ISSUE TITLE
SPIKE []: Research how to make debugging better for checking tool wrapper

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/translationCore#6911]
This SPIKE is needed for determining tasks needed for #6771

Could be potentially be solved by changing the source mapping setting.

**Comment by PhotoNomad0** [comment]
@mannycolon - have had some success with removing webpack in checking-tool-wrapper branch `feature-mcleanb-6771`. But I don't think the devtools are seeing the source maps.  At least it is readable code and can set breakpoints.

**Comment by PhotoNomad0** [comment]
@birchamp @mannycolon I think we can close this now that https://github.com/unfoldingword/translationcore/issues/6771 is implimented.
