### ISSUE TITLE
Problem uploading ULT file to DCS repo

### ISSUE THREAD

**Issue by joeldruark** [unfoldingWord/translationCore#6927]
I am using tCore to review and edit the ULT alignment for the book on Nehemiah.  I hit an unexpected problem uploading my work yesterday to my DCS repo.  I tried deleting the file from my repo and reuploading, but still the same problem.  Here is the error message that I am getting.
<img width="766" alt="Screen Shot 2020-05-15 at 9 01 10 AM" src="https://user-images.githubusercontent.com/34244019/82078581-34019080-9696-11ea-9239-5b6f0f77964d.png">

**Comment by joeldruark** [comment]
[en_ult_neh_book.zip](https://github.com/unfoldingWord/translationCore/files/4636049/en_ult_neh_book.zip)

**Comment by elsylambert** [comment]
I am able to replicate this issue in 2.2.0 (4496c12).
Here is my log file:
[Fri May 15 2020.log.zip](https://github.com/unfoldingWord/translationCore/files/4636142/Fri.May.15.2020.log.zip)
I copied the attached project in Projects folder. The project opens fine in tC with 98% alignment. When uploaded to D43, I got the error message.

**Comment by elsylambert** [comment]
[en_ult_neh_book.zip](https://github.com/unfoldingWord/translationCore/files/4644386/en_ult_neh_book.zip)
@PhotoNomad0  @birchamp Deleting index.lock file works. Able to upload the project to D43 now.

**Comment by PhotoNomad0** [comment]
@birchamp If we see this in the field, this would be a difficult problem for tech support to walk people through- deleting a hidden file from the file system.  Maybe we could add a warning when the user opens the project and give them the option of unlocking and continuing? @cckozie @elsylambert
