### ISSUE TITLE
Add font selection dropdown to project details screen (Frontend Design)

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord/translationCore#6937]
- Make standard Unicode font the default and Awami Nastaliq and Scheherazade fonts as options.
- Fonts are stored in a subfolder under the current fonts folder with the name complex script
e.g.
```bash
├── src
│   ├── fonts
│   │   ├──  complex script
│   │   │     ├── **/*.woff
│   │   │     ├── **/*.tff
```
- Font selection dropdown comes from list saved in src/assets, named complexScriptFonts.js
- Font selection dropdown is not searchable
- Include CSS font setting for Padauk

**Comment by birchamp** [comment]
mockup from the epic #6935
![Font_Choice.png](https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/222b5772-7e29-4b13-b8d7-485fab69bf8c)

**Comment by elsylambert** [comment]
@mannycolon For an Arabic project import, do I have to select a Language Font as Awami Nastaliq or does tC recognize the font by itself?
Just wondering, I did no selection while online import of an Arabic project.

**Comment by cckozie** [comment]
Adding to Elsy's comment above, is the plan to have default selections for a font based on the language? (Defaulting to Noto Sans is specified in the epic)
Also, font selection dropdown lists (and other dropdowns) usually display the options in alphabetical order. Is that planned as part of another issue?
