### ISSUE TITLE
RTL support in enhanced Scripture Pane

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#6941]

**Comment by PhotoNomad0** [comment]
![82339847-1f820880-99b4-11ea-8743-4076e018903c](https://user-images.githubusercontent.com/14238574/82559948-77e51180-9b3e-11ea-98de-1ac77a99b88f.jpg)

**Comment by PhotoNomad0** [comment]
@birchamp @cckozie @elsylambert  - is it even worth the effort to move the pencil icon?  I haven't even seen a mockup where it should be on the left with RTL language.

**Comment by cckozie** [comment]
In reference to ^^^
My 2 cents: The pencil is part of the UI, not the content, and thus should be dealt with in the UI RTL issue(s).

**Comment by PhotoNomad0** [comment]
@cckozie Not following here.  Are you suggesting we should not move the pencil icon then?

**Comment by cckozie** [comment]
@PhotoNomad0 - Yes, not move it until we do the UI mirroring for RTL.

**Comment by birchamp** [comment]
@PhotoNomad0  It's not necessary to move it.

**Comment by PhotoNomad0** [comment]
@birchamp I guess we either close this issue or move it out of sprint.
