### ISSUE TITLE
Arabic font rendering is different in 2.2 than in 2.1.2

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6944]
Maybe I passed the thinner fonts issue one day too soon. It looks like this is not related to Electronite.
These screenshots were taken with this project in wA.
[ar_eph_text_ulb.tstudio.zip](https://github.com/unfoldingWord/translationCore/files/4663597/ar_eph_text_ulb.tstudio.zip)

2.1.2 (44c92e9)
![image](https://user-images.githubusercontent.com/8171759/82583617-e040ec80-9b58-11ea-96e6-b7a84c8330ae.png)

2.2.0 (b749003)
![image](https://user-images.githubusercontent.com/8171759/82583647-eafb8180-9b58-11ea-81f7-4abf72ea57df.png)

2.2.0 (d6e50a5) - pre-Electronite
![image](https://user-images.githubusercontent.com/8171759/82584724-7fb2af00-9b5a-11ea-99f0-df913b477feb.png)

**Comment by birchamp** [comment]
@cckozie  We need to wait until we're using the Scheherazade Graphite font and then we can see what we get. There are anti-collision features built in. Definitely something to keep watch on though.
