### ISSUE TITLE
Current build no longer saves the version of resources used for tool.

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#6945]
### User Story

As a [type of user], I want [some goal] so that [some reason].

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by PhotoNomad0** [comment]
@cckozie @elsylambert - some more breakage

**Comment by PhotoNomad0** [comment]
Note: saveResourcesUsed() is no longer being called in prepareToolForLoading()

**Comment by PhotoNomad0** [comment]
This is working now in latest develop build

**Comment by cckozie** [comment]
Looks good in 3.0.0 (5b5cbbc)

**Comment by elsylambert** [comment]
Looks good in 3.0.0 (cbed56b).
