### ISSUE TITLE
Migrate tN Essentials to New Google Sheet

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#695]
Open Notes check for Ephesians and Titus, and use the checkdata/TranslationNotesChecker.tc for the following:
Convert Book/Chapter/Verse/groupName/Phrase/PhraseInfo to a Google Sheet, with columns of Book/Chapter/Verse/Topic/Quote/Note and a column for Essentials boolean.

Think about scripting for doing the entire Bible.

**Comment by ihoegen** [comment]
https://docs.google.com/spreadsheets/d/1GwBxAqvSm9uNN4MIONV0rQqrEmHh70ttaEmhduGzvGU/edit?usp=sharing
