### ISSUE TITLE
WA tool doesn't work with new projects in Linux

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/translationCore#6955]
To reproduce the problem:
1. Open tC in Linux
2. Import a USFM file and create a new project
3. Open the WA tool
4. Click through the alerts.

The WA tool shows a Warning. 
![image.png](https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/50840d61-ac3c-4a8c-8ab4-d6c63a640abe)

**Comment by PhotoNomad0** [comment]
@neutrinog -  The first problem I found was resource migration fails which explains why it launches so quickly the first time. Looks like a permissions problem that is happening on github action builds, but don't see it when doing `npm start`. Made a build to print the path to the bundled resources and saw that it is correct (`/opt/translationcore/resources/app/static/tcResources/source-content-updater-manifest.json`), but in tCore the test for file exists fails.

Suspect the failure to launch projects in wA is related to this, but could be more.

**Comment by PhotoNomad0** [comment]
@neutrinog - FYI, I just ran `npm run build` in Linux and see that I get the same permissions problem when I launch that.

**Comment by da1nerd** [comment]
This was the build in question https://github.com/unfoldingWord/translationCore/actions/runs/120208932

**Comment by da1nerd** [comment]
I just built the code locally and didn't have any problems.
I ran the build linked above and confirmed the problem occurs on my linux box, I noticed that build was on a PR and not the develop branch.
I'm testing this build next https://github.com/unfoldingWord/translationCore/actions/runs/123220341 which is on the develop branch. This one might actually be working, though projects opened with the broken build might still be corrupt. Still need to do more tests.

**Comment by da1nerd** [comment]
Ok, there was a typo in a config file. Here's a PR to fix it https://github.com/unfoldingWord/translationCore/pull/6964.

I suspect what happened was the resources were updated, and because of the typo the migration failed halfway through so the resources were left in a corrupt state.

**Comment by PhotoNomad0** [comment]
Fixed in 8f548af

**Comment by PhotoNomad0** [comment]
Project that didn't work for Birch: https://git.door43.org/birch/ar_vdb_tit_book

**Comment by cckozie** [comment]
Passing this based on comments from McLean and Birch
