### ISSUE TITLE
Problems with the width of the word bank in wA

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6957]
This was broken in 2.2.

[en-x-demo1_1jn_text_reg.tstudio.zip](https://github.com/unfoldingWord/translationCore/files/4718523/en-x-demo1_1jn_text_reg.tstudio.zip)
This image from 3.0.0 (c8646fa)
<img width="1192" alt="english 1jn" src="https://user-images.githubusercontent.com/8171759/83545670-24bb7900-a4c5-11ea-98fb-837089b1008b.png">
Same view from 2.1.2
<img width="1193" alt="english 1jn 2" src="https://user-images.githubusercontent.com/8171759/83545791-52a0bd80-a4c5-11ea-823e-7eeb8c0e7311.png">

[50-EPH.usfm.zip](https://github.com/unfoldingWord/translationCore/files/4718507/50-EPH.usfm.zip)
From 3.0.0 (c8646fa)
<img width="1188" alt="french word bank" src="https://user-images.githubusercontent.com/8171759/83545880-77953080-a4c5-11ea-872a-515b45d080ec.png">
From 2.1.2
<img width="1190" alt="french word bank 2" src="https://user-images.githubusercontent.com/8171759/83545922-88de3d00-a4c5-11ea-80a5-a37f8b6df601.png">

It's interesting that it works correctly on this project.
![image](https://user-images.githubusercontent.com/8171759/83561276-2c871780-a4dd-11ea-83fa-4f1b2ef2df26.png)

**Comment by elsylambert** [comment]
<img width="1675" alt="Screen Shot 2020-05-26 at 5 03 35 PM" src="https://user-images.githubusercontent.com/51806180/83546695-15412d80-a4cf-11ea-848a-6954614e54ed.png">

**Comment by elsylambert** [comment]
3.0.0 (0f8fc18). Found that word bank width varies in wA within a project for different verses, especially when there are two scroll bars. Here are few screenshots for different sizes:
<img width="419" alt="Screen Shot 2020-06-03 at 11 30 59 PM" src="https://user-images.githubusercontent.com/51806180/83712072-e2905580-a5f2-11ea-8d67-9d87c0fc73b0.png">

<img width="419" alt="Screen Shot 2020-06-03 at 11 30 46 PM" src="https://user-images.githubusercontent.com/51806180/83712080-e7550980-a5f2-11ea-9202-cc5de3bd9adc.png">

<img width="419" alt="Screen Shot 2020-06-03 at 11 30 33 PM" src="https://user-images.githubusercontent.com/51806180/83712088-eae89080-a5f2-11ea-8aca-1bdc9aa4f1a0.png">

<img width="419" alt="Screen Shot 2020-06-03 at 11 30 17 PM" src="https://user-images.githubusercontent.com/51806180/83712098-ede38100-a5f2-11ea-9413-ddf3c22bc9da.png">

**Comment by da1nerd** [comment]
@elsylambert  The word bank has a minimum width and a maximum width by design. It used to have a fixed width but that was changed to offer some flexibility. 

The bug @cckozie identified seems to be related to some conflicting css rules somewhere. The problem comes and goes as I change the width of the window.

**Comment by da1nerd** [comment]
turned out to be a simple css change. PR here https://github.com/unfoldingWord/wordAlignment/pull/275

**Comment by PhotoNomad0** [comment]
Verified in translationCore 3.0.0 (dad3c32)

**Comment by elsylambert** [comment]
Looks good in 3.0.0 (dad3c32).

**Comment by cckozie** [comment]
3.0.0 (dad3c32)
The width is now sizing correctly, but the hover-over on excessively long words is now not working.

**Comment by PhotoNomad0** [comment]
@cckozie - Wow, I never would guess the css change would impact that.

**Comment by da1nerd** [comment]
the tooltip bug wasn't related to the styles (I think). I don't actually know what the problem was, but I made my best guess at how to fix it and it worked. It might have been related to migrating to webpack. here's a fix https://github.com/unfoldingWord/wordAlignment/pull/278

**Comment by PhotoNomad0** [comment]
Verified hover text in translationCore 3.0.0 (2e684d7)

**Comment by da1nerd** [comment]
@cckozie can you elaborate on the outstanding problems?

**Comment by cckozie** [comment]
3.0.0 (318d196) 
@neutrinog - Sorry, I guess I must not have clicked the Comment button after adding my comment. The width and hover are working, but have created another interesting problem. Hopefully this video will help:)
[wordbank.mp4.zip](https://github.com/unfoldingWord/translationCore/files/4764626/wordbank.mp4.zip)

**Comment by PhotoNomad0** [comment]
Verified in translationCore 3.0.0 (8f8dda3)

**Comment by cckozie** [comment]
3.0.0 (8f8dda3)
Now  the hover over is not working until after a drag action occurs.
[hover problem.mp4.zip](https://github.com/unfoldingWord/translationCore/files/4795507/hover.problem.mp4.zip)

**Comment by da1nerd** [comment]
Well... the good news is that since we are now using material-ui 3.* I was finally able to stop using our old and buggy tooltip library in favor of a slick material-ui one.

This has been fixed in https://github.com/unfoldingWord/wordAlignment/pull/280

**Comment by cckozie** [comment]
Looks good in  3.0.0 (311f028) 
Wrote up #7045  relating to arrow coming of the tooltip.
