### ISSUE TITLE
Change label for font choice

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/translationCore#6961]
The label for choosing a font in the Project Properties dialog currently says:
"Language Font"
it should be:
"Project Font"

**Comment by mannycolon** [comment]
- ***NOTE:*** The font selection for projects used before this implementation will not work since the manifest valued has been changed from `languageFont` to `projectFont`. Should not be a problem because this feature hasn't been released to users.

**Comment by mannycolon** [comment]
@cckozie @elsylambert ^^

**Comment by cckozie** [comment]
Looks good in 3.0.0 (5b5cbbc)

**Comment by elsylambert** [comment]
Looks good in 3.0.0 (cbed56b).
