### ISSUE TITLE
Implement font resizing backend

### ISSUE THREAD

**Issue by mannycolon** [unfoldingWord/translationCore#6970]

**Comment by mannycolon** [comment]
Verified on 80e133b

**Comment by cckozie** [comment]
3.0.0 (80e133b) 
ISSUE 1: Vertical scroll bar
The vertical scroll bar is not shown soon enough with some fonts and sizes. This is an Arabic resource (NAV) at maximum size and the target language at 220%. The last line of text for the Arabic resource is not visible, but there is no scroll bar in that pane.
![image](https://user-images.githubusercontent.com/8171759/85790545-fdd41980-b6f5-11ea-9724-c3eaaf49d885.png)

If the target language is reduced to 220%, then the scroll bar appears as desired in the Arabic resource pane
![image](https://user-images.githubusercontent.com/8171759/85790954-b69a5880-b6f6-11ea-82c4-3c2ad9232cca.png)

ISSUE 2: Padding (and questionable text display
Here the target language is at 240%. Note that there is now an additional line of text showing for the Arabic resource, but the bottom is still clipped slightly.
![image](https://user-images.githubusercontent.com/8171759/85790836-85ba2380-b6f6-11ea-95a0-c58cc8f36b2f.png)

If the Arabic pane is scrolled to the bottom, it now appears that the bottom element that was previously clipped actually belongs to different text.
![image](https://user-images.githubusercontent.com/8171759/85791671-d716e280-b6f7-11ea-83b6-be8452f97ac1.png)

There probably should be a little more padding at the bottom of the pane when scrolled all the way to the bottom and the horizontal scroll bar is displayed.
![image](https://user-images.githubusercontent.com/8171759/85793038-06c6ea00-b6fa-11ea-9e28-af4262fe13c0.png)

ISSUE 3: Size selection not persisted
The font size for the target language and original language panes in the scripture pane of wA is reset to 100% when a different project is loaded or tC is ended. Sizes are persisted in tN and tW (until wA is again loaded), and for the other panes in wA.

ISSUE 4: Expand verses not working in Select mode
The Expand verses option in the 3 dot menu in the check pane of tN and tW is displayed but not work when the user is in Select mode.

ISSUE 5: Font size of the Hebrew verse reference
The font size being used for the verse reference for Hebrew in the scripture pane is significantly larger than it was before. The font size displayed at 100% changes significantly as the font size is adjusted. 
3.0.0 (80e133b) 
![image](https://user-images.githubusercontent.com/8171759/85798442-1b5bb000-b703-11ea-9ee4-a39b57c2edce.png)

3.0.0 (84a5a44) 
![image](https://user-images.githubusercontent.com/8171759/85798502-34fcf780-b703-11ea-9eeb-873ad4b79923.png)

ISSUE 6: Font size of Hebrew at 100% varies 
The font size displayed at 100% changes significantly after the font size is adjusted and then set back to 100%
3.0.0 (5c2609d) 
When first loaded:
![image](https://user-images.githubusercontent.com/8171759/85882374-ce301a80-b7a4-11ea-86cc-bdef8b531df7.png)

After adjusting font size and bringing back to 100%
![image](https://user-images.githubusercontent.com/8171759/85882442-e142ea80-b7a4-11ea-9c40-63c06a1d2ca1.png)

Movie showing the above process:
[fontSize.mp4.zip](https://github.com/unfoldingWord/translationCore/files/4838241/fontSize.mp4.zip)

ISSUE 7: Padding for title lines of RTL languages
The padding has been reduced (or eliminated) on the right side of the scripture panes that contain RTL languages. The image on top is from a previous build and the title lines for the RTL languages are right justified the same as the scripture text. In the bottom image, the title lines for the RTL languages are flush against the right hand side of the pane.
I think that is also why the padding between the left side of the RTL panes and the 3-dot menu (previously the close X) is also significantly larger now.
![image](https://user-images.githubusercontent.com/8171759/85905660-9be8e200-b7d1-11ea-994e-308dbd28f94a.png)

ISSUE 8: Vertical size of scripture pane
The vertical size of the scripture pane in wA now changes as the the user navigates through the verses.
![image](https://user-images.githubusercontent.com/8171759/86249303-b83fa280-bb74-11ea-8869-0908e8482cff.png)

![image](https://user-images.githubusercontent.com/8171759/86249448-ede48b80-bb74-11ea-82a8-1be5b6d71c26.png)


QUESTIONS for @birchamp 
A. Was it the intent for the font size selected for the check pane of tW to be also used in the check pane of tN and visa versa? (That is how it is currently working)

B. Was it the intent for the font size selected in the target area in wA to equally adjust both the original language and the target language in that area? (That is how it is currently working)

**Comment by birchamp** [comment]
@cckozie  @mannycolon 
A: No the tN and tW do not need to be linked, but since it's for the same project I don't have an issue with that happening. 
B: Yes that was the intent there.

**Comment by mannycolon** [comment]
**ISSUE 1:** Can't replicate
**ISSUE 2:** Done
**ISSUE 3:** Done
**ISSUE 4:** Can't replicate
**ISSUE 5:** Addressed inconsistencies with the Hebrew font size. However, the Hebrew default font size used to be 175% and now will be 100% to maintain consistency for the text resize slider to work correctly. 
**ISSUE 6:** Done
**ISSUE 7:** Done

**Comment by cckozie** [comment]
@mannycolon - It appears that ISSUE 1 and ISSUE 4 are no longer problems in the latest build.
When testing those I found another problem and added it as ISSUE 8.

**Comment by mannycolon** [comment]
***ISSUE 8:*** Done

**Comment by cckozie** [comment]
3.0.0 (818c550) 
The Hebrew default font size should be the same for the scripture pane and the alignment area. The default size (apparently 175%) was chosen by the stakeholders much as that for  Awami Nastaliq. @birchamp - Should the default  for Hebrew be set to 175%, or do you want to go back to the stakeholders now that we have user sizable fonts?
![image](https://user-images.githubusercontent.com/8171759/86605313-2a94f600-bf6c-11ea-81c4-10088db3603a.png)

**Comment by birchamp** [comment]
@cckozie I asked the content team about this.

**Comment by birchamp** [comment]
@cckozie @mannycolon Based on feedback from wg-content, unless there's a major tech hurdle, Hebrew should show by default at the larger size we've been displaying and be scalable from there.  The larger size should be considered "100%" on the slider.

**Comment by cckozie** [comment]
Retested all issues and they look good in 3.0.0 (e88d8df)
