### ISSUE TITLE
Apparent problem displaying selections in tN

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6973]
3.0.0 (5b5cbbc) 
[ar_test_rut_book.zip](https://github.com/unfoldingWord/translationCore/files/4732096/ar_test_rut_book.zip)
What is being shown in the "has been translated as" pane and the menu does not match the actual selection. I made the selection by dragging.

![image](https://user-images.githubusercontent.com/8171759/83797463-4ef96c00-a668-11ea-9ce6-2a2ab5cfc07b.png)

**Comment by birchamp** [comment]
@cckozie this is expected behavior of the font.  When that character is combined with other characters it becomes truncated.
