### ISSUE TITLE
Migrate tW data for False Positives

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#698]
Create an array of objects with the following Columns:

- False Positive (boolean)
- Book
- Chapter
- Verse
- groupName => quote
- ? => WordArticle
- gatewayLanguage => ULB

The groupName and gatewayLanguage come from data and relabeled in the sheet.
I do not know where we get the ? data from for the wordArticle column.

**Comment by ihoegen** [comment]
@klappy @benjore I'm assuming that this is a sort of data preproccessing? Or is it a functionality of reports that we're building in?
