### ISSUE TITLE
Inconsistencies in displaying Target language name in RTL when fonts are changed 

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/translationCore#6981]
3.0.0 (dad3c32).
In the scripture pane, the Target Language is not aligned Right as per the requirement "(ar)language name". Check Pane displays it correctly.
<img width="1212" alt="Screen-Shot-2020-06-08-at-11 40 40-AM" src="https://user-images.githubusercontent.com/51806180/84073349-a2d4bf80-a99e-11ea-9acc-735528ba6c6c.png">

**Comment by PhotoNomad0** [comment]
@birchamp @elsylambert @cckozie - It looks like the only easy solution (and the standard) is to just let electron (Chromium) handle the ordering of text based on the direction of the unicode characters.  In that case we would see this ordering of titles in the Scripture Pane:

![Screen Shot 2020-06-09 at 3 52 16 PM copy](https://user-images.githubusercontent.com/14238574/84194314-d7ae4880-aa6a-11ea-9bcb-476dbaba8223.png)

and 

![Screen Shot 2020-06-09 at 4 01 55 PM copy](https://user-images.githubusercontent.com/14238574/84194485-1512d600-aa6b-11ea-9096-06a6894bdf42.png)

This is consistent with what we have done in the Check Area

**Comment by PhotoNomad0** [comment]
The other option is to use a library to determine the direction of the language name based on the unicode characters and force the ordering based on the language direction setting in the project.

**Comment by PhotoNomad0** [comment]
Note: decided to let Browser do the text ordering.

**Comment by PhotoNomad0** [comment]
Verified in translationCore 3.0.0 (318d196)
