### ISSUE TITLE
Hebrew looks bold and is clipping 

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/translationCore#6984]
Hebrew looks bold and line height appears to be clipping 

![image.png](https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/1b052d9e-ed4e-46b5-a1f7-b080311cbfe4)
### User Story

As a [type of user], I want [some goal] so that [some reason].

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by PhotoNomad0** [comment]
Note: the boldness seems to be due to new anti-aliasing settings.  The clipping doesn't make sense yet (chromium version related?).

**Comment by PhotoNomad0** [comment]
Rendering:

3.0:
<img width="1436" alt="Screen Shot 2020-06-09 at 11 17 21 AM - new app" src="https://user-images.githubusercontent.com/14238574/85124495-fee9e000-b1f7-11ea-868f-bd7f2b04adee.png">

2.1.2:
<img width="722" alt="Screen Shot 2020-06-09 at 11 27 29 AM - old app" src="https://user-images.githubusercontent.com/14238574/85124546-11641980-b1f8-11ea-8796-a66384215e9b.png">

3.0 Hebrew debug:
![Screen Shot 2020-06-09 at 11 15 10 AM - new app](https://user-images.githubusercontent.com/14238574/85124602-2ccf2480-b1f8-11ea-816d-7b7381057316.png)

2.1.2 Hebrew debug:
![Screen Shot 2020-06-09 at 11 08 12 AM -old app](https://user-images.githubusercontent.com/14238574/85124660-453f3f00-b1f8-11ea-8dab-dde3dcf48142.png)

**Comment by PhotoNomad0** [comment]
Note:
-     '-webkit-font-smoothing: antialiased;' fixes the bolding.  May be able to configure in the css setting for the Elija font.
- in alignment grid, to stop clipping set line-height to normal and padding to `0px 9px 4px 9px`: 
![Screen Shot 2020-06-19 at 3 29 24 PM](https://user-images.githubusercontent.com/14238574/85174030-83615080-b242-11ea-937e-77dd040c6d6f.png)
- in wA container, line 724, currently: 
```
    if (isHebrew) {
      sourceStyle = {
        fontSize: '175%', paddingTop: '8px', lineHeight: '100%',
      };
    }
```
- fix for SP area:
![Screen Shot 2020-06-19 at 6 18 42 PM](https://user-images.githubusercontent.com/14238574/85183332-58362b80-b259-11ea-8614-44f06621f5ec.png)

- ~do we need to change Hebrew font smoothing for enhanced SP and lexicon?~  In Lexicon it doesn't look like anything needs to be done.  enhanced SP may need to be tweaked, but need the font sizing to working first - current font size is too small to be readable.

**Comment by PhotoNomad0** [comment]
Verified in translationCore 3.0.0 (84a5a44) - in WA fixed clipping of Hebrew in Alignment grid area and Hebrew text should be less bold.  In scripture pane of all tools, Hebrew text should be less bold.

**Comment by cckozie** [comment]
The clipping problem has been fixed.
Hebrew was more bold in 2.1.2 than in 3.0. Are we OK with that?
2.1.2 on top, 3.0.0 (84a5a44) on bottom
![image](https://user-images.githubusercontent.com/8171759/85422273-0a604280-b53b-11ea-8180-47241a08dc13.png)
![image](https://user-images.githubusercontent.com/8171759/85422893-b6099280-b53b-11ea-991a-f7241e3b299e.png)



![image](https://user-images.githubusercontent.com/8171759/85422475-45627600-b53b-11ea-9ebe-aeff2408514e.png)
![image](https://user-images.githubusercontent.com/8171759/85422944-c02b9100-b53b-11ea-9c23-179415da70fc.png)


![image](https://user-images.githubusercontent.com/8171759/85422526-54e1bf00-b53b-11ea-9b46-c231fe0ffb60.png)
![image](https://user-images.githubusercontent.com/8171759/85422969-c883cc00-b53b-11ea-9f70-c400d4acb9bf.png)

**Comment by PhotoNomad0** [comment]
> The clipping problem has been fixed.
> Hebrew was more bold in 2.1.2 than in 3.0. Are we OK with that?
> 2.1.2 on top, 3.0.0 ([84a5a44](https://github.com/unfoldingWord/translationCore/commit/84a5a4451c5b6f222ab053f9df74957454f13d3d)) on bottom
> ![image](https://user-images.githubusercontent.com/8171759/85422273-0a604280-b53b-11ea-8180-47241a08dc13.png)
> ![image](https://user-images.githubusercontent.com/8171759/85422893-b6099280-b53b-11ea-991a-f7241e3b299e.png)
> 
> ![image](https://user-images.githubusercontent.com/8171759/85422475-45627600-b53b-11ea-9ebe-aeff2408514e.png)
> ![image](https://user-images.githubusercontent.com/8171759/85422944-c02b9100-b53b-11ea-9c23-179415da70fc.png)
> 
> ![image](https://user-images.githubusercontent.com/8171759/85422526-54e1bf00-b53b-11ea-9b46-c231fe0ffb60.png)
> ![image](https://user-images.githubusercontent.com/8171759/85422969-c883cc00-b53b-11ea-9f70-c400d4acb9bf.png)

@jag3773 - Maybe this would be a better question for you?  In previous release it was bolder than the old version and now is less bold.  Is the new 3.0.0 release good for Hebrew readers?

**Comment by jag3773** [comment]
Yes, the regular font face in 3.0 looks good to me.

**Comment by cckozie** [comment]
Passing based on Jesse's comment
