### ISSUE TITLE
Problems with the group menu in tN and tW in languages with long book names

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6988]
3.0.0 (318d196) 
May want to consider making this an epic.
https://git.door43.org/Steve_HamNC/my_1co_text_ulb (Using Padauk font)
In wA the menu shows the entire book name and reference, but in tN and tW the reference is truncated and the hover-over is not working even though the ellipsis is shown. (2nd image)
After a selection is made, the hover-over does work. However, the book name is not abbreviated and the reference is still not displayed. (3rd image)
The hover-over needs to be fixed. Font size should be discussed. I think it is important that the reference be shown without hovering. Should it auto-size in order to always show the reference? Should we move the reference to come before the book name?
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/3f2c2afe-ad5a-40e2-88c4-dd6935151a0a)

In this image I am hovering over the highlighted menu tile
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/0c4698c1-933c-4a9d-a589-04e8654879cd)

![image](https://user-images.githubusercontent.com/8171759/84396778-11df2d80-abc4-11ea-9105-a81bef3e0722.png)

DOD: Book names no longer show up in the group menu on tN, tW, or WA

**Comment by birchamp** [comment]
@cckozie Yeah, the hover needs to be fixed.  We should discuss the resizing.

**Comment by birchamp** [comment]
@PhotoNomad0 can we truncate the bookname using divs? Needs investigation

**Comment by BincyJ** [comment]
Not a show stopper for 3.0. Would need to be fixed for Burmese.

**Comment by da1nerd** [comment]
Here's some technical info.

The checking-tool-wrapper adjusts the title of the menu item based on whether or not there is a selection. See these lines https://github.com/unfoldingWord/checking-tool-wrapper/blob/develop/src/components/GroupMenuComponent.js#L61-L68.
In wA there's only one version of the title. Do we want to keep these consistent?

We could pretty easily truncate the title so there is room for the reference after it. We just need to separate the title and reference into two spans/divs within a flex box. Then the reference will get a `min-width` of `fit-content`. I built a demo of this in just a few minutes. The tricky part will be deciding how we want to pass this information to the menu without adding complexity. Right now the menu just takes a string so there is a clean abstraction. We could potentially remove the rest of the title logic (the broken tooltips) from the menu and simply use a react component as the title. This component could handle the tooltip logic itself. This special title component would be inserted here https://github.com/unfoldingWord/checking-tool-wrapper/blob/develop/src/components/GroupMenuComponent.js#L72.

The tooltips should be migrated to use material-ui tooltips. We did that with the wordbank in wA and it fixed a lot of problems and was much easier to implement.

**Comment by PhotoNomad0** [comment]
@neutrinog @birchamp @cckozie  - For tN and tW it gets even more complicated - when there is a selection we have three strings to show in menu - book name, reference, and selection.

Do we really need to show book name for each menu item?  I would think the checker knows which book he is checking.

**Comment by PhotoNomad0** [comment]
**Note:**
Need to fix:

- [ ] Hover over text (only shows selection now)
- [ ] somehow fix long book names.  Do we do we just truncate book name and not reference, or can we remove reference altogether?

**Comment by cckozie** [comment]
Same problem in Arabic Ephesians with smallest selectable font size
![image](https://user-images.githubusercontent.com/8171759/86138219-d09bb880-bab3-11ea-9a4e-cd38f3856278.png)

If a selection is made, the selection will show in the hover over, but the reference is still not visible.
![image](https://user-images.githubusercontent.com/8171759/86138470-24a69d00-bab4-11ea-833f-41716290c9fb.png)

I'd suggest dropping the book name from the group menu as an "easy and acceptable" workaround for now, but I think the verse reference is quite important to display.

**Comment by PhotoNomad0** [comment]
**Note:**

For now It was decided to remove the book name from the group menu to make room for reference and possible selection.  This is for all tools to be consistent.

**Comment by PhotoNomad0** [comment]
**Note:**

Have it mostly working, but sometimes get tooltips even though it only comes close to ellipsis showing.

**Comment by PhotoNomad0** [comment]
Fixes in translationCore 3.0.0 (311f028)

**Comment by cckozie** [comment]
Only the selected text should appear in the tooltip instead of both the reference and selection.
3.0.0 (311f028)
![image](https://user-images.githubusercontent.com/8171759/86844076-184eb100-c06d-11ea-91e0-32f09e2ad1cb.png)

In 2.1.2
![image](https://user-images.githubusercontent.com/8171759/86844006-00772d00-c06d-11ea-9064-7b3d95a5dc05.png)

**Comment by PhotoNomad0** [comment]
@cckozie - Sorry, somewhere I picked up that there was a complaint that the reference was left out.  At this point I don't remember where.

**Comment by cckozie** [comment]
@PhotoNomad0 - Yes, that was a complaint, but it related to the reference on the menu tile which wasn't showing with the long book names.

**Comment by PhotoNomad0** [comment]
Verified removed hover reference in translationCore 3.0.0 (66e7002)

**Comment by cckozie** [comment]
Looks good in  3.0.0 (66e7002)
