### ISSUE TITLE
Esther tW check for Evil in 8:6 doesn't highlight aligned word in UST

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/translationCore#6990]
### Description
[Description of the issue]
In the UST "destroyed" is aligned to the Hebrew word for Evil, but it isn't highlighted in the scripture pane.

### Steps to Reproduce
From: https://unfoldingword.zulipchat.com/#narrow/stream/207527-wg-tc/topic/Esther.20BP

Per @jag3773 :
It could be that this is a tC highlighting issue. It seems that the data is all there, but it's not showing the highlight. Here is the line:

\zaln-s | x-strong="b:H7451c" x-lemma="רַע" x-morph="He,Rd:Ncfsa" x-occurrence="1" x-occurrences="1" x-content="בָּ⁠רָעָ֖ה"\\zaln-s | x-strong="H0834a" x-lemma="אֲשֶׁר" x-morph="He,Tr" x-occurrence="1" x-occurrences="1" x-content="אֲשֶׁר"\\zaln-s | x-strong="H4672" x-lemma="מָצָא" x-morph="He,Vqi3ms" x-occurrence="1" x-occurrences="1" x-content="יִמְצָ֣א"\\w destroyed|x-occurrence="1" x-occurrences="1"\w\zaln-e\\zaln-e\\zaln-e\*.”

It's a many Hebrew words to 1 English word alignment, not sure if that is part of the issue? But to summarize, the UST does not show the highlight for the word "destroyed" (as it should) under tW Check>evil>Esther 8:6. The ULT is highlighted correctly. On my local tC, I've got USTv11, ULTv11, UTNv30, UHB2.1.13.

**Screenshots**
![Screen-Shot-2020-06-12-at-11.06.03-AM.png](https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/f55130cc-d528-4033-b998-5608836406c9)

### Context

**Enviorment**
| Tech         | Version |
|--------------|---------|
| tc           | v0.?.?  |
| build #      |         |
| OS           |         |

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by PhotoNomad0** [comment]
Note:

seeing the first Original language word missing as three Original language words are aligned to one gateway language word.

**Comment by PhotoNomad0** [comment]
Invalid checks:

A. due to space in quote:
```
Tool: "translationNotes"
GroupId: "figs-metonymy"
Reference: "est 1:3"
Gateway Language: "en"
Quote: " לְ⁠פָנָֽי⁠ו"
Occurrence: "1"
```

B. looks like wrong verse reference - none of the quote words are in verse - should it be 1:16?
```
Tool: "translationNotes"
GroupId: "figs-metonymy"
Reference: "est 1:15"
Gateway Language: "en"
Quote: "וַ⁠יֹּ֣אמֶר מְמוּכָ֗ן לִ⁠פְנֵ֤י הַ⁠מֶּ֨לֶךְ֙"
Occurrence: "1"
```

C. looks like wrong verse reference - none of the quote words are in verse - should it be 3:5?
```
Tool: "translationNotes"
GroupId: "figs-metaphor"
Reference: "est 3:4"
Gateway Language: "en"
Quote: "וַ⁠יַּ֣רְא הָמָ֔ן"
Occurrence: "1"
```

D. due to space in quote:
```
Tool: "translationNotes"
GroupId: "figs-metonymy"
Reference: "est 3:6"
Gateway Language: "en"
Quote: " בְּ⁠עֵינָ֗י⁠ו"
Occurrence: "1"
```

E. due to space in quote:
```
Tool: "translationNotes"
GroupId: "figs-metonymy"
Reference: "est 3:12"
Gateway Language: "en"
Quote: " כִּ⁠לְשׁוֹנ֑⁠וֹ"
Occurrence: "1"
```

F. due to space in quote:
```
ool: "translationNotes"
GroupId: "figs-metaphor"
Reference: "est 10:2"
Gateway Language: "en"
Quote: " וּ⁠פָרָשַׁת֙"
Occurrence: "1"
```

**Comment by PhotoNomad0** [comment]
Verified in translationCore 3.0.0 (db49afc)

**Comment by cckozie** [comment]
3.0.0 (32e54bf) 
Evil is now highlighted in UST for Esther 8:6
![image](https://user-images.githubusercontent.com/8171759/85179072-93c6fa80-b245-11ea-8e68-fda822b45e46.png)

**Comment by cckozie** [comment]
As of 6/19/20 these are the invalid tN checks:
![image](https://user-images.githubusercontent.com/8171759/85185770-11493580-b25b-11ea-8558-394833b95ca6.png)
