### ISSUE TITLE
SPIKE [6]:Variance in the rendering of texts using Awami Nastaliq

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6993]
3.0.0 (318d196) 
[ar_nav_tit_book.zip](https://github.com/unfoldingWord/translationCore/files/4788163/ar_nav_tit_book.zip)

The outlined text in this sample is rendered differently when displayed in an edit box of both the check pane and expanded scripture pane than it is when rendered anywhere else. Per Alex: "the one on the left should be the more preferable one! given that the one on the right is not an enlarged (zoomed in) view while the one on the left is not... if they are both the same (zoom) view, the one on the left is the correct rendering - in my 'prejudiced' opinion"
We should make the change to how it is rendered in both places where the text can be edited.
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/fd4d6d1d-477f-474c-9d14-146afbc08478)

![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/d07dfa5b-6eb8-44dc-9c20-5e4d117de240)

![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/d029211a-6e12-4998-8137-9376829dd207)

![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/a03da601-d9e0-471c-99d6-01c733d1703f)

**Comment by birchamp** [comment]
Per Paul Nelson (SIL font dev):

> For editing, the extra space between words is preferred, while reading mode the collapsing of whitespace is expected.
> The issue is better carat tracking during edit operations.

In other words, this is intentional behavior of the font.
