### ISSUE TITLE
Material UI Changes

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6994]
3.0.0 (dce7570) 
Some of these change after clicking on them. May have to restart tC to recreate the problem.

![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/2fb2eafa-cefb-4388-9dfa-a75048e8c0fe)

![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/a6d059dd-54e6-47fb-a1da-73d8c29b831e)

![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/f9870141-1ef0-4520-ad59-76d84163feaa)

![image](https://user-images.githubusercontent.com/8171759/84771511-327dfd80-af9f-11ea-9a12-0d461af8275d.png)

![image](https://user-images.githubusercontent.com/8171759/84771829-a5877400-af9f-11ea-9e76-7e4c22a86f91.png)

![image](https://user-images.githubusercontent.com/8171759/84772290-5988ff00-afa0-11ea-85f4-b7b19c0a96bc.png)

![image](https://user-images.githubusercontent.com/8171759/84773131-96a1c100-afa1-11ea-96d3-3ddfbe18fd47.png)

The expanded scripture pane is taller now than in previous builds. I don't think this is a problem. 3.0.0 (dce7570) 
![image](https://user-images.githubusercontent.com/8171759/84775683-209f5900-afa5-11ea-9d39-79b434392523.png)

3.0.0 (318d196) 
![image](https://user-images.githubusercontent.com/8171759/84775935-55131500-afa5-11ea-8a1b-f1f8bc575094.png)

**Comment by mannycolon** [comment]
Verified on 80e133b

**Comment by cckozie** [comment]
The size of the edit pencil is now significantly smaller
Latest build 3.0.0 (80e133b)
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/aae3b23f-c4e7-4bde-9cde-f4b427fff401)

Previous builds 3.0.0 (84a5a44)
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/a7ccc1b6-8f34-473a-9a62-ac5256215b01)

**Comment by mannycolon** [comment]
Verified on a03e2cc
