### ISSUE TITLE
On D43 Upload don't mislead users as to the cause of failures while communicating with Door43

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#6999]
When the return code from Door43 does not match one of the specific errors we are watching for, rather than display the "Unable to connect to server" alert, display one that indicates we don't know what the error was and requests the user to send feedback. 

**new prompt for unknown errors:**
tC has encountered an unknown communications error. If this problem continues, please send "User Feedback" which is an option on the "Actions" button.

**Comment by PhotoNomad0** [comment]
@birchamp @elsylambert @cckozie 

In the epic it says alert should read:
"Door43 is returning an error that translationCore is unable to lookup. Please send feedback using the button below."

since we are no longer adding a "send feedback" button, should this read more like:

Door43 is returning an error that translationCore is unable to lookup. If this problem continues, please send "User feedback" on the "Actions Menu".

**Comment by cckozie** [comment]
I'd prefer something like: tC has encountered an unknown communications error. If this problem continues, please send "User Feedback" which is on option on the "Actions" button.
I think the first sentence will lend itself better to localization than the other version.

**Comment by PhotoNomad0** [comment]
Example screenshot:

![Screen Shot 2020-06-17 at 11 13 22 AM](https://user-images.githubusercontent.com/14238574/84916439-173cec00-b08c-11ea-96c9-aae835bca513.png)

**Comment by PhotoNomad0** [comment]
Verified code changes are in translationCore 3.0.0 (db49afc)

**Comment by cckozie** [comment]
3.0.0 (32e54bf) 
Sometimes the Unable to connect to server is returned if the Internet connection is lost during an upload. Many times there is no error returned, it just "spins" forever.
I was not able to cause this new error to be returned.
