### ISSUE TITLE
On D43 download don't mislead users as to the cause of failures while communicating with Door43

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#7000]
Currently on download problems (due to git clone) we give a non localized error English error prompt, or if no message generated we put up a generic message "Error occurred while importing your project.<br />Could not download the project from ${project_url} to ${toPath}".

**Comment by PhotoNomad0** [comment]
@birchamp @cckozie @elsylambert - I like having the project url and destination path in the error message.  What if we show the following:
1. in case that it is a known error we put up the existing localized message for the error along with additional information such as: `"${specific_localized_error_message}" occurred while importing your project from ${project_url} to ${toPath}.`
2. on unidentified error we do: `${app_name} has encountered an unknown communications error trying to download the project from ${project_url} to ${toPath}. If this problem continues, please send \"${user_feedback}\" which is an option on the \"${actions}\" button."`

**Comment by PhotoNomad0** [comment]
or maybe for #1 `Download failed because "${specific_localized_error_message}" occurred while importing your project from ${project_url} to ${toPath}.`

**Comment by PhotoNomad0** [comment]
**Final decision on prompts:**
1. in case that it is a known error: `The download failed because the error "${specific_localized_error_message}" occurred while importing your project from ${project_url}.`
2. on unidentified error we do: `${app_name} has encountered an unknown communications error trying to download the project from "${project_url}". If this problem continues, please send \"${user_feedback}\" which is an option on the \"${actions}\" button."`

**Comment by cckozie** [comment]
3.0.0 (84a5a44) 
Putting this on a new issue
I'm now receiving this error when the Internet connection is lost during a download. It seems like we should be able to detect and correctly report that sort of failure.
![image](https://user-images.githubusercontent.com/8171759/85420493-e3087600-b538-11ea-88c2-49eea156f075.png)
  
From the console:
![image](https://user-images.githubusercontent.com/8171759/85420585-07fce900-b539-11ea-84ba-b4e1445eacb5.png)
