### ISSUE TITLE
Problems with the hover-over target words in wA when the project is using the Scheherazade font 

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#7011]
3.0.0 (8f8dda3)
[hovering font.mp4.zip](https://github.com/unfoldingWord/translationCore/files/4795542/hovering.font.mp4.zip)

The hover-over is showing in the word bank on words that are not truncated. It should not show in the word bank unless the word is truncated and showing ellipsis. 
It is also showing on the target words in the alignment area. 
This happens with the Scheherazade font even if the project is not in Arabic.

(Note: There is currently a bug where hover-overs are not shown until after a drag action, so you may have to drag a word out of the word bank in order to get the hover overs showing)

**Comment by da1nerd** [comment]
just a couple days ago, the old tooltip code for words in the wordbank was gutted and replaced with a new tooltip that is much more stable. @cckozie if you look at this again, I suspect the issues will no longer exist.

**Comment by cckozie** [comment]
@neutrinog - Nope, still a problem in 3.0.0 (84a5a44) . Please note that it is font related.
[ar_navc_tit_book.zip](https://github.com/unfoldingWord/translationCore/files/4830977/ar_navc_tit_book.zip)

**Comment by PhotoNomad0** [comment]
@cckozie - think I have a fix for this putting in https://github.com/unfoldingword/translationcore/issues/6988

**Comment by cckozie** [comment]
Looks good in 3.0.0 (311f028)
