### ISSUE TITLE
Duplicate checks in Esther TN

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/translationCore#7012]
### Description

See duplicated check in EST 9:28 (under "Idiom") and Esther 7:8:
![image.png](https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/6d04b2e6-05a5-4287-ab89-23d8a74e9257)

### Steps to Reproduce

**Screenshots**

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

### Context

**Enviorment**
| Tech         | Version |
|--------------|---------|
| tc           | v0.?.?  |
| build #      |         |
| OS           |         |

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by birchamp** [comment]
Not sure if this is the same issue:  In tW the team is seeing a duplicated check and unable to complete checking.  Checking God in Titus 3:8 - I'm not seeing this in v3.0
![Russian problem in English - last verse duplicated check not complete.png](https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/e8809551-d53d-4e64-a8af-e705ffcff2a3)

**Comment by PhotoNomad0** [comment]
@birchamp - This is a content error, in Esther 9:28, the last two checks have the same quote string in the en_tn, so they are not unique: `"quoteString": "וִ⁠ימֵ֞י הַ⁠פּוּרִ֣ים הָ⁠אֵ֗לֶּה לֹ֤א יַֽעַבְרוּ֙ מִ⁠תּ֣וֹךְ הַ⁠יְּהוּדִ֔ים וְ⁠זִכְרָ֖⁠ם לֹא־יָס֥וּף מִ⁠זַּרְעָֽ⁠ם"`, also in Esther 7:8, the assumed knowledge checks have duplicated quote strings `"quoteString": "וּ⁠פְנֵ֥י הָמָ֖ן חָפֽוּ"`

**Comment by PhotoNomad0** [comment]
> Not sure if this is the same issue: In tW the team is seeing a duplicated check and unable to complete checking. Checking God in Titus 3:8 - I'm not seeing this in v3.0
> ![Russian problem in English - last verse duplicated check not complete.png](https://camo.githubusercontent.com/9857f1f4ce48622addb0c419190632a73f0a9aa4/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3563663533393031653339653566333365336531323966612f65383830393535312d643533642d346536342d613861662d653730356666636666326133)

@birchamp I am not seeing this in 2.1.2 with a regular titus project.  I suspect this is a broken project that 3.0.0 is repairing, but would need the original project to be sure.
