### ISSUE TITLE
Critical error screen while importing Obadiah

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#7023]
3.0.0 (5c2609d)
Arabic - [31-OBA.usfm.zip](https://github.com/unfoldingWord/translationCore/files/4849276/31-OBA.usfm.zip)
English - [31-OBA.en.usfm.zip](https://github.com/unfoldingWord/translationCore/files/4849372/31-OBA.en.usfm.zip)
https://git.door43.org/burje_duro/am_oba_text_ulb

![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/4a9d1efd-658c-4da8-b590-1b350dbc7f61)

**Comment by PhotoNomad0** [comment]
Notes:
- There is a bug in the tN checks.  At runtime see:

![Screen Shot 2020-06-30 at 4 46 19 PM](https://user-images.githubusercontent.com/14238574/86175427-51c57080-baf1-11ea-9000-8553e0e1a1a3.png)

- it looks like "bita-phenom" is missing.  The only entry in en_tn is `OBA 1:18`
- there are a bunch of check warnings in `https://door43.org/u/Door43-Catalog/en_tn/master/` in `OBA 1:18`:
```
Unexpected leading whitespace in ' וְ⁠הָיָה֩…' in OrigQuote at OBA 1:18 (rm2e) in line 111
Unexpected non-break space in '⍽וְ⁠הָ…' in OrigQuote at OBA 1:18 (rm2e) in line 111
Unable to find OBA 1:18 (rm2e) '⍽וְ⁠הָיָה֩ בֵית־יַעֲקֹ֨ב אֵ֜שׁ וּ⁠בֵ֧ית יוֹסֵ֣ף לֶהָבָ֗ה' (contains No-Break Space shown as '⍽') in 'וְ⁠הָיָה֩ בֵית־יַעֲקֹ֨ב אֵ֜שׁ וּ⁠בֵ֧ית יוֹסֵ֣ף לֶהָבָ֗ה וּ⁠בֵ֤ית עֵשָׂו֙ לְ⁠קַ֔שׁ וְ⁠דָלְק֥וּ בָ⁠הֶ֖ם וַ⁠אֲכָל֑וּ⁠ם וְ⁠לֹֽא־יִֽהְיֶ֤ה שָׂרִיד֙ לְ⁠בֵ֣ית עֵשָׂ֔ו כִּ֥י יְהוָ֖ה דִּבֵּֽר׃'
OBA 1:18: Possible missing opening '(' — found 3 '(' but 4 ')'
OBA 1:18 line 1: Possible nesting error—found unexpected ')' near The descendants of Joseph are also being described figuratively as if they were one household. Joseph was the son of Jacob, and his descendants made up a large part of the people of Israel. So Yahweh is using his descendants to represent the whole nation. (See: [Biblical Imagery - Man-made Objects](https://git.door43.org/Door43-Catalog/en_ta/src/branch/master/translate/bita-manmade/01.md)) and [Synecdoche](https://git.door43.org/Door43-Catalog/en_ta/src/branch/master/translate/figs-synecdoche/01.md))

```

- here is the check:
```
OBA | 1 | 18 | cr19 | bita-phenom | ◊ê÷µ÷ú◊©◊Å‚Ä¶◊ú÷∂◊î÷∏◊ë÷∏÷ó◊î‚Ä¶◊ú÷∞‚Å†◊ß÷∑÷î◊©◊Å | 1 | fire, flame, stubble | Yahweh is saying figuratively that just as   fire and flame burn up dry grass until it is all gone, the Israelites who   survive will conquer all of Edom. (See:   [[rc://en/ta/man/translate/bita-naturalphenomena]])
-- | -- | -- | -- | -- | -- | -- | -- | --



```

- can recover from error in ToolCardBoxes.loadArticles()-  add error checking.
- ~might try reimporting en_tn to see if error is shown.~  Looks like in tsv parsing that "bita-phenom" is not saved to others group.
  - It's even more complicated than that:  the link is a whole different format: `(See: [[rc://en/ta/man/translate/bita-naturalphenomena]])` which breaks indexing of checks into groups.

**Comment by PhotoNomad0** [comment]
Can import Obadiah projects in translationCore 3.0.0 (311f028)

**Comment by cckozie** [comment]
Not seeing the problem in 3.0.0 (311f028)
