### ISSUE TITLE
Double clicking to highlight words in Arabic projects only works intermittently

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#7024]
3.0.0 (a03e2cc)
Sometimes it works correctly, sometimes it does nothing, sometimes it momentarily highlights some spaces in blue or the entire text in blue.
[7024.mp4.zip](https://github.com/unfoldingWord/translationCore/files/4851770/7024.mp4.zip)

**Comment by birchamp** [comment]
I wonder if maybe @neutrinog can shine some light on this.

**Comment by PhotoNomad0** [comment]
Note:
- looks like an issue with window.getSelection() is returning empty selected text when double-clicking near end of rtl word.
- it looks like it only fails with graphite fonts.
- the normal double-click behavior is that we get two mouse up events and on the second we see call window.getSelection() to see what text was selected.

**Comment by PhotoNomad0** [comment]
@cckozie give this a try: verified change in translationCore 3.0.0 (66e7002)

**Comment by cckozie** [comment]
It is much better in 3.0.0 (66e7002) but there are still some problems.
[ar_nav_1jn_book.zip](https://github.com/unfoldingWord/translationCore/files/4893356/ar_nav_1jn_book.zip)
[7024b.mp4.zip](https://github.com/unfoldingWord/translationCore/files/4893351/7024b.mp4.zip)
@birchamp - Do we want to have him take another run at this?

**Comment by birchamp** [comment]
@cckozie @PhotoNomad0 Let's talk about this at standup. I just need to know if this is the type of change that can be adjusted/tweaked.

**Comment by cckozie** [comment]
We decided the juice wasn't worth the squeeze to make this better. I moved the problem to #7052.
