### ISSUE TITLE
Font sizer for word bank should be anchored to a stationary point

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#7028]
3.0.0 (a03e2cc) 
The font sizer for the word bank moves as the user changes the font size. This makes it harder to set the desired size and also makes it look strange.
[word_bank.mp4.zip](https://github.com/unfoldingWord/translationCore/files/4860657/word_bank.mp4.zip)

**Comment by PhotoNomad0** [comment]
Note:
Some positioning possibilities:
- use absolute positioning: https://material-ui.com/components/popover/
```
<Popover 
  anchorReference="anchorPosition"
  anchorPosition={{ top: 200, left: 400 }}
  anchorOrigin={{
    vertical: 'top',
    horizontal: 'left',
  }}
  transformOrigin={{
    vertical: 'top',
    horizontal: 'left',
  }}
>
  The content of the Popover.
</Popover>
```
- useFixedPositioning (see `https://react-md.dev/packages/transition/demos` under "Fixed Positioning Example")
- self positioning react components: https://www.freecodecamp.org/news/self-positioning-react-components-2/

**Comment by cckozie** [comment]
Looks good in 3.0.0 (4892ffe)

**Comment by PhotoNomad0** [comment]
Verified translationCore 3.0.0 (02924df)

**Comment by cckozie** [comment]
Looks good in 3.0.0 (02924df)
