### ISSUE TITLE
When selecting text, Error thrown on double click near end of word.

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#7030]
### User Story

When selecting text, Error thrown on double click near end of word.

This may only be seen running in developer mode:
![Screen Shot 2020-07-02 at 8.55.22 AM.png](https://images.zenhubusercontent.com/564e463c638e718c995eb353/a81e1e2f-fc08-400f-bc4d-7600db8cecf8)

Looks like logic error not checking that array is not empty:
![Screen Shot 2020-07-02 at 8.56.47 AM.png](https://images.zenhubusercontent.com/564e463c638e718c995eb353/af5abb3d-da14-42e5-a509-42748efacc30)

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by PhotoNomad0** [comment]
Should be fixed in https://github.com/unfoldingWord/translationCore/pull/7039

**Comment by PhotoNomad0** [comment]
@cckozie Should no longer see log errors on double-click.  Verified in translationCore 3.0.0 (66e7002)

**Comment by cckozie** [comment]
Not seeing any errors when double clicking in 3.0.0 (66e7002)
