### ISSUE TITLE
Alphabetize font drop down and change icon in Project Information

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/translationCore#7032]
The dropdown list for font selection on the Project Information dialog should be alphabetized. 

The icon for the font selection needs to be changed to the text_fields icon ![text_fields-24px.png](https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/4474a144-f3ae-4ff7-88b6-2307fd531e0b)

**Comment by PhotoNomad0** [comment]
Versified in translationCore 3.0.0 (e88d8df)

**Comment by cckozie** [comment]
TT icon is shown and the list is alphabetized in 3.0.0 (e88d8df)
