### ISSUE TITLE
The occurrence number in the wA alignment area for the Hebrew is not fully contained of the word tile

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#7033]
3.0.0 (818c550) 
This is mainly a problem when the original language is Hebrew, although the occurrence number for Greek and the target language do bump up against the edge of the word tile.
Should the occurrence number be a fixed size, or should it change as the font size is changed?
![image](https://user-images.githubusercontent.com/8171759/86607180-911b1380-bf6e-11ea-86ea-0030739d2d2b.png)

![image](https://user-images.githubusercontent.com/8171759/86607218-9c6e3f00-bf6e-11ea-8dbb-4d37e10ae2fe.png)

![image](https://user-images.githubusercontent.com/8171759/86933204-e8042280-c0ff-11ea-8042-28d6a54597ba.png)

**Comment by mannycolon** [comment]
@birchamp @cckozie So should it be a fixed size, or should it change as the font size is changed?

**Comment by birchamp** [comment]
@mannycolon Is the default full size now? Or is it superscript?

**Comment by mannycolon** [comment]
The occurrence number changes font size as the text changes size

**Comment by mannycolon** [comment]
@birchamp

**Comment by cckozie** [comment]
@mannycolon @birchamp I think changing size is preferable, if feasible.

**Comment by mannycolon** [comment]
@cckozie So adding some padding to the occurrence number should work then?

**Comment by cckozie** [comment]
@mannycolon I think that would solve it.

**Comment by mannycolon** [comment]
Perfect thanks

**Comment by birchamp** [comment]
Yeah. Should be fine.

**Comment by PhotoNomad0** [comment]
verfified translationCore 3.0.0 (05a58a9)

**Comment by cckozie** [comment]
Looks good in 3.0.0 (05a58a9)
