### ISSUE TITLE
Pointing arrow on group menu tooltip and word bank tooltip moves after hover over

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#7034]
This broke somewhere between 3.0.0 (84a5a44) from 6/23 and 3.0.0 (80e133b) from 6/25. It happens on tooltips that show the selected text in the group menu and on long word in the word bank that get truncated and causes the tooltip to show. 

[7034.mp4.zip](https://github.com/unfoldingWord/translationCore/files/4879826/7034.mp4.zip)

[7034a.mp4.zip](https://github.com/unfoldingWord/translationCore/files/4929158/7034a.mp4.zip)

**Comment by PhotoNomad0** [comment]
Note: 
- seems related to upgrade of material UI

**Comment by PhotoNomad0** [comment]
Verified translationCore 3.0.0 (05a58a9)

**Comment by cckozie** [comment]
Looks good in 3.0.0 (05a58a9)
