### ISSUE TITLE
Font is not sizable in verse editing dialogs

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#7038]
The definition of done on the font sizing epic (#6943) is "The user can adjust the text of any scripture on the screen."
The dialogs for editing the text both in the expanded scripture pane and in the check area of tN and tW currently do not allow resizing the font.

**DoD**: opening any scripture editor will display the text at the same size as it was being viewed.

**Comment by PhotoNomad0** [comment]
@birchamp @cckozie - how do we want to address this?  The simplest seems to be to carry the font size selections of the tools in the verse check area and word alignment area into the edit fields.

**Comment by PhotoNomad0** [comment]
Verified in translationCore 3.0.0 (380dc3e)

**Comment by cckozie** [comment]
3.0.0 (ed14fea) 
The font is properly sized in the edit dialogs associated with the expanded scripture pane and the wA alignment area, but it is not properly sized in the edit dialog associated with the check pane of tN and tW where it always is displayed at 100% when the target language font is Noto Sans.
![image](https://user-images.githubusercontent.com/8171759/87368306-ecd33700-c542-11ea-9a66-dca0f2ea229b.png)

**Comment by PhotoNomad0** [comment]
Verified in translationCore 3.0.0 (9a422eb)
