### ISSUE TITLE
Selected Arabic and Burmese text is sometimes not reproduced exactly in the "has been translated as" pane

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#7041]
3.0.0 (311f028) 
[ar_nav_oba_book 2.zip](https://github.com/unfoldingWord/translationCore/files/4887322/ar_nav_oba_book.2.zip)
Verse 1:1 in Abstract Nouns group in tN. I think the differences may be punctuation characters.
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/abe2ae1c-6f64-4093-80a8-8b9f4cbc16fc)

Verse 2:6 in Abstract Nouns
[my_ulb_1co_book 2.zip](https://github.com/unfoldingWord/translationCore/files/4892065/my_ulb_1co_book.2.zip)
![image](https://user-images.githubusercontent.com/8171759/86946997-ccedde80-c110-11ea-8095-ee88ee06dc4f.png)

**DoD**: Highlighted punctuation ends up on the correct side in the "translated as" pane for both complex/RTL and non-conmplex/LTR projects.

**Comment by cckozie** [comment]
According to Alex this is a problem and should be fixed.

**Comment by PhotoNomad0** [comment]
@cckozie @birchamp - I can fix the first example.  The second example (Burmese in left to right) is showing that the character is supposed to be joined to the preceding character https://github.com/unfoldingWord/translationCore/issues/7040.

**Comment by birchamp** [comment]
The first example is the major issue here.  The punctuation character shouldn't be swapped.

**Comment by PhotoNomad0** [comment]
See that some characters are meant to be paired with a preceding character.  The 4140 is the character in the example above:

```
Show Unicode Character
Enter a code or character and see the Unicode name.

Use START-STOP to show a range (raw, hex or int).
U+HEX (optional whitespace) U+HEX (optional whitespace) ... to show a list of hex characters.
Use "raw string" to display identification for all characters in the query box.
သူတို့အား

Raw string U+hex code point list Raw text range Hexadecimal range Integer range 
Info for string "သူတို့အား"
4126     101E     သ     MYANMAR LETTER SA

4144     1030     ူ     MYANMAR VOWEL SIGN UU

4112     1010     တ     MYANMAR LETTER TA

4141     102D     ိ     MYANMAR VOWEL SIGN I

4143     102F     ု     MYANMAR VOWEL SIGN U

4151     1037     ့     MYANMAR SIGN DOT BELOW

4129     1021     အ     MYANMAR LETTER A

4140     102C     ာ     MYANMAR VOWEL SIGN AA

4152     1038     း     MYANMAR SIGN VISARGA

Note if a range of characters is specified, only known characters in the range will be printed. If no characters in the range are found, the first character after the range will be printed (when possible).

A Unicode Toy © 2009-2020 Eli the Bearded
```

see https://qaz.wtf/u/show.cgi?show=%E1%80%9E%E1%80%B0%E1%80%90%E1%80%AD%E1%80%AF%E1%80%B7%E1%80%A1%E1%80%AC%E1%80%B8&type=string

**Comment by PhotoNomad0** [comment]
Also if you notice above the Visarga is not a punctuation, but part of the word.

**Comment by mannycolon** [comment]
Verified on e6db62d

**Comment by cckozie** [comment]
Looks good in 3.0.0 (e6db62d)
