### ISSUE TITLE
The padding has been lost on the right side of the reference lines in the check pane when displaying RTL languages

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#7043]
3.0.0 (311f028) 
![image](https://user-images.githubusercontent.com/8171759/86850323-ba26cb80-c076-11ea-8cc0-270d9e6108fb.png)

**Comment by PhotoNomad0** [comment]
Verified in translationCore 3.0.0 (e88d8df)

**Comment by cckozie** [comment]
Looks good in 3.0.0 (e88d8df)
