### ISSUE TITLE
change font drop down to show Ezra (default) as the font for Hebrew scripture resources. 

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/translationCore#7070]
font drop down should say Ezra (default) for Hebrew scripture.

**Comment by mannycolon** [comment]
Verified on 911d214

**Comment by cckozie** [comment]
3.0.0 (911d214)
Ezra (Default) is displayed in the font dropdown list when Hebrew is shown as the Original Language.
In a project where Hebrew is the target language, then Noto Sans (Default) is displayed in the font dropdown list.
