### ISSUE TITLE
Modify build scripts to include all aligned Bibles

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/translationCore#7074]
Build scripts should have a switch to include all of the currently aligned Bibles published in the catalog.

**Comment by PhotoNomad0** [comment]
Verified in translationCore 3.0.0 (84f06a6) 

Aligned Bible List: https://api.door43.org/v3/subjects/Aligned_Bible.json

**Comment by cckozie** [comment]
30 Bibles included in 3.0.0 (74b79f2)
