### ISSUE TITLE
The edit cursor is incorrectly positioned in edit dialogs for RTL projects

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#7081]
3.0.0 (529bf6b) 
When editing an RTL project verse in the expanded scripture pane, the edit cursor is positioned at the right end of the LAST line of text.
When editing an RTL project verse in the check area of tN or tW, the edit cursor is positioned at the LEFT end of the LAST line of text.
In both cases, the edit cursor should be positioned at the RIGHT end of the FIRST line of text.

**Comment by PhotoNomad0** [comment]
@cckozie - there is a bigger problem here.  The punctuation is not being rendered in the correct spot during edit.  See:

![Screen Shot 2020-07-28 at 9 07 34 AM copy](https://user-images.githubusercontent.com/14238574/88670720-662a6800-d0b3-11ea-916f-a28297048e86.png)


Also I think for RTL languages, I think we want the cursor at the left of the last line of text which is the end of text (see https://github.com/unfoldingWord/translationCore/issues/6824).

**Comment by birchamp** [comment]
@cckozie In 3.0, I'm seeing the caret at the end of the verse in LTR languages - Rightmost position of last line.

**Comment by cckozie** [comment]
Yes, my bad. Had it backwards. Cursor should show at the left end of the last line of text when opening an edit.

**Comment by PhotoNomad0** [comment]
It's confusing for us ltr readers.

With fix, I now see: 
![Screen Shot 2020-07-28 at 9 53 23 AM](https://user-images.githubusercontent.com/14238574/88675194-ae985480-d0b8-11ea-9061-fb563a2c270f.png)

**Comment by PhotoNomad0** [comment]
Verified in translationCore 3.0.0 (5a7caea)

**Comment by cckozie** [comment]
Cursor positioning in edit dialogs and proper rendering of punctuation looks good in 3.0.0 (5a7caea
