### ISSUE TITLE
tN smurf bar links are incorrectly rendered after changing to the Hindi GL, then changing back to English

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#7084]
3.0.0 (5a7caea) 
1. Import a project from USFM. (I used a Hindi phm)
2. Open the project in tN
3. Note that the smurf bar links look correct
![image](https://user-images.githubusercontent.com/8171759/88708786-cf24d680-d0d9-11ea-9c8a-e8e3540d4482.png)
4. Return to the Tools page
5. Change the tN GL to Hindi
6. Load the project in tN (download the needed UGNT when prompted)
7. Note that the smurf bar links still look correct
![image](https://user-images.githubusercontent.com/8171759/88708909-fed3de80-d0d9-11ea-884b-e73b05b44200.png)
8. Return to the Tools page
9. Change the tN GL back to English
10. Load the project in tN
11. Note that the smur bar links now are incorrectly rendered, although they do still work
![image](https://user-images.githubusercontent.com/8171759/88709170-67bb5680-d0da-11ea-9fd4-3c7e140f7c91.png)
12. Import a different usfm project
13. Set the tN GL to English and load the project in tN
14. Note that the links are incorrectly displayed.
At this point I have not been able to get the links to again show properly on either new (from USFM) or existing projects. Restarting or reinstalling tC or rebooting don't help. 
I see the same result on both of my MacBooks.
On my Windows machine the links show incorrectly never having changed the GL to Hindi.

I'm not if it's related, but I'm seeing an additional problem if the smurf bar contains multiple links.
![image](https://user-images.githubusercontent.com/8171759/88725577-ef608f80-d0f1-11ea-964e-c53522934e8e.png)

Might the build or en-tn have been corrupted somehow? 
Additional info:
It doesn't seem to be en-tn. 
I did a clean install from a build from a week ago and everything was fine. 
I downloaded the en updates and everything was still fine. 
I upgraded to the latest RC build 3.0.0 (5a7caea) and everything was still fine.
I deleted both of the translationCore folders and did a clean install.
It is now broken again.

**Comment by PhotoNomad0** [comment]
Note: work on issue https://github.com/unfoldingWord/translationCore/issues/7074 exposed a bug that when processing tN links, the tA was not automatically unzipped.

**Comment by PhotoNomad0** [comment]
@cckozie - Working in translationCore 3.0.0 (74b79f2) 

Just note that you may have to switch tN GL to hi and back to en to force latest links to load if you have already opened the project with latest en_tn.

**Comment by cckozie** [comment]
Fixed in 3.0.0 (74b79f2)
