### ISSUE TITLE
Check manifest for default aligned text for GL Quote

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/translationCore#7102]
### User Story

As a GL team, we want to be able to specify the name of my chosen checking text and use the new naming convention of GLT so that the GL Quote in both TN and TW are the text of our choosing.

### Features / Specifications

- [ ] check the 'related' field in the the manifest of tN and tW for aligned GL Bibles. Top of the list takes precedence. Ignore bibles in GLs other than current gl (e.g. if current gl is russian we ignore 'en/ult', 'en/ust', etc.).
- [ ] check for a GLT of that language.
- [ ] Fall back to previous logic

### Definition of Done

- [ ] A team member with edit permissions for the manifest of TN or TW can add the GL text that they want to be used for GL quotes
- [ ] The text that's added to the manifest is chosen by default for that GL by tC.

**Comment by PhotoNomad0** [comment]
Verified in Version 3.0.1 (343c98b)

**Comment by cckozie** [comment]
Looks good in 3.0.1 (343c98b)
