### ISSUE TITLE
Check for software updates incorrectly reports running latest version

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#7103]
**[Verifying that the check for software updates works should be added to the tC Release issue template]**

When running tC 2.2.0 and Actions/Check for software updates is clicked, it returns this message even though 3.0 has been released. I don't know when this quit working, or if the problem is on the client or server side. I now tested it back to 1.1.4 and found it not to work. There is nothing related in the log file or console.
![image](https://user-images.githubusercontent.com/8171759/95255311-c988f280-07e6-11eb-94de-c442c56bd40f.png)

**Comment by birchamp** [comment]
@PhotoNomad0 Could you give us a estimate on what this would take to track down?

**Comment by PhotoNomad0** [comment]
Mac install file name should now include `macos-x64`.  checked in Version 3.0.1 (343c98b)

And renamed file in latest release so older mac installs can find latest version.

**Comment by cckozie** [comment]
After 3.0.1 was posted to the releases page, tested when running 3.0.0 (74b79f2) and it reports still reports Your are running the latest...
When testing from 2.1.2, it reports "There is a new version of translationCore.
You are running version 2.1.2. Version v3.0.0 is now available."

**Comment by cckozie** [comment]
Looks good now.
