### ISSUE TITLE
The 'You are about to transmit data over the Internet' warning is not displayed before downloading a previous version of the original language for tN checks

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#7120]
3.0
If the user selects a GL for tN that requires an older version of the original language than is on the system, he is prompted that a download of that version is required. When the user clicks Download on that alert, the Internet warning alert should be displayed unless he has previous clicked the Do not show again checkbox during the current session.

DoD: The user is presented with the internet warning alert after he is prompted to download a different OrigL.

**Comment by elsylambert** [comment]
Works as expected in translationCore 3.0.2 (f02bb06). Now getting "Access to Internet "warning after the usr is prompted for version difference.

**Comment by gayathrihayden** [comment]
Fix tested in tC 3.0.2 (ccf6be6) and works fine. 
Tested as part of [#7121](https://github.com/unfoldingWord/translationCore/issues/7121)
