### ISSUE TITLE
tC needs to allow more than 2 versions of the original languages to be on the system simultaneously

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#7121]
3.0 (Field reported by Russ Perry)
The tN checking tool is sensitive to the version of the original language that was used to create the checks in each GL. If the version of the original language needed for the GL selected for tN checking is not on the system, tC will prompt the user indicating such and then give him the opportunity to download the required version. If there are already 2 other versions of that original language on the computer, after the download tC errantly deletes the other non-latest version. Thus, if a user is working with more than 2 GL's that each use a different version that is not the latest version on the system, one of the older versions will be deleted. This is very undesirable!

**Comment by birchamp** [comment]
@da1nerd and @cckozie does this seem related to #7140?

**Comment by da1nerd** [comment]
@birchamp related, but different issues from my understanding.

**Comment by cckozie** [comment]
@birchamp @da1nerd - It is a different issue. In this case tC correctly detects that it needs a previous version of the original language, so it prompts the user and then downloads it. The problem is that if there is currently more than one version of that original language in the resources folder, it will replace one of them with the newly downloaded one. So when the user goes back to working on a tN that needs the deleted version, the prompt for download is repeated. etc. etc. etc.

**Comment by da1nerd** [comment]
This should now be fixed in https://github.com/unfoldingWord/translationCore/pull/7155

**Comment by PhotoNomad0** [comment]
@da1nerd - In testing it appears to leave 2 ugnt versions out of 4 on my PC!

**Comment by elsylambert** [comment]
translationCore 3.0.2 (f02bb06). Seeing 2 versions of Original language simultaneously on the system.

**Comment by gayathrihayden** [comment]
Fix tested in tC 3.0.2 (ccf6be6) and works fine. 

Reference screenshots:
 
![Previous version of OL](https://user-images.githubusercontent.com/74929193/142054026-75098057-e51b-496f-b1d1-f3dde378a39c.PNG)

![Diff version of UGNT](https://user-images.githubusercontent.com/74929193/142054049-18cac36d-449b-497a-aa4b-6f706fdc1de0.PNG)

![Transmit data over the internet warning](https://user-images.githubusercontent.com/74929193/142054070-7c528fbc-17fe-40be-8590-cd4959cf1e9f.PNG)

Switching between GLs no longer presented the alert to (force) download the different version of the OL. The system retains multiple versions of the OL as seen in the file explorer. 

![Multiple versions of OL on the system-file explorer](https://user-images.githubusercontent.com/74929193/142054091-405c2086-5175-4805-aaf9-14be48130577.png)
