### ISSUE TITLE
Link problems on 3.0.1 releases page and translationCore.com

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#7122]
ISSUE 1:
In the section
"How to Install
The installation files are available on the translationCore v3.0.1 release page or go to https://translationcore.com."
the release page points to
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/0afa1743-e724-4672-96e9-7cc09214a15c)

ISSUE 2:
The link to download the Mac build after clicking the Download button on translationCore.com generates a 404 error.

ISSUE 3:
The link to download the Windows and Linux builds after clicking the Download button on translationCore.com download tC 3.0.0 instead of 3.0.1

**Comment by birchamp** [comment]
@cckozie I believe I've fixed all 3 of these issues now.

**Comment by cckozie** [comment]
The 3 issues have been fixed.
