### ISSUE TITLE
Build tC using the latest String-Punctuation-tokenizer

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/translationCore#7129]
tC is using an outdated tokenizer.  The new tokenizer handles the original languages better.  tC should be built using the latest version of the string-punctuation tokenizer. 

See issue #6831

**Comment by birchamp** [comment]
@da1nerd another issue to add in to your work on tC

**Comment by da1nerd** [comment]
@birchamp should this still be assigned to me?

**Comment by birchamp** [comment]
Updating the String-Punctuation-tokenizer will guarantee that tC has to be completely regression tested. Before @da1nerd works on this, we need to know from @cckozie based on the issues that have already been done, will full regression testing already be needed?

**Comment by da1nerd** [comment]
@birchamp I had to update the string-puctuation-tokenizer as part of #7156 so I think this task is no longer relevant.
