### ISSUE TITLE
New tW (Primary) Tool

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#713]
- [ ] New Design
- [ ] Updated Content (remove false positives/negatives)

**Comment by Thajny** [comment]
Quick note: most of the tool related UI (Step 1 and step 2 panes) are out of date, this is just to show the side menu (left).

![image 2017-02-28 at 3 34 01 pm](https://cloud.githubusercontent.com/assets/21183377/23437126/8f0dee20-fdd2-11e6-8967-d8acf439bfb1.png)

This is an example of the "default" view. The side menu is expanded.

----------------------

![image 2017-02-28 at 4 30 30 pm](https://cloud.githubusercontent.com/assets/21183377/23437315/4855e1f8-fdd3-11e6-92e3-019d02d76c24.png)

Example of the side drawer being collapsed.

A few things to note for this mockup:
• there is a thin black line that shows up on the far left edge of the screen for where the menu comes from. Subtle, but it's there to give the user a small amount of context for what to expect when they expand it again.
• the little tab box thing has slightly rounded edges (2px).
