### ISSUE TITLE
Include new TN categories when parent category is checked. 

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/translationCore#7133]
When a user chooses all checks under Figures of Speech, all checks including new categories like 'figs-quotemarks' should be included.  For instance 'figs-quotemarks' doesn't show up in the 'Figures of Speech' and 'grammar-connect-logic-goal' doesn't show up in the 'Grammar' category. Both show up in the 'Other' category.  We believe this means that tC is not processing new types of checks and is simply placing all new checks in the 'Other' category.  

**DoD**: Any TN checks should appear in their appropriate category.

<img width="523" alt="Capto_Capture 2021-06-23_08-57-25_AM" src="https://user-images.githubusercontent.com/10272744/123100794-6cc77980-d401-11eb-822e-be8edf738170.png">

See Zulip thread: https://unfoldingword.zulipchat.com/#narrow/stream/209457-SOFTWARE--.20UR/topic/Helpdesk/near/219501248

**Comment by da1nerd** [comment]
@birchamp do you have a sample project I can look at?

**Comment by birchamp** [comment]
@da1nerd added a screenshot

**Comment by da1nerd** [comment]
@birchamp the categories are hard coded here https://github.com/unfoldingWord/tsv-groupdata-parser/blob/master/src/tNoteGroupIdCategorization.js#L4  is there a way to determine these dynamically, or do you just want to update this hard coded list?

In either case, I'll need help determining how to categorize the new checks. Is there a definition of those somewhere?

**Comment by birchamp** [comment]
@da1nerd  I don't believe there is a definition other than the TA repo itself.  In the tNoteGroupIDCategorization.js file it doesn't list "Quote Markings" but it shows up in the TN card above. Where's that coming from?

**Comment by cckozie** [comment]
@da1nerd 
I think the categories and sub-categories come from scanning the translationNotes resources folders; e.g. 
/Users/cckozie/translationCore/resources/en/translationHelps/translationNotes/v48/other/groups/luk/figs-quotemarks.json

**Comment by birchamp** [comment]
Here's my project, but any new 1TI project should do it. 
[en_kjv_1ti_book.zip](https://github.com/unfoldingWord/translationCore/files/6730223/en_kjv_1ti_book.zip)

**Comment by da1nerd** [comment]
@birchamp 
> I don't believe there is a definition other than the TA repo itself. In the tNoteGroupIDCategorization.js file it doesn't list "Quote Markings" but it shows up in the TN card above. Where's that coming from?

Undefined things are automatically placed in "Other"

**Comment by da1nerd** [comment]
the original code here was hardcoded. The only realistic way to make this dynamic would be to add this information to the source content. And before that we'd need to automatically parse that information out of the TA repo to include in the source content. 

That will require some considerable development time for something that is not frequently updated. So I'm just going to add two lines to https://github.com/unfoldingWord/tsv-groupdata-parser/blob/master/src/tNoteGroupIdCategorization.js#L4 and call it good for now. 

I suggest starting a new feature request if it is still desirable to update this information automatomatically.

**Comment by da1nerd** [comment]
should these be placed under grammar as well? 
```
    'grammar-connect-exceptions': 'Connect - Exception Clauses',
    'grammar-connect-logic-contrast': 'Connect - Contrast Relationship',
    'grammar-connect-logic-result': 'Connect - Reason-and-Result Relationship',
```

**Comment by birchamp** [comment]
yes, they should be added to grammar @da1nerd

**Comment by elsylambert** [comment]
Works fine in translationCore 3.0.2 (f02bb06). The TN categories are shown on the Card are coming from Resources>TranslationHelps>tN>categories. Works as expected.
