### ISSUE TITLE
New tN (Primary) Tool

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#714]
- [ ] New Design
- [ ] Updated Content (divide essential/other)

**Comment by Thajny** [comment]
**Prototype link**
https://xd.adobe.com/view/ce322171-3472-4b46-a225-60a933b93fea/

**Notes**
- The transition effect is just a default thing XD does, do not do that
- Clicking on the siders for _side menu_ and _tHelps pane_ should *not* close both at the same time. They are independent of each other. In the prototype it just hides and expands both at the same time. Don't do that
- I added extra navigation in the _Scripture Modal Popup_ to better illustrate what I was thinking could be done with it. Do not implement them (they say 1/3 modal, 2/3 modal, 3/3modal).
- Theres a lot of functionality in the prototype missing, but theres enough to go through all the screens.
- Blurry background on modal is optional, just so long as it darkens the screen below it its fine.
- Clicking on the text field in _comment mode_ will populate it with an example. This opens up the ability for the user to save changes. This similar for how _edit_ works.
- The screenshot for translationNotes is not included in the prototype, but I am including a screenshot of that below. Theres a **very** minor difference between the two in the _check info_ card where the "see more" text changes slightly.
- lastly, if you have questions about something, just lemme know.

**Comment by Thajny** [comment]
**TranslationNotes Mockup**
![image 2017-03-07 at 3 42 52 pm](https://cloud.githubusercontent.com/assets/21183377/23679224/c8bdaac8-034c-11e7-9087-a57e5ea7443b.png)
