### ISSUE TITLE
tN selections get misplaced when the user changes the gateway language if a verse has multiple checks in the same category

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#7153]
3.0.1 (343c98b)
This was field reported by the India team. See this video beginning at 30:50.
These steps cause a somewhat different result, but I think it is the same problem.
To replicate:
1. Update English, Hindi, and Greek resources
2. Import this project [https://app.zenhub.com/files/65028237/40c8afb4-9159-41db-99d8-026c85796a7d/download](https://app.zenhub.com/files/65028237/40c8afb4-9159-41db-99d8-026c85796a7d/download)
3. Select Hindi as the GL for tN
4. Open the project in tN
5. Make selections for the checks as per this screenshot:
![Screen Shot 2021-06-10 at 8.58.53 PM.jpg](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/9f032175-6835-4730-a1f9-bb7079bf9e2d)
6. Return to the Tools page
7. Select English as the GL
8. Open the project in tN
9. Note that 2 of the checks now have the same selection:
![Screen Shot 2021-06-10 at 8 59 22 PM](https://user-images.githubusercontent.com/8171759/121621571-03735e00-ca32-11eb-98bb-c313a2ca0abf.jpg)

**Comment by elsylambert** [comment]
Not seeing this issue in translationCore 3.1.0 (a7d2893). Multiple tN checks are saved correctly to the respective selections when the GL is switched.
<img width="1442" alt="Screen Shot 2022-01-13 at 8 38 01 AM" src="https://user-images.githubusercontent.com/51806180/149340370-a4a87f09-ad57-4a6d-8409-ea005144d9c1.png">
