### ISSUE TITLE
Unable to upload to DCS due to git index.lock file in project's .git directory

### ISSUE THREAD

**Issue by richmahn** [unfoldingWord/translationCore#7159]
### Description

There is a known issue that a user of tC v3.0.1 cannot upload their project due to the lock file (index.lock) not being removed from a previous git process. This file is located in `<user dir>/translationCore/projects/<project>/.git`. If this index.lock exists, no other git processes, including a `git push` can be executed.

This was noticed in issue https://github.com/unfoldingWord/translationCore/issues/6927 and also through forums.door43.org in a Helpdesk issue sent by Grant Ailie:

> For the past 2 weeks when I have tried to save/upload my current 2 Samuel ULT work in tC to Door 43 I have not been able to but rather have received the “unkown communication error” message. In the past the “upload to Door 43” option has always worked for me, or if I did encounter a communications error message it always worked again within a day or so. I have included my application logs.
> 
> App Version:
> 3.0.1 (343c98b)
> 
> Name: Grant_Ailie

### Steps to Reproduce

1. To simulate, just create a index.lock in a project's .git directory (format given in Description) which can be an empty file:
  Example, from terminal window on Mac, which starts from the user's directory: 
  `touch translationCore/projects/en_ult_2ti_book/.git/index.lock`
![image](https://user-images.githubusercontent.com/2839925/124829182-439d0200-df46-11eb-8797-2d26bff2c854.png)
2. Open translationCore v3.0.1 and go to the list of projects.
3. Click the project's `...` menu and select "Upload to Door43"
![image](https://user-images.githubusercontent.com/2839925/124829048-151f2700-df46-11eb-87d6-9b9d5259681e.png)
4. See error:
![image](https://user-images.githubusercontent.com/2839925/124829209-50b9f100-df46-11eb-8c38-3a8014c35c3d.png)

**Expected behavior:**

It appears a previous git process crashed, didn't finish, or something in that regards. tC probably should remove all index.lock files when starting up and/or look for the file if the above error persists and ask if the user wants to delete the file and if they are sure (no other uploads in progress).

See https://github.com/unfoldingWord/translationCore/issues/6927#issuecomment-630191744 for @PhotoNomad0's advice to how it should behave.

**Actual behavior:**

It stop the user from ever being able to upload. According to Grant's email above, maybe somehow, over time, the index.lock gets removed, maybe by git if it is a few days old it assume it is from a dead process.

### Context

Keeps users from getting their content uploaded to DCS, and we don't want to hinder that!

**Environment**
| Tech         | Version |
|--------------|---------|
| tc           | v3.0.1  |
| build #      |   343c98b    |
| OS           |    MacOS  |

### Additional info:

Log file sent by Grant of what the actual error was:

> 14:23:04 GMT-0500 (Central Daylight Time) ERROR: v3.0.1 (343c98b): Unknown error:,fatal: Unable to create '/Users/grantailie/translationCore/projects/en_ult_2sa_book/.git/index.lock': File exists.
> 
> Another git process seems to be running in this repository, e.g.
> an editor opened by 'git commit'. Please make sure all processes
> are terminated then try again. If it still fails, a git process
> may have crashed in this repository earlier:
> remove the file manually to continue.

[log.zip](https://github.com/unfoldingWord/translationCore/files/6780142/log.zip)

**Comment by richmahn** [comment]
Note, workaround for user added to the bottom of this Forum article: https://forum.door43.org/t/problems-uploading-tc-or-ts/508

**Comment by PhotoNomad0** [comment]
@birchamp I suggest that we try to delete the lock file on upload if it exists.  The file will delete if a git process is not actively using it.  If we can't delete (likely because git has it open), we suggest that they reboot the Computer and try again to upload.

**Comment by PhotoNomad0** [comment]
@birchamp @elsylambert Here is the prototype message that will be shown if we can't remove the lock file:

![Screen Shot 2021-11-15 at 2 16 45 PM](https://user-images.githubusercontent.com/14238574/141840795-daff4ee6-7b5b-48a2-8d32-fa663682ee8e.png)

**Comment by PhotoNomad0** [comment]
OK, updated to:

![Screen Shot 2021-11-15 at 2 49 49 PM](https://user-images.githubusercontent.com/14238574/141844833-e1e7bfe3-0f4d-45dc-9099-9d8e5ce83c50.png)

**Comment by PhotoNomad0** [comment]
@elsylambert verified in translationCore 3.0.2 (ccf6be6)

You can simulate a git lock by creating a lock file: `touch ~/translationCore/projects/<project_name>/.git/index.lock`

**Comment by PhotoNomad0** [comment]
found a command to make the lock not deletable if you want to see the warning dialog: `chflags uchg  ~/translationCore/projects/<project_name>/.git/index.lock` then you need to remember to make it deletable to enable upload again `chflags nouchg  ~/translationCore/projects/<project_name>/.git/index.lock`

**Comment by elsylambert** [comment]
translationCore 3.0.2 (c8c2941). Simulated with index.lock file. tC deleted the lock file and I was able to upload to D43 without a failure.

**Comment by elsylambert** [comment]
translationCore 3.0.2 (c8c2941). Here is the screenshot of the Alert box.
![image](https://user-images.githubusercontent.com/51806180/142643040-7c5fb0e9-56fc-4786-80bb-01b050a4ceb4.png)
Can the Modal be modified so that it does not add a horizontal scroll bar? @PhotoNomad0 
Wrote this separately in #7192

**Comment by elsylambert** [comment]
Works as expected.

**Comment by gayathrihayden** [comment]
Fix tested in tC 3.0.2 (0d9cd25) and works fine. 

- Created an index.lock file for the project that needs to be uploaded to Door43. 
- While the project is being loaded to be uploaded to Door43, the index.lock file gets removed under the .git directory (username > tC > projects > <projectname> .git) and the upload to Door43 is successful.
