### ISSUE TITLE
Unable to import online project

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/translationCore#7162]
Issue:
---
Users need to be warned that a project doesn't exist.
Error should read: *The project <project_url> does not exist, please select a different project.*

Details:
---
Encountered while testing  #7158 
- When trying to Import online project https://git.door43.org/lrsallee/en_ult_1ti_book , the spinner just goes on with no success. Had to close tC. Please see console.
<img width="1641" alt="Screen Shot 2021-08-10 at 5 48 57 PM" src="https://user-images.githubusercontent.com/51806180/128939983-a02d41c5-81c9-4ca8-993a-62ead33340b4.png">

**Comment by elsylambert** [comment]
<img width="1576" alt="Screen Shot 2021-08-24 at 9 10 00 AM" src="https://user-images.githubusercontent.com/51806180/130622203-a00f6dae-95e2-47b1-9b5a-0e285a3cc7de.png">

**Comment by birchamp** [comment]
@da1nerd could you take a look at this?

**Comment by da1nerd** [comment]
That repository does not exist, so naturally tC had trouble downloading it :wink: 
It would probably be helpful to let the user know that the repo could not be found. Shall I add that @birchamp ?

**Comment by birchamp** [comment]
@da1nerd that depends on how long it will take to implement.

**Comment by da1nerd** [comment]
@birchamp I don't think it would take more than an hour.

**Comment by birchamp** [comment]
@da1nerd yes, go ahead and do that, I've updated the issue with the wording for the warning.

**Comment by PhotoNomad0** [comment]
@birchamp, @da1nerd  This is an exception being thrown in logging in the updated electronite that is causing the hang.  Seems to happen in production build and not develop.  Testing a work-around.

**Comment by PhotoNomad0** [comment]
@elsylambert @birchamp - the current localized error message reads "The URL ${project_url} does not reference a valid project.".  We could add the new one Elsy suggested, but we won't have localized strings for a while.

**Comment by PhotoNomad0** [comment]
Here would be the full message: 

The download of project https://git.door43.org/lrsallee/en_ult_1ti_book failed. The URL 'https://git.door43.org/lrsallee/en_ult_1ti_book' does not reference a valid project.

**Comment by PhotoNomad0** [comment]
![Screen Shot 2021-11-08 at 11 54 02 AM](https://user-images.githubusercontent.com/14238574/140784461-97b1fe44-e23d-4ad6-8e6f-8b59901cab7c.png)

**Comment by PhotoNomad0** [comment]
@elsylambert Have fix in translationCore 3.0.2 (d24193f).  Will show message like above ^^^

**Comment by elsylambert** [comment]
translationCore 3.0.2 (38258ea). This build seems to be the latest and I am seeing a different message in the modal. Please see the snapshot:
<img width="1067" alt="Screen Shot 2021-11-09 at 2 44 29 PM" src="https://user-images.githubusercontent.com/51806180/140995063-3c3d9d2b-b4b7-4113-94fb-5e4c04ef12d0.png">
Here is the log file:
[Tue Nov 09 2021.log](https://github.com/unfoldingWord/translationCore/files/7507656/Tue.Nov.09.2021.log)

**Comment by PhotoNomad0** [comment]
@elsylambert Verified fix in translationCore 3.0.2 (18ad847).  It's working now on my test PC.

**Comment by elsylambert** [comment]
Looks good in translationCore 3.0.2 (18ad847). Import of an invalid project https://git.door43.org/lrsallee/en_ult_1ti_book  threw a correct message that the project was invalid and it failed to download. Works as expected.
