### ISSUE TITLE
update git install

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/translationCore#7166]
The current tC installer calls an older git install that no longer works in Win10. 

The installer needs to be updated to call the latest stable git install.

**Comment by birchamp** [comment]
@PhotoNomad0 can you check this issue to confirm it's correct.

**Comment by PhotoNomad0** [comment]
updated windows git version to `git version 2.35.1.windows.2`

**Comment by PhotoNomad0** [comment]
@elsylambert Latest tCore dev build has latest git version for windows ^^^

**Comment by elsylambert** [comment]
Works as expected in Version 3.2.0 (1aea3cc) . Git is updated to  git version 2.35.1.windows.2.
