### ISSUE TITLE
Epic for Editing and Aligning Verse Ranges

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/translationCore#7167]
**Feature Canvas:** https://docs.google.com/document/d/1-76Ysa_AurM3yQCyajoEqFw4ZzcJvdC5DCb7xE285Rw/edit

**ClickUp:** https://app.clickup.com/t/1jfq4cj

**Sample text for testing:** gal 1:1 in UST

**Existing issues that affect this need:** 

**TODO - tCore Updates Needed:**
- scripture pane:
  - update to show verse spans when selected verse is within a span
  - update to show all verses in the range when selected verse is a verse span
- enhanced scripture pane:
  - update to show verse spans
  - update to edit verse spans
- word alignment:
  - glom original language verses together for ease of alignment
  - add support for verse spans in on edit notifications to invalidate alignments (in checking-tool-wrapper?)
  - API: getInvalidChecks(), getProgress(), _initChapterAlignments(), validateVerse(), getGlobalAlignmentMemory() , <= add verse span support
  - misc: indexChapterAlignments(), migrateChapterAlignments() <= add verse span support
- tN & tW:
  - add support for verse spans in on edit notifications to invalidate notes (in checking-tool-wrapper?)
  - make sure selections work with verse spans
    - display verse span in check area
    - on selection save, use verse span  
- tCore:
  - remove warnings of missing verses when there are verse spans on project import and project selection
  - export - add refs on verse span alignments
  - import - parse refs for verse spans
    - also overwrite merges
  - add verse span support checking for external edits on WA tool open
- checking-tool-wrapper:
  - fix verse span support for edits in misc.: 
    - look at groupsDataActions.verifyGroupDataMatchesWithFs()
    - look at verseEditActions.editTargetVerse()
      - fix problem parseInt converts verse span to number
- what is the impact on csv's, since currently verse is a number?
- set min compatible version for tCore to 3.1.0

- **General** - examine places: 
  - where verse is converted to number: parseInt, isNaN
  - check for loops that iterate through verses numerically
  - check for verse proptypes that are numbers only in react components

**Comment by birchamp** [comment]
@birchamp add in canvas and scripture

**Comment by birchamp** [comment]
@mannycolon @PhotoNomad0  Please review these mockups:

- Alignment:
![tC-Alignment](https://user-images.githubusercontent.com/10272744/135105279-0d746a8c-c90f-4d47-8120-b21dac8c2ec0.png)

- Expanded/multi-verse view
![tC-Multi-Verse](https://user-images.githubusercontent.com/10272744/135105408-848030dc-f463-43c4-8a1f-1aa8caae3f46.png)

- Edit scripture
![tC-Verse-Edit](https://user-images.githubusercontent.com/10272744/135105480-540faba4-63e2-4af4-aaa0-b454668a5ed6.png)

**Comment by PhotoNomad0** [comment]
@birchamp Some of these can be done, but we were talking about minimal UI changes to make this doable in a short time.  Currently the Expanded scripture pane is laid out in rows, so it is much easier to do this layout:

![Screen Shot 2021-09-27 at 9 41 57 AM](https://user-images.githubusercontent.com/14238574/135107653-486a9d36-99a9-4a78-ac89-40edaeb2a363.png)

Still looking into how we could do the regular scripture pane without a lot of refactoring of UI.  Currently I can make all the bibles show up as verse spans, such as:

![Screen Shot 2021-09-28 at 10 35 35 AM](https://user-images.githubusercontent.com/14238574/135109238-55d6d9d5-1646-49e9-88f3-166a76f43a25.png)

but that is not ideal.  Looking at options.

**Comment by birchamp** [comment]
Thanks for the heads up on that. @PhotoNomad0

**Comment by birchamp** [comment]
@PhotoNomad0 Could you put a verse number mid-text in the UGNT where the next verse starts? 
So leave the reference as '1:1-2', but also have a bold '2' where the 2nd verse begins.

**Comment by PhotoNomad0** [comment]
@birchamp @mannycolon - I have succeeded in getting a rough prototype working for the UI.  Still have a bunch of business logic issues to resolve.  Here is the rough UI for alignment now:

![Screen Shot 2021-09-29 at 4 46 29 PM](https://user-images.githubusercontent.com/14238574/135460988-ca9e7609-3fd2-4ac7-90df-d7dd8266d78c.png)

**Comment by PhotoNomad0** [comment]
> @PhotoNomad0 Could you put a verse number mid-text in the UGNT where the next verse starts? So leave the reference as '1:1-2', but also have a bold '2' where the 2nd verse begins.

I think in this case I can place two separate verses here (e.g. 1:1 and 1:2).  I'll look at it later to see what might be easier.  For now I just have the 1:2 before the second verse.  See screen above.

**Comment by PhotoNomad0** [comment]
@birchamp @elsylambert - I have a very rough prototype if you want to take a look: https://github.com/unfoldingWord/translationCore/actions/runs/1304694194

**Comment by PhotoNomad0** [comment]
**Notes:**
_Repos with verse spans:_
- https://git.door43.org/christopherrsmith/en_ust_act_book
- https://git.door43.org/lrsallee/en_ust_luk_book
- https://git.door43.org/lrsallee/en_ust_gal_book
- https://git.door43.org/lrsallee/en_ust_jos_book
- https://git.door43.org/MattCarlton/en_ust_gen_book - has a verse span of 4, see chapter 36

**Comment by elsylambert** [comment]
Looks good in translationCore 3.1.0 (a7d2893).
