### ISSUE TITLE
Add Verse Span Support to WA tool

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#7171]
## Summary

- word alignment:
  - glom original language verses together for ease of alignment
  - add support for verse spans in on edit notifications to invalidate alignments (in checking-tool-wrapper?)
  - API: getInvalidChecks(), getProgress(), _initChapterAlignments(), validateVerse(), getGlobalAlignmentMemory() , <= add verse span support
  - misc: indexChapterAlignments(), migrateChapterAlignments() <= add verse span support
  - Add Verse Span Support to Scripture Pane

- set min compatible version for tCore to 3.1.0

## Motivation

Why are we doing this? What use cases does it support? What is the expected outcome?

## Specifications (If applicable)
A clear and concise description of the details about the feature that may or may not be obvious

**Comment by PhotoNomad0** [comment]
@elsylambert @birchamp Is this UI sufficient for the WA tool?

<img width="1433" alt="Screen Shot 2021-10-11 at 7 51 00 AM" src="https://user-images.githubusercontent.com/14238574/136789419-79e7a7f2-9aaf-4021-8405-569c2beb60ad.png">


<img width="1319" alt="Screen Shot 2021-10-11 at 8 23 12 AM" src="https://user-images.githubusercontent.com/14238574/136789511-7ae3ad0b-f72e-46e3-9470-b23711129065.png">

**Comment by PhotoNomad0** [comment]
@elsylambert Verified in translationCore 3.1.0 (e04e19d)

**Comment by PhotoNomad0** [comment]
@elsylambert - I am not seeing a problem with upgrading projects from older tC, started by deleting resources folder, launching tC 3.0.1, and importing https://git.door43.org/lrsallee/en_ust_gal_book.  Just shows empty verses:

https://user-images.githubusercontent.com/14238574/137959322-7a3e245a-2cf7-4226-8d38-faad6129516a.mov

Then launched tCore 3.1.0 -  can see the versespans now:


https://user-images.githubusercontent.com/14238574/137959622-6df397db-0d39-4d70-9096-070190dfaebf.mov

**Comment by elsylambert** [comment]
Looks good and works as expected in translationCore 3.1.0 (8d50789). The project that have the verse spans in them, WA tool displays in the scripture pane, displays all the words in word bank and shows in the expanded scripture pane.
