### ISSUE TITLE
Add Verse Span support to tW and tN

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#7172]
## Summary

- tN & tW:
  - add support for verse spans in on edit notifications to invalidate notes (in checking-tool-wrapper?)
  - make sure selections work with verse spans
    - display verse span in check area
    - on selection save, use verse span  
- checking-tool-wrapper:
  - fix verse span support for edits in misc.: 
    - look at groupsDataActions.verifyGroupDataMatchesWithFs()
    - look at verseEditActions.editTargetVerse()
      - fix problem parseInt converts verse span to number
- what is the impact on csv's, since currently verse is a number?
  - feedback from content team is that csv export is not really used except for manual review and training, so putting the verse span in the verse column will not impact things. 

## Motivation

Why are we doing this? What use cases does it support? What is the expected outcome?

## Specifications (If applicable)
A clear and concise description of the details about the feature that may or may not be obvious

**Comment by PhotoNomad0** [comment]
@elsylambert This should be also working in translationCore 3.1.0 (e04e19d)

**Comment by elsylambert** [comment]
translationCore 3.1.0 (8d50789). The display looks fine in scripture pane and selection area. But I do not see edit notifications to invalidate notes. 
I made selections in tN and tW for the verses that has verse spans and then went to WA and edited the verse to invalidate the selections. When I reopened tN and TW, I do not see the notifications. I see that the edits are shown and the selections are removed but the translation for area shows the old selections.
![image](https://user-images.githubusercontent.com/51806180/149165345-6e9eb8bb-2ba8-4bdc-becd-f553f979eaf1.png)

![image](https://user-images.githubusercontent.com/51806180/149165396-fec4d112-b438-493a-af82-d61cda291789.png)
I made selections for "the fellow believers " and saved it. then edited the verse to "the brothers"

**Comment by elsylambert** [comment]
Verified in translationCore 3.1.0 (a7d2893). Seeing the invalidation messages as expected when a selection is invalidated. Seeing the broken chain link as well on the cards.
<img width="810" alt="Screen Shot 2022-01-13 at 7 56 45 AM" src="https://user-images.githubusercontent.com/51806180/149335535-47c80920-8a57-42e8-a6e1-c825c07e646d.png">
<img width="715" alt="Screen Shot 2022-01-13 at 7 57 13 AM" src="https://user-images.githubusercontent.com/51806180/149335544-9c460fd7-c619-4937-b474-e2d7b73a314b.png">
<img width="779" alt="Screen Shot 2022-01-13 at 8 00 35 AM" src="https://user-images.githubusercontent.com/51806180/149335561-a9d9ab79-4bcd-4e15-a14b-66c621c72113.png">
<img width="1160" alt="Screen Shot 2022-01-13 at 8 00 51 AM" src="https://user-images.githubusercontent.com/51806180/149335575-db63201e-4368-4321-9e14-ca9d50cef4c8.png">
