### ISSUE TITLE
Remove missing verse warnings for Verse Spans

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#7173]
## Summary

  - remove warnings of missing verses when there are verse spans on project import and project selection

## Motivation

Why are we doing this? What use cases does it support? What is the expected outcome?

## Specifications (If applicable)
A clear and concise description of the details about the feature that may or may not be obvious

**Comment by PhotoNomad0** [comment]
**Notes:**
- it looks like the fix will need to be in MissingVersesHelpers.getMissingVerses()

**Comment by elsylambert** [comment]
Not seeing the Missing verse warnings on importing the projects with verse spans in translationCore 3.1.0 (8d50789).
