### ISSUE TITLE
 Explore and document storage of resources of multiple resources for the same language

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/translationCore#7187]
Currently, a language can only have one of each resource.  CatalogNext allows anyone to release a resource, so there could be multiple per language.

Note: versions could be in the same path, similar to how OrigL works?

**Comment by PhotoNomad0** [comment]
Here are some tCore storage options for handling orgs:

current example ~/translationCore/resources/en/translationHelps/translationNotes/v33

```
option 1 - add org to version:
	translationNotes
		↳ v33_unfoldingWord
		↳ v34_test-org

option 2 - add org to resource ID:
	translationNotes_unfoldingWord
		↳ v33
	translationNotes_test-org
		↳ v34

option 3 - add org as new layer:
	unfoldingWord
		↳ translationNotes
			↳ v33
	test-org
		↳ translationNotes
			↳ v34
```

**Comment by PhotoNomad0** [comment]
From @mannycolon :
> 
> I prefer option 1, we do a lot of filesystem calls in our codebase to check for resources and would prefer not to add an additional directory to overcomplicate this process. What do you think?

We can do that.  We would just have to add the ability to filter by org when getting latest version.

**Comment by mannycolon** [comment]
Sounds good to me!

**Comment by PhotoNomad0** [comment]
I was able to prototype option 1, so I think this issue is finished.
