### ISSUE TITLE
Support 7 Column TSV TN

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/translationCore#7188]
How can we handle 7 column TNs?

What about referencing multiple verses?
How do we show all the verses?
How will the new filenames be handled?

**Comment by birchamp** [comment]
What does the UI do for 2:3-5 vs. 2:3,5 @birchamp @PhotoNomad0

**Comment by birchamp** [comment]
After talking to the content team they have said that they want the verses in the reference range to be displayed, both in the scripture pane and the checking window.

**Comment by PhotoNomad0** [comment]
**Notes:**
Tasks:
- tc-sourcecontent-updater - convert 7 col TSVs to the tsvObject format:
  - parse Reference field into chapter/verse
    - break down references into chunks using `;` as delimiter
      - [x] for each chunk , remove chapter and break down into verseChunks by `,`
      - [x] for each verse chunk, get numeric value for string as verse, if em-dash or dash——-‑
      - [x] save a tsvObject for each verse chunk
      - do we need to persist the parsed ranges?
  - [x] add multiple ref and range support when parsing twls
  - [x] add multiple ref and range support when parsing tns
  - [ ] fix tag support in twls? is it sufficient to parse the link for the data?

- tCore
  - [x] fix getAlignedTextFromBible to work with verse spans.
  - [x] fix for tN bug that changing orgs does not trigger changing checks if language stays the same.

- checking tools 
  - [x] show all verses in verse range for a check
  - [x] fix that check shows empty verse for check verse range.
  - [x] fix for tW that verse range not shown in left menu, just the starting verse.

- tsv-group-data-parser
  - [x] tnJsonToGroupData - add support for verse ranges when fetching original verse

- mapping of 7 to 9 column
  - [x] Reference to Chapter, Verse
  - [x] ID unchanged
  - [ ] ~Tags to ?~ <= not needed?
  - [x] SupportReference unchanged
  - [x] Quote to OrigQuote
  - [x] Occurrence unchanged
  - [x] Note to OccurrenceNote

**Test Examples:** 
- 7 column en_tn repo with multi-verses and ranges: https://git.door43.org/test_org/en_tn/src/tag/v0.2
  - made changes to `php 2:1-2,5`, `b1q7`, `figs-explicit` (Assumed Knowledge and Implicit Information) to include testing multiple verses and spans
    - under Assumed Knowledge and Implicit Information should see an entry for 2:1-2 and for 2:5
- twl with multi-verses and ranges: https://git.door43.org/test_org/en_twl/src/tag/v0.2
  - made changes to Christ in **tit** for testing multiple verses and spans
    - under `Christ, Messiah`, 1:1,4;3:6 and 2:13-14

Testing:
- to test tN `7 column TSV` support with verse ranges, download en_ta, en_tn and en_ult in test_org
  - open a php project and in tN tool select en/test_org as GL and launch.  Scroll down to `Assumed Knowledge and Implicit Information`, and should see an entry for 2:1-2 
- to test tW support for verse ranges, download en_tw in test_org
  - open a tit project and in tW tool select en/test_org as GL and launch.  Scroll down to `Christ, Messiah`, and should see entry 2:13-14

 implemented in translationCore 3.2.1 (d0bd234)

**Comment by PhotoNomad0** [comment]
@elsylambert implemented in translationCore 3.2.1 (d0bd234) 

Note that the comma separated verses will be supported in a separate issue: https://github.com/unfoldingWord/translationCore/issues/7322

Testing:
- to test tN `7 column TSV` support with verse ranges, download en_ta, en_tn and en_ult in test_org
  - open a php project and in tN tool select en/test_org as GL and launch.  Scroll down to `Assumed Knowledge and Implicit Information`, and should see an entry for 2:1-2 
- to test tW support for verse ranges, download en_tw in test_org
  - open a tit project and in tW tool select en/test_org as GL and launch.  Scroll down to `Christ, Messiah`, and should see entry 2:13-14

**Comment by elsylambert** [comment]
translationCore 3.2.1 (d0bd234).
Seeing entry for 2:1-2 in tN but not seeing 2:13-14 in Christ, Messiah.
Steps followed:
1. upgraded to translationCore 3.2.1 (d0bd234).
2. downloaded en content for test-org.
3. opened php project and selected test-org english for tN and tW both.
4. tN shows the verse range as mentioned by @PhotoNomad0 in the Testing notes, but not seeing for tW.
![image](https://user-images.githubusercontent.com/51806180/172631029-79a30c04-5ab3-44ef-8aa0-278725a34a77.png)

**Comment by elsylambert** [comment]
Looks good in translationCore 3.2.1 (e7b7769).

**Comment by elsylambert** [comment]
Looks good in translationCore 3.3.0 (ce8ec7b).
