### ISSUE TITLE
Add org support for Scripture Panes and Expanded Scripture Panes 

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#7194]
Allow selection of resources by owner/org.

**Comment by PhotoNomad0** [comment]
@elsylambert - The ability to select bibles by GL in the scripture panes is now present in latest dev build. Example:
![Screen Shot 2022-02-17 at 2 31 07 PM](https://user-images.githubusercontent.com/14238574/154556927-4730e33f-e8ce-4001-a0b3-52c871e3076f.png)

**Comment by elsylambert** [comment]
Looks good in translationCore 3.2.0 (ba8ab1d) .

**Comment by elsylambert** [comment]
Looks good in Windows as well in Version 3.2.0 (1aea3cc)
