### ISSUE TITLE
Implement org support for Tool cards

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#7195]
- discovery of GLs in multiple test orgs
- on tool card display multiple orgs for GL
How should the orgs be displayed?
Are there new implications of choosing a different org's GL resource?

**Comment by PhotoNomad0** [comment]
@elsylambert Give this a try.  Look at https://github.com/unfoldingWord/translationCore/pull/7232 for ideas how to set up for testing.

**Comment by PhotoNomad0** [comment]
![Screen Shot 2022-02-10 at 8 46 30 AM](https://user-images.githubusercontent.com/14238574/153420729-ca862766-f619-42ce-9d9e-5e0bb3540018.png)

**Comment by elsylambert** [comment]
translationCore 3.2.0 (1ed3822)
Not able to select the GLs for tN and tW. @PhotoNomad0 

- downloaded eng Resource
- opened projects>tools page> unable to select the GL for tN and tW.
- log file: 
[Fri Feb 11 2022.log.zip](https://github.com/unfoldingWord/translationCore/files/8051733/Fri.Feb.11.2022.log.zip)

<img width="807" alt="Screen Shot 2022-02-11 at 4 16 53 PM" src="https://user-images.githubusercontent.com/51806180/153671939-86d3f07c-b58c-422c-b294-c07731b3c414.png">
.

**Comment by PhotoNomad0** [comment]
@elsylambert - I deleted the resources folder, ran the latest tC build (same as you tested), and updated all en content, and then tried a couple of gal projects.  It seems to be working for the cases I tried.  There is nothing obvious in the log file as to why it would fail to show GLs.  It looks like you are testing `/Users/elsylitsonlambert/translationCore/projects/en_ultz_gal_book` which looks like the project naming I do.

**Comment by PhotoNomad0** [comment]
Could you point me to your project?

**Comment by elsylambert** [comment]
[en_ulte_act_book.zip](https://github.com/unfoldingWord/translationCore/files/8061366/en_ulte_act_book.zip)
[en_ust_gal_book.zip](https://github.com/unfoldingWord/translationCore/files/8061368/en_ust_gal_book.zip)

**Comment by elsylambert** [comment]
@PhotoNomad0 It is not project specific because I see this problem for all the projects I have. 
The only thing I did not do is the Resources folder deletion before I updated the resources 
- log file: 
[Fri Feb 11 2022.log.zip](https://github.com/unfoldingWord/translationCore/files/8051733/Fri.Feb.11.2022.log.zip)

**Comment by PhotoNomad0** [comment]
@elsylambert - Hmm...the projects are working for me.  Try deleting the resources and see if that helps.

**Comment by PhotoNomad0** [comment]
@elsylambert - Hmm...the projects are working for me.  Try deleting the resources and see if that helps.

**Comment by elsylambert** [comment]
After I deleted the Resources, then launched tC and updated the content, It works fine. User must reload the project to see the GL list in the tools card.
<img width="807" alt="Screen Shot 2022-02-14 at 12 22 09 PM" src="https://user-images.githubusercontent.com/51806180/153914282-28a14684-84bc-4e64-a915-223f5793126f.png">

**Comment by PhotoNomad0** [comment]
@elsylambert Added a Fix in latest dev build for org support in tWords - tWords using ru_gl should work now

**Comment by elsylambert** [comment]
translationCore 3.2.0 (71ca242) 
@PhotoNomad0   log file: 
[Fri Feb 18 2022.log.zip](https://github.com/unfoldingWord/translationCore/files/8099672/Fri.Feb.18.2022.log.zip)

GL list shows Door-43 ru resource but not from ru_gl
![image](https://user-images.githubusercontent.com/51806180/154744313-e4689be5-6067-49bd-b37f-0ecbb42474d9.png)

**Comment by elsylambert** [comment]
translationCore 3.2.0 (ba8ab1d)
1. upgraded to translationCore 3.2.0 (ba8ab1d).
2. Started tC and opened the project. Note that not seeing the GL list to  launch tN and tW.
<img width="687" alt="Screen Shot 2022-03-07 at 2 13 19 PM" src="https://user-images.githubusercontent.com/51806180/157103383-6f7147ed-4910-49d7-b567-941320c80407.png">

[](https://cdn.discordapp.com/attachments/942829365509640192/950475557873786920/Screen_Shot_2022-03-07_at_2.30.23_PM.png)tC is not able to access the Resources for tN and tW. 
I did content download by selecting All the Resources and then cancelled the download as a part of testing #7222- ability to cancel download of Resources when it is taking too long. So after the download is cancelled, I saw that some of the Resources were downloaded and it showed up on the tW tools card.
![image](https://user-images.githubusercontent.com/51806180/157106857-b0f69d7f-185c-4c76-81fe-07df2fef2c59.png)

**Comment by elsylambert** [comment]
@PhotoNomad0 I also downloaded ru_gl Resources (tW and tWLs) but it does not show in the list
<img width="822" alt="Screen Shot 2022-03-07 at 2 48 50 PM" src="https://user-images.githubusercontent.com/51806180/157107158-5c54f9aa-2433-4004-9f86-2e4aaaad1335.png">
.

**Comment by elsylambert** [comment]
Log file:
[Mon Mar 07 2022.log.zip](https://github.com/unfoldingWord/translationCore/files/8200465/Mon.Mar.07.2022.log.zip)

**Comment by PhotoNomad0** [comment]
@elsylambert I found a few small bugs, and also see in the logs that calls to ~~catalog next API~~ old catalog API are failing.

**Comment by PhotoNomad0** [comment]
@elsylambert have new build with fixes: Branch [develop] build [07d98b8]

It's working for me when I upgrade from 3.1.0 or from previous develop build.

**Comment by elsylambert** [comment]
@PhotoNomad0 Did you delete the Resources folder before the upgrade? I upgraded to the latest from the previous develop build and still not seeing the GL list
<img width="1354" alt="Screen Shot 2022-03-08 at 4 38 10 PM" src="https://user-images.githubusercontent.com/51806180/157329535-621668e4-ef57-4d48-965a-f37fd89d6604.png">
.
Log file:
[Tue Mar 08 2022.log.zip](https://github.com/unfoldingWord/translationCore/files/8209806/Tue.Mar.08.2022.log.zip)

**Comment by PhotoNomad0** [comment]
@elsylambert  No, I didn't delete the resources.  And did not see a problem after upgrade.

I realize that I have been just reusing the same project.  I'll retry the upgrade with the zipped project.  Do you open the project in the old tCore build before the upgrade?  From the log I am guessing that you do not.

**Comment by PhotoNomad0** [comment]
@elsylambert I followed these steps:
- deleted resources folder
- copied your ust gal project into the projects folder
- opened older tCore build 71ca242
- went to projects page
- closed tCore
- launched newer tCore build 1bcc4e4
- selected ust gal project and see GLs:

<img width="918" alt="Screen Shot 2022-03-09 at 10 19 44 AM" src="https://user-images.githubusercontent.com/14238574/157473271-09b94965-36b1-4cbc-b54b-e6f1ed8141d0.png">

Not seeing your problem.

I think I am going to need more detailed steps in how you set up the initial conditions.

Also note that upgrading from older dev builds is not a problem the user will see in the field.

The user will be starting with 3.1.0, so when they upgrade to 3.2.0 all the tHelps files in the resources folder (this is a safety measure because the helps format is always changing).  Then the tHelps bundled with tCore will be unzipped into the resources folder.

Maybe we need to meet to talk through this?

**Comment by elsylambert** [comment]
I did this:
1. Upgraded to translationCore 3.2.0 ((1ed3822) 26 days ago.
2. Deleted resources folder and relaunched tC. Updated content and GL list worked fine as expected.
3. Later I  upgraded to translationCore 3.2.0 (71ca242) and it worked fine.
4.  March 7- I upgraded to v3.2.0 (ba8ab1d) and was not seeing the GL list.
Please Note that I did not open the project in the previous version before upgrading to the newer version.

I deleted the Resources folder in the latest build and relaunched tC and now the GL list is available, it shows EN and Hi. I did content update and the othet GL shows in the list.

**Comment by elsylambert** [comment]
I separated ru_gl issue to #7262

**Comment by elsylambert** [comment]
Looks good in translationCore 3.2.0 (1aea3cc) in windows 11.
