### ISSUE TITLE
Design UI for selection of organizations of latest resources to download

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#7196]
Notes:

- use door43 import dialog as pattern for search - show org and language and resource type
- will need to download dependency - verify that tA is downloaded as a dependency for tw, twl, and tn
- can we fall back to using en_twl as basis for all GLs?

- could/should this be phase 2?

**Comment by PhotoNomad0** [comment]
Another option that might be more helpful to the user would be use the existing updated resources dialog that shows the languages with updated resources.  Just add capability to expand the language and select/deselect individual resources. @birchamp @mannycolon 

My thought is to make it work like this rough example from tN tool:
collapsed:
![Screen Shot 2022-01-11 at 8 23 05 AM new](https://user-images.githubusercontent.com/14238574/148957085-32587be0-f1fe-4cdd-80a7-56db398e42f7.png)


expanded:
![Screen Shot 2022-01-11 at 8 21 46 AM new](https://user-images.githubusercontent.com/14238574/148957048-3d1b31d5-9a4b-4c37-90eb-13eadf6170b5.png)


Where collapsed it would just show the languages.  But if you expand a language it would show any updated resources for any owner and let you select/deselect specific resource to download.

**Comment by PhotoNomad0** [comment]
To make use of this approach:

- expanded sourceContentUpdater.getLatestResources(localResourceList, filterByOwner) to return a list of updated resources under each language.  See:
  - https://github.com/unfoldingWord/tc-source-content-updater/blob/feature-mcleanb-7186/src/index.js#L152

- will have to switch updateResources() from using sourceContentUpdater.downloadResources() to a new API: sourceContentUpdater.downloadAllResources(resourcesPath, resources). See:
  - https://github.com/unfoldingWord/tc-source-content-updater/blob/feature-mcleanb-7186/src/index.js#L233

**Comment by elsylambert** [comment]
Local date for a content is broken. It no longer shows the date when the previous content was updated written separately in #7240

**Comment by elsylambert** [comment]
Looks good in translationCore 3.2.0 (1ed3822).
