### ISSUE TITLE
Import latest tHelps

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#720]
- [x] Resources to be updated: 
  - [x] ULB
  - [x] UDB
  - [x] translationWords articles
- [x] For each resource, use a process that can be reused for the same resource in a different language, or for updating the same resource

**Comment by benjore** [comment]
From @jag3773 on 5/11/2017 "Content should be grabbed from https://api.door43.org/v3/catalog.json .  The testing endpoint is https://test-api.door43.org/v3/catalog.json .  This should all be in prod within a couple weeks."

**Comment by mannycolon** [comment]
## Tasks
- [1] Plan implementation.
- [5] write a script to get latest tHelps.
- [5] Write a parser to format data as desired.
- [2] Refactor/clean up thelps updater script.

**Comment by cckozie** [comment]
The tW check group does not always match the tHelps header.
Examples (Eph)
Menu                                        tHelps
appoint, appointed                  appoint, appoints, appointed
believe, believe in, belief         believe, believes, believed, belief
call, calling, called, call out     call, calls, calling, called

We're going to ignore this type of discrepancy for now.

**Comment by mannycolon** [comment]
# QA Tasks
- [3] Debug why tW check group does not always match the tHelps header.
- [3] Fix tW check group that does not always match the tHelps header.

**Comment by cckozie** [comment]
@mannycolon 
[es-419_tit_text_ulb.zip](https://github.com/unfoldingWord-dev/translationCore/files/1243065/es-419_tit_text_ulb.zip)
![image](https://user-images.githubusercontent.com/8171759/29582292-c29ee20a-8741-11e7-8f80-e51276405c95.png)

![image](https://user-images.githubusercontent.com/8171759/29582315-d8c17188-8741-11e7-9cd1-f7f875e453ff.png)

**Comment by cckozie** [comment]
Just noticed that it removed the spaces in my original comment (8 days ago). If you click the edit icon there you can see the separation between the group text in the menu and the header in tHelps. I don't have that project any moe because I couldn't get it to load properly in the current release.

**Comment by jag3773** [comment]
Note that if it is helpful and if @benjore approves, it may be acceptable to just have the first word form in the menu on the left and only have the full word list in the tHelps heading.  The first word listed is usually the "head" (or main) word form and it may help to make the menu on the left cleaner.

**Comment by cckozie** [comment]
1. I don't know if this discrepancy is a problem with the source, API, or tC, but I do see some differences in tW.
![image](https://user-images.githubusercontent.com/8171759/29633105-cc3dcc12-880a-11e7-9481-9595112baa4a.png)

2. Clicking on one of the Bible references, either in the tHelps pane or in the one that comes up after clicking one of the linked words, brings up an empty window.
![image](https://user-images.githubusercontent.com/8171759/29633225-2d4613ac-880b-11e7-9da3-e3df01785b8d.png)

3. There also appear to be some discrepancies in the ULB
![image](https://user-images.githubusercontent.com/8171759/29636144-2ae8c5b4-8815-11e7-96a0-b6074ba572f1.png)

**Comment by jag3773** [comment]
For clarity's sake:

* ULB
  * Latest: https://git.door43.org/Door43/en_ulb
  * Released in API: https://git.door43.org/Door43-Catalog/en_ulb
* tW
  * Latest: https://git.door43.org/Door43/en_tw
  * Released in API: https://git.door43.org/Door43-Catalog/en_tw

For the purpose of consistency comparison, the versions Released in API (Door43-Catalog) should be used.

**Comment by mannycolon** [comment]
@benjore

**Comment by mannycolon** [comment]
@cckozie 
^

**Comment by mannycolon** [comment]
@klappy 
what do you think about Jesse's idea? If @benjore  approves I like it.


```
Note that if it is helpful and if @benjore approves, it may be acceptable to 
just have the first word form in the menu on the left and only have the full 
word list in the tHelps heading. The first word listed is usually the "head" 
(or main) word form and it may help to make the menu on the left cleaner.
```

**Comment by klappy** [comment]
If I recall, there was a point in history when tC only showed the "group id" which in this case was like having the first word. This caused some confusion during testing when looking for words that don't show up in the menu. I think it was Perry who was doing the testing and brought up the need for all words to be in the menu.

**Comment by benjore** [comment]
@mannycolon tC should only display what is in the API. 
#2539 Covers the other issue

**Comment by cckozie** [comment]
Need to use the catalog links to see the API source.
