### ISSUE TITLE
tC Electronite update

### ISSUE THREAD

**Issue by BincyJ** [unfoldingWord/translationCore#7203]
To setup the continuous build system on CircleCI so that we can automatically keep up with the electron releases

**Comment by PhotoNomad0** [comment]
Looks interesting.

**Comment by PhotoNomad0** [comment]
@birchamp @da1nerd - It looks like Electron uses CircleCI for the linux and macos builds, but uses AppVeyor for the windows builds.  I tried building the `electronite-v12.0.5` branch to understand how build works on CircleCI, but I got an error with the electronite patch.

**Comment by PhotoNomad0** [comment]
Ran tests building plain vanilla electron
- Tried building electron 12-x-y branch - failed with corrupted cache at 50 min.  Seems to be due to 12-x-y builds being deprecated and no updated.
- Tried building electron 13-x-y branch - electron build times out at about an hour on free tier - Tried building electron 13-x-y branch using paid tier - electron build times out at about 3 hours.
- retrying building electron 13-x-y branch using medium gen2 resources - thought it would work with 50% boost...but still timed out at 3 hours.

**Comment by birchamp** [comment]
@da1nerd Do you have any time to work on an updated Electronite build?

**Comment by da1nerd** [comment]
> @da1nerd Do you have any time to work on an updated Electronite build?

Unfortunately not, I'm managing two teams on a few large projects at the moment, and don't have the bandwidth.

**Comment by PhotoNomad0** [comment]
@da1nerd Seeing this error when I run your windows script `electronite-tools.bat get v12.0.5-graphite-graphite`
```
src (ERROR)
----------------------------------------
[0:00:02] Started.
[0:00:02] Finished running: git remote set-url --push origin https://chromium.googlesource.com/chromium/src.git
running "git cat-file -e 89.0.4389.128^^^^{commit}" in "C:\Users\blm\.git_cache\chromium.googlesource.com-chromium-src"
[0:00:02] Finished running: git config remote.origin.url
[0:00:03] Finished running: git rev-list -n 1 HEAD
[0:00:03] Finished running: git rev-parse --abbrev-ref=strict HEAD
----------------------------------------
Error: 2>
2> ____ src at 89.0.4389.128
2>      You have unstaged changes.
2>      Please commit, stash, or reset.
```

It seems the branch `v12.0.5-graphite-graphite` is related to the last release.
Is there a manual command I need to run here?

I tried pointing the script to plain vanilla electron, and was able to get sources, build, and release.  So it seems I have the configuration set up right for windows.

**Comment by da1nerd** [comment]
I'm not exactly sure what is causing that error. It's possible you may need to delete your cached files, including the git cache.

**Comment by PhotoNomad0** [comment]
@da1nerd Thanks - tried building on a clean machine.  It fetched the sources and is building now!

**Comment by PhotoNomad0** [comment]
@da1nerd @birchamp - baby steps here.  I have electronite builds working for macOS and LInux now.  And even have built electronite on the latest v12.2.3 and running:

<img width="962" alt="Screen Shot 2022-04-01 at 6 29 33 AM" src="https://user-images.githubusercontent.com/14238574/161247060-215bcb99-8d90-47b0-a211-1b342abd0ac2.png">

**Next Steps**
1. Get Electronite windows builds working - cannot get through applying hooks.
2. Get Electronite builds for Electron versions v14+ - these are needed for Windows 11 UI quirks.  On a side note, I have tCore running on plain vanilla Electron up to v17!

**Comment by PhotoNomad0** [comment]
@da1nerd I am very impressed with your work and your notes.  You accomplished so much on a complex issue.  I am slowly getting my head wrapped around the process of reproducing your work.

**Comment by PhotoNomad0** [comment]
Here is the test of Graphite support:
<img width="1109" alt="Screen Shot 2022-04-01 at 7 11 48 AM" src="https://user-images.githubusercontent.com/14238574/161252715-4b2281a6-b6af-4bfd-9204-97724c736f56.png">

**Comment by da1nerd** [comment]
> @da1nerd I am very impressed with your work and your notes. You accomplished so much on a complex issue. I am slowly getting my head wrapped around the process of reproducing your work.

I'm glad it helped! Sorry I'm not available work on this, I've been swamped with work, but it's good to have someone else familiar with the process.

**Comment by PhotoNomad0** [comment]
@da1nerd  Made progress on building for Windows - was able to get all the sources checked out  and  patches applied (the previous road block).

Finished the  first part, created a pre-release of Electronite v17.3.1 here: https://github.com/unfoldingWord/electronite/releases.  Updated build notes.

Next to be done is update the CLI, publish it on nodejs and then can start testing in tCore.

**Comment by PhotoNomad0** [comment]
@elsylambert - the new electronite is in develop branch starting with build [6cfe461]

Should see the updated version in the debug console:

![Screen Shot 2022-04-14 at 10 57 37 AM](https://user-images.githubusercontent.com/14238574/163417725-f2e56837-891c-4776-90c1-4a86e62daac6.png)

**Comment by elsylambert** [comment]
Looks good in translationCore 3.2.0 (6cfe461) on Mac.
<img width="1411" alt="Screen Shot 2022-04-14 at 2 22 01 PM" src="https://user-images.githubusercontent.com/51806180/163453084-1ba0a391-bcc1-4f2a-86d3-4e0744e11305.png">
