### ISSUE TITLE
Empty occurrence notes crashes parsing of books when downloading latest tNs

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#7213]

**Comment by PhotoNomad0** [comment]
**Discussion:**

Russ Perry: Thanks, @Birch . I'll let them know to see if that helps them.

Russ Perry: @Birch @Rich Mahn @Bruce McLean Book packages for Kannada rut and jon have been published to DCS three weeks ago, but Kannada is not showing as a GL in tCore (3.0.2) for Ruth or Jonah. I renamed the translationHelps folder and re-downloaded the content, but it's still not there. Telugu is not there either. What am I missing?
image.png

...

Russ Perry: @Rich Mahn are you still looking for a solution for te rut, or do I just need to tell the Telugu team to fill in all the ONs?

Rich Mahn: @Russ Perry Unless they want to wait for next version of tC, you need to tell them. It should be fixed anyway if they want that tN to be checked.

...

Bruce McLean: @Russ Perry Stepping through the program. @Rich Mahn is right, an
empty occurrence note causes the whole book to be skipped over.

Russ Perry: @Bruce McLean when is that fix expected to be released?

Bruce McLean: That could be put into 3.1.0 release. @Birch when is that expected?

Birch: End of the month.

**Comment by elsylambert** [comment]
Not seeing this issue in translationCore 3.1.0 (a7d2893).
