### ISSUE TITLE
Add Ability to cancel download of resources when downloads are taking too long

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#7222]
The user should be able to cancel a download of resources while it is in progress. 

DoD:
===
After the user has chosen to download a resource update the download can be canceled.

**Comment by PhotoNomad0** [comment]
@elsylambert This is in the latest dev build.  Clicking cancel button may have a delay if processing a large resource.

**Comment by elsylambert** [comment]
Looks good in translationCore 3.2.0 (ba8ab1d) and works fine. Not seeing any delay in canceling the download.

**Comment by elsylambert** [comment]
Works as expected in windows 11 in translationCore 3.2.0 (1aea3cc).
