### ISSUE TITLE
On resource download failure, show list of repos that failed to download.

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#7225]
Add a list of failed repos to the error dialog. 

DoD:
===
When repos fail to download the names of the repos are displayed to the user.

**Comment by PhotoNomad0** [comment]
@elsylambert See https://github.com/unfoldingWord/translationCore/pull/7236 for example how to test.

**Comment by elsylambert** [comment]
translationCore 3.2.0 (1ed3822). Works fine. The dialog box lists the repo and the cause of the download failure.
