### ISSUE TITLE
Add quick toggle to expanded scripture pane to show raw USFM

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#7226]
### User Story
Suggested by Larry at January meeting.  Larry reviewed the prototype.

Added toggle button to title bar to switch to show raw USFM.

Regular view:
![Screen Shot 2022-02-03 at 11 26 41 AM](https://user-images.githubusercontent.com/14238574/152385508-edea4cda-c5f5-4db6-8317-e9396d3f059c.png)

Normal view:
![Screen Shot 2022-02-03 at 11 27 00 AM](https://user-images.githubusercontent.com/14238574/152385597-1e38b691-9514-4707-9efb-5820049dcddc.png)

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by elsylambert** [comment]
@PhotoNomad0 The toggle state is not persistent when the expanded scripture pane is closed. Is it designed that way? If so, I will write up a separate issue for this.

**Comment by PhotoNomad0** [comment]
@elsylambert I have not had a user request for that feature.

**Comment by elsylambert** [comment]
translationCore 3.2.0 (ae2304b). USFM formatting fails when selection is made.
In tW, the new line added is not shown in the expanded Scripture view.
![Large GIF (912x476)](https://user-images.githubusercontent.com/51806180/153089106-e9affea0-63a2-40e1-b903-2270637d89b1.gif)

**Comment by PhotoNomad0** [comment]
@elsylambert Try again in latest build.

**Comment by elsylambert** [comment]
Works fine in translationCore 3.2.0 (1ed3822). Not seeing formatting issues. Toggle works well for the USFM view.
