### ISSUE TITLE
Update Electronite to fix UI issues with Windows 11

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/translationCore#7230]
v 3.1.0
On startup the screen looks as shown in the screenshot below:

![image.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/59821c25-5613-4509-92a7-f35943c60964)

Notes:
- currently using electronite version: 12.0.5-graphite

**Comment by PhotoNomad0** [comment]
@birchamp @elsylambert I didn't find anything about Windows 11 UI problems with older versions of electron.  One way to see if upgrading electonite version would fix this, would be to make builds with plain vanilla electron to test with windows 11.  That would be much quicker than creating new electronite builds.

**Comment by PhotoNomad0** [comment]
@elsylambert Here are some plain vanilla electron builds to test with Windows 11:
- a build with latest electron 12.2.3 - https://github.com/unfoldingWord/translationCore/actions/runs/1868754166
- a build with latest electron 13.6.9 - https://github.com/unfoldingWord/translationCore/actions/runs/1868832257

**Comment by birchamp** [comment]
@elsylambert ^^

**Comment by PhotoNomad0** [comment]
Notes:
- created tCore feature branches for test builds using plain vanilla Electron such as `feature-mcleanb-electron.14`
- summary of Electron versions: https://en.wikipedia.org/wiki/Electron_(software_framework)
- list of breaking changes in newer electron versions: https://www.electronjs.org/docs/latest/breaking-changes#removed-remote-module
- problems running on Electron 14:
  - ~~environment variables not seen in client~~ <= found work-around
  - ~~logging not being saved~~ <= fixed
  - ~~many jest unit tests fail with error: No such module was linked: electron_common_features~~ <= found issue and fixed
  - ~~see warning that fsevents needs to be upgraded.~~ <= updated react scripts and react, and this is now working
  - ~~splash screen not showing version/build.~~ <= found work-around

- problems running on Electron 15:
  - ~~splash screen not showing version/build.~~ <= found work-around

- problems building on Electron 16:
  - Windows fails to build - permissions problem? - https://github.com/unfoldingWord/translationCore/actions/runs/2003758522
  - seems to be working well.

**Comment by PhotoNomad0** [comment]
@elsylambert - I cannot reproduce the problems Benjamin is seeing.  The shifted launch screen only lasts for a  second at most.

**Comment by PhotoNomad0** [comment]
@elsylambert Here is another plain vanilla electron build to test with Windows 11:

- a build with latest electron 14.2.6 - https://github.com/unfoldingWord/translationCore/actions/runs/1989272861

**Comment by PhotoNomad0** [comment]
@elsylambert - I did once see the launch screen shifted over and I couldn't click on it.  That is once in about 30 attempts.  Will make it hard to determine if a newer electron version will fix it.  I tried 50 more attempts rapid fire, but didn't see the problem again.

**Comment by PhotoNomad0** [comment]
@elsylambert - I just discovered that I can reproduce the problem consistently when I have one instance of tCore open and then open a second instance.

**Comment by elsylambert** [comment]
![image](https://user-images.githubusercontent.com/51806180/158589780-328fd620-3fe2-4e66-8734-c9350e5dd224.png)

translationCore 3.2.0-e14 (1805292). @PhotoNomad0  I am not seeing the UI issues while startup, even when I open the second instance. Just seeing the version number missing on the above screen which stays for few seconds before the startup screen with version number and the "Get Started" button appears.
![image](https://user-images.githubusercontent.com/51806180/158590599-bbd682cd-7d55-438b-8940-9170778e3155.png)

**Comment by PhotoNomad0** [comment]
@elsylambert Thanks for checking that - I have just been noticing that also with Electron 14 and greater.  Will take a look at how to fix that.  But glad it does seem to fix the UI problem for me also.

**Comment by PhotoNomad0** [comment]
@elsylambert FYI - it looks like Electron 13 had the UI shifted problem sometimes also.

**Comment by PhotoNomad0** [comment]
@elsylambert Have builds:
- Electron 16: https://github.com/unfoldingWord/translationCore/actions/runs/2003758522
- Electron 17: https://github.com/unfoldingWord/translationCore/actions/runs/2006746469

Electron 17 would be ideal (if it works) since it is the latest electron version.

**Comment by elsylambert** [comment]
translationCore 3.2.0-e17 (41854a0) Looks good in Win 11 and Mac. Not seeing UI issues.

**Comment by PhotoNomad0** [comment]
@elsylambert - the new electronite is in develop branch starting with build [6cfe461]

Should see the updated version in the debug console:

![Screen Shot 2022-04-14 at 10 57 37 AM](https://user-images.githubusercontent.com/14238574/163417725-f2e56837-891c-4776-90c1-4a86e62daac6.png)

**Comment by elsylambert** [comment]
Not seeing UI issues in Win 11 in translationCore 3.2.0 (5d518ca). Startup screen looks good. Seeing the Electronit 17.3.1 version in the console.

![image](https://user-images.githubusercontent.com/51806180/166249306-b15fe78d-8cd3-48fa-b9ee-9c601e0ecc69.png)
