### ISSUE TITLE
Error while trying to download UGNT for tN tool 

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/translationCore#7241]
translationCore 3.2.0 (1ed3822)
log file:  [Mon Feb 14 2022.log.zip](https://github.com/unfoldingWord/translationCore/files/8062814/Mon.Feb.14.2022.log.zip)

Project:
[https://app.zenhub.com/files/65028237/70e420bc-84de-4202-bc30-8da73380d620/download](https://app.zenhub.com/files/65028237/70e420bc-84de-4202-bc30-8da73380d620/download)

Steps:
- Download the en content for the "Actions>Check for Content Updates".
- Open the above project, open tools and for tN select the GL, hi-door-43-catalog.
- You should see the below message notifying tN using a different version of UGNT
![Screen Shot 2022-02-14 at 12.31.08 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/fc511c8e-e96c-44bd-b595-b36b30525883)
- Click Continue.
![Screen Shot 2022-02-14 at 12.31.16 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/14d6a70f-2767-47bd-be3f-7ec2e683b025)
- Click on Download.
- Note that it fails the download 
![Screen Shot 2022-02-14 at 12.30.19 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/a4322558-c57d-4d7b-ae9d-d269e580a08c)

**Comment by PhotoNomad0** [comment]
@elsylambert This should be fixed in latest dev build.

**Comment by elsylambert** [comment]
Not seeing the problem in translationCore 3.2.0 (71ca242). tC now downloads the UGNT without fail.
