### ISSUE TITLE
Add feedback button to Update resource error dialog

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/translationCore#7246]
Errors during update resource are particularly troubling, and often need helpdesk support.  The user needs a way to send a log to the helpdesk via the feedback button. 

DoD:
===
The update resource error dialog has a feedback button that opens the existing feedback dialog functionality.

**Comment by PhotoNomad0** [comment]
@birchamp @elsylambert Would this work for the UI? I centered the feedback button under the error text:

![Screen Shot 2022-03-07 at 10 03 57 AM](https://user-images.githubusercontent.com/14238574/157060166-72aa5dc0-de10-45e3-b03f-ee4e1326db07.png)

**Comment by birchamp** [comment]
Where is the 'send feedback' on other dialogs? @PhotoNomad0

**Comment by PhotoNomad0** [comment]
@birchamp - The only other error dialog i know of with integrated feedback is in the checking tool for invalid checks.  It only has two buttons at bottom: submit feedback and ignore.  If you are thinking we should move the feedback button to the bottom line, it would take some significant refactoring to add support for a third button to the generic alert dialog or require creating a custom dialog.

**Comment by birchamp** [comment]
I see. In that case, let's make the send feedback button centered in the dialog instead of under the text and white like the cancel button because it will cancel the operation when they send the feedback.

**Comment by PhotoNomad0** [comment]
@birchamp Turning it white is easy, but centering button in dialog would be a refactor.  Currently just adding the button to the alert message.  I could move it down a little bit and try to fake centering by indenting, but the dialog width is dynamic and will change to accommodate width of the text.

**Comment by PhotoNomad0** [comment]
Will take a look - maybe I can add the third button support in a day.

**Comment by elsylambert** [comment]
@PhotoNomad0 Can we replace the Retry button with the Feedback button. The retry does not actually help after we get the error on download.

**Comment by PhotoNomad0** [comment]
@elsylambert We could.  And drop the retry?  The retry is handy if the user is having intermittent network problems.  In case of retry it just tries to download what failed and they don't have to reselect the resources.

**Comment by PhotoNomad0** [comment]
Or I suppose if they select cancel to the send feedback, we could give another prompt asking if they want to retry the download?

**Comment by elsylambert** [comment]
@PhotoNomad0 I was considering "missing dependency" error only, to remove the Retry button, but that would be unfair if the error happens due to network disconnections. 
Another prompt on Cancel could be a bit tedious for the user.

**Comment by elsylambert** [comment]
@PhotoNomad0 Ideal UI would be to have three buttons, but if it requires major refactor then either:
1. we could use the layout as per your recent screenshot and align the buttons by bringing Feedback button down a little bit.
2. Or we can use two buttons "Feedback" and "Retry". Clicking on X on the Alert box can be utilized for Cancel. (workaround)

**Comment by PhotoNomad0** [comment]
@birchamp @elsylambert _ after a bit of flex slight of hand, I have this.  Feedback?

![Screen Shot 2022-03-07 at 3 29 02 PM](https://user-images.githubusercontent.com/14238574/157113039-ff8a2792-6c4d-471f-b684-efe16b837305.png)

**Comment by birchamp** [comment]
any chance we can move the Send Feedback up closer to the text?

**Comment by PhotoNomad0** [comment]
@birchamp Here we go:

![Screen Shot 2022-03-08 at 10 39 56 AM](https://user-images.githubusercontent.com/14238574/157273051-5b119f2f-9141-46ab-bac2-bc4402dd8932.png)

**Comment by birchamp** [comment]
@PhotoNomad0  Ship it!

**Comment by PhotoNomad0** [comment]
@elsylambert: This is added to Branch [develop] build [0ec0674]

**Comment by PhotoNomad0** [comment]
@elsylambert Have another fix in Branch [develop] build [b269b60].  Supports scrolling when error list is long.

**Comment by elsylambert** [comment]
Works as expected in translationCore 3.2.0 (3ff972e) .
