### ISSUE TITLE
If a dependency fails the error should show what resource was missing

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/translationCore#7247]
During a Update Resource operation when a dependency fails the user should be informed as to what resource was missing if that is the cause of the failure.

DoD:
===
if a resource dependency is missing the user is informed of the actual missing resource.

**Comment by PhotoNomad0** [comment]
@elsylambert This is in Branch [develop] build [bc52f1f]

**Comment by elsylambert** [comment]
This works as expected in translationCore 3.2.0 (3ff972e).
