### ISSUE TITLE
Fix update of tA resources to gracefully handle missing title.md files.

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#7250]
### User Story

As a [type of user], I want [some goal] so that [some reason].

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by PhotoNomad0** [comment]
**Notes from 2022-02-10:**

Jobby Prasannan: We have an issue with the Nepali resource in tCore. The content update shows an error
Jobby Prasannan: This is true even for the Kannada Resource. 

Russ Perry: I'm seeing the same failures on my system for downloading content for Kannada and Nepali.

Jobby Prasannan: @Rich Mahn @Bruce McLean Any updates on this issue?

Bruce McLean: @Jobby Prasannan for kn, the problem is in ta. tCore is choking on a missing title `translate/translate-kinship/title.md`

Bruce McLean: @Russ Perry for ne, it is also a ta problem. Missing title `translate/figs-aside/title.md`

**Comment by PhotoNomad0** [comment]
@elsylambert Test in  develop Branch build `ba8ab1d`

**Comment by elsylambert** [comment]
@PhotoNomad0 I tried with Kannada Resources, not seeing errors on download. Can you please point me to a Resource with missing .md files?

**Comment by elsylambert** [comment]
@PhotoNomad0 How do I test it? Do you  know a Resource with missing .md files?

I am able to download Kn Resources without any fails. Does this suffice?

**Comment by PhotoNomad0** [comment]
Sorry, no idea how to test - they seem to have fixed the resources.  Maybe you could publish something in one of your test repos?

**Comment by elsylambert** [comment]
Looks good in translationCore 3.2.0 (3ff972e).
![image](https://user-images.githubusercontent.com/51806180/161768252-6726c67e-1646-45f9-a77e-a943486493bb.png)
