### ISSUE TITLE
Fix resource update UI to only show one entry for tw download (rather than separate twL and tw downloads)

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#7251]
### User Story

As a [type of user], I want [some goal] so that [some reason].

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by PhotoNomad0** [comment]
@elsylambert Will no longer see a separate TWL download if both need to be updated.  Select TW and TWL will be updated as well if necessary.

New branch [develop] build [1aea3cc]

![Screen Shot 2022-03-10 at 4 30 50 PM](https://user-images.githubusercontent.com/14238574/157758697-12525f0b-a3d2-4410-859f-39a83e41fb8a.png)

**Comment by elsylambert** [comment]
Looks good in translationCore 3.2.0 (1aea3cc). tW download also downloaded tWLs as expected.
