### ISSUE TITLE
Org support for tools card: ru_gl not shown in the GL list in tools card.

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/translationCore#7262]
Running into a problem with org support in tools.  An example is ru_gl.  We can download the ru tW and tWL resources, but ru doesn't show up as an option for GL in tW tool.  
![image](https://user-images.githubusercontent.com/51806180/157584299-9ae2a4e5-67ab-4181-8bd3-d612b6075929.png)

The reason is that we still don't have an aligned bible resource downloaded. It is not a great user experience since the user has no idea why ru does not show up.  I checked the manifest of the twl, but there is no aligned ru bible referenced in the relation field.  So I don't know which ru bible in ru_gl has alignments, so I can't automatically download.  Maybe we just update all the bibles in that org when tW and tN are selected?  But still would have a problem if they open a project for a book that is not aligned in a bible.

**Comment by PhotoNomad0** [comment]
@elsylambert Thanks for moving this to a new issue. I discovered that for some owners, even with all the bibles downloaded, we don't have bibles with alignments nor twls for many books.  In the case of gal projects (such as the project in the original issue), we don't have a bible with alignments for gal in ru_gl.

**Comment by PhotoNomad0** [comment]
@elsylambert @birchamp I would suggest this is a new feature, since we never had feedback to the user about the reason GLs are not showing up on the tool cards.  This was a pre-existing problem even when we only supported door43-catalog.  This is going to require UI design.

**Comment by PhotoNomad0** [comment]
For troubleshooting measures, I have added more detailed logging to determine why a GL is not supported in a tool.

**Comment by PhotoNomad0** [comment]
@elsylambert - with all the resources added, the following books are supported for ru_gl in tN: 3jn, jon, rut, tit (but tW doesn't like any of the checks)

some observations:
- ru_gl/rob - has all the books of the bible, but only a few are aligned.
- ru_gl/reg - Russian radio bible does not have alignments and only has 3jn, jon, rut, tit
- ru_gl/rlob  - Russian Literal Bible has a larger number of books, looks like all are aligned
- ru_gl/rsb - Russian Synod Bible has all the books of the bible, but only a few are aligned.
- ru_gl/rsob  - Russian Simplified Bible has a large number of books, looks like only a few are aligned

**Comment by PhotoNomad0** [comment]
Thoughts:
- should we remove validation of checking level?
- ru_gl tw is a problem for many books since none of the checks seem to match the OL <= turns out to be problem that there are no alignments for that book in the ru bibles.

**Comment by PhotoNomad0** [comment]
@elsylambert - try these books in ru_gl in the latest build: 3jn, jon, rut, tit

**Comment by elsylambert** [comment]
translationCore 3.2.0 (1aea3cc). I downloaded ru_gl resources and have translation helps files for some books. The tools card drop down shows ru_gl for those books for tW but for tN the tools card is not loading the categories check boxes. ![ru_gl tn tool card](https://user-images.githubusercontent.com/51806180/158676866-04bc0813-7f86-4a4f-a75a-7f2c700db09c.png)
Here is the log file: 
[Wed Mar 16 2022.zip](https://github.com/unfoldingWord/translationCore/files/8270714/Wed.Mar.16.2022.zip)

**Comment by PhotoNomad0** [comment]
@elsylambert Fix is in tCore Branch [develop] build [df57834]

**Comment by elsylambert** [comment]
Looks good in translationCore 3.2.0 (3ff972e). Able to see ru_gl on the toold card for the aligned books, 3jn and titus.
