### ISSUE TITLE
Need to show org for Bible in scripture pane

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#7270]
### User Story
Russ requested to show org for Bible in scripture pane.  
Add org to tool tip for scripture in scripture pane.

As a [type of user], I want [some goal] so that [some reason].

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by birchamp** [comment]
@PhotoNomad0 what's the easiest way to implement this?

**Comment by PhotoNomad0** [comment]
How about adding this detail to hover text?

**Comment by PhotoNomad0** [comment]
@birchamp ^^^

**Comment by PhotoNomad0** [comment]
We currently have hover text for language type (not super helpful).  We could to something similar for the language text field and add the org.

<img width="277" alt="Screen Shot 2022-06-04 at 8 16 14 AM" src="https://user-images.githubusercontent.com/14238574/171998564-4069cfa6-6abd-452f-8309-f6fb71d2d548.png">

Maybe put in the full description for bible such as shown here:

<img width="716" alt="Screen Shot 2022-06-04 at 8 17 47 AM" src="https://user-images.githubusercontent.com/14238574/171998644-c86f8066-7f27-4eee-8ef7-2681af7e718c.png">

**Comment by birchamp** [comment]
Can we just replace the existing hover text?

**Comment by PhotoNomad0** [comment]
@elsylambert Here is how the hover text now looks in the scripture Pane:
<img width="260" alt="Screen Shot 2022-06-22 at 1 27 40 PM" src="https://user-images.githubusercontent.com/14238574/175100550-61bd5a46-56ea-4ff5-b79b-5ca458f2afb8.png">
<img width="230" alt="Screen Shot 2022-06-22 at 1 27 53 PM" src="https://user-images.githubusercontent.com/14238574/175100556-44757365-4815-4ea1-8b77-552db6144025.png">
<img width="232" alt="Screen Shot 2022-06-22 at 1 28 15 PM" src="https://user-images.githubusercontent.com/14238574/175100561-5a22e4b0-ac4c-49b4-9b8a-09e8afc9237e.png">

The content of the hover text is now the same for the language title and subtitle.

**Comment by PhotoNomad0** [comment]
@elsylambert issue is addressed in translationCore 3.2.1 (9cd4f03)

**Comment by elsylambert** [comment]
Looks good in translationCore 3.2.1 (2c2672c). Hover text works fine for different Bible Resources.

<img width="520" alt="Screen Shot 2022-06-28 at 9 04 51 AM" src="https://user-images.githubusercontent.com/51806180/176185631-108a3aa6-5318-439a-8bda-9b92b21cdaa3.png">

<img width="328" alt="Screen Shot 2022-06-28 at 9 05 18 AM" src="https://user-images.githubusercontent.com/51806180/176185727-d7be9470-cadf-4ee0-8af9-f385c8e9a9c0.png">
