### ISSUE TITLE
Make use of original language resources from unfoldingWord org

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#7274]
Suggested by @richmahn that we should remove dependency on Door43-Catalog for original languages in the case when we are using resources from other orgs.  He suggested that all orgs other than Door43-Catalog should use the original languages in unfoldingWord org.  This would protect in future when we stop depending on the catalog.

Maybe future task would be to allow all orgs to have original language resources, with fallback to uW?

**Comment by PhotoNomad0** [comment]
Note:
- in source content updater method getCatalog - need to remove filter
- in tC need to change logic, so all orgs other than d43-catalog use unfoldingWord.

**Comment by PhotoNomad0** [comment]
@elsylambert The feature is in Branch develop build 3ff972e.

**Comment by elsylambert** [comment]
translationCore 3.2.0 (3ff972e). Seeing unfoldingword as org for Original languages Greek and hr.
<img width="584" alt="Screen Shot 2022-04-05 at 1 48 06 PM" src="https://user-images.githubusercontent.com/51806180/161818895-2d886bd4-03c1-45fb-936e-6d57e83ef5e0.png">
