### ISSUE TITLE
SPIKE: Can tC handle notes without RC links in the note? 

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/translationCore#7278]
If a note doesn't have a RC link within the note, what does tC do?   How challenging is it to make it handle either case (with or without link)?

**Comment by PhotoNomad0** [comment]
I found several en_tn checks missing the RC in v60_Door43-Catalog. Note that these are already imported in tCore:

  console.log src/__tests__/rcChecks.test.js:33
    missing RC /Users/blm/translationCore/resources/en/translationHelps/translationNotes/v60_Door43-Catalog/culture/groups/jhn/figs-explicit.json {"bookId":"jhn","chapter":17,"verse":10} q0tm in note: This could mean: (1) **all things** are the means by which Jesus is glorified. Alternate translation: “by means of them” (2) Jesus is glorified **in** **all things**. Alternate translation: “within them”

  console.log src/__tests__/rcChecks.test.js:33
    missing RC /Users/blm/translationCore/resources/en/translationHelps/translationNotes/v60_Door43-Catalog/culture/groups/luk/translate-names.json {"bookId":"luk","chapter":20,"verse":37} m407 in note: translate-names

  console.log src/__tests__/rcChecks.test.js:33
    missing RC /Users/blm/translationCore/resources/en/translationHelps/translationNotes/v60_Door43-Catalog/figures/groups/1th/figs-metaphor.json {"bookId":"1th","chapter":5,"verse":21} ihzh in note: This could mean: (1) Paul is beginning a general list of things that the Thessalonians should **Test** and **Hold fast** if they are **good**. (2) Paul is continuing to refer to the prophesies in the previous verse, and wants the Thessalonians to **Test** those and **Hold fast** to the prophesies that are truly from God.

  console.log src/__tests__/rcChecks.test.js:33
    missing RC /Users/blm/translationCore/resources/en/translationHelps/translationNotes/v60_Door43-Catalog/figures/groups/exo/figs-metonymy.json {"bookId":"exo","chapter":1,"verse":5} uk67 in note: Here, **lives** refers to people (specifically, men); **going out of the loins of Jacob** is a reference to these people as being in his seed or semen and produced through his sexual acts–therefore meaning they are his descendants. See also Hebrews 7:9-10. Alternate translation: “And all the male descendants of Jacob numbered 70.”

  console.log src/__tests__/rcChecks.test.js:33
    missing RC /Users/blm/translationCore/resources/en/translationHelps/translationNotes/v60_Door43-Catalog/figures/groups/gal/figs-doublenegatives.json {"bookId":"gal","chapter":2,"verse":2} ejb8 in note: Paul uses running as a metaphor to compare his work of preaching the gospel to a person running a race. Paul worked hard to preach the gospel. He wanted the gospel that he preached to have lasting effects. Alternate translation: “I did not want to work hard for God uselessly” or “I did not want my hard work to be wasted”

  console.log src/__tests__/rcChecks.test.js:33
    missing RC /Users/blm/translationCore/resources/en/translationHelps/translationNotes/v60_Door43-Catalog/figures/groups/gal/figs-personification.json {"bookId":"gal","chapter":5,"verse":19} yf2a in note: The word **flesh** is used as if it were a person. The abstract noun **works** can be translated with the verb “does.” Alternate translation: “what the sinful nature does” or “the deeds if we follow the sinful desires of our hearts” or<br>“what people do because of their sinful nature.” See how you translated **flesh** in [Galatians 5:13] and [Galatians 5:16].

  console.log src/__tests__/rcChecks.test.js:33
    missing RC /Users/blm/translationCore/resources/en/translationHelps/translationNotes/v60_Door43-Catalog/figures/groups/gal/figs-rquestion.json {"bookId":"gal","chapter":2,"verse":19} r55d in note: The phrase, **I...died to the law** means that the law no longer has any power or authority over Paul. Alternate translation: “I am separated from the law”

  console.log src/__tests__/rcChecks.test.js:33
    missing RC /Users/blm/translationCore/resources/en/translationHelps/translationNotes/v60_Door43-Catalog/figures/groups/gal/figs-rquestion.json {"bookId":"gal","chapter":2,"verse":19} xg5q in note: **I have been crucified with Christ** could mean (1) by the Messiah’s death, Paul was now separated from the law (2) Paul died spiritually and escaped the dominion of sin and the law.

  console.log src/__tests__/rcChecks.test.js:33
    missing RC /Users/blm/translationCore/resources/en/translationHelps/translationNotes/v60_Door43-Catalog/figures/groups/jon/figs-metonymy.json {"bookId":"jon","chapter":3,"verse":3} g4nk in note: Alternate translation: “the message of Yahweh” or “the command of Yahweh”

  console.log src/__tests__/rcChecks.test.js:33
    missing RC /Users/blm/translationCore/resources/en/translationHelps/translationNotes/v60_Door43-Catalog/grammar/groups/mrk/figs-activepassive.json {"bookId":"mrk","chapter":1,"verse":14} ys3b in note: It might be helpful for your readers to clarify that Jesus was returning to Galilee. Alternate translation: “Jesus returned to the Galilee district” or “Jesus went back to the district of Galilee”

  console.log src/__tests__/rcChecks.test.js:33
    missing RC /Users/blm/translationCore/resources/en/translationHelps/translationNotes/v60_Door43-Catalog/numbers/groups/mrk/translate-numbers.json {"bookId":"mrk","chapter":1,"verse":13} k2kt in note: If it would be clearer in your language, you could say **being tempted by Satan** with an active form. Alternate translation: “For 40 days Satan continued tempting him” or “For 40 days the devil kept trying to persuade him disobey God”

  console.log src/__tests__/rcChecks.test.js:33
    missing RC /Users/blm/translationCore/resources/en/translationHelps/translationNotes/v60_Door43-Catalog/other/groups/exo/grammar-collectivenouns.json {"bookId":"exo","chapter":1,"verse":10} wkvf in note: Here, **him, he**, and **himself** refer to the Israelite people. The pronouns agree grammatically with the singular “people” in the original. This occurs in many places in Exodus. If this is confusing in your language, you can use the plural, as in the UST.

  console.log src/__tests__/rcChecks.test.js:33
    missing RC /Users/blm/translationCore/resources/en/translationHelps/translationNotes/v60_Door43-Catalog/other/groups/jhn/guidelines-sonofgodprinciples.json {"bookId":"jhn","chapter":17,"verse":21} v6i7 in note: Here, **so that** could indicate: (1) that what follows is the purpose for believers to be united to Jesus and God the Father, as in the UST. (2) that what follows is the result of believers being united to Jesus and God the Father. Alternate translation (with a comma preceding): “with the result that the world would believe that you have sent me”

**Comment by PhotoNomad0** [comment]
@birchamp It looks like it is handled fine without RC. The link is not displayed in smurf bar, but probably not necessary since the note is displayed on the right:
<img width="1396" alt="Screen Shot 2022-05-31 at 8 58 27 AM" src="https://user-images.githubusercontent.com/14238574/171179318-df8ccef0-2d43-4002-87d8-3fddd06f9f3f.png">

**Comment by birchamp** [comment]
@birchamp create issue for validator to remove requirement.

**Comment by PhotoNomad0** [comment]
@birchamp I discovered that tCore is using those links on download to get localized Title from the ta article.  So it is not a problem if a few are missing.  But if a lot of them are missing we will see a lot of strings such as `figs-explicit` in the checking tools menu.  There is a work around to using the supportReference and looking under `translate` folder of the ta articles.

**Comment by PhotoNomad0** [comment]
> @birchamp I discovered that tCore is using those links on download to get localized Title from the ta article. So it is not a problem if a few are missing. But if a lot of them are missing we will see a lot of strings such as `figs-explicit` in the checking tools menu. There is a work around to using the supportReference and looking under `translate` folder of the ta articles.

@elsylambert This is fixed in latest dev build.  Not sure how to verify.
