### ISSUE TITLE
Critical Error thrown when scripture pane was expanded

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/translationCore#7279]
translationCore 3.2.0 (3ff972e). Windows 11.
- Updated the ru_gl content.

- Opened the project [en_test_3jn_book.zip](https://github.com/unfoldingWord/translationCore/files/8418526/en_test_3jn_book.zip) . Seeing ru_gl in the GL list for tN and tW.
- Selected the ru_gl and launch the tN. It shows the warning that the"Opening a project in translationNotes could invalidate some work previously completed on it. Are you sure you want to continue?
" . Click on Continue.
- tN is opened. Click on the Expand Scripture pane button. Note that you get a Critical error screen.
![image.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/54f3e463-cec7-449b-8d1a-7fad1c10a5dd)

Here is the log file
[Tue Apr 05 2022.zip](https://github.com/unfoldingWord/translationCore/files/8418513/Tue.Apr.05.2022.zip)
:

**Comment by PhotoNomad0** [comment]
@elsylambert  Were you able to reproduce this on Mac?

**Comment by elsylambert** [comment]
@PhotoNomad0 Yes, I am able to reproduce this on Mac with the same 3jn project. 
- I downloaded ru_gl Resources and opened the project.
-  Opened tN with en first, then opened with ru_gl, 
- got the warning message>click on Continue. 
- I clicked on expand scripture pane button, it opened fine. 
- Close the expanded scripture pane.
- Then I added/loaded ru_gl bible in the scripture pane and expanded the scripture pane again and got the error.
<img width="1792" alt="Screen Shot 2022-04-05 at 1 31 09 PM" src="https://user-images.githubusercontent.com/51806180/161816177-fa591cea-34a0-41e0-888a-6761a0f8cf78.png">

LOG FILE:
[Tue Apr 05 2022.log.zip](https://github.com/unfoldingWord/translationCore/files/8420601/Tue.Apr.05.2022.log.zip)

**Comment by elsylambert** [comment]
@PhotoNomad0 Could it be the org support on scripture pane causing the error? I got the error in wordAlignment also when I expanded the scripture pane. I had added ru_rob bible in the scripture pane. I am consistently able to reproduce the error.

**Comment by PhotoNomad0** [comment]
@elsylambert - I was able to reproduce the problem, so I know where I need to look.

**Comment by PhotoNomad0** [comment]
> @PhotoNomad0 Could it be the org support on scripture pane causing the error? 

@elsylambert  Your theory was correct - it was not using the org, but always using door43 catalog.  Good sleuthing!

**Comment by PhotoNomad0** [comment]
@elsylambert This is now working in the latest develop build `dafe703`

**Comment by elsylambert** [comment]
Not seeing the issue in translationCore 3.2.0 (6cfe461) on Mac.

**Comment by elsylambert** [comment]
Not seeing this issue in translationCore 3.2.0 (5d518ca)
