### ISSUE TITLE
Space before *paseq* U+05C0 isn't showing in Hebrew scripture pane.

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/translationCore#7286]
Issue
----
In the UHB (for example EXO 7:19) the sequence is: final mem (U+05DD); regular space (U+0020); paseq (i.e. vertical line, U+05C0), but tC it omits the U+0020 when it displays the text. 

DoD:
---
When a space occurs in the raw USFM before the paseq U+5C0 the space will be displayed and copiable into the clipboard.

Details
---
[Video demonstrating the problem](https://unfoldingword-org.zoom.us/rec/play/B-U74U7akcbMvsPLaxIEE6o7CLuZpXHPffeVe1o2BFPMR-8xVJXIq3krgkXqsfAKvktN-a8c_iBxw7TT.wuAb8K6qou9Srk_n?startTime=1649699862000&_x_zm_rtaid=vLbeLH-7Q46UxeBf1aAsXg.1649703878163.fea208957478d50bf3847d3b6420b0a0&_x_zm_rhtaid=357)

**Comment by PhotoNomad0** [comment]
Note:
- example is from Exodus 7:19, in uhb line 2439: https://git.door43.org/Door43-Catalog/hbo_uhb/src/branch/master/02-EXO.usfm#L2439
- it looks like the space is lost or mixed up when USFM is parsed by usfmjs on resource download.  The text block comes out as "׀ ".  There is no space before it.
- So it is a usfmjs issue.

**Comment by PhotoNomad0** [comment]
@birchamp have a fix for this in usfm-js.

**Comment by PhotoNomad0** [comment]
Note: before publish, Will need to regenerate bible content to pick up the fix.

**Comment by PhotoNomad0** [comment]
New layout:
![Screen Shot 2022-05-17 at 3 01 58 PM](https://user-images.githubusercontent.com/14238574/168891899-e94c320f-d428-4be2-8163-27904afbc1e9.png)

**Comment by PhotoNomad0** [comment]
When I copy from the scripture pane I now get `עַֽל־ נַהֲרֹתָ֣⁠ם ׀ עַל־`

**Comment by joeldruark** [comment]
Yes, this looks right.  This problem exists in tC Create as well, just FYI

**Comment by PhotoNomad0** [comment]
@birchamp - would you create PRs for GWE and TCC to update the version of usfm-js?  It looks like the core of the fix is in scripture-resources-rcl which is still using a very old version of usfm-js.  After updating the scripture-resources-rcl , we can update the version of scripture-resources-rcl used in GWE and TCC.

**Comment by PhotoNomad0** [comment]
@elsylambert  Fixed in translationCore 3.2.0 (b8de885) - in Exodus 7:19, the uhb should render as screenshot above.

**Comment by elsylambert** [comment]
translationCore 3.2.0 (b8de885).
-Online Imported Exodus project and opened wA.
-The Hebrew text in the scripture pane looks as in the screenshot below, without the space after paseq.
<img width="983" alt="Screen Shot 2022-06-02 at 9 27 10 AM" src="https://user-images.githubusercontent.com/51806180/171640637-80a6794b-1c30-4836-82b5-793a74e2f251.png">

Am I missing a step here? @PhotoNomad0

**Comment by PhotoNomad0** [comment]
@elsylambert - very mysterious.  It is working well for me.  Which GL organization are you using? And which version of the UHB?  I have selected D43 English and have this uhb: ~/translationCore/resources/hbo/bibles/uhb/v2.1.24_Door43-Catalog

**Comment by PhotoNomad0** [comment]
@elsylambert - I also have ~/translationCore/resources/hbo/bibles/uhb/v2.1.24_unfoldingWord, which would be used for any other org.  I tested with ru/ru_gl and it is also working.

**Comment by PhotoNomad0** [comment]
@elsylambert - OK I solved the mystery. when I installed on a clean PC, I see the same as you do.  The uhb bundled with tCore was processed with the older tCore version and does not have the space.  On my dev machine, I had processed the uhb with the updated tCore.  I'll create a new build with reprocessed bibles. Since all the bundled bibles were processed with the older USFM-js that had the spacing bug.

**Comment by PhotoNomad0** [comment]
@elsylambert - will need to delete the previous uhb before installing the new build (~/translationCore/resources/hbo/bibles/uhb).  Fixed in translationCore 3.2.0 (82ee207)

**Comment by elsylambert** [comment]
Looks good in translationCore 3.2.0 (82ee207). Space before paseq is showing correctly in the latest tC build. It worked after deleting old uhb from the resource folder.
<img width="524" alt="Screen Shot 2022-06-07 at 8 40 22 AM" src="https://user-images.githubusercontent.com/51806180/172381921-87ef12aa-79cd-44bd-9f00-acbbb6abe989.png">

**Comment by elsylambert** [comment]
Works well in translationCore 3.3.0 (fb96f72)
