### ISSUE TITLE
Critical Error when selecting GL for tN

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/translationCore#7287]
translationCore 3.2.0-e17 (41854a0) . Win 11.
- Opened Project: [en_ulb_tit_book.zip](https://github.com/unfoldingWord/translationCore/files/8474597/en_ulb_tit_book.zip)
- Go to TN Tools card:
 Note that no GL is selected.
- Select Hindi(hi) as GL and tC shows the error.

![image.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/90e01204-be81-405a-af04-91e396ca2325)

- Go to project again>tN tools card>Shows Hindi as GL >Launch. It shows the warning that the UGNT version is different and that the UGNT version needs to be downloaded.
- Click to download. see that download fails.

![image.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/4f4c2b1d-4470-4b0f-8b94-549800f62af1)

LOG file:
[Tue Apr 12 2022.zip](https://github.com/unfoldingWord/translationCore/files/8474608/Tue.Apr.12.2022.zip)

**Comment by PhotoNomad0** [comment]
@elsylambert - This should be fixed in develop branch starting with build [6cfe461]

**Comment by elsylambert** [comment]
Not seeing this problem in translationCore 3.2.0 (5d518ca).
