### ISSUE TITLE
Error in PHP 3:2 for "Forms or You- Singular" 

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/translationCore#7292]
I can reproduce this error by checking TNs in Phil 3:2 under the check "Forms of You - Singular.  
Ongoing discussion is [here](https://unfoldingword.zulipchat.com/#narrow/stream/309205-Helpdesk---ST/topic/Philippians.203.3A2.20tC.20Alert.20GroupId.3A.20.22figs-yousingular.22/near/279008461).
```
There is a problem with the content for this check:

Tool: "translationNotes"
GroupId: "figs-yousingular"
Reference: "php 3:2"
Gateway Language: "en"
Quote: "βλέπετε"
Occurrence: "-1"
```
Validation doesn't find anything wrong with the content.

**Comment by PhotoNomad0** [comment]
@birchamp 

Looked at the repo (https://git.door43.org/Door43-Catalog/en_tn/src/branch/master/en_tn_51-PHP.tsv).  It looks like this check and another have -1 for occurrence notes.  It is a data error in the repo.


257 | PHP | 3 | 2 | ttws | figs-yousingular | βλέπετε | _**-1**_ |   | All three times that the phrase Beware occurs in this verse, it is a command or instruction given to all of the Philippian believers. Use the most natural form in your language to give direction to a group of people. Alternate translation: “I exhort each of you to beware of” or “Each of you beware of” (See: [[rc://en/ta/man/translate/figs-yousingular]])
258 | PHP | 3 | 2 | ny6y |   | βλέπετε | _**-1**_ | Beware | Alternate translation: “Watch out for” or “Look out for” or “Be on guard against”

**Comment by PhotoNomad0** [comment]
@elsylambert fix is in translationCore 3.2.0 (12353d0)

**Comment by PhotoNomad0** [comment]
Should see:

![Screen Shot 2022-05-09 at 1 45 34 PM](https://user-images.githubusercontent.com/14238574/167467515-98776ad0-0790-42a1-be07-3b6c2652d043.png)

**Comment by elsylambert** [comment]
Looks good in translationCore 3.2.0 (15b6efa).
