### ISSUE TITLE
Problems in seeing ru_gl(org support) as Selections in wA Tools card.

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/translationCore#7295]
translationCore 3.2.0 (5d518ca).
ru Helps Resources are not available to download in Content Update. Not seeing ru in the list. Local Resources folder shows ru Bibles available but not Translation Helps.
In Mac:
- Able to see ru_gl in the GL Selection list on the wA card, but when selected and opened it gives a blank alignment area.
![Screen Shot 2022-05-02 at 10.31.59 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/af598ef0-1199-447e-82e2-dcc9683677dc)
- It shows fine in scripture pane>Load resources >able to see the gl Resources 
![Screen Shot 2022-05-02 at 10.34.06 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/0cd6a931-213a-4f2c-96a5-72262bc46213)

In Windows:
- ru_gl is not shown in the  GL Selection list on the wA card,
![ru_org name](https://user-images.githubusercontent.com/51806180/166255547-22056288-6b30-40f8-9c7f-1cff85513f74.png)

LOG file win11: 
[Mon May 02 2022.zip](https://github.com/unfoldingWord/translationCore/files/8603732/Mon.May.02.2022.zip)

Log file Mac: 
[Mon May 02 2022.log.zip](https://github.com/unfoldingWord/translationCore/files/8603755/Mon.May.02.2022.log.zip)

**Comment by richmahn** [comment]
From the console log I can right away see that the query of the Door43-Catalog entries and all entries is being limited to 100. As it is sorted by repo_name, this means Russia is past the 100 mark, as there are currently 194 repos that match this query. I bit the bullet and simply made a release for everything in Door43-Catalog with the version # in its manifest file and plan to do this for all repos published to Door43-Catalog EXCEPT unfoldingWord repos, as we will continue to do their release in their upstream repo.

**Comment by richmahn** [comment]
https://git.door43.org/api/catalog/v5/search?subject=Bible%2CAligned%20Bible%2CGreek%20New%20Testament%2CHebrew%20Old%20Testament%2CTranslation%20Words%2CTSV%20Translation%20Words%20Links%2CTSV%20Translation%20Notes%2CTranslation%20Academy&sort=reponame

Should be all you need now. No limit. No Door43-Catalog UNLESS you feel the need for repos we currently massage (add/remove data, or convert formats: TQ, UGNT, UHB, and ULT & UST [removes front matter])

**Comment by elsylambert** [comment]
translationCore 3.2.0 (e319381) .
Issues Resolved : Seeing all the language resources available for download in the Content Update List. Works fine.

Still having problems in Mac:
- I downloaded ru_gl Translation helps resources(tA, tW and tN).
- Re-opened 3JN/Titus project to see ru_gl, but the GL list does not show ru_gl in Mac. But this works fine in Windows.
Mac screenshot:
 
<img width="803" alt="Screen Shot 2022-05-04 at 12 08 10 AM" src="https://user-images.githubusercontent.com/51806180/166621932-93e52a0e-667b-44b4-bc07-53e0eb113166.png">

Windows screenshot:
![image](https://user-images.githubusercontent.com/51806180/166622149-50d77baf-6c31-4c76-aa54-7798cb446725.png)

-Another problem is in Windows:
- Opened tW with ru_gl and got Blank screen.
![ru_gl_tW](https://user-images.githubusercontent.com/51806180/166622209-619c0792-46a0-47a6-80d2-ac753112c3ee.png)

**Comment by elsylambert** [comment]
Mac Log file:
[Tue May 03 2022.log.zip](https://github.com/unfoldingWord/translationCore/files/8617842/Tue.May.03.2022.log.zip)
 Windows log file:
[Tue May 03 2022.zip](https://github.com/unfoldingWord/translationCore/files/8617856/Tue.May.03.2022.zip)

**Comment by PhotoNomad0** [comment]
> translationCore 3.2.0 ([e319381](https://github.com/unfoldingWord/translationCore/commit/e31938198b2332e403c4608bff8852fc55ae17fe)) . Issues Resolved : Seeing all the language resources available for download in the Content Update List. Works fine.
> 
> Still having problems in Mac:
> 
>     * I downloaded ru_gl Translation helps resources(tA, tW and tN).
> 
>     * Re-opened 3JN/Titus project to see ru_gl, but the GL list does not show ru_gl in Mac. But this works fine in Windows.
>       Mac screenshot:
> 
> 
> <img alt="Screen Shot 2022-05-04 at 12 08 10 AM" width="803" src="https://user-images.githubusercontent.com/51806180/166621932-93e52a0e-667b-44b4-bc07-53e0eb113166.png">
> 
> Windows screenshot: ![image](https://user-images.githubusercontent.com/51806180/166622149-50d77baf-6c31-4c76-aa54-7798cb446725.png)
> 

@elsylambert - Looking at the windows log, it looks like for windows you have the rlob loaded from ru_gl which has alignments for tit and 3jn:
`getValidGatewayBibles() - For owner ru_gl, rlob, ru, tit - is VALID aligned bible for translationNotes`
and
`getValidGatewayBibles() - For owner ru_gl, rlob, ru, 3jn - is VALID aligned bible for translationNotes`

On mac, starting with fresh resources, when I download just the  ru_gl Translation helps resources(tA, tW and tN), ru/ru_gl does not come up as valid GW language (the same as you saw), since I have no aligned ru bibles from ru_gl.  Then when I download the rlob from ru_gl, I now see the ru_gl as a valid GW language.

**Comment by PhotoNomad0** [comment]
> -Another problem is in Windows:
> 
>     * Opened tW with ru_gl and got Blank screen.
>       ![ru_gl_tW](https://user-images.githubusercontent.com/51806180/166622209-619c0792-46a0-47a6-80d2-ac753112c3ee.png)

@elsylambert - I can also reproduce this problem on Mac, will take a closer look tomorrow.

**Comment by elsylambert** [comment]
@PhotoNomad0 On Mac: I dowmloaded rlob from ru_gl and I can see ru_gl as Valid GW language but hindi-d43-catalog(hi) and kn-door43-catalog resources do not show up.
<img width="803" alt="Screen Shot 2022-05-05 at 9 36 08 AM" src="https://user-images.githubusercontent.com/51806180/166934891-834f5abf-fd2e-4796-9376-552630e50fd7.png">

- Opened tC(Saw En and Hi as GL), Missing Kn on first startup.
- Downloaded ru(door43) Resources, Reopened tC. Now seeing En and ru_gl.
- Tried to download Kn resources but did not find it in the Content Update list(as I already had all of the KN Resources in my local).
- Reopened tC, still not seeing hi and kn Resources.
- Log File:
[Thu May 05 2022.log.zip](https://github.com/unfoldingWord/translationCore/files/8631651/Thu.May.05.2022.log.zip)

**Comment by elsylambert** [comment]
@PhotoNomad0 Just found that as soon as I download a resource from the Content update, it removes a resource form the GL list. After I downloaded another ru resource, I lost ru-door43 resource from the GL List.
<img width="803" alt="Screen Shot 2022-05-05 at 9 45 20 AM" src="https://user-images.githubusercontent.com/51806180/166936731-0f30171f-7ebd-40a0-b2f9-3d413d098b00.png">
Latest LOG:[Thu May 05 2022.log.zip](https://github.com/unfoldingWord/translationCore/files/8631689/Thu.May.05.2022.log.zip)

**Comment by PhotoNomad0** [comment]
@elsylambert fixes for blank tw screen are in dev build [79e06fb]

**Comment by elsylambert** [comment]
Separated the above issues(missing Resources) to #7300.

**Comment by elsylambert** [comment]
translationCore 3.2.0 (79e06fb). Not seeing this issue. works fine.
