### ISSUE TITLE
GL Resources List on Tools card not showing the available GL

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/translationCore#7300]
@PhotoNomad0 found that as soon as I download a resource from the Content update, it removes a resource form the GL list. After I downloaded another ru resource, I lost ru-door43 resource from the GL List.
<img width="803" alt="Screen Shot 2022-05-05 at 9 45 20 AM" src="https://user-images.githubusercontent.com/51806180/166936731-0f30171f-7ebd-40a0-b2f9-3d413d098b00.png">
Latest LOG:[Thu May 05 2022.log.zip](https://github.com/unfoldingWord/translationCore/files/8631689/Thu.May.05.2022.log.zip)

On Mac: I downloaded rlob from ru_gl and I can see ru_gl as Valid GW language but hindi-d43-catalog(hi) and kn-door43-catalog resources do not show up.
<img width="803" alt="Screen Shot 2022-05-05 at 9 36 08 AM" src="https://user-images.githubusercontent.com/51806180/166934891-834f5abf-fd2e-4796-9376-552630e50fd7.png">

- Opened tC(Saw En and Hi as GL)
- Downloaded ru(door43) Resources, Reopened tC. Now seeing En and ru.
- Tried to download Kn resources but did not find it in the Content Update list(as I already had all of the KN Resources in my local).
- Reopened tC, still not seeing hi and kn Resources.

**Comment by elsylambert** [comment]
Retested in translationCore 3.2.0 (79e06fb) with clean start(deleted resources folder) and not seeing this problem.

**Comment by elsylambert** [comment]
[Tue May 10 2022.log.zip](https://github.com/unfoldingWord/translationCore/files/8664368/Tue.May.10.2022.log.zip)
Happening again in translationCore 3.2.0 (12353d0) after the upgrade.
-Installed translationCore 3.2.0 (12353d0).
- Opened project with en Resources.
- Downloaded the latest en Resources.
- Now not seeing en in the GL list in tools card.

**Comment by PhotoNomad0** [comment]
@elsylambert This should be fixed in Branch develop build 15b6efa

**Comment by elsylambert** [comment]
This issue is resolved in translationCore 3.2.0 (15b6efa) for Mac OS.
