### ISSUE TITLE
Export to CSV failing with a crash

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/translationCore#7307]
translationCore 3.2.0 (15b6efa)
![image](https://user-images.githubusercontent.com/51806180/168624513-934aed3f-466c-4b8f-a819-228ed5756226.png)

**Comment by PhotoNomad0** [comment]
@elsylambert - should be fixed in develop build [cf1e99

**Comment by elsylambert** [comment]
Not seeing this problem in translationCore 3.2.0 (fcf1e99). Export to CSV works as expected.
