### ISSUE TITLE
Failing to send feedback.

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/translationCore#7311]
![image.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/5ccb0c10-cee1-43b1-a827-e01d50f1cdba)

**Comment by PhotoNomad0** [comment]
@elsylambert fix is in develop branch [a1634b3]

**Comment by elsylambert** [comment]
Works fine in translationCore 3.2.0 (a1634b3).

**Comment by elsylambert** [comment]
Not seeing this problem in translationCore 3.3.0 (ce8ec7b).
