### ISSUE TITLE
tN has bug that changing orgs does not trigger changing checks if language stays the same.

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#7316]
### User Story

tN has bug that changing orgs does not trigger changing checks if language stays the same. This is in 3.2.0.

As a [type of user], I want [some goal] so that [some reason].

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by PhotoNomad0** [comment]
@elsylambert @birchamp  This bug will be fixed in the 7 column TSV upgrade (need to fix this in order to do testing), but creating this issue to make sure that it is tracked.

**Comment by birchamp** [comment]
Thanks for catching this Bruce. I don't think it will be a common user
issue, but it should definitely be fixed.

**Comment by birchamp** [comment]
As stated above this is needed for TSV7

**Comment by PhotoNomad0** [comment]
@elsylambert This should be fixed in latest dev build.

**Comment by elsylambert** [comment]
Works fine in translationCore 3.2.1 (2c2672c) . When organization is switched the checks are changing as expected.

**Comment by elsylambert** [comment]
Works fine in translationCore 3.3.0 (ce8ec7b).
