### ISSUE TITLE
On tC startup remove bibles processed with different usfm-js version update with bundled bibles

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#7319]
### User Story

We have made a fix to USFM-js to preserve space before punctuation.  This impacts the UHB and maybe other languages.  Since the UHB is not changing that frequently, we run the risk that the user already has downloaded the latest UHB with tC 3.2.0, and then when they upgrade to 3.2.1 (for example), it will not replace the installed UHB with the bundled version because the version numbers are the same.

A few options:
1. On D43-Catalog and unfoldingWord, we increment the version number of UHB after the new tC is released - this could still be problematic
1. in the newer tCore we could add a special case for the UHB that we force update of UHB after tC upgrade
1. add processing date to the installed bibles so that we can compare to processing date of bundled resources to determine if we need to upgrade a bible
1. on tC version update we remove all the installed bibles and auto install bundled bibles (this is what we already do for tHelps). May be overkill, but safe for users, and less work for developers
1. if tC bundled resource is newer than installed resources we remove all the installed bibles and auto install bundled bibles (this is also what we already do for tHelps). May be overkill, but safe for users, and less work for developers.  This is better for developers and QA since we don't have to worry about manually deleting resources before testing.

Number 5 is my recommendation.  Has advantage of most safety going forward.  But slows down first installs, and users will have to download again any custom bibles. 4 and 5 are probably the least effort since we already do this for tHelps.

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by birchamp** [comment]
What if we track USFM.js in the manifest and only download/re-process if USFM.js has changed?

**Comment by PhotoNomad0** [comment]
**Notes:**

- [x] Add the current usfm-js version the bible manifest when we process the bible resource downloads.
- [x] when checking for updated resources, flag bibles with older usfm-js versions in manifest as being outdated.
- [x] on tCore startup do quick check of bible resources and remove bibles with outdated usfm-js versions in manifest, then do resource migration from bundled resources.

**Comment by PhotoNomad0** [comment]
@elsylambert fixed in translationCore 3.2.1 (39a0d6d). On upgrade from 3.2.0, all bibles in resources folder without `"usfm-js": "3.4.0"` field in manifest.json will be removed.  Any bundled bibles installed will have the field, and future downloaded bibles will have it also.

**Comment by elsylambert** [comment]
Looks good in Version 3.2.1 (39a0d6d). On upgrade from 3.2.0, all bibles in resources folder without "usfm-js": "3.4.0" field in manifest.json were removed and bundled Bibles were installed with the newer field.
