### ISSUE TITLE
Need to address growing install sizes of tCore - we are approaching 1/2 GB

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#7320]
### User Story

Need to address growing install sizes of tCore.  We bundle all the aligned Bibles now in the d43 catalog (as well as Greek & English for unfoldingWord). Each release there are more Bibles and the existing Bibles get larger: 
- Version 3.2.0 is about 400MB
- version 3.1.0 had 300MB
- version 3.0.1 had 200MB installs

This makes it take more time for downloads on slower internet connections.  Higher expense on metered connections. And possibility of having to try more than once.

There is a trade off here - not everyone needs all the bibles, but everyone is penalized by larger download sizes.

Perhaps we need to look:
- minimal bundle packages and side-load installs for full resource bundle.
- investigate creating light tCore builds alongside the heavy builds - increased build times.

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by PhotoNomad0** [comment]
I was able to reduce the size by 100MB by hand grooming the bundled resources.  Discovered that the script was leaving older versions in Greek, Hebrew, English, Hindi.  Need to investigate in the future why this is happening.

**Comment by birchamp** [comment]
@PhotoNomad0 My recollection is that since previous projects use checks connected with the older versions, we need those versions available.  Will the user be prompted to download the older version of the resources or will it invalidate the checks based on the new version?

**Comment by PhotoNomad0** [comment]
In case of original languages we always bundle just the latest.  in case of TN, the user will be prompted to download the correct version of original language.  In case of other languages we replace the bibles and thelps with the latest when they update tC if they are bundled with tC

**Comment by birchamp** [comment]
If we set a DoD as having a minimal and maximal install where minimal is latest English and OrigL, and maximal is everything we currently include, does that solve for this issue?

**Comment by PhotoNomad0** [comment]
@elsylambert - this is now working in translationCore 3.4.0 (551be4e).  Note that there are now twice as many build artifacts now.  The minimal builds have LITE in the name.  They only have en, Greek and Hebrew resources bundled into them.  I would expect only difference is for the LITE builds to see quicker start ups on clean installs.

**Comment by PhotoNomad0** [comment]
@birchamp @elsylambert  The full builds are running about 300MB, but the minimal builds are only about 180MB.  The minimal builds use 1.3GB in resources folder on clean install.  Where the full builds use 3.5GB in resources folder on clean install.

**Comment by elsylambert** [comment]
translationCore 3.4.0 (551be4e) .
<img width="369" alt="Screen Shot 2022-09-22 at 9 21 06 AM" src="https://user-images.githubusercontent.com/51806180/191758179-54df1da6-5f28-4a27-8419-5118c789274f.png">
<img width="364" alt="Screen Shot 2022-09-22 at 9 21 38 AM" src="https://user-images.githubusercontent.com/51806180/191758321-e4f54083-cb6a-4d68-becf-d5c261508619.png">

**Comment by PhotoNomad0** [comment]
Notes:

@Birch @Elsy Have a question about naming the install files.  Currently we are inserting -LITE into the install file name for the minimal builds.  Should we add -FULL  to the install file name for the full builds?  Would you rather have something other than -LITE for the minimal builds install file name?
 
Birch 
What if we used min/max
However, lite is probably more standard
Not sure if full is what others use or not. Can you think of other apps to use as examples

Elsy
**MAX and LITE** 😊

**Comment by PhotoNomad0** [comment]
Notes:

- Discovered that we cannot attach all the installs to a single release.  Whenever the total size of the files goes over 2GB, a random file is dropped.  So we will have to go do two releases or host some files elsewhere.

- Thinking of doing two releases: one with tag name of vx.x.x and the other with vx.x.x-LITE
- we can detect the size of current release by the number of languages bundled.  Then on auto upgrade use the correct tag.
- need to fix bug updating macOS arm64 that it will fall back to x64.
