### ISSUE TITLE
In tn and tw, add support for displaying verse ranges in format `2:1,4`

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#7322]
### User Story

As a [type of user], I want [some goal] so that [some reason].

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by PhotoNomad0** [comment]
**Notes:**

- [x] Make sure check for updated helps data supports verse lists and spans
- [x] add verse markers in selection area.
- [x] come up with a solution to verse edit to edit multiple verses. (verseEditWrapper)

**Comment by PhotoNomad0** [comment]
**Feedback from Larry Sallee:**
I'm beginning to track, I think. I would say that the tW is a bad example, as we would never use multiple verses in the TWL. We would use them extensively in TQ's and in study-type notes—neither of which would have checks. The only place I can think of where they would show up in a check is the TN's. If they did appear there, it would almost certainly be a situation where each of the verses contributed to the topic being checked and would need to be referenced together to decide whether the translation was correct. For example, a TN for 2-3 consecutive verses that is one metaphor. Or a TN for separated verses, the first of which lists the metaphor and the second of which states the meaning. IMO, the checker would want to see them all to judge if the issue is handled correctly.

**Comment by PhotoNomad0** [comment]
@birchamp - the last hurdle on this issue is supporting multiple verses (such as 2:3,5) in verse editor for the checking tools.  This may mean a significant refactor for full support.  It seems like a bunch of work for a rarely used reference option.  A few implementation options:
1. disable verse edit in the case of multiple verses - maybe with message to use the expanded scripture pane to edit.  Or maybe have it automatically bring up the expanded scripture pane when edit is selected?  We could have the editor automatically open in first verse.
2. expand to checking tools to show a scroll-able array of single verse editors
3. expand the verse editor to also show the USFM verse markers if multiple verses.  When edit is saved we split at the verse markers and do multiple saves.  will have to add sanity checking logic in case a verse is inadvertently removed, changed, or added.

option 1 is the easiest.  The next two options require some significant refactoring.  And 3 is the hardest.

**Comment by birchamp** [comment]
It sounds like option 1 with using the expanded verse editor instead of disabling editing entirely is the best option. Jump to the first verse in the reference

**Comment by PhotoNomad0** [comment]
@elsylambert 
Here are some entries under ml test_org2 for tit:
<img width="604" alt="Screen Shot 2022-06-17 at 9 59 03 AM" src="https://user-images.githubusercontent.com/14238574/174313534-0637adda-747a-4232-8c6c-45a81d3fc29f.png">
Here is an entry under ml test_org2 for php:
<img width="615" alt="Screen Shot 2022-06-17 at 10 08 49 AM" src="https://user-images.githubusercontent.com/14238574/174315039-1e431e24-26d7-41ac-97c1-639a8c7bce60.png">

**Comment by PhotoNomad0** [comment]
@elsylambert Fix is in translationCore 3.2.1 (e7b7769) - a couple of checks above with verse lists ^^^^

**Comment by elsylambert** [comment]
@PhotoNomad0 Not able to open the project in translationCore 3.2.1 (e7b7769) 
![Large GIF (1146x732)](https://user-images.githubusercontent.com/51806180/174609516-088c8bd3-4071-4514-bcc0-5339767006c4.gif)
.

**Comment by elsylambert** [comment]
Looks good in translationCore 3.2.1 (e7b7769). Tested for test_org :ml_en. Seeing the verse ranges in tN and tW for Php and Tit respectively
<img width="1430" alt="Screen Shot 2022-06-20 at 2 35 54 PM" src="https://user-images.githubusercontent.com/51806180/174661608-c0b1d8ee-1441-472c-bff7-799f67eaf588.png">
.
<img width="1430" alt="Screen Shot 2022-06-20 at 2 34 41 PM" src="https://user-images.githubusercontent.com/51806180/174661623-7a531770-c728-4725-9db5-bc3e7b520ae3.png">

Upon editing, tC brings up Expanded scripture pane, starting with the first verse in the verse span. Works as defined.

**Comment by elsylambert** [comment]
Looks good in translationCore 3.3.0 (ce8ec7b).
