### ISSUE TITLE
Spike: Explore new data structure

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#733]
## Concerns to address:
- Merge conflicts
- Diverged History
- Making highlight/selection compatible
- Explore separation of concerns
- Normalize data between checks
- Store data independently from the way menu or checks are performed

**Comment by ihoegen** [comment]
I wonder if a delimiter based structure would be good for check data?  Anything that can be nested seems dangerous

**Comment by klappy** [comment]
@ihoegen: I agree, using delimiting formats greatly diminishes parsing errors, but come with it's own set of issues, such as repeating text that would become more work if we needed to change some of that. I'm trying to mix approaches so that we have a nested directory structure to minimize the bulk of repeated data. We can assess if what's left risks merge conflicts and discuss as a team to switch between json and csv or something else.

**Comment by klappy** [comment]
It's not complete but here is the latest:
[dot.apps.zip](https://github.com/unfoldingWord-dev/translationCore/files/814038/dot.apps.zip)

<img width="1280" alt="screen shot 2017-03-02 at 9 23 57 am" src="https://cloud.githubusercontent.com/assets/118073/23511076/fe8a93ea-ff29-11e6-8d6e-90720c155f05.png">
