### ISSUE TITLE
tCore still shows options even after they have been downloaded.

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#7331]
### User Story

tCore still shows options even after they have been downloaded.

to see the problem. in translationCore, click on Actions button and then click on “Check for content updates“.  Then Select all resources for lang/org such as:

![Screen Shot 2022-06-23 at 10.35.59 AM.png](https://images.zenhubusercontent.com/564e463c638e718c995eb353/f6cdae00-7d50-46ea-8c9a-c72986ee2d71)

After download completes, click again on Actions button and then click on “Check for content updates“.  Then we still see these options even though download succeeds:

<img width="790" alt="Screen Shot 2022-06-23 at 2 20 49 PM" src="https://user-images.githubusercontent.com/14238574/175369793-fca37589-dedc-48a1-aac2-330e5618de35.png">

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by PhotoNomad0** [comment]
@elsylambert fix is in translationCore 3.2.1 (2c2672c)

**Comment by elsylambert** [comment]
Looks good in translationCore 3.2.1 (2c2672c). Issue is resolved.

**Comment by elsylambert** [comment]
Looks good in translationCore 3.3.0 (ce8ec7b).
