### ISSUE TITLE
Empty check found in tN 

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/translationCore#7333]
translationCore 3.2.1 (2c2672c).
Project: [https://app.zenhub.com/files/65028237/7399e5b8-82cb-4ad2-9829-c720bc1a71f4/download](https://app.zenhub.com/files/65028237/7399e5b8-82cb-4ad2-9829-c720bc1a71f4/download)

Steps:
- copy and Paste the above project in tC Projects folder.
- Open tC and select the Exo project.
- Open tN using the org selection : മലയാളം (ml) - test_org2.(Please download if you don’t have this resource downloaded already). Make sure all selections are checked in the tN tools card.
- Scroll down to check "When Masculine Words Include Women". Note that there is an empty check after that.
![Screen Shot 2022-06-28 at 9.15.15 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/c48073e4-d178-4482-bfc1-d301613e45e6)
And the TA articles do not open for the checks that follow the empty check but works for the checks that precedes the empty checks.

Log File:
[Tue Jun 28 2022.log.zip](https://github.com/unfoldingWord/translationCore/files/9001469/Tue.Jun.28.2022.log.zip)

**Comment by PhotoNomad0** [comment]
Notes:
- This is an old tN resource: 2021-05-10
- There is an issue with the group ID's that have a leading ZERO WIDTH SPACE (Unicode: U+200B)

**Comment by PhotoNomad0** [comment]
making fix to trim zero width and no break spaces when downloading tn resources.

**Comment by PhotoNomad0** [comment]
@elsylambert added fix in translationCore 3.2.1 (4db5df4)

**Comment by PhotoNomad0** [comment]
@elsylambert Have a second build here for testing: translationCore 3.2.1 (c38c94f)

**Comment by elsylambert** [comment]
Looks good in translationCore 3.2.1 (c38c94f).

**Comment by elsylambert** [comment]
Not seeing the problem in translationCore 3.3.0 (ce8ec7b).
