### ISSUE TITLE
Support verse ranges that span chapter boundaries such as "2:3-3:2" and "2:3;3:2"

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#7338]
### User Story

As a [type of user], I want [some goal] so that [some reason].

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by birchamp** [comment]
Yes, let's **add** the semicolon (2:3;3:2) as most users will be used to typing that, but also allow for a comma between a verse from two chapters (2:3,3:1)

**Comment by PhotoNomad0** [comment]
Notes:
- in tc-ui-toolkit:
  - highlighting is done in verseArray()
  - updated verseHelpers.getVerseData() to count original words by verse if multi-verses 
  - now need to update highlightHelpers.isWordArrayMatch() to check previous verse word-counts
  - checking area needs to be updated for verse ranges

**Comment by PhotoNomad0** [comment]
@elsylambert fixed in latest develop build translationCore 3.3.1 (a97a13b) 

To test download the ult and tw resources from ml/test_org2.  Open a tit project and for tW select ml/test_org2, scroll down to Christ.  make sure all verses are shown in selection area as well as in scripture panes.

<img width="1728" alt="Screen Shot 2022-08-03 at 7 13 46 AM" src="https://user-images.githubusercontent.com/14238574/182595145-067914ff-2813-46b2-8ef1-f7461d653e90.png">

**Comment by elsylambert** [comment]
translationCore 3.4.0 (551be4e).Verse ranges that span across chapters look good. Shows fine in the scripture pane and left side categories. Selection works fine.


<img width="1492" alt="Screen Shot 2022-09-22 at 8 52 11 AM" src="https://user-images.githubusercontent.com/51806180/191751896-519f56c9-6145-45e1-881c-0b341702a096.png">

**Comment by PhotoNomad0** [comment]
Notes:
- This is a continuation of issue: https://github.com/unfoldingword/translationcore/issues/7322
- The verse edit behavior was decided in https://github.com/unfoldingWord/translationCore/issues/7322.  for speed of development, Instead of changing the verse editor in the checking tools to support multiple verses, if there are multiple verses we bring up the expanded scripture pane and automatically open the editor in it to the first verse in the list.  It is a crude compromise, but the user could edit one verse at a time.
- asked @birchamp and he decided that cross chapter editing is not a priority of the stakeholders right now.  We could add later if requested.
