### ISSUE TITLE
New Data Structure

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#734]
This is to change the current ./checkdata folder that is in each project folder. Nothing changes to the location of the project or the project folder name.

## Location of this directory
- **~** => The user's home directory
  - /**translationCore** => The path where we store all user projects
    - /**ar_eph_text_ulb** => The project folder
      - /**manifest.json** => The project manifest
      - /**...** => all the files of the project
      - /**.apps** => the location of all tC data for each project

## Data locations
- /**.apps** => based on the spec this is where all app data goes
  - /**translationCore** => using the app name, that's where our app specific data goes
    - /**index** => where the index/parsed data for the checks/menu are stored
    - /**checkData** => where user generated data is stored
    - /**resources** => where sources/resources unparsed data is stored if any

## Index
App/Tool generated data that is ./.apps/translationCore/index
- /**index** => same folder as above
  - /**translationNotes** => checking tool namespace
    - /**index.json** => inside of tool namespace but not book namespace
    - /**eph** => book namespace
      - /**figs_metaphor.json** => list of checks for this id in menu and data to perform check

## Group Index
Index file that addresses order and labels ./apps/translationCore/index/translationNotes/index.json
```json
[
  {"id": "figs_hyperbole", "name": "Hyperbole"},
  {"id": "figs_rpronouns", "name": "Reflexive Pronoun"},
  {"id": "figs_metaphor", "name": "Metaphor"},
  {"id": "figs_activepassive", "name": "Active or Passive"},
  {"id": "figs_ellipsis", "name": "Ellipsis"},
  {"id": "figs_...", "name": "..."}
]
```

## Group Data
Index file that addresses list of checks for this id in menu and data to perform check ./apps/translationCore/index/translationNotes/eph/figs_metaphor.json
```json
[
  {
    "priority": 2, // => is this check "essential" or first priority? Do priority 1 checks first
    "information": "Paul speaks of destruction as a person who bore a son whose goal is to totally destroy everything. AT: \"the one who destroys everything he can\" (See: [[:en:ta:vol1:translate:figs_metaphor]])\n  ", // => the note that goes along with this check
    "contextId": {
      "reference": {
        "bookId": "2th",
        "chapter": "1",
        "verse": "3"
      },
      "tool": "translationNotes",
      "group": "figs_metaphor",
      "quote": "God is sending them a work of error so that they would believe a lie",
      "occurrence": 1
    }
  },
...
]
```

## checkData
User generated data that is ./.apps/translationCore/checkData
- /**checkData** => same folder as above
  - /**comments** => namespace for comments data
  - /**reminders** => namespace for reminders/bookmark/flag data
  - /**selections** => namespace for selections data
  - /**translationNotes** => namespace for tool data
  - /**translationWords** => namespace for tool data
  - /**verseEdits** => namespace for verse edits data

## contextId attributes
Each of the checkData types include the same contextId attributes
```json
{
  "contextId": {
    "reference": {
      "bookId": "2th",
      "chapter": "1",
      "verse": "3"
    },
    "tool": "translationNotes",
    "group": "figs_hyperbole",
    "quote": "should always give thanks to God",
    "occurrence": 1
  }, // => namespace of the check in which this comment was made, partition is not hard in data structure so it can be shared between checks of the same verse
}
```

## Comments Data
Nested inside the checkData Namespace of **./checkData/comments/eph/1/3/**
- /**2017-02-17T22:23:49.357Z.json** => timestamp as filename with .json extension
```json
{
  "text": "I removed a hyphen in the first word.", // => actual comment being saved
  "verseEditId": "2017-02-17T22:23:50.357Z", // => timestamp/filename of last verse edit when comment was made
  "user": "klappy", // => user that made last edit of comment
  "modifiedTimestamp": "2017-02-17T22:23:49.357Z", // => timestamp that updates on each edit of this json
  "contextId": ...
}
```

## Reminders Data
Nested inside the checkData Namespace of **./checkData/reminders/eph/1/3/**
- /**2017-02-17T22:23:49.357Z.json** => timestamp as filename with .json extension
```json
{
  "enabled": true, // => actual status of the reminder
  "verseEditId": "2017-02-17T22:23:50.357Z", // => timestamp/filename of last verse edit when reminder was made
  "user": "klappy", // => user that made last edit of reminder
  "modifiedTimestamp": "2017-02-17T22:23:49.357Z", // => timestamp that updates on each edit of this json
  "contextId": ...
}
```

## Selection Data
Nested inside the checkData Namespace of **./checkData/selection/eph/1/3/**
- /**2017-02-17T22:23:49.357Z.json** => timestamp as filename with .json extension
```json
{
  "selection": [
    {
      "text": "സഹോദരന്മാരേ", // => actual text selected
      "occurrence": 1, // => which occurrence was selected
      "occurrences": 1, // => how many occurrences of the word are there 
    }
  ],
  "verseEditId": "2017-02-17T22:23:49.357Z", // => timestamp of the last edit made to verse
  "user": "klappy", // => user that made last edit of comment
  "modifiedTimestamp": "2017-02-17T22:23:49.357Z", // => timestamp that updates on each edit of this json
  "contextId": ...
}
```

## Verse Edit Data
Nested inside the checkData Namespace of **./checkData/verseEdits/eph/1/3/**
- /**2017-02-17T22:23:49.357Z.json** => timestamp as filename with .json extension
```json
{
  "before": "സഹോദരന്മാരേ, നിങ്ങളുടെ വിശ്വാസം ഏറ്റവും വർദ്ധിച്ചും നിങ്ങൾ ഓരോരുത്തർക്കും അന്യോന്യം സ്നേഹം പെരുകിയും വരികയാൽ ഞങ്ങൾ ഉചിതമാകുംവണ്ണം ദൈവത്തിന്നു എപ്പോഴും നിങ്ങളെക്കുറിച്ചു സ്തോത്രം ചെയ്‌വാൻ കടപ്പെട്ടിരിക്കുന്നു.", // => text before the edit
  "after": "സഹോദ-രന്മാരേ, നിങ്ങളുടെ വിശ്വാസം ഏറ്റവും വർദ്ധിച്ചും നിങ്ങൾ ഓരോരുത്തർക്കും അന്യോന്യം സ്നേഹം പെരുകിയും വരികയാൽ ഞങ്ങൾ ഉചിതമാകുംവണ്ണം ദൈവത്തിന്നു എപ്പോഴും നിങ്ങളെക്കുറിച്ചു സ്തോത്രം ചെയ്‌വാൻ കടപ്പെട്ടിരിക്കുന്നു.", // => text after the edit
  "tags": ["wordChoice", "punctuation", "i didn't like it"], // => tags for describing the edit
  "user": "klappy", // => user that made last edit of comment
  "modifiedTimestamp": "2017-02-17T22:23:49.357Z" // => timestamp that updates on each edit of this json
  "contextId": ...
}
```

## Tool Data
Nested inside the checkData Namespace of **./checkData/translationWords/eph/1/3/**
- /**2017-02-17T22:23:49.357Z.json** => timestamp as filename with .json extension
```json
{
  "selectionId": "2017-02-17T22:23:49.357Z", // => timestamp/filename of last selection
  "verseEditId": "2017-02-17T22:23:49.357Z", // => timestamp/filename of last verseEdit
  "commentId": "2017-02-17T22:23:49.357Z", // => timestamp/filename of last comment
  "user": "klappy", // => user that made last edit of comment
  "modifiedTimestamp": "2017-02-17T22:23:49.357Z" // => timestamp that updates on each edit of this json
  "contextId": ...
}
```

**Comment by mannycolon** [comment]
https://git.door43.org/klappy/2TH/src/master
