### ISSUE TITLE
Loosing Alignment and Blank Align section when GL is changed to different org

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/translationCore#7341]
Field Reported by Sam:
First Video: •    https://www.youtube.com/watch?v=amPpjv0H_Pg
•    export aligned 1sa bible to USFM with alignments and import back as a test project. 
•    Then when switch WA GW from D43 to en/unfoldingWord the alignments go to zero.  Seems to be broken in tool - alignment area is blank - no words at all.
•    no checks shown for tW and tN, but checks are not exported with USFM
•    when they change tW GW to en/unfolding word and launch with only names selected - tool page is empty. Seems broken in tool.

Test Steps:
Did a fresh install of 3.2.0 on windows and following the test steps as in the video.
- When immediately after the usfm import, WA GW is chosen as en-unfoldingword, we see the alignments go 0% and Align section has no words. When switched to en-Door43, alignment is shown 97%(included alignments). If I switch back to en-unfoldingword, I see the alignments 97% and Align section has words. 
- Not seeing the tW screen go blank with en-unfoldingword
https://images.zenhubusercontent.com/65028237/70d1ab2f-ca41-4097-944b-7f797b74ce02/local_import_wt_alignmt_data_.mp4

**Comment by elsylambert** [comment]
Log file:[Mon Jul 04 2022.zip](https://github.com/unfoldingWord/translationCore/files/9045967/Mon.Jul.04.2022.zip)

**Comment by PhotoNomad0** [comment]
Testing with: https://git.door43.org/ElsyLambert/en_test_rut_book

**Comment by PhotoNomad0** [comment]
@elsylambert FYI - This is fixed in tC 3.2.1 develop build.  In 3.2.0 there is a bug switching GL orgs in WA did not load the new original language bible.

**Comment by elsylambert** [comment]
This issue is resolved in translationCore 3.2.1 (24bd9f9). No longer loosing alignments or blank Align section in wA when GL is changed to a different org.

**Comment by elsylambert** [comment]
Verified in translationCore 3.3.0 (9e96976). Not seeing blank alignment when GL is switched.
