### ISSUE TITLE
Support Pre-release testing in Catalog Next

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#7343]
### User Story

As an admin I want to be able to do pre-production (draft) release testing in Catalog Next.

Here is a preliminary mock up of admin options:

<img width="791" alt="Screen Shot 2022-07-03 at 8 45 26 PM" src="https://user-images.githubusercontent.com/14238574/177316654-533e9845-985f-41ae-94b5-eff9cf0950a5.png">

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by PhotoNomad0** [comment]
Notes:

- [ ] remove checking level support from tCore?
- [ ] add option to search with stage preprod.

**Comment by birchamp** [comment]
- Change "Include Pre-Release Resouces" to "Show Pre-Release Resources"
- Pop-up a busy box when re-fetching

**Comment by PhotoNomad0** [comment]
@elsylambert - whenever the user changes state of "Show Pre-Release Resources", there will be a refetch of resources.

**Comment by PhotoNomad0** [comment]
@elsylambert fix is in translationCore 3.2.1 (2f23553).  If you do a regular download of ml_tn/test_org2 you will get version 0.4.1.  Then turn on "show prerelease resources" and then download ml_tn/test_org2 and you will get version 0.5.1.

**Comment by elsylambert** [comment]
@PhotoNomad0 Unable to install translationCore 3.2.1(2f23553) due to an error.
![image](https://user-images.githubusercontent.com/51806180/178492085-3c298ac0-6435-4e1d-b2d3-e79804ac337d.png)

**Comment by PhotoNomad0** [comment]
@elsylambert - do you have a log file?  I didn't see a problem in MacOS.  Will try WIndows

**Comment by elsylambert** [comment]
@PhotoNomad0  Win 11.
Log file:
[Tue Jul 12 2022.zip](https://github.com/unfoldingWord/translationCore/files/9093755/Tue.Jul.12.2022.zip)

**Comment by PhotoNomad0** [comment]
@elsylambert This log file is for v3.2.1 (24bd9f9)?

**Comment by PhotoNomad0** [comment]
@elsylambert I was able to install on Windows 10.  Will try Windows 11 next.

**Comment by elsylambert** [comment]
@PhotoNomad0 win 11 machine was on 3.2.0(a1634b3) and I upgraded to translationCore 3.2.1 (2f23553), thats when I got the error in tC/resources/..../books.zip.
So I installed translationCore 3.2.1 (https://github.com/unfoldingWord/translationCore/commit/24bd9f985fc240d2023ae3dc5c6a4ee66bda360d). instead and it worked fine. now I upgraded from translationCore 3.2.1 (https://github.com/unfoldingWord/translationCore/commit/24bd9f985fc240d2023ae3dc5c6a4ee66bda360d). to translationCore 3.2.1 (2f23553), it worked fine.

**Comment by PhotoNomad0** [comment]
@elsylambert It looks like that error occurred before tCore even started.  So that is an installer error message (and not a helpful one).  So would not see anything in the log.  Could the PC's hard drive be full?

**Comment by PhotoNomad0** [comment]
...it's a file copy error.

**Comment by elsylambert** [comment]
Works as expected in translationCore 3.2.1 (2f23553).
@PhotoNomad0 I have three observations:
1. I do not see the third check box- "Delete downloaded Resources" in the admin options.
2. The checkbox selections do not get cleared when I re-open the Update content window. i.e I selected the option "Show Pre-release Resources" and then downloaded the resource. I reopened the Content Update window and the "Show Pre-release Resources" was already checked.
3. The content Update window opens in the background when the Alert is displayed and it gets closed when you make selection on the alert.
![image](https://user-images.githubusercontent.com/51806180/178646257-3895e85c-50ca-4f72-9e28-642ec524f34e.png)

**Comment by PhotoNomad0** [comment]
> Works as expected in translationCore 3.2.1 ([2f23553](https://github.com/unfoldingWord/translationCore/commit/2f23553a3a0113ce197f00cbfea40ff7dc982c6e)). @PhotoNomad0 I have three observations:
> 
>     1. I do not see the third check box- "Delete downloaded Resources" in the admin options.

Sorry @elsylambert , that was something @birchamp decided to remove from the issue but it was not updated here.

> 
>     2. The checkbox selections do not get cleared when I re-open the Update content window. i.e I selected the option "Show Pre-release Resources" and then downloaded the resource. I reopened the Content Update window and the "Show Pre-release Resources" was already checked.

@elsylambert I made the checkbox sticky for the tCore session.  I was thinking it would be annoying for the admin if they were doing repeated downloads that they would have to reselect the pre-release checkbox and wait for a new fetch.  I could reset this after each use.  @birchamp - what  do you think?

>     3. The content Update window opens in the background when the Alert is displayed and it gets closed when you make selection on the alert.

@birchamp - is this something we want to work on as part of the issue?  I believe it is a pre-existing issue, but would take some refactoring to fix.  It is annoying, but does not block the user.

**Comment by elsylambert** [comment]
Thanks for the update @PhotoNomad0
for 2., it seems reasonable for the checkbox to be sticky per tC session.
for 3, Its not a blocker and if requires refactoring then I wont push you to fix UI at this point.

**Comment by PhotoNomad0** [comment]
FYI - item 3 occurs starting with the second time you open the dialog if you haven't selected to not show the warning again.

**Comment by PhotoNomad0** [comment]
Let me check - I may have a quick fix for 3 that may work. @elsylambert

**Comment by PhotoNomad0** [comment]
> Let me check - I may have a quick fix for 3 that may work. @elsylambert

No, the quick fix did not work.

**Comment by birchamp** [comment]
2. Since it clears the next time tC is run, I think that we can leave it checked during the session. 
3. Since this is a pre-existing issue, it's not necessary to fix it.  @elsylambert do we have an issue for this already? If so, can you link to it here?

**Comment by elsylambert** [comment]
I am passing this issue since it works as defined and expected and based on the above comments, 2- functionality is fine and 3 doesn’t need to be fixed at this point.

**Comment by PhotoNomad0** [comment]
@elsylambert have a fix for downloading pre-release of en_tn/test_org in build translationCore 3.3.0 (350f91e)

**Comment by elsylambert** [comment]
Not seeing the problem in translationCore 3.3.0 (350f91e) while downloading en_tn/test_org pre-release Resource.
