### ISSUE TITLE
Get error importing USFM files with BOM marker

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#7353]
### Description

Get error importing RU EST bible

### Steps to Reproduce

* https://www.youtube.com/watch?v=0aPo9213VIk
    * downloaded USFM file from https://git.door43.org/Door43-Catalog/ru_rlob/src/branch/master/17-EST.usfm
    * in tCore import est from USFM file, but tCore refused to import it.  See error dialog "Book not supported"

Note: at first glance there does not appear to be a problem with the USFM file, but tCore parses incorrectly.  Seems to be a problem in parsing the first \id line.  regex bug?

**Comment by PhotoNomad0** [comment]
Note:
- seems to be something with the file format?
- if I add a newline to start of file, it imports correctly.

**Comment by PhotoNomad0** [comment]
Note:
* it looks like USFM-js is choking on the BOM marker at the start of the file (0xEF, 0xBB, 0xBF).

**Comment by Samuel-Kim** [comment]
> Note:
> 
> * it looks like USFM-js is choking on the BOM marker at the start of the file (0xEF, 0xBB, 0xBF).

Thank you for finding the reason. An easy way to solve this problem is to remove the BOM marker.

**Comment by PhotoNomad0** [comment]
@birchamp - In tCore we have a few options:
1. remove the BOM marker from start of USFM data in USFM-js before parsing the USFM and update tCore to use latest USFM-js
2. remove the BOM marker from start of USFM data in tCore before handing off to USFM-js
3. do nothing and hope the validator will be updated to flag the problem on DCS

It seems that # 1 has advantage of code fix in one place, and then we update apps to use latest USFM-js.

**Comment by birchamp** [comment]
Yes option 1. @PhotoNomad0

**Comment by PhotoNomad0** [comment]
Note that Notepad (and other apps) adds a BOM markers when it saves files in UTF-8 format.

**Comment by Samuel-Kim** [comment]
I use Visual Studio Code & AkelPad.

**Comment by PhotoNomad0** [comment]
@Samuel-Kim Thanks - committing a fix, but note that it did not make it into the tC 3.3.0 release which is now in QA testing before release.

**Comment by PhotoNomad0** [comment]
@elsylambert this is fixed in translationCore 3.3.0 (b0ef8c5).

**Comment by elsylambert** [comment]
EST book local import works fine in translationCore 3.3.0 (3d8552f) . Not seeing "Book not supported" error message.
