### ISSUE TITLE
Seeing 500 errors downloading resources in latest develop build

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#7355]
### User Story
When I try to download all resources I get many errors.  When I look in the log file I see a lot of 500 errors because the URL is invalid:

![Screen Shot 2022-07-07 at 8.06.51 AM.png](https://images.zenhubusercontent.com/564e463c638e718c995eb353/2cf08760-ebf0-40fc-a6a8-b77087b09734)

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by PhotoNomad0** [comment]
@elsylambert This is to fix a catalog next bug I recently introduced. The fix is in translationCore 3.2.1 (3eaad77)

**Comment by elsylambert** [comment]
Not seeing 500 errors in translationCore 3.2.1 (24bd9f9). Downloading ALL resources work fine.

**Comment by elsylambert** [comment]
Not seeing 500 errors while downloading All resources in translationCore 3.3.0 (ce8ec7b).
