### ISSUE TITLE
Spike: List possible interactions for use cases

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#736]
What is every possible click/drag/release/overlaps/outside of area...

**Comment by RoyalSix** [comment]
X is the users word/words to be highlighted
Single Action Type:
- Click X
- Click whitespace before/after X
- Click punctuation
- Click & drag over X
- Click & drag over X (containing containing multiple non-words)
- Click & drag over start/end of X to a character before/start the end of X
- Click & drag over X + whitespace (before and/or after)
- Click & drag over X + punctuation (before and/or after)
- Click & drag over X past the start/end of the verse
- Click & drag above/below X

**Comment by RoyalSix** [comment]
Multiple Action Type:
- Any type of "One Action Type" combined with another.
