### ISSUE TITLE
Button to clear pre-releases

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/translationCore#7363]
Admins that test pre-releases may want to get back to work on a project using a production release resource.  If the pre-release is newer they won't be able to do that without deleting the pre-release that they tested. Add a button to clear downloaded pre-release updates. This button will clear all pre-releases on the local install.  _Be sure to not delete last prod download of tHelps_. Button will say: "Delete all pre-release resources", then prompt "Do you want to delete all of the pre-release resources that have been downloaded?"

DoD:
---
Clicking the Delete all pre-releases button and confirming will delete all downloaded pre-release resources

**Comment by birchamp** [comment]
@elsylambert can you take a look at the wording of the button and prompt for this?

**Comment by elsylambert** [comment]
@birchamp I changed the button text to "Delete all pre-release resources" to make the term consistent across the app. Prompt looks good to me.

**Comment by PhotoNomad0** [comment]
@elsylambert Implemented in translationCore 3.3.0 (4a9b3e4)

**Comment by elsylambert** [comment]
Looks good in translationCore 3.3.0 (4a9b3e4) 
and works as expected.
