### ISSUE TITLE
French locale UI issues

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/translationCore#7372]
If hover is a challenge then it can be put in another issue for the next release.

DoD
---
Text in the boxes or buttons does not overlap the frame. 

Details
---
translationCore 3.3.0 (4a9b3e4)
The following places the text goes out of the button frame:
Tools card page>GL selections
![french tools card.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/766f0e56-6f29-4cfa-b5f2-57477bd4d8f5)
TW/TN checking area: Clear Selection/Edit Verse
![image](https://user-images.githubusercontent.com/51806180/180275863-238d072b-6091-4148-8c94-1567a88b37ef.png)
![tN](https://user-images.githubusercontent.com/51806180/180275940-86bd8e6f-36b9-4ccd-bc27-f63edd218a22.png)

**Comment by PhotoNomad0** [comment]
@elsylambert Have ellipsis fixes in translationCore 3.3.0 (25a356f)

**Comment by PhotoNomad0** [comment]
@elsylambert New build translationCore 3.3.0 (9e96976) has hover text support for the above buttons and drop down.

**Comment by elsylambert** [comment]
Looks good in translationCore 3.3.0 (9e96976).
