### ISSUE TITLE
Add ability to Load Master branch resources to tCore Scripture pane.

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#7375]
### User Story
Add ability to Load Master branch resources to tCore Scripture pane.

We could add option to enter a repo URL to Scripture pane drop-down to read bible resources.  This would input:
- a tCore book repo that is for the same book of the bible as the current project
- a whole bible repo that contains the book of the bible.

Also add a refresh button to three dot menu (with online warning)

To simplify implementation:
- don't save data to disk, but just keep in memory for session.  After user reopens tCore, when they open tool give prompt to user in scripture pane that they need to refresh the resource.
- save URL to the USFM file into the repo manifest
- could add an item to end of list - `load from URL` that would trigger tC to prompt for URL and validate.

We could do this as a patch for the 3.3.0 release.

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by PhotoNomad0** [comment]
@birchamp @elsylambert OK need some suggestions on verbage.  Here are the screenshots:

**A.**
<img width="579" alt="Screen Shot 2022-08-08 at 9 45 44 PM" src="https://user-images.githubusercontent.com/14238574/183611370-ecd2210d-2339-4413-a498-8f1986d24b8c.png">

**B.**
<img width="797" alt="Screen Shot 2022-08-08 at 9 46 08 PM" src="https://user-images.githubusercontent.com/14238574/183611402-623b35d5-036b-4564-9d87-e33f3243c000.png">

**C.**
<img width="778" alt="Screen Shot 2022-08-08 at 9 47 51 PM" src="https://user-images.githubusercontent.com/14238574/183611425-d366e2ed-a1bf-4dcb-9141-2a1a252371ee.png">

**D.**
<img width="778" alt="Screen Shot 2022-08-08 at 9 47 51 PM" src="https://user-images.githubusercontent.com/14238574/183611443-655c2dd0-a73f-4235-a4f2-e4ecbb4283d9.png">

**E.**
<img width="263" alt="Screen Shot 2022-08-08 at 9 58 02 PM" src="https://user-images.githubusercontent.com/14238574/183611455-fedcb991-a989-4c2c-8ce5-28dda078b828.png">

**Comment by PhotoNomad0** [comment]
Replacement for B:

<img width="723" alt="Screen Shot 2022-08-09 at 10 46 48 AM" src="https://user-images.githubusercontent.com/14238574/183680181-40f07a04-a2d4-48b8-89d9-add555b2be83.png">

**Comment by PhotoNomad0** [comment]
**Added support for following URL formats:**
1. specific resource or project USFM file such as: `https://git.door43.org/<owner>/<repo>/raw/branch/master/02-EXO.usfm` or `https://git.door43.org/ayan.75/bn_bgst_1ti_book/raw/branch/master/bn_bgst_1ti_book.usfm`
2. general repo with book lookup from manifest: `https://git.door43.org/<owner>/<repo>`

If exact load of URL fails, then will try to extract URL of repo from the start of the URL such as in # 2 and then lookup using manifest.

**Comment by elsylambert** [comment]
A. Load Bible Resource (USFM)
B. Project: en_ult_1ti_book
    Enter Resource URL 
C. Loading Resource : {URL}
D. What is the difference between C and D?
E. View Resource URL

@birchamp Please update/edit my suggestions when you get a chance.

**Comment by PhotoNomad0** [comment]
> A. Load Bible Resource (USFM) B. Project: en_ult_1ti_book Enter Resource URL C. Loading Resource : {URL} D. What is the difference between C and D? E. View Resource URL
> 
> @birchamp Please update/edit my suggestions when you get a chance.

Oops, it looks like D was just a duplicate. @elsylambert

**Comment by PhotoNomad0** [comment]
> A. Load Bible Resource (USFM) B. Project: en_ult_1ti_book Enter Resource URL C. Loading Resource : {URL} D. What is the difference between C and D? E. View Resource URL
> 
> @birchamp Please update/edit my suggestions when you get a chance.

Oops, it looks like D was just a duplicate. @elsylambert

**Comment by PhotoNomad0** [comment]
**Note:**
@elsylambert and I discussed `E` and decided to just put back the language ID in place of the VIEWURL.

**Comment by PhotoNomad0** [comment]
@elsylambert Fix is in `translationCore 3.3.0 (421972d)`.  

There should be a separate issue(s) for next steps:
- improved support in SP including being able to add Bible URL from SP add pane
- fix issue that the remove resource menu item does not work on the URL Bible panes.
@birchamp

**Comment by elsylambert** [comment]
@PhotoNomad0 
A. I added the USFM for tit :https://git.door43.org/Es-419_gl/es-419_glt/raw/branch/master/57-TIT.usfm, it shows in a TIT project, but I am not able to remove the Resource from the Scripture Pane.

**Comment by elsylambert** [comment]
For your review: B. Console shows error that Locale is missing
<img width="1904" alt="Screen Shot 2022-08-15 at 1 46 07 PM" src="https://user-images.githubusercontent.com/51806180/184688325-31e74236-3752-42f3-a608-7ecf48409233.png">
.

**Comment by elsylambert** [comment]
C. I mistakenly was trying to load a Ruth USFM to a EST project. At first, it went fine but showed nothing in the SP. Then I tried again and it showed the following error:
<img width="1904" alt="Screen Shot 2022-08-15 at 1 40 36 PM" src="https://user-images.githubusercontent.com/51806180/184688883-ff374c2a-00a5-4354-8ea7-5970f6b041e0.png">

The error message is missing the text in {}.

**Comment by PhotoNomad0** [comment]
> @PhotoNomad0 A. I added the USFM for tit :https://git.door43.org/Es-419_gl/es-419_glt/raw/branch/master/57-TIT.usfm, it shows in a TIT project, but I am not able to remove the Resource from the Scripture Pane.

Yes, as stated above that is a known issue.  We need to create separate issue(s) for next steps:
- improved support in SP including being able to add Bible URL from SP add pane
- fix issue that the remove resource menu item does not work on the URL Bible panes.
    @birchamp

**Comment by PhotoNomad0** [comment]
> For your review: B. Console shows error that Locale is missing <img alt="Screen Shot 2022-08-15 at 1 46 07 PM" width="1904" src="https://user-images.githubusercontent.com/51806180/184688325-31e74236-3752-42f3-a608-7ecf48409233.png"> .

I've seen that before, but not able to reproduce that in the latest build.

**Comment by PhotoNomad0** [comment]
> C. I mistakenly was trying to load a Ruth USFM to a EST project. At first, it went fine but showed nothing in the SP. Then I tried again and it showed the following error: <img alt="Screen Shot 2022-08-15 at 1 40 36 PM" width="1904" src="https://user-images.githubusercontent.com/51806180/184688883-ff374c2a-00a5-4354-8ea7-5970f6b041e0.png">
> 
> The error message is missing the text in {}.

Yes, I see the broken error message.  I cannot reproduce the problem that it does not show an error the first time.

**Comment by PhotoNomad0** [comment]
Note:
testing with https://git.door43.org/Es-419_gl/es-419_glt/raw/branch/master/08-RUT.usfm

**Comment by PhotoNomad0** [comment]
> > C. I mistakenly was trying to load a Ruth USFM to a EST project. At first, it went fine but showed nothing in the SP. Then I tried again and it showed the following error: <img alt="Screen Shot 2022-08-15 at 1 40 36 PM" width="1904" src="https://user-images.githubusercontent.com/51806180/184688883-ff374c2a-00a5-4354-8ea7-5970f6b041e0.png">
> > The error message is missing the text in {}.
> 
> Yes, I see the broken error message. I cannot reproduce the problem that it does not show an error the first time.

OK, I saw that happen once, very strange... @elsylambert

**Comment by elsylambert** [comment]
translationCore 3.3.0 (df4a8a6). The issue C. is resolved. tC gives the correct error message when a different USFM(Book) is loaded into the a Project(different from the Manifest). User is able to delete the USFM Resource from the ADD Resource Modal. Remove Resource option is no longer available for the USFM Resource in Scripture Pane.

**Comment by elsylambert** [comment]
Wrote up #7403 for a minor UI issue with the Resource title in expanded scripture pane.
