### ISSUE TITLE
Blank tW screen when the project is opened for the first time after upgrade

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/translationCore#7376]
translationCore 3.3.0 (9e96976) .
After the upgrade to translationCore 3.3.0 (9e96976) , open the project: 
[fr_miss_tit_book.zip](https://github.com/unfoldingWord/translationCore/files/9199085/fr_miss_tit_book.zip)
  and selected en as gl for tW, it opened with a blank screen.
![blank screen-tw.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/03d4f28e-c370-4137-8835-e36d510ee1ae)

- Changed the GL to Hi and again it showed blank screen.
- Closed tC and reopened the project, it opened fine.
- LOG file: 
[Wed Jul 27 2022.zip](https://github.com/unfoldingWord/translationCore/files/9199074/Wed.Jul.27.2022.zip)

**Comment by PhotoNomad0** [comment]
@elsylambert - There is a problem with a missing manifest.json file in the ugnt.  There is a fix for the issue in translationCore 3.3.0 (b0ef8c5), but I recommend deleting the ugnt folder in the resources before installing.  Otherwise it will not get updated and the problem will remain.

**Comment by PhotoNomad0** [comment]
The broken resource is installed to ~/translationCore/resources/el-x-koine/bibles/ugnt/v0.22_Door43-Catalog

**Comment by elsylambert** [comment]
Not seeing this issue in translationCore 3.3.0 (b0ef8c5).
