### ISSUE TITLE
Show users that a resource is pre-release in updates dialog & SP

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#7391]
Issue:
---
Currently, once a user chooses to see pre-releases in the update dialog, those resources appear like any other resources, both in the update dialog and in the Scripture Pane.  Users need some indicator that they are working with a pre-release. 

DoD:
---
Update Identifiers to read like: [English - Door43] - Pre-release

Details:
---

- [x] Updates Dialog
- [x] Scripture pane add resources
- [x] Scripture pane title (hover text)
- [ ] Expanded Scripture pane (hover text)

**Comment by PhotoNomad0** [comment]
@elsylambert This is only part of the Epic.  Fix is in `translationCore 3.3.0 (421972d)`.  There is a separate issue for GL drop down on tools: https://github.com/unfoldingWord/translationCore/issues/7378

**Comment by PhotoNomad0** [comment]
@birchamp ^^^

**Comment by elsylambert** [comment]
<img width="784" alt="Screen Shot 2022-08-15 at 9 00 13 AM" src="https://user-images.githubusercontent.com/51806180/184695000-653b2616-90f4-4f28-b369-86fea91efa52.png">

**Comment by elsylambert** [comment]
Looks good in translationCore 3.3.0 (df4a8a6). The Pre-released resources shows in [] and Pre-Release title, in 1. Content Update dialogue
<img width="794" alt="Screen Shot 2022-08-16 at 8 46 55 AM" src="https://user-images.githubusercontent.com/51806180/184885034-f04bc5e4-1bec-4cfc-87bf-d7d2350483e2.png">

 2. Scripture Pane Add Resource
 
<img width="991" alt="Screen Shot 2022-08-16 at 8 53 24 AM" src="https://user-images.githubusercontent.com/51806180/184885136-7e2880e7-2467-4881-831c-9e4d210326d0.png">

 3. Scripture Pane hover text.
<img width="235" alt="Screen Shot 2022-08-16 at 8 53 58 AM" src="https://user-images.githubusercontent.com/51806180/184885173-cfcbf3f7-dc30-4fcb-a664-eee4426a9198.png">

**Comment by elsylambert** [comment]
Wrote up #7404 for the Expanded Scripture Pane part of this issue.

**Comment by elsylambert** [comment]
Something got messed up in translationCore 3.3.0 (fb96f72). Pre-Release title shows "Missing translation key" for Scripture Pane and Add scripture Resource drop down.
<img width="1437" alt="Screen Shot 2022-08-18 at 10 31 25 AM" src="https://user-images.githubusercontent.com/51806180/185421973-df25fb35-10eb-4a0c-9476-fb568657d8e6.png">
<img width="1321" alt="Screen Shot 2022-08-18 at 10 36 07 AM" src="https://user-images.githubusercontent.com/51806180/185422134-9d984bb7-d4a4-41c3-85a6-270d848ac3f8.png">

**Comment by PhotoNomad0** [comment]
@elsylambert found a typo, the locale key should have been pre_release, not pre-release.  Fix is in translationCore 3.3.0 (ce8ec7b)

**Comment by elsylambert** [comment]
Looks good in translationCore 3.3.0 (ce8ec7b).
