### ISSUE TITLE
Cannot see French helps in tN and tW

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#7399]
### User Story

Seems to be a bug in tCore that it is showing the English tHelps and not the French tHelps in the tN and tW tools even though they are seen as translated in GWE.

Using the MVHS org for testing here.

For example in GWE French is shown:

![Screen Shot 2022-08-15 at 10 04 57 AM](https://user-images.githubusercontent.com/14238574/184651752-ab4558cb-b70f-4ab0-a837-aafd84902b1f.png)

But in tCore we see English:

![Screen Shot 2022-08-15 at 10 07 54 AM](https://user-images.githubusercontent.com/14238574/184651857-6f352ca0-1b71-4ddc-8839-c37a7d18f23d.png)

Note: seems to be an issue that the tHelps are looking for resources in D43-Catalog only.

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by PhotoNomad0** [comment]
@elsylambert Fixed in translationCore 3.3.0 (25e1d62) Using the MVHS org for testing.

**Comment by elsylambert** [comment]
Looks good in translationCore 3.3.0 (df4a8a6). Able to see tA helps articles in tW and tN in French using MVHS org.
