### ISSUE TITLE
USFM Resource title in the Expanded Scripture Pane 

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/translationCore#7403]
When the Scripture Pane is expanded, it shows ViewURL in the title, which is not a clickable link.![Screen Shot 2022-08-16 at 8.33.38 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/48e9e903-1ad7-40b1-928a-4a1e83a9aefa)

**Comment by PhotoNomad0** [comment]
@elsylambert Have fix in translationCore 3.3.0 (fb96f72) 

![Screen Shot 2022-08-16 at 11 34 52 AM](https://user-images.githubusercontent.com/14238574/184920439-da6bca46-0fee-4c60-9493-25045e6d1050.png)

**Comment by PhotoNomad0** [comment]
@elsylambert Found this quirk where it is not breaking a line.  Maybe create an issue and see if @birchamp wants to hold the release for this.

<img width="618" alt="Screen Shot 2022-08-16 at 2 00 11 PM" src="https://user-images.githubusercontent.com/14238574/184947985-3369ceda-dfb2-4419-a3e0-b6ddce1bc241.png">

**Comment by birchamp** [comment]
Yeah, we don't need to hold the release.  I think we should fix this with hover instead of taking up screen space with wrapping.  But it isn't worth holding the feature until that's implemented.

**Comment by PhotoNomad0** [comment]
It looks that to fix requires setting  the 'overflow-wrap' in CSS

**Comment by elsylambert** [comment]
Looks good in translationCore 3.3.0 (fb96f72). Expanded Scripture pane shows the URL with a scroll bar in the title.
<img width="982" alt="Screen Shot 2022-08-17 at 9 05 20 AM" src="https://user-images.githubusercontent.com/51806180/185142792-7f4e6d24-6c03-4dfd-ad07-150f5e01eeb0.png">

**Comment by PhotoNomad0** [comment]
This should be working now in latest 3.3.0
