### ISSUE TITLE
Show users that a resource is pre-release in Expanded Scripture Pane

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/translationCore#7404]
This is separated from #7391 , The Expanded scripture does not show the title for Pre-releases resources.
 ![Screen Shot 2022-08-16 at 8.59.43 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/ee2a17da-a03d-4ef1-b817-f9e04e580a81)

**Comment by PhotoNomad0** [comment]
@elsylambert I also notice that orgs are not shown here.

**Comment by PhotoNomad0** [comment]
@elsylambert I don't know that we ever implemented hover on the titles here.

**Comment by elsylambert** [comment]
@PhotoNomad0 You are right!!! It is just the Title. I copied the details from #7391, where it was mentioned: Expanded Scripture Pane Title(Hover Text).

**Comment by PhotoNomad0** [comment]
@elsylambert Have fix in translationCore 3.3.0 (fb96f72) 

![Screen Shot 2022-08-16 at 11 34 52 AM](https://user-images.githubusercontent.com/14238574/184920439-da6bca46-0fee-4c60-9493-25045e6d1050.png)

**Comment by elsylambert** [comment]
Looks good in translationCore 3.3.0 (fb96f72). Expanded Scripture pane shows Pre-release in the title.
<img width="982" alt="Screen Shot 2022-08-17 at 9 05 20 AM" src="https://user-images.githubusercontent.com/51806180/185142223-daa1478b-6d8c-45e1-bc0a-d0156a56c213.png">
