### ISSUE TITLE
Problem with adding scripture panes after upgrade.

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#7414]
### User Story

After upgrading from older version of translationCore, can have problem adding scripture panes in the translationNotes and translationWords tools (not all downloaded bibles are shown).  The work around is to switch to wordAlignment tool and add scripture panes in that tool.  Then when you switch back to translationNotes or translationWords tools you will also see the added scripture panes. 

![image](https://user-images.githubusercontent.com/14238574/188119256-d6f7ffe1-a5f1-40ee-9d4f-ec857c25548b.png)

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by PhotoNomad0** [comment]
@elsylambert the fix is in translationCore 3.3.1 (7a369ef)

**Comment by elsylambert** [comment]
Works fine in translationCore 3.4.0 (7871560). Not seeing the problem.
