### ISSUE TITLE
Warn user when they try to open the wA tool with an older version of the original language than was last used.

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#7417]
### User Story

Warn user when they try to open the wA tool with an older version of the ugnt than was last used.  And direct the user to upgrade to that version.

This issue came from the field.  alignments were being lost and work had to be redone.
Made a fork of original repo https://git.door43.org/Mukesh_Parte/mr_mgst_jhn_book :

https://git.door43.org/tCore-test-data/mr_mgst_jhn_book
Also made repos with snapshots of contents at specific upload dates:
- 8/5/2022 - https://git.door43.org/tCore-test-data/mr_mgsa_jhn_book
- 8/23/2022 - https://git.door43.org/tCore-test-data/mr_mgsb_jhn_book
- 8/24/2022 - https://git.door43.org/tCore-test-data/mr_mgsc_jhn_book

Found another repo: https://git.door43.org/sunilkasbe/mr_mgst_jhn_book that I forked to: 
- https://git.door43.org/tCore-test-data/mr_mgsy_jhn_book

Russ's recommendation on the fix:
 
Thanks for digging into this and figuring out what happened. I agree with Birch that something like:
- warning the user and NOT allowing them to open the project and break the data, but instead guiding them to update the UGNT before they can open the project, sounds like a reasonable solution.
 
But:
- Giving them a warning that they can ignore, and allowing them to open the project and break the data, does NOT sound like a good option. 

### Features / Specifications

- [ ]

### Definition of Done

- [ ]

## Additional Context

Here is the timeline of git history:
7/20 - sachin_nerlekar started with tc 3.0.1
7/20 - sunilkasbe started with  tc 3.0.1 and ugnt v0.14
7/21 - sunilkasbe updated to tC 3.2.0 and ugnt v0.24
working on tn, and a few wa fixes
7/28 - sunilkasbe updated to ugnt v0.26
7/28 - 7/29 - continued working on tn
7/29 - 8/3 - started working on tw
8/3 - 8/5 - continued working on tn
8/5 - sunilkasbe uploaded to D43
8/5 - Mukesh_Parte started working with  tC 3.2.0 and ugnt v0.24 (this is going to an older version of ugnt)
8/5 - started doing word alignment starting with chapter 1 and making fixes to tw
8/23 - Mukesh_Parte uploaded to D43
8/24 - Mukesh_Parte uploaded to D43 <= problem reported on this date
* 8/24+ - see wa alignment fixes not in consecutive order (mostly in chapters 11-19, but a few fixes in earlier chapters)
9/6 - Mukesh_Parte final upload to D43, still at ugnt v0.24

**Comment by PhotoNomad0** [comment]
@elsylambert @birchamp -  It looks like we will have to show the warning immediately when they try to open the project.  The reason is that there is a performance optimization that the tools are initialized immediately when the project is opened, so the wA tool will start checking for invalidations in the background before the wA tool is even opened.  So we have to block opening the project until they have updated the ugnt (or hbo) to match or exceed the version in the project manifest.

**Comment by PhotoNomad0** [comment]
Notes:
- add check in openProject()
- move the dispatch(closeAlertDialog()) from bottom of method.
- call dispatch(downloadMissingResource())

**Comment by PhotoNomad0** [comment]
To test:
- start tCore, and click get started button.
- before opening up a project, delete the contents of `~/translationCore/resources/el-x-koine/bibles/ugnt`
- Then open a new testament project and should see this warning:

![Screen Shot 2022-09-15 at 12 04 52 PM](https://user-images.githubusercontent.com/14238574/190468505-cfcbbb0b-b3bf-45ec-8642-c71ce90389d9.png)

- Click update to version button and then will get confirmation to connect to internet.  
- click Access Internet.
- when download completes, click OK
- now should be able to open the project.

**Comment by PhotoNomad0** [comment]
@birchamp @elsylambert - is this verbage in the screenshot above ^^^ sufficient for the issue?

**Comment by PhotoNomad0** [comment]
@elsylambert This is implemented in the latest tCore develop build 3.4.0 [984c28c].  See the notes above for a way to test.

**Comment by elsylambert** [comment]
@PhotoNomad0  got this error when I tried to open a PHP project after deleting the contents of ugnt folder.
<img width="1782" alt="Screen Shot 2022-09-16 at 9 05 00 AM" src="https://user-images.githubusercontent.com/51806180/190645526-0cbf9c7a-b4ce-4be3-a43a-aa59c78b6552.png">
Log file:[Fri Sep 16 2022.log.zip](https://github.com/unfoldingWord/translationCore/files/9584237/Fri.Sep.16.2022.log.zip)

Project: 
[en_ulb_php_book.zip](https://github.com/unfoldingWord/translationCore/files/9584239/en_ulb_php_book.zip)

**Comment by PhotoNomad0** [comment]
Newer test instructions:

- On clean tCore startup you should see these bible versions in ugnt:

<img width="945" alt="Screen Shot 2022-09-16 at 7 54 50 PM" src="https://user-images.githubusercontent.com/14238574/190831827-6f330f4f-f0b3-46af-b5fd-63ae136e75d2.png">

- to test the upgrade delete the folder `v0.22_Door43-Catalog`.  Then rename the `v0.29_Door43-Catalog` to `v0_Door43-Catalog`

- On clean tCore startup you should see these bible versions in uhb:

<img width="636" alt="Screen Shot 2022-09-16 at 7 56 41 PM" src="https://user-images.githubusercontent.com/14238574/190831828-3a22bed2-4e9d-41c2-8b4a-3c8f8208d540.png">

- to test the upgrade delete the folder `v2.1.23_Door43-Catalog`.  Then rename the `v2.1.29_Door43-Catalog` to `v0_Door43-Catalog`

**Comment by PhotoNomad0** [comment]
@elsylambert - have a new build translationCore 3.4.0 (279bc52) for testing.  Also see the updated test steps above. ^^^

**Comment by elsylambert** [comment]
Works fine in translationCore 3.4.0 (7871560). Tested with a NT and an OT project. Seeing the alert to update to the version of the aligned resource for ugnt and uhb. Works as expected.
