### ISSUE TITLE
Address Selection Bugs

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#742]
- [x] selecting outside of area
- [x] overlapping new selection over old selection
- [x] concatenate contiguous selections
- [x] selecting words before any current selection highlights something random afterwards
- [x] selecting range that starts at 1 always attaches 0
- [x] selecting multiple occurrences of a word sometimes doesn't work.
- [x] selecting a word that has multiple occurrences sometimes highlights the wrong word occurrence.

**Comment by klappy** [comment]
Blocked on #741

**Comment by mannycolon** [comment]
@klappy I added to this list a few bugs that I encounter using text selection

**Comment by klappy** [comment]
@mannycolon: Can you help share steps to recreate these issues?
If I can recreate them, I can try to fix those tonight.

**Comment by klappy** [comment]
Addressed most issues with PR https://github.com/translationCoreApps/translationWords_Check_plugin/pull/41
