### ISSUE TITLE
Content Updates window is not opening

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/translationCore#7424]
Version 3.4.0 (7871560)
Go to Actions> Check for content updates>Click>Nothing happens on the screen.
Note the errors on the console:
![Screen Shot 2022-09-20 at 2.49.24 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/8dfe7e27-6b19-493f-8fe6-6484ee9037b1)

When we are inside a tool or on tools page, the Actions button disappears from the screen after Check for Content update option was selected.
![Screen Shot 2022-09-20 at 2.48.13 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/c5253a56-42ac-46fc-b2d1-5622c61dd911)
Log file: 
[Tue Sep 20 2022.log.zip](https://github.com/unfoldingWord/translationCore/files/9610545/Tue.Sep.20.2022.log.zip)

**Comment by elsylambert** [comment]
@PhotoNomad0 Unable to do the content update.

**Comment by PhotoNomad0** [comment]
@elsylambert @birchamp This is a very strange compile bug.  In two functions I reverted to an alternate format for declaring them.  But the strange part is that this file I touched was unchanged from 3.3.0 release in which it worked.  There have been only minimal changes from 3.3.0, and nothing that should have impacted the linking of files.  I also see this problem on local builds also.  Waiting for a build to make sure it is fixed there also.

**Comment by PhotoNomad0** [comment]
PS - Very thankful for @elsylambert test scripts to quickly catch this

**Comment by PhotoNomad0** [comment]
@elsylambert - this is now working in translationCore 3.4.0 (551be4e).  Note that there are now twice as many build artifacts now.  We now have some minimal builds tagged with LITE.  You should probably leave those alone for now.

**Comment by elsylambert** [comment]
Not seeing the problem in translationCore 3.4.0 (551be4e). Able to download content updates successfully.
