### ISSUE TITLE
Abstract function for sending selection

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#743]
```
function textSelection(text, occurrence, occurrences) {
// do something
// choose to use append or remove
} 
```

**Comment by RoyalSix** [comment]
@mannycolon you are using this correct? 
`"selectedText": [
        {
          "text": "യേശു",
          "occurrence": 0,
          "occurrences": 1
        },
        {
          "text": "നിന്നു നിന്നു",
          "occurrence": 1,
          "occurrences": 2
        }
      ]`
