### ISSUE TITLE
tW articles are not opening in tN

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/translationCore#7436]
tW articles do not show up when tW links in the smurf bar is clicked, it opens a blank screen like this:
![Screen Shot 2022-10-03 at 10.23.42 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/733e3ec7-d952-4ddf-aac1-b182b4597d8f)

**Comment by PhotoNomad0** [comment]
@elsylambert - ther is a fix for this in translationCore 3.4.0 (e1f61af)

**Comment by elsylambert** [comment]
Issue is resolved in translationCore 3.4.0 (5b601bd). TW articles are now opening in TN.
