### ISSUE TITLE
Update tCore to recent Electronite.

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#7443]
### User Story

Update tCore from Electronite v17 to recent v19.1.3.

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by PhotoNomad0** [comment]
This issue is resolved in translationCore 3.4.1 (92397fd).  tCore functionality should be the same as in 3.4.0.

**Comment by elsylambert** [comment]
Not seeing any problems in the latest Electronite build. Verified in translationCore 3.4.0-QA (d482d09).
