### ISSUE TITLE
Add Print Preview and Pdf generation to tCore.

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#7456]
### User Story

As a [type of user], I want [some goal] so that [some reason].

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by PhotoNomad0** [comment]
Adding this to QA server build as per suggestion from Birch

**Comment by PhotoNomad0** [comment]
@elsylambert The first pass of Printing is in translationCore 3.4.0-QA (d482d09).  This will add a new menu item to each project:

<img width="580" alt="Screenshot 2022-12-08 at 6 48 19 PM" src="https://user-images.githubusercontent.com/14238574/206590900-c31510ba-b5bd-442c-8b5c-64c84f2eb394.png">

Clicking on the item will pop up a print preview window:

<img width="849" alt="Screenshot 2022-12-08 at 6 50 03 PM" src="https://user-images.githubusercontent.com/14238574/206591024-365d8c38-fcb1-445a-a453-444d6bfdab7e.png">

beneath the preview will be a new dialog where you can adjust the size of the fonts,the detail of the preview, and save to PDF file:

<img width="780" alt="Screenshot 2022-12-08 at 6 50 16 PM" src="https://user-images.githubusercontent.com/14238574/206591227-000c4eae-b7af-462a-b065-9a5e0b35d1ab.png">

**Comment by elsylambert** [comment]
Tested in translationCore 3.4.0-QA (d482d09). Print Preview looks good and works fine. Changing font size and Preview scale works fine. Print to PDF downloads the pdf to local download folder and the pdf looks good.
