### ISSUE TITLE
When there are attribute changes in the Original Language, migrate the new attribute values into wA aligned data.

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#7465]
Note:
- attributes that should be updated automatically are morph, lemma, strongs

**Comment by PhotoNomad0** [comment]
Notes:

- some of the Greek changes seen that are difficult to map are:
  - capitalization changes - these could mess up occurrence counts.
  - greek accents such as in `κατ’` where `2019     ’     RIGHT SINGLE QUOTATION MARK` was replaced with ` 02BC     ʼ     MODIFIER LETTER APOSTROPHE` 

- there is also leftover alignments in projects with no bottom words - likely ignored by WA tool.

**Comment by PhotoNomad0** [comment]
To Do:

- [x] handle missing verses
- [x] handle verse spans
- [x] handle empty alignments

**Comment by PhotoNomad0** [comment]
@elsylambert - latest build  translationCore 3.4.1 (17ff357) has this update:

Test by enabling pre-release and then selecting for download:

<img width="785" alt="Screenshot 2023-01-06 at 7 48 50 PM" src="https://user-images.githubusercontent.com/14238574/211172406-bacd8d7a-76f6-42b5-825d-20c4730a6acd.png">

and then for en:

<img width="784" alt="Screenshot 2023-01-06 at 7 49 23 PM" src="https://user-images.githubusercontent.com/14238574/211172428-e296cb72-9549-40c6-99ca-51c35348230b.png">

Then open a Titus project (such as https://git.door43.org/unfoldingWord/en_ult/raw/branch/master/57-TIT.usfm) and for WA GL then en unfoldingWord

<img width="594" alt="Screenshot 2023-01-06 at 7 59 12 PM" src="https://user-images.githubusercontent.com/14238574/211172937-53c82bb5-7a66-4b4c-aeda-3a883a0b7c8f.png">

Launch WA and for 1:15 click on `καθαρὰ` (second word of verse) in the alignment area the morph string should show:

<img width="979" alt="Screenshot 2023-01-06 at 8 01 09 PM" src="https://user-images.githubusercontent.com/14238574/211172987-dd219aef-fee4-4b56-a960-cf7be033fbb9.png">

**Comment by elsylambert** [comment]
Looks good and works as expected(as per the test instructions above^^) in translationCore 3.4.1 (https://github.com/unfoldingWord/translationCore/commit/5ed21f7da0dccdf7118bcf66129942ff68e92762) .
