### ISSUE TITLE
When user changes GLs, make sure the Original Language (e.g. the UGNT) version is immediately updated in wA tool.

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#7466]

**Comment by PhotoNomad0** [comment]
Notes: translationCore 3.4.1 (17ff357)

**Comment by PhotoNomad0** [comment]
@elsylambert - latest build  translationCore 3.4.1 (17ff357) has this update:

Test by enabling pre-release and then selecting for download:

<img width="785" alt="Screenshot 2023-01-06 at 7 48 50 PM" src="https://user-images.githubusercontent.com/14238574/211172406-bacd8d7a-76f6-42b5-825d-20c4730a6acd.png">

and then for en:

<img width="784" alt="Screenshot 2023-01-06 at 7 49 23 PM" src="https://user-images.githubusercontent.com/14238574/211172428-e296cb72-9549-40c6-99ca-51c35348230b.png">

Then open a fully aligned Titus project (such as https://git.door43.org/unfoldingWord/en_ult/raw/branch/master/57-TIT.usfm) and for WA GL select en door43:

<img width="615" alt="Screenshot 2023-01-06 at 7 53 49 PM" src="https://user-images.githubusercontent.com/14238574/211172491-04c639dd-ea1d-4645-8e1d-1573e039f4bc.png">

Launch WA tool and for 3:15 should see the first Greek word should be lower case:

<img width="909" alt="Screenshot 2023-01-06 at 7 54 36 PM" src="https://user-images.githubusercontent.com/14238574/211172829-a0e26691-727c-4feb-909d-80e1bbe02a95.png">

Also all the verses should be aligned - or make it so.

And then go back to tools page and select for WA GL then select en unfoldingWord

<img width="594" alt="Screenshot 2023-01-06 at 7 59 12 PM" src="https://user-images.githubusercontent.com/14238574/211172937-53c82bb5-7a66-4b4c-aeda-3a883a0b7c8f.png">

Launch WA and should see first word of Greek should be upper case in Scripture pane and alignment area:

<img width="979" alt="Screenshot 2023-01-06 at 8 01 09 PM" src="https://user-images.githubusercontent.com/14238574/211172987-dd219aef-fee4-4b56-a960-cf7be033fbb9.png">

also verify that the scripture pane is showing pre-release:

<img width="913" alt="Screenshot 2023-01-06 at 8 06 08 PM" src="https://user-images.githubusercontent.com/14238574/211173021-94331264-41df-4c26-b76e-f6ebae425818.png">

**Comment by elsylambert** [comment]
Verified in translationCore 3.4.1 (5ed21f7). When GL is changed , the Original Language version was also changed. 
Thanks @PhotoNomad0 for detailed test instructions.
