### ISSUE TITLE
Add support for x-strong attribute in USFM

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#7467]

**Comment by PhotoNomad0** [comment]
@elsylambert - latest build  translationCore 3.4.1 (17ff357) has this update:

Test by enabling pre-release and then selecting for download:

<img width="785" alt="Screenshot 2023-01-06 at 7 48 50 PM" src="https://user-images.githubusercontent.com/14238574/211172406-bacd8d7a-76f6-42b5-825d-20c4730a6acd.png">

and then for en:

<img width="784" alt="Screenshot 2023-01-06 at 7 49 23 PM" src="https://user-images.githubusercontent.com/14238574/211172428-e296cb72-9549-40c6-99ca-51c35348230b.png">

Then open a Titus project (such as https://git.door43.org/unfoldingWord/en_ult/raw/branch/master/57-TIT.usfm) and for WA GL then en unfoldingWord

<img width="594" alt="Screenshot 2023-01-06 at 7 59 12 PM" src="https://user-images.githubusercontent.com/14238574/211172937-53c82bb5-7a66-4b4c-aeda-3a883a0b7c8f.png">

Launch WA and for 1:15 click on all the words in the alignment area and make sure non of the strongs numbers are empty:

<img width="979" alt="Screenshot 2023-01-06 at 8 01 09 PM" src="https://user-images.githubusercontent.com/14238574/211172987-dd219aef-fee4-4b56-a960-cf7be033fbb9.png">

**Comment by elsylambert** [comment]
Looks good and works as expected(as per the test instructions above^^) in translationCore 3.4.1 (https://github.com/unfoldingWord/translationCore/commit/5ed21f7da0dccdf7118bcf66129942ff68e92762) . All Original words have strong numbers.
