### ISSUE TITLE
Add support for the new morph string format and keys (all handled in tc-ui-toolkit)

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#7468]

**Comment by PhotoNomad0** [comment]
Notes:

1.  conversion of greek morph strings to human readable  is handled in MorphUtils.getMorphLocalizationKeysGreek() in word-aligner which uses a tree (morphCodeLocalizationMapGrk) to interpret the fields
  - current morph strings are in format:  `"morph": "Gr,N,,,,,GMS,"` (13 characters)
  - new morph strings are like:                 `"morph": "Gr,N,....NMS"` (12 characters dropping the type)
  - in morphCodeLocalizationMapGrk it looks we
    - remove the type nested in role (2)
    - and all the fields from mood are decremented by 1 (e.g. mood goes from 4 to 3)

**Comment by PhotoNomad0** [comment]
@elsylambert - latest build  translationCore 3.4.1 (17ff357) has this update:

Test by enabling pre-release and then selecting for download:

<img width="785" alt="Screenshot 2023-01-06 at 7 48 50 PM" src="https://user-images.githubusercontent.com/14238574/211172406-bacd8d7a-76f6-42b5-825d-20c4730a6acd.png">

and then for en:

<img width="784" alt="Screenshot 2023-01-06 at 7 49 23 PM" src="https://user-images.githubusercontent.com/14238574/211172428-e296cb72-9549-40c6-99ca-51c35348230b.png">

Then open a Titus project (such as https://git.door43.org/unfoldingWord/en_ult/raw/branch/master/57-TIT.usfm) and for WA GL then en unfoldingWord

<img width="594" alt="Screenshot 2023-01-06 at 7 59 12 PM" src="https://user-images.githubusercontent.com/14238574/211172937-53c82bb5-7a66-4b4c-aeda-3a883a0b7c8f.png">

Launch WA and for 1:15 click on `καθαρὰ` (second word of verse) for both alignment area and in scripture pane the morph string should show:

<img width="979" alt="Screenshot 2023-01-06 at 8 01 09 PM" src="https://user-images.githubusercontent.com/14238574/211172987-dd219aef-fee4-4b56-a960-cf7be033fbb9.png">

**Comment by elsylambert** [comment]
Looks good and works as expected(as per the test instructions above^^) in translationCore 3.4.1 (5ed21f7) .

**Comment by PhotoNomad0** [comment]
@elsylambert A new fix is in develop build translationCore 3.4.1 (f9a156c)

Testing fix for particle support:

Need to get latest pre-release of unfoldingword ugnt.

open a 1 Cor project . Scroll down to WA tool and select unfoldingword en as gateway language
launch wa and in 1:13, should see:

![Screenshot 2023-02-01 at 2 42 56 PM](https://user-images.githubusercontent.com/14238574/216430667-19d4a5e3-c043-487d-8ca0-c1f5d7d50c97.png)

**Comment by elsylambert** [comment]
Looks good in translationCore 3.5.0 (84d05fd). 
<img width="1407" alt="Screenshot 2023-02-03 at 8 56 33 AM" src="https://user-images.githubusercontent.com/51806180/216621333-33561de3-d4c7-4fe9-a818-b0c49cc5bf25.png">
