### ISSUE TITLE
On change of original language in WA tool, do automatic alignment mapping for capitalization changes and accent fixes/normalization.

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#7471]
Some of the SR Greek changes seen that break alignments and could be automatically handled are:
- capitalization changes - these could mess up occurrence counts.
- Greek accents such as in `κατ’` where `2019     ’     RIGHT SINGLE QUOTATION MARK` was replaced with `02BC     ʼ     MODIFIER LETTER APOSTROPHE`

**Comment by PhotoNomad0** [comment]
**Notes:**

- do exact compare first and if not exact match fall back to doing inexact compare:
  - When comparing original words:
     - could do Unicode normalization and toLowerCase() before comparison or with word count (about 85% of mismatches)
     - replace trailing `RIGHT SINGLE QUOTATION MARK` with `MODIFIER LETTER APOSTROPHE` (about 10% of mismatches)

- replacing other changes probably have too much risk unless there is a way to force manual review.

scripture-resource-rcl calls tokenize from string-punctuation-tokenizer this for normalization:
```
  return tokenize({
    text: text,
    greedy: true,
    normalize: true,
  });
```

which in turn calls `normalizer(string);` from string-punctuation-tokenizer

**Comment by PhotoNomad0** [comment]
Notes:

https://git.door43.org/photonomad1/en_migr_tit_book (should be fully aligned with no invalidations)

when you change GL to en unfoldingWord, all the capitalization changes and punctuation fixes should be migrated automatically.

So After migration should only see invalidations on these three verses:

One of the two `καὶ` was removed:
![Screenshot 2023-01-10 at 9 51 21 AM](https://user-images.githubusercontent.com/14238574/211584499-4043a266-59dc-4a43-b436-36fc25a3a0dd.png)

Word change:
![Screenshot 2023-01-10 at 9 51 40 AM](https://user-images.githubusercontent.com/14238574/211585746-ce1d0ff0-d6af-4f91-8c32-74fec301b518.png)

Word change:
![Screenshot 2023-01-10 at 9 52 06 AM](https://user-images.githubusercontent.com/14238574/211585235-175b2b23-aa76-4687-84b3-3f2d154e5968.png)

**Comment by PhotoNomad0** [comment]
@elsylambert 

Fix is in translationCore 3.4.1 (5ed21f7) 

Test by enabling pre-release and then selecting for download:

<img width="785" alt="Screenshot 2023-01-06 at 7 48 50 PM" src="https://user-images.githubusercontent.com/14238574/211172406-bacd8d7a-76f6-42b5-825d-20c4730a6acd.png">

and then for en:

<img width="784" alt="Screenshot 2023-01-06 at 7 49 23 PM" src="https://user-images.githubusercontent.com/14238574/211172428-e296cb72-9549-40c6-99ca-51c35348230b.png">

Start with a fully aligned titus book https://git.door43.org/photonomad1/en_migr_tit_book (should already have WA GL of en door43-catalog selected, and should be fully aligned with no invalidations)

when you change GL to en unfoldingWord, all the capitalization changes and punctuation fixes should be migrated automatically.

Launch WA and after migration should only see invalidations on these three verses:

One of the two `καὶ` was removed:
![Screenshot 2023-01-10 at 9 51 21 AM](https://user-images.githubusercontent.com/14238574/211584499-4043a266-59dc-4a43-b436-36fc25a3a0dd.png)

Word change:
![Screenshot 2023-01-10 at 9 51 40 AM](https://user-images.githubusercontent.com/14238574/211585746-ce1d0ff0-d6af-4f91-8c32-74fec301b518.png)

Word change:
![Screenshot 2023-01-10 at 9 52 06 AM](https://user-images.githubusercontent.com/14238574/211585235-175b2b23-aa76-4687-84b3-3f2d154e5968.png)

Then change GL back to en door43-catalog and launch WA again - should only see invalidations on the same three verses.

**Comment by elsylambert** [comment]
Looks good and works as expected(as per the test instructions above^^) in translationCore 3.4.1 (https://github.com/unfoldingWord/translationCore/commit/5ed21f7da0dccdf7118bcf66129942ff68e92762) . 
In the last step when we change GL back to en door-43 catalog and launch WA again, I see invalidations on the same three verses.

**Comment by PhotoNomad0** [comment]
Note:

The other changes were:
- in tit 1:10 removed first instance of`καὶ`
- in tit 2:4 changed `σωφρονίζωσι` to `σωφρονίζουσιν`
- tit 3:15 `παλινγενεσίας` to `παλιγγενεσίας`
