### ISSUE TITLE
On first time project is opened, update alignment data if they have not already been updated.

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#7474]
One particular use case is after downloading a project, update the alignment data if it has not been updated to the latest original language version - even if you don't change the GL.

**Comment by PhotoNomad0** [comment]
@elsylambert this is now working in translationCore 3.4.1 (06cf68c)

May not see a lot of difference, but when you open a project and if:
- if there is already a GL selected for WA, then alignments should be migrated when the project is opened.  And there will be an entry `tc_orig_lang_wordAlignment` added to the project manifest.
- if there is no GL selected for WA, then when you select a GL the alignments will be migrated.  And there will be an entry `tc_orig_lang_wordAlignment` added to the project manifest.

**Comment by elsylambert** [comment]
Looks good in translationCore 3.4.1 (06cf68c). Seeing the entries in Project manifest. Also the alignments were migrated when GL is selected.
