### ISSUE TITLE
Highlighting broken with Ampersand in tNotes original quotes

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#7490]
### User Story

Highlighting broken with Ampersand in tNotes original quotes when there is a verse span.

@abelpz found this while testing a verse range combined with an original language quote that contained an ampersand.

To see this in tCore, download the pre-release of en_ult and en_tn in es-419_lab org.  Open a php project in tCore.  And for tNotes select the GL of es-419_lab/en_tn.  Launch tNotes and look in `abstract-nouns`.  The highlighting is greedy:

<img width="1187" alt="Screenshot 2023-03-27 at 6 47 54 AM" src="https://user-images.githubusercontent.com/14238574/227927760-8aaef630-da41-4787-9fe2-bdf66bab6291.png">

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by PhotoNomad0** [comment]
@birchamp @elsylambert - The first step here is to do a refactor: https://github.com/unfoldingWord/translationCore/issues/7492.  Later we can use the shared code in all the apps so we have consistent highlighting.  And then we can fix this greedy highlighting behavior in all apps at the same time.

**Comment by PhotoNomad0** [comment]
@elsylambert It seems this was fixed sometime ago.  Is this still a problem?

**Comment by elsylambert** [comment]
Verified in translationCore 3.6.7 (3ccbde3). Highlighting work fine when there is ampersand in the Original quote.
<img width="1512" alt="Screenshot 2024-12-16 at 10 10 34 PM" src="https://github.com/user-attachments/assets/139a47cc-a360-4104-a9c7-99e0f43d68e4" />
