### ISSUE TITLE
Refactor tc-source-content-updator to move reusable code into tsv-group-data-parser

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#7492]
## Summary

Refactor tc-source-content-updator to move reusable code into tsv-group-data-parser - this is preliminary work in order to make a reusable highlighting library that can be shared among all our apps.

**Comment by PhotoNomad0** [comment]
@elsylambert Nothing specific to test here - just a refactor here so that we can have shared highlighting code for all apps.  There is no new behavior here, but his should not break anything in the 3.5.0 release.

**Comment by PhotoNomad0** [comment]
@birchamp this refactor was the first step in making a reusable GL quote module.

**Comment by birchamp** [comment]
@PhotoNomad0 great to hear!
