### ISSUE TITLE
Pivot the Translation Notes sidebar navigation

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/translationCore#7502]
## Summary
In the translationNotes tool, add a menu item to the filter dropdown to allow users to pivot the index in the left bar to sort order where the parents are the chapter:verse numbers and the nodes are the figures of speech. 

## Motivation
Users want to navigate their work verse by verse after they have done all the checks.

## Specifications (If applicable)
DoD: Users can switch the sort order of the notes to have verse numbers be the primary index.

## Additional context

![CleanShot 2023-06-23 at 13 27 01](https://github.com/unfoldingWord/translationCore/assets/10272744/76a673e9-5894-4429-af24-c2737791475d)

**Comment by PhotoNomad0** [comment]
@birchamp - I have a prototype working.  Here is a screenshot for feedback.  The toggle is the actions menu.  At moment it is not a check button, but a button that shows the option that you would switch to.  Do you want an icon?  Or should we make it a checkbox? or?  Also on the group menu it is currently showing the original quote on the check.  I should fix that to show the selected text after the category. @elsylambert @danielklapp 

<img width="1440" alt="Screenshot 2023-06-30 at 8 15 14 AM" src="https://github.com/unfoldingWord/translationCore/assets/14238574/3fa469bb-7b55-4acb-b8a7-973265ae064e">

**Comment by birchamp** [comment]
@PhotoNomad0 This looks good. The toggle should be under the filter menu in the upper left.

**Comment by PhotoNomad0** [comment]
@elsylambert @danielklapp This is in translationCore 3.5.0 (4508628): 

<img width="663" alt="Screenshot 2023-07-03 at 11 29 49 AM" src="https://github.com/unfoldingWord/translationCore/assets/14238574/dfd2c77c-62c1-4b5e-9f24-94bfdf6cdc43">

**Comment by elsylambert** [comment]
Looks good in translationCore 3.5.0 (30831db). Organize by reference is shown on upper left filter menu and works as expected in tNotes and tWords. The filter checkbox, when selected, displays the reference as a list in order and the checks underneath the specific reference.
<img width="1438" alt="Screenshot 2023-07-11 at 10 34 16 AM" src="https://github.com/unfoldingWord/translationCore/assets/51806180/5aa401cd-14e4-499b-91bd-d5c6698f1caf">

The selection works fine and the filter works fine.
