### ISSUE TITLE
Add the Charis font

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/translationCore#7506]
Some languages are not rendered correctly in the default font.  SIL has done a lot of work to render many languages correctly in SIL Charis. https://software.sil.org/charis/.  SIL Charis should be available to users who want to take advantage of the improved rendering.

DoD
---
Users can choose Charis as a font for their scripture project or Scripture pane resources.

**Comment by PhotoNomad0** [comment]
@elsylambert @danielklapp This is in translationCore 3.5.0 (4508628): 

<img width="470" alt="Screenshot 2023-07-03 at 6 15 48 PM" src="https://github.com/unfoldingWord/translationCore/assets/14238574/165a681c-8fa3-4521-9057-1ce73af5e3ea">

**Comment by elsylambert** [comment]
Looks good in translationCore 3.5.0 (30831db). Seeing Charis SIL is available in the font selection list for scripture resources in Scripture pane.
