### ISSUE TITLE
Clear all alignments for a verse

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/translationCore#7514]
**Scenario**: When aligning users want to be able to revert to a completely unaligned verse by clearing all of the alignments
**Given**: The user is in the Word Alignment tool and the current verse has some words aligned
**When**: The user clicks a button labelled "Clear" with a tooltip "Clear all alignments"
**Then**: An optional prompt should warn the user that all of the alignments will be removed for the current verse. If the user clicks OK on the prompt then all of that verse's alignments should be removed. 

DoD:
---
Users can easily clear the alignments from the current verse in the WA tool.

Details:
---
The prompt should read:

**Comment by PhotoNomad0** [comment]
@elsylambert I think we already have this in the release.

**Comment by PhotoNomad0** [comment]
@elsylambert Either this is a duplicate, or my mistake to not move it into review.

**Comment by elsylambert** [comment]
Duplicate
