### ISSUE TITLE
Bengali Galatians doesn't show correctly in PDF preview. 

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/translationCore#7533]
If you import the attached USFM and choose print preview then the preview shows that chapter 1 beginning at verse 6. The first paragraph marker \p is just before verse 6.  Other USFM texts with no paragraph markers work correctly.
[49-BN_GAL file](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMm9kQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bac5732719fbd8f2859d9e2e57ed3a66598a25f8/49-BN_GAL.usfm.txt)

[screenshot](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXNkQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--176459db55777e350aa04b97edc2ae540cfdf1b3/CleanShot%202023-10-10%20at%2006.15.53%402x.png)

**Comment by PhotoNomad0** [comment]
Will likely need to upgrade to latest proskomma print. Sent from my iPhoneOn Oct 10, 2023, at 3:41 AM, birchamp ***@***.***> wrote:﻿
If you import the attached USFM and choose print preview then the preview shows that chapter 1 beginning at verse 6. The first paragraph marker \p is just before verse 6.  Other USFM texts with no paragraph markers work correctly.
49-BN_GAL.usfm.txt
Private Zenhub Image

**Comment by birchamp** [comment]
Thanks @PhotoNomad0  Is it using proskomma already?

**Comment by PhotoNomad0** [comment]
Yes, but it was a year old library. They have done major refactoring and the API has changed.  So I expect significant rework integrating that into tC.  Or we could do a quick hack to insert a paragraph marker at beginning in print queue if needed. Sent from my iPhoneOn Oct 10, 2023, at 5:00 AM, birchamp ***@***.***> wrote:﻿
Thanks @PhotoNomad0  Is it using proskomma already?

**Comment by PhotoNomad0** [comment]
@birchamp @elsylambert - tested with latest release: translationCore 3.5.1 (6e1cd7b).  This is looking good here, but then again the example file above does have a \p after chapter 1.

<img width="740" alt="Screenshot 2023-10-11 at 11 57 20 AM" src="https://github.com/unfoldingWord/translationCore/assets/14238574/e1b20fac-553a-49e2-9970-cf413d397756">

**Comment by PhotoNomad0** [comment]
@birchamp @elsylambert 
OK, I removed the first \p marker and see the bug mentioned.

It looks like last year we made a fix for bibles that did not have any paragraph markers (do not understand proskommas fixation about paragraph markers).  Now adding a fix for when there is not a paragraph marker before the first verse.

Do we want to release a minor tCore update with this fix?

**Comment by PhotoNomad0** [comment]
@elsylambert Fix is in latest develop build translationCore 3.5.2 (9d8cdec)

**Comment by elsylambert** [comment]
Looks good in translationCore 3.6.4 (ee24062). 

<img width="1787" alt="Screenshot 2024-03-21 at 9 01 43 AM" src="https://github.com/unfoldingWord/translationCore/assets/51806180/213e86e2-d5a2-4ba8-9b3c-eb51ca52a31f">
