### ISSUE TITLE
Clear/reset the alignments

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#7543]
**Problem Statement**
If the user wants to clear all the alignment suggestions, previous alignments and half aligned words, they have to manually move every aligned word which is cumbersome.

**Proposed Solution**
Provide a button to clear the alignments that should  send all the words to sent back to the word bank allowing the user to start over fresh.

**Details**
~~On clicking the Clear alignment button, there should be a prompt for the user to confirm if they want to claer the alignments. This is necessary to avoid accidental clicks. If user selects Yes> this should  send all the words to sent back to the word bank; If No then the words/alignment should stay as is.~~ _<= Note - Removed this for consistency because reset of suggestions does not include verification prompt.

**Additional context**

**Comment by PhotoNomad0** [comment]
@elsylambert @birchamp I couldn't find this issue for tCore, so created this using the GWE issue as a template.

**Comment by PhotoNomad0** [comment]
@elsylambert - Issue is fixed in develop branch translationCore 3.6.0 (2bc4476) .

<img width="1440" alt="Screenshot 2023-10-26 at 5 57 39 AM" src="https://github.com/unfoldingWord/translationCore/assets/14238574/9e8ee265-ad33-439a-b934-5168841159af">

**Comment by elsylambert** [comment]
Looks good in translationCore 3.6.0 (2bc4476). Clear button works as expected, clears alignments by sending words back into the word bank.
