### ISSUE TITLE
Verse span support failing for wA tool

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/translationCore#7546]
Verified in the latest 3.6.0 (2bc4476)  when there is a verse range in the Target text, Alignment area shows blank.
Project: https://git.door43.org/tracypreslar/en_ust_deu_book
Log file//: [Mon Nov 06 2023.log.zip](https://github.com/unfoldingWord/translationCore/files/13279906/Mon.Nov.06.2023.log.zip)
<img width="1792" alt="Screenshot 2023-11-06 at 11 26 36 PM" src="https://github.com/unfoldingWord/translationCore/assets/51806180/5207b293-0924-49f6-81c4-2f392d14fc0c">

**Comment by PhotoNomad0** [comment]
@elsylambert I'm guessing you are using the released build.  But when I open a book I am seeing a different error.  What repo did you load?

<img width="1483" alt="Screenshot 2023-11-07 at 7 29 03 AM" src="https://github.com/unfoldingWord/translationCore/assets/14238574/af04a948-eaa0-4fe2-b83f-f96d3c735e5a">

**Comment by elsylambert** [comment]
@PhotoNomad0  https://git.door43.org/tracypreslar/en_ust_deu_book

Log file in in the description ^^ in the issue.

**Comment by PhotoNomad0** [comment]
@elsylambert It looks like the bug is in generating the group data shown in the group menu.  Here is from 3.5.1:

<img width="1728" alt="Screenshot 2023-11-07 at 7 49 02 AM" src="https://github.com/unfoldingWord/translationCore/assets/14238574/fa09ce8d-ee94-4ffa-a25f-80cbcc45aa41">

**Comment by elsylambert** [comment]
Not seeing this issue in translationCore 3.6.1 (7e87603). Verse span works fine in wA tool.
<img width="1759" alt="Screenshot 2023-11-07 at 10 34 08 AM" src="https://github.com/unfoldingWord/translationCore/assets/51806180/ce3e53d7-f0a5-440b-8ad3-c04d07d36322">
