### ISSUE TITLE
Slow CI Build

### ISSUE THREAD

**Issue by ethantkoenig** [unfoldingWord/translationCore#755]
The Travis builds for this repo take quite a long time, and run rather frequently (see https://travis-ci.org/unfoldingWord-dev/translationCore/builds). This is causing problems for other unfoldingWord repos, particularly our gogs fork; Travis throttles open-source accounts that use too many resources, and we're afraid that the large number of long-running builds from this repo are slowing down gogs builds.

From scanning through the build logs, in seems that installing npm dependencies (i.e. `travis_retry npm install`) seems to take a fairly long time (routinely over 20 minutes), particularly on OSX. Would it be possible to cache those dependencies to speed up your builds?

**Comment by ihoegen** [comment]
@ethantkoenig We will look into caching, but for now, I've limited translationCore to only 4 concurrent builds, and disabled building on pushes. Builds will be limited to just pull requests until we find a solution.

**Comment by klappy** [comment]
@ethantkoenig @ihoegen: I disabled creating builds for PR's to prevent it from clogging to Queue, I've also limited tC concurrent builds to 2.
