### ISSUE TITLE
In WA tool, Bug in shift-click selects words already used.

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#7555]
### User Story

In WA tool, Bug in shift-click selects words already used:

<img width="875" alt="Screenshot 2023-11-08 at 9 12 04 AM" src="https://github.com/unfoldingWord/translationCore/assets/14238574/6ab2e41e-f543-4b4b-b375-5577691e2bc4">

Then if the user drags the group to another alignment, the word is doubly aligned:

<img width="1408" alt="Screenshot 2023-11-08 at 9 08 18 AM" src="https://github.com/unfoldingWord/translationCore/assets/14238574/c76eee43-7396-4b65-b165-5a397792676c">

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by elsylambert** [comment]
Looks good in translationCore 3.6.2 (d1f76d8)
