### ISSUE TITLE
TranslationAcademy pane shows RTL languages left aligned  when expanded

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/translationCore#7562]
Project: [ar_new_phm_book.zip](https://github.com/unfoldingWord/translationCore/files/14485587/ar_new_phm_book.zip)
Open an Arabic project  and go to tW. 
Screenshot: 

<img width="1356" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejZzQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5f912274369bac25f155cfa7042eb9b7cecfbc9e/Screenshot%202024-03-04%20at%2012.44.55%E2%80%AFPM.png" alt="Screenshot 2024-03-04 at 12.44.55 PM.png" />

**Comment by PhotoNomad0** [comment]
@elsylambert This screenshot seems broken?

**Comment by elsylambert** [comment]
<img width="1596" alt="Screenshot 2024-03-19 at 11 24 07 AM" src="https://github.com/unfoldingWord/translationCore/assets/51806180/1bfc3cb3-9a67-4496-877d-92be57af782c">

**Comment by PhotoNomad0** [comment]
@elsylambert Does this look right to you:

<img width="1476" alt="Screenshot 2024-03-19 at 1 18 52 PM" src="https://github.com/unfoldingWord/translationCore/assets/14238574/7f4dd8d9-71cf-40c4-8764-c996e17bb964">


And also the side panel is backwards also:

<img width="1489" alt="Screenshot 2024-03-19 at 12 53 08 PM" src="https://github.com/unfoldingWord/translationCore/assets/14238574/bbb36905-d9ec-469a-b63f-b4db3070c926">

**Comment by elsylambert** [comment]
@PhotoNomad0 The screenshot above ^^ is Hindi which is actually LTR, so it looks odd to me, but otherwise by RTL perspective, it is fine . May be I can try with Arabic TA.

**Comment by PhotoNomad0** [comment]
Yeah, my goof here on language selection.  Still working on the implementation to use language direction of GL.

**Comment by PhotoNomad0** [comment]
@elsylambert Here's a second attempt with Farsi as the GL:

<img width="1495" alt="Screenshot 2024-03-19 at 2 29 50 PM" src="https://github.com/unfoldingWord/translationCore/assets/14238574/852e336e-434a-412f-885b-7b6acba8427f">

**Comment by elsylambert** [comment]
Looks good to me.

**Comment by PhotoNomad0** [comment]
@elsylambert Fix is in latest develop build translationCore 3.6.4 (ee24062)

**Comment by elsylambert** [comment]
Looks good in translationCore 3.6.4 (ee24062). TA pane and the expanded tA article are now RTL Compatible.
<img width="1787" alt="Screenshot 2024-03-20 at 9 25 20 AM" src="https://github.com/unfoldingWord/translationCore/assets/51806180/93d16ea6-0327-41fc-a78c-36169878fc62">
