### ISSUE TITLE
tC shows blank screen when fa_gl resources are downloaded

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/translationCore#7563]
Open tC and download content updates from fa_gl.
Problem I: Note that in translationHelps>tNotes> fa_gl folder is empty with only manifest file in it.
Problem II: After the download, tC screen goes blank.

Field reported: tC shows blank screen, until they delete the tN folder for fa_gl.

**Comment by PhotoNomad0** [comment]
Fix is in translationCore 3.6.3 (e859026)

**Comment by elsylambert** [comment]
This issue is fixed in translationCore 3.6.3 (e859026). Not seeing white blank screen on downloading fa_gl
