### ISSUE TITLE
Do not completely fail downloads of resources due to missing files

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord/translationCore#7580]
## Summary

The current download of unfoldingword/en_twl fails because there are files mentioned in manfest projects that are missing in the repo.  It seems that rather than failing the entire download, we should just process the files that are present in the repo and referenced in the manifest.

## Motivation

According to Rich this is because they removed unpublished books from the repo, but not the manifest.

## Specifications (If applicable)
A clear and concise description of the details about the feature that may or may not be obvious

**Comment by PhotoNomad0** [comment]
@elsylambert Fix is in translationCore 3.6.5 (de28495)

**Comment by PhotoNomad0** [comment]
To test in tCore, download all the en resources from unfoldingWord - it should succeed.

**Comment by elsylambert** [comment]
Verified in translationCore 3.6.5 (de28495). Download of uW resource succeed without fail.
<img width="1904" alt="Screenshot 2024-07-12 at 10 34 42 AM" src="https://github.com/user-attachments/assets/da3048e9-3f4d-4502-9c12-bc5b2642d37a">
