### ISSUE TITLE
Critical error when opening a project  App Version: 3.6.6 (635b02f)

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/translationCore#7597]
I downloaded the latest ULT Titus from https://git.door43.org/unfoldingWord/en_ult/src/branch/master/57-TIT.usfm and imported it as a local project, and when tC 3.6.6 tries to open it, it has the same error.
[id_glt_3jn_book.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1lFQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ce62d9173f155418705b39f7368dd879ee823658/id_glt_3jn_book.zip)
[Wed Sep 25 2024.log.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2dFQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ff1f6e91505f9581eca2f43242b65b45c5887306/Wed%20Sep%2025%202024.log.zip)

This is their repo: https://git.door43.org/id_gl
The projects I have I loaded a couple months ago, so the ones on DCS may be updated ones now.

**Comment by PhotoNomad0** [comment]
@elsylambert A bit confused by the description.

I tried importing the usfm project and it opened for me.

then I unzipped the 3jn project and that one opened for me also.  

So I'm wondering what is different between our setups.  Did you download other resources?

**Comment by elsylambert** [comment]
Hi Bruce,

I wrote up the issue to have all project info and logs in one place. I
myself have not been able to replicate the error yet. This was reported by
Russ Perry and I wanted to investigate more with your help.

**Comment by PhotoNomad0** [comment]
@elsylambert Thanks - It looks like they were using resources from owner `bahtraku`.  I'll check that.  


Language id

**Comment by PhotoNomad0** [comment]
Notes:

**Observations**
* Crash is when enumerating GLs for WA - stops after `Door43-Catalog, rlob, ru, tit`
    * Usually `Door43-Catalog, rob, ru, tit` would be next
      * Is one of the resources broken?
      * additional resources installed?
* Seems to be using max build
* Actual errors seem to be when rendering UI

**Ideas**
* Have Russ zip up and send his resources folder?
* Test on windows since Russ is using `10.0.19044` (it could be win10, but need to verify)
  * _note:_ worked for me installing MAX on on win10 - I'm on 19045 which is Version 22H2 (2022 Update), Russ is on Version 21H2 (November 2021 Update).  That may not make a difference, but I don't have a way to test the older release.

**Comment by elsylambert** [comment]
@PhotoNomad0 I have emailed you shared drive where Russ uploaded his resources.

**Comment by PhotoNomad0** [comment]
> @PhotoNomad0 I have emailed you shared drive where Russ uploaded his resources.

That solved the problem - I've been able to reproduce the crash using Russ's projects.  There is corruption in this file: `~/translationCore/resources/ru/bibles/rob/v8_Door43-Catalog/manifest.json`.  He just needs to delete his resources folder before starting tCore and the resources will be recreated.  Not sure how that happened on his PC, but it can be fixed.

Also rsb is corrupted.

**Comment by PhotoNomad0** [comment]
@elsylambert This problem was file system corruption on Russ's computer.  It doesn't seem that we want to expend a lot of effort on this since we have not been able to recreate this.

**Comment by elsylambert** [comment]
Closing this issue.
