### ISSUE TITLE
QA Mode in tC is breaking

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/translationCore#7608]
When we switch to QA mode using the command echo "<https://qa.door43.org>" > ~/translationCore/QA_MODE and open tC, it shows white screen. Please see screenshot with error console:
<img width="1512" alt="Screenshot 2024-12-13 at 9 22 35 AM" src="https://github.com/user-attachments/assets/6ad520c1-75a5-4e02-aa51-2eec2a028d98" />

**Comment by PhotoNomad0** [comment]
@elsylambert Not seeing this problem.  Would you please attach the log file?

**Comment by PhotoNomad0** [comment]
@elsylambert - Oh I see the problem - the one line should be `Found param = --QA_MODE=https://qa.door43.org` but in your debug it has the URL as `<https://qa.door43.org>`, the brackets are not supposed to be there.  Try executing `echo "https://qa.door43.org" > ~/translationCore/QA_MODE` in the terminal.

**Comment by elsylambert** [comment]
Thanks @PhotoNomad0 Works fine after I corrected the command.
