### ISSUE TITLE
Unable to create new Repository while doing online import of a project.

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/translationCore#7611]
Steps:
- Open tC and click on online import and paste this project link: https://git.door43.org/ElsyLambert/en_teso_tit_book.
This project already exists in my github user account, so tC prompts that Project repo be renamed or create new Repository.
- Click on Create new Repository. tC shows error as in the screenshot.
<img width="1512" alt="Screenshot 2024-12-17 at 9 20 21 AM" src="https://github.com/user-attachments/assets/e43dd074-6497-4ae0-8162-53ccd8e2f38b" />
- In this prompt, Rename local project and change the translation Id and try again. The project is now imported. 
Log files: 
[Tue Dec 17 2024.log.zip](https://github.com/user-attachments/files/18167547/Tue.Dec.17.2024.log.zip)

**Comment by elsylambert** [comment]
Logs file: [Tue Dec 17 2024.log.zip](https://github.com/user-attachments/files/18167554/Tue.Dec.17.2024.log.zip)

**Comment by PhotoNomad0** [comment]
@elsylambert - would to try to reproduce this again and record it?  So far I cannot reproduce the git init error.

**Comment by elsylambert** [comment]
@PhotoNomad0 here is the recording:

https://github.com/user-attachments/assets/af53803b-ab46-4ee7-b714-c1aa831eb373

**Comment by elsylambert** [comment]
@PhotoNomad0 after the clean install this is the workflow I am seeing ^^.

**Comment by PhotoNomad0** [comment]
> @PhotoNomad0 after the clean install this is the workflow I am seeing ^^.

It seems like it worked this time in your video, and I didn't see the git init error.
