### ISSUE TITLE
SPIKE: Why Create Account broken

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#764]
Spike for #707 
Talk to Luke & Klappy about what it isn't.

**Comment by RoyalSix** [comment]
Found a problem, but didn't fix it. 
The problem that I found was spending the wrong parameters in the POST object
it was : 
`{
username:
password:
login_name:
email:
}`
it should be:
`{
username:
password:
full_name:
email:
}`
For implementation, we may have to simply show another window from the gogs site letting them create an account.
