### ISSUE TITLE
"Login failed. Unknown error" message returned

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#778]
I attempted to log in using the wrong password. The error message indicated that the problem may be because I tried to use an email address rather than a user name. So I tried to log in using a email address and now I get an error message indicating that the error is unknown. We should always try to give the user the most accurate information we have. 

In translationStudio it returns error messages indicating Invalid username and Invalid password so I assume that the API returns that sort of information. I would not expect that type of error to return "Unknown error".

**Comment by cdwhitfield73** [comment]
The error handling for logging in was updated awhile ago, and these scenarios have been resolved.
