### ISSUE TITLE
Difficult to determine which Load Project button to click

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#784]
There is so much blank space between the project name and the Load Project button that it is difficult to visually determine which button is the desired one. There should be some kind of delineation (e.g. alternating darker/lighter bands, solid lines between bands, etc.) to make it easier to visually find the button that is related to the desired project.
![image](https://cloud.githubusercontent.com/assets/8171759/23385005/082850a4-fd13-11e6-8d99-aea2e3fb6a4a.png)

**Comment by cdwhitfield73** [comment]
this page has been completely reformatted since this issue was written.  The problem has been resolved with those changes.
