### ISSUE TITLE
Standardize on capitalization rules

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#845]
I think most apps these days have standardized on only capitalizing the first letter in headings, etc., so would recommend that. We currently do not have consistency here. E.g. Propose Changes, This change addresses:, Word Choice.

**Comment by benjore** [comment]
https://xd.adobe.com/view/0c5703e1-8ddb-4c25-b66f-933a9e014326/screen/5270cbe0-1e58-4329-ba0b-83da1a41b343/Fonts

**Comment by cckozie** [comment]
This should be taken care of now in the style guide.
