### ISSUE TITLE
Split tN into Primary & Secondary

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#857]
# User Story

As a *user* I want to *start with the most important checks* so that *I prioritize my efforts and don't get overwhelmed*. 

# Definition of Done
- [ ] Only Ephesians & Titus
- [ ] Only creating Primary is necessary (though tN - secondary will come soon)
- [ ] Split according to specifications in Notes (below)

# Notes

**Specifications for splitting Primary & Secondary** - For each check, the consultants labeled it primary or secondary. If a value of `2` is given for each "primary" answer and a value of `1` is given for each "secondary" answer, then every check that gets an average of `1.5 or greater` will be included in "primary". Anything `less than 1.5` will be a part of "secondary".

- Google Sheets: 
  - Ward - https://docs.google.com/spreadsheets/d/1jWad07LfR_wFE-OYaHeeuRqPoTmx_7ZbASIXJXufnfk/edit#gid=248585669
  - Simona - https://docs.google.com/spreadsheets/d/1okOXVvEU3XS0JO56NNExN72TkIjst6IG2TPDFP3Vo7w/edit#gid=2059862525
  - Alan - https://docs.google.com/spreadsheets/d/1Y4GPc7BGtnm2hiOuQN0AW_iFKgty2bFEzS4iBqFzZ_Y/edit#gid=248585669
  - Tom - https://docs.google.com/spreadsheets/d/1GjwaOI_k-RP4fN0TT4Obsx3zy5EXFXwhIrKFphNSp2k/edit#gid=2059862525
  - Christian - https://docs.google.com/spreadsheets/d/1PthVDfKyEjVuvcGmTtXO1ZVpJ4ev20wNUdpV9SkPmQk/edit#gid=2059862525
  - Mark - https://docs.google.com/spreadsheets/d/1HmVawX1cMt1mX-VI7kQYHdgcE8XfLgvwhiCg0mKFhpk/edit#gid=2059862525
  - Perry - https://docs.google.com/spreadsheets/d/12WV-01hqDBfyCZRZTaY5mD52UrpbuCM1Cny7PzmwNEY/edit?ts=58b70dbb#gid=2059862525

- See also Ben's Spreadsheet with averages https://docs.google.com/spreadsheets/d/1xeYQjzVtJLfA2zd3TGCGvmiK1NPf2jK2RjH0boBPqFg/edit#gid=0

**Comment by ihoegen** [comment]
@benjore Will this Primary/Secondary checking be split into sections on the menu, or is this just the order checks are displayed in the menu?

**Comment by ihoegen** [comment]
Nothing can be done on this until translationNotes is refactored

**Comment by cckozie** [comment]
I need to spot check to ensure they were split and imported correctly.

**Comment by cckozie** [comment]
There are many checks missing based on the data in the spreadsheet. For example:
The spreadsheet shows 8 checks for Active or Passive in Eph., tC shows 5.
The spreadsheet shows 3 checks for Idiom in Eph., tC shows 1.
The spreadsheet shows 9 checks for Metaphor in Titus, tC shows 8.

**Comment by klappy** [comment]
The code looks good but I still see the same output that Koz failed this issue over...

There are many checks missing based on the data in the spreadsheet. For example:
The spreadsheet shows 8 checks for Active or Passive in Eph., tC shows 5.
The spreadsheet shows 3 checks for Idiom in Eph., tC shows 1.
The spreadsheet shows 9 checks for Metaphor in Titus, tC shows 8.

Except tC now shows 18 metaphors and not 9 or 8.

**Comment by ihoegen** [comment]
@klappy I've looked over the code, and have debugged the check objects that are kept, while also looking at those that are gotten rid of, and it makes no sense, the actual checks aren't matching the checks that are on the spreadsheet anymore, possibly due to a data update

**Comment by ihoegen** [comment]
@cckozie @klappy I believe the issue with this is that the sources have changed, so the checks have changed. I think we need to have another review of the data.

**Comment by cckozie** [comment]
It looks like Titus is now correct, but there are still issues in Ephesians

**Comment by ihoegen** [comment]
@cckozie From what I've looked at, all checks that have been marked to remove have been removed from Ephesians. I believe any discrepancies between the spreadsheet and tC are caused by changes in the checks, so the spreadsheet needs to be updated. @klappy Could I get some input?

**Comment by cckozie** [comment]
@ihoegen It looks to me like too many have been removed. The spreadsheet shows 52 tN Part 1 checks for Ephesians and tC shows 38.

**Comment by ihoegen** [comment]
@cckozie When I looked for the ones that were being removed, they weren't being removed by the filters, instead they were removed from in the data source itself.

**Comment by cckozie** [comment]
@benjore @klappy How do we want to deal with this? 
Is the spreadsheet the system of record or not?
If yes, then is our team responsible to ensure we have current data in tC, or is some other team responsible for making that available via an API or some other vehicle?
If no, then what should I be testing against?

**Comment by ihoegen** [comment]
Am now blocked by Titus not loading

**Comment by klappy** [comment]
@ihoegen: This fixed 2/3 categories to match in number. Can you double check Metaphors? Somehow we grew to 23 metaphors! :o

I can't recreate your problems with titus, can you share your project url? Try some from my user on d43, klappy.

**Comment by cckozie** [comment]
I'm still seeing a signifcant disconnect between what's in the spreadsheet and what is in tC. For example, in Ephesians I'm seeing these numbers:
![image](https://cloud.githubusercontent.com/assets/8171759/26325577/71d32b08-3f05-11e7-862c-13ff02acd6cc.png)

**Comment by ihoegen** [comment]
@cckozie Try deleting the`.apps` folder, it will force the fetchdata to run again, bringing in a fresh filter

**Comment by cckozie** [comment]
@ihoegen Imported a new project In 0.6.26.6 and we're still missing a couple of Metaphors in Ephesians. Didn't recheck Titus.

**Comment by ihoegen** [comment]
@cckozie I noticed the 2 missing metaphors on Ephesians, I put a PR out today for them
