### ISSUE TITLE
Check info Card

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#858]
# User Story

As a *user* I want to *clearly see what I am checking and what it means* so that *I always know what check I am on*. 

# Definition of Done
- [x] On the left ~1/3 of the card
  - [x] For tN - The quote from the text
  - [x] For tW - The quoted word from the text
- [x] On the right ~2/3 of the card 
  - [x] For tN - The translation Note
  - [x] For tW - the first paragraph of the tW article
- [ ] Link
  - [ ] For tN - "See: [Title of tA article]" (e.g. "See: Ellipsis")
  - [x] For tW - "See More" 
  - [x] [Clicking the link will open the tHelps side panel. If the panel is already open, the link is grayed out and unclickable.]

**Comment by klappy** [comment]
@benjore @ihoegen: I don't think the final result looks like the description here. Did Thomas send the wrong mockup?

<img width="671" alt="screen shot 2017-03-13 at 8 55 02 am" src="https://cloud.githubusercontent.com/assets/118073/23855098/c760c57a-07ca-11e7-9570-bed4f988ec95.png">

**Comment by klappy** [comment]
Oh wow, nvm... That only happens when developer console is open.
Sorry for the false alarm!

<img width="774" alt="screen shot 2017-03-13 at 8 57 31 am" src="https://cloud.githubusercontent.com/assets/118073/23855195/2ddd4e40-07cb-11e7-9af7-9985eb7ce517.png">
