### ISSUE TITLE
Edit Mode

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#860]
# User Story

As an *OCD checker* I want to *edit my translation on the spot* so that *I don't have a breakdown by having to advance to the next check without fixing the current one*!

# Definition of Done 
- [ ] The edit box pre-populates with the current translation. 
- [ ] Checkboxes as per mockup
- [ ] When the user clicks "Save Changes", the edits made are now the current translation. 
  - [ ] STRETCH: Any selection that has already happened and that has not been broken is retained.
  - [ ] If the selection is broken at all, it resets and the user must re-select the portion of the translation that corresponds to the check. 
- [ ] Selecting is not permitted in this mode, but is to be shown if it has been already completed.

**Comment by Thajny** [comment]
![image 2017-03-09 at 4 24 07 pm](https://cloud.githubusercontent.com/assets/21183377/23773456/dd68a362-04e4-11e7-82ab-15fcf56f53ca.png)
