### ISSUE TITLE
Comment Mode

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#861]
# User Story

As a *user* I want to *leave a comment* so that *I have a way of making notes in the check that are not lost*. 

# Definition of Done 
- [ ] A freeform edit box where the user can save notes. 
- [ ] If a user leaves the check where he has left a comment, when he later returns to the check, the comments will still appear in the edit box. 
- [ ] Selecting is not permitted in this mode, but is to be shown if it has been already completed.

**Comment by Thajny** [comment]
![image 2017-03-09 at 4 25 01 pm](https://cloud.githubusercontent.com/assets/21183377/23773471/fa0db5ca-04e4-11e7-8526-62f9b7bafeae.png)
