### ISSUE TITLE
In VerseCheck: Modal Pop-out for Target Translation

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#863]
# User Story

As a *user* I want to *see the context of the verse I am checking* so that *I can make a better translation by seeing how the verse and check flows with the larger passage*.

# Definition of Done 
- [x] Modal Pane pop-out showing just the translation
- [x] Appears in and works in Select Mode, Edit Mode, and Comment Mode.

**Comment by Thajny** [comment]
![mylang](https://cloud.githubusercontent.com/assets/21183377/24416127/54aad314-13a9-11e7-8093-b9cdd23d2d7a.png)
