### ISSUE TITLE
Dynamic verbiage on Continue and Previous buttons

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#891]
As an easily confused user I would like the text related to the Save and Continue button and the Save & Previous link to be more specific so the workflow is more obvious. I'd like the initial verbiage to just be "Continue" (or "Next") for the button, and "Previous" for the link. Once I have made any changes to the form I would like the button text to be "Save and Continue" (or "Save and Next"), and the link text to be "Save & Previous". If I cancel all of the changes made, the "Save" verbiage should again be hidden. Both the button and the link should always be active when the form is displayed.

**Comment by benjore** [comment]
Same as #1182
