### ISSUE TITLE
Standardize verbiage used to "import" and "export" projects

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#894]
As a new user I would like the verbiage used for getting projects into and out of tC to be standardized so that I can more easily understand what will happen when I make a selection.

Background:
In translationStudio we have used upload, download, save, backup, import, export, and maybe others to describe the various processes. We have now standardized on call everything that brings a project into the app as "Import" regardless of where it is coming from, and everything that sends a project out as "Export" regardless of where it is going of what form it will take.

**Comment by cdwhitfield73** [comment]
I'm not sure what all verbiage was being used when this issue was created, but we now just have "Import", "Export" when it goes to csv, and "Upload" when it goes to Door43.  Is that acceptable?
