### ISSUE TITLE
Change wording for check info card

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#905]
- [x] for tNotes only, change wording of the link from "See more: [title]" to "See: [title]" (title, not slug, e.g. Doublet, not figs_doublet)
  - [x] when tHelps Pane is open, this link disappears
  - [x] when tHelps Pane is closed, this link reappears
- [x] tWords - keep verbiage "See More"
  - [x] tHelps Pane open/close appear/disappear feature (see above)
- [x] Make the capitalization match what is in the text, e.g. quote verbatum
  - [x] for tW
  - [x] for tN

**Comment by mannycolon** [comment]
@cdwhitfield73 what's the status on this story? do you need any help?

**Comment by cdwhitfield73** [comment]
Blocked until we get the Notes tool working again.

**Comment by klappy** [comment]
@cdwhitfield73: Can you copy/paste some of the updated formatting from tW checking tool for this? There are some odd things that happen that were already addressed in tW.

**Comment by klappy** [comment]
@cdwhitfield73: Overall this looks great, but the white bar going from top to bottom doesn't match the mockups anymore. 

@benjore: Can you share the mockups for him to look at?

**Comment by cdwhitfield73** [comment]
@klappy Ben and I talked about this and he said it was okay to make minor changes to the formatting for now, realizing that there are still some issues that will need resolved later.  I will discuss the issues I had with Thomas, because what was there before wasn't perfectly matching the mock ups either.
