### ISSUE TITLE
Warning when trying to "Save and Continue" without selecting translation

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#908]
Use bootstrap modal

**Comment by Thajny** [comment]
![image 2017-03-14 at 2 42 13 pm](https://cloud.githubusercontent.com/assets/21183377/23919339/7ef35bfe-08c4-11e7-9e9e-6261e1556f5e.png)

**Comment by mannycolon** [comment]
@RoyalSix you should probably use this instead of the react-bootstrap component
http://www.material-ui.com/#/components/dialog

**Comment by RoyalSix** [comment]
@mannycolon haha ok, I might.

**Comment by benjore** [comment]
bug - Save & Continue works once, not the next time

**Comment by benjore** [comment]
Hopefully will be addressed by #1104

**Comment by mannycolon** [comment]
based on new testing this issue seems to be fixed

**Comment by cckozie** [comment]
@benjore I need your opinion on whether I should pass or fail this issue. The functionality does work, but visually it is different than what is in a previous comment in this issue, including animation on the Close button which I really, really don't like.
![image](https://cloud.githubusercontent.com/assets/8171759/25490023/3c94b50c-2b31-11e7-83e5-78118b83a664.png)

**Comment by cckozie** [comment]
Please remove the animation on the Close button and change its text color to black as in Thomas' image above.
