### ISSUE TITLE
Reducers modeled after New Data Structure

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#911]
Ask Manny :)

**Comment by ihoegen** [comment]
@klappy @mannycolon This issue would be something I'd like to help out on

**Comment by mannycolon** [comment]
@ihoegen I let you know. i have to plan  a few things out first. did you review redux documentation??  and/or checked out the tutorial ?? https://egghead.io/courses/getting-started-with-redux

**Comment by mannycolon** [comment]
**Actions**

- Import Project Actions
    - Local import
    - Online import

- Load Project Actions
   - Load/fetch data (bibles, translationNotes, translationWords)
   - submodules (verseCheck, Scripture pane etc) do not fetch data.
   - Generate data structure for checks

**Reducers** 

- modulesReducer and/ or projectInfoReducer (not sure if both or just one)
- checkData:
   - commentsReducer
   - remindersReducer
   - selectionsReducer
   - verseEditsReducer

- resourcesReducer
- settingsReducer
- uiReducer
- notificationsReducer
- popoverReducer
- loginReducer

**Comment by ihoegen** [comment]
@mannycolon Just looked at the documentation. I think I get what's going on

**Comment by mannycolon** [comment]
@ihoegen so I think after we meet Wednesday for the redux show and tell we should be able to work together on this.
