### ISSUE TITLE
Scripture Pane not displaying correctly when name of translation is 2 lines long

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#928]
![screenshot 2017-03-14 12 01 18](https://cloud.githubusercontent.com/assets/13352518/24108291/3171ceec-0d5b-11e7-81cb-1cc9f748bcfb.png)

**Comment by cckozie** [comment]
What is a project I can use to test this?

**Comment by cckozie** [comment]
I cannot find any door43 projects that have a multiline language name.

**Comment by cckozie** [comment]
Two lines are now fine, but 3 lines aren't good in the expanded scripture pane. See issue #1340 .
