### ISSUE TITLE
Implement Reducer/Actions for Group Index.

### ISSUE THREAD

**Issue by EllDoubleYew** [unfoldingWord/translationCore#952]
From https://github.com/unfoldingWord-dev/translationCore/issues/734

> Index file that addresses order and labels ./apps/translationCore/index/translationNotes/index.json
```json
[
  {"id": "figs_hyperbole", "name": "Hyperbole"},
  {"id": "figs_rpronouns", "name": "Reflexive Pronoun"},
  {"id": "figs_metaphor", "name": "Metaphor"},
  {"id": "figs_activepassive", "name": "Active or Passive"},
  {"id": "figs_ellipsis", "name": "Ellipsis"},
  {"id": "figs_...", "name": "..."}
]
```

This story will address the Reducers and Actions for everything related to the group index.

**Comment by mannycolon** [comment]
@EllDoubleYew whats the status on this??
