### ISSUE TITLE
Close modal and pop toast when a project successfully loads

### ISSUE THREAD

**Issue by EllDoubleYew** [unfoldingWord/translationCore#96]
> As a user I want to know that my project successfully loaded so that I have confidence to chose a check app.

Right now when you load a project in from your Door43 account the modal does not change and there is not really a good way to know that the project was successfully loaded. I was thinking that we could close the modal and display a toast that confirms that the project was successfully loaded.

**Comment by mannycolon** [comment]
@EllDoubleYew @klappy @RoyalSix @ihoegen @benjore  A project is not `Loaded` when the user clicks `Load` on the side bar and then selects the loading option. In reality, the loading process starts once the end user clicks/selects the app he/she will be using. Therefore, I added a toast notification saying: **Info:  Your project is ready to be loaded once you select a tool**

**Comment by mannycolon** [comment]
#219
