### ISSUE TITLE
"Welcome to translationCore" Screen

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#963]
- [ ] This screen only appears on fresh installs, or if no user has been created
- [x] Clicking "Get Started" takes the user to the home screen

**Comment by Thajny** [comment]
![welcome](https://cloud.githubusercontent.com/assets/21183377/24412404/fdf7255a-139d-11e7-8599-c1aee97c3c58.png)

**Comment by Thajny** [comment]
![startup](https://cloud.githubusercontent.com/assets/21183377/25150026/2d7adc14-2446-11e7-90ec-74cdb3190a21.png)

**Comment by cdwhitfield73** [comment]
Putting this in the QA column for now, but it can't be tested by QA because it is on a separate branch for the new "home screen" layout that is not part of the current builds.

**Comment by cdwhitfield73** [comment]
This screen has been adapted from it's original purpose and is being used as the main screen on start up.  QA this issue based on that and we can address any issues with the new home screen layout later.

**Comment by cckozie** [comment]
@benjore Should I pass this for now even though it wasn't completed as specified?
1. The issue specifies "This screen only appears on fresh installs, or if no user has been created", but it is displayed every time the app is opened regardless of whether or not a user has been created or projects have been worked on.
2. Thomas' image shows the tC version number at the bottom, but it is not displayed in tC.

Clicking get started does take the user to the home screen.

**Comment by benjore** [comment]
@cckozie 
1. is not an issue any more with the new workflow. In fact better the way it is currently. 
2. With the current workflow the version number is plenty obvious in the modal, so I'm fine without the version number not appearing... until we get rid of the menu modal in future releases.

**Comment by benjore** [comment]
@cckozie I changed my mind. The version number was removed from the setup modal, so here is my revised comments. 
1. This is fine as is. 
2. We need the tC version number at the bottom of the "Get Started" screen.

**Comment by cdwhitfield73** [comment]
Added version
