### ISSUE TITLE
License Page

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#967]
- [ ] When a user clicks the (i) next to the version number on any of the set-up screens, it will take them to this modal pop-out
- [ ] Content in the modal
  - [ ] translationCore license - this must be copied exactly as it appears in the mockup
  - [ ] "Third Party Code..."
    - [ ] Research which libraries & 3rd party code has been used in tC
    - [ ] For each, include the name of the library, the license it is released under, and a link to that license.

**Comment by Thajny** [comment]
![license 1](https://cloud.githubusercontent.com/assets/21183377/24412445/1049fc82-139e-11e7-8d9a-ce83c499c2ad.png)
![licensing 2](https://cloud.githubusercontent.com/assets/21183377/24412444/1044e986-139e-11e7-96ad-e3b1d8e45f58.png)

**Comment by Thajny** [comment]
On the second screenshot, I didn't have what software/libraries tC is using, so I just put in place holder text. "name of software" should be replaced by the actual name. Same for "license released under" and "link to license"

**Comment by Thajny** [comment]
![licensing 1](https://cloud.githubusercontent.com/assets/21183377/25150051/3c5d41ae-2446-11e7-855e-d6a18048ca97.png)
![licensing](https://cloud.githubusercontent.com/assets/21183377/25150050/3c5be48a-2446-11e7-8a6d-4915dee0e44d.png)

**Comment by cckozie** [comment]
The licenses page has been created but is accessed via the Licenses "tab" on the User page. There is no (i) that I can find anywhere. Is that OK, @benjore

**Comment by cckozie** [comment]
Ben says it's good!

**Comment by cckozie** [comment]
The link for each package has the text "Link to license" but the link actually is not to the license but rather to the package's github repo.
1. At a minimum, the text on the link should be changed so that it is accurate
2. I think it would be preferable to link to the packages website as we do in tS rather than to its github repo

**Comment by cckozie** [comment]
I'm re-passing this issue and creating a new one to redo this page.
