### ISSUE TITLE
2. Project: Export to CSV

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#973]
- [x] How to access
  - [x] Add another button to the "My Projects" Menu
- [ ] What to export
  - [x] Comments.csv
  - [x] Reminders.csv
  - [x] Selections.csv
  - [x] VerseEdits.csv
  - [x] CheckInformation.csv (what's in GroupData)
- [x] Remove the "Reports" tab

# For the Stepper
- [ ] How to access
  - [ ] In the "Project" phase of the stepper, each project card has a three-dot menu, this also allows "Export Checking Data (CSV)"
  - [ ] In "Home", a loaded project also has the three-dot menu which allows "Export Checking Data (CSV)"

**Comment by Thajny** [comment]
![export csv](https://cloud.githubusercontent.com/assets/21183377/24416024/f77dbcd8-13a8-11e7-95ec-a376e32627b6.png)

**Comment by cdwhitfield73** [comment]
@RoyalSix Jay - I removed the Reports tab for you, since I was already in this area making other changes to the tabs.

**Comment by klappy** [comment]
@RoyalSix: Where is this data going currently? It looks like it is going in the existing project folder. I think we need it to go elsewhere. Also, I think we need to export all verse edits, not just the latest ones. All of the others just only return one value, and don't have more than one per contextId.

@benjore: What are you expecting to happen with the data? Should it "download" a zip file? or where should they go? Should the user select a path for it to store the zip or to create a sub directory with the files?

**Comment by RoyalSix** [comment]
@klappy Its going  to the apps folder and then ./output I just did that for now, can change it. I don't think I'm sure what behavior you are experiencing it should be going to the corresponding tool apps/output folder. Can you send the csv file its generating?

**Comment by cckozie** [comment]
1. The file names in the .zip are not the same as specified in this issue
2. If the user chooses to cancel rather than continue the export, the displayed message still indicates that the export was successful.
3. Change the text on the message displayed when there is no checkdata to ""No checks have been performed in this project."

**Comment by klappy** [comment]
@cckozie:
1. Do we want to separate check information for each tool? One for tW and one for tN?

**Comment by cckozie** [comment]
The file names are now correct and so is the message when the user cancels the export, but the username and timestamp need to be included in all of the files (except for checkinformation).

**Comment by RoyalSix** [comment]
@cckozie  When you say "the username and timestamp need to be included in all of the files" do you mean the actual data in the csv for each change or the file names corresponding to when the csv was exported and by who?

**Comment by benjore** [comment]
@RoyalSix In the data in the csv for each change. 

We have to have the data organized so that if multiple edits and comments are made by multiple users and then the data is merged, the user will be able to export the data as a CSV and easily see who did what. Hence, all the username & datestamp being in each change in the CSV.
