### ISSUE TITLE
2. Project: Archive project

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#975]
- [ ] Archiving a project moves the file somewhere (Create an "archive" folder in the tC directory?) and removes the project from the list of projects in "project"

## Specs
- [x] Archiving project will show up in the three-dot menu for each project
- [ ] If that project already shows up in the archive, add an ascending numerical value to the project e.g. `en-ulb-tit-book(3)`
- [x] Capture timestamp when it was archived. 
- [ ] Suggestion: Create a new folder "archive" and move the project there in its totality (so that a tech can manually move it back into the "project" folder if needed/desired.

## Note
- This action can be undone by "Restore Archived Project" #978

**Comment by Thajny** [comment]
![project-remove](https://cloud.githubusercontent.com/assets/21183377/24563522/348e6542-1614-11e7-8086-e5a62d64d892.png)

**Comment by Thajny** [comment]
![project-archive](https://cloud.githubusercontent.com/assets/21183377/24669121/c65651f2-192e-11e7-81a9-7ee52a59ca21.png)

**Comment by birchamp** [comment]
Inform the user that they can restore upon archive.   So they know how to use the feature and that they aren't deleting the project

**Comment by birchamp** [comment]
Proposed text for Archive only. This will need to be changed if we add restore:

"Archiving this project will remove the project from the project list, but it will continue to store the project on your computer. If you wish to continue, click Archive Project below."

**Comment by birchamp** [comment]
This mockup supersedes the one above![archive alert.png](https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/af1c551f-e413-4831-a227-4c01a033fafe)

**Comment by da1nerd** [comment]
Where should the timestamp be stored?
We could put it in the file name. This would replace the need to put numeric values on the file name.

e.g.
```
en-ulb-tit-book(2020-03-20T02:40:25Z)
en-ulb-tit-book(2020-04-23T02:40:25Z)
```

Also, should we make the archive folder hidden? e.g. `.archive` to avoid people putting things in there manually? This would limit restoration to the tC application or tech assistance.

**Comment by da1nerd** [comment]
I have a PR ready with archiving support.
https://github.com/unfoldingWord/translationCore/pull/6868

I implemented it with my suggestions in the comment above, but can adjust it without too much trouble.

**Comment by da1nerd** [comment]
@birchamp could you or someone answer the questions in https://github.com/unfoldingWord/translationCore/issues/975#issuecomment-618142589? Thanks.

**Comment by birchamp** [comment]
@neutrinog yes, the timestamp looks good. And yes a hidden folder is fine.

**Comment by da1nerd** [comment]
Builds for this are here https://github.com/unfoldingWord/translationCore/actions/runs/90787427

**Comment by cckozie** [comment]
@birchamp - 
Issue 1:Under "Specs" in the first comment of this issue, both a numeric designator for multiple versions of the same project, in addition to a timestamp, are listed as requirements. If you did authorize the elimination of the numeric designator, please strike out that requirement in the list.

Issue 2: In regard to the fourth requirement: If a user moves or copies the project back to the projects folder and then selects it without removing the timestamp from the project name, the critical error screen is displayed after the Your project has been named alert. Should this be handled properly here or written up as a new issue.

**Comment by da1nerd** [comment]
@cckozie I thought importing was going to be handled in a different issue?

**Comment by elsylambert** [comment]
Archiving Project looks fine in 2.2.0 (dd79140). archive folder is hidden from the user, so Issue 2 should be handled with re-importing issue.
