### ISSUE TITLE
Add Refresh button when an error occurs

### ISSUE THREAD

**Issue by EllDoubleYew** [unfoldingWord/translationCore#98]
As a translation checker I want the loading modal to go away when an error occurs so that I can try and load a different app or project to remedy the issue.
- [ ] Add refresh to red error alerts.
- [ ] Don't add to silent errors, but will address those later.

This is especially a problem when you factor in persistence. Certain errors will continue happening every time you open the app and there is no way to get rid of the loading modal to fix them. The temporary workaround is to re-enable the tutorial which bypasses the persistence but it would be better if an error just caused the loading modal to go away.

**Comment by klappy** [comment]
Link for a forced refresh?
