### ISSUE TITLE
Stepper

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#980]
- [ ] Home button on the left
  - [ ] Is always black on white, except when in the Home screen, then it is blue.
- [ ] The current step 
  - [ ] icon is always blue
  - [ ] the category text is bold and black
- [ ] When a step is complete
  - [ ] the icon becomes a blue checkmark
  - [ ] the category (e.g. "User", "Project", "Tool") turns blue
  - [ ] the selection appears below the category, in gray
  - [ ] completed steps become links (you can go back to completed steps, but you cannot skip steps)
- [ ] the line to the right of the completed category turns blue. 
- [ ] inactive steps
  - [ ] icon is grayed out
  - [ ] the category text is grayed out
  - [ ] inactive steps are not links

**Comment by Thajny** [comment]
![steppers](https://cloud.githubusercontent.com/assets/21183377/24563669/e4bdef0a-1614-11e7-80a0-0f05749f00f9.png)

**Comment by Thajny** [comment]
![steppers](https://cloud.githubusercontent.com/assets/21183377/24724003/32bd6ad4-1a0f-11e7-8d73-6a54e7eca167.png)

**Comment by mannycolon** [comment]
http://www.material-ui.com/#/components/stepper

**Comment by benjore** [comment]
- [ ] The line changing to blue is optional at this point

**Comment by klappy** [comment]
- [ ] Add a previous and next button to simulate progress

**Comment by RoyalSix** [comment]
@mannycolon is there a PR out for this?

**Comment by mannycolon** [comment]
@RoyalSix this is already in but it can't be tested until we start implementing the home screen.

**Comment by EllDoubleYew** [comment]
@benjore Should we leave this in review until we have a framework for the homescreen? Or technically is this done since we cant review it yet?

**Comment by mannycolon** [comment]
@elldoubleyew it has to stay in review until it can be reviewed.

**Comment by Thajny** [comment]
![steppers](https://user-images.githubusercontent.com/21183377/27196810-931d9954-51d1-11e7-8ee7-8c8eebf33e7a.png)
